### PR TITLE
 Fix [has_attack]type= cause infinite recursion when called from [damage_type] which concerns the filtered attack.

### PR DESCRIPTION
**Pull request by newfrenchy83**
When for example we have [damage_type][filter_self][has_attack]type=pierce applied to one or any pierce type attack and the unit does not have an unaffected pierce attack, the change in type triggers an infinite recursion.

this PR fixes the problem in the same way as for [filter_weapon]

### CODE REVIEW

**Comment by stevecotton** [comment]
Although the new test is good, I'm not in favor of special-casing `damage_type` unless there's a specific reason why that one behaves differently. If I understand the bug report correctly, many different filters in `[has_attack]` could trigger the bug.

**Comment by newfrenchy83** [comment]
> Although the new test is good, I'm not in favor of special-casing `damage_type` unless there's a specific reason why that one behaves differently. If I understand the bug report correctly, many different filters in `[has_attack]` could trigger the bug.

this problem of infinite recursion presents itself when has_attack is used to condition the activity of a [damage_type] with the possession by the unit of an attack whose type matches but which is the same one which will be modified by [damage_type] .

the only solution left for me is to forgo https://github.com/wesnoth/wesnoth/pull/8936 and also remove replacement_type from [damage_type]

**Comment by stevecotton** [comment]
Is it specific to `[damage_type]`? Which of the following two statements is true:
* Infinite recursion only occurs with `[damage_type]`
* Infinite recursion can occur with `special_id_active`, `special_type_active`, and `formula` filters too

My concern is that we'll end up with patches scattered across the codebase, instead of looking at the root of the problem and fixing it in the design.

**Comment by newfrenchy83** [comment]
> Is it specific to `[damage_type]`? Which of the following two statements is true:
> 
>     * Infinite recursion only occurs with `[damage_type]`
> 
>     * Infinite recursion can occur with `special_id_active`, `special_type_active`, and `formula` filters too
> 
> 
> My concern is that we'll end up with patches scattered across the codebase, instead of looking at the root of the problem and fixing it in the design.

if [has_attack]type= is the filter,the issue is then specific to [damage_type] but infinite recursion occur also with special_id_active if weapon special filter itself(or filter special opponent who filter weapon special also).

But I don't see a general solution to prevent infinite recursion.

**Comment by newfrenchy83** [comment]
enough, I'm fed up I'm abandoning this request, there is no satisfactory solution

**Comment by newfrenchy83** [comment]
@stevecotton it is work, it's  time.

**Comment by stevecotton** [comment]
For 1.18, as the only behavior change is from (crash) to (no crash) then I think it's okay to merge #8945.

For the master branch, my feeling is that we should stop adding new functionality to abilities and weapon specials until we have a general solution to the problems with recursion.

**Comment by newfrenchy83** [comment]
> For 1.18, as the only behavior change is from (crash) to (no crash) then I think it's okay to merge #8945.
> 
> For the master branch, my feeling is that we should stop adding new functionality to abilities and weapon specials until we have a general solution to the problems with recursion.

I fear wkat i must close https://github.com/wesnoth/wesnoth/pull/8936 pr and remove replacement_type attrbute of [damage_type] for résolve this issue in long term

**Comment by newfrenchy83** [comment]
i think to have find a generic solution

**Pull request closed without merging**
