### PR TITLE
filter attribute integrates the tag_name check to verify that the attribute sought can be used there

### PR DESCRIPTION
**Pull request by newfrenchy83**
resolve https://github.com/wesnoth/wesnoth/issues/7992 issue

### CODE REVIEW

**Comment by stevecotton** [comment]
The documentation is welcome, but what #7992 needs is a different type of documentation, and I'm not sure how to explain it. It needs design-level documentation, rather than implementation-level documentation.

**Comment by newfrenchy83** [comment]
> The documentation is welcome, but what #7992 needs is a different type of documentation, and I'm not sure how to explain it. It needs design-level documentation, rather than implementation-level documentation.

Wikia?

**Comment by newfrenchy83** [comment]
> The documentation is welcome, but what #7992 needs is a different type of documentation, and I'm not sure how to explain it. It needs design-level documentation, rather than implementation-level documentation.

and where do I put this documentation?

**Comment by Pentarctagon** [comment]
Do we have design level documentation for much else? What would an existing example be?

**Comment by newfrenchy83** [comment]
> Do we have design level documentation for much else? What would an existing example be?

This is what I don't understand here, I already put the documentation for the implementation and apart from https://wiki.wesnoth.org/StandardAbilityFilter, I don't see what else I can do.

If there is nothing else to add I suggest to merge this PR close the issue and move on to the next step. I followed almost all of @soliton-  requests- but now it becomes nitpicking.

**Comment by Pentarctagon** [comment]
Well, this PR doesn't make the functional changes that Soliton asked for in the issue either.

**Comment by newfrenchy83** [comment]
> Well, this PR doesn't make the functional changes that Soliton asked for in the issue either.

I don't know what changes remain to make, what @soliton- explain that to me then!

**Comment by Pentarctagon** [comment]
I did though: https://github.com/wesnoth/wesnoth/issues/7992#issuecomment-2356618363

**Comment by newfrenchy83** [comment]
> I did though: [#7992 (comment)](https://github.com/wesnoth/wesnoth/issues/7992#issuecomment-2356618363)

i added this https://github.com/wesnoth/wesnoth/pull/9361/commits/9993f6c47739403ec5a103a168e164c0b59c8080

**Comment by newfrenchy83** [comment]
> I did though: [#7992 (comment)](https://github.com/wesnoth/wesnoth/issues/7992#issuecomment-2356618363)

https://github.com/wesnoth/wesnoth/pull/9361/commits/94ad2517edc5894a9f4112cdf22ce01e4ceb8656 reply to that?

**Comment by Pentarctagon** [comment]
I will just do it myself, as I said in the issue. I have an idea of how I'd like it to be done and at this point it's probably faster and less stressful for everyone if I just do it myself.

**Comment by newfrenchy83** [comment]
> I will just do it myself, as I said in the issue. I have an idea of how I'd like it to be done and at this point it's probably faster and less stressful for everyone if I just do it myself.

ok, but i let this PR open.

**Comment by newfrenchy83** [comment]
@soliton- could you look at PAR which meets one of your requirements please?

**Comment by Pentarctagon** [comment]
Thinking about it a bit more, I don't understand why it's wrong to check whether `cfg` has an attribute or not. If the filter is checking for an attribute and the ability config doesn't have that attribute (and has no default) then stopping there and returning false seems like a perfectly normal thing to do.

**Comment by Pentarctagon** [comment]
I'll go ahead and merge this tomorrow, barring any additional comments.

**Comment by soliton-** [comment]
> (and has no default)

Yet the exact example linked in #7992 is still checking `cfg` without a default. I'm not going to try to decipher the new comment since it makes no sense for `unsigned_matches_if_present` to work differently from `int_matches_if_present`.

**Comment by Pentarctagon** [comment]
I mean, it doesn't really make sense for `unsigned_matches_if_present` to exist in the first place.

**Comment by soliton-** [comment]
Fixing it or removing it is fine with me.

**Comment by Pentarctagon** [comment]
I will remove it then.

**Pull request merged**
