### PR TITLE
Add a composite hero/leader ellipse, closes #8011 closes #6258

### LINKED ISSUE #6258: Add a composite hero/leader ellipse
If an add-on author tries to use `{IS_HERO}` or the ellipse `misc/ellipse-hero` for a unit with `canrecruit=yes`, they end up getting messages like `error display: could not open image 'misc/ellipse-hero-leader-top.png'`. (I have had this happen to me before myself.) Technically this is Wesnoth just doing what it's told, so there's no need to change any code here, but it *would* be useful to at least add a composite ellipse with that path for this particular case, at least IMO.

### LINKED ISSUE #8011: Using {IS_EXPENDABLE_LEADER} causes image error
I used `{IS_EXPENDABLE_LEADER}` in a scenario,
and got this:

```txt
20231103 15:46:16 error image: could not open image 'misc/ellipse-hero-leader-top.png'
20231103 15:46:16 error image: could not open image 'misc/ellipse-hero-leader-bottom.png'
```

### PR DESCRIPTION
**Pull request by ProditorMagnus**
Add a composite hero/leader ellipse, closes #8011 closes #6258

### CODE REVIEW

**Comment by ProditorMagnus** [comment]
Not sure these are up to date files, got them from https://github.com/cooljeanius/Flight_Freedom/commit/b9271d1220aacfbde56887ee601017b09643ec6e

**Comment by ProditorMagnus** [comment]
@cooljeanius @Toranks @knyghtmare as the people involved in this issue workarounds

**Comment by cooljeanius** [comment]
> Not sure these are up to date files, got them from [cooljeanius/Flight_Freedom@b9271d1](https://github.com/cooljeanius/Flight_Freedom/commit/b9271d1220aacfbde56887ee601017b09643ec6e)

...and I just got them from elsewhere in mainline in the first place. I think their copyright info can just be copied over from where they're already listed in a different directory?

**Comment by ProditorMagnus** [comment]
CI / copyright (pull_request) Successful in 48s

since checksum is ok, those have to be correct images

**Comment by ProditorMagnus** [comment]
They just waited too long before merge.

**Comment by gfgtdf** [comment]
I'm still unsure what the usecase for IS_HERO with canrecruit=yes is, aren't carecruit units by default "heroes"?

Actually thinking about it more: Is there a reccomendation when IS_HERO should be used? I'd assume its for unit that aren't allowed to die and have special handling in the scenarios code, but i don't see that documented anywhere.

**Comment by CelticMinstrel** [comment]
> I'm still unsure what the usecase for IS_HERO with canrecruit=yes is, aren't carecruit units by default "heroes"?

I'm not sure of the use-case either, but the ellipse path is dynamically constructed from several conditions, so I think it makes sense to want all possible combinations of those conditions to have a valid ellipse. If you _do_ have a reason to make a character that's both a leader and a hero, that shouldn't cause them to lose their ellipse.

**Comment by ProditorMagnus** [comment]
Another partial solution is changing
```
        [effect]
            apply_to=ellipse
            ellipse="misc/ellipse-hero"
        [/effect]
```
To filter for canrecruit=no.

**Comment by CelticMinstrel** [comment]
The meaning of "hero" also isn't really defined by the engine, so there could be some campaign where it's _not_ expected that every leader is also a hero. Even some of the mainline campaigns occasionally make the leader expendable, don't they?

So, while the filter change could indeed solve the issue, I don't really have an issue with adding a new ellipse.

**Comment by cooljeanius** [comment]
> The meaning of "hero" also isn't really defined by the engine

Also, the ambiguous meaning that it does kind of have has kind of changed over time; I'd almost forgotten that this was one of the checkboxes in #6403 until #8375 closed #6258 for us...

**Pull request closed without merging**
