### PR TITLE
THoT S6: Let a Scout be the first to smell Ratheln's cooking.

### PR DESCRIPTION
**Pull request by jostephd**

### CODE REVIEW

**Comment by jostephd** [comment]
The hut at 19,10 is now highlighted with gohere.png. Is that not clear enough?

What would you have the po hint say? I don't use translations but I expect the translated text not to omit things from the source text.

**Comment by sevu** [comment]
I forgot about this change, is yes it's clear.
I mentioned the po hint because originally the english version mentioned that the hut is at the road, while the German said it's over there, wherever that would be.
Free translations are usually a lot better than the ones which stay very close to the original, sometimes however it is not obvious that that changed the sense.

**Comment by sevu** [comment]
Actually, after all these changes, we would be free to change the triggering for the mage event, like it could now only happen if the unit comes close to the location.

And thanks a lot for all these changes.

**Comment by jostephd** [comment]
You're very welcome. I suppose it makes sense to tighten the trigger conditions now that we highlight the hut. I took a shot it at, https://github.com/wesnoth/wesnoth/pull/3408

**Pull request merged**
