### PR TITLE
make it safe to dofile("on_event.lua")

### PR DESCRIPTION
**Pull request by vgaming**
make it safe to dofile("on_event.lua")

### CODE REVIEW

**Comment by vgaming** [comment]
This PR is against 1.14. IDK if it'd better go to master branch, leaving that for reviewers to decide.

**Comment by gfgtdf** [comment]
i don't think this works, i didn't test it but it looks to me like for example the following code
```
dofile("on_event.lua")
-- ...
on_event = dofile("on_event.lua")
on_event("prestart", function()
print("Hi")
end)
```

will execute the event handler twice because the on_event.lua is executed twice and the game_events.on_event hander callback registreated twice, which would obviously be worse than before.

I am also not convinved that this should go into 1.14 since it might casue oos and fixes a rather minor issue, Maybe it be better for if in 1.14 it'd just print a warning or erro when executed twiuce but work as before,

**Comment by vgaming** [comment]
@gfgtdf ouch, I forgot to check that part. Indeed, double-executing it would be a problem.
I'll try to write a fix and target "master" instead.

**Comment by vgaming** [comment]
@gfgtdf rebased and fixed the mistake (I think). I'm beginning wary of the change as it grows to be non-trivial. If you'd prefer to keep it simpler, feel free to just close the PR, I woudn't mind. Leaving it up to your tastes.

**Comment by vgaming** [comment]
@gfgtdf I re-considered my approach and made a totally different PR now (force-pushed as I'm sure the new approach is saner).
See the new diff.

**Comment by vgaming** [comment]
@CelticMinstrel regarding Lua-s global namespace -- I think that if we want to support "dofile", some kind of global variable is necessary regardless. The reason for that is that on_event supports priorities, and we need to store the array of events _somewhere_.
Also, only uses the minimum amount of global variables needed for it to work. And not under short "hot" names. This goes in line with how global variables are recommended to be used in general.

Regarding `dofile` -- I have no strong opinions. I just saw in an IRC discussion that it can be a problem, so I decided to make a PR. If the opinion on `dofile` changes, I could re-think the need for this PR.
Then again, to be honest, I don't see any problem with the new approach (it only brings safety, modulo one global variable `core_on_event`).

**Comment by gfgtdf** [comment]
@CelticMinstrel that's similar to what i thought when i first implemented on_event, but now i really cannot think of any cases where people would really want the dofile behviour on that file or any case where people would use dofile over require on that file except by accident. I also know how annyoing it is if your another addon is incompatible with yours simply because it has mistakes like that in its code that you cannot fix from your side, so i dedecided in favour of this change. I also think global variables are not really a problem as long their names are unique enough so that people will not use them accidently. We could also put that variable somehere in wesnoth.x, i don't really have an opinion on that part.

**Comment by CelticMinstrel** [comment]
We should just remove on_event.lua and move the function it contains into core.lua (probably as something like `wesnoth.hooks.on_event`). Then there won't be any need for this global variable. (I might've even done this already, actually? Either on master or on that branch that has an open PR - lua_reorg if I recall correctly.)

Also, I'm pretty sure it's ill-advised to use dofile on most of the other files in the main Lua directory, so giving `on_event` special treatment is a little silly.

**Comment by vgaming** [comment]
I guess if we want to change anything here, we need something constructive and/or a PR..

**Comment by CelticMinstrel** [comment]
It'll probably end up in my Lua API reorganization PR eventually.

**Pull request merged**
