### PR TITLE
Demote Dawarf to level 0

### PR DESCRIPTION
**Pull request by Gothyoba**
This unit far too weak for a level 1, with only 22HP, relatively terrain defenses and resistances and a only 6x2 meele attack. I know it's only a joke unit, but I'd still like it if the stats made sense.

I propose the following changes:

-Decrease level from 1 to 0.
-Decrease XP from 50 to 25 so it makes more sense with the new level.
-Reduce gold from 17 to 12 like in Venomous Sands. They aren't recruited in-game, but I think it's still good to have a cost that is sensible for its level.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
How does loss of zone of control affect the scenario it appears in?

**Comment by ForestDragon-wesnoth** [comment]
> How does loss of zone of control affect the scenario it appears in?

The unit is encountered in a 1-tile wide cave if I remember correctly, so it won't fundamentally change the fight.

**Comment by Gothyoba** [comment]
Not one tile wide but quite tight. And the unit is a minor easter egg so it shouldn't make much of a difference. I will be adding a changelog entry so please don't merge in the meantime.

**Comment by Gothyoba** [comment]
A changelog entry has been added.

**Comment by Gothyoba** [comment]
@Dalas121 I think you need to review this, and possibly some other people I’m not sure of.

**Review by Dalas121 — APPROVED** [review]

**Review by knyghtmare — APPROVED** [review]

**Pull request merged**
