### PR TITLE
Add const to some functions

### PR DESCRIPTION
**Pull request by rikardfalkeborn**

### CODE REVIEW

**Comment by rikardfalkeborn** [comment]
There are more places where const could be added, but I figured I start smallish to make it simpler to review.

**Comment by CelticMinstrel** [comment]
Looks good. Provided the Travis build passes, this could be merged; or if you want to add more const in an additional commit, feel free to.

If you want, you could also add a commit putting your name in the credits (under "Miscellaneous Contributors"). If you do, please add "[ci skip]" on a line by itself to the commit message.

**Comment by Vultraz** [comment]
Let us know when you're done and we'll merge.

**Comment by rikardfalkeborn** [comment]
I'm done now.

**Pull request merged**
