### PR TITLE
Fix compiler warnings

### PR DESCRIPTION
**Pull request by GregoryLundberg**
Use a more meaningful variable name and make the usage more clear while we're snubbing the compiler warnings.

### CODE REVIEW

**Comment by GregoryLundberg** [comment]
With this change I get a clean make with no errors and the only warnings being the deprecated header messages from upstream (Boost) which we can't fix.

**Comment by GregoryLundberg** [comment]
Probably better but too much thinking for me. I can see what I did plainly fixes it with the intention of the authors and doesn't change logic or operation. So I can confidently make the change as I did.

Changing to utils::join() means operational changes which I would want to test before issuing a PR and I have no idea what this code does, or how to test it, to be sure I got it right.

That said, it does look better to use the existing function. So I'll try and someone wiser and more experience can either code-read or test ...

**Comment by GregoryLundberg** [comment]
There you go.

**Comment by GregoryLundberg** [comment]
OK, compiles clean and by my code-read looks functionally the same. If you want I can compress it to a single diff.

**Comment by CelticMinstrel** [comment]
I'll accept it as-is. In fact I've already merged it into my local copy and am applying a few other cleanups to this section of code (not really related to the PR).

**Comment by GregoryLundberg** [comment]
I replaced the patch a while ago. Spotted a missing part and pushed a replacement. Won't effect compiles. I missed line 1208 (original) and added it to line 1194 (new): the `<< "[/"` was what I originally omitted. I should have proof-read the patch set before uploading it. It was sorta obvious once I did. Should not really effect your local copy and you'll merge from here, so it's not a big deal.

**Comment by CelticMinstrel** [comment]
Given that the commit hashes match between here and #707, I'm pretty sure I got the fixed version, but thanks for the warning.

**Comment by GregoryLundberg** [comment]
Question: since you did that PR, should I close this one? Or will you? Or does github figure it out and close this when you merge yours?

**Comment by CelticMinstrel** [comment]
I think github should figure it out, but you're free to close it earlier if you prefer.

**Pull request closed without merging**
