### PR TITLE
typo in log.hpp

### PR DESCRIPTION
**Pull request by ScegfOd**
fixed a typo:
ourput -> output

### CODE REVIEW

**Comment by Wedge009** [comment]
Thanks for pointing out the typo. In the future, please rebase against master so that you don't have the merge commit included. I'll close this now as I have corrected the spelling error directly.

**Comment by CelticMinstrel** [comment]
I wonder if someone should run a spell/grammar check on the comments... there are tons of errors that I've noticed and mostly not bothered fixing.

**Comment by Wedge009** [comment]
I've noticed some as well - is there a tool that does this easily in Linux?fs

**Comment by CelticMinstrel** [comment]
I'm not sure. I think my text editor can check spelling only in the comments, and possibly XCode too, but I'm not sure if I want to run an interactive spell check across the entire codebase... that could take forever... >_>

**Comment by Wedge009** [comment]
I think that's the catch - having something that does this automatically... as you say, doing this manually will be time-consuming. Maybe will just have to correct the errors as we find them. :/

**Pull request closed without merging**
