### PR TITLE
move multiplayer macros to proper folder

### LINKED ISSUE #4698: Macros QUICK_4MP_LEADERS and TURNS_OVER_ADVANTAGE are missing
### Game and System Information
 - 1.15.2, but observed from 1.12 times as well

### Describe the bug
wesnoth -p fails when input contains QUICK_4MP_LEADERS orTURNS_OVER_ADVANTAGE
### To Reproduce
Have addonIn/_main.cfg containing `{QUICK_4MP_LEADERS}`
Run `./wesnoth -p addonIn addonOut`

### Expected behavior
QUICK_4MP_LEADERS is expanded

### Actual behavior
```
Battle for Wesnoth v1.15.2
Started on Sat Jan 11 01:44:44 2020

Automatically found a possible data directory at C:\Users\USER\games\Battle for Wesnoth 1.15.2
added 1 defines.
preprocessing common macros from 'data/core' ...
acquired 1732 'data/core' defines.
preprocessing specified resource: addonIn ...
20200111 01:44:44 error preprocessor: Macro/file 'QUICK_4MP_LEADERS' is missing
at C:/Users/Ravana/games/Battle:1
    included from Wesnoth:for
    included from <unknown>:1.15.2/addonIn/_main.cfg
```
### Additional context
This stacktrace seems strange

### LINKED ISSUE #7471: Macro/file 'RANDOM_SIDE' is missing
### Game and System Information

- **Version:**Battle for Wesnoth v1.16.6 x86_64
- **Downloaded from:**Steam
- **OS:**windows

### Description of the bug

Probably the same reason as #4698, but created as separate issue since it is now happening with stable release.

```
"C:\Program Files (x86)\Python37-32\python.exe" C:/Users/Ravana/PycharmProjects/WML_tree_tools/py_files/preprocess_addon.py
Running ['C:\\Program Files (x86)\\Steam\\steamapps\\common\\wesnoth\\wesnoth.exe', '--data-dir', 'C:\\Program Files (x86)\\Steam\\steamapps\\common\\wesnoth', '--userdata-dir', 'C:\\Users\\Ravana\\Documents\\My Games\\Wesnoth1.16', '--preprocess-defines', 'MULTIPLAYER', '-p', 'C:\\Users\\Ravana\\Documents\\My Games\\Wesnoth1.16\\data\\add-ons\\Era_of_Magic', '..\\preprocessed_addon16\\Era_of_Magic', '--wnoconsole']

Battle for Wesnoth v1.16.6 x86_64
Started on Wed Mar 22 23:14:13 2023

Automatically found a possible data directory at C:\Program Files (x86)\Steam\steamapps\common\wesnoth
Overriding data directory with C:\Program Files (x86)\Steam\steamapps\common\wesnoth
added 2 defines.
preprocessing common macros from 'data/core' ...
acquired 1778 'data/core' defines.
preprocessing specified resource: C:\Users\Ravana\Documents\My Games\Wesnoth1.16\data\add-ons\Era_of_Magic ...
20230322 23:14:13 error preprocessor: Macro/file 'RANDOM_SIDE' is missing
at ~add-ons/Era_of_Magic/EoMa_eras.cfg:10
    included from ~add-ons/Era_of_Magic/_main.cfg:37

```

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ProditorMagnus**
closes #4698 closes #7471

### CODE REVIEW

**Comment by Pentarctagon** [comment]
Makes sense to me.

**Comment by ProditorMagnus** [comment]
I see #define ERA_HEROES is still there, would be good to move that too.

**Comment by Pentarctagon** [comment]
Anything else to do, or is it fine if I merge this?

**Comment by ProditorMagnus** [comment]
Ready for merge.

**Pull request merged**
