### PR TITLE
Add [replace_map] file= which will load the specified map at runtime

### PR DESCRIPTION
**Pull request by Vultraz**
This has an advantage over the map key behavior, where the contents of the map
file were preprocessed and written to savefiles.

### CODE REVIEW

**Comment by gfgtdf** [comment]
1) This doesn't comple (see the travis report)
2) Currrently we have map_data={MAPFILE}/map=MAPFILE in [scenario], and map={MAPFILE}/file=MAPFILE in [replace_map] maybe we could get some more consistency here by using map_data/map= for both?
3) This looks like its likeley to casue OOS if people have different versions of the MAPFIL, any idea whta to do about it?

**Comment by Vultraz** [comment]
I didn't know we had a map=MAPFILE key in [scenario]. I have no problem with consistency, but how would we deprecate the {MAPFILE} usage of map= in [replace_map] (and change it to map_data=) easily?

Wouldn't OOS happen with different versions of the map even if it's cached beforehand?

**Comment by gfgtdf** [comment]
> I didn't know we had a map=MAPFILE key in [scenario]. 

Y, i also only noticed that from looking at the scenario loading code. Hmm maybe check it its afile

> I have no problem with consistency, but how would we deprecate the {MAPFILE} usage of map= in replace_map easily?

Hmm maybe we coudl parse it as a map if it isnt found as a file for that time? Another option is a change map= in [scenario] to someting like map_file= i think we can also so that if map? in [screnario] is undocumented.

> Wouldn't OOS happen with different versions of the map even if it's cached beforehand?

No, the [scenario] with all its contents it delivered to all clients of a mp game?

**Comment by Vultraz** [comment]
>> Hmm maybe we coudl parse it as a map if it isnt found as a file for that time? Another option is a change map= in [scenario] to someting like map_file= i think we can also so that if map? in [screnario] is undocumented.

So map and map_file in replace_map and map_data and map_file in scenario?

>> No, the [scenario] with all its contents it delivered to all clients of a mp game?
In that case, let's just leave it up to the UMC authors to use this responsibly.

**Comment by Vultraz** [comment]
@gfgtdf ok, so I updated the PR. Now we have [[scenario]] map_data and map_file and [[replace_map]] map= and map_file=

**Comment by gfgtdf** [comment]
Hmm i'm still worried about point 3 (OOS in mp games) and i think it woudl be better if there was just some read_file function in wml/lua so that one could dynamically load the map data to a variable and then use replace_map with map=$variablename. The advantage is that people have teh option to make it mp save with using [sync_variable] or similar.

**Comment by Vultraz** [comment]
As @CelticMinstrel mentioned, such a function would be unsafe and easy to abuse.

**Comment by Vultraz** [comment]
According to @shikadilord, a read_file function could actually be made safe. If someone else wants to work on it, we can re-implement this PR with that, but for now I'll merge it.

**Pull request merged**
