### PR TITLE
Time of day variants

### PR DESCRIPTION
**Pull request by doofus-01**
The lights are on at night, but off during the day.
This is currently for merfolk villages, but eventually could be for other villages too, and other things like the aquatic castle towers.

### CODE REVIEW

**Comment by Vultraz** [comment]
Er, you appear to have some commits from a previous PR in here?

**Comment by doofus-01** [comment]
Yes, I tried to get rid of them, but there they are.  I don't like git.

**Comment by Vultraz** [comment]
Ok, so it's just 6c8cc88 that pertain to this PR?

**Comment by doofus-01** [comment]
Right.

**Comment by Vultraz** [comment]
Pushed manually (c7040d6bb0ca).

**Pull request closed without merging**
