### PR TITLE
Porting WML tags to Lua (part 2)

### PR DESCRIPTION
**Pull request by CelticMinstrel**
Continuation of #881.

This is a branch dedicated to porting WML tags to Lua, mainly focusing on ones that are nominally implemented in Lua but actually just defer to an API call that does all of the work.

It's not ready for merge yet, but could use a lot of testing for each affected tag to ensure that things still work as they should.

Things to be tested:
* [ ] kill
* [x] scroll
* [x] music
* [x] volume

Tags to evaluate:
* [x] music
* [ ] set_menu_item
* [ ] time_area
* [ ] replace_schedule

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
So, this is now ready for testing and probably merge, and I'd also welcome comments on the Lua API underlying the four tags listed as "to evaluate" in the opening post.

**Comment by Pentarctagon** [comment]
This might be out of scope, but:

- There's [bug 24231](https://gna.org/bugs/?24231).
- [This](https://gna.org/bugs/?24739) feature request for a [music]-specific volume key.
- Also, if possible, it would be nice to have an automatically stored variable (or some other way) to get the name of the currently playing song.

**Comment by CelticMinstrel** [comment]
I think this Lua API does allow getting the name of the currently playing song. I haven't made a WML tag to do that though.

Not sure bug 24231 is easily-fixable, given the way shuffle works. Shuffle just means "pick a random song once this one is finished playing" - the wiki's description of it is wrong, as it applies per-song, not to the whole playlist.

**Comment by CelticMinstrel** [comment]
If someone could test `[music]` and `[volume]`, preferably in some depth, that would be great. Testing for `[kill]` would also be welcome; if I recall correctly, I only verified its basic functionality. I think there's no further testing required for `[scroll]` though.

Also - should [kill] play the victory animation (if any) when a killer unit is supplied? Should you be allowed to select the weapon used for the animations?

Comments on the niceness of the API underlying [music] would also be welcome. I'll summarize it here for those who can't easily glean it from the source:

There is a new table, `wesnoth.playlist`, which gives direct access to the current playlist. It is an array, and supports the length operator and integer indices. There are also a few other things in it:

* `wesnoth.playlist.current` - The currently-playing track. This can be a track not on the playlist; the way to detect that would be `wesnoth.playlist.once`, as "play_once" tracks are not added to the playlist.
* `wesnoth.playlist.current_i` - The index of the currently-playing track on the playlist. If the currently-playing track is not on the playlist, this is currently equal to `#wenoth.playlist + 1`; otherwise, `wesnoth.playlist[wesnoth.playlist.current_i] == wesnoth.playlist.current`.
* `wesnoth.playlist.volume` - The current relative volume as set by `[volume]`.
* `wesnoth.playlist.play()` - Pass the name of a track, and it plays it once.
* `wesnoth.playlist.add()` - Pass the name of a track to add it to the playlist. In addition to the track name, you can pass ms_before, ms_after, and immediate.
* `wesnoth.playlist.clear()` - Empties the playlist.
* `wesnoth.playlist.commit()` - Commits changes made with add().

Music tracks are a userdata providing access to the following keys: append, shuffle, immediate, once, ms_before, ms_after, id, title, path. The parameter shuffle, once, ms_before, and ms_after are mutable. The id parameter is what's passed to `[music]` as name; I may rename it to match that. I'm not sure if the `path` parameter is helpful or even desired, as it indicates the resolved path to the music file, so I may remove it.

**Comment by Pentarctagon** [comment]
```
[music]
  name=victory.ogg
  append=no
[/music]
[music]
  name=defeat.ogg
  append=yes
[/music]
```

results in:

> 20170407 20:48:39 error scripting/lua: lua/wml-tags.lua:272: attempt to perform bitwise operation on a boolean value (field 'append')
> stack traceback:
> 	lua/wml-tags.lua:272: in local 'cmd'
> 	lua/wml-utils.lua:145: in field 'handle_event_commands'
> 	lua/wml-flow.lua:20: in local 'cmd'
> 	lua/wml-utils.lua:145: in field 'handle_event_commands'
> 	lua/wml-flow.lua:138: in local 'cmd'
> 	lua/wml-utils.lua:145: in field 'handle_event_commands'
> 	lua/wml-flow.lua:20: in local 'cmd'
> 	lua/wml-utils.lua:145: in field 'handle_event_commands'
> 	lua/wml-flow.lua:6: in function <lua/wml-flow.lua:5>

**Comment by Pentarctagon** [comment]
Now I get this:
```
20170408 12:40:56 error scripting/lua: lua/wml-tags.lua:274: attempt to index a userdata value (field 'current')
stack traceback:
	lua/wml-tags.lua:274: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml/message.lua:409: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml/message.lua:409: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml-flow.lua:52: in local 'cmd'
	lua/wml-utils.lua:145: in field 'handle_event_commands'
	lua/wml-flow.lua:6: in function <lua/wml-flow.lua:5>
```

**Comment by CelticMinstrel** [comment]
In addition to the fix, I decided to remove the "path" attribute from tracks and rename "id" to "name" to match the WML.

**Comment by Pentarctagon** [comment]
So, not meaning to come off as an ass or anything, but how much did you test this?  Because now I don't get any lua errors, but it's still basically non-functional.  This:
```
[event]
  name="turn 1"
  
  [music]
    name="victory.ogg"
    append="no"
  [/music]
[/event]
```
does nothing.  victory.ogg doesn't play at all.  Changing it to:
```
[event]
  name="turn 1"
  
  [music]
    name="victory.ogg"
    play_once="yes"
  [/music]
[/event]
```
works, in as much as it does actually play victory.ogg once, but then the playlist that was playing before victory.ogg doesn't resume after victory.ogg finishes.

**Comment by Pentarctagon** [comment]
Existing functionality seems to mostly work now, the only problem remaining being that playing a song with `play_once=yes` doesn't play the song anymore - it just plays the next song in the existing playlist.  I haven't tried out anything new (playlist volume, currently playing song, directly using the lua api) yet.

**Comment by CelticMinstrel** [comment]
Hm, I thought I remembered testing `wesnoth.playlist.play()`... oh well, I'll take a look at it again soon.

**Comment by CelticMinstrel** [comment]
I just tested `wesnoth.playlist.play()` again and it definitely plays the passed track, not some other track on the playlist.

**Comment by Pentarctagon** [comment]
This code:
[event]
  name="turn 1"
  
  [while]
    [true][/true]
    [do]
      
      [message]
        [option]
			    description="UnderOurSpell.ogg"
			    image="ball-blue.png"
			    label="27."
			    [command]
				    [music]
					    append=no
					    immediate=yes
					    name="UnderOurSpell.ogg"
					    play_once=yes
				    [/music]
			    [/command]
        [/option]
      [/message]
      
    [/do]
  [/while]
[/event]
```
still results in "UnderOurSpell.ogg" not playing - instead it just picks the next song in the current playlist.

**Comment by CelticMinstrel** [comment]
Hmm, this is strange. If you execute `wesnoth.playlist.play "UnderOurSpell.ogg"` in the Lua console (or with the `;lua` command), does that work? That's how I tested, and it did work for me; and the `[music]` tag does exactly that if the `play_once` key is present.

Mind you, I was testing with built-in tracks only, maybe there's some weird behaviour if it fails to resolve the track?

**Comment by Pentarctagon** [comment]
Err, right, I guess you wouldn't have a song with that name.  It is not unresolved for me though, and the current implementation of [music] in master plays it without problem.  Changing the above to "victory.ogg" gives the same result, in any case.

**Comment by Pentarctagon** [comment]
To follow up on this a bit: using `wesnoth.playlist.play` on the lua console is the only way this seems to work.  Neither invoking it from [music] or using `wesnoth.playlist.play` from inside [lua] works.  Example code:

```
[event]
  name="turn 1"
  
  {VARIABLE test 1}
  [while]
    [variable]
      name=test
      numerical_equals=1
    [/variable]
    [do]
      
      [message]
        [option]
          description="end loop"
          label="1."
          [command]
            {CLEAR_VARIABLE test}
          [/command]
        [/option]
        [option]
          description="victory.ogg [music]"
          label="2."
          [command]
            [music]
              name="victory.ogg"
              play_once=yes
            [/music]
          [/command]
        [/option]
        [option]
          description="victory.ogg [lua]"
          label="3."
          [command]
            [lua]
              code=<<
                wesnoth.playlist.play("victory.ogg")
              >>
            [/lua]
          [/command]
        [/option]
      [/message]
      
    [/do]
  [/while]
[/event]
```

**Comment by CelticMinstrel** [comment]
It seems like the problem was probably that the `wesnoth.playlist.commit()`, which is automatically called after any event, was noticing that the track is not on the track list and thus changing it to a new one. This was because the track played with `play` was not properly marked as "play once", which I have fixed. I _think_ this should make everything work properly.

In which case, this could probably be merged now!

Though it might be good to do a little more testing with `[kill]` – I only did some basic testing. And there's also a question of whether to make `[kill]` play a victory animation on the second unit if one is present, though that could be addressed separately in a follow-up commit.

**Comment by Pentarctagon** [comment]
`wesnoth.playlist.current` doesn't quite work.  Trying to set it to a WML variable just gives an error:

> error scripting/lua: [string "..."]:3: bad argument #2 to 'set_variable' (WML table or scalar expected, got userdata)

Calling `tostring()` on it then just gives a hex value.

Code I used:

> [lua]
>   code=<<
>     wesnoth.set_variable("MusicSession.current_song", wesnoth.playlist.current)
>   >>
> [/lua]

**Comment by CelticMinstrel** [comment]
`wesnoth.playlist.current` is a table containing the track information. In this case you probably want `wesnoth.playlist.current.name` or possibly `wesnoth.current.playlist.title`, though title seems not to be filled in on Windows...

**Comment by Pentarctagon** [comment]
In that case, why am I not able to set `wesnoth.playlist.current` to a WML container with `helper.set_variable_array()`?  The below code:

>   [lua]
>     code=<<
>       local test = wesnoth.playlist.current
>       helper.set_variable_array("test", test)
>     >>
>   [/lua]

gives the error:

> error scripting/lua: lua/helper.lua:288: bad argument #1 to 'ipairs' (table expected, got music track)

**Comment by CelticMinstrel** [comment]
That would be because it's a userdata, not a config... so that changes to the values in it instantly take effect in the engine.

**Comment by CelticMinstrel** [comment]
Last thing I'm doing is making the Lua API for music a little nicer... there's a couple more things to do on that, then this can be merged.

**Comment by Pentarctagon** [comment]
Going back to shuffle, would it be possible for there to be something like a `shuffle=skip` value, so when the [music] has `shuffle=skip` and `immediate=yes`, it adds the song to the playlist and then chooses a random song from the playlist to play?

**Comment by CelticMinstrel** [comment]
I think that could be done, but I don't really understand why the shuffle and immediate keys would combine in that way to do that. I think you could implement it now in Lua just by calling the `wesnoth.music_list.next()` function, so if you want you could try making a PR to that effect once this is merged, I guess.


I think this is ready to merge... in my brief testing of the Lua API, the only issue I noticed is that `wesnoth.music_list.current` is wrong when the scenario starts - it contains the first track on the playlist, rather than the menu track that's still playing. But I don't think that's an issue in the Lua API implementation...

**Comment by Pentarctagon** [comment]
Alright, I'll use `next()` then.  That function hadn't been mentioned previously.

**Comment by CelticMinstrel** [comment]
Yeah, I didn't mention previously because I added it more recently. I think it is mentioned in the changelog though.

**Comment by Pentarctagon** [comment]
More of a lua question than anything, but is there a way to convert the `wesnoth.music_list.current` userdata to a table, so I can store it into a WML variable?

Also, what's the difference between name and title?  The changelog mentions both are read-only, but that's about it.

**Comment by CelticMinstrel** [comment]
It's a userdata so that it can act as a "proxy", with changes to it taking effect in the engine. For example, if you set the ms_after field, it will use that new value the next time it fades out from that song. But maybe I could add an `.all` field that returns the whole playlist as a config...

As for name vs title, they're exactly the same as in the `[music]` config - name is the relative file path, and title is a user-friendly track title (I think it's currently only used in the editor music list menu; might also be undocumented on the wiki).

**Pull request merged**
