### PR TITLE
Store additional information in the database:

### PR DESCRIPTION
**Pull request by Pentarctagon**
* mp_scenario_addon_id
* mp_scenario_addon_version (host's version)
* mp_era_addon_id
* mp_era_addon_version (host's version)
* active_mod_addon_ids
* active_mod_versions (host's versions)

### CODE REVIEW

**Comment by gfgtdf** [comment]
is INSTANCE_VERSION the wesnoth version of the host ?

**Comment by soliton-** [comment]
https://github.com/wesnoth/wesnoth/blob/987b33565a8dc3e671f667490ed1ad1e6c63dc75/utils/mp-server/table_definitions.sql#L49

**Comment by gfgtdf** [comment]
oh hmm i think we should definitely store the clients versionsm anyve as a range (min version and max version )

**Comment by Pentarctagon** [comment]
A particular client will only ever have a single version though.

**Comment by Pentarctagon** [comment]
These changes have been added on top of #4884 for master.

**Pull request merged**
