### PR TITLE
Luacheck

### PR DESCRIPTION
**Pull request by cooljeanius**
Just creating this for a CI run; not actually ready to merge...

### CODE REVIEW

**Comment by Pentarctagon** [comment]
What's the benefit of using `nebularg/actions-luacheck@v1`?

**Comment by ProditorMagnus** [comment]
Good progress, almost all issues are in wc.

**Comment by cooljeanius** [comment]
> What's the benefit of using `nebularg/actions-luacheck@v1`?

I haven't gotten to that part yet, but for reference, leaving the link to it here: https://github.com/nebularg/actions-luacheck

**Comment by cooljeanius** [comment]
> Good progress, almost all issues are in wc.

Yeah, if it weren't for wc, I'd be able to reduce the `max_line_length=` value from a 5-digit number to a 3-digit one...

**Comment by ProditorMagnus** [comment]
have it as 3 for pr anyways

**Comment by ProditorMagnus** [comment]
I think it makes sense to ignore that 1 long line. https://github.com/LuaLS/lua-language-server/wiki/Annotations#diagnostic

    data/ai/micro_ais/micro_ai_helper.lua:24:13: (W111) setting non-standard global variable str
some are real bugs that need to be fixed.

    data/campaigns/World_Conquest/lua/game_mechanics/_load.lua:6:1: (W131) unused global variable wc2_ability_events
some are real bugs that would be nice to fix, but could be solved by encapsulating the variables in table like wc2 which would in turn be mentioned in luacheck. It would need decision from regular maintainers what to do. It is probably possible to blacklist wc2 from luacheck.

**Comment by cooljeanius** [comment]
> I think it makes sense to ignore that 1 long line. [Wiki: Annotations (diagnostic) (LuaLS/lua-language-server)](https://github.com/LuaLS/lua-language-server/wiki/Annotations#diagnostic)

Instead of using annotations, I'm just using a different config option for it instead in [5381c43](https://github.com/wesnoth/wesnoth/pull/8972/commits/5381c43f7675879a6a98abaa9ee8be9cd40e9b11)...

**Comment by soliton-** [comment]
Lots of unacceptable shell injection in that action. Would be more useful to explain what the goal is so it can be implemented without that action.

**Comment by cooljeanius** [comment]
I think how I ended up with it was that mpeterv/luacheck#198 led me to the lunarmodules fork, and then  lunarmodules/luacheck#57 led me to nebularg's fork... but, it looks like the annotation feature doesn't actually work, so... never mind about that part, at least...

**Comment by cooljeanius** [comment]
@ProditorMagnus should fixes for the new warnings go in this PR, too, or would that be material for a different one?

**Comment by ProditorMagnus** [comment]
Up to @CelticMinstrel

**Comment by CelticMinstrel** [comment]
Is the question whether code fixes should go in the same PR that introduces the check? I think it's fine to do so, but if you prefer to open a separate PR that will get merged first, that's also fine.

**Comment by cooljeanius** [comment]
Actually never mind; I'm no longer pursuing this.

**Pull request closed without merging**
