### PR TITLE
Add the Skeleton Rider line and Death Squire to core

### PR DESCRIPTION
**Pull request by Asheviere**
as discussed with @nemaara

### CODE REVIEW

**Comment by stevecotton** [comment]
While I think it's good to do this during the 1.17 cycle, I also think it should wait until after the period when UMC authors are porting to 1.16.

**Comment by Asheviere** [comment]
Oh yeah that's a good point, probably best to wait until after 1.16.

**Comment by Hejnewar** [comment]
Skeleton Rider - is fine as is - correct price is 14g. 
Bone Knight - is violating RiPLB (-100% arcane resistance) it could also use some buff, as for what that buff could be Im open to suggestions. There is also missig image for its trample attack so that would be nice to fix.
Death Squire - is fine as is - correct price is 39g.

**Comment by knyghtmare** [comment]
I just have one thing to say:
Death Squire with a _sword_...

Would it be possible to replace the sword with an axe? Otherwise, it breaks immersion.
(Skeleton (axe) -> Death Squire (sword) -> Death Knight (battleaxe))

IftU has an axe-wielding variant:
https://raw.githubusercontent.com/project-ethea/Invasion_from_the_Unknown/master/images/units/undead-skeletal/death-baron.png
https://github.com/project-ethea/Invasion_from_the_Unknown/tree/master/images/units/undead-skeletal

**Comment by Wedge009** [comment]
> While I think it's good to do this during the 1.17 cycle, I also think it should wait until after the period when UMC authors are porting to 1.16.

I'm guessing this is the reasoning for the 'postponed' tag - how long to wait until allowing this change through? This change is being done in master after all.

**Comment by CelticMinstrel** [comment]
I think it has probably waited long enough, though it's probably not up to me to have the final say here.

**Comment by knyghtmare** [comment]
> > While I think it's good to do this during the 1.17 cycle, I also think it should wait until after the period when UMC authors are porting to 1.16.
> 
> I'm guessing this is the reasoning for the 'postponed' tag - how long to wait until allowing this change through? This change is being done in master after all.

I think it's just weird that 
Skeleton (level 1) has an axe
Death Squire (level 2) has a sword
Death Knight (level 3) has a battleaxe...

So...it's sort of strange seeing it switch weapons from axe to sword, and sword to axe again. Which is why I recommended adding the IftU variant one (which has an axe).

**Comment by knyghtmare** [comment]
> I think that's largely a graphical issue that could be resolved after merging, though?

There are two things:
1. Merge conflicts
2. Hejnewar's RIPLIB comment was not met with any changes

Thus, I do not think it should be merged yet.

**Comment by CelticMinstrel** [comment]
Or someone else could open a new PR. Heck, I could do it; it's a pretty easy task. If this is considered mergeable (up to @Hejnewar 's comment) and @Asheviere is not around to fix up this PR, I could go ahead and do that.

**Comment by Asheviere** [comment]
I'm around! I could fix this up this weekend.

**Comment by Asheviere** [comment]
I havent really bothered fixing it right after the comments were posted because it was postponed anyway, sorry if that gave the wrong idea.

**Comment by Asheviere** [comment]
ok i fucked the merge part of this up

**Comment by Asheviere** [comment]
ok i should have fixed that mess now

**Comment by CelticMinstrel** [comment]
The 3rd commit there looks wrong - it's adding a Bone Knight file back in Eastern Invasion.

**Comment by Asheviere** [comment]
Yeah you're right... I have not used git enough the past few years

**Comment by CelticMinstrel** [comment]
> Skeleton Rider - is fine as is - correct price is 14g.

Looks like you didn't implement this comment from @Hejnewar?

**Comment by knyghtmare** [comment]
Hmm
Skeleton Rider and Bone Knight: please update attack icon of axe to `attacks/axe-undead.png`
Death Squire: please update sword attack icon to `attacks/sword-orcish.png`

**Comment by Hejnewar** [comment]
Okay, given that nobody else mentioned any ideas for higher statistics of Bone Knight then I would like to request this list of changes to be added. 
Hp changed from 48 to 50.
Melee damage changed from 8 to 10.
Movement points changed from 7 to 8. 
Gold cost changed from 35 to 26.

**Comment by Pentarctagon** [comment]
@nemaara is this something that should still be done?

**Review by knyghtmare — CHANGES_REQUESTED** [review]
List of Pending Changes:

- [ ] Skeleton Rider : primary attack icon update to `attacks/axe-undead.png`
- [ ] Bone Knight: primary attack icon update to `attacks/axe-undead.png`
- [ ] Bone Knight: Filename change to `Skele_Bone_Knight.cfg` (to be in-line with the rest)
- [ ] Bone Knight: Melee attack damage 8 -> 10
- [ ] Bone Knight: HP 48 -> 50
- [ ] Bone Knight: MP 7 -> 8
- [ ] Bone Knight: Cost 35 -> 26
- [ ] Death Squire: attack icon update to `attacks/sword-orcish.png`
- [ ] Death Squire: Filename change to `Skele_Death_Squire.cfg` (to be in-line with the rest)

**Comment by CelticMinstrel** [comment]
Someone also mentioned "skeleton shouldn't advance to death squire" I think… but not sure if that's an actual requested change…

**Comment by knyghtmare** [comment]
> Someone also mentioned "skeleton shouldn't advance to death squire" I think… but not sure if that's an actual requested change…

It doesn't and isn't. However, I would still be a lot more content if the Death Squire wielded an axe and not a sword.

**Comment by nemaara** [comment]
Yes it should be done but the requested changes from Knyght and Hejnewar were not made.

**Pull request merged**
