### PR TITLE
Add leader label to MP Staging/Join screens

### PR DESCRIPTION
**Pull request by Wedge009**
I'm not very familiar with the GUI code, but I'm just trying to help with #2405.

### CODE REVIEW

**Comment by Pentarctagon** [comment]
Before and after images would be good for smaller UI changes by the way.

**Comment by Wedge009** [comment]
mp-before
mp-after

**Comment by Vultraz** [comment]
I don't think this is necessary. It just clutters up the display, IMO.

**Comment by Wedge009** [comment]
Okay, I was just following what was suggested in #2405. You yourself said 'perhaps acceptable' in April 2018. If you've changed your mind, can we close #2405 then?

**Comment by Vultraz** [comment]
Closed that one.

**Comment by Wedge009** [comment]
Closing as not required.

**Pull request closed without merging**
