### PR TITLE
alterntivive min_addon_version fix

### LINKED ISSUE #5004: MP min add-on version logic incorrect.
Relevant comment [here](https://github.com/wesnoth/wesnoth/pull/4884#discussion_r460077853).  Essentially add-ons with no minimum version specified should default to requiring the latest version of the add-ons.

Creating this issue so it will be fixed separately from #4884, since it's an existing bug.

### PR DESCRIPTION
**Pull request by gfgtdf**
Fixes #5004

Now we have the following invariant: addon.min_version is set if and only if addon.required.

### CODE REVIEW

**Comment by Pentarctagon** [comment]
Wouldn't this unset the min_version if the last add-on item being processed isn't required?

**Comment by gfgtdf** [comment]
> Wouldn't this unset the min_version if the last add-on item being processed isn't required?

Hmm i don't think so, the only code that sets calls `addon.min_version` in case of `new_data.required`

**Comment by Pentarctagon** [comment]
I'll go ahead and fix this up and merge an updated PR if there are no issues raised with it.

**Comment by Pentarctagon** [comment]
Re-done in #5998

**Pull request closed without merging**
