### PR TITLE
AOI: Inform the player that Linaera can recruit

### PR DESCRIPTION
**Pull request by sigurdfdragon**
See last two comments in https://github.com/wesnoth/wesnoth/pull/969 conversation for the rational.

### CODE REVIEW

**Comment by Wedge009** [comment]
I think this is a good idea, especially since An Orcish Incursion is a beginner campaign where relatively new players wouldn't necessarily know this without the hint.

**Comment by gfgtdf** [comment]
yes, i'd maybe be even more explicitly saying somethign like "you can recruit deifferent units depending on which unit stands on the keep of you castle (assuming that the castle has only one keep)"

**Comment by ln-zookeeper** [comment]
All the other hints end with a period, so this one should too.

**Comment by gfgtdf** [comment]
sry accidently clicked "close and comment"

**Comment by sigurdfdragon** [comment]
Updated hints to mention standing on keeps and added periods at end.

**Pull request merged**
