### PR TITLE
[Wmllint] add two missing corrections for Naga Warrior and Myrmidon

### PR DESCRIPTION
**Pull request by knyghtmare**
Adds missing wmllint entries for image path change
- Naga Warrior
- Naga Myrmidon

### CODE REVIEW

**Comment by knyghtmare** [comment]
@Toranks does this patch what you have encountered?

**Comment by Toranks** [comment]
imagen
This is what wmllint changes me in the latest version 1.17.18
As you can see, it does not update the base routes, nor the animations.
It's strange since according to what I see on this PR, it should update at least all the routes of the fighter with the previous code

**Comment by Elvish-Hunter** [comment]
> It's strange since according to what I see on this PR, it should update at least all the routes of the fighter with the previous code

Indeed it should, so perhaps the error is somewhere else. This PR, however, looks correct, so I'm merging it.

**Comment by soliton-** [comment]
How exactly is this change useful? If you replace `units/nagas/warrior` then you already replace `units/nagas/warrior-` anyway.

**Comment by Toranks** [comment]
I guess he did it because the naga fighter already had the same scheme before.

**Comment by soliton-** [comment]
The naga fighter has a replacement rule for `units/nagas/fighter.png` -> `units/nagas/fighter/fighter.png`. I'm going to revert this later since it adds nothing.

**Pull request merged**
