### PR TITLE
Revised square walls

### PR DESCRIPTION
**Pull request by doofus-01**
Only **d1ca049** is supposed to be here, the earlier crap commits are there because I've given up trying to get git to do what I want.  I hope they are not too much of a headache.

### CODE REVIEW

**Comment by Vultraz** [comment]
This breaks corner transitions with the walls:
walls problem

**Comment by doofus-01** [comment]
Not sure what you mean.  Those little flag things?

**Comment by Vultraz** [comment]
No, that's a custom terrain that will need to be adjusted. I mean the corners are now hex-shaped and no longer have the distinctive wall shape that made them so interesting.

Compare:
walls original

**Comment by doofus-01** [comment]
Hrmm, I thought they were supposed to be more hex-shaped, so they don't encroach so much...

**Comment by doofus-01** [comment]
I've just pushed a right-angle south-facing corner, currently the two corners are just random variations, but they could be different terrains.  "Interesting" is subjective, I think the first one was more "interesting" (and nothing was "broken").  But if the map-maker gets to choose, then everyone is happy.

**Comment by doofus-01** [comment]
Looking at the north-facing corner, I don't see how to do this without covering up the open hex, like before.  So never mind my previous comment.  Maybe the best plan is to keep the old stone walls for people who don't care about that sort of thing and really want square corners, and this can be an alternative terrain.

**Comment by doofus-01** [comment]
I think this is basically done, just needs some slight clean-up, and removal of old wall images.

**Comment by Vultraz** [comment]
Just looked over the latest changes, and I think they look pretty good. Just a few small issues I noticed:

Slight missing transitions with cave walls:
wallissue1

Small bits of stray pixels:
wallissue2

And I'm not sure if this shape is intentional:
wallissue3

Besides that, looking pretty good! :) It does serve to highlight the need for Dwarven Castle ->Walls, transitions, though.

One think you might consider working on in relation to this is new replacements for scenery/gate-rusty-*.png, which are used extensively by UMC. They's now slightly too narrow and off-center when compared to the new walls. Since they rather look bad anyway, and I'd like to add them as terrains in 1.13, perhaps you could design a new, better gate image that aligns with these walls and then we can mainline.

**Comment by doofus-01** [comment]
Yeah, there are some stray/missing pixels, I'll fix them before it's ready for merging.  

The missing transitions were always missing, it's just that now it's like two different castles touching and they need hybrid images.  It should look better when finished.  

Sure, I can work on new gates.  I probably won't get this all done this week though.

**Comment by Vultraz** [comment]
Any chance this will be ready for merge before Sunday.

**Comment by doofus-01** [comment]
There's a chance, but it will be close, most work will have to wait until Saturday.  I will try though.

**Comment by doofus-01** [comment]
This isn't finished, but if it I don't get anymore done before 1.13.6, I think it could be merged without looking broken.  I'll still try to get it finished in the next day or so.

**Comment by Vultraz** [comment]
We've had to push back 1.13.6 again with no solid new release date, so no rush.

**Comment by doofus-01** [comment]
I think this is done now.  The n/s facing door images are not great, but I think they are OK for now.  I'm not really sure how they should be.

**Comment by Vultraz** [comment]
Few critiques of the doors, going by the screenshot on the forums:

- There seems to be a slight offset when two sw/se are placed next to each other. Dunno how much of an issue this is.
- I think the top bars should be a little thinner. Maybe by 1/3.

**Comment by doofus-01** [comment]
I thought the black part at the top would help indicate it was an impassable barrier, but it doesn't look "realistic" in any way.  I could get rid of it.  I have a plan for the side-by-side doors, and might help for n/s doors too, but I won't get to it until the weekend.

**Comment by Vultraz** [comment]
Sweet :).

**Comment by CelticMinstrel** [comment]
@doofus-01 - You should be able to fixup your master branch with the following commands:

```
git fetch origin master
git branch --force master origin/master
git push --force fork master
```

This is assuming that "origin" refers to this repository and "fork" refers to your forked repository on GitHub. If that's not the case, substitute the proper names. If you're not sure of the proper names, you can use the URLs that GitHub provides on the main repo page.

This method should work without checking out the master branch first.

In future, when git complains about diverged branches when you push, the preferred way to resolve this (for Wesnoth at least) is to run `git pull --rebase`, rather than just `git pull` as the helpful text usually suggests. You can probably fixup the commits on this branch with the same command, but I'm not quite sure.

To clarify, the first commit in this PR that matters is dac1049, right? Everything before that is already merged?

**Comment by doofus-01** [comment]
Thanks, @CelticMinstrel, those three commands seem to have worked.  We'll see how it goes when I try to add something here in a few days.

Right, the commits before d1ca049 should not be here, they are from earlier.

**Comment by CelticMinstrel** [comment]
I have no idea how I got the digits of the hash muddled up...

Anyway, the commands I mentioned won't affect the branch this PR is on. You'd need different commands to fix that. If you want to fix this PR, I think `git rebase master` might work (and then `git push --force`), but not quite sure. It might be easiest to not fix it, as I or vultraz can fix it ourselves if necessary.

**Comment by doofus-01** [comment]
I think me not trying to fix the git history of this PR sounds like a fine plan.  Hopefully I can avoid this mistake in the future.  Thanks.

As for the actual content of the PR, I am not finished, but the general plan is there (more or less):
1.  There are three portal images (gate-n,gate-se, and gate-sw)
2.  There are four pillars (pillar-sw, pillar-se, pillar-ne, pillar-nw) that are essentially transition images

The WML isn't great, but I don't think it breaks anything, and can be optimized later.  I tried to get sensible directions automatically, to make each portal just one terrain, but it may be a fool's errand.  There is a screen-shot on the forum.

**Comment by Vultraz** [comment]
I do not see the screenshot.

**Comment by doofus-01** [comment]
Patience...

**Comment by Vultraz** [comment]
The diagonal doors look **amazing**, as do the single-hex horizontal one. :D However, the horizontal doors w/ pillars don't mesh well with the walls at all :/

**Comment by doofus-01** [comment]
Yeah, I'm not sure how to fix it without exploding this into a really big project.  I think just dropping the n/s facing doors may be best.

**Comment by Vultraz** [comment]
Well, up to you. Just let me know when you're done and what commits are meant to merge.

**Comment by doofus-01** [comment]
As far as I'm concerned, this can be merged now.  I believe d1ca049 and everything after should be included.

**Comment by Vultraz** [comment]
These look great! I noticed a few small glitches with stone walls, but I don't consider them a blocker for merging; most of them are due to Dwarven Castles using Cave Wall transitions, which should really be fixed at some point...

wall glitches

Anyway, I've gone ahead and squashed + merged the commits you indicated (bc46b9c2a223).

Many thanks for doing this :)

**Comment by Vultraz** [comment]
@doofus-01 Just found a serous transition issue:
serious wall issue
Could you fix this?

**Comment by doofus-01** [comment]
Just swap these two lines in the terrain-graphics.cfg.

{NEW:WALL_A10             Xol            (!,Xu*,Xo*)                                   cave/stone_walls/lit/wall-stone-lit}

{NEW:WALL_CORNER        Xo*             (!,Xo*,Xu*)                                cave/stone_walls/wall-stone}

**Comment by Vultraz** [comment]
That worked, thanks :D

**Pull request closed without merging**
