### PR TITLE
EI S14: Indicate uncleared swamp hexes with "swamp reeds" images

### PR DESCRIPTION
**Pull request by Dalas121**
EI's S14 involves traversing a swamp with hidden, immobile undead waiting in ambush. To make it easier for the player to remember which hexes they've cleared, mark the uncleared hexes.

Alternatively, this aid could be available only on the lower difficulties.

### CODE REVIEW

**Comment by stevecotton** [comment]
Where did the images come from?

**Comment by Dalas121** [comment]
Drawn by me by modifying pre-existing wesnoth images, any new contributions licensed CC-BY-SA 4.0 (or CC0 if that makes the PR simpler)

**Comment by stevecotton** [comment]
Do you remember exactly which images they're based on?

(I know I could look, but I'd rather spend time elsewhere).

**Comment by Dalas121** [comment]
Based on on `water-plant.png` and `water-plant2.png` from `core/images/terrain/swamp`

**Review by nemaara — APPROVED** [review]

**Comment by stevecotton** [comment]
> Drawn by me by modifying pre-existing wesnoth images, any new contributions licensed CC-BY-SA 4.0

I think it ends up GPL v2+ instead, as the base images trace back to commit f7cc2f10799431a08f50d24b1a5121d37f5c8de3.

I'll try and push an updated copyrights.csv file to this PR. We should probably squash the history using Git (not just the squash-and-merge button) and then let the CI run on it again afterwards; the update_copyrights script likes to check commit dates, and squash-and-merge is likely to change them.

**Pull request merged**
