### PR TITLE
[1.18] Unit test cumulative resistance with a base value

### PR DESCRIPTION
**Pull request by stevecotton**
These tests clarify what "cumulative" means for non-leadership abilites, which since Wesnoth 1.1.3 doesn't seem to fit the English word.

For cumulative abilities, if the base value from the unit is higher that the ability's value, then the base value is used instead. In the case of a Skeleton with 40% base resistance, "cumulative=yes" is equivalent to "value,cumulative=40,no".

In all of these cases, a single ability's value is used; "cumulative" doesn't mean that the values from multiple abilities interact.

This is all when using value=, not when using add= or sub=.

### CODE REVIEW

**Comment by soliton-** [comment]
Sounds to me like cumulative should perhaps be deprecated in favor of an attribute name that actually expresses the desired logic. Or there needs to be a more flexible way to describe how multiple abilities should interact if there is no single desired logic. I know there is some overwrite and priority stuff but it feels more tacked on than one coherent design.

**Comment by stevecotton** [comment]
I'd expect anyone wanting "this ability only improves the value" to look at the Steadfast or Marksman abilities. Sadly, although the alternative was already in 1.1.3 (Steadfast uses `[filter_base_value]`), a lot of UMC is going to be using `cumulative=yes` (having copied the code from Marksman).

So while I'd like to deprecate `cumulative=yes` for non-leadership, I think its unrealistic to do so; I wouldn't consider removing it before 1.23. Will also need to work through all the built-in abilities to see if there are more behaviors that just "leadership cumulative" and "non-leadership cumulative".

FYI: @CelticMinstrel @newfrenchy83

**Comment by Pentarctagon** [comment]
Can confirm - cumulative has been a mystery to me for a while now.

**Comment by Pentarctagon** [comment]
On that note: what are the cumulative vs non-cumulative abilities anyway?

**Comment by CelticMinstrel** [comment]
> This is all when using value=, not when using add= or sub=.

Is it possible that cumulative starts to make more sense (ie, more in line with the meaning of the word) when used with add or sub?

**Comment by stevecotton** [comment]
> when used with add or sub?

Assuming all the calculation involving add and sub is in `class unit_ability_list::effect`, those ignore the value of cumulative.

> On that note: what are the cumulative vs non-cumulative abilities anyway?

As far as I know at the moment:

Leadership and non-leadership have different rules for what "cumulative" means, but it has a meaning for every ability or weapon special with a "value" attribute.

Leadership is the one that gets is_cumulative=true passed to unit_ability_list::effect's constructor, which results in it using get_extremum() to calculate the value, via the highest() and lowest() wrappers. #8726 is about working out what get_extremum() does, and the WIP commit in there drops half of the logic.

Some other attributes get calculated with get_extremum() too:
```
actions/attack.cpp: [berserk]value
tod_manager.cpp: [illuminates]max_value,min_value
units/abilities.cpp: [swarm]swarm_attacks_min,swarm_attacks_max
units/types.cpp: [resistance]max_value - I believe this has no effect, because it's in a std::min(resist_effect.get_composite_value(), ...)
units/unit.cpp in 1.18: [resistance]max_value 
```

The commit just added to this PR is a test for `[resistance]max_value`, on 1.18 the surprising result is that the `max_value` attributes get added together, although the `value` attributes don't. In 1.19, #8722 (82499d07857885263d2617560b4754c20e34f16f) changed this to something logical, using `min(each individual max_value)` and disregarding the cumulative attributes.

**Comment by soliton-** [comment]
> So while I'd like to deprecate `cumulative=yes` for non-leadership, I think its unrealistic to do so; I wouldn't consider removing it before 1.23.

Sure, I didn't expect a quick removal. I was rather thinking about indefinite deprecation as "works weird for legacy reasons here is what we recommend to use instead".

Important is that we get a clear view about how abilities work right now and how they should be working. This PR is a good step towards the first part.

**Comment by stevecotton** [comment]
The name "cumulative" has finally made sense to me - given that it was added in 1.1.3, very few units had weapon specials, and abilities couldn't be used as weapon specials, then "cumulative" on the Elvish Markman's weapon special makes sense meaning "can only be an improvement over the base value".

That meaning is lost now, given that a fight can have 10 units' abilities applying weapon specials to either combatant. Maybe more, I think 1.16's UtBS' Formation involved more distant units too.

**Pull request merged**
