### PR TITLE
Fix the scons Wesnoth Windows executable icon.

### LINKED ISSUE #2204: wesnoth.exe doesn't have proper icon
When I build master on Win 7 x64, the .exe no longer has a proper icon (swords and shield). Instead it has the windows default icon for apps. It is possible this could affect future windows releases.

This started somewhere between: https://github.com/wesnoth/wesnoth/commit/608de6a42df8ead850248e35f4b3990489d04523
and
https://github.com/wesnoth/wesnoth/commit/f759e4ecd10cfbf2d4077e69ed4811bf2c7c3c79

It might be the SConscript changes. Any ideas @jyrkive @Pentarctagon ?

### PR DESCRIPTION
**Pull request by Pentarctagon**
Fixes #2204.

### CODE REVIEW

**Comment by jyrkive** [comment]
Have you tested the fix?

For that matter, *how* does one test it?

I'd also like if you added a comment to explain that `env["wesnoth_res"]` is necessary.

**Comment by Pentarctagon** [comment]
I can't test it myself, since I don't have Windows.  Testing would just be compiling without the fix > the executable doesn't have its icon > recompile with the fix > the executable has its icon.

**Comment by jyrkive** [comment]
And this is the way to compile it? http://forums.wesnoth.org/viewtopic.php?f=5&t=40694

**Comment by loonycyborg** [comment]
Yes, @jyrkive

**Comment by sigurdfdragon** [comment]
thanks

**Pull request merged**
