### PR TITLE
WoF: new campaign description

### PR DESCRIPTION
**Pull request by Jonathan-Kelly**
Somehow I never updated the placeholder campaign description, so doing that now.

Any thoughts? Otherwise, this should be ready to commit.

### CODE REVIEW

**Comment by Pentarctagon** [comment]
Sounds good to me at least.

**Review by Wedge009 — APPROVED** [review]

**Review by knyghtmare — APPROVED** [review]
Definitely an improvement

**Comment by Jonathan-Kelly** [comment]
@nemaara did you have any thoughts on this? String freeze is in a couple days.

**Comment by nemaara** [comment]
go ahead and merge 👍

**Pull request merged**
