### PR TITLE
MP Lobby Game Notification for master

### PR DESCRIPTION
**Pull request by Wedge009**
master version of #4259 

Original author: @lilinitsy

### CODE REVIEW

**Comment by stevecotton** [comment]
Needs an update to the schema:
`error validation: Invalid key 'game_created=' in tag [sounds]`

Looks good to me, other than that and the whitespace (same as 1.14).

**Comment by Wedge009** [comment]
Hmm, where is the schema updated? I wonder why it wasn't a problem for 1.14.

**Comment by stevecotton** [comment]
data/schema/core/config.cfg

Being able to validate against the schema is a new feature in 1.15. There's a schema.cfg in 1.14 too, but it's full of TODO comments.

In 1.15 it's run by `utils/travis/schema_validation.sh` or by running wesnoth directly with command line options `--validate data/_main.cfg --preprocess-defines=TEST,SCHEMA_SHOULD_SKIP_THIS`, along with options for `--userconfig-dir` and `--data-dir`.

**Comment by Wedge009** [comment]
Thanks, I didn't know about that. Hopefully I've added it correctly.

**Comment by Wedge009** [comment]
@stevecotton Checks have passed now, right?

**Pull request merged**
