### PR TITLE
Remove sample_user_handler and other unimplemented/unused bits.

### PR DESCRIPTION
**Pull request by Pentarctagon**
This PR remove the sample user handler; the unimplemented nickserv functionality for register, set, details, and drop; unused/unimplemented email-related functionality, and unused user handler cleanup functionality.

### CODE REVIEW

**Comment by ProditorMagnus** [comment]
Remember to update MultiplayerServerWML.

Does this remove commands like register? #2500

**Comment by Pentarctagon** [comment]
Yes, it removes register, set, details, and drop.

**Comment by Pentarctagon** [comment]
I could go ahead and remove the room commands you listed in that issue as well, seeing as they apparently haven't worked for a while.

**Comment by soliton-** [comment]
It would be nice if this would be several PRs or several commits since now that's a bit hard to review. Whitespace only changes should be done in a separate commit presumably over the complete source if it's fixing some style guideline.

I'm fine with removing the user_handler class hierarchy. I agree it's not useful to overcomplicate the design if there is no actual use. I would not want to change the config format though.

The register, set, details, and drop commands can also certainly go. I don't think it's a good idea to implement them for the forum user handler since the forum is the owner of the DB and we should only read it.

I'm not in favour of adding a hard dependency on mysql for wesnothd. It's used for local games as well and this does not really benefit from the mysql integration.

The room feature should rather be brought back than completely removed. It's unfortunate it got left behind in the asio rewrite but it was and presumably still is a wanted feature.

**Comment by Pentarctagon** [comment]
Alright, should be better now.  I left `user_handler.?pp` in since it ended up being a nicer way to separate the mysql requirement than having to put a bunch of `#ifdef`s in `server.cpp`.

I'm not sure how wanted a feature the room commands are though, given they haven't worked for a few years at least at this point.

**Comment by soliton-** [comment]
Well, it might be gone for years but it’s only not in use since 1.14 was released. It’s true though that there are not as many players nowadays so it’s less useful. And of course having random code pieces hanging around is probably not that much help for someone wanting to reintroduce the feature. They‘d rather look at 1.12 code presumably.

Anyhow, thanks for breaking this down in several commits I‘ll try to review today.

**Comment by ProditorMagnus** [comment]
The way I understand room commands is that server side support for rooms was from 1.x to 1.12, and client side support(tab in lobby) in 1.x to 1.6/8 and 1.14. There might have been overlap, but I dont think that was after 1.8.

**Comment by soliton-** [comment]
Looks all good to me except the removal of the nickserv functionality should include the client side in the chat_command_handler.

**Comment by Pentarctagon** [comment]
Updated.

**Pull request merged**
