### PR TITLE
SoF S9: Map `Isay` to `Iasy` code swap

### LINKED ISSUE #7210: SoF last scenario can't load
### Game and System Information

1.17.10

### Description of the bug

imagen

### Steps to reproduce the behavior

- Play Sceptre of Fire to the last scenario or load 9_Caverns_of_Flame.map on map editor.

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by knyghtmare**
Closes #7210

### CODE REVIEW

**Comment by knyghtmare** [comment]
**Note:** I will _ignore_ the map-diff failed check.
The logic is that it registers a change from a non-existent terrain to an existing one (which patches the bug). Thus, it should be failing as expected.

**Comment by Wedge009** [comment]
See my comment in #7210. I think @doofus-01 would prefer the code to be `Isay`.

**Comment by knyghtmare** [comment]
we shall await for doofus's remarks then.

**Comment by cooljeanius** [comment]
> **Note:** I will _ignore_ the map-diff failed check. The logic is that it registers a change from a non-existent terrain to an existing one (which patches the bug). Thus, it should be failing as expected.

Is that #6862, #7034, or its own separate issue? cc @macabeus

**Comment by knyghtmare** [comment]
> > **Note:** I will _ignore_ the map-diff failed check. The logic is that it registers a change from a non-existent terrain to an existing one (which patches the bug). Thus, it should be failing as expected.
> 
> Is that #6862, #7034, or its own separate issue? cc @macabeus

I simply do not like this..."feature". It's been annoying in my case so I choose consider it to be irrelevant with logical reasoning.

**Comment by stevecotton** [comment]
Running wmllint (since #7047) will revert this change. I haven't looked at which terrain code should be used, but I think this PR should be rejected until wmllint is changed (or it should be changed in this PR).

**Comment by Wedge009** [comment]
Just got confirmation in #7210 that the definition should be changed to `Isay` to match.

**Pull request closed without merging**
