### PR TITLE
revisions to mushroom terrain graphics

### PR DESCRIPTION
**Pull request by doofus-01**
Addresses #4453, mostly by deleting the DISABLE_TRANSITION lines.  Also a couple other touch-ups.

### CODE REVIEW

**Comment by doofus-01** [comment]
Last commit was one more thing that could be probably be included: better overlay with water (without making a new terrain type).  This is a screen shot comparison of the current revision.
Screenshot_20191109

**Comment by doofus-01** [comment]
I'll commit this tomorrow if there are no objections.

**Comment by CelticMinstrel** [comment]
Oh nice!

This made me wonder how the regular forests look when placed on water, so I gave it a try… other than the great tree though, they all look alright, though I think it's just using the same small forest variant that would appear on hills.

**Comment by doofus-01** [comment]
> This made me wonder how the regular forests look when placed on water, so I gave it a try… other than the great tree though, they all look alright, though I think it's just using the same small forest variant that would appear on hills.

It does use the small forests, this bit from the main terrain-graphics.cfg file shows the terrain filter for the adjacent terrains that will cause that to happen.

```
#define SMALL_FOREST_FILTER
C*,K*,X*,Q*,W*,Ai,M*,*^V*,*^B*,_off^_usr#enddef
```

I think the mushrooms were just too big and solid, with spaces and shadows, so they stood out more than the trees do.

**Pull request merged**
