### PR TITLE
use the original action codepath when redoding

### PR DESCRIPTION
**Pull request by gfgtdf**
Previously when redoing an action each action had a seperate action::redo function that handled redioing that action. Now when redoing an action we just use the replaywml (that we cut form the replay when undoing that action) to redo the action, and call synced_context::run() just liek when we executed the action for the first time.

The main advantage is that [on_redo] is no longer nesasary since the
game will ow just fire the action related wml events again when redoing
the actions.

See also http://gna.org/bugs/?25472

### CODE REVIEW

**Comment by Vultraz** [comment]
Is this ready for merging?

**Comment by CelticMinstrel** [comment]
Just for the record, I'm not entirely satisfied that removing `[on_redo]` is a good idea. I think it might be better to have `[on_redo]` be an optional tag which, if used, overrides the default behaviour of using the original action codepath that @gfgtdf has introduced in this PR.

**Comment by gfgtdf** [comment]
> to have `[on_redo]` be an optional tag which, if used, overrides the default behaviour of using the original action codepath that @gfgtdf has introduced in this PR.

the 'orignal codepath' doesnt only handle the redoing of the wml events but also of the whole user action (moving, recuiting etc. ) so it cannot be optionally switched on and off unless you want the wml author to reimplement all these things in its wml code. also other unrelated wml events might then rely on beeing preoperly redone by this, and allowing another event to diable the redocode woudl break them.

**Comment by CelticMinstrel** [comment]
I see. Well, _if_ you were allowing `[on_redo]` as an optional tag, obviously it'd only override the event it appeared in, not the entire user action. Maybe it could be done by actually mutating the event to replace its content with the content of the `[on_redo]`? Not sure if events are mutable though.

**Comment by gfgtdf** [comment]
That sounds rather complicated, i think it's be easier if we just had a function/property like wesnoth.is_redoing that can then be checked manually by the wml author, one can ofc also write a wesnoth.wml_conditional based on it.

**Comment by CelticMinstrel** [comment]
Hmm. Well, I suppose that could be acceptable, sure. I'd also suggest defining the associated conditional tag in master rather than forcing addon devs to define it if they need it.

By the way, was `[on_redo]` new in 1.13?

**Comment by gfgtdf** [comment]
> By the way, was `[on_redo]` new in 1.13?

Yes, i added it in 1.13.2

**Comment by CelticMinstrel** [comment]
Good, otherwise I would have insisted not removing it. :P

**Pull request merged**
