### PR TITLE
fix advancement for Darken Volk

### PR DESCRIPTION
**Pull request by newfrenchy83**

### CODE REVIEW

**Review by nemaara — APPROVED** [review]

**Comment by nemaara** [comment]
Probably needs someone who works more on the code side to approve this too since it's adding something to core.

**Review by knyghtmare — APPROVED** [review]

**Comment by knyghtmare** [comment]
I did recently finish DiD on Evoker, and Noticed that Darken Volk is the _only_ Dark Sorcerer in DiD in the 1.16 one. I guess having that in core would benefit the UMC community.

**Comment by Pentarctagon** [comment]
A more general macro would be preferable if this is going in core:
```
#define DISABLE_ADVANCEMENT UNIT ADVANCEMENT
    [modify_unit_type]
        type={UNIT}
        remove_advancement={ADVANCEMENT}
    [/modify_unit_type]
#enddef
```

**Comment by newfrenchy83** [comment]
> A more general macro would be preferable if this is going in core:
> 
> ```
> #define DISABLE_ADVANCEMENT UNIT ADVANCEMENT
>     [modify_unit_type]
>         type={UNIT}
>         remove_advancement={ADVANCEMENT}
>     [/modify_unit_type]
> #enddef
> ```

except what Dark Sorcerer is the only without set_experience, using a macro for the others, ok, but using a genral macro only for one case is not interresting.

**Comment by Pentarctagon** [comment]
Well, alternatively, if there are no other units in DiD that can advance to a Lich aside from Darken Volk, then I'm not sure why this macro is needed at all?

**Comment by knyghtmare** [comment]
> Well, alternatively, if there are no other units in DiD that can advance to a Lich aside from Darken Volk, then I'm not sure why this macro is needed at all?

Adding 
```
[modify_unit_type]
        type="Dark Sorcerer"
        remove_advancement="Lich"
[/modify_unit_type]
```
inside the `[campaign][/campaign]` of DiD works just fine.

**Review by knyghtmare — APPROVED** [review]

**Review by knyghtmare — APPROVED** [review]

**Pull request merged**
