### PR TITLE
Tutorial UI improvements

### PR DESCRIPTION
**Pull request by babaissarkar**
Uses portraits in the character selection dialog. Clicking on pictures selects the unit. Buttons are removed.
Screenshot from 2024-10-28 17-58-32

Adds a dark background to hint messages.

Adds marker to show which unit should be clicked at the beginning.

https://github.com/user-attachments/assets/69da30ee-7543-41cc-b7fd-e94c1d9eb119

### CODE REVIEW

**Comment by babaissarkar** [comment]
Issues:
- [ ] something keeps erasing the unit markers.
- [ ] simplify strings and code

**Comment by Wedge009** [comment]
At first I thought a single-click might be a nuisance if there was a mis-click (now that the two options are adjacent to each other), but then I looked at the current (1.18) tutorial options and saw it also has just a single-click to accept the option. So that's fine.

I just note that this is incongruent with the double-click for the MP menu, which changed relatively recently from a click-to-select -> OK/Cancel pattern. But that's probably okay too.

**Comment by babaissarkar** [comment]
I've talked with @Vultraz on discord about changing the MP menu to single click as well.

**Comment by Wedge009** [comment]
I don't think single-click is a great idea, but if that's what the consensus is...

**Comment by babaissarkar** [comment]
The reason I am interested in single click is because
1. reduces click count
2. there's no way to know which places use double click, and most places use single click anyway. Avoids confusion, at least from a new player point of view.
3. For the MP dialog, the listbox is being used as a button grid, so that makes sense.

**Comment by CelticMinstrel** [comment]
If it's single-click then I think it shouldn't start with one of them selected.

**Comment by babaissarkar** [comment]
> If it's single-click then I think it shouldn't start with one of them selected.

Updated. Also added the description back, now center aligned.

**Comment by soliton-** [comment]
The image meta data for PNG images now moved from EXIF Artist/Copyright to XMP tags Creator/Rights. See ccb079f05c4.

**Pull request merged**
