### PR TITLE
Wyverns and other units

### PR DESCRIPTION
**Pull request by Hejnewar**
Changes:
Falcon, Elder falcon, Roc - changed charge attack into "blade - claws" and normal attack into "pierce - beak" 
Reason - birds do not attack while descending from skies with their beak. They use claws for that because if thier beak gets broken they can eat anymore.

Wild Wyvern and Wyvern Rider - overhaul of statistics. 

Roc - Decreased hp from 56 to 44, charge attack damage from 12 to 10 and cost from 45 to 36. This unit was just looking too strong for me on level 2. No as strong as Jinni looks but I decided to not touch him for now because I dont have clear vision for this unit. 

Next thing that I would like to talk about are descriptions that are missing for Wild Wyvern, Wyvern Rider and Roc. During times of dunefolk rework I created some lore for Wyverns and Rocs thus I want to show it here in shorter fashion and ask if you like it. If yes I would try to write something for their descriptions (I'm not good at that but I guess it could be helpful for someone better). If not I would like to try to improve what is here and do that then. 

Rocs:
-Are smart enough to comunicate.
-They hunt in packs or alone depending on type of prey present.
-Smallest prey would be around size of small deer.
-They even hunt wyverns if they are in pack and target is isolated.
-They don't appear much on deserts.
-Their favorite nesting terrain are mountains, they appear a lot in hilly regions.
-They can even threaten not well protected caravans.

Wyverns:
-They are omnivores.
-Females and males live in separation for most of the time.
-Males are tasked with protection of females within thier territory, if females are not protected well enough they will go to other male.
-Females try to scare their opponents and if that doesn't work they prefer to run instead of fighting. They only fight when they have no other choice, need to protect eggs or feel safe (eg. when male wyvern or friendly humans are present), they still are very dangerous.
-Females mostly eat plants but they wouldn't refuse free meat and also hunt from time to time.
-Males eat meat and plants.
-Females and humans can live near eachother if humans are not perceived as threat (touching fertilized eggs or wyverns if they don't do that first is strictly forbidden).
-Males and humans are at best neutral, humans like to live within territory of wyverns mostly because many other threats are eliminated.
-If males had bad experiences with humans they can attack them instantly.

-Wyverns don't forget favors easily (eg. if you protected them they can stop male from attacking you) (optional) (good as plot point).
-There are many types of wyverns with various sizes eg. Wyverling - small wyvern born from eggs that weren't cared for, they adapt very well and dont need to eat as much, they usually travel in packs and help male wyvern protect his territory (optional - work intensive) (good for gameplay variety).

Wyvern Rider:
-It takes long time to tame wyvern.
-Being able to ride wyvern is sing of royality or family very trusted by them (if royality exists).
-Hatchlings are trained since very first day together with thier rider. 
-Riders can only ride thier wyvern, wyverns will carry only thier rider. 

This is basically how I imagine these units. Sorry for wall of text.

### CODE REVIEW

**Comment by Earth-Cake** [comment]
Do Wyvern Riders ride males or females?

**Comment by soliton-** [comment]
Gryphon Rider is race gryphon. I would expect Wyvern Rider to be race wyvern or monster. The config file should be in the correct race directory.

**Comment by Hejnewar** [comment]
@Earth-Cake I would say that both, females might be easier to ride but they are also less eager for combat. Males are harder to ride but will engage in combat without problems. 

@soliton- Wyver Rider is in dunefolk directory that is why I changed his race, it was the only unit in dunefolk directory that had race different than dunefolk.

**Comment by Earth-Cake** [comment]
I think that wyverns should have their own race, as @soliton- said.

**Comment by CelticMinstrel** [comment]
> Reason - birds do not attack while descending from skies with their beak. They use claws for that because if thier beak gets broken they can eat anymore.

I understand this, but I think you could also make an argument for depicting the claws as a pierce attack. Just a thought, I don't actually have a problem with the change.

> Rocs:
> -Are smart enough to comunicate.
> -They hunt in packs or alone depending on type of prey present.
> -Smallest prey would be around size of small deer.
> -They even hunt wyverns if they are in pack and target is isolated.
> -They don't appear much on deserts.
> -Their favorite nesting terrain are mountains, they appear a lot in hilly regions.
> -They can even threaten not well protected caravans.

Agreed on most points. Rocs to me are a mountain sort of bird, so while they may hunt on the desert fringes, they would rarely be spotted in the depths of the desert. It certainly makes sense that a roc could threaten a caravan, and I don't mind them being smart enough to communicate. (However, their thought process should be somewhat alien, in my opinion.)

The only thing I'm a little dubious about is hunting in packs. Raptors (aka birds of prey) are typically solitary hunters as far as I'm aware. Now, with rocs being intelligent, it could make sense that they may work together; however, packs suggests a fairly large group. How about we say they hunt in groups of up to, say, five? Also, I'd definitely try to find a word other than "pack" to describe a group of rocs. If no-one can think of anything better, perhaps a "flight" of rocs? That seems like it would work for a lot of birds. Or maybe you could borrow from lions, a "pride" of rocs or something similar. (Well, that'd make more sense for gryphons than rocs, I guess…)

>Wyverns:
>-They are omnivores.
>-Females and males live in separation for most of the time.
>-Males are tasked with protection of females within thier territory, if females are not protected well enough they will go to other male.
>-Females try to scare their opponents and if that doesn't work they prefer to run instead of fighting. They only fight when they have no other choice, need to protect eggs or feel safe (eg. when male wyvern or friendly humans are present), they still are very dangerous.
>-Females mostly eat plants but they wouldn't refuse free meat and also hunt from time to time.
>-Males eat meat and plants.
>-Females and humans can live near eachother if humans are not perceived as threat (touching fertilized eggs or wyverns if they don't do that first is strictly forbidden).
>-Males and humans are at best neutral, humans like to live within territory of wyverns mostly because many other threats are eliminated.
>-If males had bad experiences with humans they can attack them instantly.
>
>-Wyverns don't forget favors easily (eg. if you protected them they can stop male from attacking you) (optional) (good as plot point).
>-There are many types of wyverns with various sizes eg. Wyverling - small wyvern born from eggs that weren't cared for, they adapt very well and dont need to eat as much, they usually travel in packs and help male wyvern protect his territory (optional - work intensive) (good for gameplay variety).

This sounds about ten times more dubious than the roc ideas. The most dubious aspect is the differing diet of male and female wyverns. I'll be frank: I think you should drop that idea entirely. If the males are the hunters (which by no means is a given - in lions for example, the females do most of the hunting), then they would bring back meat for the females.

Rather than explicitly picking out what's good and what's bad (in my opinion), I'll make a counter-proposal of my own:

* Wyverns are omnivorous, eating primarily meat but with a generous helping of fruits and the like
* Male wyverns are highly territorial, staking out a large area as their personal hunting ground and attacking any other male wyverns who stray into their territory. Most likely they drive out their own sons once they reach maturity.
* Female wyverns are about 20% smaller than male wyverns and less fierce than the males… unless guarding their eggs or young, in which case they're just as dangerous, if not more so. They might well wander without regard to the males' territorial boundaries, though the wyvern governing a territory surely factors into their movements.
* Male wyverns, being territorial, are prone to attacking humans passing through their territory, especially smaller groups. This doesn't necessarily mean that a wyvern's territory is a dangerous place for humans to live; it depends on various factors like the wyvern's disposition, the humans' reaction to his presence, who was there first, and such. Thus there are very likely some humans who live in wyvern territory and enjoy its protection from other monsters.
* Female wyverns are more likely to hide than attack, unless the humans pose a clear threat to them or their offspring. That doesn't make them any less dangerous, only easier to reason with.
* Wyverns are fairly intelligent, though they don't speak human speech (whether they can understand it is a mystery of the ages). They have good memories; if done a favour (for example, medical treatment when heavily injured, or being given food when starving), they'll remember for a long time and may treat the human who helped them favourably. On the other hand, if someone hurts them and lives to tell the tale, they won't hold back if ever they meet again.
* I think it should be essentially impossible to tame a wild wyvern. Any exceptions are tales of legend, not something that would happen every day. Tame wyverns then are those raised by humans from the egg. The wyvern and rider forms a close bond over the course of training. I wouldn't say a wyvern will never carry anyone other than their own rider, but it would be an unusual occurrence, and done only with the blessing of their normal rider. Both male and female wyverns can be ridden; there's no particular benefit of one over the other, unless fighting other wyvern riders.
* Wyverlings, sure, we could add such a thing (very low priority, I'd say - after all, we have nothing similar for gryphons or most other monster types). They could be runtish wyverns who didn't get enough food and thus had stunted development, or they could just be immature (young) wyverns, or I suppose they could even be infertile offspring who develop differently from both male and female wyverns, kinda like a third "gender".
* Male and female wyverns shouldn't be different units. They could have different sprites (to reflect the gender dimorphism), but they should be the same unit with the same basic stats and abilities. Their differing temperament doesn't affect their statsin my opinion.

> Gryphon Rider is race gryphon. I would expect Wyvern Rider to be race wyvern or monster. The config file should be in the correct race directory.

I agree, the Wyvern Rider should be of the wyvern race (or monster race, if we lack a dedicated wyvern race). For now I'd just revert the race change, I think, but we could move the wyvern to a new wyverns folder in the future (even if they're still of monster race, it kinda makes sense for them to be grouped).

No comments on the stats changes; I'm not one to care about twiddles here and there, and nothing stuck out to me as weird.

**Comment by Hejnewar** [comment]
I actually misunderstood what Soliton meant. I agree with that and will revert the race change.

Idea of rocs hunting in flights actually originated from Yumi's description of Dune Wayfarer, he fights there vs 4 rocs at once.

I honestly really like your proposal, it keeps many important things from my proposal but also adds more flavour into it not to mention it's much more nicely written.

Still I would like to clarify two things:
1. Wyverns are omnivores because it would be hard to feed them where they live if suddenly all wyverns start hunting. Difference between females and males in this regard was due to females not going out of their way in order to get meat where males would get more meat just because they protect their territory and kill some monsters form time to time. In case where there is a lot of meat around all wyverns would prefer to eat meat instead of plants. 

2. If we have lets say 2 sprites then I would rather have female as level 2 and male as level 3 or 4 unit but if there are just normal level ups then that's completely fine with me to have the same stats for male and female.

**Comment by CelticMinstrel** [comment]
> Difference between females and males in this regard was due to females not going out of their way in order to get meat

Perhaps the male wyverns would offer meat, maybe even as a courting gift or something. However it happens though, I think meat would still form a significant part of a female wyvern's diet.

> If we have lets say 2 sprites then I would rather have female as level 2 and male as level 3 or 4 unit

Absolutely not. It may be acceptable to have slightly different stats for male and female wyverns, but making them different levels is a terrible idea.

**Comment by Hejnewar** [comment]
> Perhaps the male wyverns would offer meat, maybe even as a courting gift or something. However it happens though, I think meat would still form a significant part of a female wyvern's diet.

I think that this would be dependent on where they live and would make up from 25 to 75% of their diet. 25% in places where there is not a lot of prey (wyvern territories near roc territories for example) and 75% in places where there is a lot of prey per wyvern (desert for example).

> Absolutely not. It may be acceptable to have slightly different stats for male and female wyverns, but making them different levels is a terrible idea.

Could you explain why? I know that you would want them to be similar to each other in stats but I really don't know why.

**Comment by Earth-Cake** [comment]
Let's take an example of one Wyvern and one Roc on nearby territories. 
I assume that Rocs and Wyverns won't tolerate each other nearby, since they both would probably hunt the same prey.
Now, assuming that Wyverns are stronger than Rocs, to survive Rocs would have to live in packs/flights or however you want to survive and eventually kill that Wyvern.
The problem for Rocs is that now that Rocs eventually hunt the same prey. Let's assume that they hunt both on Wyvern's and their teritorry (which is a logicak assumption), they wouldn't eventually have enough food to survive, and that means we have the same problem as on the beginning.
So, to avoid this problem, Rocs have came to an assumption; they will flight in duos, possibly one male and one female, so that they can survive a Wyvern attack, and still have enough food to not starve.

**Comment by CelticMinstrel** [comment]
> I think that this would be dependent on where they live and would make up from 25 to 75% of their diet. 25% in places where there is not a lot of prey (wyvern territories near roc territories for example) and 75% in places where there is a lot of prey per wyvern (desert for example).

Well, maybe, but I think wyverns would tend to live more in the latter type of place than the former. Still, that's only a tendency.

> Could you explain why? I know that you would want them to be similar to each other in stats but I really don't know why.

A different level suggests an extreme difference in power which just doesn't make any sense to me for gender-dimorphic dragonoids. They don't have to have identical stats - after all, the male wyvern is significantly larger, so it makes sense for it to (for example) have increased strength (higher damage) and endurance (higher hp) but perhaps reduced agility (higher move cost in a few difficult terrains). The stats don't need to be absolutely identical, but making them different levels is just too drastic of a difference. It might make sense if the female wyvern is the size of a cat and the male wyvern is the size of an horse, but that doesn't feel fun at all.

A whopping two-level difference is even worse. Like the female wyvern is the size of a squirrel and the male wyvern is the size of an elephant?

> I assume that Rocs and Wyverns won't tolerate each other nearby, since they both would probably hunt the same prey.

Already you're starting from a bad assumption. Now… it's perfectly possible that they might hunt the same prey. However, I don't think it's a given.

What prey _do_ they actually hunt, though? There was no discussion of wyvern's typical prey, but rocs were mentioned as preying upon small deer and even wyverns, so probably a roc is larger than a wyvern on average. Then a wyvern is likely going to hunt prey smaller than a deer, and probably relies at least partly on much smaller game (like rabbits or even squirrels, or at least animals of similar sizes).

Or, since it was also mentioned that rocs would only take on a lone wyvern in groups, both animals could be of similar sizes, which does increase the chance that they'd compete for prey.

On the other hand, just because they are of similar size, it doesn't follow that they definitely hunt the same prey. Perhaps the wyverns prefer goats and sheep, while the rocs prefer deer and gazelles. Rocs may occasionally catch a goat or sheep, and wyverns may occasionally catch a deer or gazelle, but more often they wouldn't come into conflict over prey.

**Comment by doofus-01** [comment]
How about we just don't worry about wyvern gender for now?  If it matters, and some variation could be good, we can add it later.  Leave sexual dimorphism in the fluff, and any scenario where it is critical will take it into account.  Do we put this level of scrutiny into the genitalia of the horses that the other mainline units ride?

I'm not just saying this to be PC, I really think this is adding complication we don't need at this point.  At least as far as what is expected for sprites and a working unit.  If it's purely a question of the fluff, I don't really care, I'm sure it can be made to work eventually.

**Comment by CelticMinstrel** [comment]
Yeah, I don't think there's any need to modify the stats based on gender.

**Comment by Hejnewar** [comment]
> A different level suggests an extreme difference in power which just doesn't make any sense to me for gender-dimorphic dragonoids. They don't have to have identical stats - after all, the male wyvern is significantly larger, so it makes sense for it to (for example) have increased strength (higher damage) and endurance (higher hp) but perhaps reduced agility (higher move cost in a few difficult terrains). The stats don't need to be absolutely identical, but making them different levels is just too drastic of a difference. It might make sense if the female wyvern is the size of a cat and the male wyvern is the size of an horse, but that doesn't feel fun at all.
> 
> A whopping two-level difference is even worse. Like the female wyvern is the size of a squirrel and the male wyvern is the size of an elephant?

TBH my line of thought was completely different. It is a bit silly but females fight less so they wont level us as much so they will usually be around level 2 but males do fight a lot so they would level up a lot so usually they would be around level 3 or 4.
I'm perfectly fine with them having the same stats or size on equal levels. 

It would be nice to have +/- weights of units before we talk about what they eat:
Rocs would be I assume at minimum as small as heaviest flying bird that ever lived on earth so 120kg+ (264 lbs.+) maybe that is not enough.
Looking at art gryphons would weight around 450 kg (1000 lbs.) dwarfs are smaller than humans so gryphon would be around horse size.
Wyverns in comparison would weight easily more than 450 kg, they need to carry humans in armor and with weapons and for long periods of time and they look bigger than gryphons.

**Comment by CelticMinstrel** [comment]
> TBH my line of thought was completely different. It is a bit silly but females fight less so they wont level us as much so they will usually be around level 2 but males do fight a lot so they would level up a lot so usually they would be around level 3 or 4.
> I'm perfectly fine with them having the same stats or size on equal levels.

This line of thought can make sense from a campaign design perspective if wyverns are a _unit line_. However, as long as wyverns are a single unit, it doesn't make any sense; and even if they were a unit line, this line of thought has no bearing on the stats of the actual units, only on which unit a campaign designer chooses for male and female wyverns. (Also, I would definitely not have a 2-level difference.)

> It would be nice to have +/- weights of units before we talk about what they eat:
> Rocs would be I assume at minimum as small as heaviest flying bird that ever lived on earth so 120kg+ (264 lbs.+) maybe that is not enough.
> Looking at art gryphons would weight around 450 kg (1000 lbs.) dwarfs are smaller than humans so gryphon would be around horse size.
> Wyverns in comparison would weight easily more than 450 kg, they need to carry humans in armor and with weapons and for long periods of time and they look bigger than gryphons.

Well, sure.

If you want to reference real animals, the largest known raptor (ie, the same general type of animal as the roc) is the Haast's Eagle, which was thought to weigh up to 16kg. The only other large flying animal I can think of is the azhdarchid pterosaur, Quetzalcoatlus. Naturally, no-one knows for sure what it weighed; estimates have run as low as 70kg or as high as 250kg.

So your choice of 120kg for the roc would put it closer to Quetzalcoatlus in weight, which seems fine to me.

Gryphons are primarily lion, and lions apparently weigh around 200kg. On the other hand, a gryphon might be larger than a lion (I can't find any good comparative measurements on Wikipedia to compare lions to ponies or horses, but I'd think a gryphon is at least pony-sized). Since they're flying animals, I also wouldn't be surprised if they're somewhat lighter than they look.

It's true that the wyvern looks quite a bit larger than the gryphon, but part of that might be the more open stance of the wyvern sprite. In fact, to me it looks like the wyvern's core body is less bulky than the gryphon's, and only when accounting for limbs and tail is it larger than a gryphon. Maybe a wyvern isn't actually a whole lot heavier than a gryphon?

Anyway, all of this seems to suggest the wyvern is at least bulkier than the roc, and probably larger.

**Comment by Hejnewar** [comment]
> (Also, I would definitely not have a 2-level difference.)

Oh, I would absolutley have 2-level difference for what I have in mind. :D

> Gryphons are primarily lion, and lions apparently weigh around 200kg. On the other hand, a gryphon might be larger than a lion (I can't find any good comparative measurements on Wikipedia to compare lions to ponies or horses, but I'd think a gryphon is at least pony-sized). Since they're flying animals, I also wouldn't be surprised if they're somewhat lighter than they look.

Well I took a look at them and was like "hmm dwarf is 150cm, horse is 150cm in withers (I have no idea if this is correct translation), horse weights 450kg, gryphon probably will weight around 450kg too because it looks slightly bigger than 150cm". 

Hmm

A lot depends on sprite and you can't make it much bigger really for wyvern but hmm depends on how much feathers vs body gryphon has really. But yea you might be right here.

**Comment by CelticMinstrel** [comment]
> A lot depends on sprite and you can't make it much bigger really for wyvern but hmm depends on how much feathers vs body gryphon has really. But yea you might be right here.

True, it could be that the gryphon is just fluffier since it has feathers.

> Oh, I would absolutley have 2-level difference for what I have in mind. :D

I doubt you could convince me that a 2-level difference is reasonable for any decent idea.

**Comment by nemaara** [comment]
I think it'd be nice to make a separate wyvern race for the wild wyvern and wyvern rider. Is there anything else I need to do besides moving the files to a new folder and creating the race in units.cfg? Also, I'm intending on merging this after making the new wyvern race unless anyone objects.

**Comment by CelticMinstrel** [comment]
…did you change your mind about the wyvern race, or did I just miss it?

**Comment by nemaara** [comment]
No I thought I didn't want to keep this PR waiting forever to merge. I'd still like to make a wyvern race sometime down the road.

**Comment by CelticMinstrel** [comment]
Well, since no-one ever _answered_ your question, I'm pretty sure that that is indeed all you need to do to add a new race. Could also be a few other optional bits, like a new movetype in units.cfg or a names list if you don't want to use the drake names.

**Pull request merged**
