### PR TITLE
Added names for wolves

### PR DESCRIPTION
**Pull request by spixi**

### CODE REVIEW

**Comment by Vultraz** [comment]
Please rebase your PR so only c62480c remains.

**Comment by spixi** [comment]
git rebase https://github.com/wesnoth/wesnoth.git does not work, it says invalid upstream.

However, I noted that the change would also affect the Wolf Rider line, which is not intended.

**Comment by ln-zookeeper** [comment]
I don't think we really want named wolves. It doesn't make any sense, and no other monster units get names. They're not pet wolves someone has named, just like no one would have given names to most Tentacles of the Deep or Mudcrawlers.

**Comment by CelticMinstrel** [comment]
These definitely look like the sorts of names humans would give to wolves. I think it's reasonable to have the macro (for people who want a wolf with a random name), but _if_ there were actual wolf names I'd want them to sound like something the wolf could have chosen for itself.

**Pull request closed without merging**
