### PR TITLE
Prose updates for orcs eating other sapient races

### PR DESCRIPTION
**Pull request by nemaara**
For #4007.

### CODE REVIEW

**Comment by sigurdfdragon** [comment]
The DW ones seem ok

Not sure on several of the TRoW ones.

**Comment by CelticMinstrel** [comment]
Typo alert in S19 - "stronger" missing the R.

**Comment by sigurdfdragon** [comment]
Will comment further on Sun, May 5th

**Comment by sigurdfdragon** [comment]
All the lines seem reasonable

**Pull request merged**
