### PR TITLE
Remove unused dawn.png image, update copyrights.csv

### PR DESCRIPTION
**Pull request by stevecotton**
dawn.png was leftover from the Time of Day being shown with an overlay image; 074e157400e04d16cdb2b77db5065537f35c9177 removed dusk.png and night.png. The image itself should be a transparent blue hexagon, but the alpha channel was corrupted, and so it appeared completely transparent.

empty.png was a copy of images/misc/blank.png, and only blank.png is used in mainline. It's a 640x480 pixel completely transparent image.

Make the capitalisation of Kitty's name consistent, and attribute the orb-disengaged.png image.

Part of clearing up #9028.

### CODE REVIEW

**Comment by cooljeanius** [comment]
> empty.png was a copy of images/misc/blank.png, and only blank.png is used in mainline.

I think I may have seen it used in UMC, though...

**Comment by stevecotton** [comment]
Good call, it's used in Era of Magic's animations for summoners; and it was already used when EoMa's Git history started in 2018.

**Comment by cooljeanius** [comment]
> Yeah, `misc/empty.png` is used quite a bit in addons. I can't find any references to `misc/dawn.png` in an addon for 1.18 or 1.16 though. So that should be fine to remove.
> 
> We could add a conversion rule to wmllint then maybe we can remove empty.png some time in the future.

I think I may also have seen use of `empty.png` recommended on the wiki at some point, too, but I can't seem to find the exact page at the moment...

**Comment by soliton-** [comment]
`empty.png` is not mentioned on any wiki page.

**Comment by stevecotton** [comment]
This PR is as good a place as any for a discussion about empty.png, and it's useful to have a way for subthreads of #9028 to be kept separate.

However, for the change itself, the previous force-push reduced the PR to only changing dawn.png and the .csv file. Is it okay to merge?

**Review by doofus-01 — APPROVED** [review]
The only conceivable issue I see with removing `terrain/dawn.png` is if someone needed a blank 72px image in the terrain directory, for some reason.  Otherwise, all "empty" 72 px images could just be replaced with `misc/blank-hex.png`.

**Pull request merged**
