### PR TITLE
remove accuracy and parry form [attack]

### PR DESCRIPTION
**Pull request by gfgtdf**

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Though I'm pretty sure you're correct that accuracy and parry can be emulated with `[chance_to_hit]`, I kind of like them; they're simpler than writing a `[chance_to_hit]` ability, for example. I actually started using them in one of my unreleased addons, and I was also the one that exposed them in the Lua API, so I would kinda prefer if they weren't removed.

**Comment by gfgtdf** [comment]
> they're simpler than writing a [chance_to_hit] ability

Can't you just put the change_to_hit in a macro which would then be as easy as accuracy= to use?

**Comment by CelticMinstrel** [comment]
Maybe, but in general, replacing something that doesn't require a macro with something that does require a macro feels like a step backwards.

**Comment by CelticMinstrel** [comment]
(In case it's not clear, I'm against this.)

**Comment by gfgtdf** [comment]
> Maybe, but in general, replacing something that doesn't require a macro with something that does require a macro feels like a step backwards.

I don't really think this is a good point.

>(In case it's not clear, I'm against this.)

y it was clear.

I should have done this before your entered the development team :p

**Comment by shikadilord** [comment]
Commit 982fecdc4ae217017d853f2efcde880e9ff64d5c belongs somewhere else, certainly not in this PR.

Since @CelticMinstrel went through the effort of documenting the accuracy and parry stuff in the wiki (as well as adding a few missing bits to manipulate them via [effect]s), I think we should give this a chance to be used in 1.14.x before deciding whether to drop it or not. So, I'm closing this for the moment.

**Pull request closed without merging**
