### PR TITLE
Update dune explorer image path, closes #5945

### LINKED ISSUE #5945: Could not open image 'units/dunefolk/explorer.png'
### Game and System Information
 - 1.15.14

### Describe the bug
wmllint has entry for ("units/dunefolk/muharib.png", "units/dunefolk/explorer.png"), but 'units/dunefolk/explorer.png' does not exist.

### Expected behavior
wmllint has entry pointing towards existing file.

### PR DESCRIPTION
**Pull request by ProditorMagnus**

### CODE REVIEW

**Comment by Pentarctagon** [comment]
It looks like the line above the one you added should also be deleted.  Additionally, the same error would be true for the other Dunefolk units as well.

**Comment by ProditorMagnus** [comment]
I checked that other dunefolk image ageless uses has unchanged path.

Matter about keeping line above would be decided by whether wmllint should be used on 1.14 addon or can be other version. Comments suggest anything over 1.4 should be supported.

**Comment by Pentarctagon** [comment]
If both lines are left, will it do both the substitutions `("units/dunefolk/muharib.png", "units/dunefolk/explorer.png"),` and `("units/dunefolk/explorer.png", "units/dunefolk/rover/explorer.png"),`, or just the first?

> I checked that other dunefolk image ageless uses has unchanged path.

I mean, that's fine, but for example on the line below the one you added, `units/dunefolk/burner.png` doesn't exist anymore either.

**Comment by ProditorMagnus** [comment]
linechanges are stored in tuple, which has guaranteed order, so both will be done given they are correctly ordered.

**Comment by Pentarctagon** [comment]
Alright, that's good then.  Can you add similar updates for the other Dunefolk units as part of this PR?

**Comment by ProditorMagnus** [comment]
I was considering refusing, but decided to solve it the fun way.

```
old = """./apothecary.png
./blademaster.png
./burner.png
./cataphract.png
./elder-falcon.png
./explorer.png
./falcon.png
./firetrooper.png
./harrier.png
./herbalist.png
./marauder.png
./piercer.png
./raider.png
./ranger.png
./rider.png
./rover.png
./scorcher.png
./skirmisher.png
./soldier.png
./spearguard.png
./spearmaster.png
./sunderer.png
./swiftrider.png
./swordsman.png
./warmaster.png
./windrider.png""".split("\n")
new = """./burner/burner+female-defend1.png
./burner/burner+female-defend2.png
./burner/burner+female-fire1.png
./burner/burner+female-fire2.png
./burner/burner+female-fire3.png
./burner/burner+female-fire4.png
./burner/burner+female-fire5.png
./burner/burner+female-fire6.png
./burner/burner+female-fire7.png
./burner/burner+female-fire8.png
./burner/burner+female.png
./burner/burner-defend1.png
./burner/burner-defend2.png
./burner/burner-fire1.png
./burner/burner-fire2.png
./burner/burner-fire3.png
./burner/burner-fire4.png
./burner/burner-fire5.png
./burner/burner-fire6.png
./burner/burner-fire7.png
./burner/burner-fire8.png
./burner/burner.png
./burner/firetrooper+female.png
./burner/firetrooper.png
./burner/firetrooper_flame1.png
./burner/firetrooper_flame10.png
./burner/firetrooper_flame11.png
./burner/firetrooper_flame12.png
./burner/firetrooper_flame2.png
./burner/firetrooper_flame3.png
./burner/firetrooper_flame4.png
./burner/firetrooper_flame5.png
./burner/firetrooper_flame6.png
./burner/firetrooper_flame7.png
./burner/firetrooper_flame8.png
./burner/firetrooper_flame9.png
./burner/firetrooper_glow.png
./burner/scorcher+female.png
./burner/scorcher.png
./herbalist/alchemist-defend1.png
./herbalist/alchemist-defend2.png
./herbalist/alchemist.png
./herbalist/apothecary-defend1.png
./herbalist/apothecary-defend2.png
./herbalist/apothecary.png
./herbalist/herbalist-defend1.png
./herbalist/herbalist-defend2.png
./herbalist/herbalist.png
./herbalist/luminary-defend1.png
./herbalist/luminary-defend2.png
./herbalist/luminary.png
./rider/cataphract-bow.png
./rider/cataphract-defend1.png
./rider/cataphract-defend2.png
./rider/cataphract-lance-defend1.png
./rider/cataphract-lance-defend2.png
./rider/cataphract-lance.png
./rider/cataphract-mace.png
./rider/cataphract.png
./rider/horse-archer.png
./rider/marauder-torch-overlay.png
./rider/marauder.png
./rider/raider-torch-overlay.png
./rider/raider.png
./rider/rider.png
./rider/sunderer-defend1.png
./rider/sunderer-defend2.png
./rider/sunderer.png
./rider/windbolt.png
./rover/explorer-defend1.png
./rover/explorer-defend2.png
./rover/explorer.png
./rover/rover-defend1.png
./rover/rover-defend2.png
./rover/rover.png
./rover/wayfarer-defend1.png
./rover/wayfarer-defend2.png
./rover/wayfarer.png
./skirmisher/eagle-e.png
./skirmisher/eagle-hover.png
./skirmisher/eagle-hover1.png
./skirmisher/eagle-hover2.png
./skirmisher/eagle-hover3.png
./skirmisher/eagle-n.png
./skirmisher/eagle-rise.png
./skirmisher/falcon-dive.png
./skirmisher/falcon-e.png
./skirmisher/falcon-hover.png
./skirmisher/falcon-hover1.png
./skirmisher/falcon-hover2.png
./skirmisher/falcon-hover3.png
./skirmisher/falcon-n.png
./skirmisher/falcon-rise.png
./skirmisher/falconer-alone-defend1.png
./skirmisher/falconer-alone-defend2.png
./skirmisher/falconer-alone.png
./skirmisher/falconer-falcon-defend1.png
./skirmisher/falconer-falcon-defend2.png
./skirmisher/falconer-launch1.png
./skirmisher/falconer-launch2.png
./skirmisher/falconer-launch3.png
./skirmisher/falconer-launch4.png
./skirmisher/falconer-launch5.png
./skirmisher/falconer-move1.png
./skirmisher/falconer.png
./skirmisher/harrier-defend1.png
./skirmisher/harrier-defend2.png
./skirmisher/harrier.png
./skirmisher/skirmisher-defend1.png
./skirmisher/skirmisher-defend2.png
./skirmisher/skirmisher-ne-defend1.png
./skirmisher/skirmisher-ne-defend2.png
./skirmisher/skirmisher-ne.png
./skirmisher/skirmisher.png
./skirmisher/sky_hunter-alone-defend1.png
./skirmisher/sky_hunter-alone-defend2.png
./skirmisher/sky_hunter-alone.png
./skirmisher/sky_hunter-eagle-defend1.png
./skirmisher/sky_hunter-eagle-defend2.png
./skirmisher/sky_hunter-launch1.png
./skirmisher/sky_hunter-launch2.png
./skirmisher/sky_hunter-launch3.png
./skirmisher/sky_hunter-launch4.png
./skirmisher/sky_hunter-launch5.png
./skirmisher/sky_hunter-move1.png
./skirmisher/sky_hunter.png
./skirmisher/strider-defend1.png
./skirmisher/strider-defend2.png
./skirmisher/strider.png
./soldier/blademaster.png
./soldier/captain-defend1.png
./soldier/captain-defend2.png
./soldier/captain-leading1.png
./soldier/captain-leading2.png
./soldier/captain.png
./soldier/paragon.png
./soldier/soldier-defend1.png
./soldier/soldier-defend2.png
./soldier/soldier.png
./soldier/spearguard.png
./soldier/spearmaster.png
./soldier/swordsman-defend1.png
./soldier/swordsman-defend2.png
./soldier/swordsman.png
./soldier/warmaster-leading1.png
./soldier/warmaster-leading2.png
./soldier/warmaster.png
./wyvern-rider.png""".split("\n")

def wmllint(o,n):
	return '        ("' + "units/dunefolk" + o[1:] + '", "' + "units/dunefolk" + n[1:] + '"),'
for o in old:
	for n in new:
		if o[1:] in n:
			print(wmllint(o,n))
```

**Pull request merged**
