### PR TITLE
[UtBS, WIP] Initial pass at Sun Singer animations

### PR DESCRIPTION
**Pull request by doofus-01**
Don't commit, this is just a first pass, but I'd still like to see what anyone who cares thinks of the flame and the base sprite.  I tried not to change the design too much.  Ideally, the flame animation can be more generalized than it is now.  If the base looks OK, I can do flying and defense animations.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I'm confused, there seems to be two copies of the same image?

**Comment by doofus-01** [comment]
No.  Maybe it can be streamlined better, but the *_image.png files need to look good with the XBRZ or whatever scaling is done in the help menu, whereas the base image needs to look good in game with the other layers applied by the [animation] WML.

**Comment by ln-zookeeper** [comment]
Looks like I forgot to change the Sun Singer's movetype at some point; it should **not** be a flyer.

Anyway, it's very nice to see that flame animation methodology used. Wouldn't it make more sense though to keep the version with the flames as unit.png and the flameless version for the standing animation as unit-plain.png (or something), instead of the other way around? The one with the flames is what's used in most contexts after all, with the version without the flames being pretty much a special case.

**Comment by doofus-01** [comment]
@ln-zookeeper - OK, I won't worry about a floating animation then.  But I won't change the movetype because I'm not sure what all you wanted to do, and this PR should probably stick to visuals-only anyway.  As for the default image, maybe it's best not to have the flame at all.

-------------
Unless there are major objections, I'll consider the singer healing animation done.  I know it could use more love, but I think it's not too cheap now and I'd better to move on to shaman and shyde.  I'll include those here, don't commit yet.

(BTW, Jetrel made some revisions to the base sprite (now the -stand.png), so I'm not the sole creator, if I ever was.)

**Comment by doofus-01** [comment]
By "shaman", I meant "mystic".  I think the healing animation for mystic looks OK now.  The base sprite for the sun-shyde/sylph needs some more review with Jetrel, I don't know when it will be ready for any animation.  So, this can be merged if the current contents are OK.  

This save-game should help with previewing the healing animations, just end turn.
[UtBS-The Morning After Turn 2 healing anim test.gz](https://github.com/wesnoth/wesnoth/files/1801270/UtBS-The.Morning.After.Turn.2.healing.anim.test.gz)

**Pull request merged**
