### PR TITLE
Cut arbitrary hardcoded restrictions of scenario settings

### PR DESCRIPTION
**Pull request by Jonathan-Kelly**
And widen the corresponding 'soft' limits for the multiplayer scenario creation screen.

~~Normally I thoroughly test everything before a pull request, but am not currently set up to build from source, So I cannot test the small, surgical, engine level changes in this one.~~ Edit: now tested and working.

### CODE REVIEW

**Comment by gfgtdf** [comment]
Did you test what happens when you set it to value out of range (like 15?) (with both `force_lock_settings = yes` and `force_lock_settings = no`) ?

**Comment by gfgtdf** [comment]
> I did - when a value is set out of range in the scenario WML ..

I mean after your changes.

**Comment by Jonathan-Kelly** [comment]
I tested the changes to `mp_create_game.cfg` and those work correctly. But I could not test the changes to `map_settings.cpp` as that requires building from source.

**Comment by gfgtdf** [comment]
When it's so unclear whether the changes actually change anything Ina reliable way they obviously need to be tested before they can be merged.

For the actual raising of the settings I don't have a strong opinion, on the one hand more options could be better here, on the other hand these sliders could then always look a bit off when people actually only use the left water of it.

**Comment by Jonathan-Kelly** [comment]
> When it's so unclear whether the changes actually change anything Ina reliable way they obviously need to be tested before they can be merged.

I agree... would you be so kind as to test them for me? : )

All you have to do is set `mp_village_gold=0` in a multiplayer scenario, go to the `Game Settings` tab of the scenario creation screen for that scenario, make sure the `Use Map Settings` checkbox is checked and then see if the `Village Gold` slider reads 0 as it should. If it instead reads 1, then the changes are not working somehow. But I am 80% sure they will.

> these sliders could then always look a bit off when people actually only use the left water of it

I can lower the upper limits of the sliders below 9 if you prefer, like 8 or 6 maybe?

**Comment by soliton-** [comment]
Note that the CI (https://github.com/wesnoth/wesnoth/actions/runs/5787469239 scroll down to Artifacts) builds a windows installer and a flatpak bundle for linux to test.

**Comment by gfgtdf** [comment]
> I agree... would you be so kind as to test them for me? : )

I'm rather lazy with testing myself, so no :(

> All you have to do is set mp_village_gold=0 in a multiplayer


No, this is not what the test as about, the point is that you remove the clamp in map_settings.cpp which clamps the value to the slider range, what should be tested is what happens if you write something like `mp_village_gold=20`

**Comment by Jonathan-Kelly** [comment]
> Note that the CI (https://github.com/wesnoth/wesnoth/actions/runs/5787469239 scroll down to Artifacts) builds a windows installer and a flatpak bundle for linux to test.

Praise be to you, soliton! Wow, this is like getting your own personal nightly builds.

Alright, so now I have tested this PR and it works!

> No, this is not what the test as about, the point is that you remove the clamp in map_settings.cpp which clamps the value to the slider range, what should be tested is what happens if you write something like mp_village_gold=20

Tested this too, and the slider reads 9 while in game the effect is (correctly) 20. This is sub-optimal behavior from the interface but seems much better than the status quo of overriding both the scenario WML and the values specified in `mp_create_game.cfg` with overly tight, hard coded clamps (which have to be separately adjusted to match `mp_create_game.cfg`).

**Comment by CelticMinstrel** [comment]
> Tested this too, and the slider reads 9 while in game the effect is (correctly) 20. This is sub-optimal behavior from the interface

I'd definitely flag this as an issue, but not a blocker. I think the way to handle it would be for the game settings screen to check if the default value is in range, and if not, adjust the slider's range to include the default value.

**Comment by gfgtdf** [comment]
> Tested this too, and the slider reads 9 while in game the effect is (correctly) 20

Is this fir force_lock_settings=yes or no ?

**Comment by Jonathan-Kelly** [comment]
> I'd definitely flag this as an issue, but not a blocker. I think the way to handle it would be for the game settings screen to check if the default value is in range, and if not, adjust the slider's range to include the default value.

That seems best.

> Is this fir force_lock_settings=yes or no ?

Both, the effect (on the interface) is the same with both `yes` and `no`.

Also, you should know that apparently `force_lock_settings=yes` is already broken on both 1.16 and 1.17. Any scenario with it set `yes` starts with no leaders and an immediate "you are defeated" message. At least on Windows 10.

**Comment by gfgtdf** [comment]
> Also, I must report that apparently force_lock_settings=yes is already broken on both 1.16 and 1.17

Hmm i think Also, force_lock_settings implies leader/faction lock so when the side has no leader it gets no leader, not sure whether  i'd call it a bug

**Comment by Jonathan-Kelly** [comment]
> so when the side has no leader defines in wml, it gets no leader, not sure whether i'd call it a bug

If the wml does not define a leader then the default should still be applied (random leader from faction leader list), as the intent of a lock is to override player choice, not to override default settings. Especially since this lock is an attribute of `[multiplayer]` and nearly all multiplayer scenarios (purposefully) do not set player leaders.

But in any case, this pull request is unrelated to force_lock_settings.

**Comment by Jonathan-Kelly** [comment]
@stevecotton Do you see any issues with this small change or can it get your approval?

**Comment by stevecotton** [comment]
Looks reasonable to me, as gfgtdf and celmin seem happy.

**Comment by Jonathan-Kelly** [comment]
Okay, good, Sounds like this is ready to merge then, if anyone wants to to push that nice green merge button : )

**Pull request merged**
