### PR TITLE
Title screen: move language button to icon

### PR DESCRIPTION
**Pull request by nemaara**
For #4531. There's not much of a reason to have a big language button. @shikadiqueen suggested making it a globe icon in the lower right, so that's what this is for. Screenshot: 

Capture

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I don't really like using a globe for language, but I suppose it's not the worst option either.

**Comment by gfgtdf** [comment]
I don't think I'd be able to tell that that button changed language just from that symbol.

**Comment by nemaara** [comment]
The globe icon is a pretty standard language icon.

**Comment by CelticMinstrel** [comment]
I don't think it's a very _good_ standard though. It doesn't represent the concept of "language" well. It's far better than using flags though, so I can live with it.

**Pull request merged**
