### PR TITLE
1.16 - some terrain graphics fixes

### PR DESCRIPTION
**Pull request by doofus-01**
This PR is for terrain-graphics issues I can fix this weekend, no particular plan outside of that.

* make X*^Efs sconce overlay rules symmetric, addresses #6381 and removes another glitch with catacombs candles in south-facing corners

### CODE REVIEW

**Comment by doofus-01** [comment]
A screenshot of what that last commit means, the new behavior and images are the upper row
Screenshot_20211211

**Comment by doofus-01** [comment]
I have no idea what those CI failures are about.

**Comment by Wedge009** [comment]
A lot of tests are failing now, but I'm not sure why. It does look like a lot of error messages relating to 'invalid rotations' but it looks like you've already tried to address that.

**Comment by doofus-01** [comment]
We'll see if CI passes now, but at least the invalid rotations error goes away.  Apparently, that `error engine: invalid rotations` message shows once per value in a rotations key that doesn't have six values.

**Pull request merged**
