### PR TITLE
Keep python 2 compatibility

### PR DESCRIPTION
**Pull request by soliton-**

### CODE REVIEW

**Comment by stevecotton** [comment]
The obvious question is, what happens if you replace line 1's vi modeline with a Python3 shebang?

**Comment by soliton-** [comment]
> The obvious question is, what happens if you replace line 1's vi modeline with a Python3 shebang?

No change.

**Comment by stevecotton** [comment]
Is something explicitly running this with Python2, and if so, why can't it be changed to Python3?

**Comment by soliton-** [comment]
It's running on an old OS. I'm not particularly interested in discussing what all else can be done. Feel free to reject the change if you like.

**Review by stevecotton — APPROVED** [review]

**Pull request merged**
