### PR TITLE
Use [leader] in the c++ code

### LINKED ISSUE #3742: side variabels clashes with leader variables
as the title say, in [side] the [variables] tag is interpreted as the sides variables aswell as the leaders [variables] which might casue issues, actually i didn't find any serious problems with that yet though.

### LINKED ISSUE #7985: Mp connect cannot handle [leader] tags
As said in the title, Mp connect completely ignores  [leader] tags, so for example when a [leader] tag is present mp connect will simply create a second leader.

### PR DESCRIPTION
**Pull request by gfgtdf**
Added code to convert all  ` [side]type=` to `[side][leader]` when the `[scenario]` is read, and the rest of the engine code to only work with [leader], this should fix all possible problems with  [leader] and also simplify the code a bit

Fixes #7985
Fixes #3742

### CODE REVIEW

**Comment by ProditorMagnus** [comment]
For rest of keys that describe leader but are still in [side] no need to change anything?

**Comment by Pentarctagon** [comment]
Should there be a deprecation warning?

**Comment by gfgtdf** [comment]
> For rest of keys that describe leader but are still in [side] no need to change anything?

Yeah the engoen converts them to a [leader] tag when the scenario si read

> Should there be a deprecation warning?

we could think about deprecatin the "old" way but its still really common so im not sure wheterh that's a good idae.

**Comment by CelticMinstrel** [comment]
Okay, so I have two small problems with this, only one of which is new in this PR.

First, the new problem. What if someone wrote `[side]canrecruit=no`? What would that have done before this change? Does it work after this change? It certainly seems wrong to turn it into a `[leader]` tag though – it should instead become a `[unit]` tag.

And now, the second problem. I'm not completely sure this is real, but… does the engine only support one `[leader]` tag per side? Or will it handle multiple `[leader]` tags correctly? It's fine if the first `[leader]` tag is special, but subsequent tags should still be placed on the map and have `canrecruit` set to true.

**Comment by gfgtdf** [comment]
> First, the new problem. What if someone wrote [side]canrecruit=no? What would that have done before this change? Does it work after this change?


It becomes a [leader} tag eith canrecruit=no and works the same same wqay as it did before,

>And now, the second problem. I'm not completely sure this is real, but… does the engine only support one [leader] tag per side? Or will it handle multiple [leader] tags correctly?

It supports multiple [leader], the only thing that special about the first one is that the one thats shown in the mp dialogs as the leader.

**Pull request merged**
