### PR TITLE
fix tag_name check deficiencies(1.18 backport)

### PR DESCRIPTION
**Pull request by newfrenchy83**
The tag_name check is deficient for two reasons:
1.when apply_to=both is used, in the case of [damage_type] [filter_opponent][filter_weapon]type= will check the modified type for application to the owner and the original type for application to the opponent, hence a risk of infinite recursion, especially if [filter_self][filter_weapon]type= is used in the same weapon.

2. in the case of apply_to=attacker/defender, the check for [filter_attacker/defender] must take into account both the value of the variable is_attacker but also the application AFFECT_SELF/OTHER, otherwise in the case apply_to=defender with [filter_defender][filter_weapon]type=, and[filter_attacker][filter_weapon]type= otherwise we end up in the same configuration as for apply_to=both

Finally tag_name is renamed check_if_recursion to mean that this variable is used to ensure that a recursion cannot be set up even if https://github.com/wesnoth/wesnoth/commit/743b146efc1e9c643a601317de491dcadffc760b prevents it from causing a crash but with an error log

### CODE REVIEW

**Comment by newfrenchy83** [comment]
@Pentarctagon could you merge this backport also, please?

**Comment by stevecotton** [comment]
IIUC:
* this could change the behavior of abilities, even ones that don't crash on the existing stable releases
* the previous fix (adding the recursion count) has already prevented the crashes

If those two assumptions are correct, then this shouldn't be backported. Keeping the same behavior to avoid OOS problems, even if it's known to be incorrect, is more important in the stable branch.

**Comment by newfrenchy83** [comment]
> IIUC:
> 
>     * this could change the behavior of abilities, even ones that don't crash on the existing stable releases
> 
>     * the previous fix (adding the recursion count) has already prevented the crashes
> 
> 
> If those two assumptions are correct, then this shouldn't be backported. Keeping the same behavior to avoid OOS problems, even if it's known to be incorrect, is more important in the stable branch.

the only chane is to prevent recursion, if this backported the one diffrence is not error log. in cases mentioned and on e [damage_type] is concerned

**Comment by Pentarctagon** [comment]
A change in behavior where the current behavior is wesnoth crashes or freezes indefinitely doesn't seem like an issue, IMO.

**Comment by stevecotton** [comment]
OK, approved; I'm emailing because I'm on my phone.

I thought there was an edge case with changed behavior which didn't crash before; I'm now convinced that there isn't such an edge case.

**Pull request merged**
