### PR TITLE
heal units on recall list at scenario end

### PR DESCRIPTION
**Pull request by gfgtdf**

### CODE REVIEW

**Comment by Wedge009** [comment]
Sorry for not remembering but what happens currently. Aren't units in the recall list at full HP in the new scenario? Or is this to cater for some end-of-scenario scenes?

**Comment by gfgtdf** [comment]
> Aren't units in the recall list at full HP in the new scenario?

Yes this is what happens, note that usually they are already healed form the last scenario they were used in, so this only really applies to unit that were sended to the recall list, for example via [put_to_recall_list]

**Comment by Wedge009** [comment]
So it's for the sake of consistency? (We have a potential scenario where they wouldn't be healed?) In that case I agree with this change.

**Comment by gfgtdf** [comment]
yes, the topic was brought up here https://forums.wesnoth.org/viewtopic.php?f=12&t=50668

it in particular does not oynl heal but also remove duration=scenario objects

**Comment by gfgtdf** [comment]
this was merged

**Pull request closed without merging**
