### PR TITLE
Units - Dunefolk Nagas - first revisions

### PR DESCRIPTION
**Pull request by doofus-01**
The Naga line of the Dunefolk didn't make much sense to me, but I realize it may have been done with an eye to MP balance, so I tried to be conservative in revisions.  The biggest issue was that the bow seemed to be a reason to use the hunter naga portrait, but was very forced.  Maybe it was for MP balance as well?

In any case, I plan to get basic animation (defense at the very least) for these, but that's not started yet.

### CODE REVIEW

**Comment by Hejnewar** [comment]
Well, water control is necessary in order to have a chance of winning on some maps. There were 3 main candidates for it, lizard, naga nad wyvern. Lizard got rejected - not everyone liked this concept, wyvern was too big for lvl 1 (and hard to animate), so we were left with naga. Also lvl 2 and 3 nagas do very well on sand with 50%/1 and 60%/1 respectively.

I believe bow is there just to make it more different from regular naga.

About sprites: 
They are great! Some people might have problems with 10-4 melee attack on a unit with ranged weapon on its sprite but for that I would just suggest renaming melee attack to "hidden blade" from "curved blade".

**Comment by Earth-Cake** [comment]
Is "chakri" supposed to be plural form of "chakram"?

**Comment by Earth-Cake** [comment]
Great sprites! 

One remark: I have noticed that none of the nagas have quivers to carry arrows or chakri (is chakri supposed to be a throwing chakram?).

**Comment by doofus-01** [comment]
> Well, water control is necessary in order to have a chance of winning on some maps. There were 3 main candidates for it, lizard, naga nad wyvern. Lizard got rejected - not everyone liked this concept, wyvern was too big for lvl 1 (and hard to animate), so we were left with naga. Also lvl 2 and 3 nagas do very well on sand with 50%/1 and 60%/1 respectively.
I believe bow is there just to make it more different from regular naga.

That's cool, I wasn't question the whole naga concept, just the advancement tree and the role the bow played in the whole thing.  If there's not some central reason for that bow, then my change to the level 1 won't break anything.  And the 10-4 melee attack can also be changed.

> One remark: I have noticed that none of the nagas have quivers to carry arrows or chakri (is chakri supposed to be a throwing chakram?).  

Chakri is a small chakram, according to Wikipedia (I wouldn't really know otherwise).  For now, they carry the arrows in hammerspace, in the interest of not cluttering the image.  Maybe quivers can be added if we ever do north-facing frames.

**Comment by doofus-01** [comment]
There's always room for improvement, but I think the dirkfang animations are enough to qualify it as "animated".  The stat changes I made probably need some review: 
 - I tried to use the fluff and general idea of the Ophidian, but I thought there were some inconsistencies, including the name "dervish".  The replacement name I chose might not be the best, but it sort of fits with a unit named "Ophidian" and the concept of a mercenary.
 - Rather than a melee & range branching, I went with both branches mixed fighter, but one is more strikes, the other is more damage (per strike).  The nagas already have a melee unit.
 - I made the alignment "neutral", rather than "liminal", since that is what the regular nagas are, and there is no obvious reason why these nagas should be different.  I also added a minimal (WML-wise) female variation, like the regular nagas.

**Comment by Hejnewar** [comment]
Well, what can I say. I would just appreciate if you contacted me first before introducing balance changes, either directly or thru balance channel on discord, changing way of fighting can in some cases be just too bad from balance standpoint.
Changning strength of L1 naga by about -6% can very well make it unplayable because factions releated to default are delicate. In case of this naga performance would drop to levels that wouldn't allow it to properly contest water. It's true that there are units that are weaker but often factions makes up for thier weaknes or thier level ups do so and that is also not the case here. Changes to L2 also are not very accurate with Ophidian being now clearly superior choice.

Reason behind naga being liminal is to not have 3 alignments in one faction. That said, for me its not that important but I know that for some people it's very iimportant. I will propose changes in statistics after alignment is set in stone.

**Comment by ElderoZ** [comment]
The lvl 1 naga 4-3 6-2 is a little bit weak with neutral, something like 4-3 and 7-2 would probably be fine. And I would agree with the change to neutral, one neutral unit adds some variety, neutral is not all THAT different from liminal and I always though liminal was a meh gimmick.

**Comment by CelticMinstrel** [comment]
Misspelled "hindrance" in the dirkfang description.

**Comment by doofus-01** [comment]
> Well, what can I say. I would just appreciate if you contacted me first before introducing balance changes, either directly or thru balance channel on discord, changing alignment or way of fighting can in some cases be just too bad from balance standpoint.

What's wrong with discussing it here?  The numbers are trivial to change; finding the right ones may not be trivial, but it's not like some balance work is ruined because I opened a PR.  As for ophidian being clearly superior, I was thinking of bumping up the terrain defense of the ringcaster, but didn't get there.  Thematically, it could makes sense as ringcaster being more nimble, ophidian being stronger. 


> The lvl 1 naga 4-3 6-2 is a little bit weak with neutral, something like 4-3 and 7-2 would probably be fine. And I would agree with the change to neutral, one neutral unit adds some variety, neutral is not all THAT different from liminal and I always though liminal was a meh gimmick.

Thanks, I will change that.  My problem with liminal naga was that the original one is neutral, it might be hard to always remember this one is different.  Not as bad as a lawful skeleton would be, but still.

**Comment by Hejnewar** [comment]
> > Well, what can I say. I would just appreciate if you contacted me first before introducing balance changes, either directly or thru balance channel on discord, changing alignment or way of fighting can in some cases be just too bad from balance standpoint.
> 
> What's wrong with discussing it here? The numbers are trivial to change; finding the right ones may not be trivial, but it's not like some balance work is ruined because I opened a PR. 

The biggest problem is that I couldn't see this here for probably around month if not more (and Eat at all) if I wasnt informed by another person. I tend to check github when Im not busy but during beginning of year I'm usually busy and on discord I always see pings. Also time is nice to have since I need to check / make proposals anyway. 

Proper changelog would be also welcomed.

Ok so balance:
Dirkfang - I refuse to believe that EoZ would be so wrong when it comes to unit balance. I think he ment 4-3 melee and 7-2 ranged. That is much closer to being balanced. 
Ringcaster and Ophidian: 
I checked them and compared to previous selves. And they are closer to being balanced between each other. But their xp and gold cost should skyrocket.
Xp to 51 from 38 and gold to 26 from 22. This is way too much when it comes to xp. I would much rather preserve old xp and gold cost because lvl-uping this unit will be almost impossible in PvP and Dunefolk will lose their weak but cheap AoH water control that fits them.

**Comment by ElderoZ** [comment]
Yeah, I meant 4-3 melee 7-2 ranged, same format as when I wrote "The lvl 1 naga 4-3 6-2 is a little bit weak" Next time I will be more clear.

**Comment by doofus-01** [comment]
> Ringcaster and Ophidian:
I checked them and compared to previous selves. And they are closer to being balanced between each other. But their xp and gold cost should skyrocket.
Xp to 51 from 38 and gold to 26 from 22. This is way too much when it comes to xp. I would much rather preserve old xp and gold cost because lvl-uping this unit will be almost impossible in PvP and Dunefolk will lose their weak but cheap AoH water control that fits them.

I'm afraid I don't understand what you are requesting.

> Yeah, I meant 4-3 melee 7-2 ranged, same format as when I wrote "The lvl 1 naga 4-3 6-2 is a little bit weak" Next time I will be more clear.

That changes things a bit, but no problem.  I'll try again next week.

**Comment by Hejnewar** [comment]
> > Ringcaster and Ophidian:
> > I checked them and compared to previous selves. And they are closer to being balanced between each other. But their xp and gold cost should skyrocket.
> > Xp to 51 from 38 and gold to 26 from 22. This is way too much when it comes to xp. I would much rather preserve old xp and gold cost because lvl-uping this unit will be almost impossible in PvP and Dunefolk will lose their weak but cheap AoH water control that fits them.
> 
> I'm afraid I don't understand what you are requesting.

Sorry for not being clear. In short dmg buffs just made these two too strong. For example Ringcaster melee dmg in this PR went up by 3. But I think it doesn't matter for a while. Just come up with design that you like that fits lvl 1, I'm fairly certain that it will be good. I will just correct numbers when I have some time.

**Comment by doofus-01** [comment]
> Sorry for not being clear. In short dmg buffs just made these two too strong. For example Ringcaster melee dmg in this PR went up by 3. But I think it doesn't matter for a while. Just come up with design that you like that fits lvl 1, I'm fairly certain that it will be good. I will just correct numbers when I have some time.

No problem, sounds like a plan.  I'll commit this now, feel free to revise the numbers.

**Pull request merged**
