### PR TITLE
Wyvern portrait and animations

### PR DESCRIPTION
**Pull request by doofus-01**
This needs some cleanup before committing, and maybe a few more frames, but it will remove the "sliding statue" instances for this unit.

### CODE REVIEW

**Comment by doofus-01** [comment]
As before, I'll plan to commit this later if copyrights is the only CI failure, then follow up with a fix for that.

I'm not so pleased with the portrait, but it's better than nothing and I don't want to get bogged down.  It can always be replaced or made an alt if there's a better one.

**Comment by stevecotton** [comment]
> then follow up with a fix for that

Please change your workflow to have the copyright file fixed before merging, otherwise it causes unexpected failures in any other PR that's opened while you're updating the copyright.

**Comment by doofus-01** [comment]
Automation is supposed to make things easier or more efficient, but this copyright bookkeeping is a pain in the ass.

**Comment by CelticMinstrel** [comment]
I think it may at least be reasonable to ask for the copyrights fix to be more or less done before merging so it's ready to push immediately, though I'm not sure if that actually fits in with the way you do things…

**Comment by doofus-01** [comment]
The fix was ready soon after, but then I had to wait for CI to pass, so couldn't merge it as soon as ideal.  (And then I got pulled away, so it sat even longer.)  I see the problem that causes, but I'm not thrilled with the request for guaranteed merge conflicts.

There must be a way to extract image metadata as a way to actually automate this instead of what we got now.  I will look into it.

**Comment by stevecotton** [comment]
@Pentarctagon again, I'm requesting to revert ef25eb2553f865e690bbc9b938b6b925d90bd9be , because requiring the file to be sorted makes merge conflicts much less likely.

**Comment by CelticMinstrel** [comment]
Looks like webp is a RIFF format that supports Exif or XMP metadata, and png supports embedded XMP metadata as well. So, in theory, storing the copyright information in each individual file is technically possible. I _think_ editors are also supposed to preserve such metadata when editing an image.

That makes it much, much harder to see the information though, so I'm not sure if I'd recommend it.

**Comment by Pentarctagon** [comment]
I still don't think it makes sense to fail the CI because the file isn't sorted.

**Comment by Pentarctagon** [comment]
An alternative solution perhaps would be to just sort them by file name from the start rather than putting the ones that need information added/updated at the top of the file.

**Comment by CelticMinstrel** [comment]
> An alternative solution perhaps would be to just sort them by file name from the start rather than putting the ones that need information added/updated at the top of the file.

That's probably a nightmare for the person updating them.

**Comment by stevecotton** [comment]
What if we add an option to put ones that need changing at the top? So there would be two workflows:

1. File is completely sorted, regardless of status
    * Make it work this way by default
    * Editing this needs the user to search through the file
    * File is already sorted, so no need for more sorting afterwards
2. Lines for editing are at the top
    * Easy to edit
    * The user has to sort the file after editing, for example by rerunning the tool

I still think the CI should enforce that it's sorted to avoid merge conflicts and unrelated changes for later editors, but the two workflows give two different ways to do that.

**Comment by Pentarctagon** [comment]
#8866 addresses that by sorting the entire list by name and also listing out the filenames that need updating on the command line.

**Pull request merged**
