### PR TITLE
Add achievements button to titlescreen.

### PR DESCRIPTION
**Pull request by Pentarctagon**

### CODE REVIEW

**Comment by soliton-** [comment]
I think this could also be done as for example a trophy 🏆 icon and placed next to language selection or so. No need to add more to the menu and no need to translate anything.

**Comment by knyghtmare** [comment]
> I think this could also be done as for example a trophy 🏆 icon and placed next to language selection or so. No need to add more to the menu and no need to translate anything.

Plus One to vote

**Comment by stevecotton** [comment]
I like the idea of a trophy icon, but it would still need one string translated because it appears in the preferences menu's Hotkeys settings. Doesn't seem like a saving to avoid translating "View Achievements" either.

**Comment by CelticMinstrel** [comment]
Yeah, a trophy icon is a nice idea, but it has no effect on needing a translation. It would also appear in the menu in-game if we added it there.

**Comment by Pentarctagon** [comment]
Do we have a trophy icon that can be used?

**Comment by Pentarctagon** [comment]
So, unless there's a trophy icon available to use, I'm going to go ahead and merge this tomorrow. If a trophy icon is added later, then the suggested UI changes here can of course be made.

**Pull request merged**
