### PR TITLE
Remove the fast path of [modify_unit]

### PR DESCRIPTION
**Pull request by stevecotton**
Always use the "slow path", because it stores and unstores the unit, triggering
the desired side effects of unstoring a unit.

Fixes issue #5133, and tests that with the new unit test.

Fixes bug #4978, that changing the facing wasn't updating the display.

This corresponds to 1.16's commit 13c5d8a96ead8d2a7f0435f60b8ec7f7e0af0972,
that commit merely disabled the fast path to be a minimal change.

### CODE REVIEW

**Comment by stevecotton** [comment]
Please take the role of `somebody` and log them yourself.

**Comment by stevecotton** [comment]
Is there a reason to wait longer before merging this?

**Comment by Pentarctagon** [comment]
Not afaik.

**Comment by stevecotton** [comment]
Stable has #6222's 13c5d8a96ead8d2a7f0435f60b8ec7f7e0af0972 instead, which was the minimal change to disable the fast path. Is something still broken in stable?

**Comment by CelticMinstrel** [comment]
…did I ever create the two new issues as mentioned above?

**Comment by gfgtdf** [comment]
> So, from that PR it seems that the main advantage of the "fast path" wasn't speed, rather it was smaller save files

Its wasn't exactly about the savefiles size but rather about not storing redundant information in them. The slow path which uses [unstore_unit] overwrites the whole unit, then everything is stored in the savefile.  Now when in a newer wesnoth version or addon version for example changes changes the definition of an ability (like it happend with backstab in wensoth 1.14 or 1.16) The unit form the savefile would still use the old ability definition, leading to bugs being hard to fix because the bad code is stored in the savefiles, or as in case of the "backstab chance" annoying  "deprecated" messages.

When the fast path is used, the game realizes that for example only the units hp is changed, and doesn't store unit units abilities in  the savefile, so when the game is loaded in a newer wesnoth or addon version changes to the units ability (or other stat changes of the unit type) take effect immidiately.

**Pull request merged**
