### PR TITLE
Fix wesnoth.interface.select_unit(nil) unexpected behavior

### LINKED ISSUE #9213: wesnoth.interface.select_unit(nil) unexpected behavior
### Game and System Information

- **Version:** 1.18.0

### Description of the bug

1. Visual bug when deselecting unit `wesnoth.interface.select_unit(nil,nil,false)`, **while** selected unit is being hovered over, **once the mouse moves out** black stripes are still all over whole screen (at this point unit is unselected, and mouse is on other tile).
Doesn't happen when the mouse is elsewhere, viz video

On the video I first select the unit, and move the mouse away from unit, everything works fine after unselecting unit in Lua console.
Then I select the unit again, while keeping the **mouse cursor hovering over the unit**, then I unselect the unit via Lua console, but then there are those black stripes all over the screen **when I move the mouse cursor away**, which shouldn't be.
https://github.com/user-attachments/assets/ea40665b-7fe5-49c0-b873-df1a26aca41a

2. `wesnoth.interface.select_unit(nil,nil,false)` Unselecting unit in wesnoth.game_events.on_mouse_button does nothing.

### Steps to reproduce the behavior

1. 1. select a unit
1. 2. hover over an empty hex
1. 3. Into Lua console: `wesnoth.interface.select_unit(nil,nil,false`
1. 4.  ou should now see a map, like normally, when no unit is selected **even when you move mouse**
1. 5. select the unit
1. 6. hover over the exact same unit
1. 7. Into Lua console: `wesnoth.interface.select_unit(nil,nil,false`
1. 8. you should now see a map, like the unit that you unselected in Lua would be selected **even when you move a mouse** BUG (Including black stripes)

-2. 1. Into Lua console:
```
wesnoth.game_events.on_mouse_button = function(x, y, button, event)
    if not (button == "left" and event == "click") then
        return false
    end
    if not(wesnoth.interface.get_selected_hex()) then
        return false
    end
    local unit = wesnoth.units.get(wesnoth.interface.get_selected_hex() )
    if unit.type~="Mage" then
        return false
    end
    wesnoth.interface.select_unit(nil)
    wesnoth.interface.add_chat_message("Mage was selected")
    return true
end
```
-2. 2. In UI:
Select a mage.

### Expected behavior

1. no gray screen, upon deselecting unit, while it's being hovered over.

2. deselected unit.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Mahoyomu**
### Goal of the PR
- Resolves #9213.
### How does the PR work?
- By adding an allowable case to the determining condition of resetting gui highlight.
### Does it resolve any reported issue?
- #9213
### If not a bug fix, why is this PR needed? What use cases does it solve?
- This is a bug fix.

## To do

Adjust possibly missed related method. The fix is not so efficient, so if there's a better idea etc. perhaps I'll try that one instead, but this fix also seems to work at least.

This PR is Ready for Review.

## How to test
Compile and run, see the test video I might upload later if needed, or see changes in the src.

### CODE REVIEW

**Comment by Pentarctagon** [comment]
@CelticMinstrel any concerns with this?

**Comment by CelticMinstrel** [comment]
I can't say I fully understand what's going on with this change, but I don't see anything alarming. If it's tested and works, then it's probably okay to merge.

**Comment by Pentarctagon** [comment]
@Mahoyomu this was tested, I assume?

**Comment by CelticMinstrel** [comment]
With that extra commit, this could be merged as a rebase but should not be squashed. Alternatively, we can wait for @Vultraz to determine the proper fix for that unrelated crash, then revert it in this PR and squash.

**Review by Vultraz — APPROVED** [review]
Since we want the last commit to remain intact, could you rebase this into two commits and I'll merge.

**Comment by CelticMinstrel** [comment]
@Vultraz Since the other two commits are merge commits, I think rebasing onto master will just delete them. You can try it locally first if you're worried.

**Comment by babaissarkar** [comment]
Rebase merged into master via command line. Manually closing this.

**Comment by CelticMinstrel** [comment]
The merged commits are 0c2b035 and 88c613.

**Pull request closed without merging**
