### PR TITLE
Added spritsheet generator

### PR DESCRIPTION
**Pull request by Vultraz**
Pulls in my old spritesheet generator code from the `old_master_20181015` with minor tweaks for code changes since then. Placing here for consideration.

This takes a folder with images and writes an assembled spritesheet to disk along with a config file.

### CODE REVIEW

**Comment by Pentarctagon** [comment]
@Vultraz are you going to merge this? At minimum, it still needs to be added to the various projectfiles/source lists and somehow be usable from the command line.

**Comment by Vultraz** [comment]
Yeah, I'll get to this soon.

**Comment by CelticMinstrel** [comment]
Doesn't this also need the code to load the spritesheet before it can be of any use? It's not helpful to be able to generate a spritesheet that you can't even use.

**Comment by Vultraz** [comment]
I'm getting to it....

**Comment by stevecotton** [comment]
Given that @doofus-01 is moving us to have metadata embedded in the image files, how will the two features interact?

**Comment by doofus-01** [comment]
Credits & copyrights are the issue, not metadata.  However it all gets merged, the spritesheets are still images, so they can have metadata.  I think we just need to figure out how the info and copyrights get merged, no matter whether it's logged in the image or in a CSV.

**Pull request merged**
