### PR TITLE
Improve performance of the game history query by a lot.

### LINKED ISSUE #7988: "Match History" on `1.17.22+dev` times out if you haven't played games yet
### Game and System Information

- **Version:** v1.17.22+dev (ae4242a430e-Clean) x86_64
- **Downloaded from:** built from source
- **Build info:** ? built from source.
- **OS:** ArchLinux

### Description of the bug

The "Match History" is not possible to open for me. See "steps" below

### Steps to reproduce the behavior

1. Start Wesnoth v1.17.22+dev (ae4242a430e-Clean)
2. Choose an account that has no games on 1.17 yet, and log in into multiplayer
3. Click the button "Match History"

### Expected behavior

Something useful shows up

Actually observed:
* the UI freezes for 5 seconds, after which a modal window "timeout" it shown as on the screenshot
* closing the modal window opens another modal window (see screenshot). This window doesn't have any games that it should have. (Playing just 1 game will fix the behavior, and more than one last game will be shown, see below on that.)

### Additional context

In essence, there are two bugs: about a modal window for "match history" being opened at all after a "timeout", and about the fact that there's a timeout in the first place. My internet connection is pretty stable, there should be no timeouts, yet the timeout is reproducible.

Note that after I've played 1 game on the 1.17 server, the "Match History" started working, showing me more games than just that one new.

The bug looks very similar to what's being reported by @knyghtmare here: https://github.com/wesnoth/wesnoth/issues/7533#issuecomment-1520113286  I'm creating a dedicated issue here because the original issue there was different.

### PR DESCRIPTION
**Pull request by Pentarctagon**
Fixes #7988

I have no idea why this helps anything at all, since my understanding has always been that inner joins vs a big where clause are essentially two different ways of accomplishing the same thing, but changing the two inner joins to a where clause improves query performance from 6.3 to 0.012 seconds (when running the query from the website VM). As best I can tell from the explain plans, the inner joins are somehow confusing the query optimizer to use the game_content_info table as the starting point of the query instead of the game_info table, but why it's doing that or why it has such a large impact remains a mystery.

------

Current query:
```
select 
  game.GAME_NAME, 
  game.START_TIME, 
  GROUP_CONCAT(CONCAT(player.USER_NAME, ':', player.FACTION)) as PLAYERS, 
  IFNULL(scenario.NAME, '') as SCENARIO_NAME, 
  IFNULL(era.NAME, '') as ERA_NAME, 
  IFNULL(GROUP_CONCAT(distinct mods.NAME), '') as MODIFICATION_NAMES, 
  case 
  when game.PUBLIC = 1 and game.INSTANCE_VERSION != 'trunk' 
  then concat('https://replays.wesnoth.org/', substring(game.INSTANCE_VERSION, 1, 4), '/', year(game.END_TIME), '/', lpad(month(game.END_TIME), 2, '0'), '/', lpad(day(game.END_TIME), 2, '0'), '/', game.REPLAY_NAME) 
  when game.PUBLIC = 1 and game.INSTANCE_VERSION = 'trunk' 
  then concat('https://replays.wesnoth.org/', game.INSTANCE_VERSION, '/', year(game.END_TIME), '/', lpad(month(game.END_TIME), 2, '0'), '/', lpad(day(game.END_TIME), 2, '0'), '/', game.REPLAY_NAME) 
  else '' 
  end as REPLAY_URL, 
  case 
  when game.INSTANCE_VERSION != 'trunk' 
  then SUBSTRING(game.INSTANCE_VERSION, 1, 4) 
  else 'trunk' 
  end as VERSION 
from wesnothd_game_info game 
inner join wesnothd_game_player_info player 
   on exists 
  ( 
    select 1 
    from wesnothd_game_player_info player1 
    where game.INSTANCE_UUID = player1.INSTANCE_UUID 
      and game.GAME_ID = player1.GAME_ID 
      and player1.USER_ID = 132039
  ) 
  and game.INSTANCE_UUID = player.INSTANCE_UUID 
  and game.GAME_ID = player.GAME_ID 
  and player.USER_ID != -1 
  and game.END_TIME is not NULL 
inner join wesnothd_game_content_info scenario 
   on scenario.TYPE = 'scenario' 
  and scenario.INSTANCE_UUID = game.INSTANCE_UUID 
  and scenario.GAME_ID = game.GAME_ID 
inner join wesnothd_game_content_info era 
   on era.TYPE = 'era' 
  and era.INSTANCE_UUID = game.INSTANCE_UUID 
  and era.GAME_ID = game.GAME_ID 
left join wesnothd_game_content_info mods
   on mods.TYPE = 'modification' 
  and mods.INSTANCE_UUID = game.INSTANCE_UUID 
  and mods.GAME_ID = game.GAME_ID 
group by game.INSTANCE_UUID, game.GAME_ID 
order by game.START_TIME desc 
limit 11 offset 0;
```
Explain plan:
```
+------+--------------------+----------+--------+---------------------+-------------+---------+-----------------------------------------------------------+---------+----------------------------------------------+
| id   | select_type        | table    | type   | possible_keys       | key         | key_len | ref                                                       | rows    | Extra                                        |
+------+--------------------+----------+--------+---------------------+-------------+---------+-----------------------------------------------------------+---------+----------------------------------------------+
|    1 | PRIMARY            | scenario | ALL    | PRIMARY             | NULL        | NULL    | NULL                                                      | 4272062 | Using where; Using temporary; Using filesort |
|    1 | PRIMARY            | game     | eq_ref | PRIMARY             | PRIMARY     | 148     | forum.scenario.INSTANCE_UUID,forum.scenario.GAME_ID       | 1       | Using where                                  |
|    1 | PRIMARY            | era      | ref    | PRIMARY             | PRIMARY     | 550     | forum.scenario.INSTANCE_UUID,forum.scenario.GAME_ID,const | 1       | Using where                                  |
|    1 | PRIMARY            | mods     | ref    | PRIMARY             | PRIMARY     | 550     | forum.scenario.INSTANCE_UUID,forum.scenario.GAME_ID,const | 1       | Using where                                  |
|    1 | PRIMARY            | player   | ref    | PRIMARY,USER_ID_IDX | PRIMARY     | 148     | forum.scenario.INSTANCE_UUID,forum.scenario.GAME_ID       | 4       | Using where                                  |
|    2 | DEPENDENT SUBQUERY | player1  | ref    | PRIMARY,USER_ID_IDX | USER_ID_IDX | 152     | const,forum.game.INSTANCE_UUID,forum.game.GAME_ID         | 2       | Using index                                  |
+------+--------------------+----------+--------+---------------------+-------------+---------+-----------------------------------------------------------+---------+----------------------------------------------+

```

------

New query:
```
select 
  game.GAME_NAME, 
  game.START_TIME, 
  GROUP_CONCAT(CONCAT(player.USER_NAME, ':', player.FACTION)) as PLAYERS, 
  IFNULL(scenario.NAME, '') as SCENARIO_NAME, 
  IFNULL(era.NAME, '') as ERA_NAME, 
  IFNULL(GROUP_CONCAT(distinct mods.NAME), '') as MODIFICATION_NAMES, 
  case 
  when game.PUBLIC = 1 and game.INSTANCE_VERSION != 'trunk' 
  then concat('https://replays.wesnoth.org/', substring(game.INSTANCE_VERSION, 1, 4), '/', year(game.END_TIME), '/', lpad(month(game.END_TIME), 2, '0'), '/', lpad(day(game.END_TIME), 2, '0'), '/', game.REPLAY_NAME) 
  when game.PUBLIC = 1 and game.INSTANCE_VERSION = 'trunk' 
  then concat('https://replays.wesnoth.org/', game.INSTANCE_VERSION, '/', year(game.END_TIME), '/', lpad(month(game.END_TIME), 2, '0'), '/', lpad(day(game.END_TIME), 2, '0'), '/', game.REPLAY_NAME) 
  else '' 
  end as REPLAY_URL, 
  case 
  when game.INSTANCE_VERSION != 'trunk' 
  then SUBSTRING(game.INSTANCE_VERSION, 1, 4) 
  else 'trunk' 
  end as VERSION 
from wesnothd_game_player_info player , wesnothd_game_content_info scenario , wesnothd_game_content_info era , wesnothd_game_info game
left join wesnothd_game_content_info mods
   on mods.TYPE = 'modification' 
  and mods.INSTANCE_UUID = game.INSTANCE_UUID 
  and mods.GAME_ID = game.GAME_ID 
where exists 
  ( 
    select 1 
    from wesnothd_game_player_info player1 
    where game.INSTANCE_UUID = player1.INSTANCE_UUID 
      and game.GAME_ID = player1.GAME_ID 
      and player1.USER_ID = 132039
  ) 
  and game.INSTANCE_UUID = player.INSTANCE_UUID 
  and game.GAME_ID = player.GAME_ID 
  and player.USER_ID != -1 
  and game.END_TIME is not NULL 
  and scenario.TYPE = 'scenario' 
  and scenario.INSTANCE_UUID = game.INSTANCE_UUID 
  and scenario.GAME_ID = game.GAME_ID 
  and era.TYPE = 'era' 
  and era.INSTANCE_UUID = game.INSTANCE_UUID 
  and era.GAME_ID = game.GAME_ID 
group by game.INSTANCE_UUID, game.GAME_ID 
order by game.START_TIME desc 
limit 11 offset 0;
```
Explain plan:
```
+------+--------------+-------------+--------+---------------------+-------------+---------+---------------------------------------------------------+------+---------------------------------+
| id   | select_type  | table       | type   | possible_keys       | key         | key_len | ref                                                     | rows | Extra                           |
+------+--------------+-------------+--------+---------------------+-------------+---------+---------------------------------------------------------+------+---------------------------------+
|    1 | PRIMARY      | <subquery2> | ALL    | distinct_key        | NULL        | NULL    | NULL                                                    | 502  | Using temporary; Using filesort |
|    1 | PRIMARY      | game        | eq_ref | PRIMARY             | PRIMARY     | 148     | forum.player1.INSTANCE_UUID,forum.player1.GAME_ID       | 1    | Using where                     |
|    1 | PRIMARY      | scenario    | ref    | PRIMARY             | PRIMARY     | 550     | forum.player1.INSTANCE_UUID,forum.player1.GAME_ID,const | 1    | Using where                     |
|    1 | PRIMARY      | era         | ref    | PRIMARY             | PRIMARY     | 550     | forum.player1.INSTANCE_UUID,forum.player1.GAME_ID,const | 1    | Using where                     |
|    1 | PRIMARY      | mods        | ref    | PRIMARY             | PRIMARY     | 550     | forum.player1.INSTANCE_UUID,forum.player1.GAME_ID,const | 1    | Using where                     |
|    1 | PRIMARY      | player      | ref    | PRIMARY,USER_ID_IDX | PRIMARY     | 148     | forum.player1.INSTANCE_UUID,forum.player1.GAME_ID       | 4    | Using where                     |
|    2 | MATERIALIZED | player1     | ref    | PRIMARY,USER_ID_IDX | USER_ID_IDX | 4       | const                                                   | 502  | Using index                     |
+------+--------------+-------------+--------+---------------------+-------------+---------+---------------------------------------------------------+------+---------------------------------+

```

### CODE REVIEW

**Comment by Wedge009** [comment]
I'm also not familiar with database optimisation. This is server code, so I suppose we can't see any difference until wesnoth.org is updated. I tested again just now and the first two requests hit the time-out, third request came back fairly quickly presumably due to the caching.

**Comment by ProditorMagnus** [comment]
I have worked with oracle sql performance.

```
exists 
  ( 
    select 1 
    from wesnothd_game_player_info player1 
    where game.INSTANCE_UUID = player1.INSTANCE_UUID 
      and game.GAME_ID = player1.GAME_ID 
      and player1.USER_ID = 132039
  ) 
```
This part looks quite dangerous, consider if it can be moved to regular join instead of subquery to run for every potential row.

```
from wesnothd_game_info game 
inner join wesnothd_game_player_info player
on game.INSTANCE_UUID = player.INSTANCE_UUID and game.GAME_ID = player.GAME_ID and player.USER_ID = 132039
```

**Comment by Pentarctagon** [comment]
Exists clauses can be dangerous if they're expensive, but in this case it shouldn't be too bad given it's using an index. Also it does need to be an exists clause here since otherwise the list of players returned would only include the person being searched instead of all players.

**Comment by ProditorMagnus** [comment]
What goes wrong when you just remove the exists part from join? I think by game.GAME_ID you should find all involved players.

**Comment by ProditorMagnus** [comment]
MATERIALIZED | player1 explains why now it is fast.

**Comment by ProditorMagnus** [comment]
|    1 | PRIMARY      | <subquery2> | 502  | 
|    1 | PRIMARY      | scenario         | 4272062 | 
Thats the main performance difference. When starting with materialized view you get 502 rows to include in next filters, while when starting from scenario there are millions.

**Comment by Pentarctagon** [comment]
> | 1 | PRIMARY | | 502 |
> | 1 | PRIMARY | scenario | 4272062 |
> Thats the main performance difference. When starting with materialized view you get 502 rows to include in next filters, while when starting from scenario there are millions.

Yeah, that was pretty clear at least. What's weird is why using `inner join` confuses it so much that the query optimizer would choose such a sub-optimal approach.

**Pull request merged**
