### PR TITLE
Add Xcode Travis build

### PR DESCRIPTION
**Pull request by hrubymar10**

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Looks good to me!

**Comment by hrubymar10** [comment]
Ofc, but btw It worked in mine fork: https://travis-ci.org/hrubymar10/wesnoth/builds/343448687?utm_source=github_status&utm_medium=notification

I hope that wesnoth isn't broken now at all

**Comment by GregoryLundberg** [comment]
I fixed the compile errors a while ago. I there has only been one substantive changes since then, and it passed.

**Comment by hrubymar10** [comment]
Well, then all should be fine. Thanks @GregoryLundberg

**Comment by CelticMinstrel** [comment]
Haha, invalid option `--version` (apparently xcodebuild only uses one dash, not two). I wonder if there's anything we can do about that?

clang and gcc both accept `-v` as well, but xcodebuild doesn't even accept _that_.

---

So it looks like the build works, which is great. It doesn't run tests (either the Boost or the WML tests), which I guess is fine since they're run on some of the linux builds. I somehow kinda feel like something is missing though? Looking at the xcodebuild options, maybe you should pass `-alltargets`?

**Comment by hrubymar10** [comment]
`--version` argument is... Well if I'll remove line 37 then problem will disappear, it will work without problem but travis will show smt like this:
2018-02-19 at 19 21
If it is fine then I can do that.

`-alltargets` will technically work but `unit_tests` build will very probably fail... I would like to stick it to Wesnoth.app which covers `liblua.a`, `wesnothd` and `Wesnoth` itself

**Comment by hrubymar10** [comment]
Travis build succeeded @CelticMinstrel .

**Comment by CelticMinstrel** [comment]
It's not _that_ important to build campaignd or the unit tests, so I guess we can forget about `-alltargets`, at least for now.

**Pull request merged**
