### PR TITLE
UtBS: Use a lower-case letter for "taurochs"

### PR DESCRIPTION
**Pull request by stevecotton**
It's the name of a species, so lower-casing it is consistent with #6067.

I intend to backport this too, I spotted it while resolving fuzzy strings.

### CODE REVIEW

**Comment by Wedge009** [comment]
It's interesting because Wesnoth seems to make an exception to the lower-case policy for unit names, eg [Fire Drake](https://units.wesnoth.org/1.16/mainline/en_US/Fire%20Drake.html). However, all of these changes appear to be referring to taurochs, the animal in general not the unit specifically. So it makes sense to me to make the change.

**Review by knyghtmare — APPROVED** [review]
Seems rather trivial but yeah, it's okay.

**Review by nemaara — APPROVED** [review]

**Comment by Wedge009** [comment]
One failing test for a string change... looks like a failure of the test itself, though?

**Comment by stevecotton** [comment]
> One failing test for a string change... looks like a failure of the test itself, though?

Looks like the build broke long before it would have reached this file - seems there's no logs from any stage after checkout.

**Pull request merged**
