### PR TITLE
Adding myself to credits

### PR DESCRIPTION
**Pull request by fusaty**
Based on https://wiki.wesnoth.org/SlovakTranslation

### CODE REVIEW

**Comment by Wedge009** [comment]
Good idea. It just looks like the existing entries follow alphabet ordering (at least by Latin characters) by first name, maybe you should be inserted before Stanislav.

**Comment by fusaty** [comment]
Thank you. You are right, I didn't notice. It's fixed now.

**Comment by Wedge009** [comment]
This seems reasonable to me and is not a big change - any objection to merging?

**Comment by Wedge009** [comment]
I note the wiki page states your contributions for 1.17 + 1.18 so I'll back-port this to 1.18 branch too.

**Comment by Pentarctagon** [comment]
I pinged ElveniskoSVK on Discord just to confirm that this looks right, but haven't heard back yet.

**Pull request merged**
