### PR TITLE
Make sure animations are skipped when skipping animations in replays

### LINKED ISSUE #8227: Show death and level-up animations while replaying saves with "Skip animation"
### Game and System Information

- **Version: The Battle for Wesnoth version 1.17.23+dev x86_64**
- **Downloaded from: Default**
- **OS: Running on Debian GNU/Linux**

### Description of the bug

When checking the "Skip animation" toggle when replaying a save, the animations for death and level-up are still played at nominal speed.

### Steps to reproduce the behavior

- Load a save.
- Enable the "skip animation" toggle.
- Replay until one unit dies or levels up
- Watch animations

### Expected behavior

These animations are skipped when enabling the "skip animation" toggle.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Pentarctagon**
Fixes #8227

---

I haven't looked deeper to see if there's anything else that needs to be done yet, but it does fix the death animation playing at least.

### CODE REVIEW

**Comment by gfgtdf** [comment]
Have you tested that this also skips the advancement "fadein/fadeout" animation now? from looking at the code this functions is mainly used in certain functions that use the unit animator not the unit animator itself.


Also i wonder whether [delay] is skipped in replays, i think it should be.

**Comment by Pentarctagon** [comment]
So far I've only looked at the death animation. There isn't anything in `udisplay.cpp` about advancements though, so I'd suspect that it won't fix that part.

**Comment by Pentarctagon** [comment]
Yep, doesn't fix the advancements part of the issue.

**Comment by gfgtdf** [comment]
Maybe we could  also check for do_not_show_anims() in unit_animator::wait_for_end() and similar function

**Comment by Pentarctagon** [comment]
Added the fix for advancements as well. The only other instance I'm not sure about is https://github.com/wesnoth/wesnoth/commit/99be6c52a44ea4321109080da87fbe5fb5391500#diff-07cbc854496f2facc551dd5184013a7c84ee0f5d6eaa528e8b581ca0947d6e1fL376

**Pull request merged**
