### PR TITLE
WML: Support [filter_side] in [item].

### LINKED ISSUE #1477: Side filters in [item] (GNA #23555)
**[Original submission](https://gna.org/bugs/index.php?23555)** by anonymous on 2015-04-30

currently [items] allows a team_name= attribute to specify for which side the item is displayed, it would be better if [item] allowed a side filter to specify for which side the item is displayed.

(Reproduced on windows)
Release: 1.13
Priority: 5 - Normal
Severity: 2 - Minor

### PR DESCRIPTION
**Pull request by jostephd**
If [filter_side] is present then "team_name" is ignored.

Fixes #1477.

Constructing a comma-separated set of team names is ugly but I didn't want to change `add_overlay` and the `overlay` struct. https://github.com/wesnoth/wesnoth/blob/cc98bcd9d015a852dbec2053f300ce4682c4765d/src/overlay.hpp#L23-L26

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Just wondering, but... this doesn't fully support #1477, does it? I mean, if sides 1 and 2 are allied, it won't let you make a label visible only to side 1, right?

I'm not saying this is a problem, but...

**Comment by gfgtdf** [comment]
the current 'per team' implementation is  also somwhzow bas in particular it doesnt play well with the current teams alliances syntax: the follwing example:

side1 is in team team1
side2 is in team team2
side3 is in team team1,team2 (allied to both)

with the current syntax it is afaik not possibel to create a label that is visible for 'team1' that is side1 and side3 but not for side2, this is because the check in display used substring, so visibility to team1,team2 imples visibility to team1 while actually the opposite way would make more sense. Of yourse this can be fixed, but maybe it makes more sense to change it to just sote the sides instead.


Another implementation woudl be to, instead of storeing sides ot team in the the overlay object to store the compltete filter in the overlay object and evaluate it when the item is drawn, this way the items visiblitity would (actuall this might not be true, it very much depnds on how exactly the drawing code works) automaticially be updated when the properties of the side change.

**Comment by CelticMinstrel** [comment]
I'd say that's a separate situation to this @gfgtdf; but assuming we stick to specifying team rather than side, the correct way to determine if a label is visible to a side would be to split the label's team name and the side's team name and perform a set intersection. If it's empty, the label is not visible.

**Comment by CelticMinstrel** [comment]
So basically this ends up taking the union of the matched side's teams, right? (Or concatenation technically, but in effect it should come out the same.)

**Comment by jostephd** [comment]
Yes. intf_add_tile_overlay will call add_overlay with team_name set to the union of all teams that at least one matched side is on.

**Pull request merged**
