### PR TITLE
Convert some fail-on-success unit tests to pass-on-success

### PR DESCRIPTION
**Pull request by stevecotton**

### CODE REVIEW

**Comment by AI0867** [comment]
What is the point of this conversion? If it is to run more tests in a batch, I would prefer this approach: https://github.com/wesnoth/wesnoth/pull/4582#issuecomment-557785976.

**Comment by stevecotton** [comment]
The main reason is just coding style, like removing double-negatives from English text.

**Comment by stevecotton** [comment]
@AI0867 are you ok with me merging this?

**Comment by AI0867** [comment]
I had some concerns about not having failing tests meaning we might not notice if events or tests break, but that seems mostly unfounded, given the remaining tests.

I have no further objections.

**Pull request merged**
