### PR TITLE
[WIP] Upgrade windows installer

### PR DESCRIPTION
**Pull request by aquileia**
Pull request so that loonycyborg can test each commit with his toolchain.

WIP status as I plan to add further features:
- link the localized manual instead of maual.en.html
- upgrade patches

### CODE REVIEW

**Comment by gfgtdf** [comment]
I still think an automatic updater would be nice. But it might be not trivial to implement, first need some librariry to download files (https mostlikeley, i think it can be done with boost asio) and a libary to extract archieve files (zip most likeley) and of course a server to host the update files.

Another problem is that wesnoth would need to be restarted multiple times when updating: 
First we'd need to restart wesnoth to get admin rights (to change files)
Then wesnoth could change the files but it cannot delete them because it might have a lock on them. So it need to be restarted a second time to delete the old files
Then wesnoth would need to be restarted a thrid time to remove admin provileges

When restarting wesnoth for updating we of cource don't need to reload most data (the data inside data/) but some of the data (like the widgets which are used in the updater dialog) would need to be loaded every time so that migth be a little annyoing.

Another option is to have the updater as a seperate updater.exe this migth be easier to implemen since we could just use some language that supports things like http requests and zip files in their framework also it migth neeed less loading time because some unused data doesnt need to be lodaded. But it also has some disadvatages: 1) the updater would not look wesnoth themed. 2) in order to check whether teh game needs updated wesnoth.exe woudl need to be able to read http requests anyway.

Any opinions ?

**Comment by aquileia** [comment]
Going through your issues:
- NSIS can extract archives and has modules for multiple compressions
- NSIS can download files with the NSISdl module
- NSIS can request admin rights at the start of the installation
- NSIS displays the Wesnoth banner on the first dialog windows, so it's Wesnoth branded, but not Wesnoth themed
So basically, Wesnoth could just scan for an update, start NSIS and shut down so that it doesn't lock files. The file NSIS links to would be replaced with every release, thus the same NSIS installer could handle any updates (updating version numbers in the Registry and the Shortcuts might be an issue, but there's probably a solution for that too).
As the user starts Wesnoth manually after the update, all issues with cached data and admin rights aren't relevant.

The reasons why I'm going for separate update packages are:
- As you said, baldras can't handle the bandwidth
- It requires no changes to Wesnoth itself
- We can upgrade versions we already released, whereas a built-in updated can't
- Implementing an auto-updater could have unforseen problems. We already had our share of features that weren't finished due to unforseen complexity.

**Comment by gfgtdf** [comment]
```
So basically, Wesnoth could just scan for an update, start NSIS and shut down so that it doesn't lock files.
```
this also requires downloading files (the NSIS installer) by the wesnoth application. I actualy think this is the hardest part so it's wrong to say It requires no changes to Wesnoth itself.


```
updating version numbers in the Registry and the Shortcuts might be an issue
```

Hmm maybe we shoudl just have drom teh minor version number from those link if we have an automatic updater.

```
As you said, baldras can't handle the bandwidth, whereas we can upload update installers to sourceforge
```
A custom auto updater could downlod from sourceforge aswell.

**Comment by aquileia** [comment]
I think you misunderstand me. The two options with NSIS are
a) Bundle an auto-update installer with wesnoth.exe which is called by Wesnoth. The new verion number might need to be provided as a command line argument, but besides that the updater would be standalone. We would need a direct link (no sourceforge redirection) to the archive containing the patch.
b) Provide an update package with each new release, which includes the changed files itself. The user manually downloads the updater each time he wants to update Wesnoth to a new release.

Neither of these require Wesnoth.exe to download the update.

BTW, if baldras were upgraded, both options could be handled over the addon server, but I doubt that's going to happen...

**Comment by gfgtdf** [comment]
Hm i see but doesn't wesnoth.exe still need to 'ask' the server whether a new update is available (whether to start the updater?)

**Comment by aquileia** [comment]
Yes, Wesnoth would need a way to check the version of the latest release. Maybe something as simple as a
- fake addon on the addon server 
- lobby message on the official multiplayer servers
could do the trick.

**Comment by Vultraz** [comment]
What about a manifest file on baldras?

**Comment by chisquare130** [comment]
The indentions in two Chinese GPL license files are fine. 
The only thing I can say is that there is no need to include Traditional Chinese reference in the Simplified Chinese version. "Traditional Chinese" is merely like using a complicated version of Chinese font and having a little Taiwan dialect, so it's a little strange to include it as a reference.

**Comment by gfgtdf** [comment]
do we really need a licence in the update installer? I thought the user already accepted the license when installing the game the first time.

**Comment by aquileia** [comment]
@chisquare130
Thanks! I'll remove the reference and add the link to the original.

@gfgtdf 
The licences (and all the other commits you currently see) are for the regular installer. After I finished polishing that up, I'll start working on the updater.

It should be pretty simple - read the original installation options (Language, InstDir, StartMenuFolder) from the registry, find the userdata directory (which unfortunately isn't registered with the other options), replace anything containing the version number (registry and shortcuts), and apply the patch.

**Comment by aquileia** [comment]
Part 1 (restructuring the Installer) is done. I'll rebase to tidy up the commits, then I'll merge to master and 1.12 (except the removal of the userdata selection page).

Part 2 will be creating update packages via manual installers.

Part 3, if a suitable hosting service is found, would be adding auto-update functionality via an installer that downloads an archive of the changed files.

**Comment by aquileia** [comment]
Closed due to merging the current state, I'll reopen the PR when I have something substantial on step 2.

**Pull request closed without merging**
