### PR TITLE
Enable a C++20 CI build

### PR DESCRIPTION
**Pull request by Vultraz**

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I think it's probably a bad idea for a C++20 CI to completely replace existing C++17 CIs.

You're not trying a C++20 Mac build? I'm not sure if it will work, but there's at least a chance that it will. (May require using 10.15 as the image though.)

**Comment by Vultraz** [comment]
CI times are long enough without adding new runs to the set. If you think I should make one of the Mac jobs build against 20, I can add that.

**Comment by Pentarctagon** [comment]
Also we were already flagged once for using too many CI resources, so adding more jobs (especially Windows or macOS) would be a bad idea.

**Comment by CelticMinstrel** [comment]
In that case I think this is best left as "on hold" until such time that we officially move to C++20. It seems like a terrible idea to _not_ build each of our targets on C++17, so if the only way to do C++20 is to _replace_ existing jobs, I think it's best not to merge it to master.

You could still make use of this branch to periodically test C++20 stuff as needed, even without merging it into master.

**Comment by Pentarctagon** [comment]
@CelticMinstrel your OS limitations more or less mean we're not getting to C++20 for a long time. So it doesn't really make sense to keep this open for multiple years - we should either have a job testing it or leave CI the way it is.

**Comment by Vultraz** [comment]
I shall leave it to Pent to decide what to do with this PR as-is, but I will say I'm not inclined to spend extra effort to create CI runs on a separate branch. If the goal of the tests is coverage, having a C++20 build is absolutely useful.

**Comment by Pentarctagon** [comment]
I'm not sure to be honest. They're there so it makes sense to have a CI job covering them, but it also doesn't make sense to me to keep adding use of these features in a conditional way when there's basically no prospect for unconditionally using them. The bar that's been set even for just increasing the macOS minimum required version to 10.15 seems, in practice, to be all but impossible to meet.

**Comment by CelticMinstrel** [comment]
I'm just saying that it doesn't make sense to remove one of the jobs that checks an officially supported configuration in order to instead check an unofficially supported, work-in-progress configuration. I have a feeling there really isn't any good answer here. Ideally we could check everything we want to check, but with GitHub's limitations, that just won't work.

**Comment by soliton-** [comment]
We could run more configurations (not just C++20, we currently leave out a lot of combinations) just once a week or so.

**Comment by Pentarctagon** [comment]
Why though? There's literally a 0% chance we're ever actually going to be able to target C++20.

**Comment by soliton-** [comment]
Why run more configurations? Because it gives us a higher chance to see issues.

**Comment by Pentarctagon** [comment]
No, why are we pursuing anything at all related to C++20 support? The criteria for increasing the macOS minimum version requirement is essentially "a feature that Wesnoth very badly needs, which exists in the standard library, and doesn't have an equivalent available in a dependency (ie: boost)". I can't imagine what such a feature would be, and even if there were such a feature it'd be irrelevant anyway if it requires a macOS version past 10.15.

**Comment by Vultraz** [comment]
I'm just going to be blunt: This change is specifically useful for me, since right now I'm the only one doing anything with C++20. I'm looking for more test coverage. It would make my life easier by ensuring I don't commit code that only works on Windows without having to go through hoops maintaining a separate branch just to do CI runs. As long as everyone is fine with any code using newer features being tested against my build alone, I'm happy to close this and continue as-is.

As for why pursuing anything relating to C++20 and later at at all... First, for my own edification, and second, because it's impractical never to progress past C++17 despite the utterly arbitrary standard we've set for bumping. Celmin's OS support is one thing. But we could have used the same "absolutely necessary features only" argument back when we were using C++03. We had the `BOOST_FOREACH` macro, why do we want native for loops? Why replace working boost::mpl code with static constexpr? Who needs `auto` when you have typedefs? Lambdas when you have functor structs? Emplace when you can just pass pointers around?

The larger you allow the gulf to grow between modern features and your codebase, the harder it is to maintain and the harder it is to modernize when the time inevitably comes. I've been doing _everything possible_ to make the eventual transition as seamless as possible. I fixed all the build issues when targeting C++20, figured out new library minimums, and added conditional code for features it's possible not everyone would support yet. (The standard feature flags means we don't even need to do things per-standard.) My idea was eventually that we would target 20/23/etc. by default while still retaining build compatibility for whatever feature can't be used yet. Then, by slowly encouraging the use of newer code, that there would eventually be enough critical mass to drop compat paths eventually instead of getting stuck in this pointless debate again and again.

Finally, however, I am not inclined to continue working on a project that eschews modern C++ in perpetuity. It's not an issue right now, but if in the coming years we're still stubbornly stuck on C++17, I have serious doubts about my continued involvement with the project. I've been incredibly busy the past few years with college, and though I have some free time now, having graduated, that's not going to last forever. It's honestly rather insulting the level to which we're willing to bend over backwards to accommodate celmin, to the extent of *freezing the codebase in perpetuity* - far beyond what is necessary given their technical limitations - but when I attempt to change a single CI config I get bikeshed into oblivion and told it's unnecessary.

**Comment by CelticMinstrel** [comment]
> It's honestly rather insulting the level to which we're willing to bend over backwards to accommodate celmin, to the extent of _freezing the codebase in perpetuity_

If it were truly solely to accommodate me, then I can definitely agree that that's kinda silly. Accommodating one dev at the expense of three others is obviously not a good choice. I didn't think it was solely to accommodate me, however. Soliton for example also appears to roughly agree, and for reasons that don't boil down to "so that I can build the game on my computer".

But I also think that the concept of _freezing the supported level in perpetuity_ is not at all unreasonable. I'm working on another project which has been (at least officially) frozen at C++11 and have no particular interest in upgrading it past that, because everything I need to do works just fine with C++11 and Boost. That said, I also wouldn't say it's absolutely necessary to freeze the requirements in perpetuity… and in any case it makes less sense for Wesnoth than for the aforementioned project (which is an old retro game).

Even if not freezing the requirements though, for something intended to be stable you should certainly not use the bleeding edge – updating to C++20 right now (with some caveats for Mac support) _may_ be barely viable, but we definitely shouldn't even _begin_ to contemplate C++23 for at _least_ three more years.

> I fixed all the build issues when targeting C++20

This is absolutely a good thing. If there's anything that makes the game _fail_ to build with C++20 or C++23, then of course it should be fixed even if we're not updating the minimum standard. If there are warnings that are new in C++20 or C++23, then those should be fixed too, as long as they're real and not false positives.

> The larger you allow the gulf to grow between modern features and your codebase, the harder it is to maintain and the harder it is to modernize when the time inevitably comes.

I have a feeling you're greatly exaggerating this. To begin with, the idea of always updating your code as new features come out in the language is an extremely terrible one – if it helps you track down and isolate old issues, then sure, but don't fix what's not broken. I'm not saying you shouldn't update your code, mind you, but updating it solely for the sake of using new features is not something you should be doing.

So that means that modernizing code should be done incrementally, a bit at a time.

> but when I attempt to change a single CI config I get bikeshed into oblivion and told it's unnecessary.

I don't think we're saying it's unnecessary. I think it's good to have a CI job that checks C++20 or C++23 support. The problem is, we have limited CI time, and it's _not_ good to have a C++20 check at the expense of one of the core, required checks. It's not that it's unnecessary, just that it's not a higher priority than the jobs we're already running in the CI.

It's not necessarily the case that this should be taken as an argument to not run a C++20 job at all. Theoretically speaking, maybe it could even be an argument for requesting funding or donations to increase our CI time so we can run additional jobs. Though I don't know whether that would actually be a worthwhile thing to put money into.

But even if we don't do such a thing, I don't see the issue with simply having another branch for running C++20 checks. We could easily updates _all_ jobs to C++20 here on this `ci20` branch (and turn off non-code jobs like copyright or whitespace checks). We could then update the `ci.yml` to enable CI runs on this branch without even opening a PR, and just merge master into the branch a few times a week (or whenever you have something C++20-related that you're working on) to run the C++20 checks.

This all boils down to the fact that we can't just run as many jobs as we want on GitHub CI. If we could, then we should have all sorts of combinations that we don't already do – as Soliton noted, it seems there are even some configurations missing for C++17, and it would definitely make sense to have a C++20 set, and a C++23 set, and yes, even a C++26 set. But GitHub CI doesn't let us do that, so we have to make sacrifices.

**Comment by Pentarctagon** [comment]
https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#minute-multipliers has the relative price (if we were paying for our resource usage), so we could very likely get away with running multiple more Linux jobs in different configurations if we build only the Release build for macOS instead of Release+Debug.

**Comment by Vultraz** [comment]
If we’re paying for CI time, we could also go for more powerful runners to cut use time. 🤔

**Comment by Pentarctagon** [comment]
I mean, we're not, but we're much less likely to be flagged for excess usage again if we reduce the macOS (and Windows) jobs from 2 to 1 and then replace them with a couple/few Linux jobs. 1 macOS and 1 Windows job is equivalent to 12 Linux jobs.

**Comment by gfgtdf** [comment]
Especially If one MacOS builds costs us as much as 10 Linux builds then I also support removing the MacOS debug build in favor of a cpp20 Linux build

**Comment by CelticMinstrel** [comment]
I can't think of any strong reason to reduce the number of Mac/Linux builds. The only thing I'm uncertain of is whether it's better to remove the debug build or the release build.

**Comment by Pentarctagon** [comment]
The Release build is where tests are run since Debug takes a while to run them, so Debug would be the one to remove.

**Review by Pentarctagon — APPROVED** [review]

**Pull request merged**
