### PR TITLE
[WIP] Windows patch installer

### PR DESCRIPTION
**Pull request by aquileia**
- A few issues have to be ironed out (scons target, uninstaller)
- The translations need to be proof-read
- The MSVC related commits have to be merged separately

### CODE REVIEW

**Comment by gfgtdf** [comment]
Since i don't know the nsi langugae i cannot comment on this in detail but:
1) It looks like the changes to the vcprojectfile might casue merging conflics with the SDL2 branch.
2) It looks like you rename the wesnoth install directory during the update, if that's the case i think this i a very bad idea since it might invalidate existing shortcuts to wesnoth

**Comment by CelticMinstrel** [comment]
Any changes to the project files are probably going to cause merge conflicts with the SDL2 branch. There's not much that can be done about that.

**Comment by GregoryLundberg** [comment]
What is the status on this?

It's updating the VC9 project files, which don't even exist any more.

**Comment by Pentarctagon** [comment]
Closing as this is ancient and incremental updates are possible through Steam now.

**Comment by CelticMinstrel** [comment]
That said, I think this is still worthwhile if someone wanted to work on it. Not everyone uses Steam.

**Pull request closed without merging**
