### PR TITLE
EI S05: fade to silence when recounting the priestess's death

### PR DESCRIPTION
**Pull request by Dalas121**
In EI's S05, Owaec briefly recounts the bloody fate of his local priestess, killed by undead.

The scenario's music consists of wanderer.ogg and traveling_minstrels.ogg, which are inappropriate for encountering a mangled corpse.

Instead, fade the music out during this section.

### CODE REVIEW

**Comment by irydacea** [comment]
While I did provide this particular scene as an example, bear in mind that the player may encounter this while the music track plays, before triggering the cutscene; and after the cutscene completes, the music may continue playing.

I feel like in general this is not the right solution or the right problem. The problem is not so much the music during the cutscene but rather the music during the **scenario**. Coming to the outpost in the aftermath of what's implied to have been a complete massacre, and then spending some time around there cleaning things up, surely should be regarded as a somber scene as a whole, not just the encounter with the priestess's body.

> Gweddry: "Alas! The northern outpost has been **destroyed**..."

> Owaec: "Many of these farmers dug deep cellars connected to a network of caves. I hid as many villagers as I could once our scouts spotted the undead. They must have thought the villages abandoned, for they moved on swiftly westward, and yet... **I was not able to save everyone. Gweddry, their deaths weigh heavy on my heart.**"

(Not to mention that the undead do attack again as well later in the scenario, even if it's an ineffective endeavour.)

*Traveling Minstrels* as a music piece, to me, evokes a sense of light-hearted adventure and the discovery of the wonders of the world, neither of which are things taking place in this scenario or encouraged by the dialogue and scenery.

On a more technical note:

The combined diff claims that you modified the entire file. That doesn't seem correct, even though I can get the proper changes by marking the option to ignore whitespace. We generally request patches that affect more than they ought to do to be redone.

**Comment by irydacea** [comment]
To clarify, while silencing music during this scene in particular seems like a valid choice to me, it ultimately does not address the general issue.

**Comment by Dalas121** [comment]
Hmm, thanks for clarifying. I understand where you're coming from, but "Wanderer" and "Traveling Minstrels" were deliberate choices for S05, because that's how I had intended the scenario's atmosphere. After the caustic fumes of the Bitter Swamp and the deadly terrors of Mal Ravanal's Capitol, you finally return to familiar terrain. Instead of fighting necromancers and liches, you fight a rather silly dark adept, and a living bandit, neither of whom pose much of a threat either narratively or balance-wise. Plus you fight alongside an ally, for the first time in the campaign.

And against all odds, Owaec has even managed to survive, along with most of the villagers!  Some died, tragically I'm sure, but the overall tone of the scenario was supposed to be _"the undead are really dangerous, but at least we can catch our breaths here"_, which is why I chose the music in question.

> The combined diff claims that you modified the entire file. That doesn't seem correct, even though I can get the proper changes by marking the option to ignore whitespace. We generally request patches that affect more than they ought to do to be redone.

Huh, that's odd.  I'll close this PR and create a new one with a new branch tomorrow; hopefully that will fix the issue.

**Comment by irydacea** [comment]
Regarding the music playlist: fair enough.

Regarding the PR, next time you should amend or rebase commits and force-push to the same branch you used for the PR if you need to rewrite commits, instead of creating a new PR. Creating a new PR just makes it harder for people to find the previous discussion of it.

**Pull request closed without merging**
