### PR TITLE
Prefer pass by reference

### PR DESCRIPTION
**Pull request by midzer**
Minor performance enhancements by passing arguments as a (const) reference and not by value

### CODE REVIEW

**Comment by gfgtdf** [comment]
SDL_Color is a 4 bytes pod type. So i don't see a reason to pass this type by value..

**Comment by CelticMinstrel** [comment]
Also, passing pointers by reference usually isn't what you want.

**Comment by gfgtdf** [comment]
@CelticMinstrel
Things like shared_ptr have some overhead when copying them becasue the refcount must be updated in a threadsafe way, so in some situations its faster to pass them by reference.

**Comment by CelticMinstrel** [comment]
I'm fairly sure they're intended to be passed by value. I don't think they should be passed by reference unless you want to change where the pointer points.

**Comment by aginor** [comment]
These changes don't compile, as can be seen from the travis build log. I also agree that those pointers should be passed by value since a copy of the object happens and the reference count is updated (which won't happen if passed by reference).

**Comment by midzer** [comment]
I am gonna revert those changes with those enums tonight to see if it compiles then

**Comment by midzer** [comment]
I cant get this one to compile and will close it

**Pull request closed without merging**
