### PR TITLE
Deletes unused, unbuildable tools

### PR DESCRIPTION
**Pull request by Pentarctagon**
Deletes create_images, cutter, exploder, schema_generator, schema_validator, and wesmage as suggested [here](https://github.com/wesnoth/wesnoth/pull/874#issuecomment-266810917) in #874.

This only deletes the above targets for scons and cmake, and removes any files they were using which are not used by any other source list.  I did not attempt to determine if any of the source files that are used elsewhere are actually necessary, or if they should be moved to a different location (such as `src/tools/schema/tag.cpp`).

### CODE REVIEW

**Comment by gfgtdf** [comment]
Are these the tools that generate the gui2 wikipages ( https://wiki.wesnoth.org/Category:GUI_WML_Reference )?

**Comment by CelticMinstrel** [comment]
@gfgtdf I believe those tools are written in Python and stored in utils/ somewhere.

**Comment by CelticMinstrel** [comment]
Regarding tag.cpp, it's used by the GUI2 schema validator as I recall, so maybe move it to src/serialization?

Also, I assume this does remove all headers solely associated with the removed tools?

**Comment by Pentarctagon** [comment]
@CelticMinstrel If a .cpp file was deleted, then its .hpp file was also deleted.

**Comment by jyrkive** [comment]
@CelticMinstrel schema_generator is the only tool that has a Visual Studio project.

**Comment by CelticMinstrel** [comment]
I just noticed that there are data files associated with the tools as well, in _data/tools/exploder_ and _images/tools/exploder_. There's also another castle cutter tool in _data/tools/castle-cutter_ that seems unrelated to the one you've removed, and two chasm cutting images in _images/tools_ that according to @ln-zookeeper are obsolete.

**Comment by Pentarctagon** [comment]
@CelticMinstrel I've deleted those files as well.

I wasn't planning on moving tag.?pp.

**Pull request merged**
