### PR TITLE
Emulate weapon specials in abilities except plagues and swarm

### PR DESCRIPTION
**Pull request by newfrenchy83**
This time i added apply_to opponent and filter_opponent. Ihope what it is good this time.

### CODE REVIEW

**Comment by newfrenchy83** [comment]
Now backstab is present and showing bug in report fixed.

**Comment by newfrenchy83** [comment]
@CelticMinstrel the new PR is postef and compile error fixed. added apply_to both opponent filter_opponent and backstab_pos to permit charge and backstab in damage ability so formation ability without cteate a defense ability.
leadership ability has also active_on option. i think what all is it.

**Comment by CelticMinstrel** [comment]
I can't promise a time frame, but I'll try to get this reviewed eventually.

**Comment by newfrenchy83** [comment]
thank you

**Comment by newfrenchy83** [comment]
i know what you can't promise a time frame but it was a month ago. excuse me for that comment if you don't forget this PR.

**Comment by CelticMinstrel** [comment]
I think you can expect at least another month before I get to this, partly because I'm trying to focus on other things, partly because I just find this PR to be harder to review, and partly because the heat makes it difficult for me to focus at all.

Sorry.

**Comment by newfrenchy83** [comment]
me too i deal with heat i understand.

**Comment by newfrenchy83** [comment]
I added explains in attack.cpp  for rhe role of functions.

**Comment by newfrenchy83** [comment]
I add this files for exemples of these abilities and there filter to uses with.
[combat_ability_exemple.txt](https://github.com/wesnoth/wesnoth/files/2380197/combat_ability_exemple.txt)

**Comment by sevu** [comment]
I'm not sure what this is all about, but @ln-zookeeper the last one in the file looks like a better implementation for the formation ability from UtBS.
Though I still wonder if it would show the increased defence in the attack dialogue etc…

**Comment by newfrenchy83** [comment]
I think what yes, luke rhe damage ability, the effect must be visible for the player know what the ability is active and evaluate chance before to attack oe not. The final value to chance_to_hit is ever visible in attack dialogs without using attack_prédiction.cpp. you modify chance_to_hit, value visible in attack dialogs .

**Comment by newfrenchy83** [comment]
@sevu and the elvish rebels in utbs s9? how formation function against side 1 in current implementation?

**Comment by newfrenchy83** [comment]
@CelticMinstrel i foxed conflict with master branch.

**Comment by newfrenchy83** [comment]
@celticminstrel forgive me for that comment but i youre last comment was 2 month ago. I know what doing master branch playable is difficult and if i could help you and the other i make this. If you prefer read this PR after the first release of 1.15, i will understand this but i like know.

**Comment by jostephd** [comment]
Replaced by #3613 as master is no longer in use.

**Pull request closed without merging**
