### PR TITLE
Add missing names to about.cfg

### LINKED ISSUE #6475: [1.16.3] Check for missing credits in about.cfg
A reminder task to check that new contributors have been credited. Definitely missing are:
* Bruno Macabeus (Trickster)
* Luis Miguel Iglesias (Descacharrado)

### PR DESCRIPTION
**Pull request by Pentarctagon**
Fixes #6475

### CODE REVIEW

**Comment by Pentarctagon** [comment]
I plan to merge this tomorrow, barring any comments about more people to add.

**Comment by CelticMinstrel** [comment]
I think @Slayer95 seems to be missing, or am I wrong?

**Comment by Pentarctagon** [comment]
Added.

**Comment by hermestrismi** [comment]
Is the Arabic Translation maintainer fixed, too?

**Comment by Pentarctagon** [comment]
I'll be updating it on the website along with the rest of the steps I do with the next release.

**Pull request merged**
