### PR TITLE
AoI S1: Hint about recruiting a healer, if the player doesn't have any

### PR DESCRIPTION
**Pull request by stevecotton**
This is just a hint on the general principle that it's good to have a healer,
based on the review comments of #3683.

When playing on easy, there's not much experience available in this first
scenario. Any hints about leveling units probably belong in S2 or later,
which also has the advantage of being able to talk about the enemies in S2.

### CODE REVIEW

**Comment by GregoryLundberg** [comment]
.looks good on bench-check.will need cherry-pick to master.

**Comment by stevecotton** [comment]
The grammar looks okay to me, because "the battles ahead" are only "if we should embark on a campaign".

The reinforcements line also seems okay to me.

**Comment by jostephd** [comment]
Well, syntactically, the reinforcements sentence is a comma splice. I assumed elves wouldn't use that pattern.

**Comment by sevu** [comment]
So… how shall the string be? (Or merging as is ?)

**Comment by jostephd** [comment]
It's a good PR; I was just waiting for someone to offer a third (tie breaker) opinion on the two questions I raised.

**Comment by GregoryLundberg** [comment]
On re-reading, I see a code comment about it not being the time, but if not, when is a good time since there is no other time? The message appears on turn 5 or not at all.

I don't see an issue with the present wording. I'd make a minor change, dropping "then" but that's mainly a personal preference.

What I do wonder about is why there is no change from the generic to the female message? Why not just use the generic (message=) form, then?

**Comment by jostephd** [comment]
> What I do wonder about is why there is no change from the generic to the female message? Why not just use the generic (message=) form, then?

I'm guessing it's because some languages would translate the sentence differently depending on the gender of the speaker.

**Comment by stevecotton** [comment]
Re the "wrong time to hint" comment - if the player has less than 5 surviving units by turn 5, I think they've already lost, and we'll get another chance to give them the hint on their next attempt at the scenario. Maybe a different hint should be shown, but 4hp/turn healing won't help much with whatever is going wrong.

**Comment by jostephd** [comment]
> if the player has less than 5 surviving units by turn 5, I think they've already lost

Or they maybe they haven't recruited five units yet? A player have recruited four units or less to grab villages and hold a defensive line during the night (turn 5 is First Watch), intending to recruit the majority of his army on turn 6 in order to attack on turn 7 (dawn).

Anyway, 1.14.6 string freeze is coming up, and I don't think this issue should block the merge. Even if we agree changes are needed they can be made for 1.14.7.

**Comment by sevu** [comment]
merging for having the string in and to have to easier test the condition

**Pull request merged**
