### PR TITLE
fixup #8766

### PR DESCRIPTION
**Pull request by spixi**
This fixes a small dialogue issue introduced with PR #8766

### CODE REVIEW

**Comment by Wedge009** [comment]
What did this actually resolve? Because #8766 seems to be about something unrelated.

**Comment by soliton-** [comment]
The PR was actually #8887.

**Comment by spixi** [comment]
> What did this actually resolve? Because #8766 seems to be about something unrelated.

This adds more dialogue to the changes of PR #8887. #8766 is the original issue which was fixed with #8887. Sorry for the inconvenience.

**Comment by Wedge009** [comment]
No inconvenience, I was just confused by the linkage when I was reviewing #8766. soliton has closed that issue as a result of #8887 anyway, which confirms what I wanted to know.

**Pull request merged**
