### PR TITLE
finish renaming of the Horseman to Pathfinder

### PR DESCRIPTION
**Pull request by sevu**
This will break some saves, is that fine?
I guess sooner or later this change should happen, and now seems like a good time.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
In my opinion, better now than in 1.14.1.

**Comment by gfgtdf** [comment]
clearly we cannot merge this after 1.14. The renaimg is good for 1.13 but i wonder why you removed the unittype alias? I see no advtanges in that actually,

**Comment by CelticMinstrel** [comment]
Yeah, I'd keep the alias unit type for 1.14 (but also use the deprecated unit macro that's used in the khalifate aliases).

**Comment by sevu** [comment]
It turned out in the Discord discussion that saves have already been broken..

**Comment by sevu** [comment]
Added the compatibility code back in

**Pull request merged**
