### PR TITLE
tips: add tips that villages can be lures, and losses are necessary

### PR DESCRIPTION
**Pull request by stevecotton**
From oaq's post https://forums.wesnoth.org/viewtopic.php?f=3&t=47702

Kai Laudiss is Kai Krellis' dad, and the quote would be 3 years
before Dead Water.

### CODE REVIEW

**Comment by sigurdfdragon** [comment]
The attributions are interesting. The wording of the advice seems a little awkward, especially on the second one.

**Comment by Vultraz** [comment]
Suggest:

> For any player, controlling villages is often key to winning a scenario. You may use this knowledge to lure your opponents into a trap.

> You must accept some losses in battle. It is not uncommon for beginners to lose sight of victory as they attempt to keep every unit alive.

**Comment by GregoryLundberg** [comment]
@stevecotton Just in case you don't know 1.13.11 is scheduled for Sunday. This being put on the milestone for it means the RM thinks it should go in. So, if you want it to make it you need to make the changes requested sometime over the next day or so.

**Comment by stevecotton** [comment]
Thank you for the suggestions, I've taken both of them and then expanded the one about using villages as lures.

**Comment by sigurdfdragon** [comment]
Second tip seems fine now.

For the first one:

“For any player, controlling villages is often key to winning a scenario. You may use this knowledge to lure your opponents into a trap by leaving a village unoccupied; but first weigh the chances of killing the lured unit in a single turn, before it is healed by the village."

The part:
"but first weigh the chances of killing the lured unit in a single turn, before it is healed by the village."

seem slightly off and a touch wordy, also unnecessary to limit the attempt to kill the unit to one turn, and also the first part is somewhat general (trap could be for more than just one unit) so second part seems unnecessarly specific, perhaps something like:

"though make sure your chances of success justify the risk of losing the village."

would be better for the second part.

**Comment by Vultraz** [comment]
I second @sigurdfdragon 's suggestion:
> For any player, controlling villages is often key to winning a scenario. You may use this knowledge to lure your opponents into a trap by leaving some villages unoccupied, though make sure your chances of success justify the risk of losing them.

**Comment by stevecotton** [comment]
With the village hint, the hint that I was trying to write was for SP campaign scenarios, where the AI values capturing villages and is likely to send a unit to capture a village, even if it can be easily killed.

I think your rewrites are better that my attempts, but OTOH if the target audience is a beginner who's still learning how to win the campaigns, I think that none of the wordings so far is right for that target audience.

**Comment by Vultraz** [comment]
How about:
> For any player, controlling villages is often key to winning a scenario. You may use this knowledge to lure your opponents into a trap by leaving some villages unoccupied, but keep in mind that an enemy unit becomes much harder to dislodge from a village! Plan your movements accordingly.

**Comment by stevecotton** [comment]
Thank you, I've cut & pasted your suggestion.

**Comment by Vultraz** [comment]
Thanks for adding these :)

**Pull request merged**
