### PR TITLE
update mingw project

### PR DESCRIPTION
**Pull request by newfrenchy83**

### CODE REVIEW

**Comment by newfrenchy83** [comment]
And if semeone other what me updated the projectfiles this will help

**Comment by GregoryLundberg** [comment]
Perhaps you're the only one using CodeBlocks?

I do know there was discussion of deleting the project files shortly before you came along.

At present, I'm trying to spin my macOS VM back up with High Sierra and get Wesnoth going on it. I've been thinking about firing up another vanilla Windows 10 someday (no Visual Studio, no build tools), and looking into getting MinGW working. But that would probably use VS Code and command-line tools, not CodeBlocks.

Meanwhile, let me know when you're completely done with changes and I'll see about sending you a PR merging and cleaning up the mess, with a better commit message.

**Comment by newfrenchy83** [comment]
Leave a commenti posted a change but i don't know if this what you're request

**Comment by newfrenchy83** [comment]
i post a change but i don'know this is that what you're request

**Comment by GregoryLundberg** [comment]
I __*think*__ I did that correctly. If not, I can try again. What it's supposed to do is eliminate all your commits and replace them with a single commit with a better commit message.

**Pull request closed without merging**
