### PR TITLE
fix halo remain for advancement, normal kill and lua function

### PR DESCRIPTION
**Pull request by newfrenchy83**
jyrkive did'nt apply his soluce for all kill unit, and advance unit and unstore_unit are also an problem to remain halo.

### CODE REVIEW

**Comment by gfgtdf** [comment]
this still uses spaces instead of tabs.

**Comment by newfrenchy83** [comment]
i know but i cannot uses tabs, sorry.

**Comment by AI0867** [comment]
Then stop making these kinds of changes through the webinterface.

**Comment by newfrenchy83** [comment]
i post an new request where spacing are removed, butfor web, i have not adsl and using smartphone. i cannot use desktop git. i do with i have.

**Pull request closed without merging**
