### PR TITLE
Add debug command :terrain.

### PR DESCRIPTION
**Pull request by jostephd**
Usage: `:terrain <terrain type> [both|base|overlay]`

### CODE REVIEW

**Comment by Wedge009** [comment]
So one can change terrain in the middle of a game?

**Comment by jostephd** [comment]
Yes (in debug mode only, of course).

It's easier than running `wesnoth.set_terrain(2, 3, 'Ss'); wesnoth.redraw{}` in the lua console.

**Comment by CelticMinstrel** [comment]
Also easier than using the Lua way of getting the currently-hovered hex and subbing that into the command.

**Comment by gfgtdf** [comment]
hmm this is not synced, all other gamechanging debug functions are synced, (so that they don't cause OOS). I think it'd be better if his way synced aswell.

**Comment by jostephd** [comment]
Done. Is the undo handling correct?

**Comment by gfgtdf** [comment]
> Is the undo handling correct?

I'd say so i dont remeber exactly but its what all the other debug functions do aswell.

**Pull request merged**
