### PR TITLE
AoH balance. 

### PR DESCRIPTION
**Pull request by Hejnewar**
Drakes:
Cost of Drake Warrior changed from 30 to 32
Cost of Drake Arbiter changed from 31 to 32
Cost of Drake Trasher changed from 31 to 32
Cost of Flare Drake changed from 35 to 33
Cost of Fire Drake changed from 35 to 35
Cost of Sky Drake changed from	30 to 28
Cost of Saurian Ambusher changed from 30 to 24
Cost of Saurian Oracle changed from	27 to 28
Cost of Saurian Soothsayer changed from 27 to 25

Knalgan Alliance:
Cost of Dwarvish Steelclad changed from 32 to 36
Cost of Dwarvish Thunderguard changed from 30 to 27
Cost of Dwarvish Stalwart changed from 32 to 30
Cost of Dwarvish Berserker changed from 33 to 30
Cost of Outlaw changed from 28 to 26
Cost of Trapper changed from 27 to 21
Cost of Gryphon Master changed from 37 to 38

Loyalists:
Cost of Swordsman changed from 25 to 29
Cost of Knight changed from 40 to 38
Cost of Lancer changed from 40 to 44
Cost of Dragoon changed from 34 to 27
Cost of Duelist changed from 32 to 29
Cost of Merman Warrior changed from 28 to 26
Cost of Ogre changed from 33 to 30
Cost of Lieutenant changed from 35 to 29

Northerners:
Cost of Goblin Knight changed from 32 to 28
Cost of Goblin Pillager changed from 32 to 28
Cost of Troll changed from 29 to 27
Cost of Troll Rocklobber changed from 29 to 25
Cost of Naga Warrior changed from 27 to 24
Cost of Orcish Crossbowman changed from 26 to 21
Cost of Orcish Slayer changed from 33 to 26

Rebels:
Cost of Elvish Hero changed from 30 to 26
Cost of Elvish Captain changed from 32 to 28
Cost of Elvish Marksman changed from 37 to 31
Cost of Elvish Ranger changed from 38 to 31
Cost of Elvish Rider changed from 31 to 32
Cost of Elvish Druid changed from 34 to 27
Cost of Elvish Sorceress changed from 34 to 32
Cost of Elder Wose changed from 31 to 27
Cost of Merman Spearman changed from 27 to 27, movement changed from 6 to 7 and hp changed from 40 to 43.
Merman Javelineer - movement increased by 1 and hp increased by 3 in order to match Merman Spearman.

Undead:
Cost of Revenant changed from 28 to 31
Cost of Deathblade changed from 28 to 34
Cost of Dark Sorcerer changed from 32 to 33
Cost of Blood Bat changed from 21 to 22

Cost of Red Mage changed from 40 to 38
Cost of White Mage changed from 40 to 38

Forum link:
[here](https://forums.wesnoth.org/viewtopic.php?f=15&t=51028&p=648246#p648246)

### CODE REVIEW

**Comment by Pentarctagon** [comment]
It doesn't sound like there are any particular concerns from the thread, so I don't think there's a reason not to merge this?

@Hejnewar Fixed the link btw.

**Comment by nemaara** [comment]
I can spot a few at a glance, but haven't had time to review this yet. Please allow me a few days.

**Comment by soliton-** [comment]
I'm still not happy about units advancing from the same unit costing differently and the Lieutenant cost explanation is not particularly convincing either IMO.

**Comment by Hejnewar** [comment]
Thanks, Pentarctagon.

I will wait for it @nemaara.

**Comment by Hejnewar** [comment]
Ambusher - I get that this unit can be very unpleasant for some factions but is he really that srong? Well I guess its better if unpleasant units would be seen less often but still.
Traper, Crossbowman and other cheap units - I think the biggest issue with cheap units is that people worry that they will be spamed left and right. I really dont see Crossbow or water units as spamable ones but I will think about Trapper a bit more.
Lieutenant - yeah. 
Hero - also yeah but I would go with 26 rather than higher number.
Mages -they lack hp and red mage is neutral but well protected can do a lot of damage yes. I want to test them more since it's quite popular opinion.

Equal prices - well once we establish by how much unit a is stronger from unit b it will be easier to adjust them.

**Comment by CelticMinstrel** [comment]
I don't see the point of trying to make both advancements cost the same.

**Comment by Pentarctagon** [comment]
It looks like this can be merged, then?

**Comment by nemaara** [comment]
Probably still needs @soliton-'s approval.

**Comment by soliton-** [comment]
I've still not heard much explanation on why different costs for advancements of the same unit are necessary. I do not agree with the Lieutenant change and I've not heard anything at all on why the Merman movement change is a good idea.

It's not great that this lingers here. I've mentioned that one way to speed this up would be to only do uncontroversial changes as a first pass so it gets easier to discuss the remaining changes.

**Comment by soliton-** [comment]
To be clear I'm not blocking this if Krogen and EoZ are ok with it but so far I have not heard that.

**Comment by nemaara** [comment]
Okay, I don't intend to be the one merging this, since this affects MP. I'm hoping you can do it once things are cleared up.

**Comment by Hejnewar** [comment]
"I've still not heard much explanation on why different costs for advancements of the same unit are necessary. " 
I tried but it would mess with default balance. In order to change prices I would need to buff these units and that would affect default. 

"I've not heard anything at all on why the Merman movement change is a good idea."
For me it's the simplest way of buffing this unit while saving as much of its past self as possible.

"I do not agree with the Lieutenant change"
While leaders with leadership prefer to avoid combat (especially lieutenant because of his low hp) units with leadership actually fight and lieutenant has very weak body 7 hp less and 4 melee dmg (not counting traits) less than elvish capitan, his biggest saving grace is his 6mp. 
That said I cant just price units with leadership based on only the fact that they have that ability, I expect them to fight and lieutenant can't fight very well / at all, after all chance of losing him if not covered is high, even more so if he is damaged and this unit is not cheap at all. Elvish Captain with his 7 more hp can afford to fight killing lets say 38 hp (9 dmg is quiet common in wesnoth) unit is not that easy while killing 31 hp unit is different story, this is most often one hit that matters. Probability of hitting 5/6 strikes (again using 9 dmg) on 40% is 23,3% but 4/6 strikes is 54,4% (elvish captain can also be used as tank if necessary with very low chance of his death (4,7% when 6/6 hits are needed)). That's quite a big difference. 6mp let's lieutenant support units the best but at the same time to make full use of it you need to invest more in lieutenant also in form of better protection another thing is that loyalist units gain more from leadership than elvish units that is why his price is still higher than that of elvish captain. I hope that this showed my point of view well enough.

Also I will remove troll rocklobber change just to not mess with leaders at all.

**Comment by Hejnewar** [comment]
Ok, I have some time for wesnoth again and I would like to bring this to the end. 
@nemaara I can check campaigns if necessary.
@soliton- Last time we talked about this every problem of @ElderoZ and @Krogen was resolved IIRC.

**Comment by ElderoZ** [comment]
@soliton- Ok, if I have seen this thread earlier I would have responded earlier, @Soliton
I do want people to have a degree of understanding, and I will respond to your question, I see your point and well, I havent thought that much about why would we actually couldn't make the units advancing from a single unit cost the same, to me it was enough that recruit cost depends solely on the type of a unit, and its way less invasive to change costs of units than to completely change their stats.
I think there are some reasons that would be harder to dismiss.

First of all, the cost is not a representation of a unit's power in every specific situation, it cannot be, it is rather a representation of its usefulness in a game and in most situations. I think that by the very nature of the game there will have to be units that will be good in say 80% of the situations and then there will be units that are good in 20%, therefore the units that are good in 80% of the situations should cost more, this is just an example. By the very game design of wesnoth and many other games, units good in niche applications just are naturally worse vs most units.

So, to the point, what if I tried to make the level ups cost the same? Not sure how hard it would be, but in wesnoth the types of units a single unit can advance into have so much variety and their statistics can be so much different, that by making them cost the same i think some of their uniqueness in stats would have to be sacrificed, if say one unit is amazing against heavy infantry and the other is good against grunts, its basically impossible to not recruit grunts, while an opponent can very often just give up on recruiting heavy infantry, so say even if the unit that has niche application is 80% better against that type of a unit than the other advancement, which has more general use, I dont think there is a way in hell to make it just as useful in general, it would require a degree of cooperation from the other player, this isj ust an example.

So I think that would be a pretty good reason to not make units cost the same, and on top of that, i am still of opinion that if you recruit a level 2 unit, it doesn't matter what it advanced from.


About the changes, ok, there are some controversial changes, but in current AoH costs of many units are so weird that really there is not much reason to keep arguing about changing some costs by a few gold now. We can always tweak some costs later if we get more feedback and maybe argue a bit more.

**Comment by soliton-** [comment]
> So, to the point, what if I tried to make the level ups cost the same? Not sure how hard it would be, but in wesnoth the types of units a single unit can advance into have so much variety and their statistics can be so much different, that by making them cost the same i think some of their uniqueness in stats would have to be sacrificed

Lots of units cost the same and have wildly different stats already. So clearly units that cost the same don't have to have similar stats. There are also several level ups that do cost the same right now and also if this PR is merged.

> About the changes, ok, there are some controversial changes, but in current AoH costs of many units are so weird that really there is not much reason to keep arguing about changing some costs by a few gold now. We can always tweak some costs later if we get more feedback and maybe argue a bit more.

Why do we have to make the controversial changes now, they can be done later just as well?

I'd like to hear some more opinions on the Merman movement change and the Lieutenant cost.

As far as I understood it Hejnewar mentioned that the Lieutenant has less HP than the Elvish Captain and while the 6 MP + leadership is "the best" and "loyalist units gain more from leadership than elvish units" it still needs a cost reduction of 6 gold. Can't say I understand that but as mentioned before if others agree that's fine with me.

**Comment by ElderoZ** [comment]
@soliton- "Lots of units cost the same and have wildly different stats already."

I think I don't agree with all the costs here, hejne's changelog (or rather lack of it) has been so chaotic that I didn't follow every single change specifically. I made some comments in balancing about the costs I didn't like that were ignored or got lost in the discussion. Eitherway some units can have same costs, other not so much. Say I think mages are more similiar in their general usefulness and are less "niche" than say ranger and sharpshooter. Sharpshooter deals more damage than red does in comparison to red, white can heal and thats a huge factor, but healing will be always good, so thats kinda a "passive" buff you could say. Ranger has more hp and better terrain defenses, but it only matters if you put him on these terrains, its better defensively, seems kinda more niche than pure damage output. That being said my suggestion for mages was red 37 white 38 but I thought 38 maybe would be fine. Krogen said that white indeed may be a bit stronger in AoH. I think I still stand by the suggestion, but not really 100% sure.

As I said, im not sure how hard making the costs be the same would be, but you cant really avoid the pikeman and sword situation, where they deal similiar damage but one has different resistances that are more often useful (tho I did suggest a small pike buff at one point, but maybe its a little bit controversial), or the deathblade and revenant situation where one just deals more damage, ignore even the movement factor, say they had same movement, if you cover it a unit with higher damage, it will just do more work, mages and adepts cost more for a reason.

But ultimately, you ask "Why not make level ups cost the same?", I would ask "Why make them cost the same?", so why do it if it doesn't matter at all when levelling up the unit? Consistency, yeah, I don't feel strongly that everything has to be so homogenous cost wise in this case, the fact that 2 units advance from a single unit, therefore they should be recruited for the same cost, is a rather weak argument to me. Especially if it would mean sacrificing whatever little amount of diversity and complexity in the game, that would be needed to sacrifice. I don't see how setting the costs to be the same can make the game more complex or give it a more diverse unit roster, if it would force stat changes that would tend to make units look more homogenous.

"There are also several level ups that do cost the same right now and also if this PR is merged."

Afair their stats are pretty similiar, no. And beside

"Why do we have to make the controversial changes now, they can be done later just as well?"

Well, I think there are more controversial changes than it would first seem, still an argument could be made that original costs are worse for these units than the new controversial ones.

Im not completely sure, but I would wager the controversial costs are still an upgrade overall. If you feel strongly about it, as far as im concerned im ok with postponing or not including the controversial changes, as well as including them. At this point this detail doesn't matter that much to me, I have made the suggestion,s I have talked about the changes, the execution is a different story.

**Comment by ElderoZ** [comment]
@soliton- About fish and lieu

"EoZ19.12.2019
also it buffs orc leader
what is teh change
in fish
Hejnewar19.12.2019
+1 mov +2 hp"
"ok comparing stats I totally support it
make that buff happen"

I doubt hejne even remembers what were his own suggestions.

Lieu:
"EoZ04.12.2019
im not really convinced lieu should cost as much as sword"

**Comment by Hejnewar** [comment]
> Lieu:
> "EoZ04.12.2019
> im not really convinced lieu should cost as much as sword"

At this point I won't even argue about him.

> I doubt hejne even remembers what were his own suggestions.

Just look at date of changes and date of reply that will solve your question.

**Comment by Hejnewar** [comment]
Okay, we came up with new idea to just remove lieutenant and ogre from AoH. 
Reason: Only loyalists are getting additional units. No other faction does.

**Comment by Hejnewar** [comment]
It would be nice to have this in 1.15.3 but I doubt that this will happen.

**Comment by Pentarctagon** [comment]
What's still undecided at this point?

**Comment by Hejnewar** [comment]
After Lieutenant change everything should be ok. So we are waiting for @soliton- approval.

There was that idea to remove Ogre and Lieutenant but that isn't that important, it might as well wait.

**Comment by soliton-** [comment]
I was hoping for a response here from Krogen but I‘ll assume he‘s in favor of the majority of changes. I‘ll be back home tomorrow and will hopefully find time to merge this.

**Comment by ElderoZ** [comment]
@soliton- Oh, you would need to probaby message him on discord and wait for a week or more, but he would most probably say that this is all fine or something like that. Afair there wasn't a single change that i did not talk about with him.

**Pull request merged**
