### PR TITLE
[1.16] Version bump for 1.16.12+dev

### PR DESCRIPTION
**Pull request by stevecotton**
I have no expectation that we'll release a 1.16.13, but it's still useful to know which builds were from exactly the 1.16.12 tag.

That "I have no expectation" is in the commit message, please say if I should remove it.

The reason to push this now is to find out if the CI still works for 1.16, given that 1.14's Docker images no longer exist (see the build logs of #9036).

### CODE REVIEW

**Comment by Wedge009** [comment]
Looking at the corresponding files for 1.10, 1.12, 1.14, the version bump is in place already so I don't think it's unreasonable to have it for 1.16 as well even without any further releases planned.

**Comment by stevecotton** [comment]
@hrubymar10 and @CelticMinstrel,what should be done with MacOS for 1.16? I assume this needs some update to the MacOS build setup, as the jobs have been queued without runners for a couple of days. Should we look at that, or just assume that 1.16 doesn't need to build for Mac any more?

**Comment by soliton-** [comment]
`macos-11` is gone since a couple days. https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners

master and 1.18 use `macos-12` now.

**Comment by stevecotton** [comment]
The Boost tests weren't added until 1.18, and I've dropped the MacOS release build because it would need a signing certificate to be set up.

**Pull request merged**
