### PR TITLE
1.16 Backports

### PR DESCRIPTION
**Pull request by gfgtdf**
Partly tested.

- the Bezoar Item works now (tested)
- custom effects work in following scenarios
- "Destruction mechanic line 73 bug"
- Promoted commanders having the wrong id.

### CODE REVIEW

**Comment by Pentarctagon** [comment]
These are safe to backport, I assume?

**Comment by gfgtdf** [comment]
Well the wc changes won't do harm but they don't fix "[traits] in artifacts not working" part yet, basically  they backport the fix from master in a safe way that won't cause OOS erros.

The other commit could in some cases cause oos with previous version but also fixes oos errors in 1.16 that existed before which i think is more important. Also it fixes this api (which is used also by examples in the wiki) for single player campaigns.

**Comment by Pentarctagon** [comment]
> The other commit could in some cases cause oos with previous version but also fixes oos errors in 1.16 that existed before which i think is more important. Also it fixes this api (which is used also by examples in the wiki) for single player campaigns.

What OOS errors are being fixed, and what OOS errors would it cause when played with previous versions?

**Comment by gfgtdf** [comment]
> What OOS errors are being fixed

Well when using the "Mp back to turn" feature you could bring the game out of sync since it effectively loads a game. and this bug caused reloaded games to change the gamestate.

> and what OOS errors would it cause when played with previous versions?

When addons use custom effects the older version would still have bug in, unless the addon (like WC2 does has  workaround in it)

**Comment by Pentarctagon** [comment]
> When addons use custom effects the older version would still have bug in, unless the addon (like WC2 does has workaround in it)

So when a version older than 1.16.9 plays a UMC that uses custom effects with someone on an earlier version, will they get OOS errors that they weren't getting before? If so, that isn't something that can go into 1.16.

**Comment by Pentarctagon** [comment]
So it's changing from "never safe to use" to "safe to use when all clients are on 1.16.9", correct?

**Comment by gfgtdf** [comment]
> So it's changing from "never safe to use" to "safe to use when all clients are on 1.16.9", correct?

Yes BUT, the bug only effects unit that are on the recall list on scenario start, so de facto only (mp) campaigns, which by itself is rather rare, and furthermore only mp campaigns that use lua to add custom effect, at which point it probably only effects world conquest (which (with this pr) already has a seperate workaround in it that also works when one of the players has an older version).

The Bug also effected sp campaigns though (but these can't cause OOS).

**Comment by Pentarctagon** [comment]
What's the name of the API? Soliton can search the add-ons on the 1.16 add-ons server for whether there are any that use it.

**Comment by gfgtdf** [comment]
wesnoth.effect

**Comment by soliton-** [comment]
Matches in 1.16 addons:

> Invincibles_Conquest_II/lua/game_mechanics/effects.lua:function wesnoth.effects.ic2_optional_attack(u, cfg)
Invincibles_Conquest_II/lua/game_mechanics/effects.lua:function wesnoth.effects.ic2_moves_defense(u, cfg)
Invincibles_Conquest_II/lua/game_mechanics/effects.lua:function wesnoth.effects.ic2_min_resistance(u, cfg)
Invincibles_Conquest_II/lua/game_mechanics/effects.lua:function wesnoth.effects.ic2_min_defense(u, cfg)
Invincibles_Conquest_II/lua/game_mechanics/effects.lua:function wesnoth.effects.ic2_update_aura(u, cfg)
Invincibles_Conquest_II/lua/game_mechanics/effects.lua:function wesnoth.effects.ic2_overlay(u, cfg)
Invincibles_Conquest_II/lua/game_mechanics/effects.lua:function wesnoth.effects.ic2_move_on_recruit(u, cfg)
Invincibles_Conquest_II/lua/game_mechanics/effects.lua:function wesnoth.effects.ic2_recall_cost(u, cfg)
Invincibles_Conquest_II/lua/optional_mechanics/unitmarker.lua:function wesnoth.effects.ic2_unitmarker(u, cfg)
War_of_Legends/lua/equipment-system/levels.lua:function wesnoth.effects.level(u, cfg)
Wild_Frontiers/lua/utils.lua:function wesnoth.effects.canrecruit(u, cfg)
Advance_Wesnoth_Wars_fork/_main.cfg:              function wesnoth.effects.level(unit, cfg)
Reign_of_the_Lords/utils/lua_events.cfg:                  function wesnoth.effects.osd_fix_advancements(u)
War_of_Life_and_Death/utils/lua_events.cfg:                       function wesnoth.effects.osd_fix_advancements(u)
Ageless_World_Conquest_ll/lua/effects.lua:function wesnoth.effects.wc2_optional_attack(u, cfg)
Ageless_World_Conquest_ll/lua/effects.lua:function wesnoth.effects.wc2_moves_defense(u, cfg)
Ageless_World_Conquest_ll/lua/effects.lua:function wesnoth.effects.wc2_min_resistance(u, cfg)
Ageless_World_Conquest_ll/lua/effects.lua:function wesnoth.effects.wc2_min_defense(u, cfg)
Ageless_World_Conquest_ll/lua/effects.lua:function wesnoth.effects.wc2_fixed_lua_filter(u, cfg)
Ageless_World_Conquest_ll/lua/effects.lua:function wesnoth.effects.wc2_update_aura(u, cfg)
Ageless_World_Conquest_ll/lua/effects.lua:function wesnoth.effects.wc2_overlay(u, cfg)
Ageless_World_Conquest_ll/lua/effects.lua:function wesnoth.effects.wc2_move_on_recruit(u, cfg)
Ageless_World_Conquest_ll/lua/effects.lua:function wesnoth.effects.wc2_recall_cost(u, cfg)
Invasion_from_the_Unknown/Naia/lua/units.lua:function wesnoth.effects.level(u, cfg)
Ageless_World_Conquest_II/lua/effects.lua:function wesnoth.effects.wc2_optional_attack(u, cfg)
Ageless_World_Conquest_II/lua/effects.lua:function wesnoth.effects.wc2_moves_defense(u, cfg)
Ageless_World_Conquest_II/lua/effects.lua:function wesnoth.effects.wc2_min_resistance(u, cfg)
Ageless_World_Conquest_II/lua/effects.lua:function wesnoth.effects.wc2_min_defense(u, cfg)
Ageless_World_Conquest_II/lua/effects.lua:function wesnoth.effects.wc2_fixed_lua_filter(u, cfg)
Ageless_World_Conquest_II/lua/effects.lua:function wesnoth.effects.wc2_update_aura(u, cfg)
Ageless_World_Conquest_II/lua/effects.lua:function wesnoth.effects.wc2_overlay(u, cfg)
Ageless_World_Conquest_II/lua/effects.lua:function wesnoth.effects.wc2_move_on_recruit(u, cfg)
Ageless_World_Conquest_II/lua/effects.lua:function wesnoth.effects.wc2_recall_cost(u, cfg)
Legend_of_the_Invincibles_beta/lua/stats.lua:             -- TODO: Add alignment, max_attacks and new_advancement using wesnoth.effects
Legend_of_the_Invincibles/lua/stats.lua:          -- TODO: Add alignment, max_attacks and new_advancement using wesnoth.effects
World_Conquest_II/lua/game_mechanics/effects.lua:function wesnoth.effects.wc2_optional_attack(u, cfg)
World_Conquest_II/lua/game_mechanics/effects.lua:function wesnoth.effects.wc2_moves_defense(u, cfg)
World_Conquest_II/lua/game_mechanics/effects.lua:function wesnoth.effects.wc2_min_resistance(u, cfg)
World_Conquest_II/lua/game_mechanics/effects.lua:function wesnoth.effects.wc2_min_defense(u, cfg)
World_Conquest_II/lua/game_mechanics/effects.lua:function wesnoth.effects.wc2_fixed_lua_filter(u, cfg)
World_Conquest_II/lua/game_mechanics/effects.lua:function wesnoth.effects.wc2_update_aura(u, cfg)
World_Conquest_II/lua/game_mechanics/effects.lua:function wesnoth.effects.wc2_overlay(u, cfg)
World_Conquest_II/lua/game_mechanics/effects.lua:function wesnoth.effects.wc2_move_on_recruit(u, cfg)
World_Conquest_II/lua/game_mechanics/effects.lua:function wesnoth.effects.wc2_recall_cost(u, cfg)
World_Conquest_II/lua/optional_mechanics/unitmarker.lua:function wesnoth.effects.wc2_unitmarker(u, cfg)
After_the_Storm/Naia/lua/units.lua:function wesnoth.effects.level(u, cfg)

**Comment by Pentarctagon** [comment]
So that'd be:
```
Invincibles_Conquest_II
War_of_Legends
Wild_Frontiers
Advance_Wesnoth_Wars_fork
Reign_of_the_Lords
War_of_Life_and_Death
Ageless_World_Conquest_ll
Invasion_from_the_Unknown
World_Conquest_II
After_the_Storm
```

**Comment by Pentarctagon** [comment]
I think I'm good with this then.

**Pull request merged**
