### PR TITLE
Make sure Elvish Race Description doesn't contradict WoF

### PR DESCRIPTION
**Pull request by Gothyoba**
https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Winds_of_Fate/story/Past_and_Future_Drake_History_(Spoilers).txt

This contradicts the unused drake history file in WoF, which shows the elves appeared after many other races, like drakes, trolls and many others.

CC: @Dalas121

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
The unused history file shouldn't be considered canon.

**Comment by Gothyoba** [comment]
> The unused history file shouldn't be considered canon.

It is though. It’s in mainline and is going to be the basis of part of my history encyclopedia sections. But before I can do that I have to clear up the sources so they’re consistent.

**Comment by CelticMinstrel** [comment]
It's not canon until it's put somewhere player-visible. At present it's no more than a general suggestion.

**Comment by Gothyoba** [comment]
I'd still like to get sources consistent given that I plan to make part of what is written here player-visible. And it would still be ideal to prevent sources form completely contradicting each other.

**Review by Dalas121 — APPROVED** [review]
No strong opinion. I don't consider non-player-visible files to be canon, so I don't think it hurts to leave the elvish info unchanged. But I also don't think it hurt to make the change you've proposed here.

**Comment by CelticMinstrel** [comment]
I don't consider that file to be canon, but I _do_ think making claims about which race is the "eldest" is fundamentally questionable and should be avoided. So, I can approve of this change on that basis, rather than the basis of a hidden file.

**Review by Jonathan-Kelly — APPROVED** [review]
Looks fine to me.

**Review by knyghtmare — APPROVED** [review]

**Pull request merged**
