### PR TITLE
replace ability steadfeast by resistance ability for Garak in Utbs(1.16)

### PR DESCRIPTION
**Pull request by newfrenchy83**
fix steadfeast don't work for Garack. Fix https://github.com/wesnoth/wesnoth/issues/6046

### CODE REVIEW

**Comment by newfrenchy83** [comment]
Resolve https://github.com/wesnoth/wesnoth/issues/6046 issue

**Comment by Pentarctagon** [comment]
Note that this can't go into 1.16 for now due to the string freeze.

**Comment by newfrenchy83** [comment]
> 
> 
> Note that this can't go into 1.16 for now due to the string freeze.

Ok i doing on master only then

**Comment by CelticMinstrel** [comment]
The description needs to be changed though (grammar issues). Maybe the name too, but it might be fine since it _is_ similar to the other steadfast.

**Comment by newfrenchy83** [comment]
> 
> 
> The description needs to be changed though (grammar issues). Maybe the name too, but it might be fine since it _is_ similar to the other steadfast.

grammatical issue fixed in https://github.com/wesnoth/wesnoth/pull/6075 but name no changed.

**Pull request closed without merging**
