### PR TITLE
wmlxgettext: fix #3469: lua plural strings not recognized in some context

### LINKED ISSUE #3469: wmlxgettext does not recognize plural strings in some contexts
I had a line similar to the following:

```
local var = wesnoth.format(_("one thing","$count things",count), {count = count})
```

When I ran wmlxgettext, the string was not gathered. Adding a space before the underscore allowed wmlxgettext to recognize it.

### PR DESCRIPTION
**Pull request by AncientLich**
wmlxgettext couldn't recognize lua plural strings in some context. More in details the underscore marker ( _ ) originally required to be located at the beginning of the line or preceded by a space.
Now string maker is recognized without the requirement of an extra space, so syntax like: 
`local var = wesnoth.format(_("one thing","$count things",count), {count = count})`
now can be recognized as plural string, even if the underscore marker is not preceded by a space, but is preceded, for example, by a parenthesis

### CODE REVIEW

**Comment by gfgtdf** [comment]
please add a short description of the issue in the commit message title and not just the link, also please just write the bug id in the title instead of the the whole link in the title, for example
`wmlxgettext: fix plural strings in lua code, fixes #3481`

**Comment by AncientLich** [comment]
I did the changes you asked.
Imho those informations are redundant, because all the informations and details about the bugfix were discussed in the original bug report.

**Comment by gfgtdf** [comment]
> Imho those informations are redundant, because all the informations and details about the bugfix were discussed in the original bug report.

yes but if you want to get an overview of the commits you don't want to have click on the link or look at the diff to figure our what it does, People for example want to be able get an overview what happens in last few days just by quickly looking at https://github.com/wesnoth/wesnoth/commits/1.14 (or master).

**Comment by CelticMinstrel** [comment]
@ancientlich It's not redundant; the issue could go poof at some point in the future but the commit message will always be there. So the commit message should have the authoritative description of the fix (even if it's just a quick summary).

**Comment by AncientLich** [comment]
Not necessary at all. I commented in order to save the old regex in order to 'save' it until tests for myself. Now I agree it can (and should) be completely deleted. I will remove it with another commit

**Comment by CelticMinstrel** [comment]
It'll always be saved in the commit history anyway, so I don't think there's ever a need to leave something in but commented out.

**Comment by jyrkive** [comment]
Merged. Thank you! :)

**Pull request merged**
