### PR TITLE
resolve problems of negative value for heals

### PR DESCRIPTION
**Pull request by newfrenchy83**
This is the only option to solve this problem without breaking add and sub tags. Fix for https://github.com/wesnoth/wesnoth/issues/3811 issue

### CODE REVIEW

**Comment by gfgtdf** [comment]
so why is this now better than just calling get_composite_value ?

**Comment by newfrenchy83** [comment]
This is not the case but someone ask me an fix specific to heals. With your midifications of code in egfect constructor, i must replace get_composite value by in highest("value") in illuminates ability.

**Comment by jostephd** [comment]
I assume you're referring to me, so let me clarify: What I asked to open separate issues for separate bugs. That's just best practice. For example, the leadership fixes were independent of the healing fixes so we split them and merged them separately.

Regarding healing, the discussion on #3811 has established that **we would like to change the behavior of healing**, but it has _not_ established **how to implement the new behavior**. There may be more than one way to implement the desired behavior, so we need to decide how to implement the new behavior that we've agreed on. That's what @gfgtdf is asking.

To be absolutely clear, I don't know what the best way to implement the new healing behavior is, whether by changing heal.cpp or by changing the effect constructor or by some other way.

**Comment by newfrenchy83** [comment]
i choose https://github.com/wesnoth/wesnoth/pull/3814 finally.

**Pull request closed without merging**
