### PR TITLE
Changed description of the alternative plague ability.

### PR DESCRIPTION
**Pull request by sevu**
This ability gives content creator complete freedom on what unit type to create. (It's also only used in UMC)  While it's probably mostly the lvl0 version of the unit who used the ability, the current description is not fitting.

Credits for spotting and changing this go to Ravana.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I just wish there was a way to actually insert the name of the unit in there... oh well.

**Comment by sevu** [comment]
I thought sth. like "replaced with a ${TYPE}.name" or "replaced with a ${TYPE}.language_name" could be used, but it doesn't replace the variable. (Testing with a unit without spaces). Maybe somebody knows why it doesn't work and if it's possible?

**Comment by CelticMinstrel** [comment]
Macros and variables are two completely different things. You can't use macros in translatable strings, because the macro is substituted at load time and the substituted string is used to look up translations; but the translation is stored under the unsubstituted string, so they won't be found. Variables in translatable strings are safe, but variables are only available in specific contexts, and this is not one of them.

**Comment by gfgtdf** [comment]
> but variables are only available in specific contexts, and this is not one of them.

But we could implement it, in `unit::ability_tooltips` do something like
```
string_map vars;
if(ab.key == "plague") {
    string_map["plague_type"] = ab.cfg["type"]  
}
else if (ab.key == "heals") {
    string_map["heal_amount"] = ab.cfg["value"]
}
else if ... {

....


}
std::string desc = vgettext(ab.cfg["name"], vars)
```

**Comment by CelticMinstrel** [comment]
That's what I meant when I mentioned the auto-generated description. Note though that `cfg["type"]` is not the correct value - you need to actually look up the unit_type to get the translatable name.

**Pull request merged**
