### PR TITLE
Bump min Pango version to a saner value

### PR DESCRIPTION
**Pull request by Vultraz**
The previous min version (1.21.3) is almost 10 years old at this point (release archives indicate a
release date of June 2008). The current pangocairo package available in Debian oldstable (Jessie,
which we still support since we're still supporting GCC 4.8...) is 1.36.8 (from September 2014), so
I made that the new minimum.

### CODE REVIEW

**Comment by sigurdfdragon** [comment]
I've got 1.36.1 for my Win build so I would have to update. I would rather it be after 1.14 comes out.

Also the 1.13.10 official windows build uses 1.30.1, so @loonycyborg would have to update the windows packaging process as well.

**Comment by Vultraz** [comment]
Looks like Travis's repo has `1.36.3`...

**Comment by jyrkive** [comment]
What's the point of increasing the minimum version? Do we need a feature or bug fix that was introduced in a newer version? Dependencies shouldn't be increased just for the sake of it.

**Comment by Vultraz** [comment]
Well, if we bump the minimum to 1.38 (can't right now, obviously), there are some additional markup tags available. Not necessarily that useful, but still, nice to have. Plus I figured it's better to have a more recent minimum since no one should be using software with 10 years' worth of bug fixes missing.

**Comment by gfgtdf** [comment]
Some color definitions have also chnged in earlier  pango versions, see also https://github.com/wesnoth/wesnoth/commit/498581d41233a679fbffd3d285917c9e182a12a0

**Comment by GregoryLundberg** [comment]
If we linked against a shared library (.so or .dll) I'd see this as an issue because it effects end-users. But, we statically link; so, this really is just a question of how far up we want to force the developers and builders to go. While bleeding-edge might be nice, I think the rationale used in the OP is fine. Newer than that, I'd want to see a compelling reason such as an open Issue or a CVN

**Comment by Vultraz** [comment]
I'll get back to this after 1.14.

**Comment by CelticMinstrel** [comment]
Um, what? I was pretty sure Wesnoth links dynamically against all its libraries.

**Comment by GregoryLundberg** [comment]
Sorry, right, we only statically link our stuff.

**Pull request closed without merging**
