### PR TITLE
Define core units without [base_unit] tag (Horse, Scorpion, Ant Egg)

### PR DESCRIPTION
**Pull request by OrekOrek**
Out of all 311 core units, only 5 relatively newly added units use `[base_unit]` tag as a part of their definition (Dark Horse, White Horse, Sand Scamperer, Sand Scuttler, and Fire Ant Egg).
To keep the consistency, and to prevent the potential nested structure of `[base_unit]` of `[base_unit]` in modified units, it is probably better to define core units without the tag.

1. Dark Horse, White Horse, Sand Scamperer, and Sand Scuttler are now defined without `[base_unit]` by copy-pasting data from respective base units.
2. The deprecated variation of Giant Scorpion (moved to Sand Scuttler) is untouched just in case, but it should be removed in the future.
3. Ant_Egg.cfg is the only file that defines 2 units (Giant Ant Egg and Fire Ant Egg) within a single file. They should be separate in my opinion, but I don’t know if separating causes any problem, especially when Giant Ant Egg (level 0) advances to Giant Ant (level 0) and it doesn’t appear in [the unit database](https://units.wesnoth.org/1.19/mainline/en_US/mainline.html). Therefore, Fire Ant Egg whose base unit is Giant Ant Egg is untouched for now.

I would like people to double-check the changes, and give opinions on Ant Eggs.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I don't understand the reason for this change. I guess I don't particularly care one way or the other, but it just seems pointless to arbitrarily remove `[base_unit]` usage for unexplained nebulous reasons.

**Comment by soliton-** [comment]
What issue is there with using `[base_unit]` on a unit that also uses `[base_unit]`?

**Comment by OrekOrek** [comment]
I’m sorry for being unclear about my reasoning and intention.
As a gaming program, there is nothing wrong with the current state. It automatically refers to the base unit stats and everything works fine.
However, for us people who read the codes, it is easier to understand the unit if all data is available in 1 file there just like the rest of 306 units. Also, it prevents accidental unit stats change when that of the base unit is changed in the future.

This is not something urgent or high-priority, but the philosophy is that;
if program A and program B work exactly the same way, there may be no reason to change A to B, but if adopting B reduces exceptions, there is no reason to persist with A just because it is the current version, either.

If using `[base_unit]` is better in general, we must use it more for other units as well, but the only reason why it is used only for these 5 units is that they are added recently as a part of the unit file patchwork. I believe nothing is wrong with making them just like the rest of the units.

**Comment by CelticMinstrel** [comment]
That's a better explanation of the reasoning. I'm not especially attached to the use of `[base_unit]`, for the record. I'll leave it up to someone else (probably @Pentarctagon or maybe @Dalas121) to decide whether you reasoning is enough to accept the PR.

**Comment by Pentarctagon** [comment]
I don't really have an opinion one way or the other.

**Comment by Dalas121** [comment]
I'm afraid I also don't have much of an opinion. This is mostly about the architecture of the underlying files, rather than the player-facing gameplay I understand the best.

**Comment by OrekOrek** [comment]
Thank you all for joining the conversation. I have nothing to add for now.

For the changed 4 units, I have checked in game that they are exactly the same as before.
For the Ant Eggs that are left out in this PR, a separate PR or Issue would be more appropriate because Giant Ant Egg is the only unit that advances to another unit of the same level (level 0 to level 0), and a more comprehensive approach than just removing `[base_unit]` seems necessary if any change is to be made.

**Comment by Pentarctagon** [comment]
I'll just go ahead and merge it then.

**Pull request merged**
