### PR TITLE
Fix remove overlay by addition of bis_overlay non persistent

### PR DESCRIPTION
**Pull request by newfrenchy83**
THIS PR must be resolve https://github.com/wesnoth/wesnoth/issues/4058 issue.
the main problem that came from the accumulation of a copy of the same image in overlays after each advancement, the best way is to limit the addition to images that are not already present rather than to make overlays non persistent.

### CODE REVIEW

**Comment by newfrenchy83** [comment]
@jostephd i hope what this PR will resolve problem of overlay for 1.15 version

**Comment by gfgtdf** [comment]
The overlays_.remove is needed to make remove modification of overlay effects work , I currently don't have much time but I think it better if I fix this myself.

**Comment by newfrenchy83** [comment]
All I have to do is propose the following solution: keep overlays as a persistent variable for all cases where apply_to = overlay is not used, and create a non-persistent bis_overlays variable for rare cases (in the core) or apply_to = overlay is used.
by assigning apply_to = overlay to this second variable, wml devellopers are avoided from reworking the code. It seems that the resolution of the non-persistent overlay AND the persistence of the overlay after expires_modification when overlay is persistent goes through TWO overlays variables in the wml code.

**Comment by jostephd** [comment]
@newfrenchy83 Thanks for letting me know of this PR. Sorry for the late answer, I've been away and haven't caught up on forums/github/discord yet.

**Comment by newfrenchy83** [comment]
@jostephd i replaced this PR by https://github.com/wesnoth/wesnoth/pull/4198

**Pull request closed without merging**
