### PR TITLE
Nerf of Orcish Crossbowman

### PR DESCRIPTION
**Pull request by Discontinuum**
The changes of Orcish Crossbowman made in 1.18 increased the power of this unit disproportionately. When advancing lvl 1 Orcish Archer, his melee damage rises extremely fast (3 times, from 3-2 of Orcish Archer to 6-3 of Orcish Crossbowman, which is unprecedented).

Also, the new xp requirement for advancing to level 3 is 43 (compared to 80 in 1.16), which is very close to lvl1-to-lvl-2 values. It becomes near-advancement after just several kills, which makes fighting him extremely troublesome.

My proposal is to set leveling XP to 57 (-10 xp compared to Orcish Warrior's 67 xp, like Orcish Archer-Orcish Grunt xp reqs) and to return 4-3 melee attack as it was in 1.16. I keep 1.18's increased hp (46 compared to 1.16's 43) and increased ranged pierce attack (9-3 vs 1.16's 8-3) because I believe those two were enough to make Orcish Crossbowman stronger without breaking things.

Regarding gold cost: in 1.16 he cost 21 gold, and after 1.18's buffs his price became 22 gold. I find just +1 gold completely unreasonable and weird for such substantial buffs. But after my nerf I think 22 gold becomes a reasonable price, so I let it stay unchanged.

### CODE REVIEW

**Review by Dalas121 — APPROVED** [review]
Seems fine to me from a SP perspective.

**Review by knyghtmare — APPROVED** [review]

**Comment by dashomew** [comment]
[DiD-Saving Parthyn replay 20241025-205418.gz](https://github.com/user-attachments/files/17527725/DiD-Saving.Parthyn.replay.20241025-205418.gz)

On the highest difficulty of DiD 1st scenario, "almost" impossible to kill the Orcish Leader, be it unluck that he did recruit  3 times the strongest Orcish unit in the list of 1.18, even AI recognize the overpowered Orcish Crossbowman.

I agree mostly with melee damage change returning him into the Archer Role instead that of an Hybrid Fighter.

About Experience Cap i agree with this nerf partialy, i would prefer few more digits, either way i am fine with this.

For the rest approved!~

**Comment by Jonathan-Kelly** [comment]
> When advancing lvl 1 Orcish Archer, his melee damage rises extremely fast (3 times, from 3-2 of Orcish Archer to 6-3 of Orcish Crossbowman, which is unprecedented).

Wow, that's crazy. It is good to see this advancement line being restored to a reasonable design.

**Comment by Roge-Tebnelok** [comment]
Maybe 6x2 instead of 4x3, and also I crease Archer's melee to 4x2 but decrease pierce ranged to 5x3? Everything else proposed is reasonable enough.

**Comment by Roge-Tebnelok** [comment]
> Maybe 6x2 instead of 4x3, and also I crease Archer's melee to 4x2 but decrease pierce ranged to 5x3? Or, to not debuff Archer, buff Bowman's ranged to 7x3? Everything else proposed is reasonable enough.

**Comment by ForestDragon-wesnoth** [comment]
I agree with dwarftough (Discontinuum)'s proposed stats

**Comment by Tezereth** [comment]
As I played LoW just yesterday, I can really confirm. Orcish crossbowmen in 1.18 are SCARY

No other enemy units, not even the lv1, got as close to leveling up as them, their xp requirement is LOWER than some lv1's. Their melee is also too high at 7x3, got multiple melee fighters dying trying to attack them that way.

So as far as the proposed changes goes, I think they seem quite great. I would be tempted to propose gold cost to be upped to 23 but 22 might be better as you proposed.

**Comment by ForestDragon-wesnoth** [comment]
> Their melee is also too high at 7x3, got multiple melee fighters dying trying to attack them that way.

I assume you with mean with the strong trait?

**Comment by Roge-Tebnelok** [comment]
> > **Discontinuum:** increased ranged pierce attack (9-3 vs 1.16's 8-3) because I believe those two were enough to make Orcish Crossbowman stronger without breaking things.
> 
> The XP makes the unit at the same power level of other Archers, so ranged buff isn't needed giving that the unit has **3 different damage types**, which makes it distinct enough from other Archers, plus little trivia to support my point about [Crossbow < Bow](https://www.youtube.com/shorts/KpS4cpaVr0M), as said on [Orcish Crossbowman](https://units.wesnoth.org/1.19/mainline/en_US/Orcish%20Crossbowman.html) description:
> 
> > very few tribes have any semblance of formal training in any of the warring arts. Because of this, orcish bowmen are rather ineffective at wielding longbows.
> 
> > these weapons can still be deadly even when handled roughly by inexperienced warriors.
> 
> Leading to the disparity of damage between [Orcish Archer](https://units.wesnoth.org/1.19/mainline/en_US/Orcish%20Archer.html) and Orcish Crossbowman, taking into account both trivia and description, Damage/Strikes in Wesnoth are interpreted in an **"abstract" way**, the wielded weapon differences/power and its taktikal/strategic use of them.
> 
> [Longbowman](https://units.wesnoth.org/1.19/mainline/en_US/Longbowman.html), [Elvish Marksman](https://units.wesnoth.org/1.19/mainline/en_US/Elvish%20Marksman.html), [Bone Shooter](https://units.wesnoth.org/1.19/mainline/en_US/Bone%20Shooter.html) and Orcish Crossbowman have all differences given by **Race** and/or dictacted by **Resources/Military culture**.

Orcish Archers are in fact half-orc, who are weaker and that's another reason why they are worse at shooting than humans, elves compensate for their weakness with speed and precision. Altough I agree that skill with weapon also affects damage, but crossbow doesn't require strength to be used effectively, and at the same time is used by stronger orcs, as evident by their hit/die sounds, and even with 9x3 they are still weaker than Longbowman or Marksman. What bothers me however is that fire ranged attack, Orcish Archer signature ability, suffered in usefulness because of increased pierce damage, altough Orcish Archer has the same issue. Without increasing Bowman's damage, which would make him overall better than Elvish Archer, Orcish Archer has the same piercing ranged damage as his human counterpart, for the same price, better xp and mobility which lower melee damage and slightly lower hp can't really compensate for. But with 5x3 ranged piercing damage Orcish Archer becomes overpriced, and orcs are known for their cheaper price, so, with reduced ranged piercing damage and increased melee damage, his price can be reduced to gp 13, which will allow him to be used more often, and that could partly solve Grunt Spam issue. Without reverting Crossbowman's ranged piercing damage to 8x3, to make fire ranged attack more useful, it can be increased to 11x2.

> > **Roge-Tebnelok:** Maybe 6x2 instead of 4x3, and also I crease Archer's melee to 4x2 but decrease pierce ranged to 5x3? Everything else proposed is reasonable enough. 
> 
> I think giving it 6dmg x 2 strikes melee would make it stronger and **WAY less unique**, in fact ALL the other Archers have 2 strike on melee from lvl1s to lvl3s. I highly dislike this one just for sake of uniqueness.

The other way around, actually, with base 6x2 his ToD buff will make him deal 7x2 damage, maximum 14 damage per attack without strong, while 4x3 at night becomes 5x3 with maximum 15 damage per attack. And Master Bowman has 3 melee hits per attack, Trapper has 4 melee hits per attack, if Thunderguard can count as an archer, he also has 3 melee hits per attack, so Crossbowman's 3 hit melee attack isn't that unique.

**Comment by dashomew** [comment]
> **Roge-Tebnelok:** Orcish Archers are in fact half-orc, who are weaker and that's another reason why they are worse at shooting than humans, elves compensate for their weakness with speed and precision. Altough I agree that skill with weapon also affects damage, but crossbow doesn't require strength to be used effectively, and at the same time is used by stronger orcs.

Yeah, my summary if it was verbose, go on xP

> **Roge-Tebnelok:** as evident by their hit/die sounds

XD okay, yes they are lvl2, fair??? XD tho i think they are still "half-orcs" so they can grow in power through experience *wink* and training.

> **Roge-Tebnelok:** and even with 9x3 they are still weaker than Longbowman or Marksman.

YES, for Elvish Marksman, but Orcish Crossbowman is as "strong" (even stronger IMO than) as Longbowman becouse of... (one) damage versatility, (two) huge XP buff that the fix is yet bringing...
> **Discontinuum:** in version 1.18 xp requirement to level 3 is 43xp (compared to 80xp in 1.16), proposed change 57xp

... (three) better mobility [Terrain Cost].

> **Roge-Tebnelok:** What bothers me however is that fire ranged attack, Orcish Archer signature ability, suffered in usefulness because of increased pierce damage

Yes and no, fire damage is situational and is usefull because of how the whole unit is designed and combos with how the faction works, adding to why +1dmg on pierce ranged is bad.

> **Roge-Tebnelok:** altough Orcish Archer has the same issue.

Different discussion. Open Orcish Archer PR i guess XD i'm not familiar how this site works.

> **Roge-Tebnelok:** The other way around, actually, with base 6x2 his ToD buff will make him deal 7x2 damage, maximum 14 damage per attack without strong, while 4x3 at night becomes 5x3 with maximum 15 damage per attack. 

Talking about competitive mostly in this sentence, it makes them way better against a Charger/Ulf or Melee Unit, kind of a big deal, retalition with few strikes and high dmg can be hell, even without Strong Trait.

> **Roge-Tebnelok:** Trapper has 4 melee hits per attack, if Thunderguard can count as an archer, he also has 3 melee hits per attack.

IMO they aren't, they are Ranged units yes, but fall into Elvish Ranger category (Hybrid Fighter), and Thunderer is ever further from that one considering how weird he is XD, btw Dwarves are as melee focused as Orcs.

> **Roge-Tebnelok:** Though, for orcs who are generally better at melee than ranged compared to other races
, it doesn't make sense for Crossbowman, almost full orc, be so much weaker compared to Longbowman with 8x2 damage.

They are "half-orcs" but i never seen a description saying that they aren't as strong as an Human, but Orcish Archer description says: ~ _smaller stature or build_ ~ which would make sense for Orcish Crossbowman to have more strikes rather than damage.

**Comment by Roge-Tebnelok** [comment]
> XD okay, yes they are lvl2, fair??? XD tho i think they are still "half-orcs" so they can grow in power through experience _wink_ and training.

Actually, the same happens to Assassins, after they become Slayers, though that's more about sound usage.

> > **Roge-Tebnelok:** and even with 9x3 they are still weaker than Longbowman or Marksman.
> 
> YES, for Elvish Marksman, but Orcish Crossbowman is as "strong" (even stronger IMO than) as Longbowman becouse of... (one) damage versatility, (two) huge XP buff that the fix is yet bringing...
> 
> > **Discontinuum:** in version 1.18 xp requirement to level 3 is 43xp (compared to 80xp in 1.16), proposed change 57xp
> 
> ... (three) better mobility [Terrain Cost].

That makes them stronger as a unit, but not as archer, but I agree, movement advantege should be taken in consideration, I forgot to bring it up myself.

> > **Roge-Tebnelok:** What bothers me however is that fire ranged attack, Orcish Archer signature ability, suffered in usefulness because of increased pierce damage
> 
> Yes and no, fire damage is situational and is usefull because of how the whole unit is designed and combos with how the faction works, adding to why +1dmg on pierce ranged is bad.

They are the only unit line who uses fire arrows, dunefolk doesn't count, altough they use fire arrows as sprite projectiles, their attack is more like greek fire, and Orcish fire ranged attack is more situational partly because of big difference between maximum piercing and ranged damage the line can deal, the same happens with 1.18 Shyde's entangle, singature abilities should be similar in effectiveness to alternative attacks, so they are used more often, though now I think 12x2 would be even better for 9x3, 11x2 leaves a bit too much of a damage difference and therefore should be used for 8x3,altough 10x2 works with 1.16 as well
.
> > **Roge-Tebnelok:** altough Orcish Archer has the same issue.
> 
> Different discussion. Open Orcish Archer PR i guess XD i'm not familiar how this site works.

They are directly connected, so it's relevant enough.

> > **Roge-Tebnelok:** The other way around, actually, with base 6x2 his ToD buff will make him deal 7x2 damage, maximum 14 damage per attack without strong, while 4x3 at night becomes 5x3 with maximum 15 damage per attack.
> 
> Talking about competitive mostly in this sentence, it makes them way better against a Charger/Ulf or Melee Unit, kind of a big deal, retalition with few strikes and high dmg can be hell, even without Strong Trait.

Not sure about influence on Ulf, is he going to keep his 20% slashing resistance or not, in case not it would be -2 damage, otherwise it's +1 damage, but for Horseman difference in damage taken is +2, maximum 18 for 4x3 or maximum 20 for 6x2, that's better but not that much, with strong it will be maximum 24 for 4x3(5x3 with strong) or 22 for 6x2 (7x2 with strong), -2 damage difference between 4x3 with strong and 6x2 with strong, so 4x3 is still better against charge than 6x2, 7x2 with or without strong is more powerful than 4x3 either way, maximum 18/24 with strong for 4x3 (5x3 with strong) vs 22/26 with strong for 7x2 (8x2 with strong), +6/+10 with strong damage difference.
> 
> > **Roge-Tebnelok:** Trapper has 4 melee hits per attack, if Thunderguard can count as an archer, he also has 3 melee hits per attack.
> 
> IMO they aren't, they are Ranged units yes, but fall into Elvish Ranger category (Hybrid Fighter), and Thunderer is ever further from that one considering how weird he is XD, btw Dwarves are as melee focused as Orcs.

Fair enough, though compared to melee focused humans units Dwarves start to get melee damage advantage only from level 2 and only with one unit, Steelclad, on level 1 they are similar as far as damage is concerned.

> > **Roge-Tebnelok:** Though, for orcs who are generally better at melee than ranged compared to other races
> > , it doesn't make sense for Crossbowman, almost full orc, be so much weaker compared to Longbowman with 8x2 damage.
> 
> They are "half-orcs" but i never seen a description saying that they aren't as strong as an Human, but Orcish Archer description says: ~ _smaller stature or build_ ~ which would make sense for Orcish Crossbowman to have more strikes rather than damage.

Orc Archers are weaker than true orcs, who are stronger than average human, and often lack training which would make them more accurate, but also build their muscules, humans get this training, thats why they are better archers and melee fighters, short swords also allow them to deal more damage, but not too much, daggers are more dangerous in closer combat, but melee distance advantage sadly isn't reflected in Wesnoth's gamemechanics aside from first strike, and short swords aren't as light as daggers, and require strength to be used effectively, especially because they are balanced for one hand, so half-orcs need even more additional training to swing fast with their lower strength. And because crossbow is something that is more often given to smart archers than strong ones, they usually don't get that additional training needed to make more light hits with short sword, less strikes with more power is easier to do.

**Comment by Discontinuum** [comment]
@Roge-Tebnelok my aim is to fix the stats that make Orcish Crossbowman broken, so I don't want to change his melee from 3 strikes to 2 strikes - it will change the unit on a more fundamental level and I don't want that. 
Orcish Archer in my opinion also does fine, so I don't think we should tweak him

**Comment by Roge-Tebnelok** [comment]
> @Roge-Tebnelok my aim is to fix the stats that make Orcish Crossbowman broken, so I don't want to change his melee from 3 strikes to 2 strikes - it will change the unit on a more fundamental level and I don't want that. Orcish Archer in my opinion also does fine, so I don't think we should tweak him

Fair enough, although if a unit can be improved, why shouldn't we do that?

**Comment by Discontinuum** [comment]
Comparing to 1.16, Orcish Crossbowman stays improved: +3 hp, +1 ranged pierce damage, less xp to level.

Regarding Orcish Archer - this unit does fine both in SP and MP. So improvements here aren't needed

**Comment by Roge-Tebnelok** [comment]
> Comparing to 1.16, Orcish Crossbowman of this PR stays improved: +3 hp, +1 ranged pierce damage, less xp to level.
> 
> Regarding Orcish Archer - this unit does fine both in SP and MP. So improvements here aren't needed

There's still a space for improvements, and there's nothing wrong in improvement of a unit that is already good enough, but if you don't wan't that now, it can wait.

**Comment by CelticMinstrel** [comment]
> Orcish Archers are in fact half-orc

Starting from a false premise isn't going to make your argument work. There are no half-orcs in the game. The archers and assassins draw from the pool of what I think I'd call the "average" orc, with the warriors being the "exceptionally strong and large" orcs and the goblins being the "runts". But they are all full orcs.

**Comment by Roge-Tebnelok** [comment]
> > Orcish Archers are in fact half-orc
> 
> Starting from a false premise isn't going to make your argument work. There are no half-orcs in the game. 

There aren't now, they were until 1.14, that's how weaker orcs who aren't goblins were called, now they don't have any name. Outdated info that doesn't contradict current isn't false. And it doesn't matter now anyway, I'm not sure why you commented on this post in the first place.

> The archers and assassins draw from the pool of what I think I'd call the "average" orc, with the warriors being the "exceptionally strong and large" orcs and the goblins being the "runts". But they are all full orcs.

On the other hand, we have definition of "true orcs" even up to date, and Archers and Assassing don't fall within this definition. I'm not disputing that they all are full orcs, just using a more convenient term.

**Comment by CelticMinstrel** [comment]
> On the other hand, we have definition of "true orcs" even up to date, and Archers and Assassing don't fall within this definition.

Then that definition is wrong.

**Comment by Roge-Tebnelok** [comment]
> > On the other hand, we have definition of "true orcs" even up to date, and Archers and Assassing don't fall within this definition.
> 
> Then that definition is wrong. There is nothing less "true" about an archer orc.

About that you have to argue not with me but with whoever put it in their race description. I don't have any issues with trueness of Grunt and falseness of Archer or Assassin, and although I prefer their older race description with a clear division between true orcs, half-orcs and goblins, current one is good enough.

**Comment by Pentarctagon** [comment]
For MP, my understanding/recollection is that the Orcish Archer changes are considered a problem because it's too easy to level them up and the Orcish Crossbowman changes are considered a problem since it makes the unit too powerful. That sounds like something which would be fairly easy to demonstrate directly in a game?

**Comment by dashomew** [comment]
> **Penta:** For MP, my understanding/recollection is that the Orcish Archer changes are considered a problem because it's too easy to level them up and the Orcish Crossbowman changes are considered a problem since it makes the unit too powerful.

For MP, Orcish Archer didn't have a problem, 1.18 patch didn't touch him, but the buff of Orcish Crossbowman makes one.. the melee powerup is mostly what unbalance it for MP, xp is crazy but still unlikely to happen for how maps are designed.

> **Penta:** That sounds like something which would be fairly easy to demonstrate directly in a game?

I guess if a new Balance Team is proposed you will know ^^

**Comment by Roge-Tebnelok** [comment]
> > **Penta:** For MP, my understanding/recollection is that the Orcish Archer changes are considered a problem because it's too easy to level them up and the Orcish Crossbowman changes are considered a problem since it makes the unit too powerful.
> 
> For MP, Orcish Archer didn't have a problem, 1.18 patch didn't touch him, but the buff of Orcish Crossbowman makes one.. the melee powerup is mostly what unbalance it for MP, xp is crazy but still unlikely to happen for how maps are designed.

I disagree, every time I see Crossboworcs in MP they get dangerously close to leveling up, but melee retaliation isn't dangerous enough for more melee focused units to be discouraged from attacking, more powerful ranged attack is, it's even used against other archer units more often than melee, despite the latter being much safer option with maximum damage difference not as big as it was in 1.16. So, what really unbalances Crossboworcs is their increased ranged attack, followed by low XP.

> > **Penta:** That sounds like something which would be fairly easy to demonstrate directly in a game?
> 
> I guess if a new Balance Team is proposed and approved you will know ^^

The demonstrations have to be genuine matches, tests in lab conditions with one player controlling both sides and creating units via debug will more likely give results that don't correspond with reality. Just tried to run an archery test on Merkwuerdigliebe, with every faction and orcs being able to attack them, recruiting only bowmen, e.g. no DAs or Thunderers, Drakes use only Burners, everyone have taken the best positions on the map but that prevents me from ordering the first attack, for I know that this will put attackers at disadvantage, with an opponent I think this wouldn't be the case, though every mistake a player makes needs to be noted.

**Comment by dashomew** [comment]
> **Roge-Tebnelok:** I disagree, every time I see Crossboworcs in MP they get dangerously close to leveling up

Yeah, sorry had to speficy Competitive 1v1. 

I would get pretty triggered if it happens in a Competitive environment, tho is as much unlikely as an adept or a mage to get to lvl2, and the current 1v1s i see use Balanced Era from SkyEnd, and little to none Ladder/LadderEra games are played, which don't use Default Era. 

Played an Isar's Cross game today as Orc Crossbowman (i didn't get a chance to use it) but 1 single Orcish Archer level up could really ruin your mental and game balance.

> **Roge-Tebnelok:** melee retaliation isn't dangerous enough for more melee focused units to be discouraged from attacking

For a lvl2 MeleeFighter probably, which is not the case for MP(Default Era) and Competitive, but for a lvl1 MeleeFighter its nightmare.


> **Roge-Tebnelok:** more powerful ranged attack is, it's even used against other archer units more often than melee despite the latter being much safer option with maximum damage difference not as big as it was in 1.16. So, what really unbalances Crossboworcs is their increased ranged attack, followed by low XP.

What XD, no-shit-sherlock.. if you are attacking Archers with Archers, you are doing something wrong or you need that exact damage to kill the enemy Archer OR have better ToD/Dodge% and the other "100" VALID reasons that you would want to do that, now even MeleeFighters fall into this situation.

Btw thanks for agreeing on Orcish Crossbowman +1dmg on Ranged Pierce makes it too strong, i see i have changed your mind!

**Comment by Roge-Tebnelok** [comment]
> > **Roge-Tebnelok:** melee retaliation isn't dangerous enough for more melee focused units to be discouraged from attacking
> 
> For a lvl2 MeleeFighter probably, which is not the case for MP(Default Era) and Competitive, but for a lvl1 MeleeFighter its nightmare.

Not as much as another level 1 melee focused unit. All of them deal as much melee damage as Crossbowman if not more, their hp also isn't that different, and they are much cheaper.

> > **Roge-Tebnelok:** more powerful ranged attack is, it's even used against other archer units more often than melee despite the latter being much safer option with maximum damage difference not as big as it was in 1.16. So, what really unbalances Crossboworcs is their increased ranged attack, followed by low XP.
> 
> What XD, no-shit-sherlock.. if you are attacking Archers with Archers, you are doing something wrong or you need that exact damage to kill the enemy Archer OR have better ToD/Dodge% and the other "100" VALID reasons that you would want to do that, now even MeleeFighters fall into this situation.

I also think so, and yet it was done by my opponents, and they won more often than not. Granted, I'm a SP main, and my MP experience is limited, that's why I'm hesitant to move under attack from good position, even if I'm taking one myself, let alone attack an enemy who isn't on flat or bad terrain like water. More experienced players are more willing to take these risks.

> Btw thanks for agreeing on Orcish Crossbowman +1dmg on Ranged Pierce makes it too strong, i see i have changed your mind!

It's too strong without additional hp increase on every unit, which is harder to do than to decrease damage. That's why slow is such a powerful ability.

**Comment by Discontinuum** [comment]
> For MP, my understanding/recollection is that the Orcish Archer changes are considered a problem because it's too easy to level them up and the Orcish Crossbowman changes are considered a problem since it makes the unit too powerful. 

Level 1 Orcish Archer doesn't have problem. In 1.18 he almost didn't change (expect for 32 xp vs 30 xp to level). I don't see problems with him so didn't change him in this PR

Orcish Crossbowman became problematic in 1.18 with increased melee and dramatically less xp to level to lvl 3. Dashomew's replay in the beginning of the PR (Descend in Darkness, scenario 1) demonstrates that: strong Orcish Crossbowman has 9-3 melee at night, so kills a 
18 hp Walking Corpse with 2 hits making this scenario significantly harder than it used to be. The decreased xp requirement makes them get close to level very quickly after some lucky kills, so destroying them becomes quite risky. 

Regarding increased ranged pierce attack, I don't mind lower it back to 1.16's 8-3 if 1.18's 9-3 causes troubles as well. In my experience I feel new melee and very low xp to level causing more evident problems

**Comment by dashomew** [comment]
> **Discontinuum:** Level 1 Orcish Archer doesn't have problem. In 1.18 he almost didn't change (expect for 32 xp (1.18) vs 30 xp (1.16) to level). I don't see problems with him so didn't change him in this PR

Damn it, i got gaslighted by [Henjewar forum post](https://forums.wesnoth.org/viewtopic.php?t=56867), i will never use forum to check this things.. only github changelogs.., in this case the Orcish Archer change is just a petty nerf to (especialy **hard on Orcs** against the Undeads) justify a bad buff for Orcish Crossbowman.

The Xp difference is:

- [1.16]  Intelligent= 17xp --> Without= 21xp

- [1.18]  Intelligent= 18xp --> Without= 22xp

> **Dashomew:** a petty nerf to justify a bad buff

IMO note this!
Henjewar changes turn to be like this, lvl1 XP nerf --> his lvl2 advancement get buffs (exemple Elvish Scout vs Elvish Outrider)

> **Discontinuum:** Regarding increased ranged pierce attack, I don't mind lower it back to 1.16's 8-3 if 1.18's 9-3 causes troubles as well. In my experience I feel new melee and very low xp to level causing more evident problems.

If Crossbowman staying at 9x3 prevents Orcish Archer to undo 1.18 xp change, i am against it.

1 xp difference will sound like a shitty revert to most, tho for Competitive 1v1 an Hard Matchup where Orcs already have the disadvatage would make for a weak change to enhance its difficulty.

**Comment by Roge-Tebnelok** [comment]
> > **Discontinuum:** Regarding increased ranged pierce attack, I don't mind lower it back to 1.16's 8-3 if 1.18's 9-3 causes troubles as well. In my experience I feel new melee and very low xp to level causing more evident problems.
> 
> If Crossbowman staying at 9x3 prevents Orcish Archer to undo 1.18 xp change, i am against it.

I would rather undo 9x3 than OA's 32 XP, they already are as powerful as human archers, save hp and melee and they differ slightly. Of course, melee and XP buff on OC should be reverted/revised, but ranged damage is the biggest issue imo. Not sure even debuffing Archer to 5x3 7x2 and buffing Crossbowman's fire to 12-13x2 is enough to fix 9x3 without reverting it.

**Comment by dashomew** [comment]
> Roge-Tebnelok I would rather undo 9x3 than OA's 32 XP, they already are as powerful as human archers, save hp and melee and they differ slightly. 

You are comparing by unit to unit.

I compare by matchup to matchup, faction to faction, unit to unit.

### **We are not the same**

----------------------
Memes Formats aside XD

Northerners have different needs than Loyalist, you can't keep comparing them mindlessly to other units.
(talking about Orc Archer in this specific case) Obviously it is more about Competitive Balance, it won't change anything for SP side... ;-:

**Comment by Roge-Tebnelok** [comment]
> > Roge-Tebnelok I would rather undo 9x3 than OA's 32 XP, they already are as powerful as human archers, save hp and melee and they differ slightly.
> 
> You are comparing by unit to unit.
> 
> I compare by matchup to matchup, faction to faction, unit to unit.
> 
> ### **We are not the same**

Incorrect. It's unit to unit, faction to faction, matchup to matchup on my part :).

> Memes Formats aside XD
>
> Northerners have different needs than Loyalist, you can't keep comparing them mindlessly to other units. (talking about Orc Archer in this specific case) Obviously it is more about Competitive Balance, it won't change anything for SP side... ;-:

If a solution how to meet one faction's needs requires to stop meeting other faction's needs that was already met, that solution creates one issue in place of another. I'm comparing Orc Archer to Bowman because Skeleton Archer has resistances that significantly change the approach to their other stats, Poacher as you said is more of a mixed fighter, though it's not the case on level 1, and it's more because of more hits with less damage, same for Elvish Archer, and Drake Burner is an archer only because of his role, and he has not only better attack, but also hp, resistances, mobility and worse defense, price and XP, which makes him even more extreme case than Skeleton Archer. And change in Competitive balance is also reflected in SP, in fact, most issues with current balance come from SP.

**Comment by dashomew** [comment]
> **Roge-Tebnelok:** If a solution how to meet one faction's needs requires to stop meeting other faction's needs that was already met, that solution creates one issue in place of another.

Yes, it can shift meta and disadvantage/advantage of matchups.

> **Roge-Tebnelok:** I'm comparing Orc Archer to Bowman because Skeleton Archer has resistances that significantly change the approach to their other stats, Poacher as you said is more of a mixed fighter, though it's not the case on level 1, and it's more because of more hits with less damage, same for Elvish Archer, and Drake Burner is an archer only because of his role, and he has not only better attack, but also hp, resistances, mobility and worse defense, price and XP, which makes him even more extreme case than Skeleton Archer.

Yeah, the closes resemblance to Orc Archer, still Comparison by unit to unit :P

> **Roge-Tebnelok:** And change in Competitive balance is also reflected in SP, in fact, most issues with current balance come from SP.

Agree, Competitive MP is susceptible to minimal changes and huge changes, SP is susceptible mostly to huge changes, MP suffers more.

So are you against what i proposed about Orc Archer? I don't understand what you think about it, are trying to make a point other than showing your game knowledge.

**Comment by Roge-Tebnelok** [comment]
> > **Roge-Tebnelok:** I'm comparing Orc Archer to Bowman because Skeleton Archer has resistances that significantly change the approach to their other stats, Poacher as you said is more of a mixed fighter, though it's not the case on level 1, and it's more because of more hits with less damage, same for Elvish Archer, and Drake Burner is an archer only because of his role, and he has not only better attack, but also hp, resistances, mobility and worse defense, price and XP, which makes him even more extreme case than Skeleton Archer.
> 
> Yeah, the closes resemblance to Orc Archer, still Comparison by unit to unit :P

You can't do it other way, can you?

> > **Roge-Tebnelok:** And change in Competitive balance is also reflected in SP, in fact, most issues with current balance come from SP.
> 
> Agree, Competitive MP is susceptible to minimal changes and huge changes, SP is susceptible mostly to huge changes, MP suffers more.

I meant the other way around, the changes that created issues for SP was made for MP or for no explained reason, MP and SP are equally important and susceptible but SP suffers more because most of the time it's not fractions who are balanced around faction matches and who does the fighting, it's their parts, and if an unbalanced unit gets into these parts, they are used more often and that puts either player or ai in undeserved advantageous or disadvantageous position. In MP players have a better adaptability than in SP.

> So are you against what i proposed about Orc Archer? I don't understand what you think about it, are trying to make a point other than showing your game knowledge/understanding.

If you mean reverting to ranged 8x3, no, I agree, these were the examples why 9x3 can't be kept, even with debuffing Archer.

**Comment by Dalas121** [comment]
@Hejnewar

**Comment by cooljeanius** [comment]
The main thing I noticed when testing SotBE:EE on 1.18 was the XP part; maybe increase the XP more in exchange for keeping a bit of the buffed melee damage? 60XP and 5 melee damage?

**Comment by Roge-Tebnelok** [comment]
> The main thing I noticed when testing [SotBE:EE](https://github.com/cooljeanius/Son_Of_The_Black_Eye_Easy_Edition) on 1.18 was the XP part; maybe increase the XP more in exchange for keeping a bit of the buffed melee damage? 60XP and 5 melee damage?

60 xp is a bit too small, not unheard of among level 2 units, but I would raise it closer to 80, regardless if Crossbowman gets melee 5x3 instead of 4x3, which isn't a bad idea.

**Comment by ForestDragon-wesnoth** [comment]
I agree with Roge, either 80 or something between 65-75 could work

**Comment by cooljeanius** [comment]
> I agree with Roge about xp, it should be either 80 or something between 65-75

69.

**Comment by Dalas121** [comment]
Balance team vote held (credit to Knyghtmare), passed 4-0.

If you can create a changelog, this'll be good to merge.

**Pull request merged**
