### PR TITLE
swarm tests

### PR DESCRIPTION
**Pull request by Pentarctagon**

### CODE REVIEW

**Comment by ProditorMagnus** [comment]
swarm_disables_upgrades and maybe more can be moved here

**Comment by newfrenchy83** [comment]
Schéma validation don't support double values for swarm

**Comment by ProditorMagnus** [comment]
I did not investigate if tests already cover if float value is used, therefore whether to update schema or tests.

**Comment by Pentarctagon** [comment]
The tests have been updated. It's correct for the schema to reject such values since they're not really handled - if they were, then they'd do proper rounding.

**Pull request merged**
