### PR TITLE
Add quick-start instructions on building Wesnoth in Windows

### PR DESCRIPTION
**Pull request by dlshcbmuipmam**
The INSTALL.md file contains only the instructions of CMake and Scons, but neither of the default options works in Windows, even after the listed dependencies are installed using MinGW-w64. Therefore, I have added a quick instruction on the essential options needed by Scons in MinGW-w64.

### CODE REVIEW

**Comment by jyrkive** [comment]
I think these instructions aren't really that relevant. The best C++ IDE for Windows is Microsoft Visual Studio, primarily because of its top-notch debugger. We have an existing VS project file in the repository, and [instructions](https://wiki.wesnoth.org/CompilingWesnothOnWindows#Visual_Studio) for compiling with in in the wiki.

**Comment by dlshcbmuipmam** [comment]
> I think these instructions aren't really that relevant. The best C++ IDE for Windows is Microsoft Visual Studio, primarily because of its top-notch debugger. We have an existing VS project file in the repository, and [instructions](https://wiki.wesnoth.org/CompilingWesnothOnWindows#Visual_Studio) for compiling with in in the wiki.

I think you are correct if this project is a pure Windows project. However, I guess many of the developers coming from the Linux side, who may not like the heavy Visual Studio, still want to test their commit on Windows. Mingw provides an useful Linux-like environment for them to do simple tests. 

Besides, I think one of the most important aspects of tools including CMake and Scons, is their ability to cross platforms. In this sense, maintaining a separate VS project seems not to be an elegant idea. My personal preference is using Mingw and CMake/Scons, but it can also be done by generating VS project by CMake. I think it is good to open up more options instead of limiting developers to use Visual Studio.

Anyway, even if pure Visual Studio is the right way to go, I think there should be some instructions about Windows in this github project besides the wiki page. According to the current documentation, the natural walkthrough of newcomer is: README.md -> README.md asks me to go INSTALL.md -> CMake or Scons -> try CMake -> fails -> install missing dependencies -> try CMake again -> fails ->  Google -> Wesnoth's wiki says Scons is working -> try Scons -> fail -> Google -> fix the problem / try Visual Studio / leave.

**Comment by jyrkive** [comment]
We don't "limit" developers to use Visual Studio. The wiki page I linked above also contains instructions for Code::Blocks and a SCons + TDM-GCC combo.

The main reason why INSTALL.md doesn't have compile instructions for Windows is that Windows users don't need to compile the game from source unless they want to develop the game themselves. Windows simply doesn't have priority for build instructions.

IMO, it would be a good idea to add Windows build instructions to INSTALL.md, but not really favoring MinGW like this. At least Visual Studio would also need to be covered. (TDM-GCC and Code::Blocks are less important because they're harder to support and we might drop them in the future.)

**Comment by GregoryLundberg** [comment]
I note that the Windows (Visual Studio) compiler tool set is actually separate from Visual Studio and can be downloaded separately, and run standalone, as we do for AppVeyor.

**Comment by dlshcbmuipmam** [comment]
> I note that the Windows (Visual Studio) compiler tool set is actually separate from Visual Studio and can be downloaded separately, and run standalone, as we do for AppVeyor.

That's how I normally use microsoft's compiler :)  I actually prefer working with the commandline tools (e.g. MSBuild) and some other editors (e.g. VScode, vim, etc.). However, from what I know, the management of the solution files and the project files is quite tedious without the full Visual Studio. Therefore, I prefer generating the VS project files by CMake instead of directly maintaining the project files. Of course, it is just my personal taste, I am just hoping that Windows development preparation can be simplified and documented.

**Comment by jostephd** [comment]
I don't know if the build instructions should be in INSTALL or in the wiki, but even if VS is the "recommended" way to build on windows, I see no reason not to document alternative ways alongside it.

**Comment by sigurdfdragon** [comment]
I'm in favor of the proposed instructions being added in some form.
They are similar to https://forums.wesnoth.org/viewtopic.php?f=5&t=48296
which I've been using, and has been the quickest & easiest way for me to build on windows that I've used

**Pull request closed without merging**
