### PR TITLE
Deploy Cutscene Themes

### PR DESCRIPTION
**Pull request by sigurdfdragon**
Makes use of Cutscene and Cutscene_Minimal themes for all scenarios in mainline that I am aware would benefit from it.

There seems to be a slight graphical hiccup when switching to Cutscene mid scenario in the third commit.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
With the second commit, if the user selects a different theme in preferences (for example, Classic), will that choice be honoured after the cutscene has ended.

If not, I'd suggest trying `theme=` - an empty attribute.

**Comment by sigurdfdragon** [comment]
@CelticMinstrel No, it wasn't honored. Thanks for the suggestion, that worked, and I've updated the commit.

**Comment by sigurdfdragon** [comment]
I think I may remove the 2nd & 3rd commits.
The third one because of the glitch, and both because for the non-SotA changes I'm not sure the cases warrant using them, and that's a decision best left for the campaign maintainers.

**Comment by Vultraz** [comment]
I think we should just merge the first commit for now.

**Comment by CelticMinstrel** [comment]
You can totally cherry-pick it and leave the PR open, if you want.

**Comment by sigurdfdragon** [comment]
I'll strip it down to the first commit and get it merged by the end of the week.
I'll pick the other two and stash them on a local branch of my repo copy.

**Pull request merged**
