### PR TITLE
Concede button

### PR DESCRIPTION
**Pull request by DaJulian**
Adds a concede button that can be added to a theme's menu via WML "concede"

### CODE REVIEW

**Comment by gfgtdf** [comment]
1) the commits look messy: it seems to contain quietsome unrelated changes.
2) This can already easily be done with wml (i made a concede defaet addon for that in teh 1.12 server so i wonder what are teh advantaged of implementing this in the engine?)
3) your code looks like it would cause OOS since it just sets the defeat condition to always on the current client.

**Comment by CelticMinstrel** [comment]
@gfgtdf Regarding point 2, note that this feature is [explicitly requested](http://wiki.wesnoth.org/EasyCoding#Add_a_.22concede.22_button). I'm not entirely sure what the advantages are of having it in the engine, though.

**Comment by gfgtdf** [comment]
Anothe issue: your code uses spaces for indent (tabs ar teh preferec indent for teh c++ sources)

**Comment by aginor** [comment]
I would like to test these changes against the SDL2 branch as well before they are merged. I'll test once the other issues have been resolved.

**Comment by Wedge009** [comment]
Is there any progress on this? If this was cleaned up and rebased, it would make testing easier.

Thanks.

**Comment by gfgtdf** [comment]
Like i said before this code causes OOS becasue the side will onyl be defeated on the client that ckicked that button, not on the other clients, so i see no need to test this yet.

Iirc the main intention behind the concede button is that the server can make a differene between 'giving up and leaving' and 'leaving becasue of other issues'/diconnects. So that the server can for example make about things like whihc faction win more often e.t.c.

**Comment by gfgtdf** [comment]
closing this since it doesn't seem like this pr will ever be fixed.

**Pull request closed without merging**
