### PR TITLE
HttT: minor grammar tweak

### PR DESCRIPTION
**Pull request by jostephd**

### CODE REVIEW

**Comment by jostephd** [comment]
Later in this scenario Relgorn says:

https://github.com/wesnoth/wesnoth/blob/b83a3b3d1de9197ecf159b611270915ce0cb2461/data/campaigns/Heir_To_The_Throne/scenarios/14_Plunging_Into_the_Darkness.cfg#L452

Is the phrase "We know not where the Sceptre is though" not missing a comma?  (Moreover, with the "though" at the end it sounds more like a book than like a conversation, but maybe that's just me.)

**Comment by CelticMinstrel** [comment]
That's one of the places where comma use seems to be optional. I have no idea how putting it at the end makes it sound like a book; I use "though" at the end of a sentence often enough. If I wanted a lead word with the same meaning I'd probably use "However".

**Comment by GregoryLundberg** [comment]
Given the archaic phrasing I'd suggest: ...at your service though we know not ...

**Comment by jostephd** [comment]
Changed it to "at your disposal, though we know not" -- hopefully it's archaic now?

@GregoryLundberg Did you mean to also change "disposal" to "service"?  I kept it as is since I wasn't sure.

**Comment by Vultraz** [comment]
Honestly think it would sound better as:
> We must not fight among ourselves as the evil orcs roam the lands above us!

and
> I will put my best men at your disposal, though we know naught of the Sceptre’s location.

**Comment by GregoryLundberg** [comment]
'service'? Well that shows you read what you expect sometimes instead of what's there.

@Vultraz Your suggestion reads to me as if it would be acceptable to fight among ourselves if there were no evil orcs (none at all, or only good orcs) roaming the lands above us, or the evil ones would roam elsewhere.

**Comment by Vultraz** [comment]
Well, isn't the point of the sentence to convey "holy shit there are evil orcs roaming about and fighting amongst ourselves is counterproductive and makes us more vulnerable"?

**Comment by jostephd** [comment]
I agree with @GregoryLundberg that moving the "as" from the start of the sentence to the middle changes its meaning (from "Because" to "whilst").

I've pushed another commit implementing the "naught" suggestion.

**Comment by jostephd** [comment]
> > We must not fight among ourselves as the evil orcs roam the lands above us!

I've pushed this with s/as/for/ for clarity.  Okay?

**Comment by Vultraz** [comment]
Hmmm... I do think that changes the meaning a bit. The party already knows about the orcs. I think I'd prefer "as" still, but I'll leave it to you to decide.

Either way, please squash these commits into one with the final version and I'll merge.

**Comment by Vultraz** [comment]
Also, feel free to add yourself the the Misc Contributors section of the credits (`data/core/about.cfg`) if you haven't already. :)

**Comment by jostephd** [comment]
I didn't mean to change the meaning.  I think "for the evil orcs roam" implies the party knows about them; if the party hadn't known about the orcs, Delfador would have said "for evil orcs roam" without "the".

I'll squash, etc tomorrow.  Thanks!  (+ for merging the other PR's as well)

**Comment by jostephd** [comment]
Squashed.

**Pull request merged**
