### PR TITLE
Bug fix23201: Toggle icons display error in replay.

### PR DESCRIPTION
**Pull request by Randypk**
Enable hotkeys from replay controller so they show the correct status when the replay is loaded.

### CODE REVIEW

**Comment by gfgtdf** [comment]
seems like the line with 'Version 1.13.0-dev:' was changed i dont know really what was changed though.

**Comment by AI0867** [comment]
I downloaded the diff (https://github.com/Randypk/wesnoth/commit/394dde068fa327f8c4180a4c025e15abd22a5439.diff) to check, and it's a UTF-8 BOM that was prepended. This needs to be fixed.

**Comment by Randypk** [comment]
Not sure what happened there.  I nuked the commit, fixed up the changelog and put in a new commit.
Should be good now.

**Comment by gfgtdf** [comment]
I would be better to remove the "Update change log for bugfix #23201." commit and the revert commit by rebasing.

**Comment by Randypk** [comment]
I already did the revert, but both commits still show in the branch.  I could just remove this entire branch and put in a new one.  Let me know.

**Comment by gfgtdf** [comment]
you can remove commits froma branch completely without reverting, to so so type:
```
git rebase -i HEAD~4
```
in the git commandline then a text editor will pop up (make sure you didnt had any texteditors open before)

there will be 4 lines (one for every commit) remove the lines from the commit you want to remove (the 2 in the middle) and then close the text editor.

Some parts might be differnt depending on which OS or which git client you use.

**Comment by Randypk** [comment]
Thanks, that worked.  Only the 2 commits are in the branch now.

**Comment by Randypk** [comment]
This should be now.

**Comment by gfgtdf** [comment]
merged into master

**Pull request closed without merging**
