### PR TITLE
add tag [random_placement]

### PR DESCRIPTION
**Pull request by gfgtdf**
and use it to implement SCATTER_IMAGE, SCATTER_EMBELLISHMENTS and
SCATTER_UNITS

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I think this is a very good idea, but I have one significant problem with it and a few additional comments.

The problem is that the variable remains in scope after the tag finishes, requiring you to explicitly clear it afterwards. You should instead use the variable scoping functions that the looping tags use to ensure that the variable is reset to whatever value it had before calling the tag. Then you don't need to clear it.

I'm a little unsure on the name "random_placement"; it feels like it might be slightly misleading, since you could probably do something in the `[command]` block that doesn't involve placing objects on the map.

It might be a nice touch to pass `num_items` through `wesnoth.random` (perhaps only if it contains a hyphen or a comma). Then you could do things like `num_items=12-20`. Of course, this is possible anyway by setting a variable first, but like I said, it might be a nice touch to integrate it here.

**Comment by gfgtdf** [comment]
> The problem is that the variable remains in scope after the tag finishes, requiring you to explicitly clear it afterwards. You should instead use the variable scoping functions that the looping tags use to ensure that the variable is reset to whatever value it had before calling the tag. Then you don't need to clear it.

Yes, most usecases show that the variable is not used afterwards so it might make sense to have this tag not to change this variable permanently.

> I'm a little unsure on the name "random_placement"; it feels like it might be slightly misleading, since you could probably do something in the `[command]` block that doesn't involve placing objects on the map.

If you suggest a better name we can discuss it, but since these things things can also be fixed afterwards i dont think this is a reson against merging.

> It might be a nice touch to pass `num_items` through `wesnoth.random` (perhaps only if it contains a hyphen or a comma). Then you could do things like `num_items=12-20`. Of course, this is possible anyway by setting a variable first, but like I said, it might be a nice touch to integrate it here.

afaik formula also supports some kind of random so it could be possible to use num_items="$(some formula random)"

num_items support eigher an integer, or a string that evaluates as a lua expression (this syntax is mainly inteded for cases when the num_items should depend on the locations found). So that you can still use num_items="wesnoth.random(12,20)" otherwise. I tried to change my implementation so that is covers most usecases in mainline best. (for example my first version also had a 'percentage=' key to choose a fixed % of the found locations but i thought this was too specific so i removed it).

**Comment by CelticMinstrel** [comment]
I saw it before you removed the `percentage` key. I didn't think it seemed overly specific.

I don't think it's good to allow an arbitrary Lua expression in `num_items`.

**Comment by gfgtdf** [comment]
> I don't think it's good to allow an arbitrary Lua expression in `num_items`.

It sure is, its definiteley better than providing numerous keys for percentage, minimum, random_range... and still not covering most usecases.

I implemented the variable scope thing so i'll merge this, if you want to suggest a different name, we can discuss that on irc.

**Pull request merged**
