### PR TITLE
Spelling fixes in German translation of the tutorial

### PR DESCRIPTION
**Pull request by Ordoviz**
Feel free to ask me about the changes I made.

Some other small issues (not fixed with this PR):
- Space before ’%’: https://de.wikipedia.org/wiki/Prozent#Schreibweise
- Spelling of numbers is inconsistent and doesn’t seem to follow any logic

### CODE REVIEW

**Comment by nemaara** [comment]
Please submit these changes to the German translation coordinator instead. See https://wiki.wesnoth.org/GermanTranslation and https://wiki.wesnoth.org/WesnothTranslationsHowTo#How_to_submit_your_translations.

**Comment by sevu** [comment]
Thank you. Quite a lot of mistakes ...

**Comment by Ordoviz** [comment]
@sevu I already sent my changes to Bitron on the forum with [this](https://forums.wesnoth.org/viewtopic.php?f=7&t=49566&sid=eae84933bb68406ff4cc4e82d30525df) thread. Let’s hope that it doesn’t create confusion.

**Comment by sevu** [comment]
I had a talk with Bitron, all fine.

**Pull request merged**
