### PR TITLE
1.17 (test scenario) out-of-hex unit animation tests

### PR DESCRIPTION
**Pull request by doofus-01**
This is for testing #6589, as well as looking at how ellipse and HP bar move with sprite in progressive y= key

### CODE REVIEW

**Comment by mesilliac** [comment]
I thought i couldn't get it to reproduce even with this, but now i do see some artifacts when zooming in as much as possible.

I found regular unit movement from hex-to-hex has this problem as well, just it's not normally noticable as all surrounding hexes are cleared when the unit arrives at the next hex.

I haven't found the fix yet but will keep poking at it. I guess it doesn't happen when zoomed out because the default size ends up clearing more than necessary, not less.

**Comment by mesilliac** [comment]
I think i found the culprit. There was some code that wasn't accounting for zoom. I'll tidy it up and see about pushing a fix tomorrow.

**Comment by mesilliac** [comment]
I committed a fix to master which fixes all the drawing problems for me at all zoom levels.

This test case should probably be merged too, but for a couple issues:
* i'm not sure what the CI failure here is about
* the map label overlaps the one to the left, it should maybe be placed on a different hex?
* the changed text colour is nice but nothing else does that so it looks a bit weird :sweat_smile:

Well those last two issues aren't all that critical.

**Comment by CelticMinstrel** [comment]
The test failure is just that unit names need to be translatable to pass schema validation.

**Comment by doofus-01** [comment]
Thanks for fixing the issue.  The different color text was a lazy fix for the overlapping.  There should probably also be some way to turn that animation off, without just ending the test.

I didn't know what the CI failures were about either, `No value for $TERM and no -T specified` is not for mere mortals to understand.

**Comment by doofus-01** [comment]
I believe this is done now, but I noticed something that's (I think) unrelated.

This elf has what I think is the handle of a sword from the wesnoth icon blinking as the NW neighbor hex gets redrawn.  This must be some deliberate test, I guess it's failing?
```
        [unit]
            x,y=4,8
            type="Elvish Avenger"
            id=statue
            generate_name=yes
            hitpoints=4
            vision=15
            ellipse=none
            [status]
                petrified=yes
            [/status]
            overlays="wesnoth-icon.png~CROP(10,10,20,20)"
        [/unit]
```

**Comment by mesilliac** [comment]
I think that might be to test the out-of-hex part of the overlay. It has the same symptoms as #6118 when you mouse over it.

All of the code related to "overlays" seems rather buggy. I can only assume sometime in the past it was all broken by a rewrite, because as the code is now, things like this could never have worked.

**Review by mesilliac — APPROVED** [review]

**Comment by mesilliac** [comment]
I would merge this but i'm not sure whether to squash/rebase/merge, feel free to click the button :)

**Comment by CelticMinstrel** [comment]
> I didn't know what the CI failures were about either, `No value for $TERM and no -T specified` is not for mere mortals to understand.

Just for the record, that was not the error message that allowed me to determine the issue. You can just ignore that message; the real error was further down in the log.

**Pull request merged**
