### PR TITLE
help(editor): fix duplication of text attribute

### PR DESCRIPTION
**Pull request by fujimo-t**
There are duplication of text attribute, so some sentence is not displayed.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
This is a great example of why you shouldn't merge PRs the moment they're opened.

**Comment by Vultraz** [comment]
Really doesn't matter either way. The entire editor help section needs a rewrite.

**Comment by CelticMinstrel** [comment]
I mildly disagree. Sure it may need a rewrite, but that's no excuse for inserting nonsensical lines into it.

**Comment by fujimo-t** [comment]
I should more consider the pull request is really needed before I send it .

**Pull request merged**
