### PR TITLE
UtBS S04 - enhance goblin leader trigger "how can he move that fast?"

### LINKED ISSUE #6266: UTBS S4 Descending Into Darkness: Improve trigger of "how can he move fast" dialog
### Game and System Information
 - Scenario was played in 1.15.18
 - Steam
 - Windows 10

### Describe the desired feature
Currently, when any of the player's units proceed to attack the enemy Direwolf Rider Leader, Kaleh says
https://github.com/wesnoth/wesnoth/blob/ee233cead6e2335ea71d5bf6b03bc6de024a2bd7/data/campaigns/Under_the_Burning_Suns/scenarios/04_Descending_into_Darkness.cfg#L605

The current timing looks like a delayed reaction. He has already seen the Rider move fast but is only commenting on it late. I think it would be an improvement if the dialog also triggers the first time the Direwolf Rider moves to attack one of the player's units.
It is explained later lorewise that the Rider was unnaturally fast because he had a ring that gave him an additional 1MP.

### Screenshots
The timing of the dialog is... unnatural
image

### Replay
[UtBS-Descending into Darkness replay 20211005-023011.gz](https://github.com/wesnoth/wesnoth/files/7490889/UtBS-Descending.into.Darkness.replay.20211005-023011.gz)

### PR DESCRIPTION
**Pull request by Descacharrado**
Now the event triggers when the player gets sight on Panok (the goblin leader) moving.

Closes #6266

### CODE REVIEW

**Review by knyghtmare — COMMENTED** [review]
Not sure how just "Seeing" the goblin leader on his keep would be some indication of his speed.

**Comment by Descacharrado** [comment]
> Not sure how just "Seeing" the goblin leader on his keep would be some indication of his speed.

It would not trigger then, only when:

> the player gets sight on Panok moving.

**Comment by knyghtmare** [comment]
> > Not sure how just "Seeing" the goblin leader on his keep would be some indication of his speed.
> 
> It would not trigger then, only when:
> 
> > the player gets sight on Panok moving.

Ah, I see it now. The diff made it hard to read.

**Comment by Descacharrado** [comment]
> > > Not sure how just "Seeing" the goblin leader on his keep would be some indication of his speed.
> > 
> > 
> > It would not trigger then, only when:
> > > the player gets sight on Panok moving.
> 
> Ah, I see it now. The diff made it hard to read.

Oh. oops it may have been the comment, which is a little missleading, will fix.

**Review by nemaara — APPROVED** [review]

**Pull request merged**
