### PR TITLE
Show current acceleration speed when activating

### PR DESCRIPTION
**Pull request by Wedge009**
Quick attempt to give some sort of feedback for #1311. I'm sure there are better ways to handle this, though, plus I recognise there's no translation handling (I was trying to avoid breaking existing strings). If it is acceptable, however, it can also go in master.

### CODE REVIEW

**Comment by gfgtdf** [comment]
hmm i wonder whether the x should be transltable  or not.

**Comment by CelticMinstrel** [comment]
Probably not, math notation is fairly universal (and note that it probably should be the multiplication operator rather than the letter x). If someone complains though, we can always go back and make it translatable then.

**Comment by Wedge009** [comment]
That's what I was wondering. But with the prevalence of electronic devices (play-back speed, for example), 2x, 4x, etc seems pretty universal across even languages where Latin characters aren't used.

**Comment by CelticMinstrel** [comment]
Oh, also, I wonder whether the x should precede the number or follow it?

**Comment by Wedge009** [comment]
Another good point. I've seen it written both ways. I think it's 4x in the case of optical drive speeds. Yet for PCIe lanes it's often written x16. Although the latter is a multiplier of quantity while the former is a multiplier of speed.

**Comment by stevecotton** [comment]
This seems to be similar but slightly nicer, and would allow language-specific ordering of the number and the multiplication sign:
https://github.com/wesnoth/wesnoth/blob/09b799e9f1566b41a73e6c6436ecc344e4b38abd/src/gui/dialogs/statistics_dialog.cpp#L259

The preferences dialog gives us translatable string "Acceleration factor:", sadly that is in textdomain wesnoth-lib.

**Comment by Wedge009** [comment]
I'll close this since it's only a work-around for #1311 specifically while #1188 covers the full feature.

**Pull request closed without merging**
