### PR TITLE
add items from Blarumyrran and run woptipng on the directory

### PR DESCRIPTION
**Pull request by doofus-01**

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Running woptipng in the same commit makes it impossible to tell what's actually new here… maybe it would be better to run woptipng on master, commit that, then add the new icons?

**Comment by doofus-01** [comment]
You can look at the rich diff.

**Comment by CelticMinstrel** [comment]
That really doesn't help. I mean, sure, you can notice the ones that are brand-new and those that have a very obvious change, but clicking "rich diff" on every image is a huge pain and you'll never know whether one of those that _doesn't_ show an obvious difference is an update or a woptipng alteration.

**Comment by soliton-** [comment]
Certainly anyone trying to figure out attribution from this might as well give up. 2 commits would be much better.

**Pull request merged**
