### PR TITLE
Use same default id in [remove_unit_overlay] as [unit_overlay]

### LINKED ISSUE #7896: [remove_unit_overlay] issue
https://github.com/wesnoth/wesnoth/commit/b2cd1cf made [remove_unit_overlay] use an object_id key and unlike [unit_overlay] does not fall back to "overlay_" + image. At least the UNMAKE_HERO macro uses  [remove_unit_overlay] without object_id.

I've added minimal documentation of object_id to the wiki but this does not look like it all fits together...

It seems [unit_overlay] and [remove_unit_overlay] are kinda deprecated?

### PR DESCRIPTION
**Pull request by soliton-**
Closes #7896.

### CODE REVIEW

**Comment by stevecotton** [comment]
Repeating my question from #7896, why would code use this? What code will want to undo the removal of an overlay, yet not know enough about that overlay to just put a new one on the unit?

**Comment by soliton-** [comment]
I'm not really interested in further discussion myself. I tried to figure out a rationale for the current state in the linked issue. Nothing came of that. If there is a rationale feel free to document it and close this as well as the issue.

**Comment by CelticMinstrel** [comment]
I think this makes sense. If you didn't specify an ID when you added the overlay, then not specifying an ID when removing it will succeed.

**Comment by stevecotton** [comment]
> If you didn't specify an ID when you added the overlay, then not specifying an ID when removing it will succeed.

That seems true with or without this PR.

**Pull request merged**
