### PR TITLE
Display ID of addon in addon manager

### PR DESCRIPTION
**Pull request by binarydigitz01**
As discussed in  #6255.

### CODE REVIEW

**Comment by Pentarctagon** [comment]
Please add a screenshot.

**Comment by binarydigitz01** [comment]
image

**Comment by Vultraz** [comment]
I would suggest making it small and gray under the title in the details section

**Comment by CelticMinstrel** [comment]
I think that might be making it a bit _too_ prominent? It's not something that the average player needs to know. I mostly like where it is in the screenshot, but would probably prefer placing it further down, after "Translations".

**Comment by binarydigitz01** [comment]
I agree with @CelticMinstrel, I'll place it below translations.

**Comment by binarydigitz01** [comment]
Can I get a confirmation on the placement?

**Comment by binarydigitz01** [comment]
image
 This is an image with id under translation

**Comment by stevecotton** [comment]
Don't worry about the build failure, it's a known intermittent bug with vcpkg/glib.

**Pull request merged**
