### PR TITLE
Balancing Update to Dwarvish Miner

### PR DESCRIPTION
**Pull request by Gothyoba**
Intended to compensate for high gold.

HP 22 -> 24
Attack 4x3 -> 5x3

### CODE REVIEW

**Comment by Hejnewar** [comment]
Imo that's over buff. I could see 25 HP and 5-3 for 12 gold tho.

**Comment by Mirion147** [comment]
> Imo that's over buff. I could see 25 HP and 5-3 for 12 gold tho. 

Can I ask if you consider the mermen citizen to be balanced? 

Miner has +10% resists (but -10% cold)
-2mp, +2hp +2xp and pierce damage vs impact

Citizen 9g, Miner 11g

What I would suggest is:
4x3 melee, 24hp, 20xp maintaining 11g

**Comment by Dalas121** [comment]
> 4x3 melee, 24hp, 20xp maintaining 11g
Fine by me. @Hejnewar, do these numbers work for you?

**Comment by Roge-Tebnelok** [comment]
Even though miners are professionals, it doesn't make sense for them to swing the pickaxe light but often. As it was said on Discord, miner can have 7x2 because of possible advancement into Guardsman who right now has less base damage than goblin spearman, and it's just weird that non weak goblin can deal more damage with it's weak hands and crude spear than non strong but still more physically stronger dwarf with spear made of fine dwarvish metal by famous dwarvish blacksmiths, and Impaler makes guardsman even worse as a damaging unit, leaving him only with better ranged attack, health and resistances, to meat shield role. Other units with spears are even better than Guardsman, who is also the most expensive and therefore less if not least often used level 1 unit with spear. Because of how short it is, he has easier time wielding it, and adding his natural dwarvish strength to it, even if it's massive as description says, and compared to other units, it's only natural for Dwarvish Guardsman to deal at least 6x3 melee damage if not 7x3, which would make him more worthy his price and race, and also allow Miner to deal 7x2 instead of 4x3, so when he advances to level 1 he gets substantial upgrade.

**Comment by Hejnewar** [comment]
> Can I ask if you consider the mermen citizen to be balanced?

Actually no. I dont. It should also be 11g.

> What I would suggest is:
4x3 melee, 24hp, 20xp maintaining 11g

I would go with 25hp and thats fine.

**Comment by Dalas121** [comment]
>>     4x3 melee, 24hp, 20xp maintaining 11g
> I would go with 25hp and thats fine.

Done. Will merge once checks finish.

> Actually no. I dont. It should also be 11g.

I'm fine with changing the merman citizen (though I'd prefer a nerf rather than a cost increase), but whenever you/we/whoever actually makes a change we'll need to make sure Dead Water's first scenario isn't an issue.

**Comment by Hejnewar** [comment]
Sure I was just answering Mirion cuz he asked.

**Pull request merged**
