### PR TITLE
Change Giant Scorpion/Scorpling resists

### PR DESCRIPTION
**Pull request by nemaara**
For #1299. Also adding a recolored scorpion sprite with the original resists as discussed on the issue (I'll add the frames and corresponding unit later if people think the coloring is fine).

### CODE REVIEW

**Comment by nemaara** [comment]
Added the unit file and animation frames for the scuttler. Leaving this open for a few days in case anyone has comments.

**Comment by CelticMinstrel** [comment]
I'd probably merge the sand scuttler stuff into a single commit, but other than that this seems fine.

**Comment by sevu** [comment]
How about making the Sand Scuttler a [variation] ?

(btw, what's the story behind the Sand Scuttler?)

**Comment by CelticMinstrel** [comment]
The commit message for the sand scuttler commit is no longer accurate.

**Comment by nemaara** [comment]
> How about making the Sand Scuttler a [variation] ?

I thought about this, but I thiiiink that it'll be easier for UMC creators to just use a separate unit, especially since it specifically has different resists than the base scorpion (not just a recolored scorpion). The whole point of the scuttler is to allow UMC creators (and us) to have a unit that has the exact same stats as the original Giant Scorpion while giving an in world reason why they might exist.

**Comment by sevu** [comment]
I think it wouldn't be too hard to for UMC authors … let's have a look:
* you can't use some unit placement  macros strightahead, because you need to set the variation. It's the same like if you want to place a female mage, there you have to set random_gender=yes, just that with the variation it is obvious that one must set it.
* couldn't use the scatter unit macro for placing them

For making it a variation, it would …
* add more variation to wesnoth (pun intended), because you can see in the help that this unit has a variation. Currently we have a few hundred types, but only the zombie line uses variations, and Konrad + Lisar.

For your last remark, I think we don't _have to_ provide a unit with the same values like the old one, but it is certainly a nice addition.
Can be a leader scorpion, or a hidden gem. (Actually, if it's a variation without hide_help=yes, it should appear somewhere in mainline, because people will be curious… which is a good thing)

**Comment by nemaara** [comment]
Sure, I made it a variation now. Committing soon unless more comments pop up.

**Comment by CelticMinstrel** [comment]
> It's the same like if you want to place a female mage, there you have to set random_gender=yes,

Uh no, if you want a female mage you need to set gender=female.

**Comment by Konrad22** [comment]
Can we get a Scorpling variation/recolored Scorpling sprite as well? :)

**Comment by jostephd** [comment]
@Konrad22 If you ask here it may get lost; better open a new issue or ask on the art forums.

**Comment by sevu** [comment]
@spixi good point. Multiplayer will use the variation then.

**Pull request merged**
