### PR TITLE
Rename the Khalid's shield bash to pommel strike.

### PR DESCRIPTION
**Pull request by Pentarctagon**
The sprite has two swords, not a shield.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Hmm, interesting idea, though I don't think a pommel strike would do much damage...

**Comment by GregoryLundberg** [comment]
The pommel is the cap at the end of the hilt of  European-style sword.

In this case I think he means 'Pommeling strike"

**Comment by CelticMinstrel** [comment]
Not sure why you'd add an -ing here...

**Comment by Pentarctagon** [comment]
@CelticMinstrel The Khalid is a lvl 4, offensive unit, so the damage doesn't really seem out of place to me.  Otherwise, the unit doesn't have anything to deal impact damage, short of maybe just throwing punches.

**Comment by GregoryLundberg** [comment]
You're right I should have checked a couple other dictionaries. "Pommeling" is repeated strikes with the first or hilt of a sword as in "He took a pommeling in that fight."

I did some more research and don't find any specific terms. In fact, most times, two swords where considered foolish, but not completely unheard of. Using a smaller weapon such as a dagger or hand-axe in the off hand can be found throughout the ages.

Yes, pommel is wrong, and I could not find any specific names other than the SCA calls it "Florentine style" but there is no historical basis for that, and a few Japanese masters taught it with two katana, but the terms there were the master's names.

So, pick a flowery name. "Buzzsaw" (bad choice) or "Sword dance" (better) but which isn't already used.

**Comment by Pentarctagon** [comment]
The closest example of how I was seeing it be done is [here](http://www.worksofrichardmarsden.com/fiorelongsword.htm), under "Strong Bind Play"(the images are also youtube links), except with a scimitar rather than a longsword.

I don't know what you mean by "document" though, given that this is a two word attack description.

**Pull request merged**
