### PR TITLE
unit_recall: Show unrecallable units grayed out.

### PR DESCRIPTION
**Pull request by jostephd**
Part of issue #1282.

Looks like this:

2019-09-18-154113_1024x768_scrot

- [x] add a tooltip with the reason the unit is grayed out

<details>

<summary>
test case
</summary>

```
diff --git a/data/campaigns/An_Orcish_Incursion/scenarios/01_Defend_the_Forest.cfg b/data/campaigns/An_Orcish_Incursion/scenarios/01_Defend_the_Forest.cfg
index 53ea5f5be8e..596689ec975 100644
--- a/data/campaigns/An_Orcish_Incursion/scenarios/01_Defend_the_Forest.cfg
+++ b/data/campaigns/An_Orcish_Incursion/scenarios/01_Defend_the_Forest.cfg
@@ -50,7 +50,7 @@
     [side]
         side=1
         controller=human
-        {GOLD 200 150 100}
+        gold=20
         income=0
         team_name=Elves
         user_team_name= _ "Elves"
@@ -61,6 +61,10 @@
 
         facing=nw
 
+        {UNIT 1 Mage recall recall ()}
+        {UNIT 1 Mage recall recall (recall_cost=25)}
+        {UNIT 1 Peasant recall recall ()}
+
         [unit]
             side=1
             type=Elvish Rider
```

</details>

### CODE REVIEW

**Comment by soliton-** [comment]
Perhaps label should still be set in the cfg file and C++ would just conditionally append `~GS`?

**Comment by jostephd** [comment]
@soliton- I wanted to do that, actually, but couldn't figure out how. Would that be `listbox.get_row_grid(listbox.get_item_count() - 1).find("gold_icon", false)`?

**Comment by soliton-** [comment]
Sorry don't know much about GUI2. I just assumed you have access to the cfg file via a config object somewhere.

**Comment by gfgtdf** [comment]
From.looking at the code this only checks for costs and.nit for [filter_recall] of the leader?

**Comment by gfgtdf** [comment]
I wonder whether it should also check for free tiles.

**Comment by jostephd** [comment]
> From.looking at the code this only checks for costs and.nit for [filter_recall] of the leader?

Units that don't match the [filter_recall] do not appear in the dialog in the first place. (The list of units passed to `unit_recall`'s constructor doesn't include them.)

> I wonder whether it should also check for free tiles.

Maybe... :thinking:  but I don't consider this a blocker.

**Comment by jostephd** [comment]
@soliton- That worked, so pushed.

**Comment by jostephd** [comment]
Recruit dialog updated too:

2019-09-18-190446_509x346_scrot

**Comment by gfgtdf** [comment]
Wasn't the gold already shown in red before? I currently tend to say I like the previous way better because it makes clearer why exactly you cannot recruit the unit.

**Comment by jostephd** [comment]
> Wasn't the gold already shown in red before?

Old behavior: the gold is shown in red if the unit has a recall_cost higher than the team's recall_cost, regardless of how much gold the team has in the bank.

New behavior: if the unit's recall cost is higher than the team's gold, the line is gray. Otherwise, same as old behavior.

**Pull request merged**
