### PR TITLE
fix level up emove overlay from unit

### PR DESCRIPTION
**Pull request by newfrenchy83**
this fix https://github.com/wesnoth/wesnoth/issues/4058 in hope to not generate another bug

### CODE REVIEW

**Comment by gfgtdf** [comment]
as I mentioned in #4058 this code is there for a reason (in particular to make remove obejct for the overlay effect work). To fix #4058 it'd be better to change the wml istead to use object-based overlay modifications.

**Comment by gfgtdf** [comment]
actually we should consider putting that overlay effect directly into the loyal trait definition.

**Comment by newfrenchy83** [comment]
I understand what i must create a hero trait for put héro icon overlay instead of loyal for the heroes. And i understand what you wamt use add in effect applied to overlay for replace an overlay by amprher, why don't use replace instead to alter the vode and generate a bug more frquent what that wjat you would resolve ?

**Comment by jostephd** [comment]
@gfgtdf With your solution, any add-on that gives units overlays would have to change between 1.14 and 1.15. (At least Unitmarkers, but I believe there are others too.) Is there another option that preserves compatibility better so add-ons and the loyal definition won't all have to change?

**Comment by newfrenchy83** [comment]
I understand that you want to solve the overlay problem that accumulates after each advance in https://github.com/wesnoth/wesnoth/commit/1a7724e547201d0ff1fda048b6079559d6da560c#diff-8dd74f653e8c20d19565e37121f74e9f
 but By putting overlays_.clear () in the code you generated a more common bug than the one you partially solved in the lua code.
My solution is not perfect, but it does not oblige developers to rewrite code for heroes

**Comment by gfgtdf** [comment]
> Is there another option that preserves compatibility better so add-ons and the loyal definition won't all have to change?

Hmm not sure, I mean we could clearly make those changes easier by providing both a overlay and a  no-overlay adding version of the loyal trait, or adding an optional parameter to the loyal trait.

Another option that would probably give us the most backward compatability would be to change the existing {is_loyal} macro to add an effect, that'd have the disadvantage that removing the loyal trait would then not auomatociall remove the loyal overlay.

> By putting overlays_.clear () in the code you generated a more common bug

yes i knew that when I did that change but unlike the remove_object bug this one can be easily fixed by umc devs by adapting their code. Second it was not only remove_object that was broken but the overlay [effect] in general as it kept adding the same overlay multiple times to the unit on advance. So I'm the end I had to decide whether I either want to 1) keep broken features (apply_to=overlay), 2) deprecate the apply_to=overlay [effect] or whether I would 3) make the overlay behave like most other unit stats even if it's some sort of compatability break.  And I went for (3), and in particular since I think that for the most common (loyal) overlay we can adapt the mainline macros without giving umc authors too much work in total I still say this is the best option.

**Comment by jostephd** [comment]
@gfgtdf Thanks for explaining. I'm not too concerned about the loyal macros, we can change them as we please. I'm more concerned about UMC WML code breaking when they upgrade wesnoth.

Frankly, I'm not sure I follow all the details here. I keep trying to think if there isn't some fourth option that would solve both the original problems and the new problems. But if there's a workaround UMC authors can deploy in their mods, I guess we should just document the compatibility issue in changelog and/or the wiki, so they find it when they port their addons to 1.16. Is there a wiki page about porting addons between wesnoth versions? Or do we just add a note on https://wiki.wesnoth.org/SingleUnitWML?

**Comment by newfrenchy83** [comment]
the fourth option is here https://github.com/wesnoth/wesnoth/pull/4073, it is create a single overlay persistent for the crown and use the classic overlay multiple for other case,(or convert classic overlay in overlay with one image possible but persistent and assign old code to "multiple_overlays")

**Pull request closed without merging**
