### PR TITLE
HttT: Fix OOS when redoing a recall and Li'sar is allied

### PR DESCRIPTION
**Pull request by jostephd**
For #2216.

### CODE REVIEW

**Comment by GregoryLundberg** [comment]
Tested and appears to work in that the crash no longer occurs.

Can you rebase against the current master, and push over your feature branch? I can do it but it's easier to just click the button here.

**Comment by GregoryLundberg** [comment]
Rebased and merged by hand.

**Comment by jostephd** [comment]
@GregoryLundberg Thanks for rebasing and merging.  Will keep that in mind for next time.

**Comment by GregoryLundberg** [comment]
BTW. Tested subsequent scenario with Li'sar nearby and this PR in and cannot cause similar crashes on undo/redo cycles. Checked before and after both have the initiative special.

**Pull request closed without merging**
