### PR TITLE
Use core strings in campaigns

### PR DESCRIPTION
**Pull request by sevu**
.
This is the continuation of PR #902 
The code style is not everywhere the same, I switched mostly back to the original textdomain after the relevant strings, though this is not necessary. If there Is some preferred variant, I'm happy to make it the same everywhere.
 
Before merging this PR, there are a few edge cases: 
1) There exists "morningstar" and "morning star" - what is the better variant?
2) In some languages "entangle" in wesnoth-units (the entangle of the elves) and "entangle" in wensoth-dm (the entangle of the wose shaman) is translated differently. I can kind of understand it. Should we maybe use different words in english for it? Otherwise I would unify it too.

Talking about that... there were two similar string changes which I would wish for:
3) Khalifate units have "shield bash" - the south guard has a unit with "shield" as attack.
Switching to "shield bash"?
4) There exists "long sword" and "longsword", has been discussed at [gna #25013]. And, if changed, "short sword" would then be "shortsword". (used by orcish/loyalist bowman and the mages in liberty/main character in DiD)

One last idea regarding that topic:
Some attacks are used by different campaigns, but not in core. E.g. "trample", is used by the new utbs, eastern invasion and liberty. Can I move it to the wesnoth-units domain too?

[gna #25013]: <https://gna.org/bugs/index.php?25013>

### CODE REVIEW

**Comment by ln-zookeeper** [comment]
1. If both are legitimate forms then I guess I'd prefer "morningstar", but I'm not sure if they are. Arguably, they should be changed to "flail", though, since that's what the weapons actually are.

2. I'd think entangle can be shared. It is, after all, seemingly the same "spell" that's being used.

3. Yes, it can be "shield bash" in TSG too.

4. I'd agree that it should be "longsword" rather than "long sword", but it doesn't really make sense to use either of those for the Arif/Ghazi/Khalid/Shuja swords. I'd suggest that only Monawish/Mighwar get "longsword", everyone else gets "sword" (or maybe "scimitar"). However, I think "short sword" is correct as-is and should definitely not be "shortsword".

**Comment by CelticMinstrel** [comment]
As Zookeeper says, "longsword" and "short sword" are the correct forms. Yes, it's inconsistent, but that's how it is. The elvish and wose "entangle" are the same sort of attack, so I'd think they should be translated the same.

I think "morning star" is more correct than "morningstar", but note that this refers to a spiked mace. If the weapon is in fact a spiked ball on a chain, it should be changed to "flail".

Not sure on the question of moving "trample" to the core textdomain.

**Comment by sevu** [comment]
So, finally finished.

"morning star" and "morningstar" seems to be both as common as mixing it up with flails. I left it like it was, if some else has an opinion on it ...
The images and names besides that are correct now though.
Maybe we could add a wmllint rule to rename morning-star.png to flail.png.

**Comment by ln-zookeeper** [comment]
Looks good to me. I had a hard time making up my mind regarding Outlaw/Fugitive and Bandit/Highwayman, but I think it's okay to call their weapons morning stars.

**Comment by sevu** [comment]
Was thinking much about that too, but I think it's better like that.

**Pull request merged**
