### PR TITLE
Test and potentially merge Sdl2 branch with Master

### PR DESCRIPTION
**Pull request by aginor**
I would like help with testing this and see if more people can break it. If we can get some sort of consensus that this is stable/good enough I think it would be good to have it merged into master.

If you test it and have a crash, please raise a bug in the tracker and attach a stack trace. I'd also like to know which version of SDL2 you are using if you see any issues, and which operating system/distribution and video-card. We have had both AMD and Nvidia specific issues so it matters :)

Currently open bugs for SDL2:
https://gna.org/bugs/?23934 - Since resize items are funky even on master with SDL1 I don't see a reason treat this as a blocker.
https://gna.org/bugs/index.php?23857 - Trivial enhancement, I do not think this should be a blocker.

Bugs that should not be fixed:
https://gna.org/bugs/?23909

### CODE REVIEW

**Comment by gfgtdf** [comment]
There qre still bugs related to resizing:
1) The game sometimes crashes when resizing in titltescreen as i repoorted in irc.
2) when the game is maximized then minimized and then unminimized the game becomed a black window
3) When the game is resized during the game, some tiles become black

**Comment by aginor** [comment]
Hi @gfgtdf, thanks for providing feedback.

1. As I told you on IRC, I nor anyone else has been able to reproduce your crash. Can you please provide more details? It would be good if you could raise a bug report.
Could it please include:
   * Operating System (including version, not just windows)
   * Build method
   * Version of SDL2 libraries
   * Steps to reproduce
   * A stack trace if possible
   * Looking at the "pixels" value of the source and destination of the sdl_surface if it's a crash within a SDL_Blit function. This is easiest done through a debugger. It's not something that's feasible to add to the game log unless you want gigabytes of data.
2.  This is a new bug. I'll raise an issue for it.
3. This is a new bug. Would you mind raising a bug for it? It would be good if it could contain the following:
   * Operating System (including version, not just windows)
   * Build method
   * Version of SDL2 libraries
   * Steps to reproduce
   * A screenshot of the problem

**Comment by gfgtdf** [comment]
>    * Operating System (including version, not just windows)

windows 7 64 bit
>   * Build method

msvc 2010 32 bit release build. At commit https://github.com/wesnoth/wesnoth/commit/55f7b28720f2749d543fabfbdd3037faa1f86c80
>   * Version of SDL2 libraries

Here a screenshot of wesnoths version info window: http://i.imgur.com/w82Qf5H.png
>    * Steps to reproduce

I'm just resizing the window by draging the bottom-right corner of the window, if i do this long enough the game crashes as soon as a i drop it.
>   * A stack trace if possible

I already gave you a stracktrace on irc.
>   * Looking at the "pixels" value of the source and destination of the sdl_surface if it's a crash within a SDL_Blit function. This is easiest done through a debugger. It's not something that's feasible to add to the game log unless you want gigabytes of data.

I tried but i couldn't figure out how to to this.

>    * Operating System (including version, not just windows)
>   * Build method
>   * Version of SDL2 libraries

Same as before
>   * Steps to reproduce

Rezising the window during a game 
>   * A screenshot of the problem

http://i.imgur.com/OUM23fe.png (screenshot taken from AoI scanrio1 aftert some mpouse moving after rezising (without mouse moving it's just all black))
Last time I tried rezising the window during the game (still sdl2 branch) it looked different so that only some tiles became black.

**Comment by aginor** [comment]
Thanks @gfgtdf. Could you please also tell me which SDL2 libraries you used, and how they were compiled if you did it yourself.

**Comment by gfgtdf** [comment]
I am not completeley sure but i think i downloaded from here: https://www.libsdl.org/release/SDL2-devel-2.0.3-VC.zip

I didn't even know it was possible to compile SDL2 myself with msvc2010.

**Comment by shikadilord** [comment]
> 1) The game sometimes crashes when resizing in titltescreen as i repoorted in irc.

As I mentioned on IRC yesterday, I tried to reproduce this on Windows 8.1 (running on a VirtualBox VM without 3D accel enabled) and didn't get any crashes. I just tried rapidly maximizing and restoring the game window while on the title screen about three dozen times and still didn't crash.

Until another Windows user can confirm that this is an actual issue that should block **merging** the branch (after 1.13.2, that is, see my email to the devs ML yesterday), I'd prefer it if @gfgtdf's crash bug was considered only a **release** blocker so that we can get this merged into master and increase our test coverage that way.

Anyway, I wouldn't rule out it being linked to his hardware configuration in some way. @gfgtdf, perhaps you could mention your GPU (even if it's integrated graphics) and driver version as well?

**Comment by aidanhs** [comment]
I was going to raise this on gna, but my setup is pretty bizarre and I don't really know if you want to spend time trying to fix this edge case - my host machine is Ubuntu 12.04, but Wesnoth is running in a Ubuntu 14.04 Docker container with audio and video forwarded to the host.
I'm therefore just noting the issue here in case other people intermittently see it and you potentially want to talk to someone who can reliably reproduce.

----

When using this branch I'm able to reliably reproduce a near-identical error to https://gna.org/bugs/?2970 after starting up Wesnoth for the first time within a container - the steps to repro the crash only work once in a particular container.

The issue happens like this:
```
/work $ ./wesnoth/wesnoth-debug 
Battle for Wesnoth v1.13.1+dev (f709b8e-Clean)
Started on Thu Dec  3 01:31:53 2015

Automatically found a possible data directory at /work/wesnoth
process 357: D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open "/etc/machine-id": No such file or directory
See the manual page for dbus-uuidgen to correct this issue.
libGL error: failed to open drm device: Permission denied
libGL error: failed to load driver: i965

Data directory:               /work/wesnoth
User configuration directory: /myhome/.config/wesnoth
User data directory:          /myhome/.local/share/wesnoth/1.13
Cache directory:              /myhome/.cache/wesnoth

Checking video mode: 1024x768x24...
Setting mode to 1024x768x24
Checking lua scripts... ok
[...PRESS MAXIMIZE...]
[...PRESS WINDOWED...]
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  130 (MIT-SHM)
  Minor opcode of failed request:  3 (X_ShmPutImage)
  Value in failed request:  0x400
  Serial number of failed request:  3377
  Current serial number in output stream:  3378
```
And it dies. No backtrace is available when using GDB. Note that the libGL and dbus complaints are also new as of SDL2.

**Comment by aginor** [comment]
Hi @aidanhs,
Thanks for the feedback. You never state it, but can I assume that the actual steps to reproduce the crash is to resize the game? I will raise a proper bug for it in GNA and reference it, but I am not sure whether it should be treated as a merge blocker.

**Comment by aidanhs** [comment]
Sorry, I should've emphasised these lines:
```
[...PRESS MAXIMIZE...]
[...PRESS WINDOWED...]
```

**Comment by aginor** [comment]
@aidanhs I've raised https://gna.org/bugs/index.php?24137, could you please review and see if there is anything missing?

**Comment by aidanhs** [comment]
@aginor looks good, thanks.

**Comment by aginor** [comment]
@aquileia and @gfgtdf, Could you please help and test again? I'm not able to reproduce any more after commit 5c187a518566b09d70fd6bfa40eb2cac9554fa48 (but I may have made bug https://gna.org/bugs/?23934 slightly worse).

**Comment by aquileia** [comment]
@aginor Neither am I, it seems you fixed it for good!

**Pull request merged**
