### PR TITLE
Eastern Invasion and Liberty Bone Knight attack image

### PR DESCRIPTION
**Pull request by Descacharrado**
From #4145:

> [ ] Bone Knight has no attack icon for the "trample" attack

Bone Knight's image was added to core.

In-game it looks like this:

Bone knight trample image in-game

EDIT: removed kick-orcish.png in f79848e5 because this commit inspired doofus to work on better icons on #6339

### CODE REVIEW

**Comment by Wedge009** [comment]
Thanks for taking this initiative. Overall it makes sense to me. Are the images yours? I'm not sure how the skeletal hoof icon looks all that different from the normal hoof icon. Also, is the Bone Knight only used in EI? If not, might it make sense to have the icon in core as well?

Note to whoever merges: please remember to squash.

**Comment by Wedge009** [comment]
I think making it whiter would help - the brown (which I suppose is meant to give an 'aged' look) makes it look like a normal hoof to me.

**Comment by Wedge009** [comment]
Looks good to me! And good to see Liberty benefits too. It's not my decision, but I approve. (:

**Review by doofus-01 — CHANGES_REQUESTED** [review]
I'll work on a more detailed review this weekend, but for now:
1. hoof-skeletal.png looks fine, it can go in
2. kick-orcish.png needs work before merging

**Comment by Wedge009** [comment]
I forgot to mention that the kick icon is quite dark. I also thought we had kick before, but looking at #6071 again, it is indeed currently missing.

**Comment by doofus-01** [comment]
So about that kick image:
Execution - Too narrow color range, needs some highlights.  Context matters, it probably wouldn't look as bad in game as it does in github.com, but it still needs highlights.  Compare it to `fist.png`, for example.
Design - It looks like a small, bare foot?  That might make sense for a goblin or zombie, I'm not sure it does for the nightblade.

orc-kick
That's my relatively quick take, it still needs some work but is hopefully worth more than words.  In general, stick with the mainline (non-magical) attack icons as models, and using more materials (leather, metal, etc.) can make it more interesting.

**Comment by Descacharrado** [comment]
That is way better, I would vote on putting that in.

**Comment by Wedge009** [comment]
@doofus-01 Since it's just the skeletal hoof being added now is it okay to merge this?

**Comment by doofus-01** [comment]
It is OK to merge now, thanks.

**Pull request merged**
