### PR TITLE
revisions to portals or gates terrain

### PR DESCRIPTION
**Pull request by doofus-01**
I think the "auto-orientation" of the gates terrain was a nice idea, but it wasn't really working.  I've split the orientations into separate terrains, like the bridges.  That is annoying in how it occupies 3 x 2 x (# of types) buttons in the terrain selection panel, but it gives the map-maker more control, so I believe it is a net improvement.

I've added end-caps for if the gate isn't next to a wall (affects nw, ne).

The old terrain codes still exist, so maps can still be loaded and updated, if necessary.

Known issues:
~~Some of the images here are place-holders.~~
Putting rusty and wooden gates next to each other can clash, but I don't know how much that matters.
EDIT: these formatting codes are annoying.

### CODE REVIEW

**Comment by doofus-01** [comment]
Now I've got done what I wanted to get done with this.

**Comment by ln-zookeeper** [comment]
There's quite a few inconsistencies in these. Some pillars are different in the open and closed versions (either WRT texture or shadows), some pillars don't have shadows at all. Also the size of the pillars in the n/s rusty gate varies. The differences in texture are only partly due to the grain I added earlier, so the differences other than the difference in grain are possibly unintended.

[I think I managed to fix all the texture/shadow/size inconsistencies](https://www.dropbox.com/s/axouv79c6jiquzr/portals.zip?dl=0), although some of them actually look pretty bad, and all the missing shadows are still missing.

So, what do you want to do? I can put these in now and you can tweak them later, or if you want to do it now I can wait until you're finished.

**Comment by doofus-01** [comment]
I'd forgotten there were texture tweaks, I probably did inadvertently "revert" those.  I can't see your linked fixes without registering with dropbox.com, is it something you can send in a forum PM? 

As for what to do, how much time is there?  I still believe this is an improvement over what was there, but if time permits, it probably is better to get it done correctly now.

**Comment by GregoryLundberg** [comment]
At the bottom of the login / signup popup is "No thanks, continue to download" where you can download the zip file anyway.

**Comment by doofus-01** [comment]
So there is, thanks.

**Comment by doofus-01** [comment]
I'm not sure what was "pretty bad", aside from maybe the shadows, so I may have still missed something, but I think things are fixed now.  I didn't put as big a shadow to the left of the left-hand pillars as I did in the open N-S door spot, but as long as the door isn't sitting by itself in a meadow, I think it looks better that way.  I also made the N-S open gate one-sided, like the closed door.

**Comment by ln-zookeeper** [comment]
In my manual merge, I changed the compatibility code to not show the terrains in the editor palette at all, and to use a n/s door in place of color-hex.png. Everyone currently using the terrains already knows that they'll be needing to update, anyway. I also put even the open doors into the obstacle editor group, because both the open and closed doors so clearly belong together.

There's still some cases where the pillars are slightly different between the open/closed variants, but then again it's not actually a problematic discrepancy and most likely no one will ever notice, so it's fine. I'm also not sure why half the images are 180x144 when there doesn't seem to be any need for it, but maybe that's a leftover from the previous versions.

**Comment by pydsigner** [comment]
I do hope you made those tweaks as a separate commit rather than putting
them in the merge commit.

**Pull request closed without merging**
