### PR TITLE
Resolving date inconsistency

### PR DESCRIPTION
**Pull request by clockback**
This bug was a problem: https://github.com/wesnoth/wesnoth/issues/4314
The discussion regarding it can be found here: https://forums.wesnoth.org/viewtopic.php?f=8&t=50702

### CODE REVIEW

**Comment by Wedge009** [comment]
While I always appreciate consistency in lore, I thought there was an effort to align dates and such across the Wesnoth story not too long ago. So I'm just wary that we don't undo any of that work - I leave this to those more familiar with the details. I assume those involved in the forum discussion are taking care to avoid further conflicts/contradictions.

**Comment by CelticMinstrel** [comment]
The only think that confuses me about this is why was Weldyn changed to Tath...?

**Comment by clockback** [comment]
Weldyn was changed to Tath because that is where "The Treaty" from LoW appears to be set. The previous scenario "Human Alliance" takes place in Tath, while "The Treaty" has no map. There is no indication on the map in "The Chief Must Die" that they travelled to Weldyn.

**Comment by nemaara** [comment]
Merged into master.

**Pull request merged**
