### PR TITLE
TSG S3: fixes in the story logic

### PR DESCRIPTION
**Pull request by sevu**
- Ethiliel's sprite is a Shyde
- On easy difficulty the player didn't fight undeads

What do you think about this string changes?
Please post if you have an better wording in mind.

### CODE REVIEW

**Comment by sigurdfdragon** [comment]
Maybe: "What have we done?! Our forces cannot stand against this commander!"
The other changes seem ok.

**Comment by ln-zookeeper** [comment]
Ethiliel was supposed to have a wingless version of her portrait, but I think the artist simply forgot to upload it at the time. So, changing her to a shyde on all difficulties seems fine, at least until someone makes a wingless version out of the current portrait.

However, the story logic fixes really don't seem necessary to me. As far as I can tell, you can only get that outcome (no undead recruited) if you kill the outlaw leader before you visit Westin. Considering it's a main plot point that you have bandits summoning undead, I think one should rather make sure that it happens regardless of player action, instead of having alternate dialogue if it doesn't. One possible way to make sure it happens would be to change the recruit list also when getting close to the enemy leader (if Westin hasn't been visited yet) and then tweaking all the relevant dialogue to account for the possibility of Hylas not having been found yet.

**Comment by pydsigner** [comment]
@ln-zookeeper agreed. Has anyone ever actually defeated the outlaws before heading to Westin? There's a pretty hard time on making it over there if I remember correctly.

**Comment by sevu** [comment]
In the 2nd Scenario you are in Westin and encounter undeads. This has no influrence on the 3rd Scenario.
In the 3rd Scenario you fight undeads only on the higher difficulties, and bandits with bats otherwise.
This line in question could fit referring to what appended in Westin too, but having another one referring to the current lost battle would be nice.

**Comment by ln-zookeeper** [comment]
Oh, duh. I don't know why I thought this was about the 2nd scenario, when it obviously isn't. My bad.

Ok, so, I don't really see any reason why they shouldn't recruit undead even on easy. The fact that on easy they only get bats might very well date back to ancient times when bats actually were undead units.

Of course the outlaw leader can be limited to recruiting only 1-2 Skeletons and/or Skeleton Archers if necessary for balance, but it doesn't make any sense for him to not recruit undead on one difficulty level, and then for the dialogue to even acknowledge that.

**Comment by CelticMinstrel** [comment]
> The fact that on easy they only get bats might very well date back to ancient times when bats actually were undead units.

If you wanted to you could also use an undead bat instead of the standard bat? Not sure if this is a good idea though.

**Comment by sigurdfdragon** [comment]
I agree with zookeeper, I think something like adding skeletons and limiting the number if appropriate would work.

**Comment by sevu** [comment]
I will look into it at some point

**Pull request closed without merging**
