### PR TITLE
1.14: run woptipng png compression script.

### PR DESCRIPTION
**Pull request by matthiaskrgr**
992 of 14223 files optimized, 5242590 bytes reduced to 3878424 bytes; -1364166 bytes, -26.02%
Optimization threshold was 10.0%
(size reductions below 10% compared to original size were discarded).

run imagemagick, optipng, advdef and optipng on png images.

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
I remember that there were some issues with image compression in the past where it looked fine on one distro but bad on others so it would be great if someone on windows or macosx could double check that the images look like intended.

**Comment by Wedge009** [comment]
What kind of OS differences are there? I wouldn't have thought there would be major differences for a lossless algorithm, unless there are things like metadata (gamma, translucency, etc) to consider.

Looks like we've had some unit updates as well, since this was run.

**Comment by matthiaskrgr** [comment]
@Wedge009  d5fa4bc7b25ae115d23070c04970dec7f66baf3f

**Comment by Wedge009** [comment]
Awaiting input from others, then.

**Comment by GregoryLundberg** [comment]
There is a difference between using an off-the-wall obscure method (which was what was done in 2014) and choosing different options for existing, accepted methods to obtain better results.

It seems to me that woptipng was run some time prior to 1.14 and this would be a re-run to catch new/changed files and gain a bit more compression.

**Comment by GregoryLundberg** [comment]
@matthiaskrgr Can you resolve the conflicts and/or re-run this?

1.15 will be based of master, so you will want to consider whether it should cherry-pick or be run against master as a separate PR.

**Comment by Vultraz** [comment]
Can be re-run at a different time.

**Pull request closed without merging**
