### PR TITLE
Add sprite for the Cold Dagger item to UtBS

### PR DESCRIPTION
**Pull request by Elvish-Hunter**
I just finished replaying UtBS and I noticed that the map was changed in the Descending Into Darkness scenario.
To be more specific, in older versions there was a long tunnel filled with water; at its end, there was a hex of ford terrain, so it was obvious that moving there would've done something.
In the 1.18 version, the map has been reworked so the tunnel has disappeared and has been replaced with a small cave filled with water and some other terrains and objects (paved road, a brazier, some remains...); it isn't really clear any more where to find the cold dagger, especially if you play the campaign for the first time, so a sprite for this item seems needed.
I looked in the forums to see if a cold dagger/sword sprite was already made, but apparently nobody did; however, a long time ago, I made a recolor of the flaming sword sprite to give it a blue flame, so I decided to finally use it.
Being a derivative work of the original flaming sword, I'm forced to release the sprite as GPL v2+ (but if it were just for me, we could use any license we want).

### CODE REVIEW

**Review by Dalas121 — APPROVED** [review]
Thanks for noticing this and getting it resolved. Looks good to me.

**Review by knyghtmare — APPROVED** [review]
It's good. Would also appreciate if the cold-sword.png thing is moved to core.

**Comment by Elvish-Hunter** [comment]
> It's good. Would also appreciate if the cold-sword.png thing is moved to core.

Thanks, but of course that's up to @doofus-01 to decide.

By the way, this PR is on the master branch; do we want to backport it to 1.18 as well?

**Review by doofus-01 — APPROVED** [review]
This looks like a bug-fix, so it should not linger.  I'd need to see it in context to judge the image quality, but this is simple enough to touch up later if needed.

**Comment by doofus-01** [comment]
> It's good. Would also appreciate if the cold-sword.png thing is moved to core.

It's fine staying in _UtBS_ for now.  What is the reason for moving it to core?

>By the way, this PR is on the master branch; do we want to backport it to 1.18 as well?

I think this is OK to backport; it doesn't move or delete any images, and doesn't involve MP.

**Comment by Elvish-Hunter** [comment]
As agreed, I just backported the PR to the 1.18 branch.

**Pull request merged**
