### PR TITLE
Change colors of ToDs

### PR DESCRIPTION
**Pull request by bumbadadabum**
This mostly makes night darker and makes dusk more red.

It also makes the summer and winter schedule have more of a use, since they now have slightly different colors.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I definitely want to try this before merging... in particular, making nights darker triggers an alarm bell for me.

**Comment by Vultraz** [comment]
Ok I'm really an idiot. I forgot that testing in a savefile doesn't show the changes. I have now correctly tested them and they still seem fine. Might tone down the red at dusk just the tiniest bit; seemed slightly hard on my eyes.

Still, good to go in I'd say.

**Comment by Wedge009** [comment]
I did a side-by-side comparison on a default Heir to the Throne starting scenario (I don't know about differences between summer and winter):
* Dawn: Subtly brighter than before.
* Day: No change.
* Dusk: Noticeably more red, which I suppose matches what one might see in a sunset.
* Night: Noticeably darker and less red/yellow.

I do think the darker night phase exacerbates the problem reported in https://gna.org/bugs/?14503, but I suppose the problem there is the root cause and not due to the changes made here.

**Comment by bumbadadabum** [comment]
@Wedge009 Yeah shadows are barely visible during the night, but they weren't before either. Ghosts and Wraiths are still visible enough, which I think is the bigger thing with this change.

**Comment by bumbadadabum** [comment]
Tweaked some of the colors.

If they're fine like this I'm going to start converting the post-fall and 24hr schedules as well.

**Comment by bumbadadabum** [comment]
Did the 24hrs schedule and the post-fall schedule.

**Comment by CelticMinstrel** [comment]
I keep forgetting to try this... feel free to poke me about it whenever you're around...

**Comment by Vultraz** [comment]
Oh, and also Eastern Invasion defines its own TOD_COLOR_SHIFT macro. Recommend replacing it with the mainline one.

**Comment by CelticMinstrel** [comment]
That would depend on the reason for the custom macro...

**Comment by bumbadadabum** [comment]
>Oh, and also Eastern Invasion defines its own TOD_COLOR_SHIFT macro. Recommend replacing it with the mainline one.

Ah yes that should be done.

**Comment by bumbadadabum** [comment]
Updated.

**Pull request merged**
