### PR TITLE
Add case conflict check

### PR DESCRIPTION
**Pull request by AI0867**

### CODE REVIEW

**Comment by AI0867** [comment]
Related to issue #2046.

**Comment by Arcanister** [comment]
What is the reason to disallow installing add-on in client code? It would be better to be able to install add-on which has no problems (in case-sensitive system) at all or problems with some files (in other systems), than be not able to install it at all. I think it should be a warning, not error.

**Comment by AI0867** [comment]
I primarily added it to the addon server. However as those checks are also used by the client, I added them there too. I suppose they might be of use for a windows user connecting to an old server. (in which case it would refuse to install the add-on, rather than silently corrupting it)

**Comment by CelticMinstrel** [comment]
This looks good, but is it possible to also give a list of the conflicting files?

**Comment by Arcanister** [comment]
I agree that installing add-on, which corrupts files silently is not the best option, but refusing to install it at all is not much better. It is better this to be clearly visible warning instead of an error.

**Comment by AI0867** [comment]
The primary function is that the add-on server will reject them, not that the client will refuse to install them (that's just as a fallback and for consistency).

There is no conflict between `_info.txt` and `_INFO.CFG`, but I suppose that's just a typo. `_info.cfg` is never uploaded, though differently-cased versions might be. After the add-on is downloaded and extracted, `_info.cfg` is written by the client, so it will simply silently overwrite any other versions that might be present.

Regarding a list of conflicts, that would be a bit more work. Shadowm is working on something like that already (PR #2047). I'd prefer to base any improvements in that regard on his work.

**Comment by AI0867** [comment]
Rebased to fix merge conflicts.

**Comment by AI0867** [comment]
I have a followup branch lined up to show the conflicting filenames.

**Comment by gfgtdf** [comment]
`boost::algorithm::to_lower_copy` works chracter-wise,  in particular this implementation probably only supports ascii chracters, which is ok if #2070 is merged but should be reworked in case it's not.

**Comment by AI0867** [comment]
Checking unicode case would probably also mean checking normalizations and such, which would probably require more code than this PR.

**Comment by GregoryLundberg** [comment]
to_lower_copy can convert to lower case for the given locale. In the default global ("C") locale, it only converts ASCII letters to lower case.

**Comment by AI0867** [comment]
Okay, regarding windows case insensitivity, this is decided on a by-volume basis. Each NTFS volume has an `$upCase` special file that contains the mapping to uppercase for each character (apparently for compatibility with FAT?). This file does not take locales into account, does not use match unicode case conversion, and likely won't match HFS+ either (which also does normalization). I think our best bet in this case is to just case-check ASCII and hope for the best in the other cases.

References:
http://archives.miloush.net/michkap/archive/2005/01/16/353873.html
http://archives.miloush.net/michkap/archive/2005/10/17/481600.html
http://archives.miloush.net/michkap/archive/2004/11/28/271121.html
http://www.ntfs.com/exfat-upcase-table.htm
http://elixir.free-electrons.com/linux/latest/source/fs/ntfs/upcase.c

**Comment by AI0867** [comment]
I've added the 'C' locale to the `to_lower_copy` call to ensure only ASCII is converted.

**Pull request merged**
