### PR TITLE
Avoid overwriting an invalid/corrupt preferences file.

### PR DESCRIPTION
**Pull request by jostephd**
For #1326

Example:

```
$ mkdir /tmp/foo
$ echo '[foo]' > /tmp/foo/preferences
$ ./wesnoth --userconfig-dir=/tmp/foo
```

Before this patch, /tmp/foo/preferences would be overwritten.  With this patch, it would be preserved.

### CODE REVIEW

**Comment by gfgtdf** [comment]
so wesnoth now just closes? for people that don't know how to access this file this would mean that wesnoth is then permanently broken for them right?


I think it'd be better if wesnoth would just make a backup of the corrupted file and then overwrites it as it did before.

**Comment by jostephd** [comment]
> for people that don't know how to access this file this would mean that wesnoth is then permanently broken for them right?

The error message gives the path of the file.

> I think it'd be better if wesnoth would just make a backup of the corrupted file and then overwrites it as it did before.

https://github.com/wesnoth/wesnoth/issues/1326#issuecomment-532628007, third paragraph.

**Comment by jostephd** [comment]
**Changes requested** on #1326.

**Comment by Vultraz** [comment]
Discussion on related bug seems to have reached a consensus that this isn't the optimal fix.

**Pull request closed without merging**
