### PR TITLE
Move generally-useful units to core so addons can use them

### PR DESCRIPTION
**Pull request by CelticMinstrel**
This moves many units from campaigns to core, allowing addons to safely use them without having to copy them into their own addon directory.

The following units have been moved (or are planned):

* [x] ~Quenoth faction (all units except Youth, Corrupted Elf, and Incarnation) - note that this is a total of 21 units~
* [x] Naga Hunter and ~Naga Guardian line~ (4 units total)
* [x] Merman Citizen and Brawler
* [x] Great Ogre (with optional define to enable it advancing from ogre; NOTE this define still needs to be added to LoW's extra_defines)
* [x] ~Wose Sapling and Shaman~ (with optional define to enable the shaman advancing from wose)
* [x] ~Skeleton Rider, Bone Knight, and Death Squire (with optional define to enable the death squire advancing from skeleton)~
* [x] Dwarvish Miner
* [x] Orcish Shaman
* [x] ~(new) Riderless tauroch, if I can find a sprite for it.~

This hasn't been tested yet, but for now it's up here for general review. I'll test it at some point once I get master built (which I think just means switching out libraries).

### CODE REVIEW

**Comment by sevu** [comment]
For the miner: Will the status be reset when advancing to the next scenario? (Both cases would be okay though)
I would only use the loaded status, and set it accordingly in the SoF campaign and use sth. else in the campaign, such as unit variables to differentiate between gold and coal. On the other hand, one could write the [or] part as oneliner, I think status can be a comma separated list.

For the orcs… that's quite some change, they were all lvl 1 cosmetic units. though I think most players would wish for a rare seen orcish mage line…

For the Quenoth, I like the idea to move them to core a lot. But, on the other hand, I wonder if the dehydration status couldn't be implemented another way (C++?), so there would be no need for separate healing abilities in UtBS.
If the dazed ability is available in general, it may need some rewording (#3076).
The formation ability has the disadvantage that it's bonus is not displayed in the UI, I guess that can't be solved trivially.

Great Ogre… It's probably fine to advance without extra define.

Naga Hunter, the one with the awesome portrait! The warden though has none…maybe not mainline quality. Also, maces don't work well in water.

Death Squire… I think that makes the Death Knight less special. Similar to the cases where UMC added various fitting advancements for the sake of having them.

Skeletal Riders… A new unit for the undead would be good. However, won't a skeleton just fall down from a living horse? I think that's the part which Chocobones do better.

**Comment by CelticMinstrel** [comment]
> For the miner: Will the status be reset when advancing to the next scenario? (Both cases would be okay though)

Good question. I think it probably should be? With this PR as it is now, I'm not sure whether it will.

> I would only use the loaded status, and set it accordingly in the SoF campaign and use sth. else in the campaign, such as unit variables to differentiate between gold and coal. On the other hand, one could write the [or] part as oneliner, I think status can be a comma separated list.

Both good points. Considering that the image doesn't reflect gold vs coal, I think I prefer the first method.

> For the orcs… that's quite some change, they were all lvl 1 cosmetic units. though I think most players would wish for a rare seen orcish mage line…

Yeah. I actually copied those from my never-released campaign (rather than from SotBE) and then compared them against the SotBE ones to remove any extraneous changes. The only substantial difference in my campaign is that I added the magical special alongside drain, but I figured it was probably better not to do that here.

> But, on the other hand, I wonder if the dehydration status couldn't be implemented another way (C++?), so there would be no need for separate healing abilities in UtBS.

Sure it's possible, I guess. Something similar to how poison is implemented would work. Do we want to do this though?

> The formation ability has the disadvantage that it's bonus is not displayed in the UI, I guess that can't be solved trivially.

Well, when I was looking at formation, I was actually wondering why this can't be implemented via `[chance_to_hit]`? Or even the much-maligned `[defense]` special? (Or was that an ability?) I'm sure there's probably some reason why it doesn't work with `[chance_to_hit]` but it wasn't immediately clear to me what that reason is.

> Great Ogre… It's probably fine to advance without extra define.

Sure, I can do that. I just kinda assumed that any new advancements would need to use an extra define, but I suppose this particular one isn't an MP faction unit, so maybe it's fine.

> Naga Hunter, the one with the awesome portrait! The warden though has none…maybe not mainline quality. Also, maces don't work well in water.

Well, nagas are amphibious though, unlike the merfolk - they can function well both on land and in the water. For a portrait, maybe we could temporarily use one of the other two naga portraits for this line?

> Death Squire… I think that makes the Death Knight less special. Similar to the cases where UMC added various fitting advancements for the sake of having them.

Well I mean, that unit was in a mainline campaign, so... I think it's fine. Still, I guess I can remove that one if it's not wanted. (Or I could remove only the extra define?)

> Skeletal Riders… A new unit for the undead would be good. However, won't a skeleton just fall down from a living horse? I think that's the part which Chocobones do better.

I always assume the idea with this was that both the rider and horse were skeletal, though that horse _does_ look more like a zombie to me (or possibly even alive, which wouldn't make much sense - wouldn't it bolt?).

**Comment by ln-zookeeper** [comment]
I'll reiterate that the Quenoth units should not be moved to core, at least not yet. They might still undergo **some** substantial changes, and moving them to core means having to worry about breaking UMC.

As for the rest, I'd wish for some rationale beyond "add-ons could use them directly", because that same reasoning potentially applies to every image/sound/unit/terrain/macro that campaigns have. For example, how many add-ons actually do ship their own mostly-unaltered copies of Orcish Shamans, Dwarvish Miners or the Great Ogre? Assets are segregated as they currently are for a reason, after all.

A lot of campaign units are also reasonably redundant. The Naga Guardian line for example offers little that the regular Naga Fighter line doesn't already have. It has a different melee weapon, +10% physical resistances, and it's slower. It's more or less a flavor unit that works fine as a campaign unit but in core will appear alongside the Naga Fighter and beg the question of why couldn't we come up with something more interesting, while also making it harder to actually make big changes to it due to its core status.

So, I'd say that for any units moved to core, we should consider now only whether someone will find it convenient, but also how well it actually fits in with the other units of its race, because that's how they'll appear. Is a civilian merman really a natural fit amongst the core merfolk, do we want the ogres to be a race that can grow to monstrous size, do we want core orcish units that are a complete dud gameplay-wise, and so on.

I guess I'd feel more comfortable considering each unit in isolation, with some proposed changes to make them more core-worthy. For example I've always felt like in principle the Wose Shaman would be good in core (at least after it got its current sprite), **but** that it's also very dull if/when its only specialty is entangle.

**Comment by stevecotton** [comment]
Once the list is finalised, it would be helpful to have a compatibility add-on for 1.14 - a resource pack add-on with these units, so that other 1.14 add-ons can depend on it. Doing it in the other order (creating the 1.14 resource pack first, seeing how many add-on authors start using it) might be a way to get feedback while 1.16 is still in the early 1.15 stages.

**Comment by CelticMinstrel** [comment]
That's a great idea! If/when this (or a successor) is merged, I'll probably go ahead and do that.

Thanks for all the feedback, Zookeeper. I can certainly open a new PR for each unit or unit line if you really prefer that. Personally I'd prefer to keep it all in one place. You'll notice I do at least have a separate commit for each unit/line, so it would be easy to drop or tweak individual commits as desired.

> As for the rest, I'd wish for some rationale beyond "add-ons could use them directly", because that same reasoning potentially applies to every image/sound/unit/terrain/macro that campaigns have.

I can't deny this! My rationale in choosing which units to include was basically something like "is this unit used for a unique character in the campaign?". I may be mistaken, but as far as I know, all the ones I selected are indeed general units, rather than unique characters or rare, unusual monsters.

> For example, how many add-ons actually do ship their own mostly-unaltered copies of Orcish Shamans, Dwarvish Miners or the Great Ogre? Assets are segregated as they currently are for a reason, after all.

Well, this is an answerable question, either by browsing the units list or by grepping the add-on server.
 
> The Naga Guardian line for example offers little that the regular Naga Fighter line doesn't already have. It has a different melee weapon, +10% physical resistances, and it's slower. It's more or less a flavor unit that works fine as a campaign unit but in core will appear alongside the Naga Fighter and beg the question of why couldn't we come up with something more interesting, while also making it harder to actually make big changes to it due to its core status.

I'm fine with dropping the Guardian line and importing only the Naga Hunter. I'd also be fine with changing the Guardian line if someone had suggestions on what changes to make.

> Is a civilian merman really a natural fit amongst the core merfolk

I'm not sure why it wouldn't be? In any case, I like level 0 units in the vein of the human peasant and ruffian, which is why I added not only the citizen here but also the wose sapling.

> do we want the ogres to be a race that can grow to monstrous size

I like the idea that some ogres can do so. I don't see it as the norm though.

> do we want core orcish units that are a complete dud gameplay-wise

Well, no. We don't want units that are a complete dud. What exactly makes these orcs a complete dud? I tried to keep the changes minimal here, but I can certainly add more changes. For example, in my (never-released) campaign, I think I increased the damage slightly, and I also added the magical special to the ranged attack (so it has two specials). I don't know whether those are _good_ changes for getting it in mainline, though.

> I've always felt like in principle the Wose Shaman would be good in core (at least after it got its current sprite), but that it's also very dull if/when its only specialty is entangle.

Do you have any other suggestions of what it could gain, then?

---

So I guess the general consensus is that most of these units need additional work to be accepted. Should we just go through each of these units one commit at a time and discuss each one in detail, or should we discuss them all simultaneously?

> I'll reiterate that the Quenoth units should not be moved to core, at least not yet.

That's fine, there's no hurry; and we don't even have to merge this PR directly. We can just cherry-pick individual commits as they become ready.

**Comment by soliton-** [comment]
I think you'll more likely get this moving if you start with picking units/commits that you think are most uncontroversal to be cherry-picked and explain why those units should be in core. I'm happy to provide UMC usage stats for specific unit types.

**Comment by jostephd** [comment]
This PR needs to be rebased from old master to new master.

**Comment by spixi** [comment]
Could the Great Orge be enabled for Era of Heroes? The Ogre is the only stand-alone unit in the whole era.

**Comment by CelticMinstrel** [comment]
I think it would be reasonable, but I'm not quite sure if it could potentially affect the balance of campaigns that use ogres.

**Comment by CelticMinstrel** [comment]
(I suggest opening a new issue for it though.)

**Comment by stevecotton** [comment]
The now-mainlined Wings of Victory has a Wose Shaman too.

**Comment by CelticMinstrel** [comment]
So the wose pair have been moved... any plans to move other units in this PR to core? (Maybe bring back the Great Ogre? ;p )

**Comment by jostephd** [comment]
Should Quintains be moved to core while we're at it? I remember playing a "practice against these dummy enemies" scene in some UMC or another, but don't remember which.

https://github.com/wesnoth/wesnoth/blob/9f179295dd1c6bcbf0fe9c7d4efacb3107076497/data/campaigns/tutorial/units/Quintain.cfg

**Comment by CelticMinstrel** [comment]
Well, we _could_, I guess. I don't see a strong reason to do so, but if others want it...

**Comment by stevecotton** [comment]
A new PR has been opened for the Quenoth elves, #4687 by @Earth-Cake, linking it from here partially to ping everyone subscribed to this PR.

**Comment by CelticMinstrel** [comment]
That pull request has been closed, but is there any chance of moving other units from this list to core?

**Comment by CelticMinstrel** [comment]
I'm going to redo this PR without the Quenoth (I might open a separate PR for them though) and any that were already moved to core.

So just to be clear… if I'm not mistaken, the two wose and the four nagas are now in core, right? (@doofus-01 you probably know the answer, right?) Did anyone ever add a riderless tauroch unit?

**Comment by doofus-01** [comment]
Naga hunter is not moved (and I don't think it should be), but the three guardian nagas are in core, as are the wose sapling and shaman.  There is a riderless tauroch.

**Comment by CelticMinstrel** [comment]
> I don't think it should be

I thought the naga hunter was considered more interesting than the mace nagas, and even had a portrait?

Well, whatever; I'll move it for now but if the consensus is that it shouldn't be, I'll take it out.

**Comment by doofus-01** [comment]
I have no idea who considered what interesting, but there are ranged nagas now, probably changes the situation.

**Comment by CelticMinstrel** [comment]
Although this is a draft, anyone wishing to move any of these units to core can feel free to cherry-pick the appropriate commit as a base.

**Comment by spixi** [comment]
It would be nice to have an intermediate unit between the Wose Sapling and the Wose Shaman.

Something like:
Cost: 20
HP: 44
XP: 40
MP: 4
ambush, regenerates
10 × 2 melee-impact
10 × 2 ranged-impact (slows)

Pilauli created nice artwork for such a unit here: https://forums.wesnoth.org/viewtopic.php?p=658688

**Comment by cooljeanius** [comment]
> Should Quintains be moved to core while we're at it? I remember playing a "practice against these dummy enemies" scene in some UMC or another, but don't remember which.
> 
> https://github.com/wesnoth/wesnoth/blob/9f179295dd1c6bcbf0fe9c7d4efacb3107076497/data/campaigns/tutorial/units/Quintain.cfg

"The Elf, The Dwarf, and The Mage" uses them.

**Comment by CelticMinstrel** [comment]
Updated opening post to strike out the undead horsemen since they've now been added.

**Comment by stevecotton** [comment]
> Updated opening post to strike out the undead horsemen since they've now been added.
> 
> Is there anything else on that list that's now in core but isn't struck out yet?

Everything seems to be either ticked-off or struck out, although I haven't checked that those units are in core now. Can we close this PR?

**Comment by CelticMinstrel** [comment]
Only the struck-out ones are already in core (excluding Quenoth, which was removed from this PR). This PR does need to be redone but I'd like to keep it open as a reminder.

**Comment by CelticMinstrel** [comment]
Closing in favour of #7323, #7324, #7325, #7326, and #7327.

**Pull request closed without merging**
