### PR TITLE
Liberty S3: Play orcish war drums

### PR DESCRIPTION
**Pull request by jostephd**
Previously discussed on #3377.

### CODE REVIEW

**Comment by GregoryLundberg** [comment]
Um .. wrong spot. Move it down to the TODO and then remove the TODO comment?

**Comment by jostephd** [comment]
Yeah, it works better as you say.

If one quits to the title screen while the [sound] is playing, the sound keeps playing. This also happens for [music] when quitting an MP game to the MP lobby. I thought there was already an issue for that but I can't find it.

**Comment by GregoryLundberg** [comment]
Might want to do the same for Master.

**Comment by jostephd** [comment]
@GregoryLundberg There are a _lot_ of changes to 1.14 that haven't been committed to master. What's going to be done about them?

**Comment by GregoryLundberg** [comment]
Someone is gonna need to work through them. Some won't go in due to whatever they're doing to the code, but many will still want to be applied.

**Pull request merged**
