### PR TITLE
SoF: Align masked dwarf portrait to the right

### LINKED ISSUE #9008: THoT S05: Enemy leader (Masked Dwarf) portrait is shown cut off by the vertical crop
### Game and System Information

- **Version:** 1.18.1+dev (d5b726df6ecd107b8923e6a9a8bbc3785bf3a20a)

### Description of the bug

In the intro of S05 Fear, the portrait of the enemy leader is shown on the left side of the screen, facing left, but the image is obviously cropped assuming that it will be shown touching the right side of the screen.

### Steps to reproduce the behavior

1. Start S05 Fear. No need to play through to that point, can just start the campaign and then use debug to just directly to S05.
2. Move any unit east. No need to recruit, can just move the leader in turn 1.
3. Dialogue happens, including the portrait.

### Expected behavior

_No response_

### Additional context

All of the enemy portraits in this campaign are drawn facing left, including Karrag and Elurin; they're all cropped assuming they'll be shown at the right hand side of the screen.

### PR DESCRIPTION
**Pull request by Wedge009**
Resolves #9008.

I think this is a small enough change to be back-ported.

### CODE REVIEW

**Comment by Wedge009** [comment]
Before (#9008):
image

After:
image

**Comment by Wedge009** [comment]
Any remarks on this trivial change? I feel like this shouldn't need to wait weeks before merging.

**Comment by Wedge009** [comment]
@stevecotton You made the original report, do you have any advice on this?

**Comment by stevecotton** [comment]
Looks good to me. Not sure if someone else should review, I'd lean to merging now.

**Comment by Wedge009** [comment]
1.18: cf7ceb6f24544475d4a058af03a9219d2b214bdf

**Pull request merged**
