### PR TITLE
Disable game name for local MP

### LINKED ISSUE #1122: Setting game name shouldn't show when playing a local game (GNA #10785)
**[Original submission](https://gna.org/bugs/index.php?10785)** by blueblaze on 2008-01-15

Another minor issue, the name of the game shouldn't show when playing a local game, as it's just a pointless option that I can tell. Unless the game name has some effect on the save file, then I don't think it should even be selectable when playing locally.

(Reproduced on XP)
Release: 1.3.14
Priority: 5 - Normal
Severity: 1 - Wish

### PR DESCRIPTION
**Pull request by Wedge009**
Also remove redundant disablement of registered_users_ option.

Resolves #1122

### CODE REVIEW

**Comment by Vultraz** [comment]
What was this change for?

**Comment by Wedge009** [comment]
See above, #1122.

**Comment by Vultraz** [comment]
So it's just cosmetic?

**Comment by Wedge009** [comment]
I believe so, but there was some concern that the game name is saved (though for what purpose we don't know). If there is concern about that I can remove the game name blanking and just disable the widget.

**Pull request merged**
