### PR TITLE
remove inproper and inconsistent names

### PR DESCRIPTION
**Pull request by babaissarkar**
1. remove obviously English female names from Dunefolk female names list
2. remove 'bakri' from male name list (means 'goat', could be offensive)
3. remove one potentially offensive name from saurian name list
4. remove 'Dalal' from dunefolk female names (~~not female name,~~ can be used as slang, means 'broker/pimp')

### CODE REVIEW

**Review by knyghtmare — APPROVED** [review]

**Comment by cooljeanius** [comment]
Kinda tangential, but I wonder if it'd be possible to break up the name lists across multiple lines at all? It's kind of hard to review when they're all on a single line like that...

**Comment by Gothyoba** [comment]
I don’t think we should be using actual arabic names here, but Dalal is a real arabic female name.

**Comment by babaissarkar** [comment]
Seems like both of these are true for `Dalal`
1. https://en.wikipedia.org/wiki/Dalal_(name)
but also,
2. https://en.wiktionary.org/wiki/dalal

**Comment by babaissarkar** [comment]
> but I wonder if it'd be possible to break up the name lists across multiple lines at all?

Yes, given it's a WML translatable string, just requires a bit of time investment.

**Comment by Gothyoba** [comment]
Probably unrelated, but the drake names phonetics sections should be reviewed. What is /th/ /sh/ /ch/ pronounced like? I’m inclined to think this is IPA (International Phonetic Alphabet), but if so ‘ is a marker of stress, not a glottal stop. Is sh supposed to reperesent the s in sand followed by the h in hat like the IPA or the sh in sheep? When they say /y/ is absent, do they mean /j/ in IPA or the vowel sound in IPA represented by y (which does not exist in most english dialects)? And what is hn a nasalization marker of? The prvious vowel, or perhaps the following vowel, or a consonant, or something else? é is also unnecessary, and feels like it was made to be easier to an English speakers, but drakes would probably not speak English. I would imagine this would create issues for transaltors, and potentially lead to inconsistent translations.

**Comment by babaissarkar** [comment]
> What is /th/ /sh/ /ch/ pronounced like?
Aspiration is also a likely candidate.

**Comment by Gothyoba** [comment]
I think aspiration could be a reasonable candidate. (Though this should be specified). ch also represents /x/ (think the ch in loch in some dialects, similar to h) in some languages like German. I think this should be further clarified rather than leaving people to guess what these sounds mean.

**Comment by babaissarkar** [comment]
An even worser problem is whether these hardcoded name lists are actually used at all.
@CelticMinstrel on discord/irc suggested that actually the CFG generator is probably being used. If so these name lists should be removed so as not to increase work for translators.

**Comment by CelticMinstrel** [comment]
Note that even when they were used, they were not used as name lists (pick a random name from the list) but as input to a markov chain generator.

I don't believe the API offers any way to reach the markov chain list for a race that declares both a markov list and a CFG definition. So it's probably fine to delete them, but I'd double-check #644 first in case there was a legitimate reason _not_ to.

**Comment by stevecotton** [comment]
Think about seeing the diff in Poedit, rather than in Git where it's obvious what changed.

I think this should have a changelog_entries file, and I suggest that file should also contain notes to the translators, specifying exactly which names were removed (including "Ssexur"). I previously suggested putting translator notes in Git commit comments, but the changelog files seem even better. @Pentarctagon, does that make sense to you? That you (or me, if you want me to do it) would collate notes from those files and mail them to the translators' list, but not copy them to the main changelog?

**Comment by Pentarctagon** [comment]
I think @babaissarkar should send an email to the translators ML with information about the change after merging (and backporting?) the PR. Not sure why they'd go in the changelog file.

**Comment by Pentarctagon** [comment]
Given the nature of the change, I think this would need to be backported. Otherwise there wouldn't be much point in notifying the translators now given they aren't supposed to translating the master branch for a while.

**Comment by cooljeanius** [comment]
> Note that even when they were used, they were not used as name lists (pick a random name from the list) but as input to a markov chain generator.
> 
> I don't believe the API offers any way to reach the markov chain list for a race that declares both a markov list and a CFG definition.

Is there an issue open for that? I think such an API would be useful; see also this forum thread:
https://forums.wesnoth.org/viewtopic.php?t=36116&start=15

...also, some of the names that I'm presuming are being removed under the "obviously English" criterion actually came from other languages first, like "Sarah" is biblical and could be considered Hebrew... actually, let me look them all up:

- https://en.wikipedia.org/wiki/Boutheina (Arabic)
- https://en.wikipedia.org/wiki/Cynthia (Greek)
- https://en.wikipedia.org/wiki/Dalia_(given_name) (Persian, Arabic, Hebrew)
- https://en.wikipedia.org/wiki/Eliana (Hebrew, Greek, Arabic, Romance Languages)
- https://en.wikipedia.org/wiki/Lamia (ok this one actually makes sense to remove given that it was a monster)
- https://en.wikipedia.org/wiki/Melissa (Greek)
- (can't find Qistina)
- https://en.wikipedia.org/wiki/Sherine_(name) (Persian)

Another thing I kinda worry about is how much longer the `male_names` list is compared to the `female_names` list. I think that we should be trying to mitigate this inequality rather than worsening it.

**Comment by Zireael07** [comment]
@cooljeanius Average person will perceive Cynthia and Melissa as English (heck I am a linguistics geek and I wouldn't know they have older origins)

Point on the rest though

**Comment by Gothyoba** [comment]
I did not know Melissa was of Greek origin, but I was aware of Cynthia being Greek.

**Review by Dalas121 — APPROVED** [review]
Without knowing exactly how the name generator works, the proposed changes seem reasonable to me.

Given that only 1-out-of-6 Dunefolk units can be female, I think it's ok for the female name list to be much shorter (though not ideal, and right now it's only 1/10 as long).

**Comment by cooljeanius** [comment]
> Without knowing exactly how the name generator works, the proposed changes seem reasonable to me.
> 
> Given that only 1-out-of-6 Dunefolk units can be female, I think it's ok for the female name list to be much shorter (though not ideal, and right now it's only 1/10 as long).

Yeah, if we could get it to 1/6 as long instead, that'd be an improvement, IMO

**Comment by CelticMinstrel** [comment]
> Is there an issue open for that? I think such an API would be useful; see also this forum thread:
> https://forums.wesnoth.org/viewtopic.php?t=36116&start=15

I don't really understand why you'd want to have two male name generators for a single race. That thread is all about "accidental profanity", but the proposal of choosing the generator type in preferences doesn't seem viable and wouldn't solve the problem even if it was.

The reason it doesn't seem viable is because in multiplayer games the host generates the name. So, assuming people can even tell which generator is used, they're going to get confused when the game uses a different one than they selected in preferences. And if they _can't_ tell the difference then there's no point in offering the option.

The Lua API to racial name generators works exactly the same as internal name generation – it uses the CFG generator if it is present, otherwise the Markov Chain generator. The general Lua API to name generation requires you to specify the generator type when you create a generator, so if you wanted to implement a preference as described in a specific campaign, you could theoretically do it.

**Comment by babaissarkar** [comment]
`Boutheina`, `Dalila` and `Sarah` has been added back.

**Pull request merged**
