### PR TITLE
De-thread the loading screen. Load in the main thread.

### PR DESCRIPTION
**Pull request by mesilliac**
The programming interface is still the same. Draw and input events are now processed when the worker function calls loading_screen::progress().

This has two main repercussions:
1. exceptions will no longer be silently eaten by the loading screen,
2. loading screen animations will not update unless progress() is called.

In order to update animations in a timely fashion... well, for me they already update so fast as to be nigh-instant. I'm not really sure what ever takes any significant time to load.

If there are actually sections of loading code that take significant time, some sort of `loading_screen::spin()` function shouild be added, that simply lets the loading screen update the spinner animation. Worker functions should call this periodically while performing long-duration tasks.

An alternate option would be to use a progress bar in stead of a spinner animation. Such that when `loading_screen::progress()` is called, it updates both the name of the loading section and the overall progress amount.

In any case, with this change it becomes the responsibility of the worker function to relinquish control momentarily so that events can be processed. As worker functions were already regularly calling `loading_screen::progress()`, with the changes i made here they do this automatically but with relatively low frequency.

The main thing that is potentially lost here is that if a loading function deadlocks for some reason, it becomes impossible to close the program via the close button. I have no idea if there is actually any chance of this happening, nor if it is really a problem. My OS offers to kill programs that are not responding to input anyway. And if there is a chance of a loading operation deadlocking, it should probably have a time-out attached.

I think doing things this way is preferable to the existing situation, and also to the major architectural overhaul that would be needed to do it properly using threads. I have previously tried four separate solutions to salvage the existing threaded implmentation, and all would be far more work than i am prepared to put in, as well as changing core game systems in dangerous ways, which i do not want to do.

### CODE REVIEW

**Comment by Vultraz** [comment]
I strongly disagree with this direction. Certainly, there are benefits from using a single thread, but design-wise this is a step backwards.

1. We shouldn't be manually raising draw events and running the event loop. I don't know if we'll ever actually get to this point - though we are getting closer - but the event loop should be run in one spot only and dispatch draw events each go-around. We can figure out what the most optimal way to cache things *between* draws is, but we shouldn't actually be invoking drawing ourselves.
2. The `spin` function itself. It is not optimal to make animations rely on an external caller to update, especially since now we need two places to raise draw events separately. It makes the whole draw pipeline unnecessarily complicated. We should be able to go from an event loop, look at draw hooks, and know they're getting called once per frame.
3. Non-maintainability and contamination of concerns. Right now, the loading screen is one of the few places in the UI where we really have animations because of the lack of accelerated rendering and how absolutely clunky it is to work with animations with the dirty widget interface. It makes the LS animation handling unnecessarily complicated to tie the drawing code into the loading code, when they should be distinct and separate. Why should the game config manager care about whatever animation the loading screen is displaying? You could argue This method preserves that separation since `spin` only raises draw events and `draw_callback` still handles the logic, but it still means we need to keep track of where we should add `spin` calls. I don't see how this is an upgrade from mutexes. We already have `progress`. Let's not add more.
4. The multiplayer connection screen. If we switch to this method, the entire multiplayer connection workflow (https://github.com/wesnoth/wesnoth/blob/master/src/game_initialization/multiplayer.cpp#L177-L231) needs to be redesigned. Right now it relies on being able to pause the LS worker to wait on the result of a third sub-worker. I never fully finished implementing the network worker for MP (incoming data packets are already handled in their own thread) - I still want to get back to that someday - but redesigning the connection process (including everything in `open_connection` would be significant work in and of itself. And I do think it's rather elegant right now, if I do say so myself 😬

**Comment by Pentarctagon** [comment]
While conceptually I do agree that having a separate thread so that loading can happen in the background while the GUI remains responsive, this has also caused its own problems (#3218, #1603, #3391 from a few minutes looking through existing issues, plus a known but apparently undocumented issue that holding F5 on the main menu will eventually crash Wesnoth).  Additionally, based what mesilliac has said from the other ways he's attempted to resolve this, there would seem to be significant other technical issues with trying to keep the current threaded implementation.

So assuming there aren't other blockers, such as potentially the multiplayer connection screen that vultraz mentioned, I'd be in favor of going back to a non-threaded implementation and then taking another look at how threading could be implemented safely (or if it's worth the risk of other issues coming up).

**Comment by soliton-** [comment]
> we need to keep track of where we should add spin calls. I don't see how this is an upgrade from mutexes.

You do not see how it's easier to add a couple of function calls at appropriate places and the worst that happens if you miss some is no GUI updates for a bit in contrast to not locking a critical region and getting random crashes or worse? And once you do add all the needed mutexes? Worse performance for every code path involved whether it runs concurrently to the loading screen thread or not.

The point is avoiding running large parts of wesnoth code in parallel for little gain and significant penalties in robustness (as evidenced by quite a few bugs that have cropped up since), maintainability (avoiding future bugs) and performance and instead sprinkle function calls to update the GUI in that same code. Unless you can somehow reduce the amount of code that runs in parallel to the loading screen it seems quite difficult to call threading the better design.

Regarding the multiplayer connection code I don't see why you couldn't just add a bool flag or something to pause GUI updates similarly.

**Comment by mesilliac** [comment]
As discussed on Discord previously, and as there has been no alternative provided, i'm going to push this basically as is.

I added a basic system for allowing the loading screen to animate while waiting for network data.

There will be parts that i have not marked. These will appear to "lock up". All these need is to call `loading_screen::spin()` while they are doing whatever they are doing that is taking so long.

For network connections this is usually a matter of using "wait_for" in stead of "wait", and updating the loading screen inside a loop. For file loading, this is mostly a matter of updating the loading screen inside loops that cycle many times.

**Pull request merged**
