### PR TITLE
[1.16] Remove fonts not used since SDL_ttf was replaced

### PR DESCRIPTION
**Pull request by pehjota**
The Andagii, Droid Sans Fallback, and Droid Sans Japanese fonts were mentioned in WML `[fonts][font]` tags in `data/hardwired/fonts.cfg`, which were removed along with the engine code to read them in commit e0d60b0e2bc (version 1.15.14).  That code was unused since SDL_ttf wrapper code was removed in commit 2dfdc0061d4 (version 1.15.11).

Tested by selecting the Japanese (`ja_JP`) locale with these fonts removed and no system copies installed.  Also confirmed by running wesnoth under strace before and after removing the fonts to verify that it doesn't attempt to open them.

The only remaining references to these fonts are PO file message entries from `data/hardwired/fonts.cfg` which were marked obsolete (beginning with `#~`) in commit fecfe194803 (version 1.15.14).

See also #8330 for master.

### CODE REVIEW

**Comment by stevecotton** [comment]
On the one hand I think this will be a good change for 1.17, but OTOH I don't see much reason to do this for the final release of 1.16, it seems to be a minor saving of disk space and download bandwidth. So my feeling is to take it for 1.17 but not for the backport.

**Comment by gfgtdf** [comment]
>  Also confirmed by running wesnoth under strace before and after removing the fonts to verify that it doesn't attempt to open them.

I'm pretty sure that the code just scans the directory and adds everything that it finds there, so its expected that it doesn't attempt to use something that doesn't exist.

I actually don't really know what these fonts do, but i think umc can choose a font via pango markup which would then be broken in the next 1.16 version if it for whatever  reason decided to use these. So i don't think we should do this in 1.16.

**Comment by pehjota** [comment]
> > Also confirmed by running wesnoth under strace before and after removing the fonts to verify that it doesn't attempt to open them.
> 
> I'm pretty sure that the code just scans the directory and adds everything that it finds there, so its expected that it doesn't attempt to use something that doesn't exist.

As I said, I ran strace *before* and after removing them.  Before removing them, wesnoth also didn't open them.

> I actually don't really know what these fonts do,

As @ivanovic wrote in commits 46a34091c7c, 7b8c57cd432, and 394ec392e74, the Droid Sans fonts were used for CJK languages.  And commit d5381323728 says Andagii was for the Shavian alphabet.

> but i think umc can choose a font via pango markup which would then be broken in the next 1.16 version if it for whatever reason decided to use these. So i don't think we should do this in 1.16.

Good point.  I just checked all 588 addons for 1.16 and all 141 for 1.17.  `Support_1_12_Core` for 1.16 is the only place where `grep -ERIn -- '(Droid.*Sans|Andagii)' */` returns any results, and they're only in POT and PO files.  In other words, the only mentions of these fonts in any UMC are in translations that never worked in 1.16 anyway (because the msgid from `data/hardwired/fonts.cfg` is gone).  So nothing will break.

**Comment by oo13** [comment]
Wesnoth 1.16.11 uses Droid Sans Japanese and Droid Sans Fallback, and I confirmed it by strace on Debian GNU/Linux testing.
The font specification "Lato" is translatable, and Japanese translators translate "Lato" into "Droid Sans Japanese,Droid Sans Fallback,Lato". cf. https://github.com/wesnoth/wesnoth/blob/165d2ba37f2c95257a33ab916ca254594890278d/po/wesnoth/wesnoth.pot#L3386

**Comment by pehjota** [comment]
> Wesnoth 1.16.11 uses Droid Sans Japanese and Droid Sans Fallback, and I confirmed it by strace on Debian GNU/Linux testing.

Confirmed, I must have done the before-removal `ja_JP` test (which didn't stat or open Wesnoth's `fonts/DroidSansFallbackFull.ttf` or `fonts/DroidSansJapanese.ttf`) while the fonts-droid-fallback package was still installed on my system.

> The font specification "Lato" is translatable, and Japanese translators translate "Lato" into "Droid Sans Japanese,Droid Sans Fallback,Lato". cf.
> 
> https://github.com/wesnoth/wesnoth/blob/165d2ba37f2c95257a33ab916ca254594890278d/po/wesnoth/wesnoth.pot#L3386

Ah, yeah, I missed those non-obsolete `msgstr`s in `po/wesnoth/ja.po`, `po/wesnoth/zh_CN.po`, and `po/wesnoth/zh_TW.po` among the noise of the obsolete entries in other PO files.

I guess these PRs should be closed then.  Sorry for the noise.

**Pull request closed without merging**
