### PR TITLE
[UtBS] various small things

### PR DESCRIPTION
**Pull request by doofus-01**
A mostly accurate list of changes follows, I will update as necessary:
 - S4 & S5:  some variations for scenery
 - S5:  give trolls troll camps, instead of orc castles
 - some cosmetic map changes to the dwarf-killing branch.
 - make sure dwarf sergeant is facing the right way in S6b
 - some very minor updates to Quenoth elves

... well, there is more I could add, but I'm out of time for now.  I'll pick it up again next week.

### CODE REVIEW

**Comment by doofus-01** [comment]
That last change mostly converted the underground mountains (?) with old stone wall.  I also noticed there was a graphics glitch with castle (23,47) overlapping walls in an odd way, so I replaced the castle hex with flat, which does change the defense values, mostly in favor of the player, but I doubt it is significant.

I think I'm done with this batch of little changes.

**Comment by CelticMinstrel** [comment]
Can you add the standard campaign prefix to each commit message, please? And the scenario number for commits that are specific to a single scenario.

**Comment by doofus-01** [comment]
How does one do that?

**Comment by CelticMinstrel** [comment]
Interactive rebase, and reword all the commits.

If you're using the command line, you'd run `git rebase -i master`, which brings up a text editor, and change all the "pick" to "reword". If you're not used to vim you may also need to change the preferred editor first.

**Comment by doofus-01** [comment]
Interesting.  Well, I've manged to screw my branch up.  I'll have to figure out how to change the editor, I'm not going to waste my time with vim.

I'll try to make future commit messages more standardized.  For now, easiest to just close this.

**Pull request closed without merging**
