### PR TITLE
Addon manager: Save the last sort order in a hidden preference

### PR DESCRIPTION
**Pull request by jostephd**
Is this okay? I assume there's a better way to do the conversions from SORT_ORDER to int and back.

### CODE REVIEW

**Comment by gfgtdf** [comment]
maybe we coudl implement this in the listbox widget so that is applies to all of them? like add a 'perfernce_id' field to the listboxs wml and if its present the code will automaticially save the sorting order.

**Comment by jostephd** [comment]
Good idea, but unfortunately, it's not a `listbox`. It's an `addon_list`, that's actually a separate class:

https://github.com/wesnoth/wesnoth/blob/c939d13711767389c100a472bac765a96a74107f/src/gui/widgets/addon_list.hpp#L36

What do you suggest then? Maybe we do what you propose for the `menu_button`. Or maybe we can make the addon_list a subclass of listbox, or of a superclass of listbox, I haven't looked into that.

**Comment by gfgtdf** [comment]
> Good idea, but unfortunately, it's not a listbox. It's an addon_list, that's actually a separate class:

but the addon_list contains a listbox, so it might still work?

https://github.com/wesnoth/wesnoth/blob/c939d13711767389c100a472bac765a96a74107f/src/gui/widgets/addon_list.cpp#L358

**Comment by jostephd** [comment]
> but the addon_list contains a listbox, so it might still work?

In this case, which widget do you think the preference_id facility should be added to, listbox or menu_button?

**Comment by Wedge009** [comment]
If I understand this change correctly, I think it can resolve #1090.

**Comment by jostephd** [comment]
Indeed.

**Comment by Pentarctagon** [comment]
@gfgtdf Is this mergable?

**Comment by gfgtdf** [comment]
I'd say yes

**Comment by Pentarctagon** [comment]
Alright, if it's mergable, please do that.  If not, @stevecotton are you planning to take this one over as well?

**Comment by stevecotton** [comment]
> Is this okay? I assume there's a better way to do the conversions from SORT_ORDER to int and back.

There's a MAKE_ENUM macro, which provides strings for saving the preferences and was used by the SCALING_ALGORITHM preference; see 15bf3bb25691c6ce71ac2a45bb4e5c06ea9239e6.

> Alright, if it's mergable, please do that. If not, @stevecotton are you planning to take this one over as well?

I'm investigating now. I'll either complete it or will push an improved version to help the next developer.

**Comment by stevecotton** [comment]
Reopened as #5284, as it's now a branch in my fork instead of in @jostephd 's.

**Pull request closed without merging**
