### PR TITLE
Filter weapon in [filter student/opponent/etc] and rework [filter_(second_)weapon(pre 1.16 string)

### PR DESCRIPTION
**Pull request by newfrenchy83**
this is the third request for resolve https://github.com/wesnoth/wesnoth/issues/4389.

This time [filter(_second)_weapon] code is reworked and new syntax have priority.

### CODE REVIEW

**Comment by newfrenchy83** [comment]
@CelticMinstrel or @jostephd can you review this PR please?

**Comment by newfrenchy83** [comment]
@jostephd i added a test case in scenario-test for 4 type of abilities, [leadership],[resistance] special bool abilities and special value abilities

**Comment by newfrenchy83** [comment]
@CelticMinstrel or @Vultraz could you review this PR because jostephd don't have time, and i fear else what this is not merged before 1.16 scripting

**Comment by CelticMinstrel** [comment]
I don't see any obvious problems, other than needing a wmlindent run… there's at least one spelling error in the test scenario, but it's the test scenario so it doesn't matter so much.

If someone (maybe @wedge009 ?) has time to test it and verify it all works properly and maybe even verify that nothing breaks, I don't mind doing the work of merging it.

**Comment by Wedge009** [comment]
I test things that I know how to test. I don't really know too much about WML stuff, but if you tell me what I'm supposed to be looking for I can try.

**Comment by newfrenchy83** [comment]
@Wedge009 Here, three things must be tested,

1. That the rewrite and reimplementation of the code for [filter_ (second_) weapon] in leadership, resistance, bool special abilities and value special abilities did not affect the operation of the filter

2. that the new syntax of [filter_weapon] in [filter_ (student, opponent, attacker, defender)] works perfectly

3. that the new syntax remains a priority over the old one

For this I enclose a text file in the comment with the main cases, for the test, implement each abilitie in a unit, start the game, and test the unit (or adjacent units) in combat to check the cases previously describing.
[abilities_weapons.txt](https://github.com/wesnoth/wesnoth/files/3825168/abilities_weapons.txt)

**Comment by CelticMinstrel** [comment]
So for the first point, I assume that's equivalent to testing that leadership still works correctly in every possible situation.

I notice a bunch of units with these new abilities in the test scenario, so that might be helpful for the testing. Otherwise I guess editing some campaign temporarily with the abilities newfrenchy posted in that text file?

Note: I don't think that text file should be in the repository. My suggestion is to put those sample abilities on the wiki somewhere.

**Comment by newfrenchy83** [comment]
@CelticMinstrel  @Wedge009 l I have added changelog entry to this PR

**Comment by newfrenchy83** [comment]
@CelticMinstrel @Wedge009  I had to repair the unit status bar but now [filter (_second) _weapon] is active on the status bar, and when [filter_student] is used without including the enemy unit, the value of the damage displayed corresponds to that calculated by [damage] abilitie. (also [filter_attacker / defender] when the right conditions are met). This PR must be chek all manual testing now.

**Comment by newfrenchy83** [comment]
i added filter_student to regular leadership and resistancde for reply to https://github.com/wesnoth/wesnoth/issues/4389#issuecomment-557534405

**Comment by newfrenchy83** [comment]
@CelticMinstrel @jostephd someone could add this PR to https://github.com/wesnoth/wesnoth/milestone/20 milestone

**Pull request closed without merging**
