### PR TITLE
EI: preserve XP when Dacyn receives scripted advancements

### LINKED ISSUE #8702: EI: Allow Dacyn to Retain Experience When Changing Unit Type
### Describe the desired feature

In S14 The Drowned Plains and S16 Eleventh Hour, Dacyn switches unit type. 
Dacyn retains any existing AMLAs and their percentage increase in total experience, but his experience is set to zero. 

EI has custom AMLAs which are much stronger (8HP instead of 3HP on a unit with base 47HP) so losing experience is a meaningful loss and a new player doesn't have any way of knowing this.

### PR DESCRIPTION
**Pull request by Dalas121**
Resolves #8702

### CODE REVIEW

**Comment by Wedge009** [comment]
I haven't tested this, but the macro additions make sense to me. Thanks again for the quick resolution.

**Comment by Wedge009** [comment]
FYI, if you include 'resolves/closes/fixes/etc <issue number>' in your commit message, GitHub will automatically link your PR to the issue concerned, which closes the issue when the PR is merged to master.

I'll mark this for back-porting to 1.18.

**Comment by Dalas121** [comment]
> FYI, if you include 'resolves/closes/fixes/etc [issue number]' in your commit message, GitHub will automatically link your PR to the issue concerned, which closes the issue when the PR is merged to master.

Excellent, thanks for telling me about that.

**Comment by stevecotton** [comment]
While this is an improvement, it seems to ignore the possibility that he already has an AMLA.

**Comment by Dalas121** [comment]
If Dacyn already has AMLAs, they're automatically carried over through `{ADVANCE_UNIT}` without needing any special handling.

**Comment by Wedge009** [comment]
@Dalas121 Are you going to back-port to 1.18 branch? Should just be a matter of cherry-picking f657a3654908eea264004f124e7970221bc7b265.

**Comment by Dalas121** [comment]
Complete beginner to github, thanks for your patience!

I'm currently using the github web UI for everything, and it looks like that doesn't support cherry-picking, but I can open a separate PR on the 1.18 branch (as you suggested in the other PR), so I'll do that

**Pull request merged**
