### PR TITLE
Tutorial damage dealt numbers fixes

### PR DESCRIPTION
**Pull request by Earth-Cake**
There have been "irregularities" in damage dealt numbers, depending on was an elf strong / dexterous, or not. If unit has strong / dexterous trait, attack damages are adjusted, which wasn't included in tutorial text before.

### CODE REVIEW

**Comment by Wedge009** [comment]
I wonder if it's worth blocking strong/dexterous traits for these units but this seems more elegant. I assume it's always the case that attack[0] is melee and attack[1] is ranged.

**Comment by CelticMinstrel** [comment]
> I assume it's always the case that attack[0] is melee and attack[1] is ranged.

It depends on the unit of course, but it's true for the Elvish Fighter, at least, which is all that matters here.

**Comment by Earth-Cake** [comment]
Since there is no better way, I guess we should keep it as it is, on basic damage.

**Comment by Earth-Cake** [comment]
There is another way, instead of using variables (which may cause some issues when trying to translate lines):
`        [event]
            name=attack_end
            [filter]
                type=Elvish Fighter
            [/filter]
            [filter_attack]
                name=sword
            [/filter_attack]

            [if]
                [have_unit]
                    id=$unit.id
                    trait=strong
                [/have_unit]
                [then]
                    [message]
                        speaker=Delfador
                        message= _ "Your elf used a sword (6×4; or 6 damage on each hit, with 4 attacks), which is a <i>melee</i> attack. The quintain defended with its melee attack (3×5; or 3 damage on each hit, with 5 attacks). The ranged attack (the bow) would have been safer."
                    [/message]
                [/then]
                [else]
                    [message]
                        speaker=Delfador
                        message= _ "Your elf used a sword (5×4; or 5 damage on each hit, with 4 attacks), which is a <i>melee</i> attack. The quintain defended with its melee attack (3×5; or 3 damage on each hit, with 5 attacks). The ranged attack (the bow) would have been safer."
                    [/message]
                [/else]
            [/if]
        [/event]
`
With this code there should be no unnecessary complications.

**Comment by CelticMinstrel** [comment]
> (which may cause some issues when trying to translate lines)

Variables shouldn't really cause issues when trying to translate lines? Aren't the translators already more or less aware of how variables work?

**Comment by Wedge009** [comment]
Depends on the translator (remember some aren't/weren't aware of the prefix^ notation).

**Comment by jostephd** [comment]
> Variables shouldn't really cause issues when trying to translate lines?

In general, variables shouldn't be used in translatable strings. See https://forums.wesnoth.org/viewtopic.php?f=8&t=11445

**Comment by CelticMinstrel** [comment]
I see the point of that post, but at the same time, if you need to interpolate variable data into a translatable string, you _must_ use a variable.

**Comment by stevecotton** [comment]
Given that there are a very limited set of values that the variable could take, maybe we should also add a translator hint about the size of the number?

```
# po: the damage will be 5 or 6, depending on whether the unit has the strong trait
```

**Comment by jostephd** [comment]
> I see the point of that post, but at the same time, if you need to interpolate variable data into a translatable string, you _must_ use a variable.

But you don't need to incorporate variable data in this case. See @Earth-Cake's solution.

**Comment by stevecotton** [comment]
> But you don't need to incorporate variable data in this case. See @Earth-Cake's solution.

@Earth-Cake, will you update the PR to use that method? It can be simplified, `[filter_attack]` has a `damage=` option.

Thanks,
Steve

**Comment by Earth-Cake** [comment]
What method are you referring to? With `trait=strong` or with way you mentioned above?

**Comment by stevecotton** [comment]
I mean, using one string containing "Your elf used a sword (5x4..." and a separate string for "Your elf used a sword (6x4..."

**Comment by Earth-Cake** [comment]
Uhh... I forgot I had to delete this branch. Here is the right code:

```        [event]
            name=attack_end
            [filter]
                type=Elvish Fighter
            [/filter]
            [filter_attack]
                name=sword
            [/filter_attack]

            [if]
                [have_unit]
                    id=$unit.id
                    trait=strong
                [/have_unit]
                [then]
                    [message]
                        speaker=Delfador
                        message= _ "Your elf used a sword (6×4; or 6 damage on each hit, with 4 attacks), which is a <i>melee</i> attack. The quintain defended with its melee attack (3×5; or 3 damage on each hit, with 5 attacks). The ranged attack (the bow) would have been safer."
                    [/message]
                [/then]
                [else]
                    [message]
                        speaker=Delfador
                        message= _ "Your elf used a sword (5×4; or 5 damage on each hit, with 4 attacks), which is a <i>melee</i> attack. The quintain defended with its melee attack (3×5; or 3 damage on each hit, with 5 attacks). The ranged attack (the bow) would have been safer."
                    [/message]
                [/else]
            [/if]
        [/event]

        [event]
            name=attack_end
            [filter_attack]
                name=bow
            [/filter_attack]

            [if]
                [have_unit]
                    id=$unit.id
                    trait=dextrous
                [/have_unit]
                [then]
                    [message]
                        speaker=Delfador
                        message= _ "Your elf used a bow, which is a <i>ranged</i> attack (4×3; or 4 damage on each hit, with 3 attacks). The quintain has no ranged attack, only a melee attack, so it could not defend itself."
                    [/message]
                [/then]
                [else]
                    [message]
                        speaker=Delfador
                        message= _ "Your elf used a bow, which is a <i>ranged</i> attack (3×3; or 3 damage on each hit, with 3 attacks). The quintain has no ranged attack, only a melee attack, so it could not defend itself."
            	    [/message]
                [/else]
            [/if]
        [/event]```

@stevecotton can you merge it?

**Comment by stevecotton** [comment]
Hmm - would `"Your <i>strong</i> elf used a sword..."` be better? It would explain why the numbers changed from the preceding "And which would that be? The sword (5×4; or 5 damage on each hit, with 4 attacks) or the bow (3×3; or 3 damage on each hit, with 3 attacks)? I suppose you’ll find out..."

**Comment by jostephd** [comment]
> would `"Your <i>strong</i> elf used a sword..."` be better?

I think putting the word _strong_ like that would only work after introducing traits, but traits haven't been properly introduced by this point.

How about doing two lines:

```
if strong:
    "Your elf used a sword (6x4...)"
    "Elvish Fighters normally do 5x4 damage, but this elf has the _strong_ trait, which increases the damage output of melee attacks."
```

and then, if the elf isn't strong, speak about another trait which it does have. Or alternatively, use a `recruit` event to force particular traits to the first two recruits.

**Comment by stevecotton** [comment]
Thanks, I like the idea of two lines to explain the trait. But if the elf doesn't have that trait, I'm not going to add extra dialogue, we don't have any discrepancy in the numbers to explain.

**Comment by stevecotton** [comment]
Merged in b408a155b31

**Comment by jostephd** [comment]
> But if the elf doesn't have that trait, I'm not going to add extra dialogue, we don't have any discrepancy in the numbers to explain.

My thinking was to make sure that the same material is covered regardless of whether either recruit happened to have received the `strong` trait. I do see that trying to put that explanation there when the fighter/archer _doesn't_ have the respective trait could be a bit awkward, though... :thinking:

**Comment by stevecotton** [comment]
It can also be added later in the tutorial, maybe in a later scenario. Taking advantage of it sounds like it would be a Tactics Puzzle.

**Comment by jostephd** [comment]
Fair enough. And we should cover resistances at some point too...

**Comment by AI0867** [comment]
I vaguely recall the tutorial using fixed-trait or no-trait units in some places, specifically to avoid these complications.

**Comment by CelticMinstrel** [comment]
Um, I think you missed something here? What about the dexterous trait?

**Comment by stevecotton** [comment]
Dextrous is handled in b408a155b313577b735234ecc8c50f0f57f51973.

I didn't miss a 'e' - in en_US and in the trait's id, it's spelt with only one 'e'.

**Comment by CelticMinstrel** [comment]
Oh, okay. I'm not sure how I missed the dextrous case there... >_>

**Pull request closed without merging**
