### PR TITLE
Fixed Warden’s and Arbiter’s animations popping on water tiles

### LINKED ISSUE #6508: [Graphics] Drake Arbiter/Warden pop outside of map hex when attacking or defending.
## Wesnoth Version
1.17.0+dev

https://cdn.discordapp.com/attachments/259976436490829825/939623417882226748/IQ-Clash_of_the_Drakes_Turn_7.2.gz
(requires Inky's Quest to be installed)

Observed Here:
Video: https://www.twitch.tv/videos/1288191641
TimeStamp: 20:24

Reproduce:
1. Spawn Drake Arbiter on a ford/shallow water hex
2. Observe it being attacked and defending.
3. Observe it retaliate in attack
4. It can be seen he is levitating on water

(Not observed for Drake Clasher/Thrasher/Enforcer)

image

Reported by @Konrad22

### PR DESCRIPTION
**Pull request by Descacharrado**
Will add animation gifs if needed. Needs more testing. Diff says there were deletions even tho  there were no deletions, only additions and code repositioning.

Closes #6508 
Addresses my request in #6475 (my name should be deleted from that issue when backported)

### CODE REVIEW

**Comment by doofus-01** [comment]
Sorry, I'll have to review this next weekend.  Glancing at the changes, I don't see anything obviously wrong.  If there is some hurry, I'm OK with someone else verifying and merging.

**Comment by Descacharrado** [comment]
> Sorry, I'll have to review this next weekend. Glancing at the changes, I don't see anything obviously wrong. If there is some hurry, I'm OK with someone else verifying and merging.

There is never a hurry on my side, but thank you for letting me know.

**Comment by Pentarctagon** [comment]
@doofus-01 reminder to review this.

**Comment by doofus-01** [comment]
Noted.  Will do it this weekend (for real this time).

**Comment by doofus-01** [comment]
This might be nit-picking, but it looks like one can avoid the copy-paste by just inserting 
```
        [if]
            terrain_type=W*,S*
            submerge=0.4
        [/if]
```
into the existing animations.  Would you be willing to give that a try, @Descacharrado ?

**Comment by Descacharrado** [comment]
Sure, seems smarter, I'll try it soon.

**Comment by Descacharrado** [comment]
Huh, seems like GH did not liked me rebasing locally, I'll close and reopen the PR.

**Pull request closed without merging**
