### PR TITLE
fix chat focus loss when re-assigning sides

### PR DESCRIPTION
**Pull request by vgaming**
Fixes GH-2817

Patch originally provided by @jostephd at github: https://github.com/wesnoth/wesnoth/issues/2817

### CODE REVIEW

**Comment by vgaming** [comment]
This PR targets the master branch, but it is also safe to use it on 1.14, because the change is UI only. I can write a PR for 1.14, or a cherry-pick will probably work, if needed.

**Comment by vgaming** [comment]
I tested the change locally BTW, I think it works.

**Comment by Wedge009** [comment]
I don't really know UI code that well, but it's just a one-line change and if it appears to solve the issue, great. Just a question of whether there's any unintended side-effects, which I'll let the experts determine.

**Comment by Wedge009** [comment]
Oh, I see from #2817 that the down-side is the loss of up/down keyboard control. I'm not sure of the practical impact of that (from a user's perspective) as I don't use MP lobby much (outside of testing).

**Comment by AI0867** [comment]
Is the originally selected widget still available at the start of this function? Re-selecting that would probably be the optimal solution.

A more complicated one would be having some sort of keyboard input pre-processor for the entire window that automagically selects the right target depending on what keys you're pressing and maybe which keyboard-sensitive buttons you last touched, but that sounds like a lot of work.

**Comment by Pentarctagon** [comment]
Is the current implementation an acceptable solution?  If it is, and no one is going to implement a different one, then this can be merged, correct?

**Comment by Wedge009** [comment]
I think that's the concern - that there's some side-effects that may be undesirable but no-one has anything better at the moment, that I can tell. I don't really have an opinion either way, I don't use MP outside of testing. But if it comes to a decision, I'd say go for it rather than letting it languish, unless someone has a compelling reason not to merge.

**Comment by gfgtdf** [comment]
I don't really know this code, but it looks like it's now randomly capture the chatbox even if it wasn't captured before? What's the point of the line in the first place (meaning: what happens if you just remove it)

**Comment by Pentarctagon** [comment]
Closing as it's been a while and nobody seems to know if this is the correct fix or not.

**Comment by vgaming** [comment]
Oh that's really sad.. Right now, each time you re-assign a side there's just focus loss for observers. Even if the proposed solution is not the best one, it's 100% better than the current state I think.

Should we triage it from this perspective? Will the patch make the situation better or worse?

In theory, I think the concern is that you could lose focus on whatever else you have as an observer when the host re-assignes sides. That's definitely better than losing the focus anyway, but make it go away from the chat as well.

Thoughts?..

**Comment by soliton-** [comment]
> I don't really know this code, but it looks like it's now randomly capture the chatbox even if it wasn't captured before? What's the point of the line in the first place (meaning: what happens if you just remove it)

Looks to me like before it set keyboard focus on the whole tree_view and now only on the chat_box.

Presumably when the whole tree_view has the focus then stuff like the side changes moves the focus to whatever widget is involved in that because it's part of the tree_view. Now when it's only set on the chat_box it ignores those other changes as far as focus is concerned.

I suppose ideally whenever those side changes are done it should remember where the focus was and set it back or maybe there is a way to not disable focus changes.

That said if the only negative side effect of this is that the up/down arrows don't scroll the sides list then it sounds like a good trade for not interrupting typing chat messages. Wesnoth cannot be completely controlled by the keyboard anyway.

**Comment by Pentarctagon** [comment]
If a decision is reached by the way, feel free to reopen this and merge it.

**Pull request closed without merging**
