### PR TITLE
Fade out music on scenario start and on disabling it

### PR DESCRIPTION
**Pull request by jyrkive**
@Vultraz requested something like this in IRC.

> 20160730 12:44:41\< vultraz\> JyrkiVesterinen: I have a small task for you, if you're up to it: make it so music fades out (such as when you toggle it off, or a scenario ends) instead of stopping abruptly.

I implemented fading out when the player disables music in preferences. I also edited the SCENARIO_MUSIC and INTRO_AND_SCENARIO_MUSIC macros by turning on fade-out of previous music (i.e. the storyscreen music) when the scenario starts.

I assume that the "scenario ends" condition @Vultraz mentioned means the victory or defeat situation, when the game plays the victory/defeat music. I didn't implement fade-out of previous music in that situation because I *oppose* it. (I prefer the "abrupt" switch to the victory/defeat music.)

### CODE REVIEW

**Comment by Vultraz** [comment]
Well, I was referring to the cases when there isn't victory/defeat music to play, such as if someone were doing a cutscene scenario. In the case of the victory/defeat music, I agree the sudden change makes sense.

**Comment by jyrkive** [comment]
How can I make a "cutscene scenario"? [[endlevel]](http://wiki.wesnoth.org/DirectActionsWML#.5Bendlevel.5D) with `result=victory` and `music` explicitly cleared? Alternatively, can you point me at an existing cutscene scenario?

**Comment by jyrkive** [comment]
I now know that one can create a cutscene scenario by using `[endlevel]` with `carryover_report=no` and `linger_mode=no`. I'm using LoW scenario 8 (Council of Hard Choices) for testing now.

It turned out that the game *does* play the victory music at the end of cutscene scenarios. You may not notice it if the game enters the next scenario fast enough.

I think that, together with the changes I have already done, disabling the victory music in cutscene scenarios would be enough to get the music to fade out when a cutscene scenario ends.

I'm not going to do it today, mind you. I got sidetracked chasing a bug.

**Comment by jyrkive** [comment]
I implemented fading out the previous music when any scenario without carryover report ends.

Do you want anything else, or are these changes enough?

**Pull request merged**
