### PR TITLE
Fix ambiguous ternary operator (fixes #4153 compile error with GCC)

### LINKED ISSUE #4153: Refactor team_data usage cause a bug in travis validation
the https://github.com/wesnoth/wesnoth/commit/5320c7120d3914f05fda793c7c1f8d67b5f6e5d9 commit,
in  src/gui/dialogs/game_stats.cpp:132; the code cause an error in travis validation. See https://travis-ci.org/wesnoth/wesnoth/jobs/554732225#L565. how repait this please?

### PR DESCRIPTION
**Pull request by stevecotton**

### CODE REVIEW

**Comment by stevecotton** [comment]
@Vultraz `column_stats["label"]` is a `t_string`, so I think this method is better than 7705d24

**Comment by stevecotton** [comment]
Fixed in the other way

**Comment by Vultraz** [comment]
Fair point, but we haven't really made the same consideration in other places. I honestly don't even think about that being a t_string most of the time. 😬

**Comment by CelticMinstrel** [comment]
I too think the other way's better - once something's a t_string it should generally stay as a t_string forever. In fact it was probably a bad idea to allow implicit conversions between the two string types.

**Pull request closed without merging**
