### PR TITLE
add an optional delay argument to scroll.

### LINKED ISSUE #8276: QUAKE macro doesn't shake the screen anymore
### Game and System Information

- **Version:** 1.17.24
- **Downloaded from:** AUR
- **Build info:** 80da6fd
- **OS:** Manjaro Linux
- Tested on two separate computers with different resolution displays

### Description of the bug

QUAKE macro still plays the assigned sound, but it's scrolling feature simulating shaking doesn't seem to be working anymore, at least on Linux using X.org. 

### Steps to reproduce the behavior

1. Launch the final scenario of The Sceptre of Fire, Caverns of Flame
2. Kill Toomak, the troll hero leader to trigger the QUAKE macro
3. The screen doesn't shake

### Expected behavior

1. Launch the final scenario of The Sceptre of Fire, Caverns of Flame
2. Kill Toomak, the troll hero leader to trigger the QUAKE macro
3. The screen shakes

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Pentarctagon**
Fixes #8276

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Needs a schema entry for the new WML key. Also, I think "delay" may not be the best name for the key. Maybe "duration" or something? In the future we could make it also affect the speed of scrolling, instead of just being a delay.

**Comment by Pentarctagon** [comment]
I think there'd need to be another attribute for speed of scrolling. This is how long to delay after the scrolling is complete.

**Comment by Wedge009** [comment]
Does this add a delay on top of a manual call to `[delay]`, eg `MEMOIRS_TREMOR`?
https://github.com/wesnoth/wesnoth/blob/88befc29de91eeda13ce11a4620fbf642a215c55/data/campaigns/Delfadors_Memoirs/utils/misc.cfg#L74-L108

**Comment by CelticMinstrel** [comment]
> This is how long to delay after the scrolling is complete.

1. That's not something that really belongs here.
2. Is that really what your code is doing in the first place? Is the scrolling finished when `game_display_->scroll` returns? I thought the bug came to exist because it _wasn't_ finished at that point in time.

**Comment by Pentarctagon** [comment]
@Wedge009 it would be additive, yes.

@CelticMinstrel The reported bug is that the draw manager now executes all the scrolls immediately, so it appears as if no shaking is happening because you end up at the same place you started from. For that to happen, you need there to be a long enough delay between scrolls so that players can see the movement.

**Comment by CelticMinstrel** [comment]
> For that to happen, you need there to be a long enough delay between scrolls so that players can see the movement.

I feel like you're misunderstanding a key point here. It's not that we want a delay between scrolls, but rather that we one one scroll to complete before beginning the next. From what I can tell, it looks like the scroll() call gets a scroll started which then continues asynchronously, so this delay you're adding is not a "delay between scrolls". A "delay between scrolls" would measure from the end of one scroll to the beginning of the next, but this delay is measuring _beginning_ to beginning, isn't it? In other words, it's not "time between scrolls" but rather "time allotted to allow the scroll to complete".

That's also why I though it should be added entirely internal to the scroll function (not with a new parameter like you've done) – because the time a scroll takes to complete depends on how far you're scrolling.

I'm making some assumptions here derived from what other people have said, and I haven't taken the time to verify that they're all correct. So it's possible that I've said something wrong. Feel free to try to verify the assumptions yourself.

**Comment by Pentarctagon** [comment]
Using scroll to make the screen shake would means you need to: move -> stop long enough for the player to see it -> move -> stop long enough for the player to see it -> etc. That's what this does - it calls the scroll function (move) -> stops long enough for the player to see it (delay) -> etc.

This delay happens after the end of one scroll and before the start of the next scroll.

**Comment by CelticMinstrel** [comment]
Something seems off about that explaination. The movement itself takes time, does it not? That should be enough for you to see it. It also doesn't quite seem correct to delay _between_ scrolls for a quake – you want the second scroll to immediately follow the first, don't you? Of course, that's assuming that you saw the motion of the first while it was happening, though… which from what I've heard is the part that's missing here.

**Comment by Pentarctagon** [comment]
> The movement itself takes time, does it not? That should be enough for you to see it.

If that were the case, then the issue opened wouldn't say that the "QUAKE macro doesn't shake the screen anymore". Or at least the time it takes to do the movement is also imperceptible, given how small the values QUAKE uses are.

**Comment by CelticMinstrel** [comment]
> If that were the case, then the issue opened wouldn't say that the "QUAKE macro doesn't shake the screen anymore". Or at least the time it takes to do the movement is also imperceptible, given how small the values QUAKE uses are.

It feels like you're missing the point again.

Logically speaking, it should be obvious that scrolling the screen takes time. It's not like it's supposed to instantly warp to the new position, right? (If it was, then your approach might make more sense.)

However, the motion isn't observed when multiple scrolls are used in succession. So, does that mean the motion is instant? Or does it mean it's not even moving at all?

Isn't it possible that the scroll function does not, in fact, scroll the screen?

Obviously, it needs to somehow cause the screen to scroll, in order to live up to its name. But that's not necessarily an immediate observable effect.

Isn't it possible that all it does is assign a "target view location"? The game will then leisurely scroll towards the new target location. However… if that's how it's implemented, what would happen if you call it twice with values that cancel each other out?

The answer is: exactly what was observed. The "target view location" never changed, so no scrolling occurred.

I haven't verified these points, to be clear. They're just what I view as the most likely scenario based on what everyone has said. Some or all of what I'm saying could be wrong.

**_However_**…

If we're going to add new API (a new argument to the Lua function, or a new WML key) based on the understanding of how it works, we need to be sure that the understanding is correct. Adding a key that's supposed to do one thing but actually does something quite different (even if the difference is subtle in the common use cases) doesn't strike me as a good idea.

**Comment by Pentarctagon** [comment]
I think most of your speculation/questions can be answered by testing it out yourself. Otherwise I don't see the point of spending a ton of time doing a deep dive on the implementation details when we have a solution that works and is incredibly simple and straight forward.

**Comment by CelticMinstrel** [comment]
If you don't want to spend time diving in to figure out how it really works, then we should be fixing it in a way that doesn't involve adding something potentially misleading to the API.

Whether it's a hard-coded 25 seconds or using the scroll distance to calculate a delay, I think that's a better solution than new API where you don't actually know what it does.

**Comment by Pentarctagon** [comment]
It's not misleading though? The `delay` attribute literally does a delay.

**Comment by Wedge009** [comment]
> Isn't it possible that all it does is assign a "target view location"? The game will then leisurely scroll towards the new target location. However… if that's how it's implemented, what would happen if you call it twice with values that cancel each other out?

I don't profess to know much about the details of how all of this is implemented, and I appreciate trying to avoid adding something to correct symptoms that may inadvertently just cause more confusion later on because the changes being made now are based on an incomplete or inaccurate understanding of the current implementation.

Just thought I'd point out - if it wasn't already known - that there are `[scroll]` actions, for moving the screen in relative terms and `[scroll_to]` actions which move the screen in absolute terms. If you're interested in testing/investigating, I suppose you could re-implement an example of a 'shake' animation with a series of `[scroll_to]` actions and see what happens as a result.

**Comment by CelticMinstrel** [comment]
> It's not misleading though? The `delay` attribute literally does a delay.

It's potentially misleading when you don't even know what scroll() actually does.

If scroll() literally scrolls, blocking input while the screen moves, then it's not misleading. It's just a delay between scrolls.

If scroll() schedules a scroll to begin asynchronously, then it's misleading. It's not a delay between scrolls but instead a duration allotted within which the scroll is expected to complete.

**Comment by CelticMinstrel** [comment]
> I think most of your speculation/questions can be answered by testing it out yourself.

Sure, but I'm also not the one trying to add new API without understanding what it does.

**Comment by CelticMinstrel** [comment]
> Just thought I'd point out - if it wasn't already known - that there are `[scroll]` actions, for moving the screen in relative terms and `[scroll_to]` actions which move the screen in absolute terms. If you're interested in testing/investigating, I suppose you could re-implement an example of a 'shake' animation with a series of `[scroll_to]` actions and see what happens as a result

While that would be fine as a quick test, a shake can't really be done that way, so it's not a solution.

**Comment by Pentarctagon** [comment]
> If scroll() schedules a scroll to begin asynchronously, then it's misleading. It's not a delay between scrolls but instead a duration allotted within which the scroll is expected to complete.

That doesn't make any sense - rendering isn't done asynchronously in the first place.

**Comment by CelticMinstrel** [comment]
> That doesn't make any sense - rendering isn't done asynchronously in the first place.

Whether it makes sense or not, it fits perfectly with the observed symptoms. Also, it's entirely possible for scrolling to be handled asynchronously even if rendering in general isn't.

**Comment by Pentarctagon** [comment]
To test it out then, for:
```
[event]
    name=turn 1
    [scroll]
        x=500
        y=0
    [/scroll]
    [scroll]
        x=-100
        y=0
    [/scroll]
    [scroll]
        x=500
        y=500
    [/scroll]
    [scroll]
        x=0
        y=-100
    [/scroll]
    [scroll]
        x=0
        y=500
    [/scroll]
[/event]
```
all the "scrolls" happens instantly. Which is consistent with the bug report - if it took time to move to the new location indicated by [scroll], there would be time to see that movement.

**Comment by CelticMinstrel** [comment]
If you use only one scroll, does that also happen instantly?

**Comment by Pentarctagon** [comment]
Yes.

**Comment by CelticMinstrel** [comment]
You mean it warps instantly from the old scroll position to the new one?

**Comment by Pentarctagon** [comment]
Correct.

**Comment by CelticMinstrel** [comment]
Then, this PR doesn't even fix the actual issue, right? There should be a smooth movement when scrolling. Perhaps restoring the smooth movement would be enough to fix the issue? Though obviously that depends on whether scroll() is asynchronous or not.

**Comment by Pentarctagon** [comment]
It is not asynchronous, it just calls `display::scroll` which directly calls `draw::blit`.

I will check if it happens in 1.16, but given the wiki states that [scroll] is useful for earthquake/shaking effects while [scroll_to]/[scroll_to_unit] have the `immediate` attribute which determines "whether to instantly warp to the target hex regardless of the scroll speed setting in Preferences", my assumption is that [scroll] has never had smooth movement.

**Comment by Pentarctagon** [comment]
In 1.16 it's also instant.

**Comment by CelticMinstrel** [comment]
Okay, that's weird, but not really the issue then.

It makes it less clear why it suddenly stopped working, though. What changed to make quakes stop working since 1.16? Well… my new guess would be that rendering took long enough to cause enough of a delay to see the move.

I think something like "a delay between scrolls" shouldn't be part of the scroll function. If you want a delay between scrolls, you call scroll, and then you call delay. However, fixing the observed bug probably requires putting _something_ in the scroll function, as it needs to be fixed not only in mainline but in any addons that rely on it.

So, I think we should do one of these:
* Just put a delay, don't expose it as a customizable parameter.
* Name the parameter "duration" and document it as "a duration allotted for the scrolling". In the future we could use that duration to adjust the speed of the scrolling, but for now it would just be a delay.
* Add a "speed" parameter instead of time. For now, translate it to a delay by dividing the scroll distance by the speed. In future, it would set the speed of scrolling and the delay would be removed because the scrolling itself takes time.

But honestly, since we're this close to release, the first method that doesn't add any API is probably the best.

**Comment by Pentarctagon** [comment]
Alright, updated.

**Comment by gfgtdf** [comment]
(disclaimer: The discussion here is a really long and i didn't read most of it)

Imo making it possible to scroll instantly ("set position"-like, what appeareantly is what scroll() did  during most of 1.17  ) is sometimes desired sometimes and should be possible. (although i agree that is probably a bad idea to add parameter so shortly before a stable release, when we aren't sure that they are gong  stays this way)

Maybe it would, to stay closer to the 1.16 behavior, make sense to call `events::draw();` instead of delay , at least thats what scroll_to with warp=yes does.


If we add a "speed" parameter (not now but in 1.19) we should also think about how it should behave with accelerated animation speed, also i think it would make sense if the api is consistent wit the scroll_to function.

Currently we have 
- [scroll_to] position in wesnoth coodinates, scrolls "smoothly", by default and has a parameter to "warp"
- [scroll] position in pixels,  always warps

**Comment by CelticMinstrel** [comment]
> we should also think about how it should behave with accelerated animation speed

The obvious answer would be to interpret the speed as a multiplier applied to the speed configured in preferences. Want it to scroll fast? Set speed to 2. Want it to scroll slowly? Set speed to 0.5.

Maybe there could be an option to ignore the user's setting as well; we have that in the delay function, after all. I'm not sure if that's a good idea or not.

> Maybe it would, to stay closer to the 1.16 behavior, make sense to call `events::draw();` instead of delay , at least thats what scroll_to with warp=yes does.

If this works, it may well be better than the delay, yeah. The delay is fine for a quick fix though, in my opinion.

**Comment by Pentarctagon** [comment]
Any issue with me merging this?

**Comment by Wedge009** [comment]
> Currently we have
> 
>     * [scroll_to] position in wesnoth coodinates, scrolls "smoothly", by default and has a parameter to "warp"
> 
>     * [scroll] position in pixels,  always warps

I wasn't aware of the 'warp' aspect. It does explain why the net result of `[scroll]` when used as a 'shake' is practically nothing with the new draw manager.

I don't have any objections to merging but I intend to check through the `[scroll]` instances I found while creating #8283 - both ones with built-in `[delay]`s and those without. We may need to remove those `[delay]`s if the additional 25 ms (if I understand the change correctly) slows things down too much.

**Comment by Pentarctagon** [comment]
My thought is that the existing delays were already there beyond the implicit delay that existed in 1.16, so since this change is a replacement for that implicit delay, then there's be no impact to anywhere that was already adding an explicit delay.

**Comment by CelticMinstrel** [comment]
> Any issue with me merging this?

I'm okay with it as-is. It's a little hacky, and your code looks a touch bizarre from my perspective (in that I would've written it slightly differently), but there's nothing fundamentally wrong with it, and it does fix the stated issue.

**Comment by Wedge009** [comment]
I note two animations that previously already worked in master because they had their own built-in `[delay]`s interleaved with the `[scroll]`s:
* Introduction for DM S10
* Introduction for SotA S20

In both cases, there appears to be a slightly longer delay after this change... but it's really subtle and probably not noticeable. The only remark I have is that SotA S20's animation added 150 ms of delay, so maybe the addition of the 25 ms on top of that is a bit much... but again, it's really subtle and it's probably fine as it is.

**Pull request merged**
