### PR TITLE
Fix for 21634

### PR DESCRIPTION
**Pull request by binarycoder**

### CODE REVIEW

**Comment by gfgtdf** [comment]
the 'prevLabel' variable is only used in one file but has external linkage, this can be fied in multiple ways:
1) add a anonamous namespace in it (`namespace { int prevLabel = 0; }`)
2) make it  emember variable of the dosplay class

usually i'd prefer version (2) but since add_floating_label is pretty static i think (1) would be ok aswell.

**Comment by CelticMinstrel** [comment]
Well, gfgtdf basically said roughly what I was going to say - this looks good, but `prevLabel` should probably not be just a global variable like that. I hadn't thought about making it a member variable of the display class, though - indeed, that's better than making it static.

If you do decide to make it static instead, I suggest moving it into the empty namespace at the top of the file.

**Comment by binarycoder** [comment]
That's a good point, I just pushed a commit to move the variable to the namespace in the display class. Will that work?

**Comment by CelticMinstrel** [comment]
Uhhh. The namespace is not in the display class. Putting it in the display class would mean moving it into display.hpp.

Still, this is fine, as long as attempting a nonexistent label just does nothing.

**Comment by CelticMinstrel** [comment]
I just checked, and `remove_floating_label` does indeed do nothing if the label already doesn't exist, so in my opinion this is now ready to merge.

At this point you can add yourself to the credits in about.cfg, under "Miscellaneous Contributors", if you wish. Also, you could add a note about this to the changelog if you think it's important enough.

**Comment by binarycoder** [comment]
Alright, just pushed the credits and changelog, let me know if there's anything else that needs changing. Appreciate the assistance, sorry it took a bit to get correct.

**Comment by CelticMinstrel** [comment]
The changelog entry should probably include the issue number.

**Comment by binarycoder** [comment]
Alright, the bug number has been added.

**Pull request merged**
