### PR TITLE
Remove extra parens to avoid compiler warning

### PR DESCRIPTION
**Pull request by soliton-**

### CODE REVIEW

**Review by stevecotton — APPROVED** [review]
The warning triggers when compiling with Clang 18.

**Comment by Pentarctagon** [comment]
What's the warning?

**Comment by soliton-** [comment]
> Equality comparison with extraneous parentheses

Extra parentheses are conventionally used with assignments so if double parentheses are used with comparisons it makes that convention useless.

**Comment by stevecotton** [comment]
@Pentarctagon are you happy with this merging? (I assume so)

**Comment by Pentarctagon** [comment]
Yeah, I was just curious what warning it was fixing.

**Pull request merged**
