### PR TITLE
update wesnoth-lib/fr.po

### PR DESCRIPTION
**Pull request by kannebankai**
I added, upgraded and changed some french translation since some were missing, outdated, false or "bad"
I checked from line 1 to 3844

### CODE REVIEW

**Comment by Wedge009** [comment]
Thanks for your contribution. I'd also like to see the French translation updated. Have you seen the French translation notes on [wesnoth.org](https://wiki.wesnoth.org/FrenchTranslation)?

**Comment by kannebankai** [comment]
I sent an empty mail to the email address who manage the french
contribution (wesnoth-resquest@ml.free.fr) with the subject "subscribe" but
the server anwser me with an error 550 <wesnoth-resquest@ml.free.fr>: User
unknown

I don't know how I can change this, if it's a problem from me or from the
server

2016-11-25 14:21 GMT+01:00 Wedge009 <notifications@github.com>:

**Comment by Wedge009** [comment]
It's possible that none of the French translators are active any more. I don't know much about the translation community but if that's the case maybe you could co-ordinate with @ivanovic and volunteer to take over maintenance of the French translation.

The last French update I see is from August 2015.

**Comment by CelticMinstrel** [comment]
Some of these changes make me wonder if it's clear over whether the Wesnoth translation is fr_FR or fr_CA, as I know they have quite a few vocabulary differences (though I'm not well-versed in specifically what those differences are). Probably none of your changes are actually relevant to this difference, mind you (I started wondering when I saw sol -> plancher, but base on Wiktionary it looks like that's really just choosing a more accurate word for the context).

**Comment by kannebankai** [comment]
I haven't see anything (words, expression ...) that make me think that it
was a fr_CA version. And yes for some changes it's just that it fit more in
the context (for example plancher is more suitable than sol if the material
of it is wood)

2016-11-25 20:17 GMT+01:00 Celtic Minstrel <notifications@github.com>:

**Comment by CelticMinstrel** [comment]
Just checking, did you read this page? https://wiki.wesnoth.org/FrenchTranslation

**Comment by CelticMinstrel** [comment]
Just checking, did you read this page? https://wiki.wesnoth.org/FrenchTranslation

Also, looking at that page, if you tried to subscribe to "wesnoth-resquest@ml.free.fr" then it's no wonder it didn't work, as you have an extra S in that email.

**Comment by kannebankai** [comment]
Yes I read this page and I tried to subscribe to this mail list but what do you mean by there is an extra s in that mail ?

**Comment by AI0867** [comment]
That you tried to subscribe by sending an email to 'wesnoth-re**s**quest' rather than 'wesnoth-request'.

**Comment by kannebankai** [comment]
Oh yes I see I sent a mail to the right address and I'm subscribed now ty

**Comment by CelticMinstrel** [comment]
So what's the status on this? Is the French translation maintainer still missing? I'd really like to see all these French updates merged soon.

If the maintainer listed on the wiki page continues to respond, we may need to appoint a new French translation maintainer; preferably someone willing to check others' work.

CC @fckanneBankai, @benoitbrb

**Comment by kannebankai** [comment]
I still get no answer from them, and it's been like this for more than
three months

2017-03-18 23:13 GMT+01:00 Celtic Minstrel <notifications@github.com>:

**Comment by Wedge009** [comment]
If you would be willing to handle French translations - at least until and unless the original maintainers return to their post - I think that would be helpful for everyone. But up to you, of course.

**Comment by kannebankai** [comment]
Yes sure. The next week is my exam week so if it takes a bit long to read
every contributions and manage it will be normal

2017-03-19 13:19 GMT+01:00 Wedge009 <notifications@github.com>:

**Comment by kannebankai** [comment]
I have free time now so, what I have to do ?

2017-03-19 13:24 GMT+01:00 Kanne Bankai <kannebankai@gmail.com>:

**Comment by CelticMinstrel** [comment]
Instructions for translation maintainers are [here](https://wiki.wesnoth.org/WesnothTranslationsHowTo#How_to_submit_your_translations).

Basically:
1. Take this PR, as well as #883 and #877.
2. Check them (proofread, run spellcheck, etc).
3. Combine them together.
4. Zip up the fr.po files and email them to Ivanovic.

If you're taking over as translation maintainer you should probably also update the list [here](https://wiki.wesnoth.org/WesnothTranslations) so that other French translators know to send their work to you instead of opening a PR here.

**Pull request closed without merging**
