### PR TITLE
Remove LOW_MEM

### PR DESCRIPTION
**Pull request by GregoryLundberg**
Per @Vultraz 

----

Hold for @CelticMinstrel to finish rename PR

### CODE REVIEW

**Comment by gfgtdf** [comment]
i don't think this belongs in the 'WML Engine' changelog category since it doent change the wml language at all.

**Comment by CelticMinstrel** [comment]
It does affect WML slightly, by removing a preprocessor define (which apparently was unused?).

**Comment by gfgtdf** [comment]
> It does affect WML slightly, by removing a preprocessor define (which apparently was unused?).


In that case the message should also mention that and describe what has changed for wml authors.

**Comment by GregoryLundberg** [comment]
I only added the WML Engine note because that was where it was announced in the changelog way-back-when.

To be honest, I'd have not done the changelog entry at all but since it was mentioned when it was added, I thought it best to mention its removal.

**Pull request merged**
