### PR TITLE
Terrain:  wooden or mine variation (Xom) of the stone walls (Xos)

### PR DESCRIPTION
**Pull request by doofus-01**
Also working on a somewhat derivative 'whitewashed' interior wall version, but for now it is only these wooden walls.

### CODE REVIEW

**Comment by Vultraz** [comment]
Looks great so far! Only downside is the lack of wood wall -> cave wall transitions. Right now it uses the stone wall transitions, which look a little odd.

**Comment by doofus-01** [comment]
Hrm, I didn't think they looked that bad as a fall-back transition.  But I guess I could try coming up with something.
(Yes, I know there is a merge commit there, but I don't remember how to deal with it and don't want to --force anything and screw this up even worse.)

**Comment by doofus-01** [comment]
83da4a4 is not a complete set of transition images, but I think it gets the most noticeable ones.

**Comment by CelticMinstrel** [comment]
The merge commit is not a deal-breaker - we can probably deal with it ourselves when we merge. (For this, simply squashing everything together might be fine.)

**Comment by Vultraz** [comment]
@doofus-01 can we merge this?

**Pull request merged**
