### PR TITLE
fix possible bug in attack prediction windows

### PR DESCRIPTION
**Pull request by newfrenchy83**
if an weapon like abilitie with apply_to=opponent is used, then name appear in attack

### CODE REVIEW

**Comment by Pentarctagon** [comment]
Can you provide a screenshot of the issue?

**Comment by newfrenchy83** [comment]
> 
> 
> Can you provide a screenshot of the issue?

bug_attack_window

**Comment by newfrenchy83** [comment]
it si when absorb implemented in [abilities] instead of [specials]( in specials, it is normal)

**Comment by newfrenchy83** [comment]
bug_fixed
ans when it si fixed

**Comment by stevecotton** [comment]
Should it not appear on the opponent's attack?

**Comment by newfrenchy83** [comment]
> 
> 
> Should it not appear on the opponent's attack?

I have already tried to implement it but this randomly generates another bug, the display of the percentage of cth may not appear in the opponent's attack, and I cannot find a solution because the character random affects the relevance of the tests

**Comment by Pentarctagon** [comment]
If I'm understanding, the issue is that when a unit has an ability that's a weapon special (ie: firststrike as an ability), and when that ability affects the opponent, the ability's name is shown on the attacking unit's weapons in the attack dialog?

**Comment by newfrenchy83** [comment]
> 
> 
> If I'm understanding, the issue is that when a unit has an ability that's a weapon special (ie: firststrike as an ability), and when that ability affects the opponent, the ability's name is shown on the attacking unit's weapons in the attack dialog?

Yes, exactly.

**Pull request merged**
