### PR TITLE
Editor terrain button click fix

### LINKED ISSUE #1335: Sometimes, clicking a terrain button after scrolling doesn't do anything (GNA #20783)
**[Original submission](https://gna.org/bugs/index.php?20783)** by espreon on 2013-05-03

When a terrain is selected while the painting tool is enabled, if you put the cursor on a terrain button, use the mouse wheel to scroll the list of terrains down, clicking the button that ends up under the cursor won't change terrains unless you move the cursor a little bit inside the button.

(Reproduced on *)
Release: 1.11.x
Priority: 3 - Low
Severity: 2 - Minor

### PR DESCRIPTION
**Pull request by SomeName42**
Fixed palette button not being clickable after scrolling in palette widget without moving the cursor. Resolves #1335. The cause of the bug was that scrolling doesnt change the highlighted state of the palette buttons and not highlighted buttons didnt process being clicked. Solved the bug by making not highlighted buttons process being clicked.

### CODE REVIEW

**Comment by soliton-** [comment]
Looks fine to me.

Would it make sense to also accept the non-ACTIVE states in the ifs below? (No idea where that'd make a difference.)

**Comment by SomeName42** [comment]
Not sure what to do about the CI failure.

**Comment by SomeName42** [comment]
I guess it just randomly times out.

**Comment by stevecotton** [comment]
I feel it should have a comment in the .cpp file, along the lines of:

> The widget is expected to be in one of the "active" states when the mouse cursor is hovering over it, but that currently doesn't happen if the widget is moved under the cursor by scrolling the palette.

That should be fixed elsewhere in the same file, however I like the way that the current PR is a small change. I think a comment should be added, then this merged and backported to 1.18, and sometime in future there might be a cleanup to make the "active" state work properly (updating the image and the tooltip).

**Comment by SomeName42** [comment]
> I feel it should have a comment in the .cpp file, along the lines of:
> 
> > The widget is expected to be in one of the "active" states when the mouse cursor is hovering over it, but that currently doesn't happen if the widget is moved under the cursor by scrolling the palette.
> 
> That should be fixed elsewhere in the same file, however I like the way that the current PR is a small change. I think a comment should be added, then this merged and backported to 1.18, and sometime in future there might be a cleanup to make the "active" state work properly (updating the image and the tooltip).

I also tried to handle the mouse wheel event inside the handle_event function as it also provides the cursor position but that didnt work for some reason. The map area in the editor also doesnt update the highlighting when only scrolling and there are probably other places too that could be fixed.

**Pull request merged**
