### PR TITLE
Changes in new units.

### PR DESCRIPTION
**Pull request by Hejnewar**
These changes are supposed to make new units look natural (and balanced). For example Icemonax should have cold resistance and Gorer (Level 1 unit) shouldn't deal 26-2 damage even if with charge.

### CODE REVIEW

**Comment by Pentarctagon** [comment]
For the future as well, more descriptive commit messages are helpful.  So what you have in the PR comment here would ideally be in the commit message itself.

**Comment by soliton-** [comment]
A wmlindent run might be good before making a PR to avoid introducing indentation errors.

**Comment by Pentarctagon** [comment]
I'm wondering if a wmlindent run would be better done as part of the release process actually, rather than leaving it to individual PRs.

**Comment by CelticMinstrel** [comment]
I think it's better to run it for each commit so that the indentation _never_ becomes wrong. Putting it on a git hook might be nice, although that's a little dangerous since it sometimes produces incorrect results...

**Comment by soliton-** [comment]
I think educating people about proper indentation and the tools that can help with it is better than periodically cleaning up afterwards.

Indeed a hook that would reject indentation errors would be neat. There are already ways to override wmlindent perhaps there would need to be more.

**Comment by Pentarctagon** [comment]
Potentially it could work where wmllindent is run and then the build fails if `git status` shows files as being modified.

**Comment by CelticMinstrel** [comment]
To be clear, a hook that simply runs wmlindent and applies the result is a little dangerous. If it instead rejected indentation errors, then that would be okay. That said, is there even a way to check in a hook to the repository?

**Comment by Pentarctagon** [comment]
Not sure.  @Vultraz would you know?

**Comment by soliton-** [comment]
I don't think you can install server-side git hooks. Presumably one would have to do some github actions stuff...

**Comment by CelticMinstrel** [comment]
I wouldn't expect Vultraz to know that… but I don't expect it to be possible in any case. That said, anything that runs it and alerts if it produces changes could be useful; and if that's all it's doing it could totally be a GitHub Action or a Travis task or the like.

**Pull request merged**
