### PR TITLE
Remove hp_bar_scaling and xp_bar_scaling from [unit] schema

### PR DESCRIPTION
**Pull request by ProditorMagnus**
#2913

### CODE REVIEW

**Comment by Pentarctagon** [comment]
From the linked issue, it sounds like this has never worked then?

**Comment by CelticMinstrel** [comment]
This is basically fine, but before merging, we should answer the question of whether we _want_ this to work.

Is there any benefit to overriding these values on a unit instance? Maybe a unit with an AMLA tree that allows drastically improving its health?

**Comment by Pentarctagon** [comment]
It doesn't seem especially useful - I'd guess most boss/hero units would likely already have their own unit types.

**Comment by stevecotton** [comment]
I'm wondering if the `[unit_type]` variants of this are useful either, as most boss/hero units that would use it are likely to have enough hitpoints to reach the maximum limits anyway.

I don't have every add-on installed, but for searching the ones that I have on hand: in A Vision Blinded S10, a `last_breath` animation of a necromancer who is obviously returning in a later scenario sets the values to negative numbers via `[modify_unit]`. Haven't watched it to see what it does.

**Comment by stevecotton** [comment]
> I'm wondering if the `[unit_type]` variants of this are useful either,

Implementing support for hiding the XP bar with `[unit_type]xp_bar_scaling=0` is being discussed for #7339, however that wouldn't need `[unit]xp_bar_scaling` to be in the schema. Even if it ends up in the `[unit]` in the savegame, savegames aren't supported by the schema (`[replay_start]` isn't in the schema for starters).

**Review by stevecotton — APPROVED** [review]

**Pull request merged**
