### PR TITLE
Have travis use a Ubuntu 16.04 docker image.

### PR DESCRIPTION
**Pull request by Pentarctagon**
This PR is meant to have Wesnoth's linux travis builds use the Ubuntu 16.04 docker image, rather than the Ubuntu 14.04 default OS that travis provides.  This will also allow upgrading to future versions of Ubuntu simply by editing the `Dockerfile`.  Current todo list:

- [x] See if building still works or not.
- [x] Check that travis' error reporting still works when a compile error is encountered while building in docker.
- [x] Re-add the unit tests to the docker builds.
- [x] See if errors encountered in the unit tests are still noticed by travis.  They are, since [the exit code of the last command is used as docker's return code](https://github.com/moby/moby/issues/354).  However this also means that the building and unit tests must be part of a single script that returns a single success or failure code.
- [x] Re-test that a compiling/linking failure is caught by travis as a failure. [It is.](https://travis-ci.org/wesnoth/wesnoth/builds/309253429?utm_source=github_status&utm_medium=notification)
- [x] Re-test that a unit test failure is caught by travis as a failure.  [It is.](https://travis-ci.org/wesnoth/wesnoth/builds/309347557?utm_source=github_status&utm_medium=notification)
- [x] Create a custom base image on [Docker Hub](https://hub.docker.com/) with Wesnoth's dependencies pre-installed. [Done](https://hub.docker.com/r/wesnoth/wesnoth/tags/).

This PR also:
- Fixes the Mac build declaring the `opt` variable rather than the `OPT` variable.  As a result, it will build with `-O3 -O0` rather than `-O3` and use the `strict` option, like I assume it was originally meant to.
- Changes the GCC `1y` build to `c++14`, since GCC 5.4 supports that option now.
- Re-enables cmake building `campaignd` and `boost_unit_tests`, since those can successfully be built as of #2208.
- Removes leftover Mac code from when Wesnoth used SDL1.

### CODE REVIEW

**Comment by GregoryLundberg** [comment]
Regardless of how this PR resolves, the commit 'Fix travis osx build' should go in.

Would it be possible for @singalen to create a separaate PR for it explaining the added library and removal of the mm source? What versions of OS/X are we dropping support for, if any, when this goes in?

I can understand why this PR requires this commit; but, really, they should be separate PRs.

**Comment by Pentarctagon** [comment]
It should also be noted that the xcode configuration files still have references to `SDLMain.mm`, so I assume someone will have to remove those as well.

**Comment by gfgtdf** [comment]
> Makes all builds use strict.

If this means that they fail on warning then don't do this. The reason why we disable that option on some builds is that with that option the compiler stops compiling when the first warning is found which means it wont tell us all warnings that arise durin the build which is quite annoying

**Comment by Pentarctagon** [comment]
@gfgtdf Alright, I've changed it back to the previous functionality.

**Comment by GregoryLundberg** [comment]
The problem is, without -Werror, we get a "Pass" when it would be better to "Fail".

Perhaps there is a way to determine non-fatal warnings were issued and "Fail" after the various tests due to those warnings?

**Comment by Pentarctagon** [comment]
If there are errors that only give warnings that would be better as errors, they can be made individually into errors with the `-Werror=some-warning`.

More generally though, I'm not sure why there even is different levels of warnings, what with `strict` and cmake's `pedantic`.  I would think there's "warnings for things that should be called out and fixed" which would be applied to all builds, and other warnings which aren't important and can be ignored.

**Comment by GregoryLundberg** [comment]
At present, there are **_no_** errors which are flagged by the compilers which are ignored. When those occur, if the compilers cannot both be satisfied with a direct change, the message is suppressed at the point of generation (#pragma).

In general, at present, I run a few compiles locally as part of my morning ritual and, when I find one of those minor errors, I fix them. But we should not depend upon that; which is why your changes for Travis appeal to me. If Travis does not "Fail" do to thise minor warnings, it means someone needs to _look_; but if you can get a non-fatal warning to "Fail" Travis at some point, I think it would promote more people fixing those piddlin' warnings as they occur.

Windows flags a raft of meaningless warnings if you try to do -Wall to MSVC. The MSBuild project files suppress a number of errors, and several are suppressed with #pragma. But MSVC is not your concern, here.

**Comment by Pentarctagon** [comment]
I agree, which is why I changed everything to use `strict` originally.  But I'm also not going to be fixing any warnings/errors that now get flagged because of this, so if there are objections to making everything `strict`, then I'm not really one of the people who should be debating the point.

That said, it seems to me that the middle ground would be to merge all the `strict` warnings into the default flags, and then have `strict` only add the `-Werror` flag.  That way all the warnings are printed and the build finishes, but also then some a build or two fails because of the `-Werror` flag.

**Comment by gfgtdf** [comment]
> The problem is, without -Werror, we get a "Pass" when it would be better to "Fail".

Thats why currently we only diable that on some builds but not all, so that one build marks the teavis report as failure while the other gives us that information about all the warnings. basically  assuming that the warings that would be generated by debug or rease builds of the same compiler are the same.

**Comment by Pentarctagon** [comment]
I think at this point, it'd be best to leave the existing `strict` functionality as-is.  I was already planning on opening another PR regarding what to do with cmake's `pedantic` warning options as well as maybe adding in one or more `fsanitize` options since we'll be using a more recent version of GCC in travis once this PR is complete.

**Comment by GregoryLundberg** [comment]
Personally, I like pedantic but SCons doesn't offer it. I use it locally on CMake.

According to GCC:

> -pedantic
> Issue all the warnings demanded by strict ISO C and ISO C++; reject all programs that use forbidden extensions, and some other programs that do not follow ISO C and ISO C++. For ISO C, follows the version of the ISO C standard specified by any -std option used.
> 

And, a bit differently, for CLang:

> -pedantic
> Warn on language extensions.
>
>-pedantic-errors¶
> Error on language extensions.
>
> Use -pedantic-errors to request an error if a feature from a later standard revision is used in an earlier mode.

I like the GCC option and don't bother with it on CLang.

Given the differences in interpretation, I'd like to keep -pedantic for GCC and don't mind if that's only available with CMake.

**Comment by Pentarctagon** [comment]
Not the actual `-pedantic` option, rather cmake [enables certain additional warnings](https://github.com/wesnoth/wesnoth/blob/master/CMakeLists.txt#L219-L229) when `ENABLE_PEDANTIC_COMPILATION` is true.

**Comment by GregoryLundberg** [comment]
:man_facepalming:

**Comment by Pentarctagon** [comment]
@GregoryLundberg @jyrkive I believe this PR is complete.  The only remaining potential thing that could be done would be to create our own docker image based on the Ubuntu 16.04 image, but with our dependencies already installed so we wouldn't need to do the `apt update`/`apt get` steps every time.  However, that requires an account on [Docker Hub](https://hub.docker.com/), and I assume I would not be the one creating/controlling it.

**Comment by GregoryLundberg** [comment]
Needs a rebase to merge, but that should wait a bit.

If there is a significant gain which would give us more time for the sporadically slow network before Travis times us out, I'd say go for it.

If you're willing to do the work, go ahead and create the Docker account. The only way we'll know if it's work the long-term support effort is to try it.

If you use a name, email and password, I'd try to set it up using a 'role' name like 'wesnoth' and if/when you want to pass it off to someone else you can give over the password and they can fix the name and password. Or they can make their own account and let yours lie dormant.

**Comment by AI0867** [comment]
Do we still need sudo, or can we remove the `sudo: required` line now?

**Comment by Pentarctagon** [comment]
For building/running docker, I'm not sure.  I assume it would still be needed for the osx build though.

**Comment by AI0867** [comment]
References:
https://docs.travis-ci.com/user/reference/overview/
https://docs.travis-ci.com/user/reference/trusty/

**Comment by Pentarctagon** [comment]
@AI0867 I'm not actually sure it matters what the `sudo` value is set at in the `.travis.yml`.  According to [this](https://docs.travis-ci.com/user/docker/), specifying the docker service automatically makes it require sudo, and even in the most recent build with `sudo: false` it [still uses](https://travis-ci.org/wesnoth/wesnoth/jobs/309955465#L445) sudo to try and start the docker service.

**Comment by AI0867** [comment]
https://docs.travis-ci.com/user/docker/

> Travis CI automatically routes builds to run on Trusty sudo: required when services: docker is configured.

I read somewhere else in the docs that it should be possible to use docker without sudo, but I haven't figured out how yet.

**Comment by GregoryLundberg** [comment]
One to two minutes saved warming up sounds like around a 3-5% speedup overall. I'd say go for it and see about what is involved in making a custom image.

If it looks like making a custom image works, but there are steps and a process, I'd suggest adding a document (travisCI.md ???) so future maintainers know what you did, why and how to pass off control to the next person.

**Comment by Pentarctagon** [comment]
Yep, looks like using the image from Docker Hub with pre-installed dependencies shaved ~1.5 minutes off the build time, based on the previous vs current NLS builds:
Current - 6:26
[Previous](https://travis-ci.org/wesnoth/wesnoth/builds/309253429?utm_source=github_status&utm_medium=notification) - 8:23
[Previous](https://travis-ci.org/wesnoth/wesnoth/builds/309347557?utm_source=github_status&utm_medium=notification) - 7:59
[Previous](https://travis-ci.org/wesnoth/wesnoth/builds/309201704?utm_source=github_status&utm_medium=notification) - 8:03

**Comment by Pentarctagon** [comment]
@AI0867 I have seen that it's possible to run docker as non-root/without sudo by doing something like [this](https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo), but that sounds like it would require a bit of additional setup on the travis side to add whichever user is doing Wesnoth's builds to the right group.

**Pull request merged**
