### PR TITLE
Suppress warning about const variable

### PR DESCRIPTION
**Pull request by GregoryLundberg**
Supress CID 1134314 about 'code' being constant. Remove 'const' if the TODO is ever done.

### CODE REVIEW

**Comment by Vultraz** [comment]
Variable is unused elsewhere, would prefer commenting it out.

**Comment by GregoryLundberg** [comment]
Actually, it's use in an if statement just below. My suggestion would be to eliminate the TODO and dead code.

**Comment by Vultraz** [comment]
Yeah, why not.

**Comment by GregoryLundberg** [comment]
Done

**Pull request merged**
