### PR TITLE
add debug_border to gui2 objects

### PR DESCRIPTION
**Pull request by white-haired-uncle**
Completes debug_border support for styled_widget, and adds grid/row/column support.

Adds dotted border (questionable value) and dashed border, to add additional clarity especially for those who see a limited color range.

Getting things to line up properly in GUI2 can be frustrating.  For example, in the image, my text is left aligned, why is it centered??? (it's left aligned in the label, but the label is centered in the column).  I always wished there was a way to draw borders around objects so I could see what was going on.  I was excited to discover debug_border, unfortunately from what I can tell, "This function is only meant for debugging and might not be available in all Wesnoth binaries" really means "This function is only meant for debugging and is not available at all".

Silly example with nested grids and different modes/colors/objects:

debug_border_example

### CODE REVIEW

**Comment by white-haired-uncle** [comment]
Looks like I do have to add schema entries.  I've been testing with wml.load and haven't seen any errors, but I do now that I tested in data/gui/themes/default/window/...

**Comment by CelticMinstrel** [comment]
Looking at your two new draw functions, I kinda feel like overengineering it into taking a bitfield to reduce code duplication…

**Comment by Vultraz** [comment]
Nice work! The existing debug border functionality does work, but it only covers the bounding box. Adding it for the grid itself is a nice addition. I need to take a closer look at this, though, since I think there’s some stuff that didn’t need to be added.

**Comment by white-haired-uncle** [comment]
Test scenario, right click and select "debug border"

[GUI_Tutorial.tar.gz](https://github.com/user-attachments/files/16721250/GUI_Tutorial.tar.gz)

**Comment by babaissarkar** [comment]
> Test scenario, right click and select "debug border"
> 
> [GUI_Tutorial.tar.gz](https://github.com/user-attachments/files/16721250/GUI_Tutorial.tar.gz)

don't know if you know it or not, but the gui test dialog (accessible via --clock) can be used for gui2 test purposes.

**Comment by Pentarctagon** [comment]
@Vultraz any issue with this PR?

**Comment by Vultraz** [comment]
I haven't looked at this recently, but I think there's way more added here than is necessary. It shouldn't be merged as-in.

**Comment by CelticMinstrel** [comment]
I kinda feel like this dashed/dotted stuff would be nice to support as a border style in canvas shapes.

I also can't help noticing that the three supported styles could be generalized down to `0b1`, `0b1100`, and `0b11100`. In other words, instead of solid/dashed/dotted you could take an arbitrary `boost::dynamic_bitset` to determine the pattern. Another nice pattern might be `0b111010`. As mentioned in my previous post, this might be overengineering things a bit, but a) I think it's kinda cool with the added flexibility and b) it reduces code duplication – `draw_dashed` and `draw_dotted` become the same function.

It would be nice if @Vultraz noted what he feels is unnecessary in here, but I personally don't think it's fair to block it solely on account of the dashed/dotted styles (which I think is the most likely thing he's thinking of).

**Comment by Vultraz** [comment]
I have no objections to the dotted/dashed styles. It's the extra handling for `debug_border_mode` in at least three places and all the extra code added to `grid`. We already have working handling in `widget`, and it's not clear what this extra handling does besides duplicate code.

**Comment by CelticMinstrel** [comment]
Thanks for the explanation. I don't know enough about this area to tell if you're correct about it being redundant, though.

**Comment by white-haired-uncle** [comment]
I'm not sure what's redundant here, since try as I might I've never been able to get debug borders working before this.  I've seen them in (photoshopped) screenshots, but I'm thoroughly convinced those are just a cruel ploy to toy with me.

As for grid, in theory I suppose if widget borders worked then grid should too, maybe, though that didn't happen for me (the first thing I did was widget borders, which did not give me grid borders even though a grid is a widget -- hmm, is a grid a _styled_widget_?).  But most of the addition to grid is to handle row and column borders.

**Pull request closed without merging**
