### PR TITLE
Rename some Dunefolk units

### PR DESCRIPTION
**Pull request by nemaara**
Like the title says. Some of the names could match stats a bit better (and descriptions, I suppose). Tagging @CelticMinstrel for any comments for fun.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
So "steppe rider" is kinda long and "windranger" is a bit… underwhelming… they're not bad, exactly, but they're not quite as nice as the previous names. (More accurate, sure, but I'm talking about, um, aesthetics or something, can't find the word for it…) It's not to the level that I'd say "don't use these names", but...

As for "ophidian", it sounds fine but it's kinda in the department of redundancy department… given that "naga" means (at least in this context) "a snake person" and "ophidian" is the adjectival form of "snake".

**Comment by nemaara** [comment]
Renamed yet again:
Ranger -> Wayfarer
Swiftrider -> Horse Archer
Windrider -> Windbolt

I'll update wmllint when it comes time to merge.

**Comment by CelticMinstrel** [comment]
Oh, windbolt isn't so bad. Horse archer is kinda boring but I can't complain that much I guess, since it does fit…

**Comment by Pentarctagon** [comment]
Would this and #4530 conflict?

**Comment by CelticMinstrel** [comment]
I think most likely they wouldn't conflict - it doesn't look like they change any of the same lines.

**Comment by gfgtdf** [comment]
also don't forget to add these changes to wmlint

**Comment by nemaara** [comment]
Can someone point out what I'm doing wrong in updating wmllint?

**Comment by Pentarctagon** [comment]
What error are you getting?

**Comment by nemaara** [comment]
`  Observed result :                                       1 - FAIL
  Expected result :                                       0 - PASS
timeout --kill-after=16 15 ./wesnoth -ucharacterize_pathfinding_reach_2 --validcache --log-strict=warning --noaddons 
characterize_pathfinding_reach_2 :
  Observed result :                                       1 - FAIL
  Expected result :                                       0 - PASS
timeout --kill-after=16 15 ./wesnoth -ucharacterize_pathfinding_reach_3 --validcache --log-strict=warning --noaddons 
characterize_pathfinding_reach_3 :
  Observed result :                                       1 - FAIL
  Expected result :                                       0 - PASS
timeout --kill-after=16 15 ./wesnoth -ucharacterize_pathfinding_reach_4 --validcache --log-strict=warning --noaddons 
characterize_pathfinding_reach_4 :
  Observed result :                                       1 - FAIL
  Expected result :                                       0 - PASS
timeout --kill-after=16 15 ./wesnoth -ucharacterize_pathfinding_reach_5 --validcache --log-strict=warning --noaddons 
characterize_pathfinding_reach_5 :
  Observed result :                                       1 - FAIL
  Expected result :                                       0 - PASS
timeout --kill-after=16 15 ./wesnoth -ucharacterize_pathfinding_reach_6 --validcache --log-strict=warning --noaddons 
characterize_pathfinding_reach_6 :
  Observed result :                                       1 - FAIL
  Expected result :                                       0 - PASS
timeout --kill-after=16 15 ./wesnoth -ucharacterize_pathfinding_reach_7 --validcache --log-strict=warning --noaddons 
characterize_pathfinding_reach_7 :
  Observed result :                                       1 - FAIL
  Expected result :                                       0 - PASS`

`Error (strict mode, strict_level = 1): wesnoth reported on channel error engine/team_construction
20191108 08:58:29 error engine/team_construction: game_error: unknown unit type: Dune Ranger
20191108 08:58:29 error engine/team_construction: game_error: unknown unit type: Dune Swiftrider
20191108 08:58:30 warning wml: The following conditional test failed:
	[variable]
		equals=$current_answer=143
		name=observed_answer
	[/variable]
	Note: The variable observed_answer currently has the value "147".
FAIL TEST : characterize_pathfinding_reach_1`

**Comment by soliton-** [comment]
The tests reference some dunefolk units, for example here:
https://github.com/wesnoth/wesnoth/blob/ab27656e16da1a4c8cc76e2c3a7acb0cd37e288b/data/test/maps/pathfind_1.cfg#L1312

Those types need to be updated in that file at least.

**Pull request merged**
