### PR TITLE
[UtBS] Sprite updates, some other updates, WIP

### PR DESCRIPTION
**Pull request by doofus-01**
This is for Quenoth sprites and some random things I notice as I go through the campaign.  I'll keep the string revisions (like removing references to horses) out of this, but there might be some new strings, like for a new terrain name.

(I'm not sure if I'm doing this PR correctly, I am tracking 1.14 branch since I couldn't run master last time I tried.)

### CODE REVIEW

**Comment by Vultraz** [comment]
Can I merge this? The sprite updates should go in 1.14.0.

**Comment by doofus-01** [comment]
How much time do I have to add a few other things?
(Kaleh needs a little attention.)

**Comment by Vultraz** [comment]
Until the 25th.

**Comment by doofus-01** [comment]
OK.  Whatever I get done tonight is all I'll be able to do by then, so feel free to merge after 12 hours from now.  I have a new terrain for the crushed tree in the first scenario, but I'll keep it out of here.

**Pull request merged**
