### PR TITLE
Fix teaching_anim not implmmented in variation_id=sceptre of Httt Princess and Battle Princess

### PR DESCRIPTION
**Pull request by newfrenchy83**
I have forget to pull this in variation scpeter of unit_type

### CODE REVIEW

**Comment by stevecotton** [comment]
Code looks good to me, and it works in game with the leading animation being used instead if the supported unit is of lower level. (The leading animation has a shiny spark, the initiative one doesn't).

The Battle Princess' animation for both leading and initiative looks odd to me, too much waving the sword about, but that's not caused by this PR. I'd approve, but I think I've the wrong person to do the review.

**Comment by doofus-01** [comment]
I'll look at it this weekend.

**Comment by Pentarctagon** [comment]
@doofus-01 were you able to take a look at this?

**Comment by doofus-01** [comment]
Sorry, I'd forgotten about this, but looking at it now.

**Review by doofus-01 — APPROVED** [review]
It looks like it should be fine.  It would be better if there were additional animation frames, both leading/initiative and regular/sceptre, but that can be a separate issue.

**Pull request merged**
