### PR TITLE
Add translation hints for time format strings

### LINKED ISSUE #6246: strftime po hints
These strings (and probably a couple that I've missed) should have translation hints:

```
src/format_time_summary.cpp-			// save is from current year
src/format_time_summary.cpp:			format_string = _("%b %d");
--
src/format_time_summary.cpp-		// save is from a different year
src/format_time_summary.cpp:		format_string = _("%b %d %Y");
--
src/save_index.cpp-	if(std::tm* tm_l = std::localtime(&modified())) {
src/save_index.cpp-		const std::string format = preferences::use_twelve_hour_clock_format()
src/save_index.cpp:			? _("%a %b %d %I:%M %p %Y")
src/save_index.cpp:			: _("%a %b %d %H:%M %Y");
```

This one should be translatable too:
```
src/gui/dialogs/addon/manager.cpp-
src/gui/dialogs/addon/manager.cpp-		const char* format = preferences::use_twelve_hour_clock_format()
src/gui/dialogs/addon/manager.cpp:			? "%B %d %Y, %I:%M %p"
src/gui/dialogs/addon/manager.cpp:			: "%B %d %Y, %H:%M";
```

### PR DESCRIPTION
**Pull request by Wedge009**
Resolves #6246

### CODE REVIEW

**Comment by stevecotton** [comment]
It looks good, but it doesn't backport cleanly because of the other changes between 1.16 and master. Not sure what to do about that, the best option might be to merge it and make a hand-edited backport for 1.16.2.

**Comment by Wedge009** [comment]
No worries, when the string freeze lifts I can do the same/similar thing for 1.16.

**Review by stevecotton — APPROVED** [review]

**Comment by stevecotton** [comment]
Just realised that most of this doesn't need to wait for the string freeze to be backported. With the exception of the one that's converted to translatable strings, all of the other po hints could go into 1.16.1 and help any translation team that's working before 1.16.2 comes out.

**Comment by Wedge009** [comment]
Oh, good point.

**Comment by Wedge009** [comment]
92e8e1cd86b0e57c2d5f4e51b55a538c8ca419f4

**Pull request merged**
