### PR TITLE
Add font for Cyrillic symbols

### PR DESCRIPTION
**Pull request by amakriLexa04**
The new main menu screen uses Oldania font, which does not have any Cyrillic characters, which makes labels in Ukrainian and other languages that use the Cyrillic alphabet look too generic due to the use of the default font.
This PR aims to fix this by adding another font which was designed specifically for Cyrillic. Translators can enable it by changing one line in [wesnoth.po](https://github.com/wesnoth/wesnoth/blob/2679fec5f2a7afa1948406a998cbe9749a59dca3/po/wesnoth/uk.po#L4223)(Remove Oldania from the msgstr and put the "Akademie Alte" there)

### CODE REVIEW

**Comment by Pentarctagon** [comment]
Looks good to me.

**Comment by soliton-** [comment]
Where did you get the files from? Seems to be neither from https://sci.ponomar.net/fonts.html or the linked github repo.

**Comment by amakriLexa04** [comment]
I downloaded them from here
https://fontlibrary.org/en/font/ponomar-unicode

**Comment by soliton-** [comment]
I'd rather use the newest version directly from upstream.

**Comment by amakriLexa04** [comment]
I see, then I'll newer version to the PR, but a little later, cause I found a few more good fonts and need to test how they look in the game to choose the best one.

**Comment by Wedge009** [comment]
I presume the Open Font Licence is okay for Wesnoth.

**Comment by soliton-** [comment]
Yes, several fonts already included with wesnoth use it.

**Comment by amakriLexa04** [comment]
Our community voted to choose the [Akademie Alte](https://online-fonts.com/fonts/akademie-alte) font. The license seems to suit us (CC BY 3.0). But I don't know what to write in COPYING file.

**Comment by Wedge009** [comment]
Seems to me you just need to credit the author, Marath Salychow. Not sure if it's necessary to link to https://creativecommons.org/licenses/by/3.0/, but you can probably mention what the licence is.

**Comment by amakriLexa04** [comment]
Well, that seems to be all

**Comment by Pentarctagon** [comment]
This is fine to merge then?

**Comment by Wedge009** [comment]
For adding the font, seems fine to me. For _using_ the font, I'm not sure if that needs to be specified by Wesnoth explicitly or if it's handled the OS/fontconfig, etc.

**Comment by amakriLexa04** [comment]
Yes, we just need to add the font, and then translators will do the rest. So this PR can be merged and closed without any problems.

**Pull request merged**
