### PR TITLE
Re-add attribution to copyright notices.

### PR DESCRIPTION
**Pull request by Pentarctagon**
These are mostly useless and outdated/wrong, but apparently it's probably illegal to remove them.

### CODE REVIEW

**Comment by irydacea** [comment]
Why are some of them broken up after the year into a new line and others aren't?

**Comment by Pentarctagon** [comment]
The line that ends with the year is the one that the script updates.

**Comment by irydacea** [comment]
Is there really no better option so that it doesn't look like someone press enter too early?

**Comment by Pentarctagon** [comment]
I don't see how it makes any difference to be honest.

**Comment by CelticMinstrel** [comment]
There's definitely another option (make the script a bit more robust), but I also don't think it makes any difference.

**Pull request merged**
