### PR TITLE
Fix Coverity null dereferenced warning

### PR DESCRIPTION
**Pull request by GregoryLundberg**
It is probably not possible for cur to be nullptr, but best check anyway.

Closes CID 1380176

### CODE REVIEW

**Comment by jyrkive** [comment]
I strongly oppose this PR in its current form. Error conditions should not be ignored.

**Comment by GregoryLundberg** [comment]
Actually, you should oppose it because it has a logic error.

Do you want a general exception "An impossible error occurred" or do you want specifics like "I am not a child of my parent" or "My younger sibling does not exist" and "A descendant of my younger sibling is not a child of its parent"?

**Comment by GregoryLundberg** [comment]
Logic error fixed. Now throws an exception rather than returning nullptr: only returns nullptr to indicate this is the first child of the (invisible) root. Added a comment describing what I see (I can remove it but it helped me think through the issues).

**Comment by jyrkive** [comment]
For supposed-to-be-impossible errors, a general exception is fine. If it ends up occurring in practice, it's trivial to look at the stack trace and notice that the problem was a condition thought to be impossible.

However, you can't use plain [`std::exception`](http://en.cppreference.com/w/cpp/error/exception) here because it doesn't have a constructor from strings. Such a constructor is a Microsoft extension. (I recall that because I did that exact mistake in my very first pull request in the Battle for Wesnoth project.)

None of the standard exception objects look like they'd fit in this situation, unfortunately. :(

**Comment by GregoryLundberg** [comment]
I think that is sdl::exception but I'll compile a test forcing the failure.

I maybe it would be better to define a wesnoth::exception(string) for this sort of thing since we're going to need it to replace all those assert(false) lamenesses.

**Comment by gfgtdf** [comment]
the only place that calls this function (https://github.com/wesnoth/wesnoth/blob/849860a0bb74d69f824390520d25f27ebfa18f0f/src/gui/widgets/tree_view_node.cpp#L791) does eplxiclty cehck whether get_node_above returns nullptr so we probabyl don't need to throw an exception there.

**Comment by jyrkive** [comment]
@gfgtdf `cur` can only be null if the node isn't a child of its own parent, which is impossible. Therefore, if we check for the "`cur` is null" condition, we should definitely throw an exception instead of ignoring the situation.

**Comment by GregoryLundberg** [comment]
Should be good to go, now.

Fixes the (actual) logic error causing the null dereference, even though it should be impossible. This will quiet Coverity.

Explicitly throws an exception with a more meaningful message then "null pointer dereferenced"

**Comment by gfgtdf** [comment]
@jyrkive yes i know, that's why i edited my post then, at first i though that codepath is also reached when there is just not 'above' node. But if it's supposed to be impossibel and indicates a corrupt state then should give an assert anstead of throwing.

**Comment by jyrkive** [comment]
Merged. Thank you! :)

**Pull request merged**
