### PR TITLE
Update WoF

### LINKED ISSUE #7361: Reworking suggestions about Drakes eating other sapient races from #wesnoth-wof
### Describe the desired feature

In another issue (#4007) that was implemented, the principle that Orcs, wesnoth arch-villains, should not not be depicted as creatures that eat or feast on sapient races.

One year away from release of BFW 1.18, reconsider if the multiple references to Drakes hunting, eating orcs, elves and humans is a welcome addition to the lore of wesnoth.

### PR DESCRIPTION
**Pull request by Jonathan-Kelly**
Closes #7361

### CODE REVIEW

**Review by nemaara — COMMENTED** [review]
One more, line 51 in S2x, could use editing. Rest looks good to me.

**Comment by Wedge009** [comment]
Don't think I've seen the PR labeller fail before, that's a weird one...

**Comment by stevecotton** [comment]
> Don't think I've seen the PR labeller fail before, that's a weird one...

It might be fallout from https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/

**Comment by Jonathan-Kelly** [comment]
@nemaara  Alright, edited that one too.

**Review by knyghtmare — APPROVED** [review]

**Review by nemaara — APPROVED** [review]

**Pull request merged**
