### PR TITLE
Remove the 'Mandatory WML Child missing but untested for' error

### PR DESCRIPTION
**Pull request by CelticMinstrel**
Pushing for preliminary review, not quite done yet. Basically I'd like _everyone_ to look it over and see if I need to change how the missing child is handled in some of the cases (particularly those labelled by `TODO`).

This addresses #3647.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
> Also all those (*cfg)["attr"] are not exactly pretty.

Yes indeed, I was thinking that too. That's why I'm planning to add a function so I can write `cfg->at("attr")` instead.

> on the other hand while forgetting the result of child() was previously 'just' a 'Mandatory WML Child ..' error it is now a segfault/nullptr dereference which is actually worse than that undescriptive error.

I'm not so convinced that it's worse. It's bad, yes, but the "Mandatory WML Child..." error is also quite bad. This forces us to raise the errors earlier, when we have more information about what has gone wrong.

Of course we do need to ensure we don't dereference a null pointer. However, most of the uses of `.child()` were already within an `if()` statement, so I don't think this will end up being a big problem. Still, that's why I've opened it for review instead of just pushing it, because ideally we'd have ten pairs of eyes looking at all the places where `.child()` or `.find_child()` was previously called.

**Comment by gfgtdf** [comment]
maybe it'd be better if that function returned a custom pointer type instead of just config* , that'd have the advantage that we could easily add new features to it in particular nullptr checks and other debugging tools.

> ...

hmm yes I was not really worried that this patch induces crashes on it's own, after all it forced is somehow to take a took all all current usecases, more about future code in that past people did accidently write code like child("tag")["atten"], and when they now make the similar mistake of child("tag")->attr("atten") it might cause crashes.

**Comment by CelticMinstrel** [comment]
@gfgtdf - What about using `boost::optional<config&>`? Does that help at all to alleviate your concerns? Or do you require a true custom class of some kind?

**Comment by gfgtdf** [comment]
my idea was basicially to be able to check whether there exists a (c++) code that uses find/get_child functiosn without checing the result first by writing 

```
//config.cpp
//todo handle const correctly
#ifdef DEBUG_CONFIG

class config_ptr
{
	config_ptr(config* cfg)
		: ptr_(cfg), checked_(false)
	{
	
	}
	explicit operator bool() { checked_ = true; return ptr_ != nullptr}
	config* operator*() const{ if(!checked_) { throw error("conifg_ptr used before checked"); return ptr_ }
	...
private:
	config* ptr_;
	mutable bool checked_;
}
#else
//std::observer_ptr<config> is basicially 'config*' as a class.
class config_ptr : public std::observer_ptr<config>
{
	config_ptr(config* cfg) : std::observer_ptr(cfg) {}
}
#endif

```

then there would be of course be two get_child functions: one like `get_optional_child` that returns a config_ptr and one `.child()` function that returns a config& and throws when when no sihc child exists.

**Comment by CelticMinstrel** [comment]
Your `config_ptr` doesn't really solve the issue as far as I can tell - it has the exact same problem that the existing implementation does. Can you explain how it would actually improve the situation?

**Comment by gfgtdf** [comment]
> Your config_ptr doesn't really solve the issue as far as I can tell - it has the exact same problem that the existing implementation does

It working quite differntly, it does not give an error when an invalid config is accecced, it gives an error when a config is accecced without being checked first, whether it is actually valid or not. As i said before it s a debuggin feature to detect unchecked config acccess.

**Comment by CelticMinstrel** [comment]
But the error still occurs at the same point - when accessing the config, not when fetching it. The point of this PR is to remove this possibility in order to force coders to check and print an error message, rather than deferring the error to a point where it's too late to add any useful information.

Another possibility would be returning an iterator, though that might make it a touch harder to do the check since you need to compare it with `.end()` rather than just converting it to bool.

**Comment by gfgtdf** [comment]
> But the error still occurs at the same point - when accessing the config, not when fetching it

just like in the config* case,.

> The point of this PR is to remove this possibility in order to force coders to check and print an error message, rather than deferring the error to a point where it's too late to add any useful information

Yes and this is exactly the purpose of the custom ptr class aswell: to detect such errors easiler and not only error when in the bad case (the child was not found) but happens,  but always when there is no check for it even when the tag is actualyl there.

**Comment by CelticMinstrel** [comment]
That still doesn't solve the underlying problem though, which is that they should be checking if the tag exists _before_ fetching it.

Maybe I should remove the "get optional child" function altogether and require that you explicitly check with `has_child` first if you want it to be optional? That doesn't work too well in the case of `find_child` mind you, but that's far less frequently used.

**Comment by CelticMinstrel** [comment]
I have no plans to work on this anytime soon, and even if I did decide to come back to it, I'd probably redo it from scratch.

**Pull request closed without merging**
