### PR TITLE
Make the fire terrains actually illuminate their hex

### PR DESCRIPTION
**Pull request by CelticMinstrel**
Fire illuminates, so it's always weird to see one of these without a corresponding gameplay effect.

### CODE REVIEW

**Comment by stevecotton** [comment]
If sconces illuminate, then Xol (Lit Stone Wall) probably should do too.

Having Xol illuminate means that, if a new player follows the recommended campaign order, scenario 3 of AToTB will be the first scenario when they encounter this. That's possibly a good thing, if #3389 is accepted then AToTB S3 it becomes the main scenario for explaining how local time areas affect the game. If #3389 isn't accepted then I echo sevu's comment in #3056, ["A hint in some way would probably not be bad, as [TSG]'s a newbie campaign"](https://github.com/wesnoth/wesnoth/issues/3056#issuecomment-387236512).

AToTB S3 also has an ^Ebn (Lit Brazer), but that hex isn't likely to see combat, whereas the Xol hexes definitely will.

**Comment by stevecotton** [comment]
Argh, Xol would be the wall, it's the hexes south, south-east and south-west of the Xol that would need the illumination.

**Comment by CelticMinstrel** [comment]
I don't think terrain-based illumination like this supports spreading into adjacent hexes, so I guess lit stone wall would need to be handled by a time area instead.

**Comment by jostephd** [comment]
This PR needs to be rebased from old master to new master.

**Comment by GregoryLundberg** [comment]
1) I'd cherry-pick it but my mind went "TILT" and nearly 1300 commits.
2) This sounds like something which should be classified a bug and backported to 1.14, as well.

**Comment by jostephd** [comment]
@GregoryLundberg `curl https://github.com/wesnoth/wesnoth/commit/1f8c7d3fef7d32d204bdb53ca3dc3e82f2e433b2.patch | git am && git push`

**Comment by GregoryLundberg** [comment]
Cherry picked to master and 1.14

**Comment by gfgtdf** [comment]
this cannot go into 1.14 since it casues OOS (unit will haev differtn attack strength on clients runniong different versions)

**Comment by GregoryLundberg** [comment]
OK. Revert it. Or I'll get to it later.

**Comment by jostephd** [comment]
Reverted

**Pull request closed without merging**
