### PR TITLE
ambusher don't workin httt 07_Crosroad.cfg

### PR DESCRIPTION
**Pull request by newfrenchy83**
fix https://github.com/wesnoth/wesnoth/issues/5383

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
…_how_ can it possibly be this simple!? Is there some other bug here?

**Comment by newfrenchy83** [comment]
two bugs here, the holy water because no id for object( an and httt crossroad(same id and specify take_only_once=no for applied to all ambusher, for trident, bug is potential if two same items in same scenario. If another bugs, then it must review all work of @nemaara in the core and campaign

**Comment by Pentarctagon** [comment]
As a side note: In the commit message I believe you need to say put fix or fixes in front of each issue being addressed.  So for example: fix #5385 and fix #5383.

Since in #5385 you can see it says you **linked** a pull request whereas #5383 says only that you mentioned the issue.

**Comment by CelticMinstrel** [comment]
So… am I to understand that these items work if you have only one of them in the scenario, but don't work if you have both in the same scenario?

**Comment by newfrenchy83** [comment]
> 
> 
> So… am I to understand that these items work if you have only one of them in the scenario, but don't work if you have both in the same scenario?

if these item work with same [object] yes because same [object] applied one time only by default, for same items work both, each object must have an different id, or, for be applied to many unit like in 
HttT Sc. Crossroads, specify take_only_once=no.

**Comment by CelticMinstrel** [comment]
But according to the wiki, not specifying an ID should have the same effect as `take_only_once=no`, unless I misinterpreted it…

**Comment by newfrenchy83** [comment]
> 
> 
> But according to the wiki, not specifying an ID should have the same effect as `take_only_once=no`, unless I misinterpreted it…

Maybe, but if an id is necessary like in 'Crossroad' then  `take_only_once=no must be specified, for holy water, i must look if holy water don't work in master version.

**Comment by newfrenchy83** [comment]
in fact the https://github.com/wesnoth/wesnoth/issues/5385 issue seem concern only the paladins, and yes otherwise, holy water items work normally without id specified, i must resolve thsi problems specifically.

**Comment by CelticMinstrel** [comment]
This change seems wrong too.

* "not type=arcane" strikes me as the correct logic
* Changing it as you did in this commit breaks any case where a campaign defines a custom damage type
* Disallowing a paladin to use the holy water is correct, since their lance is already arcane.

**Comment by newfrenchy83** [comment]
No, the sword only is already arcane but spear is pierce, but is if you said what paladins musn't have item then i remove that.

**Comment by newfrenchy83** [comment]
> 
> 
> This change seems wrong too.
> 
>     * "not type=arcane" strikes me as the correct logic
> 
>     * Changing it as you did in this commit breaks any case where a campaign defines a custom damage type
> 
>     * Disallowing a paladin to use the holy water is correct, since their lance is already arcane.

i reverted that, Crossroad ambusher is the only fixing here now.

**Comment by newfrenchy83** [comment]
@CelticMinstrel i think what this PR is complete now.

**Comment by sevu** [comment]
When I made that change, I probably tested the unit with the take_only_once case …

**Comment by sevu** [comment]
Actually, no.
The difference to TSG is, that the object there is embedded into the unit. That works despite there being implicitly `take_only_once=yes` …

**Pull request merged**
