### PR TITLE
Enable LTO by default.

### PR DESCRIPTION
**Pull request by Pentarctagon**
LTO for Windows is disabled for now, as TDM-GCC does not work well with it.
LTO for Travis is also disabled, due to the extra time linking with LTO takes.

---

From the Discord discussion, @loonycyborg is planning to look into using a different compiler starting with 1.15, so at that point LTO might be able to be enabled for the Windows releases as well.

As for Travis, short of going to the paid version of the service, which has a 120 minute build time limit compared to the free version's 50 minute limit, there just isn't enough time to be able to enable LTO on travis builds.

### CODE REVIEW

**Comment by GregoryLundberg** [comment]
We can get more time (in total) and save time (in many cases) by breaking the runs up.

We already create some libraries. Have one set of runs do just that. Save the artifacts (libraries). And another set of runs which builds the target executable programs using the libraries saved from before.

The problem is getting SCons and CMake to support that, and getting the Travis runs to coordinate correctly.

**Comment by Pentarctagon** [comment]
So you're proposing there would be runs for:
- translations

Build libraries:
- GCC C++14
- GCC scons -O0
- GCC cmake
- Clang scons -O0
- Clang cmake
- OS X

Build executable and do the unit tests:
- GCC C++14
- GCC scons -O0
- GCC cmake
- Clang scons -O0
- Clang cmake
- OS X

?

**Comment by Pentarctagon** [comment]
I'd considered something similar on and off - building the executable, then doing unit tests and anything else in a separate run, though I hadn't really found a good answer for how to use an executable from one run in a subsequent run.  This also is complicated by Travis doing concurrent jobs and concurrent builds, which I don't believe Travis offers a lot of control over, and also how to get the results of a build out of the docker container and into wherever Travis would hold it for the subsequent run.

**Comment by Pentarctagon** [comment]
Another possibility could be [mtime_cache](https://github.com/iboB/mtime_cache), or something functionally similar.

**Pull request merged**
