### PR TITLE
Solve #5145

### PR DESCRIPTION
**Pull request by Hejnewar**
Solve #5145

### CODE REVIEW

**Comment by soliton-** [comment]
Please use a more descriptive commit messages like "Update fungus terrain in MP maps where appropriate" or something.

**Comment by Pentarctagon** [comment]
@Hejnewar Once the commit message's description is updated, I'll go ahead and merge this.

**Comment by CelticMinstrel** [comment]
For what it's worth, since it's a single commit, I'm pretty whoever wishes to merge it can use the "Squash and merge" option to reword the commit themself.

**Comment by Pentarctagon** [comment]
Indeed I can.

**Pull request merged**
