### PR TITLE
Revert network_transmission.cpp/hpp to its 1.14.7 version

### PR DESCRIPTION
**Pull request by stevecotton**
I re-ran the timing test discussed in PR #4201 (comment linked to below), and
saw similar numbers.  The old, simpler code downloads an 86.1MB addon in 25
seconds, the code with the extra thread takes 29 seconds.

https://github.com/wesnoth/wesnoth/pull/4201#issuecomment-517856090

### CODE REVIEW

**Comment by Vultraz** [comment]
At what point did you start your timing and which part did you stop?

**Comment by stevecotton** [comment]
From clicking the download button until the progress bar reached the right hand side.

**Comment by Wedge009** [comment]
Just wondering: How sure are we the time difference is due to the code change? How many times were the timing tests done?

**Comment by stevecotton** [comment]
The timing tests were only done a handful of times, and over a mobile phone network, so really not ideal conditions for a test. However, they seem to point to the code that's simpler and already in use also being faster.

IIRC, the discussion in IRC was that the changes that are being reverted felt faster to @Vultraz , but without any timings to check that.

**Comment by Wedge009** [comment]
Testing download of To Lands Unknown Part 1 (92.8 MiB)
Current: average 7:58 mins
Reverted: average 6:05 mins
My Internet is bad (by US standards), but not _that_ bad. I'm in eastern Australia, I'm not sure where the wesnoth.org server is located (traceroute suggested Germany), plus the server may not be able to upload that quickly either.

Anyway, at least this gives me a good spread on timing, and this seems to suggest the current code is substantially slower for some reason (and I see it's only dialogue code, not the actual network connection). Curious.

Seems to make sense to me to revert this till the slowness is resolved. Should this reversion go to master as well?

**Comment by Vultraz** [comment]
Well this is most damn disappointing...

**Comment by Wedge009** [comment]
Why?

**Pull request merged**
