### PR TITLE
fix WRN_NG level

### PR DESCRIPTION
**Pull request by ProditorMagnus**
@gfgtdf

### CODE REVIEW

**Comment by Wedge009** [comment]
I don't see any reason not to merge this as soon as possible.

**Comment by gfgtdf** [comment]
looks good to me

**Comment by gfgtdf** [comment]
I actually don't even think this warning is needed at all, at some point advancing was aborted in this case when the unit had too many xp left, which i removed in https://github.com/ProditorMagnus/wesnoth/commit/d511933dedc6fe801a6f0d5cf6e5831181858f85 , i left the warning there instead probably as some kind of compromise with the previous code.

But especially if there exists some umc code which runs into this warning during normal gameplay we should also remove it imo.

**Comment by ProditorMagnus** [comment]
Considering ZK reported it with level 100 unit I do not consider that normal gameplay.

**Comment by Wedge009** [comment]
If it was a special case, then the unusual behaviour should have been commented - without knowing the background seeing something like warn -> error followed by error -> error is definitely an oddity.

**Pull request merged**
