### PR TITLE
stone tile floor terrain

### PR DESCRIPTION
**Pull request by doofus-01**
Take 2 at the stone floor.  This isn't finished, it only has the most basic transitions so far.
But I think the problems with #1936 are addressed, at least.
EDIT: and here is a forum link with screenshot:https://forums.wesnoth.org/viewtopic.php?f=9&t=24491&p=616880#p616880
EDIT2:  With the second commit, the transitions are improved, the base images are more varied.  I think this terrain is usable now, even if more transitions would be nice.

### CODE REVIEW

**Comment by Vultraz** [comment]
Minor stray pixel in `stone-regular-n-ne-se-s-sw-nw.png`?

**Comment by doofus-01** [comment]
I can't tell that it looks any different, but there were some out-of-hex pixels one some of the transition images. I went over all of them with a cookie cutter, so that should be fixed now.  There was also a bright pixel at the edge of the base images that was noticeable.

I changed a couple of the transition rules, to remove clashes with wood floor, swamp, and castles.
I have a screenshot:

stone_transitions_corrections

**Comment by doofus-01** [comment]
I've added chasm transitions.  The water transition still needs to be done->  Probably a wooden border?
screenshot_002

**Comment by Vultraz** [comment]
Looks like some issues with the chasm transition bleeding through in the corners.

Also, wondering if we should maybe adjust the floor or wall palettes to be a bit more similar like the guy on the forum suggested?

**Comment by doofus-01** [comment]
I originally was looking at the "clean cobbles" for color.  I don't see why it needs to match the dungeon walls, but grunginess can be added later, maybe in a different terrain variation.
 
The triple terrain transitions are non-existent, I'm not yet sure how much is just WML and how much needs a dedicated image.  It's currently no more broken than the bridges.  If it needs more images, I'd leave that until the very end.

**Comment by Vultraz** [comment]
Fair enough.

**Comment by doofus-01** [comment]
This isn't done yet, but it's getting there.  
@ln-zookeeper - I've added a new macro to deal with the three-adjacent-terrain transition that I think makes sense in context, but I'm not sure I'm not just re-inventing the wheel and creating a parallel method.  On the other hand, it's all in the details, so maybe options are fine.
This is a screenshot of the current status:
screenshot_003

**Comment by ln-zookeeper** [comment]
I thought there was a 3-way transition macro already, but I guess they're all for castle-style images and not for regular 72x72 tiles, so seems okay to me.

P.S. If someone else ends up merging this, please squash-merge.

**Comment by doofus-01** [comment]
I think these are done.  I wrote an explanation on the forums:
https://forums.wesnoth.org/viewtopic.php?f=9&p=617323#p617323
If they really are OK (I think they are, but they could be road-tested by someone else), can we consider them done, and I'll try to get a dirtier version before 1.14?

**Comment by ln-zookeeper** [comment]
Looks good to me. If nothing more comes up, I can merge this and maybe give it some quick testing before 1.13.9.

**Comment by ln-zookeeper** [comment]
There's a bit of a big problem with this, namely that it breaks at least cave<->floor transitions because of the raised base image layer. Haven't figured out what's the best fix, yet.

**Comment by doofus-01** [comment]
Just put Uu in the list of terrains in the NEW:TRANSITION line, or am I not understanding?  I've got another PR I'm working on that has "clean" walls that should go with the floor tiles, I can include fixes to this in it.

**Pull request merged**
