### PR TITLE
Fixed unstore_unit lua code (issue #5519)

### PR DESCRIPTION
**Pull request by MrTitainin**
x,y were both binding to whole table instead of their expected values
#5519 should now be solved, although there still might be problem with location_id in teleport code

### CODE REVIEW

**Comment by Hejnewar** [comment]
Tested - works fine for me.

**Comment by soliton-** [comment]
Can you fix the call for teleport a couple lines down as well?

**Comment by CelticMinstrel** [comment]
I see, whoever wrote that (was it me?) must've thought that special_locations returns two values rather than a table. This fix seems fine, if a little ugly. Could also use … I think it's table.unpack?
```
x, y = table.unpack(wesnoth.special_locations[whatever])
```
It doesn't really matter, though.

**Comment by MrTitainin** [comment]
This should address both your concerns.

**Comment by Vultraz** [comment]
Just to confirm, `table.unpack` worked fine?

**Comment by Hejnewar** [comment]
@Vultraz I tested that version too and I didn't notice anything wrong with it so I assume that it works fine.

**Pull request merged**
