### PR TITLE
Fix VC14 Warnig for unreachable code

### PR DESCRIPTION
**Pull request by GregoryLundberg**
@Vultraz commented he didn't want the throw

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I'm wondering why that was even there to begin with.

Unless you want to fix the typo in the commit message, this seems mergeable.

**Comment by Vultraz** [comment]
I'm pondering if perhaps the error (or some error) is indeed desirable.

**Comment by timotei** [comment]
Compared with the era-related throw, it might make more sense to keep this as a throw instead of return.

But then, exceptions shouldn't be used in general for flow control.

**Comment by gfgtdf** [comment]
I also think that it better to show the user an error in this case than to just do nothing when the user clicks on that join button. Since i don't know where the exception is catches i m not sure wheterh using an exception here is the correct thing to do, mabye it'd better to just add a gui2::show_message before that return.

**Comment by GregoryLundberg** [comment]
Make a custom exception for the error and catch that specific class at the appropriate place.

Back in the day we were pretty militant that exceptions should only be used for exceptional conditions and not normal, run-of-the-mill errors you're likely to see. But that's changed, I guess, and I'm seeing a lot of libraries using exceptions to report normal-operation errors because you don't have to remember to check and pass .. just catch it.

**Comment by CelticMinstrel** [comment]
Note that it currently procedes to the next screen when there are no sides, which may be undesirable.

**Comment by gfgtdf** [comment]
this error is about no factions ([multiplayer_side]) in eras not about no sides in scenarios.


About no sides in [scenario]:
There are indeed scenarios without any [side]s in LoW (the only mainline mp campaign) so asuming that every scenario has a side is wrong. Sure one would expect that even in a mp campaign the first scenario has a [side] for each player to let players assign sides in the initial mp staging screen. But when plaing in debug mode afaik the mp stating screen shows after each scenario so tere might be scenarios with no sides there.

**Comment by CelticMinstrel** [comment]
...oh, right, sorry. That was a different thing than I was expecting. Still, if the first scenario in an MP campaign has no sides, then there's probably something wrong, so I think it makes sense for that to be an error message.

It's not relevant to this PR though.

**Comment by Vultraz** [comment]
I'll add a better error after the release. Merging this, though, since I'm pretty sure a throw isn't what we want here.

**Pull request merged**
