### PR TITLE
Updated included Lua lib from 5.3.3 to 5.3.4

### PR DESCRIPTION
**Pull request by Vultraz**
I followed the very helpful instructions provided by @GregoryLundberg to update to Lua 5.3.4. Also applied all currently available patches for [5.3.4 bugs](https://www.lua.org/bugs.html#5.3.4) on Lua.org (the second and third bugs listed had no patches).

### CODE REVIEW

**Comment by Vultraz** [comment]
@GregoryLundberg it seems there's a problem with scons and an old-style cast warning in `luaconf.h`. We either need to edit the file to use `static_cast`, find some other solution, or define `LUA_FLOAT_LONGDOUBLE` so the code in question is avoided (see below). Thoughts?

```
/*
@@ LUAL_BUFFERSIZE is the buffer size used by the lauxlib buffer system.
** CHANGE it if it uses too much C-stack space. (For long double,
** 'string.format("%.99f", 1e4932)' needs ~5030 bytes, so a
** smaller buffer would force a memory allocation for each call to
** 'string.format'.)
*/
#if defined(LUA_FLOAT_LONGDOUBLE)
#define LUAL_BUFFERSIZE		8192
#else
#define LUAL_BUFFERSIZE   ((int)(0x80 * sizeof(void*) * sizeof(lua_Integer)))
#endif
```

**Comment by GregoryLundberg** [comment]
My 5.3.4 source kit reads:
`#if LUA_FLOAT_TYPE == LUA_FLOAT_LONGDOUBLE`
instead of `#if defined` as you show.

**Comment by Vultraz** [comment]
Oh wait. Durrr. I copied that from master. Here's the entire right version:
```
/*
@@ LUAL_BUFFERSIZE is the buffer size used by the lauxlib buffer system.
** CHANGE it if it uses too much C-stack space. (For long double,
** 'string.format("%.99f", -1e4932)' needs 5034 bytes, so a
** smaller buffer would force a memory allocation for each call to
** 'string.format'.)
*/
#if LUA_FLOAT_TYPE == LUA_FLOAT_LONGDOUBLE
#define LUAL_BUFFERSIZE		8192
#else
#define LUAL_BUFFERSIZE   ((int)(0x80 * sizeof(void*) * sizeof(lua_Integer)))
#endif
```

**Comment by GregoryLundberg** [comment]
I have no problem with dropping `--strict` as you did. Lua is supposed to be strict ANSI/ISO C but that does not mean it's always "good" C code.

**Comment by Vultraz** [comment]
Ok, but the problem still persists and @CelticMinstrel said that's since this code is in a header.

**Comment by GregoryLundberg** [comment]
LUA_FLOAT_TYPE defaults to LUA_FLOAT_FLOAT not LUA_FLOAT_LONG_DOUBLE. So the #define used should be the literal number 8192 instead of that bastardized calculation.

**Comment by Vultraz** [comment]
... but then what's happening. The other branch is getting used.

**Comment by Vultraz** [comment]
Wait, no, if it defaults to `LUA_FLOAT_FLOAT` then of *course* the other branch is used. The static number is only used if it *DOES* equal `LUA_FLOAT_LONGDOUBLE`.

**Comment by Vultraz** [comment]
Looking further at this file, it seems it should actually default to `LUA_FLOAT_DOUBLE` since we don't define 32 bit Lua. Or else we do?

**Comment by GregoryLundberg** [comment]
**sigh**

Patch to revert to Lua 5.3.3 definition for LUAL_BUFFERSIZE. It was always 8192 because LUA_FLOAT_LONGDOUBLE was always defined. The Lua 5.3.4 'correction' triggers a --strict failure in the lame-ass calculation which was never, before, used. Obviously we don't need it, so POOF!

> *** luaconf.h.old       2017-10-09 23:38:22.641645801 -0500
> --- luaconf.h   2017-10-09 23:38:56.548577911 -0500
> ***************
> *** 748,758 ****
>   ** smaller buffer would force a memory allocation for each call to
>   ** 'string.format'.)
>   */
> - #if LUA_FLOAT_TYPE == LUA_FLOAT_LONGDOUBLE
>   #define LUAL_BUFFERSIZE               8192
> - #else
> - #define LUAL_BUFFERSIZE   ((int)(0x80 * sizeof(void*) * sizeof(lua_Integer)))
> - #endif
>   
>   /* }================================================================== */
>   
> --- 748,754 ----
>

**Comment by Vultraz** [comment]
Er, is that a patch snippet? It doesn't look like a patch snippet.

**Comment by GregoryLundberg** [comment]
That better.  Yes, it's from patch.

**Comment by Vultraz** [comment]
Oh, thanks.

**Comment by GregoryLundberg** [comment]
I hate patching it like that because it means we'll need to remember to fix it again for 5.3.5 or 5.4 or whatever. Hopefully, someone will point out the error to the Lua upstream and it'll get fixed.

**Comment by Vultraz** [comment]
Applied change by hand but added patch to commit message.

**Comment by Vultraz** [comment]
Which... I totally didn't need to do, but whatever...

**Comment by Vultraz** [comment]
Drop what?

**Comment by GregoryLundberg** [comment]
Drop the commit to remove --strict

After that, once Travis is happy, merge it. I've looked at the actual changes and there's a number of bug fixes and some runtime changes but nothing which looks like it should be an issue for Wesnoth.

**Comment by Vultraz** [comment]
Done. Now we wait.

**Comment by jyrkive** [comment]
I think we outright *can't* get Lua upstream to fix it. :( Lua code is C, not C++, and in C code only the C-style cast is available.

**Comment by GregoryLundberg** [comment]
We might still be able to do it. While it's "standard C" they also specifically state it can be compiled as C++ to use exceptions. And, let's face it, that calculation is lame.

**Pull request merged**
