### PR TITLE
[THoT] Remove filler scenarios and add character

### PR DESCRIPTION
**Pull request by nemaara**
(I got to this earlier than I thought) For #4009, I removed S4, S6, and S7 (which were mostly just filler scenarios), and added another character. This still needs a rebalancing pass and I need to change the new S5 (Fear), so marking WIP for now.

### CODE REVIEW

**Comment by nemaara** [comment]
New scenario for S5 Fear is in this PR now, I'll merge when I finish the rebalancing pass.

**Comment by nemaara** [comment]
This is ready to be merged now.

**Comment by stevecotton** [comment]
The Lua script in THoT was only used in the removed Invaders scenario. I don't know what edge conditions exist for removing Lua scripts and their effects on existing saves.

**Comment by AI0867** [comment]
I've only read this now, but it completely upends the previously established lore. Has there been discussion about this elsewhere?

**Pull request merged**
