### PR TITLE
Tutorial - small refactoring

### PR DESCRIPTION
**Pull request by sevu**

### CODE REVIEW

**Comment by gfgtdf** [comment]
why do we needed this bookeeping in th first place? that even did have first_time_only=yes(default) after all.

**Comment by CelticMinstrel** [comment]
@gfgtdf Presumably the event isn't supposed to be fired in a later turn.

**Comment by sevu** [comment]
This event should fire when the player selects his unit instead one of the recruited ones, which he should use for attacking.
After attacking with the correct unit, there's no need for the warning message anymore.

**Comment by gfgtdf** [comment]
right, from the dif (which collapsed some code) it forst looked like the [remove_event] is inside the same event that it removes

**Pull request merged**
