### PR TITLE
An add-on's min_version should be unset to indicate the latest version is needed.

### LINKED ISSUE #5004: MP min add-on version logic incorrect.
Relevant comment [here](https://github.com/wesnoth/wesnoth/pull/4884#discussion_r460077853).  Essentially add-ons with no minimum version specified should default to requiring the latest version of the add-ons.

Creating this issue so it will be fixed separately from #4884, since it's an existing bug.

### PR DESCRIPTION
**Pull request by Pentarctagon**
This changes the min_version logic to:
1) Unset the min_version if the add-on already exists with a set min_version.
2) Only check and potentially update the min_version if the add-on already has a min_version set.

Fixes #5004

### CODE REVIEW

**Comment by gfgtdf** [comment]
I think this is not 100% correct, of the previous addon  (`addon`) had required=false, it should be overwritten by `new_data` even though it has `addon.min_version` unset.

**Comment by Pentarctagon** [comment]
I think the pushed update should cover that.

**Comment by gfgtdf** [comment]
I think this shoudl work, but looks complicated let me try to find an alternative patch.

**Comment by gfgtdf** [comment]
made an alternative patch: #5022

**Pull request closed without merging**
