### PR TITLE
Nr: Add names of people who helped with rewrite to the credits

### PR DESCRIPTION
**Pull request by TheShadowOfHassen**
This PR is just supposed to add my name and the names of those who helped me with the dialog rewrite/edit/ touchup to the credits. I had been planning to do this after the last tweak I wanted to add, that is issue #7684. However seeing that no one has gotten back to me, I decided that that change isn't that important and to just go ahead with this.

The other people who helped (and I don't know how they want put in or added were @nemaara @stevecotton @Wedge009. If they want they can put their names with mine in the credits listing I made. (Assuming I did it right and the entire thing doesn't need redone)

If people think the rewrite/edit/touchup shouldn't be in the credits that's OK, but at the very least seeing that I put a lot fo work in it I should at least be somewhere so people can find me if they have questions.

### CODE REVIEW

**Comment by Wedge009** [comment]
Not sure what the threshold is, but I don't recall it was a complete rewrite, more like a light revision. I don't have a strong opinion on this addition, but I'm also okay to be left off the list. I thought normally such revisions would be covered under campaign maintenance.

**Comment by CelticMinstrel** [comment]
I don't have any problem with adding your name here, but I do wonder if the placement (and the `title=` key) is right.

**Comment by Pentarctagon** [comment]
This can be merged then, it sounds like? We don't really have any guidelines as far as I know for adding people to the credits other than essentially "they contributed something and nobody objects to adding them".

(also, there were 500+ comments on a light revision?)

**Comment by Wedge009** [comment]
There was a bit of discussion, but I meant that (at least with my recollection of the changes) there were punctuation changes, some slight rewording, that sort of thing. Not a rewrite of the campaign to the degree where there were large structural changes, as with that... other... highly-commented PR.

**Comment by nemaara** [comment]
I'll add your name to the credits separately, if @stevecotton would like to be added too, please let me know. I will add you under campaign maintenance, which is basically what those PRs were as Wedge suggested.

**Comment by CelticMinstrel** [comment]
> "they contributed something and nobody objects to adding them"

I think it's more like "they contributed something and they don't object to having themselves be added".

**Comment by TheShadowOfHassen** [comment]
@Wedge009 the rewrite had a lot of punctuation changes, but when it came to NR's narrator I had to literally read what the narrator said, deleted it all and then rewrote it. In my mind, campaign maintaining would be a comma here, a period there, updating a wmlint package etc.

In my mind, it's basically the same thing as if someone redrew all NR's art portraits. Yes, the characters are the same characters, and they hold the same position, and there's no major campaign rewrite/redraw. But It's still a pretty big change. (And the new art is credited in wesnoth separately)

If people don't want added, it's fine, just let me know if I need to make a change to the PR or if it can be merged.

**Comment by nemaara** [comment]
I've added you in commit 11cded5bc5b7ce7ad6c1b2d2277c9f1dbe95f759. Sorry for not doing this at the time of the last PR, we def want you to get credited for your work! We shouldn't need this PR anymore I think, but feel free to reach out with more questions or comments if needed.

**Comment by TheShadowOfHassen** [comment]
Totally, fine. It's not like I'm fame hungry or anything, but I do like seeing my name in a game I like.

oh, @nemaara I don't know if you've seen the forum discussion talking about the Scepter of Fire campaign's revision, but someone had some slightly story changing suggestions that I think are worth considering, but I kind of want to know what the higher ups think.

**Comment by TheShadowOfHassen** [comment]
Totally, fine. It's not like I'm fame hungry or anything, but I do like seeing my name in a game I like.

oh, @nemaara I don't know if you've seen the forum discussion talking about the Scepter of Fire campaign's revision, but someone had some slightly story changing suggestions that I think are worth considering, but I kind of want to know what the higher ups think.

**Comment by nemaara** [comment]
Open an issue with suggestions or ask me on the forum or discord or irc, whichever you prefer.

**Comment by TheShadowOfHassen** [comment]
@nemaara I have it on the forums, (https://forums.wesnoth.org/viewtopic.php?p=683719#p683719) I was wondering if you could look it over. I'd PM you, but I don't know who you are on the forums.

**Pull request closed without merging**
