### PR TITLE
Drop support for the l10n-track file (#4716 and #4717)

### PR DESCRIPTION
**Pull request by stevecotton**
This is for the master branch, #4721 has a minimal workaround for 1.14.

The file only had a run-time effect if it listed any files as "fuzzy", which it
hasn't since the last change in 2015. However, that isn't a reason for removing
it.

The reason for removing it is that it doesn't make sense to automatically mark
images as fuzzy when an image changes, because fuzzy is often much better than
untranslated. This is different to the logic for strings, where a single word
can negate the meaning of a sentence. The decision has to be a manual process,
and at that point it might as well be done with the source-control tool's
delete-file function.

Even considering the previous times that l10n-track was used, I can't see a
scenario where it would be useful.

* Scenario: a screenshot needs to be replaced. In this case the new images are
  going to be screenshots too. If the old images are out of date, better to
  just delete them instead of needing the fuzzy mechanism; either option would
  have the same effect of showing the up-to-date-but-untranslated image.

* Scenario: a map is completely redrawn. This seems unlikely, as a completely redrawn
  image could be added as a new map rather than replacing the old one. Even if
  it does happen, it's probably best to just delete the old --overlay.png
  files.

* Scenario: a new landmark is added to a map. Using the existing overlay file
  is still going to be good, as it means the rest of the map is shown
  translated. There's surely new dialogue in the WML files commenting on this
  new landmark, which would be a good place to say
```
    # po: Lorem's Ipsum was added to the map on 24 Jan 2020, please add a label to your language's --overlay file.
```

* Scenario: an old feature is removed from the map. Using the existing overlay
  will have an out-of-date label, and the significance of that would depend on
  how it affects the storyline. This could be significant enough to make
  showing the English labels be a better option than showing the translated
  ones. However, the translated maps could be updated without knowledge of the
  language, so if it's such a significant change then the developer writing the
  new WML should probably do that.

* Scenario: a feature moves slightly on the map. This is an example where the
  l10n-track file has been used, it happened with the Bitter Swamp on the
  bottom-right corner of the title screen. I think it would have been better to
  show the slightly-out-of-date overlay instead of showing the English.

Note about cherry-picking: in the 1.14 branch, the change needs to be applied
to src/picture.cpp instead of src/filesystem.cpp.

### CODE REVIEW

**Comment by AI0867** [comment]
How do we now differentiate between files/overlays that are up-to-date and files/overlays that are "better than nothing", but should still be updated?

Regarding differentiating between "better than nothing" and "worse than nothing", how does the person making the change to the english version make that choice for the localized versions?

**Comment by stevecotton** [comment]
@AI0867 that's a good question that should be discussed, but I think it's orthogonal to this PR. Whether the mechanism used to indicate the decision is this file or the source-control's delete function, the decision is separate to the mechanism.

If we decide to keep this mechanism, I think it should warn translators when an image is ignored because of the "fuzzy" marker.

**Comment by stevecotton** [comment]
I'd like to close this PR (either by merging or deciding not to) in time for the 1.15.4 release. If it's removed then I'll update any Wiki docs that mention it. While there are many suggestions about better support for l10n, I think they're topics for a separate PR, and have logged issue #5011 for that.

@shikadiqueen and @loonycyborg , does this seem good to you?

I've pushed a rebase, but it's just because the old version was a branch from 6 months ago.

**Comment by shikadiqueen** [comment]
My opinion on the matter hasn't changed since my statements in #4717.

**Comment by stevecotton** [comment]
Sorry, but please would you say what your position is?

From the comments in #4717 and #2825, I understand that the whole workflow should change, however I'm unsure of whether you're saying "yes" or "no" to this PR's attempt to chip away at a small part of the bigger issue. From #2825, there's "I feel that there might be some value in not dropping /l10n-track", but that only seems to be if someone integrates it into the pot-update process.

**Comment by shikadiqueen** [comment]
My position is that I don't see any value in this whole system myself.

**Pull request merged**
