### PR TITLE
Store in the database whether the game is a reload or not.

### PR DESCRIPTION
**Pull request by Pentarctagon**

### CODE REVIEW

**Comment by soliton-** [comment]
https://stackoverflow.com/questions/289727/which-mysql-data-type-to-use-for-storing-boolean-values I think using tinyint and 0/1 would be better or that BIT type perhaps.

user_is_moderator, OOS, IS_HOST should probably all use that type.

**Comment by Pentarctagon** [comment]
To do that then, I'd:
* Add a commit here to store OOS, IS_HOST, and RELOAD as 0/1 instead of "Y"/"N".
* After this is put into both 1.14 and 1.15, update all existing data in those columns to match as well.
* Alter user_is_moderator, OOS, IS_HOST, and RELOAD to be BIT(1).

**Comment by soliton-** [comment]
Sounds good. The conversion of the already existing bool fields can also be done independently of this PR. I just noticed when seeing the new bool field here.

**Comment by Pentarctagon** [comment]
The change was pretty straight forward, so I just went ahead and did it here.

**Pull request merged**
