### PR TITLE
add 'unslowable' and 'unpetrifiable' status

### PR DESCRIPTION
**Pull request by newfrenchy83**

### CODE REVIEW

**Comment by newfrenchy83** [comment]
@CelticMinstrel could you review this PR, please? Thancks

**Review by CelticMinstrel — APPROVED** [review]
This looks fine to me.

**Comment by Pentarctagon** [comment]
Is there a reason to not have a unit test for unpetrifiable?

**Comment by newfrenchy83** [comment]
> 
> 
> Is there a reason to not have a unit test for unpetrifiable?

test added.

**Comment by newfrenchy83** [comment]
@Pentarctagon @CelticMinstrel don't forgzt this PR, please.

**Pull request merged**
