### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by gfgtdf**
Fixes (some only partial) for #https://github.com/wesnoth/wesnoth/issues/3925 https://github.com/wesnoth/wesnoth/issues/3742 https://github.com/wesnoth/wesnoth/issues/4438

### CODE REVIEW

**Comment by Pentarctagon** [comment]
Have these been tested?

**Comment by stevecotton** [comment]
The test failure on macos looks like a real bug - signal 6 means something has called `abort()`.

**Comment by CelticMinstrel** [comment]
> signal 6 means something has called `abort()`

Which as likely as not means an uncaught exception was thrown.

**Comment by gfgtdf** [comment]
> Have these been tested?

Not yet i wanted to wait for the ci first,

> signal 6 means something has called abort().

Yes i think it found the issue

**Comment by gfgtdf** [comment]
Tested and the CI passes, will merge it soon

**Pull request merged**
