### PR TITLE
Fix animation truncated immediately after message

### PR DESCRIPTION
**Pull request by newfrenchy83**

### CODE REVIEW

**Comment by newfrenchy83** [comment]
this PR is an soluce for resolve bus in stable branch

**Comment by GregoryLundberg** [comment]
#1617 was closed due to merging Accelerated Rendering. Does this PR need to be ported to the new master, or does the Issue need to be re-opened?

**Comment by newfrenchy83** [comment]
Yed this PR need be ported to new master branch.

**Comment by newfrenchy83** [comment]
I put a PR for master branch

**Comment by jostephd** [comment]
> I put a PR for master branch
#3631

**Pull request closed without merging**
