### PR TITLE
Refactor of menus to remove old markup

### PR DESCRIPTION
**Pull request by CelticMinstrel**
Not quite finished yet (all the editor menus I tested work, but most in-game menus are currently unresponsive).

If anyone wishes to test the editor menus or review the code (which still needs to be cleaned up to remove commented stuff, etc), then feel free. I tested most of them, but couldn't test unit facing (since units can't be placed to access it) and skipped recent maps (in the file menu).

### CODE REVIEW

**Comment by Vultraz** [comment]
For the record, unit placing in the editor has been fixed.

**Comment by Vultraz** [comment]
Unless you're referring to something specific to this PR.

**Comment by CelticMinstrel** [comment]
It didn't look like something specific to this PR - when I tried placing it there was an assertion failure in `unit_ability` because `resources::game_board` was null.

**Comment by CelticMinstrel** [comment]
I think this is better left as part of the conversion of the main game UI to GUI2.

**Pull request closed without merging**
