### PR TITLE
Fix crash when adding/removing hotkeys with no matches

### LINKED ISSUE #3970: Segfault when hotkey filter has no matches
This is basically #3969 for #3759: if you open the "Hotkeys" tab of the preferences dialog, enter a filter that has no matches, and press "Clear Hotkey", wesnoth will segfault. @rocketBANG @addaleax 

Several dialogs have very similar search functionalities:
- hotkeys #3759 
- recruit list #3787 
- recall list
- campaign list (#3829)
and it's been requested for the faction list (#3826).

The state of this particular bug for each of these is:
- hotkeys: this issue
- recruit list: fixed in #3969 
- recall list: fixed in #3476 
- campaign list: doesn't crash, just starts AToTB. This is a minor bug but there's no issue for it.

### PR DESCRIPTION
**Pull request by rocketBANG**
fixes #3970

### CODE REVIEW

**Comment by jyrkive** [comment]
Minor nitpick: the Wesnoth code style doesn't use spaces after keywords like `if`.

**Comment by jostephd** [comment]
Thanks for the fix! Could you add an error message? Silently doing nothing can be confusing.

**Comment by jostephd** [comment]
Sorry, I didn't get a notification for the forced push. Looks good, I'll test and merge before the next release.

**Comment by jostephd** [comment]
Thanks for the pull request and sorry for the late merge!

**Pull request merged**
