### PR TITLE
Improvements in wmlvalidator, wmlgrammar and wmldata

### PR DESCRIPTION
**Pull request by brunomacabeusbr**
- Now it checks translatable lines
- Checks if it is a valid symbol
- Improvement in error checking and return feedback in lists
- Some fairs updates in schema.cfg

And some more things

### CODE REVIEW

**Comment by Vultraz** [comment]
Please write your comment lines in English.

**Comment by brunomacabeusbr** [comment]
I'm sorry, I forgot.

**Comment by Elvish-Hunter** [comment]
For what reason did you need to modify the `.gitignore` file? AFAIK we don't have an `.idea` file in the project, and your PR doesn't seem to introduce one.
Also, bear in mind that symbols can have numbers inside of them (like in the case of the `FLAG_VARIANT6` macro). They can also have lowercase letters (at least, I remember some UMCs using them), but this is usually discouraged to prevent confusion. So, I'd modify the symbol regexp to be at least
`symbol="re ^[A-Z0-9_]+$"`.

**Comment by brunomacabeusbr** [comment]
Regarding the change in `.gitignore`, it is because I use PyCharm, and to keep me send data about my IDE for the project, I decide to put in this file to ignore it.
Would there be any way to Git ignore the `.idea` folder without being so?

Regarding the symbols, ok, but I think that symbols should always begin with a letter, then it is more appropriate is `^[A-Z][A-Z0-9_]*$`

**Comment by brunomacabeusbr** [comment]
I translate multiple files to Python3 (with 2to3 and manual review) and <a href="http://stackoverflow.com/questions/32108392/translating-python2-to-python3-cannot-import-name-wmldata/32108492?noredirect=1#comment52111497_32108492">I need to merge two files</a>.
Yes, the code merge the files are VERY ugly. However, it works. I will work on it to become more readable over the weekend.

I appreciate any help =P

**Comment by Elvish-Hunter** [comment]
> Would there be any way to Git ignore the .idea folder without being so?

Yes, there's a better option. At https://help.github.com/articles/ignoring-files/#explicit-repository-excludes you'll find all the instructions.
> Regarding the symbols, ok, but I think that symbols should always begin with a letter, then it is more appropriate is ^[A-Z][A-Z0-9_]*$

That could work too. However, I'll have to check if symbols starting with a number are allowed, since I never used them in this way, but I suspect that they're supported.
> Translated multiple files for Python3.

No. Doing it in this PR isn't a good idea. PRs should be short, sweet and to the point. If this PR talks about wmldata, wmlgrammar and wmliterator, you should keep the changes limited to these three tools. Everything else must go in another PR.
Also, my strategy for the Py3 conversion consist of a soft approach: in order to keep changes small and manageable, and to intercept bugs in an easier way, I try to emulate as much as possible of Py3 on Py2. See this block at the start of wmllint:

    from __future__ import print_function, unicode_literals, division
    from future_builtins import filter, map, zip
    input = raw_input
    range = xrange

This way, I still need to change a few lines in each file, but I was able to test each update before committing it.

**Comment by Elvish-Hunter** [comment]
OK, now that's better. The only thing left to do is revert the change to .gitignore, after this is done I think that I can merge this PR.

**Comment by brunomacabeusbr** [comment]
Great! Thank you =)

In case I continue to make improvements, I need to open a new pull request or keep this?

**Comment by Vultraz** [comment]
It's up to you. If you want us to merge this you will have to open a new one, but if you'd rather we keep it open so you can continue adding improvements, we can do that too.

**Comment by brunomacabeusbr** [comment]
Because these files are not being used by other users, because they are still very incomplete, and only I'm modifying it, I think is better to keep in my repository. When it is working, merger in master repository.

**Comment by brunomacabeusbr** [comment]
It is already beginning to be "usable" =)
In all the official campaign's `_main.cfg` work, reporting any errors and analyzing every line. The only exception is "Legend of Wesmere", but <a href="http://forums.wesnoth.org/viewtopic.php?f=2&t=42911&start=45#p588515">vultraz told me to ignore it</a>.

I am now working to analyze the <a href="http://wiki.wesnoth.org/ScenarioWML">scenarios</a>. This has MANY attributes and cases to be analyzed. I will take some months to complete.

Some doubts:
<ul>
<li>I can rewrite <a href="http://wiki.wesnoth.org/ValidationFAQ">the article</a> about the schema?</li>
<li>It is necessary to analyze in detail attributes <a href="http://wiki.wesnoth.org/ScenarioWML">such as `map_data`</a>?</li>
</ul>

**Comment by Vultraz** [comment]
What is the status of this?

**Comment by CelticMinstrel** [comment]
Whoa, this is full of merge commits. o.o

**Comment by brunomacabeusbr** [comment]
Well... It is "commitable"... 

I wanted to improve and to document in wiki, however, I haven't time. I'm very busy with college and anothers projects.

What I sent works. It is better than before and it works, but it has a lot to be improved.

**Comment by Elvish-Hunter** [comment]
I manually merged this PR by cherry picking the following commits: 218aaa6, 3210254, 7b6cce4, 8c10049,  f4a9c77, 5e77d8e, 484acb1, 9effb52, 3587e4c, f1006f1, 7ad541c, f960830, b760622, 61d68fa, 0b83b94, 3194b4f, 58d04f0, ab63578,  b4ba701, 4b55170, d5d19ab, 5754a8f.
The commits that I excluded were the merge commits, plus d14b7f0 and its revert a448374.

**Pull request closed without merging**
