### PR TITLE
l10n: Add Ukrainian Logo and Maps

### PR DESCRIPTION
**Pull request by amakriLexa04**

### CODE REVIEW

**Comment by Wedge009** [comment]
@Pentarctagon amakri is the current Ukrainian translation maintainer, so should be fine to merge this? Even back-port?

**Comment by Pentarctagon** [comment]
Needs the copyright info added, otherwise looks fine to merge and backport.

**Comment by amakriLexa04** [comment]
I have a very strange problem, therefore some help would be appreciated. When I run update_copyrights script using _**py update_copyrights**_, it just deletes copyrights.csv and then does nothing for an infinite amount of time.

**Comment by Pentarctagon** [comment]
What is `py`?

**Comment by Wedge009** [comment]
Windows-specific launcher for Python?

**Comment by Pentarctagon** [comment]
@amakriLexa04 what do you mean by "infinite amount of time"? If it's recreating the entire csv from scratch it can take quite a bit of time, but it shouldn't be doing that.

**Comment by soliton-** [comment]
If git is set to convert line endings then copyrights.csv has windows line endings and the last column (MD5) might get the carriage returns depending how the csv reader works. The documentation suggests to open with `newline=''` https://docs.python.org/3/library/csv.html#id4. Can't really tell from the description but maybe that helps.

**Comment by amakriLexa04** [comment]
I'm not an expert in this particular area, so I'm probably doing something wrong.
I am running the script on Windows 10 via PowerShell using the py command, i.e. [py launcher](https://www.infoworld.com/article/3617292/how-to-use-pythons-py-launcher-for-windows.html). After that, the copyrights.csv file is immediately deleted.

> @amakriLexa04 what do you mean by "infinite amount of time"? If it's recreating the entire csv from scratch it can take quite a bit of time, but it shouldn't be doing that.

By an infinite amount of time, I mean 20-30 minutes (maybe more, but I don't have the patience to wait longer). I doubt that it should take that long to create a text document.

From the task manager, I can tell that something is happening and the script is at least doing something, but I don't know what exactly.

Знімок екрана (735)

**Comment by amakriLexa04** [comment]
Wait, after an hour and a half it actually did something! But I think something's wrong, cause I don't see any authors or licenses listed in the .csv

Знімок екрана (736)

Screenshot_1248

**Comment by Pentarctagon** [comment]
It takes that long since it's also retrieving and parsing a bit of the git history for each of the 18k+ files - that's the slowest part.

**Comment by amakriLexa04** [comment]
So because of different path separator, the script considers all existing entries in the .csv to be incorrect and therefore deletes the file. And then it goes through all game's files from and writes them as new licenses? It's a pretty interesting situation...

**Comment by Wedge009** [comment]
Getting a bit off-topic, but I was initially confused by looking at `utils/update_copyright.py` instead of `update_copyrights`. But I had a look at the latter, and it's an interesting mix of `os.path` and `pathlib` (being relatively new to Python and from an OO background, I've usually used `pathlib` in my own code).

https://github.com/wesnoth/wesnoth/blob/e7acc0e3b93ceb984f477c4b713b1cbdfcaa6dae/update_copyrights#L106
I think the issue is that this 'file' object is of type `str` and this is used as the key for the `csv_data` dictionary. When run on Windows, this uses backslashes for the path separator which differs from the slashes currently in `copyrights.csv`.

https://github.com/wesnoth/wesnoth/blob/e7acc0e3b93ceb984f477c4b713b1cbdfcaa6dae/update_copyrights#L90
I think if the `csv_data` key was given as type `pathlib.Path` instead of just `str` when it is read and written to (code snippets above), it would resolve the issue of cross-platform processing because the path separators should always be appropriate to the OS that Python is running on. I did a quick check and two `pathlib.Path` objects, one created with slashes and the other with backslashes but otherwise the same path, returned `True` in an equality test.

**Comment by Wedge009** [comment]
If you pull in current master and retry the copyrights update, I don't think it will treat every file as new any more.

**Comment by amakriLexa04** [comment]
Well, now it deletes the file and also gives this error

Screenshot_1258

**Comment by amakriLexa04** [comment]
Now it deletes everything in the file except the first row, and then writes an error
Screenshot_1259
Screenshot_1260

**Comment by Wedge009** [comment]
So it's failing to write out the lines, not that it's deleting the file. Would be good to know what's in 'final_output'. Wonder why it's even bothering with code page 1251, I thought strings were UTF-8 by default.

**Comment by Wedge009** [comment]
I'm still investigating, but I think the issue now is that existing Unicode characters in the CSV (such as in contributors' names) are not being handled properly on Windows.

**Comment by Wedge009** [comment]
I've verified #9098 is the last thing to get this working on Windows as intended.

**Comment by Wedge009** [comment]
Please have another go.

**Comment by amakriLexa04** [comment]
I have a feeling that I'm doing something wrong. Why is it that every time I synchronize a fork, it writes it into this pull request and restarts checks?

**Comment by amakriLexa04** [comment]
Well, the new update_copyrights works, kinda. If you don't add any new images, the script does its work in just a few seconds and the .csv file is there. But if you add any new images, it just deletes the file and shows an error

Screenshot_1267

**Comment by Wedge009** [comment]
For the synchronisation, I would normally re-base my branch against the updated master. Either way, an update to the branch means an update to the PR, which triggers the CI checks again.

I'm not able to replicate your error (BTW, text is often more useful than images of text). At first I thought there might have been a problem with using a file path with slashes on Windows. `do_hash` works because it's using Python's internal `open` which can handle slashes in file paths just fine. But on my Windows system `do_git` also works because the `git` command can also handle file paths with slashes (instead of backslashes).

On my system, `git --version` returns git version 2.45.2.windows.1. What does yours say?

**Comment by amakriLexa04** [comment]
> BTW, text is often more useful than images of text

I'm sorry, next time I'll send errors in text

> I'm not able to replicate your error

It's kind of awkward situation, I think I accidentally deleted my git yesterday to free some space. I just installed it again and the script works great. Thank you for your work and patience!

Screenshot_1268

**Comment by Wedge009** [comment]
That's a relief, that looks similar to what I got on Windows. Hoping you can get back to the actual work of this PR now!

**Comment by amakriLexa04** [comment]
Well, that's all for this PR, I don't plan to translate any more maps soon. `update_copyrights` works fine, so I added all the necessary information to .csv

**Comment by Pentarctagon** [comment]
This is good to merge then?

**Comment by Wedge009** [comment]
Checks have passed and as I said above, amakri is the maintainer so should be no issues on translation side. The only note was you said earlier copyright documentation needed to be updated which is now done.

**Pull request merged**
