### PR TITLE
Make the "Delay Shroud Updates" option apply to recalls.

### LINKED ISSUE #2196: "Delay Shroud Updates" should apply to recalls
Hi,

Recalling a unit unveils the shroud, and hence is not undoable, even while "Delay Shroud Updates" is enabled.

To reproduce, enable "Delay Shroud Updates" and recall any dwarf onto (8,16) at the very start of HttT Hasty Alliance.  The recall will unveil (4,13) and be non-undoable.  I expect the recall not to unveil any hexes and to be undoable, until "Update Shroud Now" is invoked.

### PR DESCRIPTION
**Pull request by jostephd**
Fixes #2196 (in addition to ca0b5033f06ad83868dc569e973897083042f90b
which was HttT-specific).

### CODE REVIEW

**Comment by jostephd** [comment]
Does this interact correctly with undo/redo?  I'm not sure.

**Comment by gfgtdf** [comment]
yes 'delayed shroud updated' is a part of the redo system. What happens in particular is, that when you then apply the shroud changes (for example manullay by clicking the button) is that game goes though all the elements on the undo stack and applies their shroud changes. This also makes mp sync more complicated since the 'undo stack' is now part of the gamesate.

**Comment by jostephd** [comment]
@gfgtdf Thanks for the explanation; I didn't know that the undo stack was part of the MP sync gamestate.

The reason I asked about undo/redo was that with this patch, I saw sync errors, but they happened even with this patch reverted.  I have now managed to reproduce those sync errors on clean master so I submitted them as #2216.  I also tested this patch in a way that sidesteps #2216 and I believe it to work correctly.

**Comment by jostephd** [comment]
To sidestep #2216 I tested in HttT The Lost General (34,11) rather than in Hasty Alliance.

**Comment by GregoryLundberg** [comment]
rebased and merged

**Pull request closed without merging**
