### PR TITLE
[Achievements] add achievement frames for Icons

### PR DESCRIPTION
**Pull request by knyghtmare**
Will resize to 72x72 on request

Author of Frames: Eleazar (wesnoth's former terrain art director)
Source: <https://opengameart.org/content/painterly-spell-icons-part-3>

image

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
These are far too large to be called just "achievement frames". I mean, obviously they can be used for achievements, but at minimum I don't think they should be in a folder called "achievement frames" when they're 256x256 but achievements force no larger than 72x72.

**Comment by Elvish-Hunter** [comment]
Mentioning @eleazzaar because his icons are used here.

**Comment by doofus-01** [comment]
I'm afraid I'm not totally up to speed on what's happened in the last month or two, is there more context for this?

**Comment by Pentarctagon** [comment]
They're additional frames to use with achievement icons. Right now for example there's:
Screenshot from 2023-02-20 20-19-09

**Comment by doofus-01** [comment]
Ah, I understand now.  Let's give Eleazzaar time to respond, but otherwise I don't see a problem.  I would like a chance to test it before approving though.  I'll look into this next weekend.

**Comment by eleazzaar** [comment]
I've added the 4.0 version of the license to those assets, as requested by Elvish Hunter.

Otherwise I'm not sure what I'm expected to be responding to.

**Comment by Elvish-Hunter** [comment]
> Ah, I understand now. Let's give Eleazzaar time to respond, but otherwise I don't see a problem. I would like a chance to test it before approving though. I'll look into this next weekend.

@doofus-01 Well, at the time of your reply Eleazar already answered to my forum PM, which I sent as CC to Pentarctagon and knyghtmare, and the discussion about it happened in the #development channel on Discord.

> Otherwise I'm not sure what I'm expected to be responding to.

@eleazzaar Indeed there's nothing else to respond to, because you already did :-)

**Comment by Pentarctagon** [comment]
@knyghtmare is the HttT PR waiting on this PR at all?

**Comment by knyghtmare** [comment]
> @knyghtmare is the HttT PR waiting on this PR at all?

Not sure yet. The HttT PR is waiting for me to add the second set on the UI and the actual `[set_achievement]` and `[progess_achievement]` into the scenarios

**Review by nemaara — APPROVED** [review]

**Review by doofus-01 — APPROVED** [review]
I'm not totally sure what I'm approving, but I don't want to be a blocker.

**Comment by knyghtmare** [comment]
This is actually waiting for me to resize the frames to 72x72. I wrote the python code but haven't run it yet

**Comment by knyghtmare** [comment]
and good to go

**Pull request merged**
