### PR TITLE
WIP: Add a hint about not save-loading, and link to it from the "Back to" menu

### PR DESCRIPTION
**Pull request by stevecotton**
This adds a new section to the "Gameplay" help topic, and puts an item that opens that help in the list of save games that's in the "Back to ..." menu.

I'm expecting this to need changes to the prose, and maybe move it to the bottom of the menu.

Can be cleanly cherry-picked back to 1.14.

### CODE REVIEW

**Comment by soliton-** [comment]
Nice idea. I think a note about possibly needing foreknowledge on the highest difficulty would be good.

Another principle that could be mentioned there is that the easiest difficulty should always be beatable with minimum gold.

**Comment by stevecotton** [comment]
I thought the principle was that hard could be completed without foreknowledge, as @jostephd assumed in https://r.wesnoth.org/p644816

In this PR, I'm going to add in the next update something along the lines of "This topic is still under discussion, at least before 1.16.0 assume that the forum threads are more authoritative than the text in the game".

**Comment by nemaara** [comment]
The principle is correct, hard should be winnable without foreknowledge (in fact, it is for every mainline campaign). The thing about winning with minimum gold on easy mode isn't applicable to all campaigns, only for the easier ones. It seems like some of the expert level campaigns expect a certain level of carryover.

**Comment by stevecotton** [comment]
I think this should go as-is in to 1.15.0, even though there will be further discussion about the exact text.

**Comment by soliton-** [comment]
Curious that you link the forum thread were josteph mentions switching to normal difficulty for no foreknowledge playthroughs.


> The principle is correct, hard should be winnable without foreknowledge (in fact, it is for every mainline campaign). 

How do you check that or keep it that way in the future ? Do you constantly look for new people to test play campaigns?
To avoid misunderstandings: I‘m talking about the hardest difficulty no matter what it‘s called. Since it seems fairly impossible for every campaign to have no plot twists or no fog/shroud or so many hints in every scenario so that it is realistic to not do better with foreknowledge either the hardest difficulty is not that hard or you need foreknowledge.

> The thing about winning with minimum gold on easy mode isn't applicable to all campaigns, only for the easier ones. It seems like some of the expert level campaigns expect a certain level of carryover.

Please point out the scenarios where this does not hold, they should be fixed. It is not useful to require players to restart campaigns or bar them from completing any campaign on the easiest difficulty as a matter of principle.
The neat part about this principle is that it is very easy to check. Just get a save or skip to the scenario in debug mode and play it.

**Comment by nemaara** [comment]
I know hard is winnable without foreknowledge because I've played all of the campaigns besides AOI on hard and won them all first time through (furthermore, with the exception of NR, I've done a no loss playthrough of all the expert campaigns). This isn't to say campaigns are properly balanced on hard for the regular player, but only that the AI is too easy to abuse if you know how to do it. Certainly more balancing is better, which is why I also did a rebalance pass on LoW before to make it easier.

Scenarios where carryover is relevant: many in LoW because you get a big chunk of gold from the treasury. Same with NR. TRoW has a ton of scenarios with single player gold values (not varying with difficulty); as an example, S6 is pretty tricky if you only have the starting gold (100) to play with. I usually recall 6-7 units on the scenario, putting my minimum at 120-140. Same deal in SoF, especially S8, you probably want to have more than 200 gold for that scenario. It's been a while, but SotBE seemed to have a few like this as well (I'd need to play it over again to really be sure). 

I don't think expecting at least some carryover is necessarily a bad thing, and additionally, the minimum gold requirement is dependent on player skill too. I don't disagree about this part:

> It is not useful to require players to restart campaigns or bar them from completing any campaign on the easiest difficulty as a matter of principle.

My feeling is that most Wesnoth campaigns are a bit too hard for the average player, which is why I've been trying to reduce the difficulty on the couple I've worked on.

**Comment by stevecotton** [comment]
I think we should talk about expectations of the user-visible difficulty levels, the "Beginner, Easy, Normal, Challenging, Difficult, Nightmare" set. Going to try and push that discussion on the forums, in the previously-linked thread, https://r.wesnoth.org/p644816

> How do you check [no need for foreknowledge] or keep it that way in the future ? Do you constantly look for new people to test play campaigns?

It's often a conscious thought, "I can safely rush forward in to the fog", or "I know I can send an unaccompanied scout down that way to grab villages".

**Comment by soliton-** [comment]
I'm sure lots of people beat all the campaigns on hard over the years, me included. The problem though is that that's one point in time and you cannot repeat it easily once changes are inevitably made.

The other problem is that now we can say "all campaigns are beatable on hard by nemaara" but what does that mean for another player? How do you compare skill? Especially skill in abusing the AI that might also change some time. If you're confident we can keep all mainline campaigns beatable without foreknowledge by some player definition that's cool with me. It just seems quite difficult how to even define that and thus how to check it's still true.

Re beatable on easy with minimum gold: If there are special scenarios were it's virtually guaranteed you have significant carry-over because you founf a treasure at the end of the previous scenario or so then it's fine to expect that of course. But the point of the rule is to avoid getting players to an unwinnable state without actually losing a scenario. Since that's just frustrating.

If there are scenarios that are tricky but beatable then it depends on tricky for who and what that exactly means. If they are tricky for you then I would think that that might nevertheless be a sign that they're too hard. If it means an average player should be able to learn some tactics to still win (perhaps there is even meant to be some tactical trick to the scenario) then I think that is perfect especially for expert campaigns. You're not at an unwinnable point but you need to improve your skills to move on.

Thanks for the specific scenario mentions I'll try those when I find some time.

**Pull request merged**
