### PR TITLE
Nerf Dwarvish Steelclad and Lord

### PR DESCRIPTION
**Pull request by nemaara**
Based on Krogen's argument here: http://forums.wesnoth.org/viewtopic.php?f=15&p=648448&sid=f2e07511b458d64bdb1b650c47a70651#p648335. I actually feel like there needs to be a slight HP nerf as well, but that might end up being overkill.

### CODE REVIEW

**Comment by slavrenyuk** [comment]
I like this changes. I think that Steelclad's description should be updated a bit. "Outfitted in **the strongest** plate and mail of Knalgan forges..." -> "Outfitted in excellent plate and mail of Knalgan forges..." Also consider adding a sentence to Sentinel's description saying that his armor is very good too, because now it is about the same as Lord's armor.

**Comment by nemaara** [comment]
Done.

**Comment by gfgtdf** [comment]
I think that we have a rule that an advancement must be better or at least as good as the previous unit in all aspects. Or must have at least one advancement with that property.

**Comment by slavrenyuk** [comment]
@gfgtdf this rule is not violated here.

**Comment by gfgtdf** [comment]
The resistances are worse than if the lvl 1 version as I see it.

**Comment by slavrenyuk** [comment]
@gfgtdf 
lvl 1 Fighter has blade=80 https://github.com/wesnoth/wesnoth/blob/master/data/core/units.cfg#L1011
lvl 2 Steelclad has blade=70
lvl 3 Lord has blade=60

https://wiki.wesnoth.org/UnitsWML#.5Bmovetype.5D
> [resistance]: describes how much damage the unit takes from different types of attacks. The attribute type=resistance makes the unit receive resistance percent of damage, or resist 100-resistance percent of damage from attacks with type=type. So for example, a resistance of fire=110 means, this unit will receive 110% of damage, or have a resistance of -10% as displayed in-game. A value of fire=0 would mean, the unit receives no damage and therefore has a resistance of 100%.

**Comment by Krogen2** [comment]
Hey, first of all, thank you for taking action on this so quickly. You might want to check the forums, there is still a discussion going on, apparently, some would prefer hp reduction rather than resistances. Even though i'm personally not convinced, you might want to see the other side's arguments.
My suggestion was to give only 10% extra blade resistance to Steelclad instead of blade, pierce and impact at the same. So it would only benefit from advancement, just not so much as it used to. And then 10% more to blade again at level 3.
I also played with the thought of increasing xp requirement at level 3, but you can read that on the forums in detail.

**Comment by nemaara** [comment]
At the very least, I think a nerf to pierce is necessary because many ranged units (archers, namely) have ranged piercing damage. Part of what makes the Lord/Steelclad so obnoxious is that they get stuck on hills/mountains and you can barely hit them with non magical or marksman attacks. In the situation you send an archer against them, even if you hit them, it then doesn't do much damage. Leaving them slightly more vulnerable to pierce would at least help offset this a bit (and note that 20% is still pretty good pierce resistance). 

I already said above that I'd like to nerf their HP a bit (on top of resist nrefs), so maybe the best course of action is to allow the Lord to have 30% resistance to impact, and slightly lower HP?

**Comment by soliton-** [comment]
> My suggestion was to give only 10% extra blade resistance to Steelclad instead of blade, pierce and impact at the same. So it would only benefit from advancement, just not so much as it used to. And then 10% more to blade again at level 3.

That's exactly what is done here, no?

**Comment by Krogen2** [comment]
Yes. Someone just said that resistances shouldn't get worse after advancement, while that was not the case here. Just wanted to make it clear that i never said anything like that.
I agree that reducing pierce is more important than impact. But at level 1 Troll Whelp is quite an okay choice to stand up against Dwarvish Fighters. At level 2, it's not really the case anymore. And while i'm personally not a fan of Woses vs Dwarves, they do okay against them in a fight, even if they don't trade that well. Now we have 2 unit lines that used to be a fair match and that become inferior after advancement, because of impact resistance. (Could find more, like Heavy Infantry, but i think that's enough...)
Though i'm just a player making suggestions. If something comes out of this, may it be impact or HP nerf, i consider that a success.

**Comment by soliton-** [comment]
I think the resistance nerf is fine since the increase didn't make much sense lore wise anyway. It also better differentiates from the guard line.

Some additional HP decrease or XP increase could still be warranted but this is a good first step at the least

**Comment by Krogen2** [comment]
Wait, now i see on the forums i actually came up with ideas that included making the unit worse than it is at level 1 in some cases. Though that was not my first or even second solution to the problem, i'll keep this rule in mind in the future.

**Comment by gfgtdf** [comment]
@slavrenyuk 

hmm okay i didnt knew there was an resitance increase when leeling uo to lvl 2. so a assumed decreasing the lvl 2s resitance woudl give it a resitance decrease (in pierce in impace) , neverming then

**Comment by nemaara** [comment]
Added a small nerf of -3 HP to both the Steelclad and Lord.

**Pull request merged**
