### PR TITLE
Do a better job of catching pbl parse errors for addons

### PR DESCRIPTION
**Pull request by drzaal**
#3971 
Fail gracefully when an addon has an invalid pbl file, and make sure to push errors to the log and addon errors.

Should I include the pbl path somewhere in the logging?

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
If I recall correctly, there is a `NOEXCEPT` macro defined (probably in global.h(pp) or thereabouts?) which might be better to use in place of `throw()`, since that syntax is deprecated. (The macro should, at least in theory, expand to `noexcept` where supported or `throw()` otherwise.)

**Comment by drzaal** [comment]
I took a minute to familiarize myself with NOEXCEPT, which I hadn't worked with before. I do not believe that would be appropriate? Throw is not deprecated as an operator, but just as a specifier. Right?

**Comment by CelticMinstrel** [comment]
I didn't even know `BOOST_NOEXCEPT()` existed... I was expecting you to use just NOEXCEPT, which should be defined in "global.hpp" in the Wesnoth source.

**Comment by CelticMinstrel** [comment]
Okay, I just checked, and it appears that it was removed at some point, so in that case just use `noexcept` (in lowercase).

**Comment by Pentarctagon** [comment]
Can this be merged?

**Comment by drzaal** [comment]
Unless CelticMinstrel has another note?

**Comment by CelticMinstrel** [comment]
I have nothing further to say on this.

**Comment by Pentarctagon** [comment]
Merged and backported.
Thanks!

**Pull request merged**
