### PR TITLE
rename [filter_ability(_active)] to experiemental_ability

### PR DESCRIPTION
**Pull request by newfrenchy83**
because it is experimental the tag of filter is changed except for [overwrite][filter_specials]

a bug is fixed also for case or ability diffrent of drains, berserk etc in checking 'value' attribute

### CODE REVIEW

**Comment by stevecotton** [comment]
> a bug is fixed also for case or ability diffrent of drains, berserk etc in checking 'value' attribute

Please make this a separate PR, instead of having feature-creep.

**Comment by stevecotton** [comment]
I think this is ready to merge.

As mentioned in #7992, there's an open question about what to do with this deprecation message; however I think it's better to merge as-is and discuss what's deprecated in the issue ticket instead.
```
deprecated_message("[effect]apply_to=remove_ability [abilities]", DEP_LEVEL::INDEFINITE, "",
    "Use [filter_ability] instead in [effect]apply_to=remove_ability");
````

**Comment by newfrenchy83** [comment]
> I think this is ready to merge.
> 
> As mentioned in #7992, there's an open question about what to do with this deprecation message; however I think it's better to merge as-is and discuss what's deprecated in the issue ticket instead.
> 
> ```
> deprecated_message("[effect]apply_to=remove_ability [abilities]", DEP_LEVEL::INDEFINITE, "",
>     "Use [filter_ability] instead in [effect]apply_to=remove_ability");
> ```

changed message for now, message changed anew when 'experimental' will be removed.

**Comment by newfrenchy83** [comment]
@stevecotton deprecated message removed

**Comment by newfrenchy83** [comment]
> Has the wiki been updated as well?

yeah, i already updated wiki for rename.

**Pull request merged**
