### PR TITLE
[1.18] Restore force-pushed commits

### PR DESCRIPTION
**Pull request by stevecotton**
@Wedge009 is there anything wrong in this? I didn't push it back because I wasn't sure whether the force-push was accidental or intentional, so waiting for you to say if there's something bad somewhere in these 5 commits.

Branch-name is just what I had locally tracking 1.18, but given that it's restoring Wuzzy's German translation (commit by @sevu), it seems appropriate.

Reapplies
* #9045
* #9053
* e28041573ac7405d38a02cd4d7751ed020d670e3 Fix "span" regex
* #9054
* d75639205d40ee6ec3ff8ad162213fb5cd93deee German translation update

### CODE REVIEW

**Comment by Wedge009** [comment]
My mistake, sorry. I noticed something odd with my local repository, but I thought I was pushing to my own fork, not the original. Thanks for noticing and fixing this.

**Review by Wedge009 — APPROVED** [review]

**Comment by Pentarctagon** [comment]
Force pushing should be disabled for 1.18 now as well. If you have rules for a branch at all the default is for it to be disabled, but apparently the default with no rules setup is to allow force pushing and rules don't get automatically applied to the new branch when creating it from another branch that has rules.

**Comment by gfgtdf** [comment]
> but apparently the default with no rules setup is to allow force pushing and rules don't get automatically applied to the new branch when creating it from another branch that has rules.

This does make sense tho: all branches are forked of from master, so if such a machanism  existed it would in most cases just block forcepushing all branches.

**Comment by Wedge009** [comment]
Again, sorry for the mistake. Be assured that if I do need to force-push I never use `--force`, always `--force-with-lease`.

**Pull request merged**
