### PR TITLE
Fix variable hides variable

### PR DESCRIPTION
**Pull request by GregoryLundberg**
Introduced by 49d0af34

### CODE REVIEW

**Comment by AI0867** [comment]
I would prefer wrapping the previous `team* t` and associated if-block in another block so it goes out of scope before the for loop.

Alternatively, you could attempt to turn that check (does this side exist, and if so, does it own this village) into a oneliner, though I'm not sure if that would remain very readable.

**Comment by GregoryLundberg** [comment]
I, too, would prefer to put it into a block of its own. But that presumes the future reader (1) notices the extra two characters, and (2) realizes what they do.  A more natural read would assume the same variable in use in both places; which is semantically true but syntactically false.

This is a prime example of code which should be rewritten to eliminate the smells.

But as a patch, simply renaming one of the variables is more clear. So, I went with a clear, understandable, commit history, instead of rewriting perfectly good code just to eliminate a bad smell.

**Comment by Vultraz** [comment]
I've pushed an alternative fix: fcaa4ef

**Comment by Vultraz** [comment]
@GregoryLundberg BTW, please feel free to introduce fixes such as the one above in future. It wasn't too intrusive and made the code neater overall.

**Pull request closed without merging**
