### PR TITLE
Add build which uses higher level of optimization

### PR DESCRIPTION
**Pull request by Pentarctagon**
Adds a build to scons which uses a higher level of optimization than available by default with build=release.  Anecdotally, I can say that it does seems to make Wesnoth create the cache and start a scenario a bit faster, and for whatever reason creates an executable ~4MBs smaller than build=release(16 vs 20.1).  I am unaware if there's a good way to actually benchmark to test for any speed improvements though, or what kind of WML/lua operations would make good candidates for benchmarking.

Currently only works for building on Linux, as far as I know.  Tested using g++ 5.4.0 (default for Ubuntu 16.04/Mint 18).

I have no access to testing on Macs.

As for Windows, -O3/-O2 plus LTO fails to compile when setup according to [my guide](https://forums.wesnoth.org/viewtopic.php?f=5&t=40694) due to reporting (for some reason) finding earlier definitions of methods.  -O1 plus LTO compiles, but creates a non-working executable (immediately crashes on launch).  Removing LTO allows compilation to complete, however -O3 somehow also ends up creating a non-working executable, though has been happening for some time now.  LTO without any of the -Ox options does produce a working executable, but it seems to be slower than the -O2 of build=release.

### CODE REVIEW

**Comment by aginor** [comment]
I'm not in front of a computer so I can check, but can we please make sure that cmake and scons have the same flags? We shouldn't updating the one and bit the other unless it's too bring them in sync.
On 29 Oct 2016 7:27 p.m., Pentarctagon <notifications@github.com> wrote:Adds a build to scons which uses a higher level of optimization than available by default with build=release.  Anecdotally, I can say that it does seems to make Wesnoth create the cache and start a scenario a bit faster, and for whatever reason creates an executable ~4MBs smaller than build=release(16 vs 20.1).  I am unaware if there's a good way to actually benchmark to test for any speed improvements though, or what kind of WML/lua operations would make good candidates for benchmarking.

Currently only works for building on Linux, as far as I know.  Tested using g++ 5.4.0 (default for Ubuntu 16.04/Mint 18).

I have no access to testing on Macs.

As for Windows, -O3/-O2 plus LTO fails to compile when setup according to my guide due to reporting (for some reason) finding earlier definitions of methods.  -O1 plus LTO compiles, but creates a non-working executable (immediately crashes on launch).  Removing LTO allows compilation to complete, however -O3 somehow also ends up creating a non-working executable, though has been happening for some time now.  LTO without any of the -Ox options does produce a working executable, but it seems to be slower than the -O2 of build=release.



You can view, comment on, or merge this pull request online at:
  https://github.com/wesnoth/wesnoth/pull/847

Commit Summary
Update SConstructUpdate SConscriptUpdate SConscript

File Changes

    M
    SConstruct
    (7)
  
    M
    src/SConscript
    (4)
  
    M
    src/lua/SConscript
    (4)
  

Patch Links:
https://github.com/wesnoth/wesnoth/pull/847.patchhttps://github.com/wesnoth/wesnoth/pull/847.diff

**Comment by Pentarctagon** [comment]
I've never used cmake before, but assuming I can get that figured out and working, is this something which would end up getting merged?

**Comment by loonycyborg** [comment]
cmake and scons already have same options on default build variant afaik. I'm not sure we should be making any requirements on other build variants. And this PR is adding another build variant, and not changing default options.

**Comment by loonycyborg** [comment]
I see you used gcc-ar/gcc-ranlib, probably due to LTO. I wonder if it'll work with ctool=clang..

**Comment by shikadilord** [comment]
LTO has the unfortunate tendency to be broken for some platforms/targets and consume an absurd amount of memory. I'd suggest that it isn't enabled by default.

**Comment by Pentarctagon** [comment]
@loonycyborg using clang already doesn't work for me, even if I revert the changes I made here locally.  Running scons as:
`scons build=release ctool=clang cxxtool=clang++ -j 1 --config=force`

results in an error([log](http://pastebin.com/00ZDi4cZ))

and the contents of my .scons_options_cache, just to be doubly sure, since I've found scons doesn't seem to always replace existing entries in this file, even if they've changed:

> default_targets = 'wesnoth,wesnothd'
> ctool = 'clang'
> cxxtool = 'clang++'

clang --version after `apt install clang` returns:
> clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)

Moreover, LTO doesn't seem to work with clang at all anymore, since [somebody removed the plugin for it](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819333) since 3.8, and the only suggestion seems to be to build the plugin manually.  Said plugin, LLVMgold.so, is also not available in 3.9.

This plugin is available in 3.7, but for some reason 3.7 fails the pre-requisite checks when run as:

> scons build=release ctool=clang-3.7 cxxtool=clang++-3.7 -j 1 --config=force

and never gets to actually build Wesnoth([log](http://pastebin.com/w3gK8NU4)).

I've added the additional text:

> LINKFLAGS=Split("-fuse-ld=gold -flto")

which is as close to getting clang to work as I've been able - ie: this is the point at which it complains about the missing shared library([log](http://pastebin.com/K99xHfra)).  Neither of these prevent gcc/g++ from working([log](http://pastebin.com/wX7pYUcq)): using ld.gold causes no problems, and passing -flto to the linker is ignored([source](http://stackoverflow.com/a/31688314)).

@shikadilord Alright, I'll make that change.

**Comment by Pentarctagon** [comment]
I've added the ability to enable/disable the LTO options.  I'm not sure what should be done about clang, as it seems to have problems even with the regular release build.

If there are no other issues though, I'll start making changes to cmake as well.

**Comment by Pentarctagon** [comment]
@aginor @loonycyborg - comparing cmake and scons, there already seem to be a fair number of differences between their builds.

**scons build options**
base and release: sets CCFLAGS as "-O2"
debug: sets CCFLAGS as "-O0 -DDEBUG -ggdb3"
glibcxx_debug: sets CPPDEFINES as "_GLIBCXX_DEBUG _GLIBCXX_DEBUG_PEDANTIC"
profile: sets CCFLAGS and LINKFLAGS as "-pg"

**cmake build options**
Release: which uses "-O3"
Debug: which uses "-g"
RelWithDebInfo: which uses "-O2 -g"
MinSizeRel: which uses "-Os"

In fact, their debug and release builds don't even use the same options, and each has two build options that don't exist on the other.  I'm not saying I shouldn't add this build option to both, just that if there was an expectation that scons and cmake are currently doing the same things, then that seems to not be true.

**Comment by loonycyborg** [comment]
-O3 shouldn't definitely be used by default. If cmake uses it in release mode then we should change it to -O2. -O3 is suited only for non-default "aggressively optimized" variant like the one you're adding.

**Comment by shikadilord** [comment]
I don't see the point in overriding that upstream default. Do you have a more elaborate reason against allowing -O3 by default?

**Comment by Pentarctagon** [comment]
I haven't tried with cmake, but with scons, building with on Windows with tdm-gcc 5.1 (which is what both my guide, and the code::blocks guide, uses) and -O3 results in a successful compilation but a broken executable - it crashes immediately on trying to launch it, and has for at least several months now.  So unless there's some part I missed that's already changing the default on Windows to something besides -O3, the default configuration for cmake's Release build has not worked on Windows for some time now.

Which also, to me at least, seems to indicate that either cmake on Windows is barely used, or it's also doing something else differently from scons which is allowing -O3 to create a functioning executable.

Either way, if both scons and cmake are going to be supported for building Wesnoth, then at the very least they should use the same flags for the same builds.

**Comment by Vultraz** [comment]
Sounds like a scons problem. My CodeBlocks release build (which I use extensively for development to avoid long link times with Debug) works perfectly fine with -O3 and tdm gcc 5.1.0.

**Comment by loonycyborg** [comment]
http://stackoverflow.com/questions/11546075/is-optimisation-level-o3-dangerous-in-g
Many people's experience shows that -O3 is less stable than -O2 and may make program slower. If it's upstream default in cmake we should make a PR changing it to -O2 too.

**Comment by shikadilord** [comment]
I rather doubt the CMake developers didn't know what `-O3` entails before making it the default for Release builds, and I’ve been using `-O3` with Wesnoth (SCons) since 2008 without any issues (it probably helps that a) we most decidedly do not rely on UB, which can be drastically altered even with -O1; b) do not ship any esoteric/low level code). In fact, I remember that back then it seemed to help greatly with animation and scrolling lag compared to `-O2` on a rather weak CPU. Your mileage may vary, of course, as one of the comments above shows.

@Pentarctagon If you ever decide to figure out why -O3 doesn't work for you, perhaps you could stop by the IRC channel and compare CodeBlocks' generated command lines with @Vultraz or see if you can get a backtrace. That said, Wesnoth has in fact been plagued by UB issues that crop up even with `-O0` (!) as of the past few months, and that is bound to cause some non-deterministic behavior on different platforms, build configurations, and days of the week. Not sure if all of them have been fixed by now, but one in particular caused `-O0` test suite builds to crash instantly for me, whereas `-O3` builds would pass all tests; just to give you an example of how severe the situation is/was.

**Comment by Pentarctagon** [comment]
[One other thing](http://public.kitware.com/pipermail/cmake/2016-May/063379.html) I found regarding cmake and -O3, for what it's worth.

I had been planning to try and get both cmake and code::blocks setup on my Windows PC, and comparing if their defaults reproduce the same crash-on-launch as scons.  As long as either one of them creates a working executable at -O3, I should be able to pretty quickly compare and test any differences, though I'm not sure that would help at all with determining what code, specifically, is causing the problem now.

Debugging with optimization enabled can generally [have a lot of problems](https://gcc.gnu.org/onlinedocs/gnat_ugn/Debugging-Optimized-Code.html) though, which is why I was surprised to see cmake having a build with both -O2 and -g.  Would getting a trace of the crash even be helpful at -O3?

Assuming I can get the scons with -O3 issue figured out though, the scons release build should instead be set to -O3 from -O2 so as to match cmake, correct?

**Comment by loonycyborg** [comment]
@shikadilord I'm pretty sure that they didn't. It's obvious to me -O2 is more likely to work on various non-standard platforms and build configurations and thus is the safe default choice. People who know can always activate -O3 on their own. Mind you -O3 might still be good default for wesnoth in particular, but I'm still not sure about that.

**Comment by Pentarctagon** [comment]
Maybe this is a silly question, but is it even possible to build Wesnoth with clang right now?  On my Mint PC with clang 3.8 and the `release` build, both cmake and scons fail to link the Wesnoth executable with the error:

> undefined reference to `boost::re_detail::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'

On my Windows PC, also using clang 3.8 with scons' `release` build and `ctool=clang cxxtool=clang++`, it fails every prerequisite check except for: pango with cairo backend, and fontconfig.

Changing nothing but `ctool=gcc cxxtool=g++`, allows a successful build.

**Comment by CelticMinstrel** [comment]
All the Mac users build with clang in XCode, so it's definitely possible. My recent scons commits also make a scons build work with clang on Mac (though I need to add -stdlib=libc++ to my LD_FLAGS and CXX_FLAGS, because I have a really old version of GCC's libstdc++ with no C++11 support). That's the debug build, mind you. It's the same clang version as you're using, though.

I have clang installed on my Windows 7 machine, but not libc++ or libstdc++; I'll give it a try with scons+clang+msvcprt though.

**Comment by loonycyborg** [comment]
I see one interesting difference: -mms-bitfields. I distinctly remember it to be required by gtk related components, though that could have changed considering cb works without it.

**Comment by Pentarctagon** [comment]
@loonycyborg I'm not actually sure where that's coming from - it doesn't seem to exist in any of the scons config files, or anywhere within the directory I cloned Wesnoth to.

Other differences between code::blocks and scons, now that I've looked into them a bit more:

1. The dependencies they use seem to be significantly different, or at the very least there seems to be a lot of unnecessary files within the scons dependencies.
2. Scons uses the same version of tdm-gcc as code::blocks, but scons uses the 64-bit variant and then passes in `-m32` to the compiler/linker and `-F pe-i386` to windres, while code::blocks just uses the 32-bit variant of tdm-gcc.  Trying to build with scons + 32-bit tdm-gcc fails with the error:

> src\desktop\paths.cpp: In function 'std::__cxx11::string desktop::user_profile_dir()':
> src\desktop\paths.cpp:175:65: error: 'SHGFP_TYPE_CURRENT' was not declared in this scope
> HRESULT res = SHGetFolderPath(nullptr, CSIDL_PROFILE, nullptr, SHGFP_TYPE_CURRENT, profile_path);

@shikadilord I just updated, and something apparently has changed in the last few weeks.  Now compiling with scons and `-O3` creates a wesnoth.exe which can launch - but it still crashes when starting a scenario immediately before "Starting game..." appears.  Recompiling with `-O3  -DDEBUG -ggdb3,` gdb gives the backtrace as:

> Program received signal SIGSEGV, Segmentation fault.
> #0  0x0000002b in ?? ()
> #1  0x0140d970 in vtable for unit ()
> #2  0x00000001 in ?? ()
> #3  0x00000014 in ?? ()
> #4  0x00000017 in ?? ()
> #5  0x00000000 in ?? ()

**Comment by loonycyborg** [comment]
Probably it comes from pkg-config then

**Comment by Pentarctagon** [comment]
Yup, it was coming from glib-2.0.pc.  It does not seem to be required either, as changing it to `-mno-ms-bitfields` did not affect compilation, nor did it affect Wesnoth crashing when compiled with `-O3`.

I also looked at the specific flags being enabled by `-O3` via the command `gcc -O3 -Q --help=optimizers`, and then tried adding them one by one on top of the flags which are also enabled by `-O2`.  Those flags are:

> -fgcse-after-reload
> -finline-functions
> -fipa-cp-clones
> -fpredictive-commoning
> -ftree-loop-distribute-patterns
> -ftree-partial-pre
> -funswitch-loops
> -fvect-cost-model=dynamic (=cheap with -O2)
> -ftree-slp-vectorize
> -ftree-loop-vectorization

The final two are the ones which are causing problems.  Without either of them, but with the other flags listed, Wesnoth is able to compile and start a scenario with no issues.  Adding `-ftree-slp-vectorize` results in Wesnoth compiling, but then crashing when trying to start a scenario.  Instead adding `-ftree-loop-vectorization` results in Wesnoth compiling, but then crashing when trying to start the application.  Adding both of them also results in Wesnoth compiling, but then crashing when trying to start the application.  However, when using `-O3`, which should also have both of these enabled, Wesnoth compiles, but then crashes when trying to start a scenario, not when trying to start the application.  This doesn't seem to make sense, but I'm not sure of a way to have gcc give a complete list of the flags it's using as it's actually compiling - trying to add `-Q --help=optimizers` to scons resulted in a bunch of gibberish being printed.

The 32-bit version of tdm-gcc, which code::blocks uses, reports having all the same flags enabled by `-O3` as the 64-bit version does.  So, assuming that the flags being reported are accurate (which I'm not quite sure I believe, due to the above discrepancy), it seems to me that the problem is either with the 64-bit version of tdm-gcc, or perhaps with the libraries used by code::blocks vs scons.

**Comment by Pentarctagon** [comment]
@loonycyborg It turns out the `-mms-bitfields` is enabled by default [since 4.7](https://gcc.gnu.org/gcc-4.7/changes.html)(under IA-32/x86-64):

> Windows mingw targets are using the -mms-bitfields option by default.

I can also confirm this by using `gcc -Q --help=target`, which lists `mms-bitfields` as enabled.

@loonycyborg @shikadilord @Vultraz I am able to get scons to compile with `-O3`.  The problem was, even though the `-m32` and `-F pe-i386` flags were used to enforce a 32-bit build, since this is the 64-bit tdm-gcc, it was also defaulting to `-march=x86-64`.  The 32-bit variant of tdm-gcc, on the other hand, was defaulting to `-march=pentiumpro`.  After changing `-O3` to `-O3 -march=pentiumpro`, Wesnoth compiled and I was able to launch Wesnoth and start a scenario without crashing.

@CelticMinstrel Did you ever try compiling with clang on Windows 7?  Also, I'm a bit curious; if you change clang on your Mac to use the default release optimization of `-O2`, does it still compile successfully?

**Comment by CelticMinstrel** [comment]
I did try, but it couldn't even locate basic libraries so I gave up fairly quickly. I can try a release build on my Mac (I assume that would use -O2 just as it does on other platforms).

**Comment by CelticMinstrel** [comment]
The -O2 build works fine but seems to have trouble launching (I'm not sure whether it's stuck in a loop or just slow, but the latter seems more likely). Did you want me to try -O3 or something too?

**Comment by Pentarctagon** [comment]
If you could try `-O1` and `-O3` as well, it would be interesting to see if they both suffer from the same problem as `-O2` or not.  I'm not particularly hopeful though, given that `-O2` doesn't seem to quite work either and clang seems to have some difficulties optimizing Wesnoth at all.

If both `-O1` and `-O3` also don't work, then that would also mean that currently the only way to build a functional Wesnoth executable with clang on Linux, Windows, or Mac is to use the `-O0` flag, which for something that's specifically [recommended on the wiki](https://wiki.wesnoth.org/Compilingwesnoth#Tips) seems pretty bad.

**Comment by Pentarctagon** [comment]
I used pentiumpro since that's what the Code::Blocks 32-bit tdm-gcc defaulted to; I have no idea what instruction sets that enabled/disables, or which of them would be important for Wesnoth.

**Comment by Pentarctagon** [comment]
@aginor Comparing `gcc -march=x86-64 -Q --help=target` to `gcc -march=pentiumpro -Q --help=target`, they both seem to actually have the same flags enabled.

**Comment by Pentarctagon** [comment]
`-march=pentiumpro` has been added to cmake as well now.  If anyone has a different suggestion for what it should be, just let me know.

In any case, I think that's everything, so unless there are any other issues, I'll (finally) add the LTO build to cmake as well.

**Comment by aginor** [comment]
@Pentarctagon there's no difference because x86-64 is not a valid target and it prints the output of "generic", which is an alias for "i686".
Reading the documentation seems to suggest that "i686" may be what you should use instead
https://gcc.gnu.org/onlinedocs/gcc-4.9.2/gcc/i386-and-x86-64-Options.html

**Comment by Pentarctagon** [comment]
> there's no difference because x86-64 is not a valid target and it prints the output of "generic", which is an alias for "i686".

Oh for the love of... _Why_ does it print x86-64 then, on both Windows+tdm-gcc and Linux+gcc?

Anyway... according to that link for i686:

> When used with -march, the Pentium Pro instruction set is used

so it would seem that i686 is also an alias for pentiumpro.

**Comment by CelticMinstrel** [comment]
So I haven't yet tried -O1 or -O3, but I realized that I messed up when testing -O2 - I'd had a shell-script called "wesnoth" that runs Wesnoth from the XCode build directory, and I was building with a script that calls scons and then copies "wesnoth-debug" to overwrite the executable in the XCode build directory... but of course, building a release build overwrote that shell script, so I was actually running Wesnoth directly instead. This doesn't work because it can't find its nib. When I manually copied it into the app package in XCode's build directory, it worked. So... I'm pretty sure that means that the -O2 build _does_ work with clang on my Mac.

**Comment by Pentarctagon** [comment]
Alright, got the nacl stuff removed.  I'm going to test this a bit more tomorrow, figure out how to combine some of these commits, then everything should be good to go.

**Comment by Pentarctagon** [comment]
I have added the `-s` option, since it reduces the executable size a decent amount, and since this build should never, ever be used for any kind of debugging anyway.  Using `-O3` already makes backtraces basically useless even with full debugging enabled, and who knows what LTO would do to it on top of that.

Speaking of the executable size though, I tried with a few different settings, and this is what I got on my Linux Mint PC:

**wesnoth**
-O3: 21.3 MBs
-O3 -flto: 16.0 MBs
-O3 -flto -s: 11.4 MBs
-O3 -flto -s  -ffunction-sections -fdata-sections -Wl,--gc-sections: 11.3 MBs

**wesnothd**
-O3: 1.8 MBs
-O3 -flto: 1.2 MBs
-O3 -flto -s: 854 KBs
-O3 -flto -s  -ffunction-sections -fdata-sections -Wl,--gc-sections: 833 KBs

So given the relatively small size reduction by `-ffunction-sections -fdata-sections -Wl,--gc-sections`, I've not added those flags.

**Comment by Pentarctagon** [comment]
Also somewhat interestingly, that error I mentioned above with clang isn't actually a clang problem - I can reproduce the same error with gcc 6.2.  Apparently it's some sort of ABI incompatibility due to a gcc bug being fixed, and all affected libraries need to be rebuilt with the fixed gcc ([source](https://bugzilla.redhat.com/show_bug.cgi?id=1331983)).  Apparently this has been a known problem for clang for some time ([source](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=797917)).

**Comment by Pentarctagon** [comment]
Alright, so... I tried to squash the first 3 commits, which I think worked, but then for some reason it also then went and duplicated every other commit.  I tried again, and this time it seems to have instead squashed all the commits into one.  I'm not really sure how that happened, and I'm not really sure how I would go about putting everything back to the way it was before, either.

**Comment by CelticMinstrel** [comment]
To put it back how it was before, you can use the git reflog ('git reflog' to view it). To fix it once you know which reference you need, "git reset --hard HEAD@{2}" or similar (the 2 may be wrong).

**Comment by Pentarctagon** [comment]
Alright, done.

**Comment by Pentarctagon** [comment]
So, is there anything else I need to do for this to get merged?  Or is it just waiting for someone to do it at this point?

**Comment by CelticMinstrel** [comment]
Just waiting for someone to do it. I'm not doing it mainly because this isn't really my strong area and I haven't reviewed it closely.

**Comment by loonycyborg** [comment]
in SConstruct you could use BoolVariable instead of EnumVariable for enable_lto

**Comment by loonycyborg** [comment]
I'm considering to change name of the variant from "optimize" to "optimized". Would it be fine for you?

**Comment by Pentarctagon** [comment]
Sure.

**Comment by Pentarctagon** [comment]
In CMakeLists.txt, the following lines were missed for the renaming:

101
117
565
574

**Comment by loonycyborg** [comment]
Should be fixed now

**Pull request merged**
