### PR TITLE
Add a line break between "Special Notes:" and the bullets.

### PR DESCRIPTION
**Pull request by jostephd**

### CODE REVIEW

**Comment by Vultraz** [comment]
There already is a linebreak in the help browser before the special notes. Why is this needed?

**Comment by jostephd** [comment]
This adds a line break between `Special Notes:` and the bullets. I thought it might look better this way.

**Comment by Wedge009** [comment]
I prefer it as it currently stands, but won't object if someone decides to merge this.

Also, are the special notes translated? While checking this it didn't look like they were...

**Comment by CelticMinstrel** [comment]
Bullets? Did someone change how special notes work? Last I checked they were all combined into a single paragraph.

**Comment by Wedge009** [comment]
Bullets are in master but not 1.14:
https://github.com/wesnoth/wesnoth/blob/master/data/core/macros/special-notes.cfg

I think the addition of the bullets is also why they're no longer translated in 1.15.

**Comment by jostephd** [comment]
> I think the addition of the bullets is also why they're no longer translated in 1.15.

Should we try to add the bullets into all po files directly, or something? Do some languages use something other than `•` for bullets?

**Comment by Wedge009** [comment]
I don't know about other languages' use of something other than bullets, but I find it hard to imagine so, with bullet points being such a common formatting option. I was thinking this is one of those cases where pofix could be used - a bit annoying re-translating all these strings because of the bullets, even though the text itself hasn't changed.

**Comment by jostephd** [comment]
Let's discuss that further on https://github.com/wesnoth/wesnoth/issues/4297.

**Comment by jostephd** [comment]
@Pentarctagon suggests not adding the empty line but underlining `Special Notes:`.

**Comment by Wedge009** [comment]
Underline sounds good to me.

**Comment by Vultraz** [comment]
Disagree. I suggest making "Special notes" bigger.

**Comment by CelticMinstrel** [comment]
I suggest making it bigger _and_ underlining it.

**Comment by jostephd** [comment]
We're bikeshedding. I'm going to just leave it as is. Feel free to reopen if you disagree.

**Pull request closed without merging**
