### PR TITLE
Healing: Do heal on turn 1.

### PR DESCRIPTION
**Pull request by jostephd**
Discussed on the forums: https://r.wesnoth.org/t48817

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
That thread sounds kinda controversial; I wonder if this should be made an option in the scenario WML?

**Comment by gfgtdf** [comment]
i currently think it should not heal on the first turn of the the first player only, so that the scenario designer can place 'wounded' units at start, it also make somehow sense as there is side turn start but not really a side turn 'transition' for the first turn of the first player.

**Comment by jostephd** [comment]
Rebased to new master

**Comment by gfgtdf** [comment]
I wonder whether these checks are sufficient, meaning if for example UMC change the initial turn number (eg change the turn numbesr in a prestart event), how should the code behave.

**Comment by GregoryLundberg** [comment]
The old code said "if turn > 1" and we're changing it to read "if turn > 1 or side > 1".

So if they played with turn numbers, this is a non-issue.

The only issue I could see if is they (effectively) don't have a "side 1", or they depended upon no healing occurring for any side on turn 1.

If they're playing games with turn and/or side numbering, there's not a lot we can do about it.

I imagine, in the rare case where they actually depend upon no healing at all throughout all of turn 1, well, a change log entry (which this PR is missing, BTW), should warn them. But there's not a lot we can do about that.

**Comment by GregoryLundberg** [comment]
The only solution I can see is to have a internal side number (index into array?) and a mapping from external side to that index.

What we mean is: "Regardless of the side number you assign, the first side to move on the first turn does not get a healing phase. But, thereafter, healing phases occur for all sides and turns."

**Comment by gfgtdf** [comment]
> Or we could just set a (default: false) doHealingPhase which is set true at the end of every movement phase.

I think this is the best solution, it also has the advantage that it allows umc to easily enable the old behviour of they want.

**Comment by GregoryLundberg** [comment]
Agreed

**Comment by GregoryLundberg** [comment]
I think the idea is, while this could merge as-is, it would be better to take a few minutes and change the side/turn test(s) into a test against a boolean which is set to false when starting a scene and set true at the end of every side/turn.

I guess what he's suggesting is that there be some option to revert back to the old behavior. I would agree if this goes into 1.14, but don't think it's needed if this goes into master (1.15) only (which is the current milestone).

**Comment by gfgtdf** [comment]
> I don't understand how adding an internal variable would help UMC.

my idea way to make the doHealingPass_ variable accessible via lua/wml like `wesnoth.game_config.do_healing_phase = true/false`

**Comment by jostephd** [comment]
I'm not sure what I think of the idea that if there's no side 1, then the first side on turn 1 shouldn't receive healing. Is there currently any special significance to `side=1`? That is, if I took a scenario that has a `side=1` and incremented all side numbers, and updated all references to them (like `side N turn M` event names), would there be any visible change?

**Comment by gfgtdf** [comment]
well yes, the colors ans side numbers in the sttus panels would be different. also side numbers have to be in order so when you want to do that you still have to put a side with side=1 at the top of the file with controller=null (disabled side)

**Comment by jostephd** [comment]
Rebased, converted side/turn number check to boolean, confirmed side/turn numbers are right and healing happens on side x turn y whenever x>1 or y>1 (in a scenario that did have side 1).

**Comment by gfgtdf** [comment]
you also have to read/write do_healing_  when loading scenarios/saves, otherwise it will be reset to 0 when a game is reloaded.

**Comment by jostephd** [comment]
Moved the logic to `game_state` as discussed on IRC.

Right now it's initialized to false in the `game_state` ctor and set to true in `play_controller`. This feels like the logic is split between two classes.

**Comment by jostephd** [comment]
<details><summary>Code for testing</summary>

```
diff --git a/data/campaigns/The_Hammer_of_Thursagan/scenarios/01_At_the_East_Gate.cfg b/data/campaigns/The_Hammer_of_Thursagan/scenarios/01_At_the_East_Gate.cfg
index a5aac138328..eb4973bd075 100644
--- a/data/campaigns/The_Hammer_of_Thursagan/scenarios/01_At_the_East_Gate.cfg
+++ b/data/campaigns/The_Hammer_of_Thursagan/scenarios/01_At_the_East_Gate.cfg
@@ -58,7 +58,9 @@
             [modifications]
                 {TRAIT_LOYAL}
             [/modifications]
+            hitpoints=1
         [/unit]
+        {UNIT 1 (White Mage) 1 14 ()}
     [/side]
     # wmllint: validate-on
 
@@ -82,6 +84,8 @@
             grouping=offensive
             attack_depth=5
         [/ai]
+        {UNIT 2 (Elvish Shyde) 6 14 (max_moves=0)}
+        {UNIT 2 (Wolf Rider)   6 15 (max_moves,hitpoints=0,1)}
     [/side]
 
     [label]
```

</details>

**Comment by jostephd** [comment]
Added a test. It reveals that rest healing isn't done on turn 2, which looks like a bug. It also reveals that rest healing is done _even if the units moved_ which is definitely a bug.

**Comment by jostephd** [comment]
> Added a test. It reveals that rest healing isn't done on turn 2, which looks like a bug.

Fixed by the new push.

> It also reveals that rest healing is done _even if the units moved_ which is definitely a bug.

Test artifact. (The test unnecessarily used max_moves=0 to immobilize the units.)

**Comment by CelticMinstrel** [comment]
...what's this about not having a side 1? I didn't think that was allowed?

**Comment by gfgtdf** [comment]
> ...what's this about not having a side 1?

you can have a 'null' controlled side1 in which case the engine skips the turn of that side, making basicially side 2 the first side.

**Comment by CelticMinstrel** [comment]
Oh... would side 2 have had no healing phase in that event before this merge, then?

**Comment by gfgtdf** [comment]
no this merge only changes healing of the first turn (and fixes abug reated to rest healing). I think the commitmessaes are quite self explaining.

**Pull request merged**
