### PR TITLE
 add harm abilities

### PR DESCRIPTION
**Pull request by newfrenchy83**
this harms ability must resolve problem of negative value in heals without bug in calculate because using proper function

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Still against the base concept here. Is there no other way to resolve this bug involving negative heals? If possible, I'd prefer to see some other way.

**Comment by jostephd** [comment]
What's the bug involving negative heals?

**Comment by newfrenchy83** [comment]
@jostephd when two units with heals abilities and negative value are adajacentto unit to harm the highest value is used, if one have -6 and other -4 then the patient is harmed to -4 hp

**Comment by gfgtdf** [comment]
> What's the expected behavior when unit A is adjacent both to a unit B with heals +8 and to a unit C with heals -4 (or harms 4, which is the same) at the same time?

iirc the point is that this does not behave the same: with heals+8 and heals -4 the highest value is chosen becasue it is 'heals' so it will heal +8. With heals8 and harms4 the  values will be applied seperately so it will heal8 and harm4 which will result in a total of +4 hp.

**Comment by CelticMinstrel** [comment]
I don't see any reason why that behaviour can't be produced without creating a new type of ability.

**Comment by jostephd** [comment]
@gfgtdf Will they be applied _one after the other_ or simultaneously? That makes a difference if the unit has `hitpoints <= 3` or `hitpoints >= max_hitpoints-7`.

**Comment by newfrenchy83** [comment]
One afyer the other.

**Comment by CelticMinstrel** [comment]
If I understand correctly, the game applies all heals (and regenerate) abilities simultaneously.

**Comment by gfgtdf** [comment]
@jostephd i don't know as i didnt write this pr i just explained the problem that this pr is trying to solve.

**Comment by newfrenchy83** [comment]
Game apply highest value of villages, regenerayes or heals + resting. For don't have this problem i prefer add an trie harms abilities applied after healing and with proper animation( this a unit have both ).

**Comment by jostephd** [comment]
@gfgtdf Sorry, I didn't mean to put you on the spot, just to clarify that I was responding to your comment which wasn't the last one on the page.

@newfrenchy83 Could you explain why adding a `harms` ability would be better than implementing *equivalent behavior* using `heals` abilities with negative arguments? The code of do_healing() and friends can be changed to handle negative and positive arguments differently.

**Comment by newfrenchy83** [comment]
i already triedthis but the result is not that what i expect. i will try yet but i not really trust

**Comment by newfrenchy83** [comment]
the calculation is done in heal.cpp:215 with heal_effect.get_composite_value(). for resolve problem of negatives value i must modify abilities.cpp:1138 effect::effect(const unit_ability_list& list, int def, bool backstab) :
	effect_list_(),
	composite_value_(0) that who will have impact on all abilities of weapon_specials.

I prefer add a harms abilities instead to modify an function withheavy consequences.

**Comment by CelticMinstrel** [comment]
I prefer modifying the function. What are these heavy consequences you refer to?

**Comment by jostephd** [comment]
Instead of modifying the effect code I think you could modify heal.cpp only. Split `heal_list` into two lists, one for positive heals and one for the negative heals, construct two effect objects, and combine them manually? You'll have to negative the negative heals before passing them to effect.cpp.

**Comment by newfrenchy83** [comment]
@jostephd split into two list? I want try but how make difference with two heals? I can use (iif heal_effect.get_composite_value() <0) for effect object but before this line tags abilities is the only information for distincts list(regenerates, heals, villages). For @CelticMinstrel suggestion, modify effect will affect calculation in leadership, resistance and weapon_specials/abilities and i don't know if this is a good idea.

**Comment by newfrenchy83** [comment]
replaced by https://github.com/wesnoth/wesnoth/pull/3739. i used @CelticMinstrel suggestion.

**Comment by newfrenchy83** [comment]
i reopen this PR in wait to find anoter solution.

**Comment by newfrenchy83** [comment]
i finally resolve this in https://github.com/wesnoth/wesnoth/pull/3748

**Pull request closed without merging**
