### PR TITLE
1.19 Boats update

### PR DESCRIPTION
**Pull request by doofus-01**
Fresh start from #6781 because this is just to update/add a couple of boats; there are other people working on boats now, no need to get the whole set here.

___________________________
EDIT:  Others referenced are https://github.com/wesnoth/wesnoth/pull/6781#issuecomment-2440118418 and https://github.com/wesnoth/wesnoth/issues/9367#issuecomment-2409014788

The scope of this PR is:

- [x] Transport Galleon
- [x] Pirate Galleon - I shouldn't make many configuration changes here, but this seems like a unit that could use some review to make it more distinct.
- [x] Derelict Hulk - sort of a "zombie ship".  Ghost ships or Phantom ships are an overlapping yet separate thing and still fair game for anyone else.
- [x] Fireship - a different sort of "zombie ship"

For portraits, there are the sailor images by LordBob https://forums.wesnoth.org/viewtopic.php?p=665657#p665657, but actual ships would be better for default profiles.  I don't remember if `small_profile` (https://wiki.wesnoth.org/UnitTypeWML) still works, but ideally it does and we can use the sailors for dialogs and ships for help pages.

### CODE REVIEW

**Comment by Wedge009** [comment]
So what should happen with #6781? Close as those 'other people' make their own PRs?

**Comment by doofus-01** [comment]
> So what should happen with https://github.com/wesnoth/wesnoth/pull/6781? Close as those 'other people' make their own PRs?

Let's just leave it be for now, close it when/if this gets merged.

--------------------------------------
Current animations aren't ready for prime-time, but they should at least give an idea of the framework I'm seeing for this.

**Comment by doofus-01** [comment]
I still need to do something about the portraits and fireship, but the rest can be reviewed.

**Comment by doofus-01** [comment]
I've asked LordBob about including his sailor images, I'll hold off adding those until he's had a chance to respond.

I expect the unit stats on anything here will get changed later, but the images and animations are mostly finished, just need a Fireship portrait at a minimum.  Maybe it will be done next week.

**Comment by DuncanusDillius** [comment]
Im not sure if these are what you have been referring to, but yak made some rather good animated ships, some of which might fit your guidelines.

**Comment by ForestDragon-wesnoth** [comment]
The Mechanical race is used extremely often in UMC for stuff that has nothing to do with ships. Adding ship names to every single mechanical unit would ruin the theme/lore of dozens of add-ons, so I believe it ship names should not be included.

**Comment by Tezereth** [comment]
Mechanical is basically already a race that was mainly made for ships, and a few other units. Furthermore, ships basically never get "traditionally" recruited, so when it comes to names, it never really comes into action, and ships in campaign scenarios can easily be given names.
I don't think it's worth breaking UMC's over something so small. Though there might be other solutions if ships really need to have random generated names without having to create a whole new race. I know it's possible for traits at least.

**Comment by doofus-01** [comment]
I'm not going to address the Galleon (which has a note that it isn't a real unit?) or the Boat here.  There will be other ship PRs.  I'll merge once CI passes.

**Comment by doofus-01** [comment]
Dammit github, I didn't mean to commit this!  I was trying to resolve a conflict, nothing more.

**Pull request merged**
