### PR TITLE
SoF: fix thursagan's arcanister advancement breaking in some cases

### PR DESCRIPTION
**Pull request by knyghtmare**
Fix for the following bug:
image

### CODE REVIEW

**Comment by stevecotton** [comment]
I'm not sure about this, but think all of `[modifications]` can be overwritten on unit rebuild. So I'm not sure about this fix.

**Comment by Pentarctagon** [comment]
What would be a specific situation to test this with?

**Comment by knyghtmare** [comment]
> What would be a specific situation to test this with?

As discerned on Discord, in _Gathering Materials_, get Thursagan into a cart and dismount.

Expected:
1. After dismount, max XP is 210 and blue XP bar

Bug:
2. 150 XP and purple XP bar

**Comment by Pentarctagon** [comment]
And you retested that situation after applying this fix, and the bug no longer occurred?

**Comment by knyghtmare** [comment]
> And you retested that situation after applying this fix, and the bug no longer occurred?

yes.

**Comment by knyghtmare** [comment]
If this patches the bug, should it be merged?

**Comment by stevecotton** [comment]
Looks good to me.

**Comment by stevecotton** [comment]
Based on the discussion of who-should-merge-what yesterday, I should. Sorry for taking so long.

@knyghtmare please will you backport it?

**Pull request merged**
