### PR TITLE
fix cumulative=yes cancel negative value of some abilities(1.16)

### PR DESCRIPTION
**Pull request by newfrenchy83**
suggest an other resolve to https://github.com/wesnoth/wesnoth/issues/6269 issue

### CODE REVIEW

**Comment by Pentarctagon** [comment]
How does this fix the issue?  All it adds are some attributes to schema and a unit test.

**Comment by newfrenchy83** [comment]
> 
> 
> How does this fix the issue? All it adds are some attributes to schema and a unit test.

excuse me, this is not fix the issue, but suggest other way to resolve.

**Comment by Pentarctagon** [comment]
For 1.16 the fix would probably be to have Formation be a regular weapon special that's added onto each weapon, rather than an ability that automatically adds the weapon special to all of the unit's attacks.

**Comment by newfrenchy83** [comment]
> 
> 
> For 1.16 the fix would probably be to have Formation be a regular weapon special that's added onto each weapon, rather than an ability that automatically adds the weapon special to all of the unit's attacks.

Uh?

**Comment by Pentarctagon** [comment]
Commented in the wrong PR, whoops.

**Comment by newfrenchy83** [comment]
i added a fix for cumulative=yes, for in case of negative value, this is the lowest value and not the highest who was used

**Pull request closed without merging**
