### PR TITLE
Expand reduce function to both fold and reduce

### PR DESCRIPTION
**Pull request by luther9**
The file `data/lua/functional.lua` contains a `reduce` function which, when receiving a falsey `identity` argument, changes it to `0`. This makes it impossible to initialize the calculation with `nil` or `false`. `functional.reduce(t, 'or', false)` will always return `0`.

While changing the function to accept any 3rd argument, I decided to rewrite it to `fold`, which always includes the init value in the calculation, and `reduce`, which only looks at the identity value if the array is empty.

Since `functional.lua` is not documented on the wiki, I wonder if maybe this change can be merged with the stable branch.

### CODE REVIEW

**Comment by Pentarctagon** [comment]
Did you mean to make this an issue rather than a pull request?

**Comment by luther9** [comment]
No, I've made a patch. Why wouldn't that be a pull request?

**Comment by Pentarctagon** [comment]
Ah, I was confused about there originally being hundreds of other commits listed for some reason.

**Comment by Pentarctagon** [comment]
Also worth noting that new API features can't be added to a stable branch, so this would need to be made against the master branch.

**Comment by luther9** [comment]
Ok, I guess I'll have to check out master and redo this later then.

**Comment by luther9** [comment]
The new version of this PR is #6337. That one is based on master, not 1.16.

**Pull request closed without merging**
