### PR TITLE
Add shallow water to oasis like ford terrain

### LINKED ISSUE #8753: Oasis should have a (shallow water / sand) dual typing
### Describe the desired feature

It would make sense for an oasis tile to have a dual typing that hints at the water. E.g. when moving a mermen unit through sandy terrain, a player would instinctively try to land them on an oasis, assuming they'd be in their element there.

As far as I understand Wesnoth terrain rules, units tend to get the terrain defense of the half that is most beneficial to them. So giving the oasis dual typing shouldn't mess anything up for sand-favoring units.

### PR DESCRIPTION
**Pull request by Jonathan-Kelly**
Closes  #8753

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
The diff looks like it potentially does a lot more than it says. What does removing the `=_bas` lines actually do? And was the removed comment checked to see if it's relevant?

**Comment by Jonathan-Kelly** [comment]
Yeah, you are right... fixed it.

Somehow I had completely forgotten that oasis was just an overlay which _optionally_ adds desert sand. It had no physical effect of its own except to add healing to the tile. Now (with this PR) it also adds shallow water to the tile (on top of whatever base terrain is there, which is just sand by default).

**Comment by soliton-** [comment]
So now `aliasof` presumably should be `Dt,Wst` so it shows up under water terrain in help as well.

**Comment by Jonathan-Kelly** [comment]
Good catch, also added `water` to the `editor_group` list.

Discovered a bug with the preexisting oasis code. When oasis is placed as an overlay terrain (using shift click in the map editor) it will falsely show as having sand, in both the editor and scenario sidebars. So if laid over green grass the tile will show as sand/flat but units on that tile will not get defense or movement effects from sand and the tile will not look sandy. This bug was introduced by a hack [(here)](https://github.com/wesnoth/wesnoth/commit/20e6ee719077ee5e6df809a931c104df94b9ec06) to force oasis to show up under sand in the help menu.

If I undo this hack to fix the bug then oasis terrain will no longer show as a "sand" type terrain in the help (though it will show up as a shallow water terrain in the help and as both desert and water in the map editor).

**Comment by stevecotton** [comment]
> If I undo this hack to fix the bug then oasis terrain will no longer show as a "sand" type terrain in the help

Leave the hack in place for this PR, but I've a work-in-progress PR to improve the engine for that - #8798.

**Comment by Jonathan-Kelly** [comment]
Excellent, thanks for taking that on.

**Review by nemaara — APPROVED** [review]
As long as it behaves as expected I'm down with this change.

**Pull request merged**
