### PR TITLE
Gui2 font scaling

### PR DESCRIPTION
**Pull request by gwhitney**
This is pull request is independent of, but related to, #4851. That one addresses the fonts and layout controlled by the theme. This one allows for, and implements, the ability to scale the text font size and layout of GUI2 visual elements according to the screen pixel pitch. Specifically, over 1200x900 pixel dimensions, text_font_size is computed proportional to the pixel pitch. Also certain dialogs are allowed to take up a certain fraction of the screen size, rather than be limited to a numerically fixed number of pixels high or wide. The primary mechanism for facilitating these scalings is to allow the values for the keys text_font_size, maximum_width, and maximum_height to be formulas rather than just numerical constants. In addition, the SDL pixel pitch is exposed in the variable screen_pitch_microns, within GUI2.

### CODE REVIEW

**Comment by gwhitney** [comment]
I see that Windows does not like "or" - will change to "||" shortly

**Comment by gfgtdf** [comment]
you still have some `or` and `and` in your code.

Also i personalyl would prefer if your would squash the 'fixup' commits (fix whitespace and fix `or`) directly into the commit that caused them (`Allow formulas to com ...`).

**Comment by gwhitney** [comment]
@gfgtdf, ugh, really sorry; it's very hard to grep for "or" and "and" as they occur in the documentation a lot as well. Had no idea they were not supported on Windows, as I think of them as pretty standard C++ at this point (and I have no access to Windows...) Will try to flush out the rest.

As far as "squash the 'fixup' commits" goes, I have to admit that although I would say I have pretty solid coding background, I am a relative git neophyte. This commit squashing is not something I am aware of. Is it something I can do on Github? Do I have to close this pull request and make a new one on a new branch to get all of the changes into just one (or probably two, one for the source code and one for the .cfg files) commits? I will google "how to squash git commits" but any quick pointers are very welcome.

**Comment by gfgtdf** [comment]
> This commit squashing is not something I am aware of. Is it something I can do on Github?

No

> Do I have to close this pull request and make a new one on a new branch to get all of the changes into just one (or probably two, one for the source code and one for the .cfg files) commits? I

Please no, we had one guy that did that and opened a bunch of prs until we totally lost overview ...

> quick pointers are very welcome.

Well on your local git repo you open the termainan and type `git rebase -i HEAD~5` where 5 is the mound of commits that you want to edit it will look like this

```
pick f739100 Differentiate divide by zero errors
pick 5990499 Allow formulas to compute GUI2 text_font_size and window maximum_heig…
pick 04dfa2d Modify GUI2 config files to scale font size with screen pixel pitch
pick a23bbb1 Merge branch 'master' of https://github.com/wesnoth/wesnoth into gui2…
pick f56092b Revert inadvertent whitespace changes
```

first you want to move the 'fixup commit before the copmmit that you want to fix up so like this:

```
pick f739100 Differentiate divide by zero errors
pick 5990499 Allow formulas to compute GUI2 text_font_size and window maximum_heig…
pick f56092b Revert inadvertent whitespace changes
pick 04dfa2d Modify GUI2 config files to scale font size with screen pixel pitch
pick a23bbb1 Merge branch 'master' of https://github.com/wesnoth/wesnoth into gui2…
```

then for the commit that you want to be sqashed into the previosu commit to replace the "pick" with `f`:

```
pick f739100 Differentiate divide by zero errors
pick 5990499 Allow formulas to compute GUI2 text_font_size and window maximum_heig…
f f56092b Revert inadvertent whitespace changes
pick 04dfa2d Modify GUI2 config files to scale font size with screen pixel pitch
pick a23bbb1 Merge branch 'master' of https://github.com/wesnoth/wesnoth into gui2…
```

then you save exit your exteditor and gi shodul do the rest

**Comment by gwhitney** [comment]
OK, I think I got things "squashed" properly. The commits now showing in the pull request look pretty clean to me. Hopefully I got all of the logical connectives like Windows likes now. I will check back at the Travis job in a few hours. Thanks for the git pointers!

**Comment by CelticMinstrel** [comment]
> I see that Windows does not like "or" - will change to "||" shortly

Officially, I believe you need to include a header to use "or"; either that, or you used to need to and Windows hasn't updated to no longer require it.

That said, please don't use "or".

On-topic, I mainly just popped in to make sure you were using `typed_formula`, which you are, so everything seems good enough to me as far as I understand it.

**Comment by Pentarctagon** [comment]
Any reason to not merge this and #4851 then?  @gwhitney I assume these have both been tested at a few different resolutions?

**Comment by gfgtdf** [comment]
I see no reason not to merge this

**Comment by gwhitney** [comment]
Yes, I have set my monitor at a wide variety of resolutions (= effective pixel pitches, not merely pixel dimensions of the window) and run with this code. The fonts covered by this PR scale nicely and maintain essentially identical physical height on the screen regardless of what resolution I set the monitor to. 

Some notes/caveats: #4851 does not by itself do anything to modify any of the font sizes covered by the theme (some items in the display, such as the stuff in the right sidebar, are not controlled by GUI2). #4851 simply enables themes with larger base resolutions than the current standard 1024x768, and in that PR I supplied a link to a (pretty rough) prototype example of such a theme. So if you run with just the *code* changes in this and #4851, without changing your theme, you get a pretty motley assortment of varying font sizes -- but let's be clear, I already would consider that a very significant readability/usability improvement. But further development will be needed to get a nice, consistent, uniform, professional-looking UI at very small pixel pitches. And also to be clear, there are some fonts - e.g the quote of the day and the buttons on the main menu/opening screen -- that do not seem to be controlled by either the theme or this pull request, so further work will be needed to get those to look good.

But all told, I would very much appreciate and recommend your merging this. I just wanted to be clear that it does put the UI in a not-fully-consistent state, and be sure you are comfortable with that as a stepping-stone for further progress (by me and hopefully others -- although I should also be clear that I have neither the skills, time, or inclination for things like fixing up enlarged background or icon pngs that will be needed to put the finishing touches on a truly complete small-pixel-pitch end-to-end UI.)

**Comment by gwhitney** [comment]
Oh and PS, I should note that both of these PRs have *zero* effect at main window pixel dimensions below 1200x900 (chosen arbitrarily as something larger than the current standard 1024x768).

**Comment by Pentarctagon** [comment]
Mainly what I'm asking is: are there any cases where there would be a regression in usability, compared to the current state of things?

The "I just wanted to be clear that it does put the UI in a not-fully-consistent state" does make me kind of nervous, especially given that not all that long ago we had an incomplete UI rework merged into master and then it hit [obstacles](https://github.com/wesnoth/wesnoth/issues/3538) that ended up preventing it from being finished, which resulted in many people needing to spend time re-adding [nearly a thousand commits](https://github.com/wesnoth/wesnoth/issues/3614) that had happened in the mean time to a reverted master branch.

So if there are any cases where usability would be made worse where it's not already pretty bad, I would prefer this be merged into a feature branch until that's no longer the case, rather than directly into master.

**Comment by gwhitney** [comment]
I just read through some of those PRs, had no idea that all happened, sorry to hear.

As for this PR, it definitely does **not** put the game in an unplayable state, but it does put the game in some cases in what some might characterize as an "ugly" state: various inconsistencies in font sizes and I will admit in some cases fairly cruddy-looking layout. But let's be clear: these are all cases in which the current code requires folks with eyesight like mine and monitor pitches like mine to take off my glasses and put my face two inches from the screen and squint to make out what the program is telling me. (I am being literal here.)

Currently the "worst" bit under this code that I am aware of is the Preferences window. Layouts that used to fit in its "tiny little" window (on a small pixel-pitch monitor) now don't. So there are scrollbars in both directions, and some of the controls are in slightly odd places, and it can be tricky to find the control you want, and some of the fonts on it are _still_ itty-bitty for reasons I have not yet understood. But it's not unusable --  everything is still there, and responds, and nothing is any _smaller_ than it was.

Maybe you can take a look on a sub-150-micron monitor with a window dimension over 1200x900 and judge usability for yourself?

So here are some options: (1) Merge and see how folks with small-pixel-pitch monitors react, and hopefully they will see this as a path to improvement and some will pitch in fixing the layouts that I have not yet been able to grok; (2) change the window pixel dimension where anything happens up from 1200x900 to say 2650x1920 so that it will only affect truly pixel-large windows which can only happen on pretty tiny-pixel-pitch displays where (imho) Wesnoth is fairly close to unusable as it stands, or (3) do this feature branch thing with whatever implications that has for this line of effort eventually coming to fruition -- sorry I don't have a sense of that due to limited involvement with large public open-source projects.

Sorry not to be able to be clearer than that. From my point of view it is a big usability *win* with no downside, but I recognize that inconsistent fonts might look uglier to some than consistently tiny fonts, and scrolling around on the preferences windows might be more annoying to others than me, given that in the current code all preferences windows except for "advanced," everything Just Fits (TM).

Hopefully I have provided enough info so that you folks as maintainers can make the call. If there's anything else you'd like me to do/test/report on, I am willing and happy to do so to help this direction of improvement become a reality.

**Comment by Pentarctagon** [comment]
I have monitors with a pixel pitch of 0.2768mm, 0.233mm, and 0.13725mm, so I'll take a look probably in the next day or two then.

**Comment by Wedge009** [comment]
I haven't looked at this in detail but I wonder if it complements or conflicts with the existing font scaling implementation. (I thought it was re-introduced in master for 1.15 but after a fresh build today I can't find it any more).

**Comment by gwhitney** [comment]
Hmmm.. I am not at all familiar with the "existing font scaling implementation." I just arrived on the scene, in some sense -- I played Wesnoth years ago, and to be frank, looking for some COVID diversion, thought I would give it another try to see how it had developed over the years. I found lots of new-to-me scenarios, which was very pleasant, but that I had a great deal of trouble playing on my small-pixel-pitch laptop because the fonts were unreadably tiny. So I just started trying to make various things readable, starting with the theme, and then attacking GUI2 -- the whole process is somewhat hampered by the fact that different displays of text seem to be controlled in very different places in the code.

Anyhow, if there's an existing more unified approach to making Wesnoth readable/usable/looking nice on a wide variety of displays and my from-scratch attempts should be dropped, totally understand -- I can just play on my branch until something better comes along. I was just trying to share things that definitely made the game more playable for me. But I definitely don't want to interfere with any more comprehensive approach.

**Comment by Wedge009** [comment]
There was an existing implementation - and if I understood it correctly I think the intent was the same as what you describe, setting up the UI to be legible on dense DPI screens. But it didn't work very well and we have (or had) a lot of issues recorded against the limitations of GUI2 and text scaling efforts. So if your ideas do a better job it may be worth your continued efforts.

Closest issue that I can find that's still open is #2219.

**Comment by Pentarctagon** [comment]
It was commented out of 1.15 ([here](https://github.com/wesnoth/wesnoth/blob/ba461bd204fea393469f74120ca935a9755a0245/src/gui/dialogs/preferences_dialog.cpp#L477-L479), [here](https://github.com/wesnoth/wesnoth/blob/ba461bd204fea393469f74120ca935a9755a0245/data/gui/window/preferences/03_display.cfg#L212-L262)) relatively recently due to being too buggy, and was never available in 1.14 for the same reason.

**Comment by gwhitney** [comment]
Aha. Thanks for the pointers, I was able to look over the existing font_scaling code. There is definitely a difference in approach between that code and this PR and my efforts at a small-pixel-pitch theme. Namely, the font_scaling code seems to attempt to simply enlarge every font at rendering time from what is requested, and as such is likely more comprehensive that what I am offering, but does nothing to ensure there is actual screen space available for the enlarged characters. The approach in my recent efforts has been instead to calculate what font size you actually want at each place that fonts are requested (which is many more disparate places, which is why my efforts so far are definitely partial and leave some things tiny) but then to also try to make sure there is room for the resulting text, which is easier in this approach because on the request side you know what stuff you're laying out and how you're going about it.

I think it's up to the maintainers which approach, if either, they'd like to pursue for Wesnoth. My only suggestion for the Wesnoth developers to consider in this matter is that ultimately to cope with the exploding (exploded?) array of different devices and screen sizes and pixel pitches and the like, is that Wesnoth should take a page from modern web design and gradually abandon use of anything denominated in pixel dimensions (except at the very lowest implementation/rendering level) and instead work in terms of screen/window-size percentage for gross layout and text em/ex sizes for dialog layout. That and making many more of the elements (sidebar, topbar, minimap, etc) manually rescalable/repositionable during gameplay, remembering their layout from run to run. (I realize those are big-ticket items, and I am not unfortunately able to volunteer to implement them, just mentioning it in terms of trying to aid the decision of whether either the existing font_scaling code, or this PR, if either, is an incremental step in the right direction.)

Two final comments: (1) imho, #4851 fixes an out-and-out bug in existing theme layout code which is a blocker to experimental effort to provide large-pixel-dimension themes, and should be merged regrdless, (2) If this PR is merged, I am volunteering to help with any proximate additional efforts needed to get wesnoth into what would generally be regarded a "decent" state (if it's not already).

**Comment by Wedge009** [comment]
Yes, the 'does nothing to ensure there is actual screen space available' is the problem with the existing implementation - I did not know until Pent's post that it had been disabled again.

The proliferation of form factors is probably the main problem with the existing GUI2 framework - when it was initiated I think PC screens were still the primary way of accessing Wesnoth. There has been many a discussion, outside the scope of this particular text-scaling issue, regarding how Wesnoth adapts to this change.

Thanks for your efforts thus far. Even if it is only an incremental improvement it is better than none.

**Comment by Pentarctagon** [comment]
As an update on this, I asked @shikadiqueen to review this PR and #4851 since she knows UIs/GUI2 a lot better than I do.

**Comment by CelticMinstrel** [comment]
> if I understood it correctly I think the intent was the same as what you describe, setting up the UI to be legible on dense DPI screens.

As the person who wrote the previous font-scaling implementation, I can say that this was not the intent. My intent was to give people a way to put Wesnoth essentially into "big print" mode – if the fonts are two small to read, especially for someone with poor eyesight, and regardless of pixel pitch or whatever, they can be made bigger.

I think ideally the two methods would complement each other – if I understand correctly, the purpose of _this_ pull request is to make the fonts a consistent _physical_ size (ie mm or whatever) regardless of the screen dpi? That seems like it should be able to complement having a slider to simply make all the fonts bigger. Now, I _may_ have also thought my font scaling system could help for people who had higher-dpi monitors, but it wasn't the primary point of it.

**Comment by gwhitney** [comment]
I hope it was clear that I admire the more unified aspect of CelticMinstrel's original font-scaling code. As I was hacking on this and noting that each effort only seemed to affect some of the text in the game, I kept thinking to myself but there's got to be a way to get all of the text to scale at once. So it was nice to see that CelticMinstrel figured that out.

In any case,

> this pull request is to make the fonts a consistent physical size (ie mm or whatever) regardless of the screen dpi?

Yes, that is exactly my desire -- I liked the look/layout on older, larger-pixel-pitch monitors, but over the years the pixel pitch has gone down and down, and I have just been trying to scale it back to what it was, in terms of physical size.

**Comment by gwhitney** [comment]
Any thoughts on the likelihood of wesnoth adopting the approach of this pull request? I ask not because of being impatient for it to be merged into master, but simply to gauge the value of further work along these lines. I might have the appetite to attack the next worst bit -- the tiny fonts on all of the dialog buttons -- but if this approach is unlikely to enter the mainstream, I probably won't make the effort just for my benefit (as by now I remember the placement of buttons on the dialogs I use often). If it's simply still up in the air, I will just hold off. Appreciate any thoughts.

**Comment by CelticMinstrel** [comment]
I have no objections to this approach, as long as adding my approach on top of it is still possible.

> So it was nice to see that CelticMinstrel figured that out.

Sure, but my scaling wasn't based on pixel pitch, it was set in preferences. So we both figured out different important aspects, I would say.

**Comment by gwhitney** [comment]
> I have no objections to this approach, as long as adding my approach on top of it is still possible.

Sure. Here's a way I envision that the two approaches could work together. The changes I have already made should be modified somewhat to keep all computations in base-typeface-dependent units like "em" and "ex" for as long as possible. Only in inner code, controlled by CelticMinstrel's parameters, would em and ex be converted to pixels and rendered. This is a general, high-level thought, not quite the basis yet for me whipping up a follow-on pull request. Should I hold off on further specific changes to other text/UI elements until this or an alternate path to an overall consistent and scalable UI is charted out?

**Comment by Pentarctagon** [comment]
I'll go ahead and click the merge button tomorrow, assuming no objections are brought up between then and now.  There's no reason to wait on making further improvements either, I don't think.

**Comment by Pentarctagon** [comment]
Merged, thanks!

**Pull request merged**
