### PR TITLE
add wesnoth.colors

### PR DESCRIPTION
**Pull request by gfgtdf**
see https://github.com/wesnoth/wesnoth/issues/3706

the main usecase to be able to print messages and dialog labels in the color of a specific team.
Im still not 100% sure about the exact interface thougfh

### CODE REVIEW

**Comment by gfgtdf** [comment]
@CelticMinstrel  im also unsure won whether to make the function that gives a pango compatible string a poperty of a function `color.pango_string` vs `color:to_pango_str()` any opinions on that?

**Comment by CelticMinstrel** [comment]
* I don't see any reason to have the `lua_color` class - it looks like you could just embed the `color_range` directly into the userdata. Am I missing something?
* The names `rep` and `pango_string` don't seem great. I don't even know what `rep` _is_, but for `pango_string`, why not just call it what it is - `hex`?

**Comment by gfgtdf** [comment]
> it looks like you could just embed the color_range directly into the userdata

Hmm yes  could do that, when i started writing it i wasn't sure what exactly i wanted to put in that lua_color class so i just started with a new class.

> I don't even know what rep is

the doc says "High-contrast shade, intended for the minimap markers." i just coped the name rep from the c++ code name. so we could call it `contrast` or `minimap_color`

> , why not just call it what it is - hex?

I thought the name pango_string is more self explaining as it imples that its in the pango format, in particular that it contains the leading `#`

**Comment by CelticMinstrel** [comment]
Yeah, calling it some variation of "map color" seems better than the cryptic `rep`; "contrast" doesn't seem too great but has the advantage of being less specific, as there might be other places besides the map where you'd want to use that colour.

As for the other, maybe `pango_hex` then?

**Comment by CelticMinstrel** [comment]
Whoops, somehow accidentally closed it. By the way, is the pango hex string also the contrast colour?

**Comment by gfgtdf** [comment]
> By the way, is the pango hex string also the contrast colour?

No, its the "mid" color. afaik that's also what other dialogs with side colors (mp create) use.

**Comment by CelticMinstrel** [comment]
My only other thought is wondering if we should avoid single-letter members (red, green, blue, alpha instead of r, g, b, a)…

**Comment by gfgtdf** [comment]
> My only other thought is wondering if we should avoid single-letter members (red, green, blue, alpha instead of r, g, b, a)…

hmm no strong opinion on this one.

**Pull request merged**
