### PR TITLE
Work-around 0% defence listing for Rails terrain (issue #1399)

### PR DESCRIPTION
**Pull request by Wedge009**
Rails terrain listing can be confusing with 0% defence - it never appears on its own and so depends on other terrain layers' defence and movement ratings.

See discussion in #1399 for more details.

(Admittedly, special case conditions aren't really a good thing.)

### CODE REVIEW

**Comment by gfgtdf** [comment]
Hmm but wouldn't this be confusing on units who have defense defined for rail terrain?

**Comment by Wedge009** [comment]
I haven't yet seen any units which define a movement/defence rating for rails. But if there are, then yes, this could be potentially confusing if the ratings are substantially different from flat and cave, the existing terrain types rails are layered with.

In the bug discussion, I did note that adding rails to the units.cfg would be an alternative to this code change.

**Comment by Alarantalara** [comment]
The rails terrain type is present entirely for the benefit of UMC - no mainline unit uses it. This code change is less than ideal since it special cases something in data. I'd prefer to see something more general that leaves out any terrain that is not defined for a unit from help, which would prevent a new UMC terrain type from appearing with 0% for every default unit if installed. Then, if the terrain should appear in help anyway, it could be explicitly defined for the unit as impassable/0% in order to appear.

**Comment by Wedge009** [comment]
I agree it's 'less than ideal' - that's why I labelled this a 'work-around' not a fix.

The problem is that a terrain's absence from a unit's configuration seems to have an impassable/0% meaning by default, but this meaning doesn't really apply or make sense in the rails context - hence the bug report. What you suggest does work, but requires units to explicitly list every terrain type the author wants to have included in the Help listing.

Hmm... maybe that's not such a bad thing for the default units. I'll have a tinker and maybe update this branch later.

**Comment by Wedge009** [comment]
It didn't work out quite as I expected - if I change the condition to only print listings for terrains which can be reached by the unit, there's still no way to distinguish between rails and the other terrain types which are impassable/0%.

But after thinking about it, I suppose there's no meaning in including a terrain for a unit when the unit cannot go there, since that terrain type is ultimately irrelevant to it. It might be nice to know which terrains the unit cannot go to, but if the aim is to avoid player confusion then it might be worthwhile to just avoid printing terrains which are impassable/0% altogether.

Thoughts?

**Comment by Elvish-Hunter** [comment]
> I haven't yet seen any units which define a movement/defence rating for rails.

Some time ago, Xalzar proposed me a concrete use case for this: creating a mine cart unit, which can move *only on rails*.
Back then, I came up with this chunk of code (untested):

    [movetype]
        name=cart
        [movement_costs]
            rails=1
        [/movement_costs]

        [defense]
            rails=60
        [/defense]

        [resistance]
            # insert here the needed values
        [/resistance]
    [/movetype]

That is to say, even if no UMC currently relies on the fact that *rails* is its own base terrain, I'm aware of at least one case where it's planned to do so.

**Comment by Alarantalara** [comment]
I don't think I'd mind not printing impassible terrain.
Alternately, if it's an issue, add a new WML to the terrain definition that says whether it should be printed/printed if not impassible in help. That allows both behaviours and keeps the information about how terrains are handled in one place. Special casing a specific value in the code is just asking for issues given how easy it is to change WML without looking at the code.

**Comment by CelticMinstrel** [comment]
Rails normally uses the underlying terrain's movement and defense, right? Perhaps there should be a way to show this? It's the only archetypal terrain that's always an overlay, so it shouldn't be surprising that this sort of thing hasn't come up before.

**Comment by Wedge009** [comment]
I thought about that but what I've seen of rails (at least in Northern Rebirth, the only place I found them in official content) is that they are layered with flat and/or cave, and units will usually have different movement and defence values for these terrains.

Anyway, between this PR discussion, the bug report, and dev channel discussion, this is sounding a lot more complicated than I originally thought. At this rate, maybe it's better to just leave the potentially confusing 0% rails listing as-is!

**Comment by CelticMinstrel** [comment]
I feel like it's not best to leave it as-is, but I'm still not sure what's the best solution.

**Comment by Vultraz** [comment]
I wonder if it would be possible to allow UMC to define custom movetypes by
terrain SLF rather than archetype.

**Comment by CelticMinstrel** [comment]
Possible, probably, but then how on earth will you display a unit's movetype to the player? It would become almost impossible.

**Comment by gfgtdf** [comment]
> I wonder if it would be possible to allow UMC to define custom movetypes by terrain SLF rather than archetype.

Evaluating standart location filters is mostlikeley much slower than archetypes so this could slowdown the ai a lot.

**Comment by Wedge009** [comment]
Noting that rails are used in scenario 20 (North Knalga) of Secrets of the Ancients, added to the official campaigns with 1.13.7. So Northern Rebirth isn't the only official campaign with rails now.

**Comment by CelticMinstrel** [comment]
Should we bump this into 1.13.9? I think the solution of only showing passable terrains is acceptable if perhaps not ideal.

**Comment by ln-zookeeper** [comment]
The main reason I don't like the idea of only showing passable terrains is because that hides cases like mountains being impassable for cavalry or HI. If a unit is unable to move on some common terrain that isn't generally impassable, then it's more like that entry needs to be clearly highlighted, not hidden.

I still think the idea first proposed by Alarantalara and later by myself of a hide_if_impassable=bool (default no) key to [terrain_type] is the ideal solution to this.

**Comment by Vultraz** [comment]
Let's implement the `hide_if_impassable=bool` solution for 1.13.9.

**Comment by Vultraz** [comment]
@CelticMinstrel can you implement this?

**Comment by CelticMinstrel** [comment]
I think you assigned me to the wrong thing. Assigning me to a pull request gives me responsibility for merging it, but it sounds like you really meant to assign me to #1399.

Is @Wedge009 not interested in doing it though? Have you talked to him at all? I can probably do it if he's not interested, but I don't want to step on his toes, either/

**Comment by Wedge009** [comment]
I wouldn't mind learning how to do this. But if it's easier to do it yourself, go ahead - don't worry, there's no need to worry about toe-stepping with me!

**Comment by CelticMinstrel** [comment]
Well in that case, I may look into it, then.

**Comment by Vultraz** [comment]
Superseded by #2391.

**Pull request closed without merging**
