### PR TITLE
Allow explicit use of any CC license for UMC assets

### PR DESCRIPTION
**Pull request by pydsigner**
The mandatory use of the GPL for all things Wesnoth has long been a sticky point for contributors, especially those not contributing to core (i.e. creating UMC add-ons).  [Here](https://forums.wesnoth.org/viewtopic.php?f=2&t=42966&p=588491#p588491) are a few [examples](https://forums.wesnoth.org/viewtopic.php?f=6&t=42975&p=588173#p588173) of forum [discussion](https://forums.wesnoth.org/viewtopic.php?f=14&t=41454&p=579487#p579340), and [an explanation](http://shadowm.ai0867.net/blog/archives/54-Original-music-in-Wesnoth-content.html) of why the current state of affairs is not ideal.

There's been much talk about addressing the issue, but no action, and the only actual planned solution is to allow use of Creative Commons licensing, which still forces content creators to give up some rights beyond simple redistribution of the unified work. Some authors wishing to use non-GPL resources have gone so far as to [attempt to disanull the upload agreement by asserting licensing terms within the add-on itself](https://github.com/wescamp/A_New_Order-1.10/blob/master/A_New_Order/LICENSE.important.txt).

This PR seeks only to allow content authors to not agree to sign away all their work under the GPL, instead only requiring that they allow distribution through the official add-on server, while still maintaining current behavior for all content not explicitly licensed. Changing the default license is far beyond the scope of this PR. Any discussion of the exact text changes is welcomed.

### CODE REVIEW

**Comment by gfgtdf** [comment]
I don't think we shoudl allow arbitary licenses in our addons.

First, note that most of this discussion was about the licensing of the art not about the programming code. We shouldn't allow people to put obfrucased code in their addons.

Second, i think thats a good thing to allow only licences that enable other addon authors to reuse those arts without too much effort.

**Comment by AI0867** [comment]
There are two big issues here:
- UMC authors frequently copy from other UMC without bothering to acquaint themselves with licensing
- mainline wesnoth occasionally mainlines UMC content

If we require all UMC contributions to be GPL-licensed, that makes all of this mostly work, by assuming that the author either used GPL-compatible content or made it himself.
If we allow other licenses, that means people need to keep track of which license applies to what, which license is compatible with what, and will cause the addon server to generally descend into licensing-hell.

You're perfectly free to also provide your content under other licenses, but to ensure that the common workflow remains legal, we *must* require that the content is also available under the GPLv2.

I haven't been involved in wesnoth recently, but that's the reason it wasn't changed in the past.

**Comment by Elvish-Hunter** [comment]
> you certify that you have the right ... to release all explicitly licensed content for download on this server, and that you choose to do so.

I guess that some users might interpret this as allowing even *fair use* contents, so I won't be surprised if someone ends up releasing an add-on based on another intellectual property. That will create even bigger problems (DMCA notices, for example).
It'd be another matter if we allowed only a subset of CC licenses as alternatives to GPL instead (example: CC BY-SA might be allowed, but CC BY-NC-ND shouldn't be).

**Comment by Vultraz** [comment]
I don't recall how compatible the GPL is for dual-licensing items or how lenient other licenses would be to being distributed under the GPL.

If we can allow dual-licensing items under both the GPL (mandatory) and whatever other license content creators decide to use, either by choice or under terms of licensing of third party content they want to use in their addons, then it should just be a matter of updating this PR to reflect that.

However, I seem to recall there being some discussion regarding the fact that the GPL does not require attribution. Licenses for thirds party content such as CC-BY-SA require attribution. Wouldn't having dual licensing under the GPL and, for example, the aforementioned CC license, mean that content would be usable without attribution under the terms of the GPL?

All being said, we do have a pretty open sharing policy within the Wesnoth modding community thanks to the GPL. The Skyrim modding community, for example, doesn't take kindly to assets used without permission from the author. It's great that we have such an open sharing environment, but it does cut us off from great content that's out there simply because its creators do not want it relicensed under the GPL.

Furthermore, there will be cases where addon authors do **not** want others to freely use the content provided in their addons, such as commissioned art. How do we plan to deal with such contingencies?

Honestly, I think @gfgtdf has the right idea. We definitely want code (anything within .cfg files) to remain strictly under the GPL. It's art/music/etc that we want to allow under other licenses.

The way I see it, either we find out if it's possible to allow dual licensing with the GPL and other licenses (mostly CC and subsets), or we declare all art and music assets under CC-BY-SA and require all addons to have correct attribution.

**Comment by pydsigner** [comment]
> I guess that some users might interpret this as allowing even fair use contents, so I won't be surprised if someone ends up releasing an add-on based on another intellectual property. That will create even bigger problems (DMCA notices, for example).
The solution to this seems to be to clarify the text, not to restrict licensing.

**Comment by CelticMinstrel** [comment]
Vultraz, you can dual-license something under GPL with any other license you want – even a restrictive proprietary license!

Personally, I think some Creative Commons license should be the official license for all addons, rather than GPL, and in fact I think CC should be used by the core project for not only its art, sounds, and music, but also for the campaigns, multiplayer scenarios, and unit type definitions (at least; possibly even for the entire core directory).

> We definitely want code (anything within .cfg files) to remain strictly under the GPL. It's art/music/etc that we want to allow under other licenses.

I disagree. The cfg files contain content that falls into your "art/music/etc" label – specifically, plot, dialogue, and similar. These are creative content, not code (thought it may be expressed amidst code).

**Comment by pydsigner** [comment]
> UMC authors frequently copy from other UMC without bothering to acquaint themselves with licensing

You're right, it is very common to pull down an add-on and have no information on where assets came from. If you're the original content author, nothing can currently be done because the GPL doesn't require attribution. Part of the goal of this PR is to stop this.

> mainline wesnoth occasionally mainlines UMC content

Also true, but to prevent UMC authors from choosing their own licensing on the off chance that it will one day be mainlined without opportunity to discuss that process with the author seems a bad cost/benefit tradeoff.

**Comment by Vultraz** [comment]
> Vultraz, you can dual-license something under GPL with any other license you want – even a restrictive proprietary license!

Well that makes everything easier :)

**Comment by pydsigner** [comment]
@gfgtdf 

> First, note that most of this discussion was about the licensing of the art not about the programming code.

- It's much simpler to allow licensing both instead of trying to denote what types of content can be released under non-default licenses
- Code is actually often a minor part of *.cfg's. What about the dialogue?

> We shouldn't allow people to put obfrucased code in their addons.

Why not?

> Second, i think thats a good thing to allow only licences that enable other addon authors to reuse those arts without too much effort.

I strongly disagree. Good art and music aren't cheap, whether the UMC author produces it himself or commissions others to produce it for him. If it's required to be licensed under the GPL or even the CC, I'd give it a couple of weeks of uniqueness before some other author uses it in his own project, where probably many of the players of the derivative work will never realize the actual source. It is my belief that we would have more good UMC content if we didn't force people who put it on the add-on server to in essence pay for everyone else to get some new assets.

**Comment by Vultraz** [comment]
As for making CC the official license of the addon server and possibly core, I wouldn't be opposed to that. It might be the simplest way to start forcing attribution, which is always good.

That still doesn't solve the issue raised by @pydsigner above, though.

**Comment by CelticMinstrel** [comment]
Note that making CC the official license of core and the mainline campaigns would be a process that requires contacting everyone who ever contributed to them and asking them if they mind changing the license. (Of course, we also first need to decide _which_ CC license.) I definitely think it would be worth it, though.

I'm not sure which specific issue you're referring to, @Vultraz

**Comment by pydsigner** [comment]
@CelticMinstrel Presumably
> Creative Commons licensing, which still forces content creators to give up some rights beyond simple redistribution of the unified work.

**Comment by pydsigner** [comment]
A couple other things I'd like to point out:
- If we're eventually going to switch the default license to something CC, allowing explicit licensing can help prepare for that and allow those who wish to keep their work GPL only to do so.
- We don't lose our existing content — everything currently on the add-on servers has been released under the GPL and anyone wishing to retain access to the current GPL assets may download them from 1.12 server as long as that remains up and from the 1.13 server until a new non-GPL version of the add-on is uploaded.

**Comment by CelticMinstrel** [comment]
I think we do also need a way to know the license of an add-on without having to download it first. Probably a new key in _server.pbl or something.

**Comment by pydsigner** [comment]
@CelticMinstrel Would that then be the primary license for all files not explicitly assigned to a license for that add-on? Multiple licenses for various parts of a project is a real thing.

**Comment by aginor** [comment]
One of my worries with these changes is that they will require a lot of policing and administration. We'd have to be able to tell which content is licensed under what, provide a mechanism for authors to complain that their contents is mis-used (by not attributing or following the forms of the licensing).

As a whole, I think we need to discuss this further, and I suggest we develop a plan over the mailing list.  I think it would be good to allow other licenses for UMC and assets, but we'd have a colossal job on our hands to either get the artwork relicensed or replaced. 

I am not a lawyer, but I do not think that the PR as it stands is sufficient to accommodate the goals of @pydsigner, so I am strongly opposed to this being merged at this stage.

**Comment by pydsigner** [comment]
@aginor 
> but we'd have a colossal job on our hands to either get the artwork relicensed or replaced. 

This PR does not require anything to be relicensed, it just allows choice in the future. Or are you talking about the CC change that's been mentioned? As I noted initially, that is a much bigger task that is outside the scope of this PR.

**Comment by CelticMinstrel** [comment]
I agree with the final thing @aginor said – I'm in favour of this PR, but don't consider it sufficient to address the issue.

@pydsigner – That's a good question. I think projects that use different licenses for different parts would have to be encouraged to not use one of the presets; using a preset would imply everything in the add-on is available under that license. I suppose there could be a way to specify separate licenses in the _server.pbl for binary files (images, music, sounds) and text files (cfg, lua), though.

**Comment by aginor** [comment]
@pydsigner I realise that, but I think the two problems go hand in hand. I am not a lawyer, but I would be very surprised if you were not to break the licensing terms if you reused any GPL licensed contents in your CC-licensed code.

**Comment by Vultraz** [comment]
If we intend to relicence core (would this also relicense the game as a whole?), then @CelticMinstrel is correct: 

> Note that making CC the official license of core and the mainline campaigns would be a process that requires contacting everyone who ever contributed to them and asking them if they mind changing the license. (Of course, we also first need to decide which CC license.) I definitely think it would be worth it, though.

In that vein, most of the new files I've added recently have simply been copyrighted to 'the Battle for Wesnoth' project as opposed to me specifically. Might I suggest anyone here who has copyright on specific files and would be willing to have them copyrighted to the project instead amend the headers in any of their relevant files? It would make a transition to a new license easier, since it'd be fewer people to talk to.

**Comment by aginor** [comment]
> In that vein, most of the new files I've added recently have simply been copyrighted to 'the Battle for Wesnoth' project as opposed to me specifically. Might I suggest anyone here who has copyright on specific files and would be willing to have them copyrighted to the project instead amend the headers in any of their relevant files? It would make a transition to a new license easier, since it'd be fewer people to talk to.

Depending on the country you're worried about, that's not sufficient. Some countries require there to be an actual signed piece of paper.

**Comment by CelticMinstrel** [comment]
> (would this also relicense the game as a whole?)

No, when I say core I'm referring to specifically the _data/core_ directory.

> Might I suggest anyone here who has copyright on specific files and would be willing to have them copyrighted to the project instead amend the headers in any of their relevant files?

Um, I think you're overly simplifying the issue here. Just contacting the person named at the top of each file isn't sufficient. You need to run `git blame` on every file and contact every person who appears in the result.

**Comment by Vultraz** [comment]
> You need to run git blame on every file and contact every person who appears in the result.

That would imply every single contribution to a file, no matter how small, constitutes copyright holding :/

**Comment by Vultraz** [comment]
@CelticMinstrel there are 836 names listed in about.cfg. Even assuming a good ~200 of those are translators, that's still over 600 people whom have contributed something in some form or another in the past. Do you really think we can contact every one of them? And that isn't even counting the people who aren't listed in about.cfg.

**Comment by CelticMinstrel** [comment]
> That would imply every single contribution to a file, no matter how small, constitutes copyright holding :/

I'm pretty sure this is the case.

But you know, we don't have to contact every single contributor to the project. No-one has suggested re-licensing the code, for example. I don't have a problem with the code being licensed under GPL. It's the content I don't think this is appropriate for. So you'd restrict your `git blame` checks to the _data/core_ directory and possible the _data/campaigns_ and _data/multiplayer_ directories. For images, sound, and music, you'd probably need to use a different means of determining who contributed what.

I'm not sure if translators need to be contacted.

**Comment by pydsigner** [comment]
http://www.gnu.org/licenses/gpl-faq.en.html#WhatCaseIsOutputGPL looks very helpful here:
> Keep in mind that some programs, particularly video games, can have artwork/audio that is licensed separately from the underlying GPLed game. 

However, note http://www.gnu.org/licenses/gpl-faq.en.html#Consider as well.

**Comment by Vultraz** [comment]
Well that's a massive PITA :(

I seem to have mixed up a few of the issues at hand, (ie, src/ vs data/) but any bit of code we change license on will be a HUGE task.

As far as I know, we do not have any disclaimer that new contributors have to agree to... it might save future hassle if we implemented such a thing.

- If we had a unified project copyright, it would be a simple matter of saying all contributions will be copyrighted to the project and we would have the right to do with them as we see fit.

-  We could do something along the lines of the [Google Individual Contributor License Agreement](https://cla.developers.google.com/about/google-individual?csw=1) and basically say contributors own copyrights to their submissions but we may distribute them as we see fit. Which might be useful as we look towards Steam and App Store distribution...

Either way, no matter what we do it seems like we'll be sending out a couple hundred emails. ;_;

**Comment by CelticMinstrel** [comment]
> Either way, no matter what we do it seems like we'll be sending out a couple hundred emails.

Yes, that's right. There is no other way to convert something from GPL to another license.

**Comment by Vultraz** [comment]
There's a problem, though: we're unlikely to hear back from a portion of them. Plus, we may not even have valid emails for all of them. What then :/

**Comment by CelticMinstrel** [comment]
Then we have to either not change the license or excise anything that they contributed.

**Comment by Vultraz** [comment]
[Here's a list](https://drive.google.com/file/d/0B-mR9s8FduLLTFA3T0pNNTl5Mm8/view?usp=sharing) of repo contributors, generated with `git shortlog -sn.`

**Comment by pydsigner** [comment]
Looks like the .mailmap needs some love.

**Comment by gfgtdf** [comment]
> Why not?


Becasue i want to know what my installed addons do specially if they could contain malicious code. Even if its not possible to do real harm to the system, there have been addon that eigher accidently break other campaigns or intentionally try to make life harder for players.

> Code is actually often a minor part of *.cfg's. What about the dialogue?

I just looked a few random addons and i'm sure that this is not the case (unless of cource you look at a mp era where the units definition takes nearly all of the cfg'). But actually is doesnt really matter how big the code part of the cfg files exacmtply is.

I think it woudl be wrong to say cfg=code, becasue 1) there are parts of code that not in cfg files 2) there are parts of cfg files that are not code.

I don't see a problem with saysing that ll code should be gpl licensed, even if this means that some parts of the same file have a different license.

**Comment by Vultraz** [comment]
I don't think we should have multiple licenses on difference parts of the same files. It would make it even more difficult to enforce attribution. If we're going to change the license to say, CC, we should consider just doing it wholly, either for both code and art/music, or the entire game and its assets.

**Comment by pydsigner** [comment]
@Vultraz We can only change related code together, the assets can be changed progressively as desired. I don't think it makes sense to change the game engine's license to CC, and Lua scripts should probably remain GPL as well.

**Comment by CelticMinstrel** [comment]
Yeah, CC is not a good license for code, so to start with we should just apply CC to the images, sounds, and music. I think it would be good to CC the campaigns too, but that might be more problematic.

**Comment by Vultraz** [comment]
The campaigns consist of code. :/

**Comment by CelticMinstrel** [comment]
The campaigns consist of code mixed with plot, dialogue, and other creative aspects.

**Comment by Vultraz** [comment]
Right. Should have said **contain** code.

**Comment by CelticMinstrel** [comment]
Right, but the only true code in the campaigns is the Lua portions and the ActionWML portions – a unit type definition is data, not code, for example. Admittedly, most of the plot and dialogue will be mixed in with the ActionWML though. So I suspect it's impossible to actually separate the data from the code (except for maybe Lua code). In my personal opinion, the creative aspects are more important, so while there _is_ code there, I think it's reasonable to CC them as a creative work.

**Comment by AI0867** [comment]
> You're right, it is very common to pull down an add-on and have no information on where assets came from. If you're the original content author, nothing can currently be done because the GPL doesn't require attribution. Part of the goal of this PR is to stop this.

The GPL may not require explicit attribution, technically, the power of a license comes from the copyright notice. If you remove the copyright notice, you're already committing copyright infringement.
Of course, many people don't bother with the copyright notices, but those aren't required for copyright to work.

Changing this notice (that many probably don't read anyway) is not going to change people's behaviour regarding reusing addon server content. Not on its own anyway.
> One of my worries with these changes is that they will require a lot of policing and administration. We'd have to be able to tell which content is licensed under what, provide a mechanism for authors to complain that their contents is mis-used (by not attributing or following the forms of the licensing).

That's my worry. The current system depends on the current uniform licensing and an appropriate license.

> All being said, we do have a pretty open sharing policy within the Wesnoth modding community thanks to the GPL. The Skyrim modding community, for example, doesn't take kindly to assets used without permission from the author. It's great that we have such an open sharing environment, but it does cut us off from great content that's out there simply because its creators do not want it relicensed under the GPL.

Our policy since we've had the add-on server has always been that whatever you upload needs to be reusable by others. If you don't want a to publish under a free license, you're free to distribute it yourself, but not on our server.

We've turned away people with this before, but that's the price we pay. It seems that especially composers in france frequently sign most of their rights over to a RIAA-like org in order to 'protect' their copyright. So much so that they may not actually be allowed to release their music under the GPL afterwards.

> I strongly disagree. Good art and music aren't cheap, whether the UMC author produces it himself or commissions others to produce it for him. If it's required to be licensed under the GPL or even the CC, I'd give it a couple of weeks of uniqueness before some other author uses it in his own project, where probably many of the players of the derivative work will never realize the actual source. It is my belief that we would have more good UMC content if we didn't force people who put it on the add-on server to in essence pay for everyone else to get some new assets.

You're free not to release your add-on on our server, of course, but art that is made specifically for your add-on is rarely going to fit others as well. And if it's generic enough to be usable by many, you've just enriched the entire community.

Regarding copyright assignment to the project, that typically requires signed papers.

As for obfuscated code, that's actually where the GPL is quite useful, as it requires the *source*, which may be interpreted as "the preferred form for editing", which obfuscated code (like minified javascript) is not.

I don't think allowing people to use a different license instead of the GPL is a good idea unless we decide to switch over to a different license or system. Making such a decision is beyond the scope of a pull request discussion.

**Comment by Vultraz** [comment]
I should have remembered to mention that this discussion has come up before, and the conclusion we came to was GPL for source code (C++, etc) and a CC license for art and music. This would presumably have applied to the main game as well as addons.

**Comment by fendrin** [comment]
Vultraz, please point to the discussion.
I seem to have missed it.

**Comment by Vultraz** [comment]
It was a combination of various IRC chats and a dev ML posting, I believe. I don't have the exact link.

**Comment by pydsigner** [comment]
@AI0867
> art that is made specifically for your add-on is rarely going to fit others as well. And if it's generic enough to be usable by many, you've just enriched the entire community.

In my experience this is not the case. A few UMC art pieces, such as the Shaxthal portraits from IftU and AtS, have very specific ties, but most indicate just a generic role. Non-generic art from mainline campaigns show this best because everyone has them downloaded causing them to be most used; I don't think I can count on my two hands the number of UMC campaigns I've played that use [SoF's new Haldric II portrait](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Sceptre_of_Fire/images/portraits/haldric-ii.png) as a generic king/ruler. When it comes down to it, characters that *can't* be adequately represented by "generic" art are rare; there are more characters like [Hylas](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/The_South_Guard/images/portraits/hylas.png), [Methor](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Delfadors_Memoirs/images/portraits/methor.png), [Dacyn](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Eastern_Invasion/images/portraits/dacyn.png), or [Edred](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Eastern_Invasion/images/portraits/dacyn.png) than like [Moremiru](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Heir_To_The_Throne/images/portraits/moremirmu.png). These characters are distinct but not distinctive, and could be used for any white mage.

Beyond that, mainline art has the advantage of being in the most played campaigns. UMC art doesn't have that advantage and currently doesn't even have the advantage of proper attribution when used in other works.

**Comment by AncientLich** [comment]
I agree with those ones who say that UMC code part should remain stick to GPL license, not allowing (at least in official server) other licenses for that. While I would suggest to anyone to credit anything coming from third party, I also think that allowing "protective" license in WML/Lua code is something against the spirit of the open source on wesnoth, and most importantly it is a choice that can lead to critical problem, like encourage flaming between UMC developers.

Figure this scenario:
In my campaign I make a huge use of macros who calls other macros like they were subroutines, I state it is something new I invented and I state that anyone can use this kind of code without credit me.
This is a not acceptable scenario imho, expecially on WML where the language is somewhat limited by its structure, so a feature you think it could be nice in your addon, can actually be developed only few ways. 
So... allowing 'strict' license (also Creative Comments - no modify can be a problem) on WML/lua code can potentially encourage 'wars' between UMC authors... it is what happened in other editable free games where any author could make any addition with any license for his "readable" code.

Having different licenses on WML/Lua code, also, has not any actual advantage.
Talking about images and music, the discussion is a bit different. For example a music author may like to forbid to sell its own music (for example he would like to be the only one who can sell its own music or albums commercially, while it allows free usage of his samples in game). So, imho, only if we talk about music or images we can think about allowing or not other licenses different from GPL and wich other licenses we could allow for images and music.

**Comment by pydsigner** [comment]
I've changed the text to be less permissive, hopefully the new text is something that we can all agree upon.

**Comment by gfgtdf** [comment]
Hmm yes i wonder whether we should add a note about where exactly the licence files must be placed, to prevent the case that somone assumed a file was GPL licensed becasue he couldn't find any license file.

**Comment by Vultraz** [comment]
I'd say all license files should either be in the addon toplevel, or in the same directory as the asset in question.

**Comment by pydsigner** [comment]
How about allowing `./ART_LICENSE` and `<resource.path>.license`?

**Comment by gfgtdf** [comment]
Hmm not sure if i understood correctly, if i have my art file at "images/units/axeman.png" should i them put the license informtaion at "images/units/axeman.png.license" or "images/units/.license" ?

In any case i don't think i personally see a problem with it. But still i think we should, before merging this, agree that we want to do it the same way with mainline content or not. Specially because we might want to mainline some addons.

**Comment by pydsigner** [comment]
@gfgtdf `add-ons/My_Addon/ART_LICENSE` or `add-ons/My_Addon/images/units/axeman.png.license`.

It sounds like there is a desire to go to CC for mainline, but having split licensing while people are contacted or art is eventually replaced seems like the sane (practical) way to go about it.

**Comment by CelticMinstrel** [comment]
I think ART_LICENSE is better, since the other way would imply having a license file for every image, though, it's good to allow that for specific images that have a different license from the main art license (or, if ART_LICENSE is missing, specific images that are not GPL).

**Comment by pydsigner** [comment]
@CelticMinstrel ART_LICENSE would have information about which resources are under which license in most cases rather than just being a copy of the GPL or CC BY-SA 4.0.

**Comment by CelticMinstrel** [comment]
That makes sense. I think that's better than placing the licence right next to each file, unless there are only a few files under a different license.

**Comment by pydsigner** [comment]
@gfgtdf Specifically added example paths.

**Comment by pydsigner** [comment]
Some other things to think about in the context of this PR (but beyond its scope): 

* Having a more lengthy, lawyer-approved text bomb in an ART_LICENSING file included with wesnoth that we can point to in this text
* Having a comprehensive wiki page about licensing

**Comment by shikadilord** [comment]
@pydsigner Would you be able to draft that wiki page in the meantime?

Personally, I am completely in favor of this change, and I'm willing to merge it provided that no-one has any last minute objections -- in particular @ln-zookeeper, who has done add-ons server policying work in the past.

**Comment by ln-zookeeper** [comment]
I don't have any particular objections, but that's just because I don't want to touch licensing issues and discussions with a ten-foot pole. As far as I recall, I've only done some light policing regarding issues like add-ons unnecessarily affecting other content, removal of garbage add-ons or pointing out that we don't want add-ons based on commercial IP on the server. Resolving licensing disputes between add-on authors would be something else entirely.

**Comment by GregoryLundberg** [comment]
BfW uses a GPL license.

As such, it already allows BfW to distribute non-GPL elements, provided they are compatible. In fact, the project is already doing so by using the Boost library. GNU maintains a list of such licenses at https://www.gnu.org/licenses/license-list.en.html

It seems the suggested change simply should be re-worded to make it clear that all uploaded content must use one of those licenses. It does not appear to do so.

It should also be made clear that "CC" and "Creative Commons" license refers to the CC0 (public domain) license. The other licenses are not GNU compatible and should not be allowed for that reason.

Something like:

    "I certify I have the rights to upload, that all contributions
     are licensed under a GNU-compatible license, as defined
     and listed at https://www.gnu.org/licenses/license-list.en.html."

should be enough.

**Comment by pydsigner** [comment]
@GregoryLundberg 
> The other CC licenses are not GNU compatible and should not be allowed for that reason.

That only applies if we were going to use the CC license for code linked to Wesnoth, the image and audio assets used with Wesnoth are under no licensing constraints from the GPL, according to [the GPL FAQ](https://www.gnu.org/licenses/gpl-faq.en.html#WhatCaseIsOutputGPL).

**Comment by pydsigner** [comment]
I've finally found time to pick this back up again, and have here the working draft of an informative post for the forum as requested by @shikadilord in `#wesnoth-dev` back in July: https://gist.github.com/pydsigner/12dcea9426ba242f465881d9e9c2eb0c

**Comment by GregoryLundberg** [comment]
It needs a TL/DR at the top.

The background and rationale are fine but clearly delineate them from the proposed policy 
statement.

What about "more free" CC licenses such as CC-C0 (I know, not a license), CC-SA and CC-BY? I can see drawing the line at CC-BY-SA but a rationale for putting the line there might help.

**Comment by CelticMinstrel** [comment]
This seems like it needs bumping. I hope @Vultraz has finally decided what should be done about this.

**Comment by pydsigner** [comment]
@Vultraz @CelticMinstrel work has been merged.

**Pull request merged**
