### PR TITLE
Add Calendar to Wesnoth encyclopedia

### PR DESCRIPTION
**Pull request by nemaara**
For #4822, I may look at adding a small tidbit about each month later.

### CODE REVIEW

**Comment by Earth-Cake** [comment]
I just wanted to state that if in the world there are 12 months, that doesn't mean Wesnoth should have 12 months. I believe it'd make things more interesting if Wesnoth had something more like the Mayan Calendar.

**Comment by nemaara** [comment]
It definitely would make things more interesting, but more difficult to learn. I thought that it would be too much of a barrier for someone just starting up wesnoth and not have an intuitive 12 month system that works like ours. Also, there's a lot of support for a very "Earth-like" seasonal system in the campaigns, so it's natural to have a 12 month calendar.

**Comment by CelticMinstrel** [comment]
Just kinda wondering, was it intentional for Whitefire and Blackfire to be adjacent months?

Also, this new help pages seems like it might be a good place to cover the standard Wesnoth epoch that's already used internally for chronological campaign ordering. (The after the fall epoch would belong in UtBS, I suppose.)

**Comment by stevecotton** [comment]
I think we should move this to the Wiki, at least until it is used in multiple campaigns.

* Which races use this naming scheme, and when?
* It sounds as if it would be different between races; particularly between races that haven't seen each other until TRoW. (I accept that there's a handwave about everyone having a common language, but calendar month names seem a stretch on top of that handwave).
* Even within loyalist humans, it seems unlikely to keep the exact same names over the millennium that's the Wesnoth timeline.

**Pull request merged**
