### PR TITLE
Various fauna-related things

### PR DESCRIPTION
**Pull request by doofus-01**
For now, just rock scorpion pincer attack animation

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
What exactly is the problem with the old sprites? I'm not convinced the new ones are an improvement… and are you replacing all the tuskers or only the piglet?

**Comment by Hejnewar** [comment]
I did tweak water spray to look more like poison spray. (I remember similar one from some UMC but couldn't find it.) I think it could be better for Rock Scorpion than water spray. 

poisonspray

**Comment by doofus-01** [comment]
> I did tweak water spray to look more like poison spray. (I remember similar one from some UMC but couldn't find it.) I think it could be better for Rock Scorpion than water spray.

A separate poison spray image could be nice to have, but not strictly necessary for now.  If we do use one, it would need to be more differentiated.  Otherwise, I believe the IPF method works.

**Comment by doofus-01** [comment]
I'll merge this soon.  Missed 1.15.12, maybe that's good, we'll see.

**Pull request merged**
