### PR TITLE
Minor fixes for DM

### PR DESCRIPTION
**Pull request by UnwiseOwl**
Responds to issues raised in #4614 mostly through dialogue changes

### CODE REVIEW

**Comment by GregoryLundberg** [comment]
All look good but I wonder if the multiple avoid is a bug and should have an issue of its own. Either way your fix is fine.

**Comment by mattsc** [comment]
> All look good but I wonder if the multiple avoid is a bug and should have an issue of its own.

Huh, funny, I just wrote the following on irc/Discord:

"For the record, this is not a bug with the AI aspect mechanism that should be fixed there.  [I know you didn't mean it that way, I am just saying it in case somebody brings it up.]
While it would be possible to combine several [avoid] tags, this does not make sense for scalar aspects.
For example, say you have two aggression aspects, one setting it to 1, the other to 0.  There's no way to combine this behavior, you have to pick one or the other.
And we do want the mechanism to work the same for all aspects, otherwise it gets too confusing."

So, no, this is not an AI bug but intentional behavior.  And since it is entirely possible and easy to combine several SLFs into one, there's really no need to come up with an alternative solution.

**Comment by UnwiseOwl** [comment]
Oh yeah, sorry, I hadn't updated my comment here since our discussion!

**Comment by CelticMinstrel** [comment]
> All look good but I wonder if the multiple avoid is a bug and should have an issue of its own. Either way your fix is fine.

It's not a bug, it was just being used wrong there. Multiple `[avoid]` tags adds multiple facets to the avoid aspect, but the AI only takes the top matching facet from the stack. If you wanted the AI to avoid one area, but then after some event they avoid a different area instead, then multiple `[avoid]` tags might make sense (the event would remove the top facet from the stack). However, if you want the AI to avoid multiple areas, they all need to be specified in a single tag.

**Comment by UnwiseOwl** [comment]
Since I had an open PR for DM, I've added the DM map changes for #4121 here.

**Comment by sigurdfdragon** [comment]
All these seem fine,
Except for these points:
1. The commit for the ones that just touch a single scenario should have a prefix of 'DM: S12'
2. Otherwise the map commit should have prefix of 'DM'
3. I think the proposed S18 castle changes clash with moss on the floor next to snow. The castles for 2 & 3 represent new construction occurring since S11. I'd handle it by mixing in snow, along with snow for player castle.
S18Pontal Suggestions

**Comment by UnwiseOwl** [comment]
Points well made. I have made a revision for the S18 map with that feedback in mind.
Sadly I cannot change commit names using the interface that I am, but the point is well made and I will endeavour to use the appropriate prefixes in future.

**Comment by sigurdfdragon** [comment]
What OS & interface for git are you using?

**Comment by UnwiseOwl** [comment]
Windows 10 and Github Desktop.

**Comment by sigurdfdragon** [comment]
If you can, I'd recommend getting https://gitforwindows.org/ installing it with notepad++ as the editor option, and doing
`git rebase -i HEAD~X` 
on the branch, where X is the number of commits to edit.

**Comment by UnwiseOwl** [comment]
Well, I gave it a go. I hope that worked!

**Comment by sigurdfdragon** [comment]
Thanks for the updates.
There are only a few issues left to fix.
Duplicate commits ended up in the pr.
In your local repo, switching to the local pr branch and running `git rebase master` should clean that up.
After that:
the erroneous DM 18 .cfg commit and its revert should be dropped through `git rebase -i HEAD~X`
In DM 12: Fix AI not avoiding villages commit, the tabs before the 'y' should be changed to spaces.
DM 18 map has Errant snowy castle at 20,24 & 21,19 that should be regular castle.
the fixes for those two should be melded into their respective previous commits, one way is with 'fixup' in the `git rebase -i HEAD~X` interface.
When that's done force push to the remote pr branch to send the changes.

If anything goes wrong that you can't figure out, I have a backup of the pr branch.

**Comment by sigurdfdragon** [comment]
Manually fixed and merged.

**Pull request closed without merging**
