### PR TITLE
Resolve preferences file polluted with null-command hot-keys (bug #21969) [sdl2]

### PR DESCRIPTION
**Pull request by Wedge009**
Only save non-default hot-keys to the preferences file if the hot-key is active (ie command != 'null').

Clearing hot-keys in memory (via the hot-key functions in the game) only sets the command to 'null', which currently gets written to the preferences file if it is a custom, ie non-default, hot-key. Over time, creating and clearing hot-keys results in a lot of redundant hot-key entries. The nice thing about this update is that it will remove redundant command='null' entries for existing preferences files as well as prevent it from being included in future ones..

I am making this change against the sdl2 branch instead of master because the sdl2 branch already contains a lot of rewriting of the hot-key functionality.

### CODE REVIEW

**Comment by aginor** [comment]
Wouldn't this behaviour conflict with being able to clear a default hotkey?
Default hotkeys are loaded first, then user hotkeys. The game need to be able to save null-hotkeys in order to override the default hotkey with the cleared version during the load sequence.

**Comment by aginor** [comment]
I tested with clearing default hotkeys and I ended up raising https://gna.org/bugs/index.php?23981. I think that bug and what you are trying to accomplish here needs to be resolved at the same time.

**Comment by Wedge009** [comment]
...except the game doesn't appear to do this. Upon restarting, all the default hot-keys are back.

**Comment by Wedge009** [comment]
Yes, I think it does, unfortunately.

**Comment by Wedge009** [comment]
For the record, I haven't forgotten about this - I still plan on having a go at retaining deleted default hot-keys (bugs #21983/23981 - oh hey, those bugs are anagrams of each other!).

**Comment by Wedge009** [comment]
I think we need a clearer, less ambiguous way of indicating that a default hot-key combination is disabled than command="null". The null item check inside hotkey::load_hotkeys() of src/hotkeys/hotkey_item.cpp is preventing the default hot-key from being disabled because it won't allow the addition of hot-keys with null commands. But even if I ignore the check and add the item anyway, we still have the issue of polluting the preferences file with null commands.

Furthermore, simply clearing a default hot-key will not result in the null command being written to the preferences file. Only if I add my own hot-key, _then_ clear it, will anything be written to the preferences file.

I will try to come up with some ideas later, but any thoughts on this would be appreciated.

**Comment by aginor** [comment]
Let's make it clear and add a "disabled" hotkey. We can then differentiate between null and disabled, giving us a clear mechanism to distinguish between overridden default hotkeys and "cleared" hotkeys that should be removed from the save.

**Comment by aginor** [comment]
@Wedge009 Would you mind reopening this PR on master instead? This was incorrectly (but understandably) closed when @loonycyborg  closed the sdl2 branch.

**Pull request closed without merging**
