### PR TITLE
Include built-in effects in wesnoth.effects

### PR DESCRIPTION
**Pull request by CelticMinstrel**
This allows them to be called by Lua code or even overridden.

In addition, the effect functions have changed a little:
- They now return a string value which can be used to describe the effect, for building descriptions of traits.
- They now receive a boolean value; if false, they should _only_ build the description without altering the unit (used when `times=per level` but the unit is level 0).
- The config passed to the function by Wesnoth will always have `times=1`, no matter what the original `[effect]` tag had. This is something of a safeguard against coders manually implementing this when Wesnoth already calls the function several times if needed.

Needs testing still.

### CODE REVIEW

**Comment by gfgtdf** [comment]
while i dont really see why it could be useful to be able to overwrite mainline effects, i also dont really see disadvantages of it.

I'd like to test whether there this causes a noticable drop in performence when creating units before this is merged.

**Comment by CelticMinstrel** [comment]
For creating units at scenario start, I suspect that that may happen before the Lua kernel is initialized, meaning that `apply_builtin_modification` would simply be called directly. So it'd be more important to test creation of units in events (or recruitment).

**Comment by gfgtdf** [comment]
Hmm yesrecruited unit uasually don't have many [modification]s so i don't expect oerformence issues there, my worry way more about UMC that uses [unstore_unit] or [unit] with many [object]s

**Comment by CelticMinstrel** [comment]
Changed the design a little. Any thoughts?

**Pull request merged**
