### PR TITLE
add max_range and min_range to weapon API, re #9169

### PR DESCRIPTION
**Pull request by ProditorMagnus**

### CODE REVIEW

**Comment by ProditorMagnus** [comment]
@hladkyjakub if it compiles you might be interested to test if this works

**Comment by ProditorMagnus** [comment]
based on parry

**Comment by gfgtdf** [comment]
does max/min_range even do anything ?

**Comment by ProditorMagnus** [comment]
Some years ago it did, and I dont think it was recently removed.

**Comment by CelticMinstrel** [comment]
I think the only thing it does currently is influence checks for whether an attack is possible.

**Comment by ProditorMagnus** [comment]
AI has optimizations and hardcodes range of 1 in most places.

**Comment by CelticMinstrel** [comment]
Okay, the new fields in the weapon object should be documented here:

https://github.com/wesnoth/wesnoth/blob/7891a9f06f5d81440982bf0bff827fb652a8537b/utils/emmylua/wesnoth/units.lua#L4

Then as long as it works, I think this can be merged. It might be good to add it to the WFL weapon object too, though. (That one is read-only.)

**Comment by hladkyjakub** [comment]
Hi, compiled this version, tested couple things (hope it covers it all):
[effect] set/increase_max/min_range works fine and is persistent.
Lua u.attacks[1].max/min_range works fine and is persistent.
In WFL u.attacks[0].max/min_range is read-able.
Filtering attacks through [has_attack] works fine (didn't tested other WML weapon filters).

**Pull request merged**
