### PR TITLE
UtBS: few more fixes after refactor

### PR DESCRIPTION
**Pull request by DisherProject**

### CODE REVIEW

**Comment by nemaara** [comment]
There's a problem with S9: if you rescue all the merfolk before turn 16, it'll still (incorrectly) show up in the objectives. You'll probably need to make an extra variable to deal with this.

**Comment by nemaara** [comment]
I playtested these briefly to check for bugs and the other scenarios seem fine to me. By the way, would you happen to be interested in handling #4019 with this PR? If not, I can deal with that at a later time.

**Comment by DisherProject** [comment]
> There's a problem with S9: if you rescue all the merfolk before turn 16, it'll still (incorrectly) show up in the objectives. You'll probably need to make an extra variable to deal with this.

It should work now

> By the way, would you happen to be interested in handling #4019 with this PR?

I can try to solve it, i'll push a new commit in 2 or 3 days. Btw, i don't really like the idea of splitting S9 into two different scenarios so i'm not going to work on this part of the issue

**Comment by nemaara** [comment]
Just to be clear, #4019 refers to S8, not S9. I agree with you, please keep it 1 scenario (but maybe try to fix the water if you can).

**Comment by DisherProject** [comment]
The first commit addresses #4019 

The second one fixes a rare situation where Kaleh and Nym may teleport to the human outpost despite being surrounded by deep water.

The last commit is a slight rebalancement

**Comment by nemaara** [comment]
Still a small problem with the water: if you activate event 11 early (the one after you defeated the demon things and need to find the way out), the water will start rising into the chamber with the altar, potentially cutting off your units (if you sent some scouts ahead). This is still one of the problems #4019 was talking about.

I'd suggest writing a bit of dialogue if Nym and Kaleh are cut off from the outpost, but I can do that after this PR is merged.

**Comment by DisherProject** [comment]
> Still a small problem with the water: if you activate event 11 early (the one after you defeated the demon things and need to find the way out), the water will start rising into the chamber with the altar, potentially cutting off your units

It will need the dialogue to be rewritten a bit. I'll deal with it asap

> I'd suggest writing a bit of dialogue if Nym and Kaleh are cut off from the outpost, but I can do that after this PR is merged.

I couldn't write anything decent. I'd appreciate if you could do it in my place

**Comment by nemaara** [comment]
Okay, don't worry about dialogue then. I can clean it up after this PR.

**Comment by DisherProject** [comment]
@nemaara shall i fix #4032 too?

**Comment by nemaara** [comment]
Sure, also note that that objective is missing from all relevant scenarios, not just S1 and S2. You could even look at #4031 while you're at it, if you really like.

**Comment by DisherProject** [comment]
> You could even look at #4031 while you're at it, if you really like.

Healing in UtBS is specifically designed not to affect units during the day, it only stops dehydration (that is, it _prevents_ 4 damage and attack damage reduction).
For example, a druid with +8 heal ability just prevents dehydration, she won't heal "+8 - 4 = +4" health. As a consequence, the druid won't heal damage dealt by enemies either.

Imo this behaviour is good: since this is a long scenario, if your units had 4 health restored per turn that would be too easy. For this reason, imo, the problem is only about explaining that "heals" ability works differently in this particular scenario.

 Anyway, if you think the current mode of operation is incorrect, i can fix it.

> (Actually, it's also bad that you can't look up how dehydration works without restarting the scenario.)

This may be fixed via a custom menu. It shouldn't be difficult

**Comment by nemaara** [comment]
Nah, the way it works is fine. I can write some notes in the objectives to clarify that. I think this is ready to merge, so I'll do that when I check over the last few commits you made.

**Comment by nemaara** [comment]
Looks like S8 is still a problem. I tried playing through it and at event 11, the water floods through the gap in the wall really early. It makes it very hard to get past it at a reasonable time (it floods down at around turn 27, I think it should be pushed back like 8 turns at least, maybe even 10).

**Comment by DisherProject** [comment]
I pushed the water 9 tiles back

**Comment by nemaara** [comment]
Good work. :)

**Pull request merged**
