### PR TITLE
Add left padding to messages with right portrait

### LINKED ISSUE #1938: messages, which have their portrait on the right, are not centered
shaman
While most other messages have their message centered.

### PR DESCRIPTION
**Pull request by jostephd**
Fixes #1938. Tested on 800x600 and 1920x1080. This brings the left edge of the message (title and text) away from the left edge of the map. When the screen is wide enough, the text is placed at the same position regardless of whether the portrait is on the left, on the right, or on both sides. To test this start AToTB and read the dialog.

### CODE REVIEW

**Comment by Vultraz** [comment]
I disagree this should be merged. I think the variation in style is a good artistic choice.

**Comment by GregoryLundberg** [comment]
I think it should be merged. It's always bothered me. To me, when I'm scanning through because I know what it says, it's like WHAM! Yank-your-eyes. That may be fine for a critically important message, but I'd rather the text, which I'm focused on, flow smoothly from panel to panel and not jerk me around for no good reason.

**Comment by CelticMinstrel** [comment]
Maybe it could help to see a before-and-after screenshot? I think there was a before screenshot on the issue thread, so... just post an after screenshot?

**Comment by CelticMinstrel** [comment]
Hmm, I see. Yeah, that makes sense. It could be nice to use a bit more of the space when there's only one portrait (maybe shift the edge over a centimetre or two), but it's not really a problem, and maybe it's actually better to have the text in a consistent location.

**Comment by GregoryLundberg** [comment]
This looks ready-to-go. @jostephd can you port this to master as well?

**Comment by GregoryLundberg** [comment]
As a new PR, yes. Unfortunately, it's one-or-the-other :(

**Pull request merged**
