### PR TITLE
NR S13: make all player sides have turns in sequence

### LINKED ISSUE #5396: NR S13, please switch Hamels (AI) and Krashs (player) sides
### Game and System Information
 - 1.15.7
 - Steam
 - Windows 10

### Describe the desired feature
NR S13 is a huge scenario with about 9 sides, 3 of them being under control of the player. I would like for those 3 sides to take their turns one after another, without an AI side inbetween. That way the player can do his part and then leave for a couple of minutes until it's the players turn again. 
Right now it's like this: Player -> 5x AI -> Player -> AI -> Player
I'd like to have instead: Player -> 6x AI -> 2x Player

### Screenshots
grafik
grafik

### PR DESCRIPTION
**Pull request by hexagonrecursion**
Fixes #5396

was: Player -> 5x AI -> Player -> AI -> Player
now: Player -> 6x AI -> 2x Player

### CODE REVIEW

**Comment by hexagonrecursion** [comment]
I don't like how manual and error-prone this is. Is there a way to change the turn order without having to change the side number everywhere?

**Comment by hexagonrecursion** [comment]
One other question: will this break saves and replays?

**Comment by cooljeanius** [comment]
I don't think this is really an improvement... breaking up all the AI turns with player turns helps keep the player more engaged in that scenario, because otherwise the AI just takes too long.

**Comment by nemaara** [comment]
> I don't think this is really an improvement... breaking up all the AI turns with player turns helps keep the player more engaged in that scenario, because otherwise the AI just takes too long.

Well I think this is a problem with NR's design more than an issue with side order. Anyway, beside the point. I'm wondering if it would be better to let the player actually play Hamel's side. Any thoughts?

**Comment by soliton-** [comment]
> I'm wondering if it would be better to let the player actually play Hamel's side. Any thoughts?

If the AI is incapable of playing an allied side I'd rather take over and play it myself unless it's really important for story reasons or something.

**Comment by cooljeanius** [comment]
> > I'm wondering if it would be better to let the player actually play Hamel's side. Any thoughts?
> 
> If the AI is incapable of playing an allied side I'd rather take over and play it myself unless it's really important for story reasons or something.

It's not that the AI is *incapable* of playing Hamel's side, it's just that it's boring to let it do so. When I last played NR the issue was actually that the AI played Hamel's side *too* well, defeating Rakshas before I could even get close to him with any of my other sides. 
(...which I guess could also be solved by making Hamel's side player-playable, as the player could just hold back with Hamel's side in that case)

**Comment by soliton-** [comment]
I was referring to the highest difficulty where you have to rush to Hamel to not lose the game early.

**Comment by nemaara** [comment]
Yea, I think let's make Hamel a player side instead of swapping the sides around. I think that's preferable anyway, regardless of the issue in question.

**Comment by hexagonrecursion** [comment]
@nemaara done

**Comment by nemaara** [comment]
Erm well you're going to have to make the side have less gold I think. More in line with what the other sides have, just slightly more since Hamel wasn't there the last couple scenarios.

**Comment by hexagonrecursion** [comment]
Done

**Review by nemaara — APPROVED** [review]

**Pull request merged**
