### PR TITLE
Misc more api

### PR DESCRIPTION
**Pull request by gfgtdf**

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
* `item_name` - Fine, but you need to rebase and run wmlindent on this commit
* `persistent` - Fine, I see no problems
* `[unit_type_fix]` - Seems okay, but I'd like to see it supported also in `[campaign]`. Also, I suggest adding a `set_cost` key for UtBS.
* `[modify_unit][set_variable]` - Well, this doesn't really add anything new that you couldn't do before, does it? But I guess it _is_ a more convenient syntax than using `[modify_unit][variables]key=$(some_formula)`, so sure.

**Comment by gfgtdf** [comment]
> persitent -> persistent

will fix thx

>     * `[unit_type_fix]` - Seems okay, but I'd like to see it supported also in `[campaign]`. Also, I suggest adding a `set_cost` key for UtBS.

It is already supported in campaign, will update the commitmessage. Also set_cost sounds like a good idea.

>     * `[modify_unit][set_variable]` - Well, this doesn't really add anything new that you couldn't do before, does it? But I guess it _is_ a more convenient syntax than using `[modify_unit][variables]key=$(some_formula)`, so sure.

Hmm i should maybe support clear_varible there aswell if i have set_variable (which is something [modify_unit][variables] cannot do afaik, in particular removing whole subtags tags). Honestly my main motive here was to make variable changing compatible with the [modify_unit] optimisation in https://github.com/wesnoth/wesnoth/blob/7ea1377945e612b9125a298c3c23d2e7a4aa06c4/data/lua/wml/modify_unit.lua#L84 and allowing set_varible was not only easier to implement (since i can just call the original set_variable code as i did) but also a little more convinient to use.

**Comment by CelticMinstrel** [comment]
I don't think `[modify_unit]` supports the full merge syntax, so yeah, it probably can't remove keys or tags. That doesn't matter much for the root level, where the valid set of keys is fixed, but in variables it's kinda limiting; maybe we should add a wml.merge() function to merge two configs (same semantics as in `[set_variables]` using merge mode), and make use of it in `[modify_unit]`?

Regarding `set_variable_impl`, I'd say you don't actually need it. You can just add the extra parameter directly to the wml function, like this:

```
function wesnoth.wml_actions.set_variable(cfg, variables)
    variables = variables or wml.variables
    -- remainder of the function stays as it is
end
```

**Comment by CelticMinstrel** [comment]
Also, if we're supporting `[set_variable]` and maybe `[clear_variable]` in `[modify_unit]`, then why not also in `[modify_side]`?

**Comment by gfgtdf** [comment]
> Also, if we're supporting [set_variable] and maybe [clear_variable] in [modify_unit], then why not also in [modify_side]?

hmm we could, but is there a direct (=without lua) way to retreive those varibles in wml in the first place? If not there is little point is being able to  set them.

> Regarding set_variable_impl, I'd say you don't actually need it. You can just add the extra parameter directly to the wml function, like this:

Hmm yes is this really better than having a seperate function? Adding another argument to a wml tag that cannot be used from wml seems sounterintuitive to me, but i don't really have a strong opinion on this.

**Comment by CelticMinstrel** [comment]
> hmm we could, but is there a direct (=without lua) way to retreive those varibles in wml in the first place? If not there is little point is being able to set them.

Well, how does one retrieve unit variables in WML? Through `[store_unit]`, probably? So maybe side variables would be available through `[store_side]`? (If not maybe they should be.)

> Hmm yes is this really better than having a seperate function? Adding another argument to a wml tag that cannot be used from wml seems sounterintuitive to me, but i don't really have a strong opinion on this.

It's certainly debatable whether it's better than having a separate function. However, it's definitely better than polluting the `wesnoth` table with an implementation detail. If you prefer a separate function, an alternative might be to declare the implementation function local but return it from the module, so you can get it with `wesnoth.require "wml/set_variable"` when you need it elsewhere.

**Comment by gfgtdf** [comment]
merged the first 3 commits to master.

**Comment by jostephd** [comment]
Thanks! Please remember to update the wiki as well:

https://github.com/wesnoth/wesnoth/commit/daf054752a35d8395c2171b5bb5e8eb0e6407f10
https://github.com/wesnoth/wesnoth/commit/3c172f73038aa9b5574bd924048c651f14b18a80
https://github.com/wesnoth/wesnoth/commit/e4c4ca7572b2986790f40ee20b1ccb2e6e85252a

**Comment by CelticMinstrel** [comment]
* Regarding the todo note in `[store_items]`, I'd recommend a comma-separated list, not a regex. Nothing else in the main Wesnoth schema uses regex as far as I know (the schema does, but that's a separate, well, schema). If you _did_ want to support regex, I'd recommend making it a separate key (eg, `item_regex`).
* You still have `wesnoth.set_variable_impl`; please choose some other way to do this. The `wesnoth` table should not be polluted with implementation details. I've already suggested two alternative ways to handle this.

**Comment by gfgtdf** [comment]
I think i might postpone the [modify_unit][set_variable] until i actually need it.

**Comment by CelticMinstrel** [comment]
By the way, these new features need to be added to the schema, too.

**Comment by jostephd** [comment]
@gfgtdf Reminder that 1.15.0 is in two weeks (this issue is milestoned 1.15.0).

**Comment by gfgtdf** [comment]
> Reminder that 1.15.0 is in two weeks

Hmm yes I don't think I'll merge this one before, it's also marked as postoned


Did we already decide on what do do with 1.15 will it be a usual Dev release or did we change our release system? I'm not really active on irc/discord currently the irc client on my phone is not really good and discord hates me for some reason

**Comment by jostephd** [comment]
> Did we already decide on what do do with 1.15 will it be a usual Dev release or did we change our release system?

It'll be a dev release as usual, we can still add APIs, until 1.16.0.

**Comment by gfgtdf** [comment]
closing this since the set_variable change was merged differntly

**Pull request closed without merging**
