### PR TITLE
Don't translate links in About dialogue

### PR DESCRIPTION
**Pull request by Wedge009**

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
This is going to cause the schema check to fail. However, I also think it's correct not to mark these translatable. I suppose we could hide it from the schema validator via a preprocessor check, but I'm not sure if that's the best way to handle it…

**Comment by babaissarkar** [comment]
> This is going to cause the schema check to fail. However, I also think it's correct to not mark these translatable. I suppose we could hide it from the schema validator via a preprocessor check, but I'm not sure if that's the best way to handle it…

Another way would be to put them into the `wesnoth-test` textdomain.

**Comment by CelticMinstrel** [comment]
Hmm. I guess that would _work_, though it's a very weird way of doing it.

**Comment by babaissarkar** [comment]
> Could also add it to a new previously-unused domain that's also not translated, eg `wesnoth-links`.

That's what `wesnoth-test` is for, it's used for the Clock button.

**Comment by soliton-** [comment]
Using the preprocessor to hide it for validation would make the intention clearer.

**Comment by Wedge009** [comment]
> This is going to cause the schema check to fail.

I did wonder about test failure but I thought it was with respect to wmllint and not the CI check. I noted there were other instances of untranslated labels so I thought it was fine to do this. At the very least my intention was to _reduce_ the burden on translators, which is something that is often aggressively pursued here.

**Comment by Vultraz** [comment]
I admittedly merged this very quickly, but I hadn't anticipated the overly zealous schema validator. Is there a way to make it accept both `string` and `t_string` for `label=`?

**Comment by CelticMinstrel** [comment]
There is, but I'm reluctant to use it, because the times when you want it not to be translatable are very rare. (There's already an exception for `[image]label=` for the record – it's not required to be translatable. I think it's actually required _not_ to be.)

**Pull request merged**
