### PR TITLE
Modify a line in tutorial on reccommended next campaign

### PR DESCRIPTION
**Pull request by Gothyoba**
AToTB has not been described as rookie since 2019, and I do not think it contains many strategy hints. This replaces the term rookie-level used in the tutorial to reffer to AToTB with novice-level.

### CODE REVIEW

**Comment by stevecotton** [comment]
Looks like a good change to me.

Although it contains a few hints that are only shown on easy mode, there's only 9 across the entire campaign.

**Comment by knyghtmare** [comment]
Wondering if the current TSG should be there instead of AToTB. TSG has a "Beginner" difficulty.

**Comment by Gothyoba** [comment]
At least in 1.19.1 AToTB is easier than TSG on its easiest difficulty in my opinion.

**Comment by stevecotton** [comment]
> Wondering if the current TSG should be there instead of AToTB. TSG has a "Beginner" difficulty.

Currently, AToTB is above TSG when listed in the campaigns menu, so AToTB is the recommendation. We should review this line again when TSGR merges, but it doesn't seem a reason to wait before merging the current PR.

**Pull request merged**
