### PR TITLE
[world conquest] Backport of making Banner stack with leadership

### PR DESCRIPTION
**Pull request by knyghtmare**
This was supposed to have been backported around 18-20 January of 2022...

### CODE REVIEW

**Review by stevecotton — CHANGES_REQUESTED** [review]
This can not go to 1.16, because it will cause OOS.

Although these files are WML, they're WML that is loaded from each player's local filesystem, not shared from the host. Players with unpatched versions of Wesnoth will get different stats compared to players with this PR applied.

Apologies for saying in https://github.com/wesnoth/wesnoth/pull/6467#issuecomment-1027375025 that I'd be happy to accept this, I've now tested and confirmed that it causes OOS.

**Comment by stevecotton** [comment]
For 1.16 (only), I guess we need to change WC_STR_BANNER_DESCRIPTION and the Imvest dialog strings instead, to say that it doesn't stack. Hopefully those don't cause OOS.

**Comment by stevecotton** [comment]
Before the string freeze, would it make sense to add a warning that it doesn't stack?

**Comment by knyghtmare** [comment]
> Before the string freeze, would it make sense to add a warning that it doesn't stack?

I would have preferred to patch up this bug given the recent player dissatisfaction with WC in its forum thread. Just telling them it doesn't stack might not really do much. However, OOS is annoying on an equal level as well.

**Comment by knyghtmare** [comment]
Probably will frustrate players...but OOS...
Done with text update

**Review by stevecotton — APPROVED** [review]

**Comment by Pentarctagon** [comment]
@knyghtmare I assume this can be merged now?

**Comment by knyghtmare** [comment]
> @knyghtmare I assume this can be merged now?

I think the discussion reached a stalemate last time since it was "fixing a bug in stable and causing OOS" and "improving player experience with WC but causing save-file OOS"
https://discord.com/channels/231976805987385345/259976436490829825/944928345961926787

However, the answer to your question is: yes, it can be merged...but yeah the discussion's outcome was not clear to me.

**Pull request closed without merging**
