### PR TITLE
Add fallback_human() action to the Lua AI

### PR DESCRIPTION
**Pull request by CelticMinstrel**
Just like the FormulaAI fallback() function, this temporarily transfers control of the side to a human player.

I simply used the same exception that the FormulaAI uses for this, making it inherit from `lua_jailbreak_exception`. I have not tested it, however, which is part of why this is a PR rather than being pushed straight to master.

### CODE REVIEW

**Comment by gfgtdf** [comment]
> this temporarily transfers control of the side to a human player.

In the fallback_ai_to_human_exception implementation (playsginle_controller.cpp) is seems like this controller change is permanent and that it relies on the player/tester to give contorl back to ai with :control/:droid

**Comment by CelticMinstrel** [comment]
Huh, you're right that it does look permanent. I always assumed it was temporary.

Do you think there would be any objection to changing it to be temporary? Also, any suggestions for how to do that? So far I'm assuming I'd need to add some code to `sync_end_turn` and probably a flag to the `playsingle_controller`,

**Comment by gfgtdf** [comment]
hm yes such a variable could be added. I wonder though whetehr it wouldn'T better, if (insteak of calling make_human) the game would just change the proxy controllr instead of the real controller. Given that this is afaik only a debug feature it might not be that important though.

**Comment by CelticMinstrel** [comment]
I don't actually know what that means.

Although _intended_ as a debug feature, I think fallback() could also be used more intentionally to give the player partial control of an allied side. I'm not entirely sure how that would be done, though...

**Comment by gfgtdf** [comment]
> I don't actually know what that means.

iceiceice somehwne aded a 'proxy' controller to change the controller only ui wise while the game logic stays that same, this is curently in particular used by :droid command so that the scenario will no longer count as 'lost' when you :droid your side to do that last seps for you (becasue there would be no alive human side left)


> Although intended as a debug feature, I think fallback() could also be used more intentionally to give the player partial control of an allied side. I'm not entirely sure how that would be done, though...

I think a synced way to tranfer control ([do_command]/ai.synced_command + [modify_side]controller=) is for other cases to prevent possible OOS.

**Comment by CelticMinstrel** [comment]
Ah, so there's another way to do it in Lua AI that even works in MP? That won't work for FormulaAI though, but then, I'm not sure of the future of FormulaAI anyway...

Is there any reason why this fallback implementation couldn't also sync though?

**Comment by gfgtdf** [comment]
> Is there any reason why this fallback implementation couldn't also sync though?


no.

**Pull request merged**
