### PR TITLE
Return early if there are no sides

### PR DESCRIPTION
**Pull request by soliton-**
Avoids calling modulo with 0.

### CODE REVIEW

**Comment by soliton-** [comment]
Should fix #7550.

**Comment by gfgtdf** [comment]
With this it looks like this function does nothing when there are no sides and throws when there is for example only one side with `controller=null`, which makes it a bit inconsistent. Still, since it fixes #7550 it still good to go in, but i should probably improve it later, (i can't right now since I'm not in my main pc)

**Comment by soliton-** [comment]
> Was this tested to make sure that the campaigns no longer get the assert (or some other issue)?

No, if 40fbf95 is completely wrong then this does not help. I won't be able to test this anytime soon.

**Comment by gfgtdf** [comment]
Technically that commit is a bit wrong since it might result in an out of range side num like i said will fix later.
(That function is usually used  the end of the side where this is intentionally possible to indicate new turns)

**Comment by Pentarctagon** [comment]
I'd like to tag 1.17.16 this weekend to push a fix for #7550 out. Is this PR good to be merged, or does it need further changes?

**Comment by soliton-** [comment]
From my side it's good to go. @gfgtdf seems to approve? Please do it through the github UI.

**Review by gfgtdf — APPROVED** [review]
Looks good to me, but i can it test it here.

**Pull request merged**
