### PR TITLE
fix carryover_percentage not valid when victory_when_enemies_defeated=no in shema test

### PR DESCRIPTION
**Pull request by newfrenchy83**
put carryover_percentage in begining of scenarion cause a bug in travis compilation in DM testing.

### CODE REVIEW

**Comment by soliton-** [comment]
Please add a link showing the travis issue.

**Comment by newfrenchy83** [comment]
it is in this pull request https://github.com/wesnoth/wesnoth/pull/4086

**Comment by soliton-** [comment]
So the reason is that carryover_percentage is not valid if victory_when_enemies_defeated is false. It would be nice if the commit message explained that.

Is this really just reported in that PR? If so why do the master travis runs not fail?
Nevermind, this commit introduced it: https://github.com/wesnoth/wesnoth/commit/48c3fb5114caa8df799e2c743483a073c9ab995f

**Comment by Pentarctagon** [comment]
[Travis did fail/is failing, FTR.](https://travis-ci.org/wesnoth/wesnoth/jobs/546984236#L630)

**Comment by sigurdfdragon** [comment]
I don't quite understand what's going on here.
I though travis didn't check wml.
@newfrenchy83 can you put a direct link to the repont in question, I'm having trouble finding it where you indicated it.

**Comment by Pentarctagon** [comment]
A schema validator for WML was added for 1.15, so it's used during the second travis job for master to validate the core WML and each campaign+difficulty.

**Comment by sigurdfdragon** [comment]
@Pentarctagon Ok, thanks
@newfrenchy83 I agree with @soliton- here, the commit message should say something about "carryover_percentage is not valid if victory_when_enemies_defeated is false' as opposed to the way it's stated currently.

**Comment by newfrenchy83** [comment]
https://travis-ci.org/wesnoth/wesnoth/jobs/546827523#L644

**Comment by gfgtdf** [comment]
I'm actually surprised that 

> carryover_percentage is not valid if victory_when_enemies_defeated is false.

I'd think that still works as a default value when [endlevel] does not specify the carryover percentage.

**Comment by sigurdfdragon** [comment]
@newfrenchy83 thanks for the link

If the schema update commit is to be used, the 1st & 3rd commits about DM S08 cancel each other out, and need to be removed before merging

**Comment by CelticMinstrel** [comment]
> I'd think that still works as a default value when [endlevel] does not specify the carryover percentage.

Should probably check the code for that, but it makes sense... I don't remember why I had that conditional check in the schema.

**Comment by CelticMinstrel** [comment]
(Revised answer posted on the updated version of this PR, #4129)

**Pull request closed without merging**
