### PR TITLE
Schema: Add lua_goal support

### PR DESCRIPTION
**Pull request by CelticMinstrel**
@doofus-01 Try pulling this and see if that fixes your validation issue. Pushing it to your PR would be fine if you're unable to validate locally.

### CODE REVIEW

**Comment by doofus-01** [comment]
I'm getting the same validation error.

**Comment by CelticMinstrel** [comment]
Ahh, I see the issue. This wasn't the correct fix in the first place.

**Comment by CelticMinstrel** [comment]
@doofus-01 Try that change instead.

**Comment by doofus-01** [comment]
How do I test that locally, is it `perl wml.pm something-something`?

**Comment by CelticMinstrel** [comment]
If you're asking how to run the validation locally, it would be something like `./wesnoth --data-dir=. --validate=data/_main.cfg --preprocess-defines=$DEFINE,$DIFFICULTY` where `$DEFINE` and `$DIFFICULTY` are replaced with the campaign and difficult defines respectively. (That line comes from utils/CI/schema_validation.sh.)

**Comment by doofus-01** [comment]
Thanks, that works.  `validation succeeded`

**Pull request merged**
