### PR TITLE
1.17 - Make map elevation available to [scenarios]

### PR DESCRIPTION
**Pull request by doofus-01**
This is to create a tag that determines the elevation data on a map that uses the feature correctly.  The five-level limit is pretty baked in, because that's how it is in the terrain graphics.  The use for this would be anything that could use a location set (group of `x,y` ) as a filter.
```
[elevation_score_map]
    high_border=<terrain code> (*^Qhh* default, key is optional)
    low_border=<terrain code> (*^Qhu* default, key is optional)
    test_labels = <boolean> ( default false )
[/elevation_score_map]
```
The effect of this tag is to create some WML variables `[elevation_area]`, one per elevation marker (the arrows in the editor) + the unassigned default elevation
It also creates a WML variable `[elevation_data]` that is basically a summary, in case that helps somehow.  Currently it is just a count of the different elevation levels.

This can be tested in the `Test_Elevation_Test.cfg` MP scenario, which has a simple example use-case, where higher-ground attacker (horseman) gets a damage boost and lower-ground attacker (wolf rider) gets a damage nerf.
Screenshot_20230611_

---- original post ------
I'm really not the right person to be doing this, but we've got to start somewhere.  This is a first draft, I need to reconcile it with the terrain-graphics rules better and then work on improving the efficiency (the failsafe cycle works, but it causes Wesnoth to choke, need to get the main flood-fill to work better).  It reminds me of Tron, I'm probably reinventing the wheel.

For this PR, I hope to get the elevation data available to the scenario author (for now it is a label, which is obviously just debug).  Goal is for each hex to have elevation data (low-low, low, default, high, high-high).  How this data should be used is out of scope.

This is a hack, just like the elevation terrain-graphics.  Best action would be to replace both of them with an engine update, but 1.18 isn't that far away, so this may be the best realistic option.
Screenshot_20230529_

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
This looks pretty complicated, and I'm not sure I understand the purpose, so I think it would be nice to see an actual use-case for it.

**Comment by doofus-01** [comment]
https://forums.wesnoth.org/viewtopic.php?t=56456 has some discussion of use cases.

**Comment by CelticMinstrel** [comment]
I meant something a little more concrete.

**Comment by doofus-01** [comment]
The first cycle works much better now, it's almost usable.  I might be able to delete the second cycle.  The final cleanup cycle is still TBD.
Screenshot_20230604_

**Comment by doofus-01** [comment]
It's working now, and has a possible use case.  The "implementation" (lua tables -> WML events/data/whatever) was a pretty small part of this, writing elevation data out to something useful in scenario WML is all I aimed to do.  So, pretty much done, aside from the whitespace etc.

Is there a way to see what exactly failed with CI?  I don't have luacheck.

**Comment by CelticMinstrel** [comment]
> has a possible use case

Where?

**Comment by Pentarctagon** [comment]
The CI shows the errors as well:
```
    data/lua/wml/elevation_scoring.lua:155:33: (W542) empty if branch
    data/lua/wml/elevation_scoring.lua:159:25: (W542) empty if branch
    data/lua/wml/elevation_scoring.lua:173:90: (W542) empty if branch
```

**Comment by doofus-01** [comment]
> The CI shows the errors as well:

Thanks, I'd thought there was more to it than that, but that was with the `fix_whitespace.sh` script

**Comment by doofus-01** [comment]
> Where?

I don't know why you've been trolling this, but I've tried to make the OP a summary of the situation.

**Comment by CelticMinstrel** [comment]
> I don't know why you've been trolling this

That's really rude.

I think storing the elevation in the unit variables isn't a great idea. It means it will be out-of-date more often than not. I think it would be better to use `[time_area]` to define the elevation areas.

**Comment by Pentarctagon** [comment]
If I'm understanding correctly, the use case is to make it easier to tell what a unit's elevation is relative to other hexes on the map, correct?

**Comment by CelticMinstrel** [comment]
Right, but elevation is logically a property of a tile, not a unit. So, putting it on the unit means it's only valid if the unit hasn't moved, which means the elevation mapping (or at least the part of it on the units) would need to be recalculated every time a unit moves or is spawned.

Using a `[time_area]` better preserves the fact that it's a property of the tile. The filter would change from

```
[filter_condition]
    [variable]
        name=unit.variables.elevation
        greater_than=$second_unit.variables.elevation
    [/variable]
[/filter_condition]
```

to something similar to

```
[filter]
    [filter_location]
        area=high
    [/filter_location]
[/filter]
[filter_second]
    [filter_location]
        area=low
    [/filter_location]
[/filter_second]
```

Generalizing that two-step filter to three or more steps isn't trivial, admittedly, and off the top of my head I'm not quite sure what it would look like. I think using two separate filters like above doesn't work. Perhaps there could be a custom conditional_wml filter.

**Comment by Pentarctagon** [comment]
Making a tile's height part of a [time_area] is also kind of strange though, since it has nothing to do with times. Is there a reason to not make it a property of the tile itself, so it would work in a regular location filter?

**Comment by CelticMinstrel** [comment]
> Making a tile's height part of a [time_area] is also kind of strange though, since it has nothing to do with times.

Time areas have nothing to do with times except insofar as you can put a custom schedule inside them. They are a general mechanism of grouping tiles into a defined area. The reason they're called `[time_area]` is basically backwards compatibility.

> Is there a reason to not make it a property of the tile itself, so it would work in a regular location filter?

This certainly makes sense, but it doesn't work too well for something that's being built on top of the engine, rather than as a part of the engine. We don't have a way to add a custom filter to a location filter from Lua. Adding an elevation check to the hex metatable does make sense, I think, but that doesn't help for filtering. Time areas do, though are a bit awkward for this use-case.

**Comment by doofus-01** [comment]
I give up, I'll just release this as an add-on.

**Comment by CelticMinstrel** [comment]
That seems better, since it's clearly in an unfinished state.

**Comment by Pentarctagon** [comment]
@CelticMinstrel it's not incomplete so much as this isn't intended as the final state in the first place. He even said in the opening post:
> This is a hack, just like the elevation terrain-graphics. Best action would be to replace both of them with an engine update, but 1.18 isn't that far away, so this may be the best realistic option.

and

> For this PR, I hope to get the elevation data available to the scenario author (for now it is a label, which is obviously just debug). Goal is for each hex to have elevation data (low-low, low, default, high, high-high). How this data should be used is out of scope.
> 
> This is a hack, just like the elevation terrain-graphics. Best action would be to replace both of them with an engine update, but 1.18 isn't that far away, so this may be the best realistic option.

**Pull request closed without merging**
