### PR TITLE
Reconvert background.webp from the original jpg and add metadata

### PR DESCRIPTION
**Pull request by babaissarkar**

### CODE REVIEW

**Comment by Wedge009** [comment]
How was the original WebP file converted? A 9.38 MiB / 31% size difference sounds like a lot.

**Review by Pentarctagon — APPROVED** [review]

**Comment by Pentarctagon** [comment]
The script to add metadata also changed it from being a lossy webp to a lossless webp.

**Comment by Wedge009** [comment]
I suppose that makes sense - any sort of conversion from lossy format to lossless format will incur some overhead compared with lossy format to lossy format. And I also agree with the choice to make the initial conversion lossless - I'm pretty sure most of the images would have been from PNG source.

**Comment by Pentarctagon** [comment]
To clarify, when it was originally converted to webp by optiwebp.py, the rule was (and still is):
* If png -> lossless webp
* If jpeg -> lossy webp at 90% quality

The original image in this PR was a jpeg, so it was converted to a lossy webp. However the script to take the copyrights.csv data and add it as metadata to the images didn't check that, so it converted the lossy webp to a lossless webp (in all such cases actually, not just this one), which is what caused the size increase.

This PR is taking the original jpeg, converting it back to a lossy webp, and then also adding the metadata back, which is why the size decreases significantly compared to the current image in the master branch.

**Comment by Wedge009** [comment]
> However the script to take the copyrights.csv data and add it as metadata to the images didn't check that, so it converted the lossy webp to a lossless webp (in all such cases actually, not just this one), which is what caused the size increase.

So has that been fixed then? I take it this file was the only one big enough to warrant the effort of a reconversion from the original source JPEG

**Comment by babaissarkar** [comment]
> I take it this file was the only one big enough to warrant the effort of a reconversion from the original source JPEG

Yes, this one was particularly big, so decided to do it manually.

**Pull request merged**
