### PR TITLE
Various bug fixes

### PR DESCRIPTION
**Pull request by Earth-Cake**
Corrected a typo, added unit file to Wose Sapling (full, before was base unit Wose), and added special notes to unit in NR.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Regarding the third commit - my understanding is that "gray" is preferred in American English, so the change might not be acceptable.

**Comment by Earth-Cake** [comment]
On the mainline map it is spelled Grey Woods.

**Comment by CelticMinstrel** [comment]
Yeah, in that case certainly one of them should be changed. Whether this is the correct one to change, I have no idea.

**Comment by jostephd** [comment]
If you keep the map as it is and change the text, please add pofix entry for the Grey/Gray change.

And if you change the map, note that the en_GB map localization should continue to say "Grey Woods" even if the en_US version is changed. http://wiki.wesnoth.org/ImageLocalization

**Comment by Earth-Cake** [comment]
I am not sure whether the map should be changed or just text. I am leaving that decision to someone else.

**Comment by Wedge009** [comment]
Yes, 'gray' is en_US. However, it does appear that 'Grey Woods' is the canonical name, perhaps to capture that 'old fashioned' feel in the same vein that 'Sceptre of Fire' is the canonical spelling even for default en_US.

Assuming Grey Woods is the canonical name, I think this change is fine as it is.

**Comment by Earth-Cake** [comment]
I guess I would rather let Wose Sapling not use description, rather than using same like wose.

**Comment by CelticMinstrel** [comment]
I agree that core units shouldn't really be using `[base_unit]`. Are you quite certain you copied over all the parameters that matter from the base wose?

**Comment by CelticMinstrel** [comment]
I agree that core units shouldn't really be using `[base_unit]`. Are you quite certain you copied over all the parameters that matter from the base wose?

**Comment by CelticMinstrel** [comment]
Never mind, I verified it myself and merged this. Thanks!

**Pull request closed without merging**
