### PR TITLE
1.19 - Brush up minor characters 

### PR DESCRIPTION
**Pull request by doofus-01**
Inspired by #8734, this is to complete some minor characters, rather than discard them.  Maybe they can be hooks for UMC to develop further.  For now it's just the Sea Orc from HttT (not totally finished) but I think there will be others.

I'm not going to make a checklist because I don't know yet what all this covers.  I'd be open to suggestions, if anyone has any.

### CODE REVIEW

**Comment by knyghtmare** [comment]
> I'm not going to make a checklist because I don't know yet what all this covers. I'd be open to suggestions, if anyone has any.

- Leopard/Lynx (WoF): the current sprite looks very...substandard and no portrait.
- Symphalian (might be good for core with some touchups and a portrait)

- Dolphin (TBH, I am not really sure about this one. Part of me thinks it can go in core under a new ID and name since Wesnoth is fantasy world and might not have the exact real world animal)

**Comment by CelticMinstrel** [comment]
I'm going to bring up the Vampire Lady as well.

I don't think the Stymphalian needs to be in core, though I guess I don't really mind if it is.

**Comment by Dalas121** [comment]
This is awesome!  Orcs will rule the seas!  I do feel like one-off units might not be the first priority compared to major units (cavalier has no attack anims, for example), but if this is what you're excited about I certainly won't complain about high-quality stuff

**Comment by Gweddeoran** [comment]
> I'm going to bring up the Vampire Lady as well.

For the Vampire Lady, we could leave that for later, since I'm not fully sure on the direction for Cursed Isle in the TRoW Rework. Also, Vampires are a brand new concept not discussed anywhere else in Mainline. I think it's something that shouldn't be added in so casually, since Vampire-dom can be an alternative to Lichdom as both grant immortality/longer lifespan, and one would question why we don't see more Vampires.

**Comment by AnekronCZ** [comment]
Might I suggest Moremirmu, the HttT mage with a holy sword? He gets a cool portrait, but uses generic White Mage / MOL sprites. Would be cool to have a sword wielding White Mage in Wesnoth's flagship campaign.

**Comment by CelticMinstrel** [comment]
> For the Vampire Lady, we could leave that for later

We could, but I still think keeping her is better than discarding her.

> Vampires are a brand new concept not discussed anywhere else in Mainline.

Which is kinda why she's interesting?

> one would question why we don't see more Vampires.

You could question it, sure, but there are probably hundreds of plausible reasons, so I don't think it's that much of an issue.

**Comment by Jonathan-Kelly** [comment]
> * Leopard/Lynx (WoF): the current sprite looks very...substandard and no portrait.

Any forest-dwelling ambush-predator big cat would be a welcome replacement for this aging beast. A tiger, lion, jaguar, leopard, panther, etc... anything level 2 or 3 with the `ambush` ability would be great.

The project and UMC community might benefit most from having a tiger or lion in core, since they can be found in a wide range of climates from very cold to very hot.

> * Stymphalian (might be good for core with some touchups and a portrait)

Unfortunately, this one currently uses a Roc's sprite. An actual [Stymphalian Bird](https://en.wikipedia.org/wiki/Stymphalian_birds) sprite would instead look like the [Great Bittern](https://en.wikipedia.org/wiki/Eurasian_bittern) which the myth seems to be based on. Just with a bronze beak, sharp metallic feathers that can be flung at enemies as a ranged attack, and also... poisonous dung.  :)

The change of appearance would also help visually distinguish it from the existing Falcons and Roc.

**Comment by CelticMinstrel** [comment]
> forest-dwelling

> lion

…what? In what world do lions live in forests?

**Comment by CelticMinstrel** [comment]
> I thought the asiatic lion inhabited teak forests

I'm admittedly not as familiar with non-African lions, so it's not impossible, but if they share the pack-hunting strategy of the African ones, it would seem more likely that they'd prefer open spaces. Which doesn't necessarily mean they'd _never_ be in a forest…

**Comment by cooljeanius** [comment]
Re: the Vampire Lady: I was actually kinda thinking of commissioning a portrait for her myself from one of the artists I like to go to for UMC, but I dunno if that'd be acceptable for mainline...

**Comment by doofus-01** [comment]
>  I do feel like one-off units might not be the first priority compared to major units (cavalier has no attack anims, for example), but if this is what you're excited about I certainly won't complain about high-quality stuff

Yeah, there's a lot of animations to do, but it's hard to get motivated for working on them by themselves.

> Re: the Vampire Lady: I was actually kinda thinking of commissioning a portrait for her myself from one of the artists I like to go to for UMC, but I dunno if that'd be acceptable for mainline...

It would really depend on the portrait, and how you set up the commission - would revisions be on the table?

**Comment by knyghtmare** [comment]
@cooljeanius @doofus-01 @AnekronCZ 
source: https://forums.wesnoth.org/viewtopic.php?p=615543#p615543
Artist: Kimir-Ra
I found this version of the Vampire Lady portrait done by artist Kimir-Ra, commission by FaeLord for his The Amaranthine Stone 2 UMC. I suppose it does not match current style of portrait art but it's still a portrait.

Vasha

**Comment by CelticMinstrel** [comment]
She looks a little bit too monstrous for my liking…

**Comment by cooljeanius** [comment]
yeah I agree with @CelticMinstrel

**Comment by doofus-01** [comment]
The _'Salem's Lot/Nosferatu_ theme isn't necessarily a bad thing, given how little story there is behind this character (and I'd personally prefer it to sexy, sparkly vampire), but that is clearly not the style we're using.

**Comment by doofus-01** [comment]
> Might I suggest Moremirmu, the HttT mage with a holy sword? He gets a cool portrait, but uses generic White Mage / MOL sprites. Would be cool to have a sword wielding White Mage in Wesnoth's flagship campaign.

There was someone interested in working on Mages (https://forums.wesnoth.org/viewtopic.php?p=687356#p687356), maybe he could give this a shot.

**Comment by doofus-01** [comment]
I'd neglected to check the sprite before drawing the vampire lady portrait, so had to do a recolor.  If she becomes a more important character some day, this should be revisited.

This was fun, but it's time to get back to other things.  I'll merge if everything aside from the copyrights passes, then I'll update the CSV in a quick follow-up.

**Comment by CelticMinstrel** [comment]
> I'll merge if everything aside from the copyrights passes, then I'll update the CSV in a quick follow-up.

I don't think this is a problem per se, but if it's no trouble for you it may be nicer to do the merge locally on your computer (with `git merge` or `git rebase` or whatever GUi equivalent you might use), then update the CSV, and finally push both at once.

Though this runs the slight chance of having to redo it because someone else got a push in before you.

Just take this as a thought, not a request.

**Pull request merged**
