### PR TITLE
NR S7-8: make Stalrag "healthy" for consistency, and avoid re-creating him from scratch

### PR DESCRIPTION
**Pull request by joeylmaalouf**
Fixes issue #3140, and addresses something brought up by @sevu down below.

### CODE REVIEW

**Comment by joeylmaalouf** [comment]
Oh, got it.

Actually, sevu, that's a good point - I hope you don't mind, but I just expanded the scope of this pull request and addressed that in another commit.

**Comment by sigurdfdragon** [comment]
That's just a comment on the first commit

**Comment by sevu** [comment]
There exist actually a trick, via [store_unit] / [/unstore_unit] one can make a copy of the unit, change all kind of things and unstore it onto the recall list. This has the advantage that the units on the field still belong to their original side, so they are still shown in linger mode (the part when the map is greyed out)

However, it has the side effect that many tags don't work on units on the recall list or that [unstore_unit] works a bit different than most tags, so one must change some things directly:
```
    [event]
        name=victory

        [store_unit]
            [filter]
                id="Stalrag,Ro'Arthian,Ro'Sothian"
            [/filter]
            variable=new_companions
            kill=no # Current units may remain on the field for visual reasons.
        [/store_unit]

        [foreach]
            array=new_companions
            # Stores a copy of them onto the recall list; the recall list cannot be viewed in linger mode.
            [do]
                {VARIABLE this_item.side 1}
                {VARIABLE this_item.canrecruit no}
                {VARIABLE this_item.overlays misc/hero-icon.png}
                {VARIABLE this_item.ellipse misc/ellipse-hero}
                # Units unstored onto the recall list won’t be healed as usual.
                {CLEAR_VARIABLE this_item.attacks_left}
                {CLEAR_VARIABLE this_item.moves}
                {CLEAR_VARIABLE this_item.hitpoints}
                {CLEAR_VARIABLE this_item.status}
                # Adds the loyal trait, for Stalrag as first one in the list.
                [if]
                    [variable]
                        name=this_item.id
                        equals=Stalrag
                    [/variable]
                    [then]
                        [set_variables]
                            name=this_item.modifications
                            mode=replace
                            [literal]
                                {TRAIT_LOYAL}
                                {TRAIT_HEALTHY}
                            [/literal]
                        [/set_variables]
                    [/then]
                    [else]
                        [set_variables]
                            name=this_item.modifications
                            mode=replace
                            [literal]
                                {TRAIT_UNDEAD}
                                {TRAIT_LOYAL}
                            [/literal]
                        [/set_variables]
                    [/else]
                [/if]

                [unstore_unit]
                    variable=this_item
                    x,y=recall,recall
                [/unstore_unit]
            [/do]
        [/foreach]
        {CLEAR_VARIABLE new_companions}
    [/event]
```
Ro'Arthian and Ro'Sothian are similarly affected like Stalrag. And, there is some way to resurrect Ro'Sothian, he's always as well created from scratch again... maybe he could be placed in a variable when dying and be unstored later.
I don't know if this resurrection thing happens in the practice though.

One more thing, while such a change could be directly merged in master, 1.14 promises compatibility between 1.14.x releases. One can change anything which is exclusive to one scenario, because when a start-of-scenario save is loaded, it reads the scenario file from the campaign.
In this case however, loading a save of scenario 8 relies onto that the units have been added in scenario 7. One can add compatibility code and check in S8 if the units are on the recall list and place the from scratch them otherwise. Such as

```
[if]
    [have_unit]
        id=...
        search_recall_list=yes
    [/have_unit]
    [then]
       # recall unit
    [/then]
    [else]
        # create new unit
    [/else]
[/if]
```
Best would be to have an compatibility commit in a separate commit, because it should not go to master, but that can be changed afterwards too.

**Comment by joeylmaalouf** [comment]
Good to know, thanks! Quite the educational PR haha.

I've updated the fix commit accordingly, and added a separate compatibility commit that can be removed later.

**Comment by sevu** [comment]
Thanks a lot, excellent PR.

**Comment by joeylmaalouf** [comment]
Thanks! :smile:

**Pull request merged**
