### PR TITLE
images: crush pngs

### PR DESCRIPTION
**Pull request by matthiaskrgr**
Current version of the wesnoth-optipng script runs different optimizations on an image.
The problem is, if one of these optimization changes pixel color, all other optimizations are discarded as well.

In this commit I ran the optimizations independently (semi-manually) to optimize images that could not be optimized before.
Only images that were reduced by at least 10% in size, or if the reduction was larger than 1000 bytes should be included and since and all images were run through compare_images.py by the script while crushing.
 For the record, without the 10%/1000b  restriction, 11974 file would have been changed.

    stats:
	  1133 binary files changed 94949833 b (90 Mb) -> 93233125 b (88 Mb) => [-1716708 b (-1 Mb)]

I remember there were some problems once where a big crush commit had to be reverted, so it would be nice if people from different platform (windows/mac) could check that this briefly and give an ok. :)

### CODE REVIEW

**Comment by gfgtdf** [comment]
I'm not a native english speaker, but crush pngs dounds to me liek you'd be straing things which isnt hat hapens i think the standard name 'run optipng..' woudl be betteras a commit name.

Also i wonder whether it makes sense to make such a commit now. Note that, for developers this does increase the size of the repo since the old files still stay in te histrory. So i think it would be better to delay this commit until shortly before the wesnoth 1.14 release.

**Comment by AI0867** [comment]
A different note: When talking about bytes, the unit is B.
1000 B = kB
1024 B = KiB
1000^2 B = MB
1024^2 B = MiB
and so on

b refers to bits.

**Comment by ln-zookeeper** [comment]
For me, the main question is does it really make sense to increase the size of the repository by 88MB in order to shave off <2MB?

**Comment by CelticMinstrel** [comment]
The question is, which is more important? Lower repo size for devs, or lower download size for players?

Though shaving off 2MB doesn't seem like very much.

**Comment by matthiaskrgr** [comment]
Ok, closing.
The new script I am working on might provides slightly better results anyway, I hope :)

**Pull request closed without merging**
