### PR TITLE
addon_manager: allow uploading . dir

### PR DESCRIPTION
**Pull request by vgaming**
fixes GH-2494

### CODE REVIEW

**Comment by GregoryLundberg** [comment]
This looks good for Linux and, probably, macOS. Can you confirm it works as expected for Windows.

While it might not make much sense, can you test `..` as well.

Also, give a quick test for reasonable behavior using symbolic links, especially on Windows?

**Comment by vgaming** [comment]
@GregoryLundberg I tested `..`, it worked. (Well, no wonder, the code uses `realpath`.)
I could not test anything on macOS and Windows (I don't have these OS-es).
Considering the simplistic fix, I wouldn't bother TBH, but it's up to reviewers.

**Comment by GregoryLundberg** [comment]
I can test Windows on a VHost. I'm not that concerned about this change. I can see it will work on Linux and macOS but I remember some discussion a while ago about realpath in relation to Windows.

I'd merge this but I think, at this point, we should hold off until tomorrow in case the scheduled tag of 1.13.11 actually happens in a few hours. That way, if it needs further tweaking (I don't expect it will), it won't delay the release.

**Comment by vgaming** [comment]
rebased.

**Pull request merged**
