### PR TITLE
Simplify pot generation

### PR DESCRIPTION
**Pull request by soliton-**
Use a standard sed invocation and avoid rewriting the file.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
This is helpful, though it doesn't solve the issue that I can't build translations for the game itself alone without installing asciidoc, and it's also kind of unfortunate that updating the pot files and compiling the mo files are rolled together into the same task.

**Comment by soliton-** [comment]
To build just translations you can do `scons translations`.

**Comment by stevecotton** [comment]
I'm happy for it to merge, but I'm not sure it's necessary.

**Comment by soliton-** [comment]
It's necessary so it actually works on systems with POSIX conform sed implementations and not just on systems with GNU sed. Avoiding the file rewrite is a bonus.

I should fix it for cmake as well actually since it does the same thing.

**Comment by CelticMinstrel** [comment]
> To build just translations you can do `scons translations`.

Maybe this isn't discoverable enough. It doesn't appear to be listed in `scons --help` for example.

**Comment by Vultraz** [comment]
> updating the pot files and compiling the mo files are rolled together into the same task.

I thought we just read directly from the po files?

**Comment by soliton-** [comment]
Wesnoth supports both.

**Comment by CelticMinstrel** [comment]
> I thought we just read directly from the po files?

We do support this, yes. However, it's quite inefficient, so for the mainline text we distribute the compiled mo files. Think of the po support as mostly just a quicker way to test translations of add-ons.

**Pull request merged**
