### PR TITLE
Fix building with Xcode 10 on master

### PR DESCRIPTION
**Pull request by hrubymar10**
Fwdport #3458 of PR #3451 

## TODO
- [x] Fix Xcode 10 build - (965aeb3)
- [x] Fix Scons, Cmake and CodeBlocks builds - (965aeb3)
- [x] Fix Visual Studio build - (bb72d55)

### CODE REVIEW

**Comment by hrubymar10** [comment]
Can I ask @jyrkive again for fixing Visual Studio project? Thanks

**Comment by hrubymar10** [comment]
PR is prepared to be merged anytime

**Comment by hrubymar10** [comment]
@jyrkive , was renaming `src\gui\dialogs\game_version.cpp` to `src\gui\dialogs\game_version_dialog.cpp` necessary? Xcode 10 project worked already. Should I mirror this change to CMake, Scons and Codeblocks?

**Comment by jyrkive** [comment]
Yes, it was necessary for Visual Studio builds.

**Comment by hrubymar10** [comment]
This PR can be merged now. Failed Xcode travis build is not caused by anything related to this PR. I believe that it is some kind of bug with travis. I can't reproduce it locally.

**Comment by jyrkive** [comment]
Thanks for the pull request. :)

**Pull request merged**
