### PR TITLE
Draft 'Why did I lose?' help topic

### PR DESCRIPTION
**Pull request by jostephd**
Based on discussion in https://forums.wesnoth.org/viewtopic.php?f=3&t=18640

### CODE REVIEW

**Comment by beetlenaut** [comment]
This is a good idea. I like what you did with the topic title.

A couple points: 1) "a wrong strategy" should be "the wrong strategy," or better yet, "a poor strategy." That bullet point should also end with a period instead of a colon to match the others.
2) There is no reason not to say "Barely winning a previous scenario," instead of "Attaining a Pyrrhic victory in a previous scenario." Writing plainly is usually better.
3) We're trying to avoid people complaining about bad luck and so forth, so I think the unlikelihood of the items in the second list should be stressed more. Like: "These reasons probably don't apply, but are slightly possible:"
4) I still disagree that we should ever _expect_ people to have foreknowledge in order to win, but if everyone else is okay with it, I guess it can stay.

**Comment by jostephd** [comment]
Thanks for reviewing.

> A couple points: 1) "a wrong strategy" should be "the wrong strategy," or better yet, "a poor strategy." That bullet point should also end with a period instead of a colon to match the others.

I changed to "Playing a poor strategy", but I think the colon is correct: if I changed the colon to a period, the remainder of the line would be a sentence fragment. Or do you see a way to change the remainder of the line too? Sorry if I'm missing something obvious.

> 2) There is no reason not to say "Barely winning a previous scenario," instead of "Attaining a Pyrrhic victory in a previous scenario." Writing plainly is usually better.

I agree. Changed.

> 3) We're trying to avoid people complaining about bad luck and so forth, so I think the unlikelihood of the items in the second list should be stressed more. Like: "These reasons probably don't apply, but are slightly possible:"

I added a subheader and changed the text. What do you think?

> 4) I still disagree that we should ever _expect_ people to have foreknowledge in order to win, but if everyone else is okay with it, I guess it can stay.

I was just trying to summarize the current state of the discussion, not to set things in stone one way or the other. In any case, if we expect foreknowledge, we should document that for players; and if we expect winnability without foreknowledge, we should document that for UMC campaign authors, so they can add warnings if they write a campaign that expects foreknowledge.

**Comment by GregoryLundberg** [comment]
I would say we expect winability based upon the information on hand. If earlier discussion exposes a fact, then we should expect you to know that to complete the scene. Knowing that fact from some other source (say, a walk-through) might make it easier, but should never be required. If the campaign/scenario does not present the fact, and it cannot be discovered through normal play (say, by passing a choke-point [which you cannot by-pass], or attaining a certain goal), then the scenario needs to be fixed.

**Comment by CelticMinstrel** [comment]
Why was this merged with two `TODO` notes still in the text!?

**Comment by jostephd** [comment]
Good catch. Let's see:

> • Barely scraping a victory in a previous scenario. At all difficulties except “Beginner” (TODO: and “Easy”?), campaigns assume that you will have some <italic>text='carryover gold'</italic> and some advanced units on your <italic>text='recall list.'</italic>

On "Easy" difficulty, is it possible to win without carryover/recalls? Note that I mean "Easy" on the Beginner/Easy/Normal/Challenging/Difficult/Nightmare scale in the UI, _not_ EASY on the EASY/MEDIUM/HARD scale in WML.

> TODO: link to a forum thread where new players can post their replays and get review/corrections (like https://forums.wesnoth.org/viewtopic.php?f=3&t=39944 but specifically for new players)?

Should we create such a forum thread and link it from the help, or just delete this?

**Comment by CelticMinstrel** [comment]
Just for the record, if this can't be easily resolved, at least move the TODO notes to comments rather than placing them in the text.

**Comment by jostephd** [comment]
Created #4280. Thanks again for catching that.

**Pull request merged**
