### PR TITLE
Buff Dune Warmaster

### LINKED ISSUE #9533: Buff DF Warmaster
### Describe the desired feature

Currently, the DF Warmaster is very underpowered, with only a 9-4 melee attack. This is the same as the general, but the general has a ranged attack, more hitpoints and an extra movement point. The only thing that the Warmaster has that is better is that is it 9g cheaper. I personally would buff the Warmaster by changing the hitpoints to 61 and the attack to 10-4, which makes it a stronger unit within the rest of the dunefolk faction. 

@Hejnewar

### PR DESCRIPTION
**Pull request by Gothyoba**
Fixes #9533

### CODE REVIEW

**Review by knyghtmare — APPROVED** [review]
2 buffs, no ranged damage, melee support unit, high priced already. It's fine.

**Comment by knyghtmare** [comment]
@Dalas121 what is stalling this PR?

**Comment by Dalas121** [comment]
Well... I guess this should go through a balance team vote first. I don't think it'll be controversial, but need to keep things legitimate. I'll post a poll in the balance team.


Also it needs a changelog.

**Comment by Gothyoba** [comment]
Sorry about that! I have added a new changelog entry which I hope should be appropriate.

**Comment by Dalas121** [comment]
Balance team vote held (credit to Knyghtmare), PR approved 3-0. Merging

**Pull request merged**
