### PR TITLE
Added new functions sgn(), int() and frac()

### PR DESCRIPTION
**Pull request by spixi**
This adds some new useful functions to the Wesnoth Formula Language.

Finally, I know how branches work ...

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I didn't add `sgn()` before simply because it's easy to implement as an inline formula function (ie `def sgn(x) if(x < 0, -1, x > 0, 1, 0);`). I think `frac()` is also implementable as an inline function using modulus (something like `def frac(x) x % 1.0;`), but I haven't tested that. Proof that they can be implemented inline is not necessarily sufficient reason to reject this pull request, though.

The `int()` implementation looks a little suspect, however. First of all, does it convert strings to integers? If so, I would call it `as_int()` instead, in analogy to the existing `as_decimal()`. On the other hand, if it doesn't convert strings, then I'm not sure how it would be any different from `round()`?

**Comment by spixi** [comment]
@CelticMinstrel

I added the `sgn()` and `frac()` functions to be more consistent with existing maths frameworks. I know that they can be implemented as user functions `frac(x) =  x - int(x)` and `sgn(x) = x/abs(x)`, but I thought it would be useful to have them inbuilt.

The difference between `ceil` (round to next integer), `floor` (round to previous integer), int (extract integer part of real number) and round (round to nearest integer) can be seen in the following table:

|number|ceil|floor|int|round|
|-------|-------|-------|-------|-------|
|1.4|2|1|1|1|
|-1.4|-1|-2|-1|-1|
|1.5|2|1|1|2|
|-1.5|-1|-2|-1|-2|

**Comment by CelticMinstrel** [comment]
I see. That's fine then - `int()` could also be called `trunc()` (for "truncate"), since it rounds towards zero. (By the way, `ceil()` is "round towards infinity" and `floor()` is "round towards negative infinity".)

Regarding `sgn()` and `frac()`, I don't think the Lua math framework has them, not that that's relevant in any way.

>The `sgn()` function for complex numbers looks different, for example.

WFL doesn't support complex numbers anyway.

**Comment by CelticMinstrel** [comment]
I've thought it over a bit, and decided I actually prefer the name `trunc()` instead of `int()` - calling it `int()` may give people the impression that it's a cast, when in fact it's merely a rounding function.

**Pull request merged**
