### PR TITLE
remove 'experimental_' of filter_ability/specials tags

### PR DESCRIPTION
**Pull request by newfrenchy83**
now what 1.18 separate of master branch it istime of aiming for that.

### CODE REVIEW

**Comment by soliton-** [comment]
IMO removing the experimental prefix should be done at the same time as the issues with the tag are largely fixed.

Which to me means addressing #7992 and #7926 at least.

**Comment by newfrenchy83** [comment]
> IMO removing the experimental prefix should be done at the same time as the issues with the tag are largely fixed.
> 
> Which to me means addressing #7992 and #7926 at least.

i think have fixed tags problems

**Comment by newfrenchy83** [comment]
> IMO removing the experimental prefix should be done at the same time as the issues with the tag are largely fixed.
> 
> Which to me means addressing #7992 and #7926 at least.

[filter_wml] added

**Comment by newfrenchy83** [comment]
@soliton- @stevecotton I don't want to seem like I'm rushing you but I would like to be able to add [filter_wml] and since I'm supposed to do it in another PR, I need this one to be merged into master before I can do that and rebase https: //github.com/wesnoth/wesnoth/pull/8546

**Comment by newfrenchy83** [comment]
@Pentarctagon could you review this PR and https://github.com/wesnoth/wesnoth/pull/7814, please?

**Comment by Pentarctagon** [comment]
@soliton- my understanding is that #7992 has to be resolved in order for the `experimental_` prefix to be removed?

**Comment by soliton-** [comment]
Yes.

**Comment by newfrenchy83** [comment]
> @soliton- my understanding is that #7992 has to be resolved in order for the `experimental_` prefix to be removed?

What issue remains to be resoved then?

**Comment by soliton-** [comment]
The code that #7992 clearly references is still in master at even nearly the same line number. It is very difficult for me to take this question in good faith.

**Comment by newfrenchy83** [comment]
@Pentarctagon Now what https://github.com/wesnoth/wesnoth/issues/7992 issue is closed,can you merge abd review https://github.com/wesnoth/wesnoth/pull/7814, please?

**Comment by Pentarctagon** [comment]
I will give it some time to see if there are any comments made.

**Comment by soliton-** [comment]
I still think that #7926 should be addressed. Probably the only part missing is combining `[filter_ability]` and `[filter_ability_active]`

**Comment by newfrenchy83** [comment]
> I still think that #7926 should be addressed. Probably the only part missing is combining `[filter_ability]` and `[filter_ability_active]`

Oh no! No way! Since filter_ability_/active is the only case where we can check abilities that are simply present or active, while overwrite_specials (and [filter_specials] pending) can only check active special weapons, and [remove_specials] (still pending) present special weapons, I don't see the point of creating a super tag to implement an attribute to check the activity that will only be usable to replace filter_ability_/active while the others will either check active weapons or can only check present weapons.

**Comment by soliton-** [comment]
If you can explain a technical issue, ideally in french, then I'll try to figure out what you mean.

**Comment by newfrenchy83** [comment]
> If you can explain a technical issue, ideally in french, then I'll try to figure out what you mean.

It's simple, since there are only two filters that can be replaced by what you suggest, why should I complicate things unnecessarily? Because it will not simplify them contrary to what you think. The problem is not technical, it is that in https://github.com/wesnoth/wesnoth/pull/7814 which remains to be merged there is only [remove_specials] tag in [effect] or [filter_special_active] to [has_attack/filter_weapon], one does not check if the special is active, the other has no [filter_specials] version

**Comment by newfrenchy83** [comment]
> So the issue is that some `[filter_ability]` use will not support setting `active` to `no`?

Yes

**Comment by soliton-** [comment]
Where is that use? I see no hint on https://wiki.wesnoth.org/StandardAbilityFilter, https://wiki.wesnoth.org/AbilitiesWML or  https://wiki.wesnoth.org/EffectWML.

I guess you actually mean it would not be supported to set `active` to `yes`?

**Comment by Pentarctagon** [comment]
It sounds like we're at an impasse here then?

**Comment by newfrenchy83** [comment]
> It sounds like we're at an impasse here then?

only because @soliton- want absolutely what unsuse design of https://github.com/wesnoth/wesnoth/issues/7926 was applied.

**Comment by newfrenchy83** [comment]
@Pentarctagon add 'active' attribute in filter is imossible because for [filter_specials] in overwrite or [filter_specials] in await to review, specials are mandatory active. unit [filter_ability] and [filter_ability_active] are the one who could be applied, but this one case don't justify this 'improvement'.

**Comment by soliton-** [comment]
What is the difference between `[filter_ability]` and `[filter]` in `[effect]` for example? Presumably using `ability_type_active` in `[filter]` works just the same?

**Comment by newfrenchy83** [comment]
> What is the difference between `[filter_ability]` and `[filter]` in `[effect]` for example? Presumably using `ability_type_active` in `[filter]` works just the same?

[filter][filter_ability_active] in [effect] must be working like [filter]ability_type_active but [filter_special_active] will not because not combat context. [remove_specials] remove specials who match, but only if owned by unit in [attack]

**Comment by newfrenchy83** [comment]
ability_type_active will check type of abilities [filter_ability_active] can check type, id, or other attributes.

**Comment by Pentarctagon** [comment]
What I'm not understanding is: what's the difference between the engine checking for `[filter_ability_active]` vs `[filter_ability]` with the `active` attribute set to `yes`? Both options seem like they represent the same information.

**Comment by newfrenchy83** [comment]
> What I'm not understanding is: what's the difference between the engine checking for `[filter_ability_active]` vs `[filter_ability]` with the `active` attribute set to `yes`? Both options seem like they represent the same information.

The difficulty to implement instead of separate tag names and what in some case, ability are mandatory active or what activity can't be checked, and 'active' option usable only when both option exist.

**Comment by soliton-** [comment]
> > What is the difference between `[filter_ability]` and `[filter]` in `[effect]` for example? Presumably using `ability_type_active` in `[filter]` works just the same?
> 
> [filter][filter_ability_active] in [effect] must be working like [filter]ability_type_active but [filter_special_active] will not because not combat context. [remove_specials] remove specials who match, but only if owned by unit in [attack]

Fine, then what is the difference between `[filter] [has_attack] special_type_active=...` and `[filter_special]`?

**Comment by newfrenchy83** [comment]
> > > What is the difference between `[filter_ability]` and `[filter]` in `[effect]` for example? Presumably using `ability_type_active` in `[filter]` works just the same?
> > 
> > 
> > [filter][filter_ability_active] in [effect] must be working like [filter]ability_type_active but [filter_special_active] will not because not combat context. [remove_specials] remove specials who match, but only if owned by unit in [attack]
> 
> Fine, then what is the difference between `[filter] [has_attack] special_type_active=...` and `[filter_special]`?

special_type_active don't work in [has_attack]  then if the same for [filter_special_active].

**Comment by newfrenchy83** [comment]
And stop to make the list of case of ability_type_active versus filter_special, one check only type, other use multiple critera

**Comment by soliton-** [comment]
> And stop to make the list of case of ability_type_active versus filter_special, one check only type, other use multiple critera

I don't see why that matters. The point is that there are already cases of certain features not working in every context (and even very similarly in a filter tag and concerning abilities/weapon specials) so it does not appear sensible to deviate from that design for new filter tags.

If you want to argue that certain features of a tag not working in every context is terrible (especially since it does not seem to be mentioned in the documentation at all) then we can have that conversation but that should not just involve `[filter_ability]` or `[filter_special]`.

---

As an aside I'm not stubbornly insisting on my point of view just because. I'm insisting on it until I'm presented with convincing arguments on why it is a bad idea and a different concept is better. The way I see it that has not happened here yet. Other people are certainly free to see that differently and are definitely encouraged to voice that opinion.

**Comment by Pentarctagon** [comment]
@newfrenchy83 once the conflicts are resolved I will merge this PR as well.

**Comment by newfrenchy83** [comment]
> @newfrenchy83 once the conflicts are resolved I will merge this PR as well.

it's done.

**Pull request merged**
