### PR TITLE
Allow paths with ".." in macro inclusions

### PR DESCRIPTION
**Pull request by CelticMinstrel**
I have made this safe (I think) by resolving any ".." components manually while the path is still a relative path to the gamedata or userdata directory. If there are ".." components left over that can't be resolved (ie, at the beginning of the path), then it's an error. Otherwise, resolution then proceeds as normal, depending on whether it's a WML path (which is also used by Lua) or binary path.

I think this could use an audit to determine if it's truly safe. I did add some unit tests to make sure it would be safe, but I'm not sure if it covers every possible case.

With this it should be possible to make any addon not depend on the name of its folder.

### CODE REVIEW

**Comment by gfgtdf** [comment]
i don't like these commits, now get_wml_location is sometimes called with absolute paths, sometimes with relertive paths, sometimes it makes removes a part of the path sometimes not. In conslusion it makes to much harder to veryfy that these functions are actually safe. Even if this commit wouldn't create securits issues directly it it makes the code harder to understand and thus easier to accudnetly create seciruily issues later.

the best fix would probably to make the preprocessor code internally always use relertive paths aswell and then behave like the lua functions did previously.

also note the following potentionl security issue:
```
a = load("return wesnoth.read_file('filename')", "@path/to/wesnoth/C:/system/someimportantfile.txt)()
```
will the function remove the leading 'path/to/wesnoth' so that only 'C:/system/someimportantfile.txt' remains?

**Comment by CelticMinstrel** [comment]
In your example, I'm pretty sure it would interpret that "C:" as the name of a file under "path/to/wesnoth", but it might depend on Boost.Filesystem to some extent.

Make the preprocessor pass relative paths as the current directory? I suppose I could try that. In that case, I suppose it could interpret an absolute path as the gamedata directory? (And issue a warning, of course.)

**Comment by GregoryLundberg** [comment]
Do you track the internal '../' components to check for underflow?

For example "dir/../../somefile" is semantically identical to "../somefile"

Note that "dir" above does not need to exist (and be a directory) if you are handing the "../" component internally.

**Comment by CelticMinstrel** [comment]
Based on the logic I wrote, "dir/../../somefile" should indeed be resolved to "../somefile" by the `resolve_filename` function. The resolved name is then passed through `is_legal_file` though, which (as before) returns false because it contains a ".." component.

**Sudden thought:** I wonder if I should manipulate the path components by iterating through a `bfs::path` instead of searching through the path as a simple string...

**Comment by loonycyborg** [comment]
If you want to reliably prevent tricks with embedded ".." you should consider this function: http://www.boost.org/doc/libs/1_64_0/libs/filesystem/doc/reference.html#canonical . It even expands symbolic links.

**Comment by CelticMinstrel** [comment]
I think I looked at that function but had some reason for not using it... possibly because it only works on files that actually exist?

**Comment by loonycyborg** [comment]
http://www.boost.org/doc/libs/1_64_0/libs/filesystem/doc/reference.html#weakly_canonical this one doesn't require path to exist.

**Comment by CelticMinstrel** [comment]
Hmm, okay. Maybe that could replace the custom function I wrote to resolve paths, then. I'll take a look at some point... maybe this weekend.

**Comment by gfgtdf** [comment]
I made my own version of this which is think is easier to veryfy wrt security issues https://github.com/wesnoth/wesnoth/pull/4953 ,

**Comment by Pentarctagon** [comment]
@gfgtdf @CelticMinstrel is this PR still relevant given #4953?

**Comment by CelticMinstrel** [comment]
Probably not? I basically needed to redo this anyway so as long as there's an alternative don't think there's any reason to keep this one open.

**Pull request closed without merging**
