### PR TITLE
Consistently sort damage types

### PR DESCRIPTION
**Pull request by soliton-**
The double sorting before should have used stable_sort. Now we sort just the types with the highest frequency count.

### CODE REVIEW

**Comment by newfrenchy83** [comment]
And when two damage type différent are same fréquence? I alphabétical order used?

**Comment by soliton-** [comment]
Yes. The second loop picks the max frequency types and that list is then sorted.

Could also use a std::map and then it’s already sorted but I think explicit sorting might be more readable.

**Comment by newfrenchy83** [comment]
If alphabétisation sort not used when two type are same fréquence then two leadehip damag_type are used, the type used dépend of position of leader, it why i have places a double sort and i cannot approve thi PR

**Comment by newfrenchy83** [comment]
> Yes. The second loop picks the max frequency types and that list is then sorted.
> 
> Could also use a std::map and then it’s already sorted but I think explicit sorting might be more readable.

oh, i haven't see what std::sort moved in end of selection but why use unordered::map for be back to vector, it was not simplest to sort by frequency only when vector size contain 3 string mininum, because it is not util to doing that when vector has 2 element max(same type or 1 emleent for each type diffrent)?

**Comment by newfrenchy83** [comment]
what sort by alphabetical order was placed in end of loop, ok, and replace optional string by string also but use unordered_map for back to vector instead of use vector directly, i don't understand.

**Comment by soliton-** [comment]
I can't really tell what you're asking. Perhaps look at the final code instead of the diff.

https://github.com/wesnoth/wesnoth/blob/1fb094ecfb0550629ffc966146939f9a7f20a509/src/units/abilities.cpp#L1171-L1196

One could add a special case for `type_count` size equal to 1 or 2 but I don't think it's particularly worth it.

**Comment by newfrenchy83** [comment]
you could add that
 `	if(max ==1  && max == 2){
		std::string type;
		for(auto& i : type_count) {
			if(i.second == max || max == 1) {
				type = i.first;
				break;
			}
		}
		return type;
	}`

**Comment by newfrenchy83** [comment]
ok add that like it is.

**Comment by soliton-** [comment]
Superseded by c7080e0eccc24681f10cb469d8b2037e46cf4db5.

**Pull request closed without merging**
