### PR TITLE
Replace fog and shroud in map files

### PR DESCRIPTION
**Pull request by hexagonrecursion**
This PR fixes the following wmllint errors:
```
"../../data/multiplayer/maps/6p_Team_Survival.map", line 2: warning, fog or shroud in map file
"../../data/multiplayer/maps/Dark_Forecast_drought.map", line 2: warning, fog or shroud in map file
"../../data/multiplayer/maps/Dark_Forecast_firstsnow.map", line 2: warning, fog or shroud in map file
"../../data/multiplayer/maps/Dark_Forecast_secondsnow.map", line 2: warning, fog or shroud in map file
```

### CODE REVIEW

**Comment by soliton-** [comment]
What issue is that fixing other than the wmllint message?

**Comment by hexagonrecursion** [comment]
Only a wmllint message as far as I can tell. Fixing wmllint errors is important. fewer&nbsp;errors=less&nbsp;noise=wmllint&nbsp;becomes&nbsp;a&nbsp;more&nbsp;useful&nbsp;tool

**Comment by soliton-** [comment]
Sure, so if there is no actual issue why not remove the wmllint message instead?

**Comment by hexagonrecursion** [comment]
We could ask the people who added the rule to wmllint.

https://github.com/wesnoth/wesnoth/commit/981477720caee06933df33dd0a1446469912198b#diff-2a47ac9772f0f3b50faf9387a746df6423bda6f870585aa06d079c7fbd8db5bdR1141

https://github.com/wesnoth/wesnoth/commit/ab95662720c540af4bb7acb4b8aa4400305ab66f#diff-2a47ac9772f0f3b50faf9387a746df6423bda6f870585aa06d079c7fbd8db5bdR2886

@eric-s-raymond , @Elvish-Hunter , why are "fake fog" and "fake shroud" banned from map files?

**Pull request merged**
