### PR TITLE
Add yellow and pink color_range

### PR DESCRIPTION
**Pull request by ProditorMagnus**

### CODE REVIEW

**Comment by ProditorMagnus** [comment]
https://github.com/ProditorMagnus/Color_Modification/blob/master/_main.cfg

**Comment by stevecotton** [comment]
I think it's too late for 1.18; while I'd agree with this for master, it might be worth postponing a couple of months before diverging from 1.18.

**Comment by ProditorMagnus** [comment]
Yes, only for master.

**Comment by CelticMinstrel** [comment]
This isn't a change that seems likely to create conflicts with backports. I'd be okay with merging it sooner instead of waiting.

**Comment by ProditorMagnus** [comment]
Any conflicts will be only cosmetic, if one client has color_range and other doesnt, the one who doesnt have will see this color units as green and purple.

**Pull request merged**
