### PR TITLE
Addon Manager: Don't use "ascending" and "descending" to describe how dates are sorted.

### PR DESCRIPTION
**Pull request by jostephd**
~Everyone is not a programmer.~

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I don't get what this has to do with whether people are programmers?

**Comment by jostephd** [comment]
Describing a chronological sorting as "in ascending order" is more understandable to programmers than to non-programmers, right? It's the rationale of the change.

**Comment by CelticMinstrel** [comment]
Like I said, I have no idea what this has to do with programmers vs non-programmers. As far as I'm aware, "ascending" is a perfectly standard English word. It's not a programmer word or anything.

**Comment by jostephd** [comment]
Ignore that remark then. This patch changes the text in the addon manager dropdown from "First upload (ascending)" to "First upload (oldest to newest)". Do you think that's a good change?

**Comment by CelticMinstrel** [comment]
I'm not opposed to the change in this PR, no.

**Comment by jostephd** [comment]
Cool. I removed that sentence from the log message.

**Comment by jyrkive** [comment]
The only reason why I abbreviated "ascending" and "descending" to "asc" and "desc" in the first place is that I wanted the whole text to fit into the dropdown when it's at the maximum size (window size 1920x1080).

Now when you have replaced them with much longer "oldest to newest" and "newest to oldest", the reason why I abbreviated "ascending" and "descending" is no longer valid. Thus, please change "asc" and "desc" to "ascending" and "descending" and delete the translator comments.

**Comment by jostephd** [comment]
Done

**Comment by jyrkive** [comment]
Thanks, merged. :)

**Pull request merged**
