### PR TITLE
Do not load Markov name generator if a CFG generator could be loaded

### PR DESCRIPTION
**Pull request by gunchleoc**
name_generator_factory::add_name_generator_from_config now only falls
back to loading a Markov-chain generator if the loading of the context-
free grammar generator fails or there is none available.

Motivation for the change: Until now, the CFG generator would be ignored for the base names. The Markov generator can't be adapted to my locale. c.f. [Forum discussion](https://forums.wesnoth.org/viewtopic.php?f=12&p=607975#p607889).

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Well, functionally I have no objection to this change, but... is it my imagination, or could it have been done as just a one-line change on line 48? (Adding "else" before the "if".)

**Comment by gunchleoc** [comment]
No, we also need the fallback in case the rules for the context-free generator contain an error. Errors are really easy to make - I just weeded out quite a lot of them in my translation by running them through [Dugi's generator](http://physics.muni.cz/~dugi/index.fcgi/cfggen).

**Comment by CelticMinstrel** [comment]
Oh, right. In that case, maybe just adding an early return after successfully loading the CFG would work?

**Comment by gunchleoc** [comment]
Early return and else do the same, so it's a question of which code style Wesnoth prefers. I can change this to early return if you prefer.

We still need both calls though, because there are 2 possible errors:

1. the context-free grammar can't be parsed
2. The context-free grammar is missing

As to the dialog, this is my first code contribution, so I'm the wrong person to ask. The dialog would be annoying for players though, so it should be there only in debug mode. There is already an error log being written when an exception occurs, although I have no idea where the error log is. It- would be nice to have the error log location documented in the [wiki](https://wiki.wesnoth.org/ReportingBugs).

**Comment by CelticMinstrel** [comment]
Well, I just thought that if you arrange the code correctly, you could get the same effect as you have here without actually having a function at all. If you use an early return when a CFG is successfully loaded, execution only reaches the next if statement (in the original code) when the CFG was not loaded, whether it's because of an error loading it or simply because the first if was never entered. The use of a new function for this just feels a bit... excessive. There's no other reason to call it. If you're going to stick to the new function, at least make it private. But I do think it's cleaner to keep everything in the one function.

**Comment by gunchleoc** [comment]
You mean like this?

```
void name_generator_factory::add_name_generator_from_config(const config& config, const std::string id, const std::string prefix) {
 	std::string cfg_name 	= prefix + "name_generator";
	std::string markov_name = prefix + "names";

	if(config.has_attribute(cfg_name)) {
		try {
			name_generators_[id] = std::shared_ptr<name_generator>(new context_free_grammar_generator(config[cfg_name]));
			return;
		}
		catch (const name_generator_invalid_exception& ex) {
			lg::wml_error() << ex.what() << '\n';
		}
	}

	if(config.has_attribute(markov_name)) {
		config::attribute_value markov_name_list = config[markov_name];

		if(!markov_name_list.blank()) {
			name_generators_[id] = std::shared_ptr<name_generator>(new markov_generator(utils::split(markov_name_list), config["markov_chain_size"].to_int(2), 12));
		}
	}
}
```

**Comment by CelticMinstrel** [comment]
Pretty much like that, yeah.

**Comment by gunchleoc** [comment]
Done. Thanks for the review :)

**Pull request merged**
