### PR TITLE
Backport map_file feature fixes for 1.14

### PR DESCRIPTION
**Pull request by fluffbeast**
This branch combines fixes needed for using map_file.

See issues #4407, #4397, #4519, and #4652 for details.

### CODE REVIEW

**Comment by Pentarctagon** [comment]
Was changing `map_data` to `map_file` on just Aethermaw intended?

**Comment by fluffbeast** [comment]
Yes, that was intended as an example, and to match the change in #4407.

**Comment by gfgtdf** [comment]
well even though its technically a 'bugfix', backporting this would still encourage people to write code that is incompatible to older 1.14 versions for a rather little gain. So in fact i think really think we shodul put this into 1.14 . I think its better if we change  the documentation to just say that map_file is not supported in [multiplayer] in 1.14.

**Comment by Pentarctagon** [comment]
I was wondering why a new API feature was added mid-way through 1.14.  Though, I don't think there's any reason to not do both (change the documentation and fix the bugs).

**Comment by gfgtdf** [comment]
> Yeah, I was wondering why a new API feature was added mid-way through 1.14

well it wasn't really added mid way it was always there in a halfway broken and  undocuemented way.

**Comment by Pentarctagon** [comment]
I mean that according to the wiki, the `map_file` attribute was newly added in 1.14.3, when it really shouldn't have been added to 1.14 at all at that point.  Given that it's already in 1.14 though, I don't think it really makes sense to intentionally leave it broken, especially given the fixes don't themselves break compatibility and are also relatively small.

**Pull request merged**
