### PR TITLE
[SoF] Minor bugfixes

### PR DESCRIPTION
**Pull request by nemaara**
Added some snow for #3416. Gameplay and other things should be exactly the same as before, I only swapped out some tiles that don't affect the player at all.

### CODE REVIEW

**Comment by nemaara** [comment]
Third commit puts guards for #3402.

**Comment by nemaara** [comment]
Latest commits take care of #3384.

**Comment by sevu** [comment]
I think the second commit is not a equivalent replacement for the Wose. The Wose has the advantage to be hidden, the Troll Welp is just canon fodder.

Pinging @Konrad22

**Comment by Konrad22** [comment]
I believe we can disregard the ambush ability in this case as all enemy units are rushing for the player anyway. Troll whelps fit better into the the story (and are way easier to explain) and are no more cannon fodder than woses. I'm fine with that commit.

**Pull request merged**
