### PR TITLE
Remove doxygen comments for GUI2.

### LINKED ISSUE #7899: GUI documentation regression
When converting custom documentation format to doxygen in https://github.com/wesnoth/wesnoth/commit/6389c1e the split between widget definition and instance got removed.

Before https://wiki.wesnoth.org/index.php?title=GUIToolkit&diff=prev&oldid=66491 the documentation on the wiki was split into GUIWidgetDefinitionWML and GUIWidgetInstanceWML.

Now looking at https://devdocs.wesnoth.org/classgui2_1_1label.html#details for example you have to guess which part is documenting a label definition and which a label instance.

It would also be good to return the documentation to above the code that it documents to have a much better chance at keeping them in sync. As far as I can tell the `@ingroup` directives decide where the documentation ends up so there should be no issue moving it back.

### PR DESCRIPTION
**Pull request by Pentarctagon**
Instead move this documentation over to the wiki under https://wiki.wesnoth.org/Category:GUI_WML_Reference

Fixes #7899

### CODE REVIEW

**Comment by Pentarctagon** [comment]
@soliton- any issue if I merge this?

**Comment by soliton-** [comment]
Nope, looks good to me. Thanks for doing this.

**Comment by white-haired-uncle** [comment]
Just noticed this and couldn't figure out how to comment on the wiki.

It would help if the units were labelled.  For example, "The time it take before..." in milliseconds?  I'll bet that's right, but only because I happened to look at something, somewhere, sometime in the past.  Height/width/font(?) are probably in pixels, but it would be nice to say so for those of us just getting started.

**Comment by CelticMinstrel** [comment]
> Just noticed this and couldn't figure out how to comment on the wiki.

If you want to comment on the wiki you can just click the discussion button (second button along the top), type your comment into the edit window, and terminate it with 4 tildes (`~~~~`), then just save the page. If the talk page already exists there's also a button to start a new topic in it (the 4th button from the left). Both the mentioned buttons use chat bubble icons.

You can also comment on IRC/Discord instead – we seem to tend towards using this more than MediaWiki's primitive native commenting system, but there's no reason we _can't_ use the talk pages.

**Comment by Pentarctagon** [comment]
It was moved to the wiki in large part to make it easier for people to update and improve, so feel free to add what you know to those pages as well.

**Pull request merged**
