### PR TITLE
Support loading translations from PO files

### PR DESCRIPTION
**Pull request by CelticMinstrel**
This makes things easier for addon campaigns to ship portable translations, since ~~the MO format is platform-dependent (although it should be compatible on all main platforms), and as I understand would eliminate the need for "wescamp"~~ MO files require the gettext tools to create.

~~Before merging, steps need to be taken to ensure that scons and CMake builds correctly result in a _translations_ directory containing po files, instead of mo files. In the XCode project I did this with rsync; scons and CMake could perhaps make do with simply renaming the _po_ directory in the repo to _translations_.~~

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
The build appears to be failing only due to warnings within the spirit_po headers. I'm not sure the best way to fix this - any ideas? Should I use a pragma?

**Comment by gfgtdf** [comment]
Whats the current state of this? does it still perform noticeably worse than the current code?

**Comment by CelticMinstrel** [comment]
The only performance issue that I recall was when switching languages, and I made it show the loading screen for that - it still takes at least a minute to load the new language, but language-switching is probably a one-time thing for most people, so I don't think that's a major problem.

I considered using .mo files for mainline and .po for addons, but I didn't really understand the previous code, and as such it was simpler to just switch everything to .po. I don't really understand how .mo files are used, but if they're loaded into memory all at once, there should be no difference in performance compared to .po files; and if they're not loaded into memory all at once, switching to .po files as I've done here may actually be marginally faster. I haven't done any timing tests, mind you, so this is only speculation.

**Comment by gfgtdf** [comment]
Also, you should move those library files to a seperate folder instead of having them at lop level.

**Comment by cbeck88** [comment]
@CelticMinstrel: The warnings are about "missing field initializers" were considered a bug and fixed in gcc 5, then the fix was backported to gcc 4.9.2

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=36750
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55805

IMO if master branch requires C++11 then you should drop support / testing for gcc 4.7 since it does not support C++11. Support is still highly experimental at that point. If for instance there is a compiler that got doesn't quite get it right when it should use default initialization or value initialization when initializing structures like this, you can get undefined behavior.

In the past wesnoth devs have always been extremely reluctant to increase compiler requirements even when it is important to do so, and I've gotten really tired of fighting such battles. But it's not up to me, you guys can decide what you want. I'm not officially supporting any gcc versions prior to 4.9 in `spirit_po` though.

**Comment by Vultraz** [comment]
Wait, 4.7 doesn't support C++11? Travis was building with 4.8 before we moved to C++11, but it was decreased to 4.7 since it was said that was the minimum. If that's not the case, we should certainly bump our minimum requirements to 4.8 or even 4.9, if SpiritPo requires it.

**Comment by cbeck88** [comment]
4.7 has experimental support but I remember that it had a lot of bugs. 4.8 was mostly good, I switched to 4.9 at some point because I tried to expand a parameter pack inside a lambda using `[&]` capture and it couldn't handle it.

**Comment by Vultraz** [comment]
Alright, then I certainly agree we should bump our requirements to 4.9.

**Comment by CelticMinstrel** [comment]
GCC 4.7 does support a large chunk of C++11. I guess 4.9 or something is the first compiler to _fully_ support it. Note however that even if we move to GCC 4.9, we still cannot use the entirety of C++11, because we're also bound by the need to support MSVC 2013. So, I don't think bumping the GCC version would benefit us that much. (Feel free to do the research and get back to me though - ie, investigate which features are supported in GCC 4.9 _and_ MSVC 2013 but not in GCC 4.7.)

**Comment by cbeck88** [comment]
It's not just about what features are supported, I mean sure, the feature list shows that most things are *implemented* in gcc 4.7. https://gcc.gnu.org/gcc-4.7/cxx0x_status.html But the question is really about what *bugs are fixed* at that point imo.

At the least, it would help you with that warning you mentioned, iiuc.

**Comment by CelticMinstrel** [comment]
Well, fair enough. That warning could also be dealt with by explicitly suppressing it though (I assume), so I'm not sure if upgrading solely for the warning is worthwhile.

**Comment by cbeck88** [comment]
Yeah, that's also fair enough.

**Comment by Vultraz** [comment]
I know we suppress warnings a lot, but I think bumping is a cleaner solution, at least to 4.8.

**Comment by cbeck88** [comment]
I think the last time I argued with shadowm about this, the issue was that he didn't want to have to update the compiler on the server which is used to compile `wesnothd`. But that had to have been more than a year ago.

**Comment by aginor** [comment]
I think it should be safe to make gcc 4.8 our minimum supported version as opposed to 4.7, as http://packages.ubuntu.com/trusty/gcc is 4.8. Debian stable is at 4.9, https://packages.debian.org/stable/devel/gcc.

However, if we still want to support debian oldstable we cannot move past 4.7 as that's the version shipped with it. https://packages.debian.org/oldstable/devel/gcc

**Comment by cbeck88** [comment]
@aginor: So as I recall, shadowm and anonymissimus told me some years ago that wesnoth dependencies historically track debian stable.

If it works now on debian oldstable, that's great, and there's no particular reason to change it.
But, I don't think there are realistically any users who are using debian oldstable and aren't willing to upgrade to stable to play a game released in 2016. I mean debian oldstable is not more stable than debian stable, it's just older... usually only like servers and stuff run debian stable. Whatever someone's machine is that they use for gaming, they are probably willing to upgrade to debian stable.

**Comment by CelticMinstrel** [comment]
Like I mentioned on the mailing list, the Debian oldstable package repos (when I last checked) do not even have Wesnoth 1.12 (they're still on 1.10), so I don't think supporting oldstable should be considered a priority. I can't recall off the top of my head if there were additional reasons for targeting GCC 4.7.

**Comment by CelticMinstrel** [comment]
So, I've redone this, softening it to supporting both PO and MO files. What this means is that addon developers do not need the gettext tools - they can just drop PO files into their translations directory, in a subdirectory named after the textdomain. It needs more testing before merging, in particular a test using an actual addon (I've been testing by substituting the translations folder with a renamed po folder). I'm also not sure if the error handling is sufficient; it writes PO errors to the log at the moment because I can't use GUI code from within the _gettext_boost.cpp_ file and am not sure if there's an exception I can throw that will trigger a nice GUI message.

**Comment by CelticMinstrel** [comment]
So, I've redone this, softening it to supporting both PO and MO files. What this means is that addon developers do not need the gettext tools - they can just drop PO files into their translations directory, in a subdirectory named after the textdomain. It needs more testing before merging, in particular a test using an actual addon (I've been testing by substituting the translations folder with a renamed po folder). I'm also not sure if the error handling is sufficient; it writes PO errors to the log at the moment because I can't use GUI code from within the _gettext_boost.cpp_ file and am not sure if there's an exception I can throw that will trigger a nice GUI message.

**Comment by CelticMinstrel** [comment]
Github only says it's unmerged because I squashed the fixup. Just for the record.

**Comment by CelticMinstrel** [comment]
I squashed the fixup and merged this manually; that's why it shows as unmerged.

**Pull request closed without merging**
