### PR TITLE
Changes in prices of monster units and Chocobone.

### PR DESCRIPTION
**Pull request by Hejnewar**
Solving #5058.

Changelog:
Cost of Gigant Rat changed from 6 to 5.
Cost of Gigant Scorpling changed from 13 to 12.

Cost of Fire Guardian changed from 16 to 11.
Cost of Gigant Mudcrawler changed from 11.
Cost of Gigant Scorpion changed from 22 to 16.
Cost of Wolf changed from 17 to 15.

Cost of Chocobone changed from 38 to 28.
Cost of Cuttle Fish changed from 40 to 36.
Cost of Great Wolf changed from 30 to 21.
Cost of Gryphon changed from 40 to 29.
Cost of Water Serpent changed from 26 to 23.

Cost of Direwolf changed from 36 to 33.
Cost of Sea Serpent changed from 40 to 55.
Cost of Wyvern changed from 54 to 75.
Cost of Wyvern Rider changed from 80 to 102.

### CODE REVIEW

**Comment by Pentarctagon** [comment]
Generally I'd recommend doing changes to changelog.md separately, in order to avoid merge conflicts like the PR has currently.

**Comment by Hejnewar** [comment]
Then I will avoid changing changelog.md in my PRs in the future.

**Comment by Pentarctagon** [comment]
Thanks.  Is there any reason to keep this and the other PR open then, or should I merge them?

**Comment by Hejnewar** [comment]
You can merge them.

**Comment by soliton-** [comment]
Are the changelog entries getting committed later?

**Comment by Pentarctagon** [comment]
Added in e4eeee73bb13ae5cfc550fd047328825ae27f1aa

**Comment by CelticMinstrel** [comment]
We should be more careful of spelling in the changelog - in this case, "giant" only has one G. Also, is it "scorpling" or "scorpionling"? I just fixed the "giant" typo but I'm not sure which name is correct for the small scorpion.

**Comment by Hejnewar** [comment]
Thanks. Small scorpion in game is called "Scorpling".

**Comment by CelticMinstrel** [comment]
Can I ask someone else to correct that incorrect changelog entry, then? Just change Scorpionling to Scorpling.

If not, I'll probably get to it "eventually", but…

**Comment by Pentarctagon** [comment]
Corrected in 444c0a418241b96618ac4a053fa3f60b9dd44d9a

**Pull request merged**
