### PR TITLE
about asymetric projectiles ... (refactoring)

### PR DESCRIPTION
**Pull request by sevu**
Instead of having the south set of images for the wail animation being upside-down
and letting the engine flip them the image files themselves are now the same like shown ingame.

I think it's simpler if you can see the differences to the other files in the filemanager.

Inspired by this thread https://r.wesnoth.org/t45562.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I wonder what effect this would have on addons using those images, though...

**Comment by sevu** [comment]
I think add-ons use the macro from core too, because it's existence is hard to miss.
However, the may be used as icon in the add-on manager. Can we grep the add-ons list? (I wonder where it is stored at runtime)

**Comment by CelticMinstrel** [comment]
Zookeeper seems to be the person to ask if you want to grep the addons server for something.

**Comment by ln-zookeeper** [comment]
Honestly, I find it pretty hard to see the point in this. Sure, if I was making the images from scratch now, I'd probably rather make them oriented this way, but the animations have been written and the images used for 10 years without problems and are currently used by 8 or so add-ons. Even a slight inconvenience to a number of people doesn't seem worth the arguably marginal improvement in clarity.

**Comment by Vultraz** [comment]
The animations or the images have been used?

**Comment by sevu** [comment]
There's not really a point in it, it's a mere refactoring to let it look simpler.
Unlike the similar case with the fire-breath images I don't see a reason why one would use them without macros, so I think this is safe.
However, if you really don't like this you can close this.

**Comment by ln-zookeeper** [comment]
Yes, there were several cases of the images being used directly, but after I more closely peeked at the context they're used in, it doesn't look like the flip really does any noticeable harm in most of those cases (they're used as small icons, etc). There's one add-on where it does make a difference, but I'll just drop a PM to the author so they can fix it if they feel like it.

**Comment by sevu** [comment]
Ok, I see.

**Pull request merged**
