### PR TITLE
SotA S16: Keep Crelanu within his ring of protective holy waters

### LINKED ISSUE #8361: [mainline] (SotA) AI doesn't understand protective circle
### Game and System Information

- **Version: 1.16.11**
- **Downloaded from: Steam**
- **Build info: not custom**
- **OS: Windows 10 I think?**

### Description of the bug

I have been playing SotA on challenging mode in 1.16.11.

In S16 (The Mage), Crelanu is potected by a circle of holy water and 2 white mages. This is a really cool mechanic, but when a unit enters Crealnu's movement range, he will leave his keep to attack, thereby leaving behind his defences. The scenario ends when you kill Crelanu, so I didn't even interact with the holy water, sadly. I would recommend tweaking the ai so that the leader will not move from his keep and only attack enemy units standing right next to him.

PS: I love the game, thanks so much to the wonderful devs to make this possible! <3

### Steps to reproduce the behavior

1. send some dark sorcerers up front to lure out crelanu, unlike your undead units they will likely survive his attack.
2. Move in for the kill with melee units
3. By killing Crelanu, the scenario is won before you even interact with the holy water 😢

### Expected behavior

In the savefile, simply end the turn and Crelanu come out.

[Bugsave8.gz](https://github.com/wesnoth/wesnoth/files/14184575/Bugsave8.gz)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Wedge009**
I play-tested this in master and couldn't get Crelanu to leave his ring, even with as tempting a target such as a weak Ardonna.

Resolves #8361.

### CODE REVIEW

**Review by nemaara — APPROVED** [review]

**Comment by cooljeanius** [comment]
Hm, not sure if this is necessarily the best way to go about it... since @OrangePumpking reported #8361, maybe they could give their opinion?

**Comment by Wedge009** [comment]
What other way do you suggest? As I understand it, the issue is Crelanu doesn't make use of the holy waters that are scripted to appear around him if there are any undead recalled/recruited.

I notice artificially reducing MP to 0 can have poor side effects as remarked upon in other issues.

From my perspective, in terms of story, it makes sense to keep Crelanu passive as he is the defender here.

**Comment by soliton-** [comment]
As far as I can tell this implements pretty exactly what the issue suggests to do...

**Comment by stevecotton** [comment]
Looks good - maybe the AI should revert to normal after some of the water has been removed, but OTOH I'm assuming the scenario won't last much longer at that point anyway.

**Pull request merged**
