### PR TITLE
Resolve #6019 - allied side not triggering failure condition when sighted

### LINKED ISSUE #6019: [Liberty][S06: The Hunters] target of "sighted" event incorrect
### Game and System Information
 - What version of the game are you running?
 1.15+dev (47c19ceff6f-Modified)

### Describe the bug
On Liberty scenario 06 (The Hunters), nothing happens when Helicrom side (side=2) unit is sighted by outpost guards (side=4).
 
### To Reproduce

1. Start scenario 6 (The Hunters) of Liberty
2. End turn of Baldras side and enter turn of Helicrom side
3. move Helicrom unit to the outpost and get sighted by guard unit
4. Nothing happens
(Outpost is located in upper left in the map; needs some turns to be sighted without debug mode)

### Expected behavior
Player should be defeated according to the lose condition `Any allied unit is sighted by the outpost guards`.

### Additional context
side=1 in this event should be modified to side=1,2 (scenarios/06_The_Hunters.cfg)?
```
    [event]
        name=sighted
        [filter]
            side=1
        [/filter]
        [filter_second]
            side=4
        [/filter_second]
    ....
```

### PR DESCRIPTION
**Pull request by Wedge009**
Issue #6019

Can be back-ported to 1.16 assuming corrections are still allowed at this time.

### CODE REVIEW

**Comment by nemaara** [comment]
I don't know if this violates feature freeze and such. @Pentarctagon can you let us know if it does?

**Comment by Pentarctagon** [comment]
It's fixing a bug, so it's fine.

**Comment by nemaara** [comment]
Alright, I don't have git on this comp so I can merge later and cherry-pick, or if anyone else can do it now that's fine too.

**Comment by Wedge009** [comment]
Merging since change was merged to 1.16 already.

**Pull request merged**
