### PR TITLE
Nerf Elvish Shyde/Enchantress/Sylph/Sharpshooter/Avenger in 1.19

### PR DESCRIPTION
**Pull request by ForestDragon-wesnoth**
Seeing the very positive reaction from the community to my suggestions in issue #8741 I decided to move forward with this issue and open a PR with my changes implemented.

### CODE REVIEW

**Comment by Dalas121** [comment]
Beautiful, thanks for the PR!

If you don't mind a suggestion, I feel that a 13x5 Sylph is still very strong in comparison to the other L4 mages. The Sylph's 13x5 matches both the Ancient Lich and Great Mage, while having superior movement and defense to both (especially compared to the Great mage0. Was 1.16's 10x5 underpowered?

**Comment by ForestDragon-wesnoth** [comment]
> Beautiful, thanks for the PR!
> 
> If you don't mind a suggestion, I feel that a 13x5 Sylph is still very strong in comparison to the other L4 mages. The Sylph's 13x5 matches both the Ancient Lich and Great Mage, while having superior movement and defense to both (especially compared to the Great mage). Was 1.16's 10x5 underpowered?

While I do agree with you that my PR is likely not sufficient, I believe a smaller change that gets accepted is still better than a more significant nerf that gets rejected and sylph keeps 16-5

**Comment by DuncanusDillius** [comment]
=
[Elves.zip](https://github.com/wesnoth/wesnoth/files/14967802/Elves.zip)
For those that can't wait, I have made some nerfed elves :D I really hope that the mainline ones get nerfed soon too, because they are way too op

**Comment by Pentarctagon** [comment]
The question I'd have would be whether this would end up creating even more work to adjust for UMC to adjust them for 1.18 then readjust again for the nerfed values in 1.19.

**Comment by CoxAsh** [comment]
I personally dislike these changes, current ones gave me and my friend a lot of fun while playing as well as epic moments, with this it will no longer happen and frankly it will be no longer worth it to try so hard to get one.

**Comment by AnekronCZ** [comment]
> The question I'd have would be whether this would end up creating even more work to adjust for UMC to adjust them for 1.18 then readjust again for the nerfed values in 1.19.

As UMC dev, I'd likely just directly override the changes for 1.18 and then delete the compatibility code once 1.19/1.20 arrives. Much less work that way.

I've considered making it so with the Orcish Crossbowman who now requires 50% less XP to level, becoming much stronger in my campaign. In the end I was able to work around the change, but I feel that might be far harder with elves since the buffs are all across the board.

I think an add-on with 1.19 unit states could be set up so any campaign can require it as a dependency while running under 1.18. Would very much like to see what elvish UMC devs think about these changes and which solution would they prefer.

**Comment by ForestDragon-wesnoth** [comment]
> > The question I'd have would be whether this would end up creating even more work to adjust for UMC to adjust them for 1.18 then readjust again for the nerfed values in 1.19.
> 
> As UMC dev, I'd likely just directly override the changes for 1.18 and then delete the compatibility code once 1.19/1.20 arrives. Much less work that way.

Good point. If UMC devs can no longer trust the game stats to not wildly change every other update, we are forced to rely exclusively on custom units or edited copies of mainline units, bloating the add-ons further.

**Comment by MechanicalDragon963** [comment]
I support this PR. On the one hand, it aims to fulfill the stated goal of making elves more "elite", on the other hand, it removes the kinks and makes the power of elves more fair to other high level units. 

As for epic moments - I think that's not an argument. I might as well say that after getting a few new sylves and shydes, my gameplay disappeared and all scenarios became playable the same way: an army of super-powerful elves just kills any enemies with one attack. It's not interesting.

**Comment by Dalas121** [comment]
> I personally dislike these changes, current ones gave me and my friend a lot of fun while playing as well as epic moments, with this it will no longer happen and frankly it will be no longer worth it to try so hard to get one.

Since nobody has given the reasoning for this PR, I wanted to elaborate.  Epic moments are really cool, and we do want to encourage them in Wesnoth!  The concern here is that some high-level elves have stats that are inordinately powerful compared to other races' equivalents, without a meaningful downside.

Most of the community feels that a unit's level should be representative of it's power, and that races should be more-or-less balanced between each-other.  The Elvish Sylph, for example, currently deals 80 magical damage, while also having a slow attack, flight, and good defense on all terrains.  The human Great Mage, on the other hand, does 64 damage, has no slow, cannot fly, and only has normal terrain defense.

Lore-wise, this seems to indicate that humans are really lousy at magic, which I don't feel is the direction we want to go in.  Balance-wise, this means that in existing campaigns that give you access to both human and elven magi, the elven magi are always better to level.  In campaigns with elven magi and other elven units (fighters, for example), the magi are also always better to level.

Additionally, changes of any sort always have a tendency to break UMC (meaning mods, add-ons, etc), and require additional rebalancing from the users who maintain those add-ons.  In this case, some of those users feel they weren't adequately consulted/made aware of these particular balance changes.

Hope that helped explain why there's been such drama about this issue!

**Comment by Dalas121** [comment]
Are there plans to move forward with this PR, and/or a 3 person balance team?

**Comment by Pentarctagon** [comment]
> Are there plans to move forward with this PR

It's a bit difficult for Hejnewar to click the Approve or Reject button until his github account is reinstated. Once he gets access back though I assume it will go forward since he previously said he's fine with it if @nemaara approves and Yumi sounded open to changes. However given this would only go into 1.19 there isn't really any urgency that I know of to get this in, and given how https://github.com/wesnoth/wesnoth/issues/8740 and https://github.com/wesnoth/wesnoth/issues/8741 have gone I do want explicit approvals to be provided.

> and/or a 3 person balance team?

While that was the idea brought up in #8740, that was not what was actually proposed to me, so that's unlikely at least at this point.

**Comment by nemaara** [comment]
Is it really bad if you keep the high exp for ench and also nerf the stats for both her and sylph? How much exp should it cost to upgrade lich to ancient lich?

**Comment by ForestDragon-wesnoth** [comment]
> Is it really bad if you keep the high exp for ench and also nerf the stats for both her and sylph? 
Considering how in 1.18 archmage xp has been changed from 220 to 150, enchantress having 180 again is still above archmage. In the PR they are closer in power now, so I think it's fair making them a bit closer in xp again as well.

**Comment by nemaara** [comment]
How do we feel the nerfed sylph compares to ancient lich?

**Comment by ForestDragon-wesnoth** [comment]
> How do we feel the nerfed sylph compares to ancient lich?

well, identical base damage on the main attack (13-5 on both), plus even with my nerfs it I would say it is still better than 1.16 sylph (roughly identical damage vs undead due to arcane rebalance, better damage vs everything else)

Plus unlike ancient lich, sylph has slow, can fly, and is available more often while ancient lich is usually advancement-locked

**Review by nemaara — APPROVED** [review]

**Comment by ForestDragon-wesnoth** [comment]
Thanks for approving the PR!

**Comment by cooljeanius** [comment]
> > > The question I'd have would be whether this would end up creating even more work to adjust for UMC to adjust them for 1.18 then readjust again for the nerfed values in 1.19.
> > 
> > 
> > As UMC dev, I'd likely just directly override the changes for 1.18 and then delete the compatibility code once 1.19/1.20 arrives. Much less work that way.
> 
> Good point. If UMC devs can no longer trust the unit stats to not wildly change from the original wesnoth gameplay every other update, we are forced to rely exclusively on custom units or edited copies/overwrites of mainline units, bloating the add-ons further.

(This is kinda why I haven't ported any of my add-ons to 1.18 yet, btw, well, that, plus just generally being occupied with other stuff...)

**Comment by Pentarctagon** [comment]
I mean, the stats won't be changing in 1.18.

**Comment by ForestDragon-wesnoth** [comment]
> I mean, the stats won't be changing in 1.18.

yep, the PR is for the 1.19 development branch

**Comment by Jonathan-Kelly** [comment]
> well, identical base damage on the main attack (13-5 on both), plus even with my nerfs it I would say it is still better than 1.16 sylph (roughly identical damage vs undead due to arcane rebalance, better damage vs everything else) Plus unlike ancient lich, sylph has slow, can fly, and is available more often while ancient lich is usually advancement-locked

@ForestDragon-wesnoth would you be for or against the advancement-lock on the ancient lich being removed at this point?

**Comment by ForestDragon-wesnoth** [comment]
> @ForestDragon-wesnoth would you be for or against the advancement-lock on the ancient lich being removed at this point?

I think it's best to get opinions from the wider community on a question like this.

Either way, this PR is merged and closed, I think such a major balance decision should be discussed somewhere other than a finished elf-focused PR.

**Pull request merged**
