### PR TITLE
Refresh po4a workflow

### PR DESCRIPTION
**Pull request by loonycyborg**
currently this fixes error with newest po4a but still po4a complains about po4a-gettextize/po4a-translate being deprecated. Could also go unified po4a approach but it seems less buildsystem-friendly.

### CODE REVIEW

**Comment by Pentarctagon** [comment]
I don't know anything about po4a, so I don't think I can review this.

**Comment by loonycyborg** [comment]
You run pot-update so at least you need to test it.

**Comment by stevecotton** [comment]
Looks good to me. I suggest we merge this (once @Pentarctagon's confirmed that it works on his system), and I'll change the other one to be CMake-only.

**Comment by Pentarctagon** [comment]
I did notice the warnings:
```
src/tests/gui/test_gui2.cpp:736: warning: a double-quote in the delimiter of a raw string literal is unsupported
src/tests/gui/test_gui2.cpp:736: warning: unterminated string literal
src/tests/gui/test_gui2.cpp:738: warning: unterminated string literal
src/ai/composite/component.cpp:137: warning: a double-quote in the delimiter of a raw string literal is unsupported
src/server/campaignd/server.cpp:104: warning: a double-quote in the delimiter of a raw string literal is unsupported
src/server/campaignd/server.cpp:104: warning: unterminated string literal
src/server/campaignd/server.cpp:120: warning: unterminated string literal
src/editor/map/map_context.cpp:159: warning: a double-quote in the delimiter of a raw string literal is unsupported
src/editor/map/map_context.cpp:175: warning: a double-quote in the delimiter of a raw string literal is unsupported
src/editor/map/map_context.cpp:181: warning: a double-quote in the delimiter of a raw string literal is unsupported
src/editor/map/map_context.cpp:645: warning: a double-quote in the delimiter of a raw string literal is unsupported
```
but it looks like those are already existing. So it looks fine to me.

**Review by Pentarctagon — APPROVED** [review]

**Pull request merged**
