### PR TITLE
[WIP] some dunefolk sprite updates

### PR DESCRIPTION
**Pull request by doofus-01**
So far includes soldier group, mostly.  Existing spearmen looked OK, this touches the swordsmen more. 
EDIT:  Adding a checklist.  I don't know if it's best to pack all sprites in here, I might commit this before the list is complete, if there are no objections.

- [x] Soldier - Swordsman branch
- [x] Soldier - Leader branch
- Soldier - Spearman branch needs no edits
- [x] Skirmisher line
- [ ] Healer line
- [x] Burner line
- [ ] Naga - melee branch
- [ ] Naga - ranged branch
- [ ] Horseman - Archer branch
- [x] Horseman - Sunderer branch
- [ ] Horseman - Raider branch
- Rover line needs no edits

### CODE REVIEW

**Comment by Hejnewar** [comment]
Great work but:
Soldier level ups somehow look fat - probably just me.
And horse biology. 
Front legs of this horse look like elephant legs.
Horses always keep their head high if they are not eating, having lowered head makes most horses look like donkeys. (Donkeys want to stay hidden thus lowered head, horses want to stay aware that is why their head is always as high as possible.)
Last thing is this weird leash. It is very unpleasant for horse, not to mention it can suffocate this poor animal, but I doubt anyone could ride horse using that leash tho... 
Once again great work over all, it just pains me to see a horse like this.

**Comment by doofus-01** [comment]
The last commit is to make the new nagas not have the same pose and general shape as the existing nagas (fighter,etc. in northerners).  It possibly doesn't make sense for the first level, but it will be useful for later levels.

> And horse biology. 
[...]

No, I'm not buying that.  I've never met an elephant, but I have encountered a horse before.  I was trying to make the horse not a cut&paste of the loyalists, but the forehead band should have gone as well.

**Comment by Hejnewar** [comment]
Yeah you are right, in game legs look good, but when comparing here on website they look like two massive pillars. My bad.

**Comment by doofus-01** [comment]
> Yeah you are right, in game legs look good, but when comparing here on website they look like two massive pillars. My bad.

No problem, it's often hard to judge things here or on the forums.  It's even more of an issue with animations and demo GIFs.

----------
In the last commit, I tried to take the criticisms of the forum into account[*], and I went with a certain naga design.  I'll base further nagas on this, so let me know if there is some problem.

[*]https://forums.wesnoth.org/viewtopic.php?f=9&p=649140

**Comment by Hejnewar** [comment]
Naga looks really good. 

Im still not sure about reins in rider sprite but if others are fine with them I have nothing more to say.

**Comment by doofus-01** [comment]
I'm going to commit this now because I rearranged the sprite paths, basically gave sub-directories so it would still be readable after animation frames are added.  There can be more conflicts if this lingers.

**Pull request merged**
