### PR TITLE
resolve problem of negative value for leadership

### PR DESCRIPTION
**Pull request by newfrenchy83**
this is the fix what i propose for the https://github.com/wesnoth/wesnoth/issues/3770 issue.

### CODE REVIEW

**Comment by newfrenchy83** [comment]
@jostephd it's done.

**Comment by newfrenchy83** [comment]
@jostephd put call under_leadership() in aspect_attack.cpp

**Comment by gfgtdf** [comment]
> @gfgtdf @CelticMinstrel any comments?


hmm not sure I mean, an alternative to this would probably be to make the leadership special use get_composite_value() (so that negative leadership could be implented with sub=. The mul/div features are probably not of much use here but behaving the same as other abilities would probably make it easier to understand for wml developers.

**Comment by newfrenchy83** [comment]
i'm not my opinion, leadership add or sub damages with value=  , use add and sub then what base value ever null is not a good idea, and i don't want complicate work of wml develloper.

**Comment by jostephd** [comment]
@gfgtdf Does the PR as it stand now conflict with switching to get_composite_value in the future? That is, suppose we merge this PR tomorrow, could we then switch to get_composite_value on Monday or would that break compatibility?

**Comment by newfrenchy83** [comment]
If we go to get_composite_value then we will need to validate the optional PR rule changes https://github.com/wesnoth/wesnoth/pull/3765 so that the problem of negative values remains solved for leadership and extend to heals but also abilities like weapon (drains among others) but without alterate illuminates or break get_composite value of heals.

**Comment by jostephd** [comment]
> Not really, at least not in the sense that merging this pr and switching later would create more work for umc developers than if we didn't merge this.

So we can merge this as it stands, can't we? If someone wants to support `add` and `sub` in leadership, that'll be great, but the PR as it stands is an improvement too.

**Comment by newfrenchy83** [comment]
@jostephd yes you can.

**Comment by jostephd** [comment]
Okay, merged. @newfrenchy83 I hadn't forgotten about this PR; I was just waiting a few days to see if anybody had further comments.

What's the next step? I think you had a patch about negative healing you wanted to submit? If so, please open a new PR for that (make sure the PR doesn't contain unrelated changes, as I explained previously) - but before that, if you can write a quick test for negative leadership, that'd be much appreciated. (I mean test in `run_wml_tests` or in `boost_unit_tests`, not in `scenario-test.cfg`.)

**Comment by newfrenchy83** [comment]
@jostephd for me the next step is https://github.com/wesnoth/wesnoth/pull/3788 because if a doing a specific fix for heals, i break add and sub tags used by some addons develloper, but anyone use these tags for illuminates, this why i replace get_composite_value by highest("value"), and use @gfgtdf code in effect constructor.

**Comment by jostephd** [comment]
Sorry, I don't understand what you said. If you'd like to continue with #3788, please clean up the diff of that PR so it has no unrelated changes: remove the leadership changes that were merged as part of this PR, remove anything else that's not relevant _to that specific PR_, and explain exactly what the problem being fixed is, with WML to reproduce the problem, as I have explained before. It is important that you do these things to make it easy for us to understand, review, and merge your changes.

**Pull request merged**
