### PR TITLE
Game Load: Show the user-name difficulty name instead of the internal name

### PR DESCRIPTION
**Pull request by jostephd**
This PR changes "Difficulty: Medium" to "Difficulty: Hero (Normal)" in the game load screen.

before after

### CODE REVIEW

**Comment by jostephd** [comment]
Not to mention that in TSG, the classification "easy" exists in both difficulty schemas:

EASY / Civilian (Beginner)
MEDIUM / Recruit (Easy)
HARD / Soldier (Normal)

So if a new player starts TSG on difficulty "Recruit (Easy)", they're going to see "Medium" in the Load Game screen.

**Comment by Wedge009** [comment]
I think the idea was to show that The South Guard was meant to be an easier-than-normal campaign aimed for beginners but the point stands.

(#3440 rates it the second easiest official campaign)

**Comment by jostephd** [comment]
Yes, I don't think the difficulties of TSG should be changed. I meant that it's confusing for "Easy" to mean one thing in the "Start a Campaign" screen and another thing in the Game Load screen.

**Comment by Wedge009** [comment]
I was agreeing with you. (:

**Comment by jyrkive** [comment]
Thanks for the pull request! :)

**Pull request merged**
