### PR TITLE
remove CI check of copyrights.csv for images

### PR DESCRIPTION
**Pull request by doofus-01**

### CODE REVIEW

**Comment by doofus-01** [comment]
I should get a second opinion before committing this.  I'd like to start updating the images today, so I have a chance to fix anything that needs fixing.

**Comment by stevecotton** [comment]
Shouldn't #9028 be resolved before adding data to images? One of the effects of adding data is that the checksums will change, thus the script in #9028 will stop working.

**Comment by doofus-01** [comment]
You can still compare the hash, just batch strip the exif data and either don't overwrite the originals or don't commit the stripped.  That's an extra step I guess, but it's pretty tiny considering the need to do research on each individual image file.

Generating the original CSV must have been a royal PITA.  We can continue to fix things as we find them.

**Comment by Pentarctagon** [comment]
Creating the original csv was basically just me looking through git history and forum posts, and either:
* I found something explicitly saying who created the image
* I didn't find anything but tried to make a reasonable guess
* I had no idea at all
So yeah, it should mostly be taken as a best attempt rather than anything definitive, especially for older content.

**Comment by stevecotton** [comment]
Instead of disabling the check entirely, would it be sufficient to change it so that files with embedded info are automatically accepted?

In other words, adding or changing a file with embedded info wouldn't need a change to the CSV file; but the check would still complain about adding a file without metadata.

**Comment by doofus-01** [comment]
There is a check for adding a file without metadata: https://github.com/wesnoth/wesnoth/blob/master/.github/workflows/image_metadata.yml

**Comment by stevecotton** [comment]
Ah, sorry. I have no objection to this PR then.

**Comment by doofus-01** [comment]
Thanks.  If there should be a duplicate hash check, that can certainly be added, but I'd prefer to address that later.  Changes would show up in an image file's commit history, but I don't think it's "pollution".

I'll merge this in a bit.

**Comment by doofus-01** [comment]
_Now_ I think it's ready to go.  I will merge this tomorrow if there are no objections.  Then I will update the images.

**Pull request merged**
