### PR TITLE
Liberty fixes

### PR DESCRIPTION
**Pull request by GregoryLundberg**
Same changes as PR #687 but consolidated.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
You can add `--force` to your git command line to avoid having to open a new pull request. (If the branch name is different, you would have to specify which branch to push to which branch, which is something like `git push <remote> <local branch name>:<remote branch name>` where the <> parts should be replaced by reasonable values. (And of course add `--force`.)

That aside, this is quite a bit more squashed than I had been expecting, but looking at the combined commit messages, it's probably fine.

**Comment by GregoryLundberg** [comment]
Actually, I'm liking --force-with-lease since it seems to avoid having GitHub lose track of the conversations and comments and my primary interaction with y'all is through those. I suppose I should get an account in the bug tracking system but .. sheesh .. so many web sites, so many accounts .. I tend to avoid making any more unless I absolutely must. IRC .. I need a better client but I like the temporal separation of email and comments, here. It's hard to talk when only one side is present, awake, and at the keyboard on IRC so I am not a real fan of IRC except for things like last night checking that it was your ISP's nameserver and not mine which was causing the problems. And, even then, I could have determined that myself so I was just being lazy.

Yeah, I probably should have let each bug fix stand alone and done 'remove artifacts' and 'clean up macros' as separate items. In my work-flow, I'm doing them in batches like that anyway .. clean up the macros, walk the scenarios finding artifacts, code-read for [if] and dead code, then check each [message] for edge conditions.

I'm giving Liberty a quick run-through on HARD and checking my work one last time. Added a todo for myself .. clean up core/ai_controller for all that deprecated stuff.

I'm really trying to get the campaigns I look at (hopefully, all of them, eventually) to run with no messages on-screen, or on stderr, and no obvious bugs like important lines going missing. The only messages on stderr I ignore are those having to do with the normal 'BfW's UI is a mess and I'm not going there.' messages.

**Comment by CelticMinstrel** [comment]
Github conversations and comments are linked to the pull request, which is linked to the branch you made the PR from. So, anything that goes to that branch while the PR is open ends up in the same PR, without affecting the conversation. (Even if you force-push, conversation from the overwritten commits is usually retained, though collapsed as applying to an obsolete diff.) That said, from what I can tell, `--force-with-lease` is essentially a safer version of `--force`, so if you prefer that, go for it. (I'd never even heard of it before now.)

**Comment by ln-zookeeper** [comment]
This is ready to merge, right?

I don't really see the point in changing [if] [else] to [if] [not][/not] [then], but naturally it doesn't hurt so no need to change it back either.

**Comment by GregoryLundberg** [comment]
The point of changing it was I followed that code style for some changes and got called out for it. So, when I see it, I change it, on the presumption that consistency is a desirable thing.

As to ready-to-merge, I have no pending work for it.

**Pull request merged**
