### PR TITLE
Moves a nice, but unused macro from anl to deprecated

### PR DESCRIPTION
**Pull request by sevu**
Nice macro, but it's not used in ANL.
Moving to deprecated for now, since ANL has lot's of macros and is maybe not the best place for dead code.

I guess it could be useful to content creator if it were in core. How about that?
And in case we do, is it possible to change the textdomain during string freeze with the pot fix scrip?

### CODE REVIEW

**Comment by gfgtdf** [comment]
The whole scenario should be converted to lua at some point, thi would in particular speedup its wml loading time that we no longer need to put it into a `scenario_define` whihc means that players would no longer to wait for an additional loading screen (which can take quite long if you have some othe addons installed) when starting that sceanrio.

**Comment by Vultraz** [comment]
If this is unused, it can just be removed outright. It's not a core macro. Though if you want to promote it to core, that's also a possibility.

**Comment by CelticMinstrel** [comment]
While the general idea of this macro would be nice for core, it's too specific to be added as-is to core. I'd say, just delete it outright; if you want to add a core version as a separate PR on master, probably in image-utils or similar, then that might be acceptable. It would need more arguments – for example the message and the image could be made into arguments.

**Comment by Vultraz** [comment]
Manually removed.

**Pull request closed without merging**
