### PR TITLE
Updates the Title field of a few tracks.

### PR DESCRIPTION
**Pull request by Pentarctagon**
defeat2: Defeat -> Defeat 2
elvish-theme: Elvish theme -> Elvish Theme
frantic-old: Frantic -> Frantic Old
silence: silence.ogg -> Silence
victory2: Victory -> Victory 2

---

This is pretty straight forward, but I don't know if there are any other considerations when making changes to music.  The titles were edited and saved through VLC.

### CODE REVIEW

**Comment by ln-zookeeper** [comment]
The other consideration when making (unnecessary) changes to large binary files is repository size. In other words, is a trivial capitalization change like "Elvish theme -> Elvish Theme" worth permanently increasing the size of the repository by 2,80mb?

**Comment by CelticMinstrel** [comment]
To be honest? I don't think I like this. Defeat 2, Frantic Old, Victory 2... those don't sound like an actual track title. Rather, we have a strange situation where there are multiple tracks with the same title. If you don't like this, then instead of applying a suffix, shouldn't we come up with an entirely new name?

By the way, I notice that frantic-old exists because for some reason the track was replaced but the old one was just kept around... what was the reason for this?

And silence.ogg isn't really a track, so it doesn't even _need_ a title.

The only thing I could maybe support here is the Elvish Theme change, though I guess I sorta see zookeeper's point on that.

**Comment by Pentarctagon** [comment]
I don't disagree that adding a "2" on the end isn't great, but it makes more sense to me than the current situation where two different tracks have the exact same title.

frantic-old.ogg doesn't seem to be used anywhere in mainline anymore, so it could just be removed, at least from master, I'd guess(though I don't know why it was kept around either).

Also, honestly, this is less useful than I originally thought anyway, since the title metadata is only actually retrieved from the track on Linux whereas it has to be manually set for Windows and MacOS.

**Comment by Pentarctagon** [comment]
Well, my use case was to list out all the core music tracks (and all 14 of my UMC Music add-ons) via lua and then display them by their title rather than fire name without needing to manually create a mapping of file name <-> title, so having duplicate titles wouldn't have worked for my case.  Since that would only work for Linux though, apparently, I'm going to have to manually make the mappings anyway in order for it to be cross platform, in which case this PR is rather pointless.

**Pull request closed without merging**
