### PR TITLE
wmlunits: Specify error as class in html reports

### PR DESCRIPTION
**Pull request by Slayer95**
Suggested by @CelticMinstrel

### CODE REVIEW

**Comment by ProditorMagnus** [comment]
What is the benefit of this change?

**Comment by Slayer95** [comment]
> What is the benefit of this change?

It preserves semantics of the exception. There are a variety of sources (MDN [1](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/class), SO [2](https://stackoverflow.com/questions/56713447/when-is-it-necessary-to-add-class-for-semantics), [3](https://stackoverflow.com/questions/32209520/in-semantic-html-does-the-class-attribute-mean-anything-in-the-absence-of-css-or)) that explain how semantic classes are useful.

**Comment by Elvish-Hunter** [comment]
The string interpolation is used incorrectly here and this is the output I got in an IDLE shell:
```python
>>> line="<INTERNAL ERROR>"
>>> print('<p class="error %s">', line[1:-1].replace(" ", "-").lower())
<p class="error %s"> internal-error
```
Besides fixing it, I suggest using either the `.format()` method or f-strings.

**Comment by Slayer95** [comment]
> The string interpolation is used incorrectly here and this is the output I got in an IDLE shell:

Damn. That proves there's no patch small enough that cannot have bugs.

> f-strings

Does ``wmlunits`` run with Python 3.6? I added the missing ``%`` to stay safe.

**Comment by CelticMinstrel** [comment]
I don't know about f-strings, but .format() should be safe regardless, right? I'm pretty sure that was already in Python 2.

**Comment by Elvish-Hunter** [comment]
> Does `wmlunits` run with Python 3.6? I added the missing `%` to stay safe.

It does. The VM which runs wmlunits has Python 3.9 installed, but if you want to stay safe the `format()` method has been available since 2.6.

**Comment by Slayer95** [comment]
I mean, #7580 was just merged and it introduces a bunch of ``%`` operators, so it doesn't make much sense to use a different approach here imo.

**Comment by Slayer95** [comment]
Yeah, right.

**Pull request merged**
