### PR TITLE
Fix the Elvish Outrider description

### PR DESCRIPTION
**Pull request by catagent101**
There are at least three units that do a better job, all of them in the Dunefolk faction, and one possible unit in the form of Pelias from THoT (unless he has a side job as a bowman).

### CODE REVIEW

**Comment by GregoryLundberg** [comment]
Seems a bit clunky.

**Comment by Vultraz** [comment]
Suggest:
>  Only the most dedicated exceed their skill as mounted archers — in fact, most would be hard pressed to equal it standing on solid ground.

**Comment by GregoryLundberg** [comment]
Do you know how to merge the commits in your feature branch to keep our master's history cleaner? We can squash when it's ready, but it's easier if you do it on your branch.

**Comment by jostephd** [comment]
@Vultraz I agree with adding "most", but now "Only the most dedicated" sounds like it refers to the outriders, not to other mounted archers. How about changing "their" to, say, "these elves'"?

**Comment by Vultraz** [comment]
Seconded.

**Comment by Vultraz** [comment]
Committed manually since a release is imminent. Thanks for pointing this out. :)

**Comment by catagent101** [comment]
Thanks

**Pull request closed without merging**
