### PR TITLE
Change layering of stone bridges

### PR DESCRIPTION
**Pull request by doofus-01**
This is to deal with #1274 
The results aren't perfect, but I don't see how to make it perfect without drawing new images.
I didn't see anything broken by changing the layer from -80, but it must have been -80 for a reason, so certainly test this before merging.
screenshot_009

### CODE REVIEW

**Comment by Vultraz** [comment]
Would be nice if they sat under the castle but over the chasm transitions like with the other castles. But I don't know if that's possible. I've tried many times to get the dwarven castle-to-chasm transitions drawing over the bridges but I could never do it :(

**Comment by doofus-01** [comment]
The chasm wall and the castle are one image, dwarf castle is special.

**Comment by Vultraz** [comment]
....Ohhhhh.....

**Comment by Vultraz** [comment]
I think the status quo is better than having the bridge on top of the dwarven castle.

**Pull request closed without merging**
