### PR TITLE
Move assert into filesystem::get_user_data_path()

### PR DESCRIPTION
**Pull request by Pentarctagon**
As discussed previously in https://github.com/wesnoth/wesnoth/pull/9016#discussion_r1650036348

### CODE REVIEW

**Comment by soliton-** [comment]
Would be good if wesnothd would not create the userdata dirs at all and the unit tests only if that is part of a test (and then not in the default locations). That can be done later though.

**Review by soliton- — APPROVED** [review]

**Comment by Pentarctagon** [comment]
I think I might've asked this before, but is there a reason wesnothd needs the preprocessor?

**Comment by soliton-** [comment]
On wesnoth.org there is a file for common configuration for all servers that is included everywhere and there is redirection config conditionally included based on what files exist.

**Comment by Pentarctagon** [comment]
So the solution would be one of:
* Remove the preprocessor's dependency on the userdata folder existing
* Add a way to have this common server config loaded that doesn't involve macros
?

**Comment by soliton-** [comment]
Macros are not used just file inclusion and `#ifhave`.

The first would be preferable since the second just sounds like duplicating the preprocessor.

**Comment by Pentarctagon** [comment]
Would you be able to post the file contents here? I'm having a hard time visualizing what this file looks like.

**Comment by soliton-** [comment]
The trunk config for example:
```
{./common.cfg}
id=trunk
versions_accepted="1.17*dev,1.19*dev,test*"
information="Code of Conduct: https://coc.wesnoth.org
Wesnoth's official Discord server: https://discord.gg/battleforwesnoth"
motd="Welcome to the official trunk multiplayer server! (https://changelog.wesnoth.org).
If you're certain you found a new bug please report it at bugs.wesnoth.org as detailed as possible.
Code of conduct for this server: https://coc.wesnoth.org
Enjoy your stay!"
#ifhave ./oldstable-redirect.cfg
{./oldstable-redirect.cfg}
#endif
#ifhave ./stable-redirect.cfg
{./stable-redirect.cfg}
#endif
#ifhave ./dev-redirect.cfg
{./dev-redirect.cfg}
#endif
#ifhave ./1.14-redirect.cfg
{./1.14-redirect.cfg}
#endif
```

**Pull request merged**
