### PR TITLE
Conditional jump or move depends on uninitialised value

### PR DESCRIPTION
**Pull request by bckpkol**
in init_mouse_location. I've found that using Valgrind.

### CODE REVIEW

**Comment by Vultraz** [comment]
Does just `SDL_Event event {}` fix it (no assignment)?

**Comment by bckpkol** [comment]
I really don't know. I'm beginner in C++. I don't even know if it is correct to pass null event. But uninitialized event isn't correct by its definition.

**Comment by bckpkol** [comment]
Options are --leak-check=full

**Comment by jyrkive** [comment]
@Vultraz It indeed fixes it. I committed the fix in commit c064de21ce7a36c62c54b5388cf85029767f5acc.

**Pull request closed without merging**
