### PR TITLE
Lua: Make sure unit type is built before returning it from iteration

### LINKED ISSUE #8456: [lua] unit_type.level seems broken
### Game and System Information

The Battle for Wesnoth version 1.17.25+dev (60ae0db6-Clean) x86_64
Running on Freedesktop SDK 23.08 (Flatpak runtime) x86_64
Distribution channel: Default
Linux

### Description of the bug

Using the following lua code

```lua
for id, ut in pairs(wesnoth.unit_types) do
     wesnoth.log("error", string.format("%s %d %d", id, ut.level, ut.__cfg.level))
end
```
shows that ut.level accessor is broken, whereas using the plain __cfg config works.

### Steps to reproduce the behavior

_No response_

### Expected behavior

_No response_

### Additional context

Here is a sample of what I got on the console 

20240225 16:21:06 error wml: Merman Brawler 0 1
20240225 16:21:06 error wml: Merman Citizen 0 0
20240225 16:21:06 error wml: Merman Entangler 0 3
20240225 16:21:06 error wml: Merman Fighter 0 1
20240225 16:21:06 error wml: Merman Hoplite 0 3
20240225 16:21:06 error wml: Merman Hunter 0 1
20240225 16:21:06 error wml: Merman Javelineer 0 3
20240225 16:21:06 error wml: Merman Netcaster 0 2
20240225 16:21:06 error wml: Merman Spearman 0 2
20240225 16:21:06 error wml: Merman Triton 0 3
20240225 16:21:06 error wml: Merman Warrior 0 2
20240225 16:21:06 error wml: Mudcrawler 0 0
20240225 16:21:06 error wml: Naga Dirkfang 0 1
20240225 16:21:06 error wml: Naga Fighter 0 1
20240225 16:21:06 error wml: Naga Guard 0 1
20240225 16:21:06 error wml: Naga High Guard 0 3
20240225 16:21:06 error wml: Naga Myrmidon 0 3
20240225 16:21:06 error wml: Naga Ophidian 0 2
20240225 16:21:06 error wml: Naga Ringcaster 0 2
20240225 16:21:06 error wml: Naga Shield Guard 0 2
20240225 16:21:06 error wml: Naga Sicarius 0 3
20240225 16:21:06 error wml: Naga Warrior 0 2
20240225 16:21:06 error wml: Naga Zephyr 0 3
20240225 16:21:06 error wml: Necromancer 0 3
20240225 16:21:06 error wml: Necrophage 0 2
20240225 16:21:06 error wml: Nibbler 0 0
20240225 16:21:06 error wml: Nightgaunt 0 3
20240225 16:21:06 error wml: Ogre 0 2
20240225 16:21:06 error wml: Orcish Archer 0 1
20240225 16:21:06 error wml: Orcish Assassin 0 1
20240225 16:21:06 error wml: Orcish Crossbowman 0 2
20240225 16:21:06 error wml: Orcish Grunt 0 1
20240225 16:21:06 error wml: Orcish Leader 0 1
20240225 16:21:06 error wml: Orcish Nightblade 0 3

### PR DESCRIPTION
**Pull request by CelticMinstrel**
Fixes #8456

### CODE REVIEW

**Comment by stevecotton** [comment]
It seems really weird that the function does logic based on whether `base` has gender varations, but only ensures the unit type is built after doing that logic. Would it be reasonable (in this PR) to add comments to the whole function explaining what the various code paths do, and why it only builds at the end?

**Comment by CelticMinstrel** [comment]
As far as I can tell, if `base` is valid, then it must have already been built. And if it has already been built, so have its variations.

So, if `base` is valid, we're iterating over the variations of `base`. If `base` is _not_ valid, then we're iterating over _all_ the base unit types. That means that `base` must have been obtained either by indexing (which builds the unit type) or by iterating over all unit types (which, as of this commit, builds the unit type). So that means `base` is already built.

It builds at the end because it seemed the simplest place to put it – it doesn't matter whether it's built until we return it to the caller which might be doing anything imaginable with it.

The logic for iterating over a unit's variations is:

1. Return the male variation, if it exists.
2. Return the female variation, if it exists.
3. Return all non-gender variations, in order.

(Incidentally – the male and female variations can _also_ have nested non-gender variations. Those aren't returned unless you grab the male or female variation and iterate over _its_ variations.)

**Comment by ProditorMagnus** [comment]
@CelticMinstrel https://wiki.wesnoth.org/LuaAPI/types#Unit_Type should tell which of the fields are 1.19 only.

**Comment by CelticMinstrel** [comment]
There aren't any fields that are 1.19 only. The 1.19 version was literally _just branched_ and there haven't been any changes to the available fields yet.

**Pull request merged**
