### PR TITLE
#1763: crash in "poisoning" Formula AI (affects mainline campaign)

### PR DESCRIPTION
**Pull request by singalen**
This piece fixes an actual problem:

	if(res.is_empty())  {
		throw formula_error("min(list): list is empty", "", "", 0);
	}

This one is a preventive care:

	if(v.is_empty()) {
		continue;
	}

Reproduces in first mission of Legend of Wesmere. Just move some units in the attack range of bottom left orcs' assassins.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
This looks fine at a glance; I do wonder if maybe the minimum of an empty list should be INT_MIN though (and INT_MAX for the maximum of an empty list)... but that won't work for strings, so this is probably simpler.

**Comment by singalen** [comment]
I suggest that the functions should have a "default" argument, if the first one is a list.

**Comment by CelticMinstrel** [comment]
I'm not entirely sure what you mean by that. How is it different from simply adding another argument/element?

**Comment by singalen** [comment]
It doesn't, except for it doesn't have to modify a list or create a new one. On a second thought, I don't think it matters for Wesnoth. 
If `min(list, another value)` is valid call in FAI, then it doesn't differ at all.

**Comment by CelticMinstrel** [comment]
Looks like it's valid based on the code. I haven't tested.

**Comment by singalen** [comment]
Well, I have tested it on Mac - it definitely fixed the crash :)

**Comment by CelticMinstrel** [comment]
I can't remember a reason why this hasn't been merged, so I'm assuming no reason exists.

**Pull request merged**
