### PR TITLE
Don't assume unit is on the map when testing ability active

### LINKED ISSUE #2247: Backstab special causes WFL error with wesnoth.simulate_combat in AI context
When a Lua AI uses wesnoth.simulate_combat with an attacker that has the backstab special, this causes the following error:
```
ERROR: TYPE ERROR: expected string but found null (null())
  enemy_of
  unit_at
  direction_from
formula type error: TYPE ERROR: expected string but found null (null())
```
This almost certainly also means that the backstab special is no evaluated correctly.  The problem does not happen if wesnoth.simulate_combat is called during the player's turn.

The error originates in https://github.com/wesnoth/wesnoth/blob/master/data/core/macros/abilities.cfg#L293 and according to an irc chat with @CelticMinstrel yesterday, the reason is that `other` in the equation is null in this context.

To reproduce, I have attached a save from a slightly modified version of the Fast Micro AI test scenario which uses only Thieves.  Just load, type `:droid` and stderr will be flooded with error messages of that type.

[Fast_Turn_1_backstab_bug.gz](https://github.com/wesnoth/wesnoth/files/1505999/Fast_Turn_1_backstab_bug.gz)

### PR DESCRIPTION
**Pull request by CelticMinstrel**
This refactors ability tests to use a passed-in unit instead of
searching for the unit on the map based on its location.

While it does fix #2247, I am not confident that this won't also
have some undesirable side-effects.

### CODE REVIEW

**Comment by gfgtdf** [comment]
seems like you are storing/converting a `const unit*` to a `unit_const_ptr` aka `boost::intrusive_ptr<const unit>` in multiple places, if `unit_const_ptr` were defined as a shared_ptr this would clearly fail (double free) and also with instrusive_optr this can casue problems:

1) It assumes that the original unit is owned by a unit_const_ptr which might not be the case, in particular if this code is somehow called in the units constructor (for example by unit::ctor->advance_to->apply_effect->check filter->check_ability_active, not sure wehnetrh this make sense but i couldn't come of with somthing better)

2) It doesn't look the like the those fields are reset after the ability check is completed, so it will extend the lifetime of the other unit objects this is oeven more problematic as those unit_prt objects are probably owned the the object they point to casuing real memeory leaks. 


The best fix for (1) is probably to turn the unit ctor in a 3 step factory method and makign the original ctor private, the factor methos woudl then in that order:
1) construct a unit* object where the unit ctor does oynl the very basic things liek initilizing fields.
2) store it in the unit_ptr
3) call soem init fnction that does th rest of the initilisation in particular calling unit::advance_to.
4) return the unit_ptr

For (2) the code should probably reset the self_/other_ objects afte the calculation is finished.

**Comment by CelticMinstrel** [comment]
I don't know of any place where a `unit*` _wouldn't_ be reference-counted? And are you sure those fields aren't implicitly reset when variables go out of scope?

That aside, if you could identify the particular points where these issues arise, that would be more helpful. I probably won't get back to this this weekend (due to my work on schema stuff), but likely next week I can do something about it.

**Comment by gfgtdf** [comment]
> I don't know of any place where a unit* wouldn't be reference-counted? 

I just told you one: during the units ctor before the unit is converted to a unit_ptr.

> And are you sure those fields aren't implicitly reset when variables go out of scope?

which varaibles? attack_type is a part of a unit structure and it doesn't go out of scope unless the unit is destroed or it's attacks are somehow reset..

**Comment by Vultraz** [comment]
I guess consider this another reason why `shared_ptr` would be beneficial :P

**Comment by gfgtdf** [comment]
To make it clear, (1) was not the main problem here it's (2). (1) describes a quite unlikeley situation that can be fixed by a rather easy refactor of which other parts of the codebase might profilt aswell. (2) on the other hand might cause quite big memeoryleaks even if no umc is involved at all.

By making it use raw pointers you now have to worry about the posiblity that it might point to a freed object.

Even with using unit* to store that unit data, it'd be ebetter to make sure these pointers are reset when the check is done.

**Comment by CelticMinstrel** [comment]
@gfgtdf Is this better?

**Comment by gfgtdf** [comment]
i think using a raii struct is the correct way, but in the new implementation during an attack the specials_context is only set while the damage stats are calculated, i think it'd be nice if they'd be present in attack related events aswell so that special_active filters in attack related events work.

**Comment by CelticMinstrel** [comment]
Agreed; do you happen to know where that would be in the code? (If not I'll just grep for it though.)

**Comment by gfgtdf** [comment]
and another issue: specials_context returns the specials_context_t by value, this might mean that a temporary is constructed that is then immidiately deleted (which will then immidiately call ~specials_context_t()) (c++17 gurantess copy elision in that case afaik but we don't use c++17).


> Agreed; do you happen to know where that would be in the code? (If not I'll just grep for it though.)

You mean when those events are fired? quite sure it's somehere in actions/attack.cpp

> And can you think of anywhere else this would be needed?

hmm i think attack.cpp is the only place where this is needed, from looking at the prs diff oynl the attack.cpp code, the report and the attack prediction dialog use  set_specials_context, and i don' think the later two can fire events.

**Comment by CelticMinstrel** [comment]
I don't think we can really do anything about the copy elision issue. I can try deleting the copy constructor, I guess, though actually that's probably done implicitly anyway since it has a reference member.

**Comment by gfgtdf** [comment]
it won't compile if you rmeove it, and a reference memeber will not prevent it from generating a cctor.

what happens (in the bad case) is that

1) object1 is created (`specials_context_t(*this, self, loc, attacking)`)
2) object2 is creatred via copyconstructor or movector (`auto ctx = weapon->specials_context`)
3) object1 is is destroed
4) other things happen
5) object2 is destroed


so after step 3 the context will be reset which is not what we want.

you have basicially 2 options to fix this
1) make set_specials_context return a uniqe_ptr<specials_context_t>
2) add a custom movector to specials_context_t that marks the 'old' obejct so that it's destructor won't do anything.

**Comment by CelticMinstrel** [comment]
Heh, I too came to conclusion 2 on my own, so there you go.

**Comment by CelticMinstrel** [comment]
Just remembered to make sure `wesnoth.simulate_combat` actually has a weapon specials context... fortunately, it does, so I didn't have to do anything.

**Pull request merged**
