### PR TITLE
Various Bug fixes and change to mouse scroll function

### PR DESCRIPTION
**Pull request by binarycoder**
Fiixes for:
24644
25217
21634
24383
Additional changes to satisfy 25591

### CODE REVIEW

**Comment by gfgtdf** [comment]
this can't be merged as-is because;
1) your changed to the msvc projectfiles will make it impossible to build with msvc 2013
2) this pr contians multiple changes to unrelated bugs which mkaes it hard to review please ad seperate prs for each indivudual bug.
3) uit has mergign conflicts please rebase your branch to reolve merging conflicts.

**Comment by CelticMinstrel** [comment]
Rather than rebasing, I think it's better if you create a completely fresh branch and cherry-pick the relevant commits. For example, @binarycoder could submit his label patch by opening a command-line window, using `cd` to switch to the wesnoth directory, and running the following commands. (These are written with the assumption that you cloned Wesnoth from your repository, binarycoder/wesnoth, rather than from the main wesnoth/wesnoth repository. I'd be happy to help you figure out what needs changing if this is a false assumption.)

First, download the latest master code from the main repository, and start a new branch:

```
git fetch https://github.com/wesnoth/wesnoth.git master
git checkout -b fix_21634 FETCH_HEAD
```

Then grab the specific commits that fix the issue (as well as the commit adding your name) and push it to your copy of the repo:

```
git cherry-pick a59ee56 7f0cd7b d2b9ac5
git push -u origin fix_21634
```

Finally, navigate to the fix_21634 branch on github and open a pull request from there.



Before starting this, you probably also want to rename the folder _projectfiles/VC12_ to _projectfiles/VC14_. After doing so, it may be necessary to run `git checkout projectfiles/VC12` from the command-line in order to restore the lost VC12 project files. Of course, this won't affect your VC14 project files, because they're now in a different directory.

**Comment by binarycoder** [comment]
Sounds good. I'll be making individual pull requests from my own fresh copy on behalf of the team, you should see them soon. Thanks,

**Comment by CelticMinstrel** [comment]
@binarycoder - That's good to hear, though personally I'd prefer if the person who made each commit opens the PR for that commit.

**Comment by binarycoder** [comment]
Ah, alright, we can do that then.

**Comment by CelticMinstrel** [comment]
(If you were working together on a larger change though, then it would be fine to have a PR with commits from multiple people.)

**Pull request closed without merging**
