### PR TITLE
Add lua functions music_list.get_current() and music_list.get_previous()

### PR DESCRIPTION
**Pull request by Pentarctagon**
Adds lua functions to get a config of the currently playing song and of the song that played before the current song.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
So I don't really get the point of `wesnoth.music_list.get_current()`. It literally returns the exact same thing as `wesnoth.music_list.current`, just in a different format. Why not just add a `__cfg` option to the music track metatable that uses `write_track` to produce a config of the track?

On the other hand, `wesnoth.music_list.get_previous()` does seem like it could be useful. I think I'd prefer a non-functional syntax, mind you (ie, adding it to `impl_music_track_get`), and it should return the track object rather than a config.

**Comment by Pentarctagon** [comment]
As far as `get_current()`, that is the entire purpose, since I want to write all the data from `wesnoth.music_list.current` to a WML variable at once, but currently can't.  I made it a function to try to be consistent with other fields returning userdata, but I don't really have a preference either way.  What is `write track` though?  I don't see a method by that name.

And similar question for `get_previous`: I don't see a method called `impl_music_track_get`.

**Comment by CelticMinstrel** [comment]
Okay, so I misremembered the names of the functions. `impl_track_get` is where you'd add new fields (rather than new functions). As for "write track", I don't remember its exact name, but it's the function that's called by `sound::write_music_play_list` in order to produce a config of every track.

So, to summarize, I'd prefer to see `wesnoth.current.__cfg` and `wesnoth.previous.__cfg` for these use cases (with the minor caveat that `wesnoth.previous` could be `nil` and thus you'd have to check for that).

**Comment by Pentarctagon** [comment]
I don't think `wesnoth.current` and `wesnoth.previous` are good names for those fields.  It begs the question "current and previous what?".  It also seems kind of odd that getting the current and previous songs wouldn't be attached to `wesnoth.music_list`.

**Comment by CelticMinstrel** [comment]
Oops, my mistake. I meant `wesnoth.music_list.current.__cfg` and `wesnoth.music_list.previous.__cfg`.

**Comment by Pentarctagon** [comment]
Alright, I've got `wesnoth.music_list.previous` working locally.  Do you have any advice on where to look for how to implement `__cfg` on `previous` and `current`?  My first thought was to use `return_cfg_attrib` or other return_* methods, but that seems to have been incorrect.

**Comment by CelticMinstrel** [comment]
I'm pretty sure `return_cfg_attrib` would be the right choice. It's a macro, and the second argument is a code chunk that writes the data to the pre-declared `cfg` variable, so it would end up being something like `track->write(false)` if I recall correctly.

(I believe the `false` in this case tells it whether to set "append" in the config, so if you wanted you could pass the actual value of "append" instead.)

**Comment by Pentarctagon** [comment]
Though unless I'm misunderstanding something, adding `__cfg` to `current` and `previous` would require them to be created similarly to how `wesnoth.music_list` is setup in the `lua_audio` namespace.  Just doing something like this in `impl_music_get` obviously does not work:

```
if(strcmp(m, "previous") == 0) {
push_track(L, sound::get_previous_music_track());

config cfg;
sound::get_previous_music_track()->write(cfg, false);
return_cfg_attrib("__cfg", cfg);

return 1;
}
```

**Comment by CelticMinstrel** [comment]
You want to add your code in `impl_track_get`, which is the `__index` metafunction for the userdata returned by `wesnoth.current`. This is the same type of userdata created and pushed by `push_track`.

The other thing wrong with your code is that, within `return_cfg_attrib`, there is an implicit `config cfg` declared, so you'll end up returning an empty config instead of the one you wrote the track to. Just move the write call into the macro where you're currently passing `cfg`.

**Comment by Pentarctagon** [comment]
Ah, alright.  In that case, are you okay with instead having it set like this:

```
return_cfg_attrib("__cfg",
                  cfg["append"]=track->append();
                  cfg["shuffle"]=track->shuffle();
                  cfg["immediate"]=track->immediate();
                  cfg["once"]=track->play_once();
                  cfg["ms_before"]=track->ms_before();
                  cfg["ms_after"]=track->ms_after();
                  cfg["name"]=track->id();
                  cfg["title"]=track->title()
                 );
```

This allows accessing with `wesnoth.music_list.previous.__cfg.name`, whereas using `track->write` results in accessing the data needing to be like this: `wesnoth.music_list.previous.__cfg[1][2].name`.  `__cfg[1][1]` at that point is just the string "music".

**Comment by CelticMinstrel** [comment]
Ah, you have a point there. That code seems fine to me. Alternatively, you could use write(), but then assign `cfg = cfg.child("music")`, though that does imply an unnecessary copy.

**Comment by CelticMinstrel** [comment]
Please use tabs for indentation.

**Comment by Pentarctagon** [comment]
I thought I had, but apparently code::blocks defaulted to using 4 spaces rather than tabs.  Should be all fixed now.

**Pull request merged**
