### PR TITLE
wesnoth.set_dialog_value can now unfold treeview nodes

### PR DESCRIPTION
**Pull request by gfgtdf**

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Hmm, I'm actually slightly surprised if this works, given 731f47b7 - is there something I've missed?

**Comment by gfgtdf** [comment]
> Hmm, I'm actually slightly surprised if this works, given 731f47b - is there something I've missed?

Actually this commit was not tested at all but i don't know why i shouldn't work.

> (More specifically, I thought that commit would be required in order to even find a treeview node.)

wesnoth.add_tree_node https://github.com/wesnoth/wesnoth/blob/32b2630c0b6aeb79e2801a0c077469756ed6f171/src/scripting/lua_gui2.cpp#L843 does work (at lest in 1.13.7) and it also requires a treeview node parameter, so i assumes there are no problme with finding a sub node here.

**Comment by CelticMinstrel** [comment]
Hm, there are actually two cases in the find_widget case for tree nodes, and 731f47b7 would only affect the second one. I'm not sure in what case that second case would have been useful anyway from Lua's standpoint, though.

**Comment by gfgtdf** [comment]
the travis check has passed so i'll just merge, since the newly added code cannot be reached unless you call set_dialog_value with a treeview node, it shouoldn't casue bugs.

**Pull request merged**
