### PR TITLE
Remove MSVC support from cmake.

### PR DESCRIPTION
**Pull request by Pentarctagon**
This PR:
- Removes MSVC support from cmake.
- Removes the two unused options `ENABLE_TOOLS` and `ENABLE_SDL2_TOOLS`.

### CODE REVIEW

**Comment by gfgtdf** [comment]
did you remvoe it because it doesn't work or is there another reasion?

**Comment by Pentarctagon** [comment]
It's unused and unmaintained, and Wesnoth has its own set of MSVC files anyways.

**Comment by GregoryLundberg** [comment]
I tested it a week or so ago. I was able to get it working up to the point where it asked for the translation programs for compiling MO to PO. Those are not in the 'external' kit, and I didn't feel like tracking them down.

Our windows packager uses SCons and an ancient MinGW MSYS.

The best way, of course, would be to use Visual Studio Build Tools and update the VC project file to do the translation compile and create an installer. But, the scons system works, so there's no rush to upgrade to a pure windows build system for windows.

**Comment by gfgtdf** [comment]
I tested once (quite long ago) the msvc files generated by wesntoh cmake. They coudl be used to to complie with msvc, but they had a problem that was that most properties are applied 'per file' which made using cmake generated projectfiles quite hard to use for developing since you had to manually add these options to each file you want if you want to add a file to these projectfiles.

So i'm not really against removing these although i do think that it coudl make maintaining the msvc prjectfiles easier if it weren't for the problem above.

**Comment by GregoryLundberg** [comment]
Code-reading, this looks good. I passed it through my build matrix to check nothing unexpected appeared. For all eight combinations of SCons/CMake CLang/GCC and Release/Debug, with all else defaults, I get no errors and no warnings.

**Comment by Pentarctagon** [comment]
@gfgtdf I'm not sure how cmake used to do it, but currently options are applied globally, with some special handling of the lua source files.  So I'd assume the way it was intended to be done, would be the new file would be added to cmake and then the project files would be re-generated.  I don't know if that's any better, though.

**Comment by GregoryLundberg** [comment]
```
20171125 01:36:22< TadCarlucci> Ivanovic, Any objection to merging PR #2241? Code-reading looks good. Not sure if any testing in needed but, since you're idle, I'm passing it through my build matrix to make sure nothing major pops up.

20171125 07:55:22< Ivanovic> TadCarlucci: the change kills too much
20171125 07:55:31< Ivanovic> set(CXX_FLAGS_PROJECT "-std=c++11 -Wextra -Werror=non-virtual-dtor")
20171125 07:55:50< Ivanovic> line 238 should stay
20171125 07:56:45< Ivanovic> ah, wait, you merged all of them into new 202, right?
20171125 07:57:28< Ivanovic> are you intentionally removing ENABLE_TOOLS as well?
20171125 07:59:05< Ivanovic> TadCarlucci: you are also removing the option flag ENABLE_SDL2_TOOLS without removing any blocks that might rely on this, that looks strange
20171125 08:00:02< Ivanovic> if you are intentionally removing those two options it might make sense to split that into two separate commits
```

I just did a full-project search.ENABLE_SDL2_TOOLS is unused, and you already have all changes required to remove ENABLE_TOOLS.

So, his operative comment is to break into separate commits.

**Pull request merged**
