### PR TITLE
fix typo en german translation

### PR DESCRIPTION
**Pull request by ePaul**
This string appears in the status dialog.
I hope editing this file is the right way to go – if not, please tell me what is the correct one.

### CODE REVIEW

**Comment by hrubymar10** [comment]
https://wiki.wesnoth.org/WesnothTranslationsHowTo#How_to_submit_your_translations

```
Important: Please do not submit translations as pull requests on the Wesnoth github repository site. While that seems like a good idea, it causes potential complications that we cannot always easily resolve. As a result, we cannot accept translations submitted via pull request and will close such PRs immediately.
```

I don't want to do that as it is only one trivial change but somebody else can decide different...

**Comment by ePaul** [comment]
Hmm, so I guess I'll need to send this to the maintainer of the german translation?

**Comment by hrubymar10** [comment]
Yes, you should. Your maintainer `chrber` will send it to Ivanovic (translations maintainer) and he will push it to 1.14 branch and master.

More info about German translations/translators: https://wiki.wesnoth.org/GermanTranslation

**Comment by sevu** [comment]
I got an Mail from `chrber` today, he is not active anymore, his circumstances changed over the years.
Seems to be similar for the other members of the old team too.

There exists also this page https://wiki.wesnoth.org/GermanTranslationErrors

**Comment by jyrkive** [comment]
Translation changes via pull requests are not accepted.

**Pull request closed without merging**
