### PR TITLE
Fix 'scons dist'

### PR DESCRIPTION
**Pull request by jostephd**

### CODE REVIEW

**Comment by loonycyborg** [comment]
Currently I'm using git archive without involving a buildsystem to make the tarball. You have own use for this target?

**Comment by jostephd** [comment]
I do have a use for producing my own tarballs (I use git HEAD with some patches) but in the future I'll just use `git archive`.

**Comment by CelticMinstrel** [comment]
Any reason not to have `scons dist` use `git archive` then?

**Comment by jostephd** [comment]
I don't know how to write that in scons, but we could write it as a shell script:

```
v=`git describe --dirty=-Modified`
git archive --prefix=wesnoth-${v}/ -o wesnoth-${v}.tar.bz2
```

**Comment by jyrkive** [comment]
In any case, this pull request is an improvement. Merged.

**Pull request merged**
