### PR TITLE
Bug in [for] missing step

### PR DESCRIPTION
**Pull request by GregoryLundberg**
https://forums.wesnoth.org/viewtopic.php?t=46450 reports a Lua crash if end is given but step is not. The wiki says the default step is 1. Note that if end is negative, the [for] does nothing (per sanity check).

### CODE REVIEW

**Comment by gfgtdf** [comment]
Looks liek a rathe complicated way to do it, the lua way to do it is:
```
loop_lim.step = cfg.step or 1
```

That said, i think soemthitn else is wrong here, the code below does a `loop_lim.step ~= nil ` check which will probably always be true then.

**Comment by GregoryLundberg** [comment]
Corrected for both points

**Comment by gfgtdf** [comment]
hmm  no you got it wrong, replace the whole if else thing with just `loop_lim.step = cfg.step or 1` in your case the `or 1` has no effect at all. Also i'm still unsure whether just disabling the ifs below is te best way to fix it, it'd be better if the one who original wrot that code coudl review this.

**Comment by GregoryLundberg** [comment]
The if tests one variable, the then sets another.

**Comment by GregoryLundberg** [comment]
I think it's to avoid evaluation of the values until execution time.

**Comment by gfgtdf** [comment]
ooh right compltley missed that. Then what i said at first is probly wrong too.

**Comment by GregoryLundberg** [comment]
Nah. The 'or 1' thing is the Lua way and the ~=nil would always be true, as you said.

**Comment by GregoryLundberg** [comment]
However: pinging @CelticMinstrel for review and commit

**Comment by gfgtdf** [comment]
No wait i think i was still right, even though the if checks `cfg.step` while the then code used `cfg_lit.step` we can assume `cfg.step` beeing 'true' iff `cfg_lit.step` is true since even if step somtians something like "$a" and a is empty, `cfg.step` shodul still evaluate to an empty strign instead of nil.

**Comment by GregoryLundberg** [comment]
'or 1' didn't work. The '~=nil' is always true. All fixed.

Test cases:

[for] end=-1 PASSED ([do] skipped)
[for] end=0 PASSED ([do] executed once: 0)
[for] end=2 PASSED ([do] executed thrice: 0, 1, 2)

[for] end=-1 step=-1 PASSED ([do] executed twice: 0, -1)

**Comment by CelticMinstrel** [comment]
Looks fine to me.

@gfgtdf would be correct that `cfg.step` is truthy _iff_ `cfg_lit.step` is truthy, since the only falsey values in Lua are `nil` and `false`, and if `cfg.step` is either of those, no variable substitution will have occurred, meaning `cfg.step == cfg_lit.step`.

**Comment by gfgtdf** [comment]
> 'or 1' didn't work. The '~=nil' is always true. All fixed.

That's what i said before, i never suggected to add the or 1 like that, instead my suggestion was to replace the whole `if cfg.step then loop_lim.step = cfg_lit.step else loop_lim.step = 1 end` with `loop_lim.step = cfg_lit.step  or 1`

**Comment by CelticMinstrel** [comment]
Ah, yeah, that would make sense, sure.

By the way, how much work would it take to ensure all your tests are actually encoded into the WML unit tests so that they're not accidentally broken later? (Or are those test you listed precisely the WML unit tests that already exist?)

**Comment by GregoryLundberg** [comment]
Done

**Comment by CelticMinstrel** [comment]
Surprised you put them in a different file than the previous `[for]` tests, but glancing over them it doesn't seem like yours duplicate anything in the existing tests.

**Pull request merged**
