### PR TITLE
new terrain variation - Elf castle ruins

### PR DESCRIPTION
**Pull request by doofus-01**
A few of the images need revision, but it's basically done.
screenshot_elf_ruins

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I should totally use this in my campaign!

**Comment by ln-zookeeper** [comment]
The walls themselves look good, but I'm not sure if the various trees are a good idea. The birches look very random and possibly weird when the castle is surrounded by other kinds of forest, and the thing sprouting from that one tower tile looks suspiciously like a palm tree. It's true that it makes sense that an abandoned elvish castle with its courtyard covered in grass and nice soil would end up growing trees sooner than one covered with cobblestone, but I don't think that's something that needs to be represented in the tiles themselves. After all, if someone wants an elvish castle ruin on their map, they'll put forests in and around it.

I also wonder whether the dry grass is the best choice. It doesn't make sense on a summer map where everything else is green. Might dirt work better as a one-size-fits-all choice?

**Comment by doofus-01** [comment]
OK, I'll remove the trees (the palm tree was already gone in the last commit, but I thought pine trees were 'generic' enough).  As for the dry grass, I thought it was the closest to one-size fits all - overgrown and unmaintained.  Wouldn't plain dirt would break the 'elvish nature theme'?  

Two possible solutions I can think of:
1.  Make a different "grass" that is mix of green and brown, to be a mix of weeds and dead weeds.
2.  Set some flag if there are neighbouring Gg, ^Fds, or ^Fms so that a green variation shows up on summer maps, or can be made to show up at least.

I think 1 is easier, I'll try that first.

**Comment by CelticMinstrel** [comment]
> As for the dry grass, I thought it was the closest to one-size fits all - overgrown and unmaintained. Wouldn't plain dirt would break the 'elvish nature theme'?

Rather than dry grass, I'd expect the courtyard to be completely overgrown with weeds. Your mixed brown+green version may indeed be better for this.

**Comment by doofus-01** [comment]
If there are no objections, I'll squash-merge this.  I can make edits to grounds.png, for example, later if needed.  Issues will be better discovered if people try it rather than looking at screenshots.

**Comment by ln-zookeeper** [comment]
Looks good to me.

**Comment by doofus-01** [comment]
Thanks, @ln-zookeeper .

**Pull request merged**
