### PR TITLE
Fix bug report for halo trmain afyer frath animation

### PR DESCRIPTION
**Pull request by newfrenchy83**
@jyrkive i'm sorry to recycle an old PR but an bugs is teported in https://github.com/wesnoth/wesnoth/issues/3509 and i fear what put clear haloes in unit_die display is necessary in windows 10. If you find another soluce thank you else...

### CODE REVIEW

**Comment by newfrenchy83** [comment]
@jyrkive.  I put another fix for this bugs in this PR

**Comment by jostephd** [comment]
@newfrenchy83 Shouldn't `clear_haloes` be called before the `die` event (but after the `last breath` event)? I think as you have it now, during a `die` event the halo is visible but the unit is not?

**Comment by newfrenchy83** [comment]
I tevert that and put another fix

**Comment by newfrenchy83** [comment]
@jyrkive. Clear_haloes sould called after the last breath and die event else halo remain if event called. I put clear_haloes in attack.cpp and synced_command for thatand revert unit_die display

**Comment by jyrkive** [comment]
I fixed the bug in commit 4666ae8c2334b73912cb96f42705c2f61e0a1893, in a completely different way.

**Pull request closed without merging**
