### PR TITLE
Allow players to choose Kaleh or Nym in the tutorial

### PR DESCRIPTION
**Pull request by stevecotton**
Could be separated in to two branches, one making the strings use
"$student_name" to allow any character, and one for adding Kaleh
and Nym to the selectable characters.

Inspired by LienRag's work on black protagonists for HttT.
https://r.wesnoth.org/t48990

### CODE REVIEW

**Comment by GregoryLundberg** [comment]
Does anything actually change other than the visuals and messages? What I mean is are the two (now four) characters sufficiently different that replaying with a different student can emphasize different things (for example: sword vs bow, good vs evil, etc.)? Or, are they virtually identical so the choice really does not matter?

**Comment by stevecotton** [comment]
They're identical. So there's possibly reason to do this change.

**Comment by GregoryLundberg** [comment]
I wonder if it might be possible to add some descriptions and/or story to aid the player choosing?

And I wonder if there might be sufficient changes between the characters to have the tutorial end with the option to run it again with a different lead character, perhaps on different maps, etc.  Although, if this is done, it might want to wait for 1.15. I remember being basically clueless even after finishing the tutorial and going ahead with the first campaign (HttT) woefully unprepared for it. And I'm thinking I probably would have chosen to extend the tutorial if that had been an option.

**Comment by CelticMinstrel** [comment]
I don't see the point of offering additional options in this way; the tutorial does not exist to tell a story, it exists to teach the mechanics. Whether you choose between Konrad/Li'sar or Kaleh/Nym doesn't seem like it would make a difference to that goal.

And if you want something like Gregory says where the tutorial contains more information, I don't see how adding additional characters would help. For that you want to extend and expand it, not add additional options &ndash; I think it's ideal if most people who play the tutorial can see all of it on a single play-through.

**Comment by stevecotton** [comment]
Thanks for the feedback, I'll close the PR.

**Comment by CelticMinstrel** [comment]
Hmm. Now that I've spent more time to look at the commit message and the linked thread, I'm not so sure this is pointless. I'd be interested to hear opinions from others, especially the author of that thread.

Certainly we shouldn't be adding different information based on the hero chosen, but perhaps it's not such a bad idea to have more options for greater inclusiveness.

**Pull request closed without merging**
