### PR TITLE
Fix bug: Map may not have starting positions

### PR DESCRIPTION
**Pull request by GregoryLundberg**
Look before you leap ...

### CODE REVIEW

**Comment by gfgtdf** [comment]
wha did you add the ```
if (scroll_team == 0) {
	scroll_team = 1;
}```
lines?

**Comment by GregoryLundberg** [comment]
The original code used team 1 (human or not) for the second scroll attempt.

My assumption was the idea was to scroll to the first human player and, if none, scroll to side=1

**Comment by GregoryLundberg** [comment]
The intention of the code, at this point, seems to be to have the map start scrolled at a reasonable guess.

The bug I'm fixing came up on LoW S01 with two messages on the console because the MAP has NO starting locations at all and the original code tried, first, the first human player (side 1) then tried side 1 when that failed .. two errors even though both happened, in this case, to be for the same side.

Talking with gfgtdf I looked at the map and LoW S01 uses a common map (Lintanir) and a mask. The mask has (incorrect) starting positions.

So, I'm thinking that this first-guess scroll was actually done too soon and it should have waited until the mask was loaded and baked onto the map.

The desire seems to be to have the scenario honor the positions from the mask, and to include positions for additional units which start at non-standard positions, relative to their leaders. When I get that working I can re-visit this issue and, perhaps, move this entire initial-scroll idea to someplace more appropriate.

We'll see.

In the meantime, if this PR merges, it does get rid of the errors arising when the map does not give any starting positions. And it's not problem (perhaps even wiser) to remove all this code and put it in a better place using a new PR should that come to pass.

**Comment by GregoryLundberg** [comment]
I just had these same errors pop up while testing HttT S17 ('The Sceptre of Fire'), which is a randomly generated map. When I'm done making the changes I'm testing I will dig into this and make sure this PR is 'doing the right thing' for this case (if I can get it to duplicate since it's a random map).

**Comment by gfgtdf** [comment]
> I just had these same errors pop up while testing HttT S17 ('The Sceptre of Fire'), which is a randomly generated map.

Whcih remings me, it'd be nice if this map generation code woudl be ported to lua, there is alreada  a half-working port of the cavegen.cpp file to lua in https://github.com/wesnoth/wesnoth/blob/master/data/multiplayer/scenarios/Random_Scenario_Lua_Cave.lua, still its not good enough yet to replace it.

**Comment by GregoryLundberg** [comment]
Maybe, someday. I'll make a note in my Issues.

**Comment by GregoryLundberg** [comment]
Tested [scroll_to] .. of cource, it works in 'start' .. does not work in 'prestart'.

Noted that no map positions (cause of error messages) and there is still a 'scroll'-like operation even though no WML calls for it. Appears to scroll to (12,12) or so on a (30,30) map. So there seems to be something scrolling somewhere after these failed scrolls and before prestart.

**Comment by GregoryLundberg** [comment]
I got curious as to why one would want to scroll to a map-defined starting location when they're optional and the designer can handle it all in prestart and start.

So, I tracked the source back. It game from the initial check-in of playsingle_controller.cpp back in 2006.

Frankly, I question the wisdom of this ever being done since, even in 2006, the map-defined starting locations were optional. And since, from my testing, something else, somewhere, is scrolling the map someplace else before the designer has a chance to in prestart/start.

You questioned the if 0 then 1 line and, now, I question whether a better change would simply be to remove these entirely. I will do some more testing. This time with a map having a human starting position and no WML to scroll, and see if that later scroll still moves the map to 12,12 .. if so, there really is no need for any of this so early in the init process

**Comment by GregoryLundberg** [comment]
The only condition where this works is:
1) The map has a starting location for a human side, or for side 1, and
2) The human-controlled [side] has scroll_to_leader=no, and
3) No [message]s appear during the start event, or all have scroll=no.

In all other cases, the map will scroll away from this position (or scroll to the same position) during the start event.

**Comment by gfgtdf** [comment]
I didn't test it but from  looking at the code it seems like without this code even with scroll_to_leader=yes the map will not start on the leader position but will instead visibly scroll to that position starting at the corner. Same for [message].

In any case is see disadvantages of keeping this code so i'll just merge it as it is

**Comment by GregoryLundberg** [comment]
Concur. I believe it is ready to merge, then.

**Pull request merged**
