### PR TITLE
new stone wall terrain variation -> catacombs

### PR DESCRIPTION
**Pull request by doofus-01**
A modified stone wall, goal is to have overlays, animations, or something to make this useful for undead scenarios, but for now it's just the base terrain graphics images.
catacombs1

### CODE REVIEW

**Comment by stevecotton** [comment]
I suggest making a terrain code that does not have the stone2 variation, for ancient catacombs where any cloth that was there has already rotted away.

`Xot^Efs` has the sconce over the opening - would it be simple to move the sconce along the wall a bit for that terrain combination?

**Comment by CelticMinstrel** [comment]
Does this meld nicely with the regular wall if you want the niches to be more spaced out?

**Comment by doofus-01** [comment]
> I suggest making a terrain code that does not have the stone2 variation, for ancient catacombs where any cloth that was there has already rotted away.

I made the cloth less "puffy", I think it's more subtle now, could be very old and rotted away.

>  Xot^Efs has the sconce over the opening - would it be simple to move the sconce along the wall a bit for that terrain combination?

I think it's better to have a variation, changing the position has potential for headaches (Xos^Efs and Xot^Efs next to each other, for example)

> Does this meld nicely with the regular wall if you want the niches to be more spaced out?

Possibly, depending on what you are expecting.  Since the wall panels and hexes don't line up, I'm not sure it's possible to make every other one have a hole, at least not in a way the user can control.
Screenshot_20191101

**Comment by doofus-01** [comment]
Last commit isn't specific to catacombs, but it gets closer to what I think @CelticMinstrel was asking about.  Minor variations means Xom/Xoi can mix, and Xos/Xoc/Xot can mix, where 'mix' means every other SE/SW facing panel is alternated.
Screenshot_20191101_b

**Comment by doofus-01** [comment]
That last commit allows putting bodies in the large diagonal catacombs holes by using the ^Edb overlay, rather than making a new terrain.
Screenshot_20191110_
Doing all this is starting to touch existing terrain graphics too much, I'd like to commit this before adding anything more.

**Comment by stevecotton** [comment]
> Doing all this is starting to touch existing terrain graphics too much, I'd like to commit this before adding anything more.

Yes, please do.

**Pull request merged**
