### PR TITLE
UtBS: code refactor

### PR DESCRIPTION
**Pull request by DisherProject**
In general, i wouldn't find refactoring code very useful, but UtBS has very long files and sometimes reading them is not that easy. What i have tried to do is mainly:

- Renaming variables, so that their aim is clearer

- Moving code from macros to custom events, since macros must be defined before they are used. Custom events can be written in "chronological" order

- Updating code (`filter_condition` instead of if-then, `repeat` instead of `while` ...)

There aren't any variations in what the code does: this refactor doesn't affect the "result" of the code, but just how it is achieved.

### CODE REVIEW

**Comment by GregoryLundberg** [comment]
No changes for scenario 1?

**Comment by DisherProject** [comment]
> No changes for scenario 1?

Some scenarios don't need to be refactored imo. I'll add some other changes later

**Comment by DisherProject** [comment]
I've pushed all of my commits. Let me know if they are ok.

**Comment by nemaara** [comment]
This is a bit hard to deal with since you've put all the changes here in one PR, without saying what the refactor actually does. It would be a lot easier if you split it up into different commits at least (and maybe PRs for different scenarios) so that I can tell what the refactor is doing.

**Comment by DisherProject** [comment]
I hope this is clearer now. 
I couldn't split S3 refactor in more than one commit, since it's all about rewriting one single lengthy event.
I'll open a new PR including some fixes in case this refactor is merged.

**Comment by nemaara** [comment]
I've looked over scenarios 2, 4, 6b, 7b, 8, and 12. If you want to split those commits off into a separate PR, I can merge them now. I'm not entirely sure if I have time to check over the others before the string freeze, since I'll need to playtest them, but I'll do my best.

**Comment by DisherProject** [comment]
If you don't mind, i'd rather keep all these commits in one PR. 

There is no hurry in merging this, as this is just a refactor. Anyway i didn't write any new line of dialogue.

**Comment by nemaara** [comment]
It's not that you wrote new dialogue, but some of your changes will still flag strings as added or removed, which translators will have to deal with. 

I've looked at S5, there is one small error: if you sight the dwarf leaders when allied with dwarves, they actually say the troll leader lines of text. You put in:

> "What you doing back here? Nasty dwarves are to the north, no dwarves this way. Go back and fight bravely."

when it should be:

> "What are you doing back here? The trolls hide in the southern tunnels, not this way."

Other than that, S5 is fine.

**Comment by DisherProject** [comment]
> I've looked at S5, there is one small error

Done, thank you

**Comment by nemaara** [comment]
Finally looked over S9, seems like there's no more issues with this PR. I'll merge when string freeze is over.

**Comment by nemaara** [comment]
Actually, I realized there's not much of a point to have this in 1.14.8, and I'm not toootally sure if it'll cause problems with saves/replays, so I'll just merge it for 1.15.0 for safety.

**Comment by DisherProject** [comment]
@nemaara it will break saves probably, because i renamed many variables

**Pull request merged**
