### PR TITLE
Mudcrawler, Great Wolf, Cuttlefish, and Bloodbat Portraits

### PR DESCRIPTION
**Pull request by doofus-01**
I'm not opposed to touching these up if someone else thinks it's needed, but I consider them good enough.  I'll make another PR for master.

### CODE REVIEW

**Comment by doofus-01** [comment]
The color-shift with for the dread-bat looks a bit cheap, but it is better than going back to vampire bat.  A replacement is on the to-do list.  The cuttlefish is an old portrait that someone on the forums suggested shouldn't go to waste, it probably is better than nothing.

**Comment by Gweddeoran** [comment]
I couldn't find the dread bat portrait, have you added it yet? I was wondering since you mentioned it in your comment here.

**Comment by doofus-01** [comment]
It's just the red bat with a color shift, see the Bat_Dread.cfg file.

**Comment by Gweddeoran** [comment]
Saw it a while after the comment. Oops. 😅

**Comment by Gweddeoran** [comment]
I just noticed the Direwolf Rider portrait. The wolf in that picture deosn't match the new Direwolf you made- could it be edited to match yours?

**Comment by doofus-01** [comment]
The Direwolf Rider portrait is also the Goblin Knight portrait, so maybe some day there could be a unique one.  But not in this PR, it should probably be its own topic.

**Pull request merged**
