### PR TITLE
SoF S9 - some cleanup to the final scenario

### PR DESCRIPTION
**Pull request by doofus-01**
- slight update to the map
 - multiple ways to get the orc to break his tablet

### CODE REVIEW

**Comment by Pentarctagon** [comment]
The WML schema validation is currently failing due to `Invalid key 'remove=' in tag [event]`.

**Comment by doofus-01** [comment]
Well, then something else needs cleanup.
https://wiki.wesnoth.org/EventWML#remove

**Comment by stevecotton** [comment]
/me self-assigns "deprecate [event]remove=yes in favor of [remove_event]"

**Comment by stevecotton** [comment]
The flashing glyphs around 27,20 are drawn on a layer above the units.

The bridges around 34,6 are very dark, it looks as if the orcs are floating in mid-air.

**Review by nemaara — APPROVED** [review]
As long as the code runs this change seems fine.

**Pull request merged**
