### PR TITLE
Reevaluate [show_if] conditions and delayed variable expansions before displaying objectives at start.

### LINKED ISSUE #3544: [show_if] is not correctly evaluated when objectives are shown on start
I'm playing Wesnoth 1.14.4 on Windows 10

To reproduce:
1) Copy the following lines in any scenario (like the "Caves of the Basilisk")
 ```
   [event]
        name=prestart
        
        [objectives]
            side=1
            [objective]
                description="Say hello to my little friend"
                condition=win
                [show_if]
                    [have_unit]
                        id=LittleFriend
                    [/have_unit]
                [/show_if]
            [/objective]
            [objective]
                description="No little friend here"
                condition=win
                [show_if]
                    [not]
                        [have_unit]
                            id=LittleFriend
                        [/have_unit]
                    [/not]
                [/show_if]
            [/objective]
        [/objectives]
    [/event]
    
    [event]
        name=start
        
        [unit]
            side=1
            placement=leader
            type=Fire Dragon
            id=LittleFriend
            name= _ "My little friend"
        [/unit]
    [/event]
```
2) Start a game in the chosen scenario
3) Pay attention to the objectives when they are shown for the first time

You'll see "No little friend here" even though the dragon is on the map. If you re-open the objectives dialog (`ctrl + J` or via the menu) you'll see the the correct sentence

### PR DESCRIPTION
**Pull request by jostephd**
Fixes #3544.

Is this a good approach?

### CODE REVIEW

**Comment by GregoryLundberg** [comment]
Looks good to me. Have the OP test that it solves the specific issue with SoF he ran across.

**Comment by sevu** [comment]
Can confirm it solves the issues discussed in #3537

**Comment by GregoryLundberg** [comment]
This will need porting to master as well.

**Comment by jostephd** [comment]
Thank you both for testing and merging. I added this PR to my Fwdport bug (#3514).

**Pull request merged**
