### PR TITLE
Chrono type refactor

### PR DESCRIPTION
**Pull request by Vultraz**
Initially, this was just going to affect events::pump_monitor, but in order to convert that, I had to convert the places using pump_monitor::ticks(), and it spiraled out from there.

In terms of behavior, everything should be the same, save that pump_monitor::ticks() now records a steady_clock value when created instead of being lazily initialized on first call.

### CODE REVIEW

**Comment by soliton-** [comment]
If there is no convincing motivation for the protocol changes then this should not be merged.

**Comment by Vultraz** [comment]
What protocol changes? The API is the same.

**Comment by Vultraz** [comment]
@soliton- addressed the issues with the timestamp resolution. It should now be seconds as before.

**Comment by ProditorMagnus** [comment]
Reported as performance issue https://forums.wesnoth.org/viewtopic.php?p=703366#p703366

**Pull request merged**
