### PR TITLE
make "modern" the default theme and rename "default" -> "classic"

### PR DESCRIPTION
**Pull request by babaissarkar**
Makes _Modern_ the initial theme (it will be used when no theme is set by preferences).
The previous theme (now called _Classic_) still exists and can be used by **Preferences -> Display -> UI Theme**.
Additionally, some more small reorganization has been done:
* the default theme is now named **Classic** (id is still *default*, otherwise the dialog/widget fallback mechanism won't work)
* more folder rename: *default* -> *classic*, *window* -> *dialogs*, *widget* -> *widgets*.

### CODE REVIEW

**Comment by gfgtdf** [comment]
can you maybe post screenshots  of before and after? Also how does this effect umc code that uses custom gui2  dialogs?

**Comment by Wedge009** [comment]
May be a bit late to change it now, but I wonder if there's a better name than 'modern'. Everything that's 'modern' eventually becomes old and the next 'classic'.

**Comment by babaissarkar** [comment]
> can you maybe post screenshots of before and after? Also how does this effect umc code that uses custom gui2 dialogs?

**Before:**
Screenshot from 2024-07-17 11-03-45

**After:**
Screenshot from 2024-07-17 11-03-29
(background is random, the current list is some of the story arts from TRoW)

The question is a bit invalid, because you can switch between the two themes using the preferences dialogs, and it respects your preferences.

For details, see #8953 

> Also how does this effect umc code that uses custom gui2 dialogs?
It doesn't ATM, because the theme doesn't contain definitions for those dialogs. For a dialog to be affected, there has to be a corresponding definition inside modern. It only redefines the titlescreen now. WoCPedia, for example, is not affected.

> May be a bit late to change it now, but I wonder if there's a better name than 'modern'. Everything that's 'modern' eventually becomes old and the next 'classic'.

Sure, I was thinking of the same thing. @Dalas121 you have any thoughts?
IMO
* the old one/classic -> "Parchment" (or something similar brown based)
* the new one/modern -> "Celestial/Ciel/Celeste/Celestum" (something related to sky)

**Comment by Discontinuum** [comment]
To be honest, I don't like how the new title screen is looking. I've discussed it with several people, the main concern is that menu items "Campaign", "Multiplayer", etc are made semi-transparent and are very hard to read. They melt into background. The difference in size, when the first three options are bigger than the others, doesn't look aesthetically appealing to me.

People I talked to also are very fond of the map of Wesnoth in the title screen, but that's probably a matter of taste

**Comment by babaissarkar** [comment]
> To be honest, I don't like how the new title screen is looking. I've discussed it with several people, the main concern is that menu items "Campaign", "Multiplayer", etc are made semi-transparent and are very hard to read. They melt into background. The difference in size, when the first three options are bigger than the others, doesn't look aesthetically appealing to me.

That's a valid concern, does these ones look any better?
https://github.com/wesnoth/wesnoth/issues/4531#issuecomment-2145914601

The first three were simply made bigger just to show that they have slightly more importance, but making them normal size isn't too hard.
Quoting from https://github.com/wesnoth/wesnoth/issues/4531#issue-515790200:
> The (functionally) most important elements also need to be the largest and stand out the most in the design.

> People I talked to also are very fond of the map of Wesnoth in the title screen, but that's probably a matter of taste

The classic theme still exists. There's also the possibility of commissioning backgrounds especially suited to the title screen (#8591).

**Comment by knyghtmare** [comment]
> That's a valid concern, do these ones look any better?
https://github.com/wesnoth/wesnoth/issues/4531#issuecomment-2145914601
I personally also thought that the buttons have too low contrast against the story backgrounds.

I like the third one of these, which lays a dark vertical bar behind the menu items and I can read the menu item texts clearly. 
Also, I can pick my preferred background image, right?

> The previous theme (now called Classic) still exists and can be used by Preferences -> Display -> UI Theme.

> (For those worried about the old theme: It still exists and can be changed to by Preferences -> Display -> UI Theme -> Classic -> Restart Wesnoth, and is exactly the same except for the drop caps in tips.)

I think keeping the classic theme supported for the sake of the existing community (and this Main Menu appreciators) would be the best course of action. True, you will face some additional maintenance (maybe not that much, just a little), but for a wonderful game like BfW, i would say that's worth it.

**Comment by babaissarkar** [comment]
> Also, I can pick my preferred background image, right?

I plan to add a preference for that, but for now you can just modify the `game_config.cfg`.
https://github.com/wesnoth/wesnoth/blob/0f188acc9f2b4f6e36e9dfbcbe22db677cae8e9f/data/game_config.cfg#L64

**Comment by MechanicalDragon963** [comment]
I'm not opposed to UI upgrades in general, but I think the current version of the “modern” theme needs improvements before it becomes the default theme. 

I agree with the problems listed above, and I would like to add one thing: in the current UI all buttons are made in the same style, it looks harmonious and sets the overall style of the game. In the presented model of the new UI, the menu buttons and the tooltip window are in different styles; also, the menu buttons differ in size. In my opinion, this creates disharmony. I think that the new interface should also be entirely consistent with the chosen style.

And yes, the lettering is really hard to read now, I'm speaking as a visually impaired person.

**Comment by Wedge009** [comment]
> The... distinction was intentional, since the main menu buttons are the game's most important buttons...

This intent was what I understood, I didn't consider it as disharmonious at all.

**Comment by gfgtdf** [comment]
> can you maybe post screenshots of before and after?

okay so just to bw sure: this only effects the titlescreen, and for things not present in the "modern" theme falls back to the current design ?

**Comment by babaissarkar** [comment]
> okay so just to bw sure: this only effects the titlescreen, and for things not present in the "modern" theme falls back to the current design ?

Yes.

**Comment by MechanicalDragon963** [comment]
> I'll think on how it can be made more consistent. The main menu button (banner style) vs tooltip window/language/about (normal buttons) distinction was intentional, since the main menu buttons are the game's most important buttons and serve as entry points, so I think they deserve some special treatment.

I think it's worth thinking about what elements create the current UI design, and trying to create a new one based on them. 

In my opinion the following things define the current style of Wesnot:

- dark semi-transparent background for button areas;
- blue color of the buttons themselves;
- gold colored stroke around the buttons; the same color of text;
- font. 

I'd like the new design to retain these qualities in one way or another (perhaps in a modified form). Perhaps it is worth keeping at least the UI color scheme for the sake of continuity. 


I also have doubts about the Oldania font for the buttons. It's a beautiful font, but it needs a stroke, but with it it looks weird on small buttons and is hard to read.

**Comment by Vultraz** [comment]
I'm in favor of a single unified sidebar instead of the individual buttons. It would be visually cleaner.

Just to clarify though, the current revision is definitely open to further improvements (and I want to commend @babaissarkar for their fantastic work so far). I advocated for merging it as-is to get it in front of as many eyes as possible. To that end, I'm in favor of making it the default as we continue to refine the new design.

**Comment by Dalas121** [comment]
> I also have doubts about the Oldania font for the buttons.

> I'm in favor of a single unified sidebar instead of the individual buttons. It would be visually cleaner.

Here's a modified version of the sidebar in #4531, with regular Lato instead of the Oldania font, if you're curious what it would look like.

main-menu

**Comment by MechanicalDragon963** [comment]
> > I also have doubts about the Oldania font for the buttons.
> 
> > I'm in favor of a single unified sidebar instead of the individual buttons. It would be visually cleaner.
> 
> Here's a new version of the sidebar mockup in #4531, revised to use regular Lato instead of the Oldania font, if you're curious what it would look like.
> 
> main-menu

I like this version much better. Although the caption on the column raises some doubts. It's also great that the language and path information are now in one area. 

I wonder what this layout would look like with a tooltip window?

**Comment by babaissarkar** [comment]
@MechanicalDragon963 
> Although the caption on the column raises some doubts.

By "caption" you mean the wesnoth logo, or is it something else?

@gfgtdf 
Let me clarify my previous answer. The currently active theme can affect UI dialogs inside UMC content (since it is global), as long as the custom dialog uses a widget/window definition from wesnoth's currently active theme. For example, if I modify the "default" button definition in "modern" and modern is active, then all buttons globally that use "default" definition get affected. Screenshot of WoCPedia with button definition "default" modified in modern, modern active (look at the Close button):
Screenshot from 2024-07-19 09-28-54

**Comment by Vultraz** [comment]
I uhhhhh somehow edited your comment while trying to add a new one. I’m sorry. Legitimately do not know how I managed to do that.

**Comment by Wedge009** [comment]
Attempted to fix the accidental edits.

**Comment by CelticMinstrel** [comment]
> So there's a very low chance of a mainline theme affecting the window layout of a UMC dialog, but much higher chance of widget appearances getting changed.

Layout could change a little, especially if a compound widget definition was modified, such as the unit preview pane. It wouldn't change that much though, I don't think. (Though it depends on the extent of the modification.)

> How would the column layout look with only the logo, no “BfW” text? I think that would make it much cleaner. People know what game they’re playing.

I kinda disagree on this. It's true that people know the game they're playing, but how many games actually leave their logo off the title screen?

But it doesn't necessarily have to be in its current location. The top right may work, for example.

**Comment by Pentarctagon** [comment]
Is there anything remaining for this PR aside from resolving the conflicts?

**Comment by babaissarkar** [comment]
> Is there anything remaining for this PR aside from resolving the conflicts?

I was planning to redo the titlescreen following: main-menu4 [Dalas's new design]. Should that be done here or in another PR?

In case that is to be done on another PR, I can try to address the concerns raised within the constraints of the current modern theme. (for example: increase the constrast in main menu buttons)

**Comment by Pentarctagon** [comment]
Yeah, that's what I was wondering - it seemed strange to add a bunch of UI/UX changes to a PR that's supposed to just be changing the default and renaming/moving a bunch of files.

**Comment by Dalas121** [comment]
The current UI mockup. Posting here to get some visibility and feedback before Lumin/Bab makes the changes (probably in a different PR).

lightblue
<details>
  <summary>Old design iterations</summary>
thick
delicate
</details>

**Comment by DuncanusDillius** [comment]
I agree with forestdragon, it is a bit harsh on the eyes. Navy would be much nicer. Also, it might be nice to change the opacity to be a bit fainter, but that's just personal preference.

**Comment by Dalas121** [comment]
New version, using the current wesnoth UI blue and slight opacity.

main-menu

**Comment by Vultraz** [comment]
I agree with ForestDragon - definitely keep it the darker background. I also think the semi-transparent looks better than the opaque.

**Comment by Dalas121** [comment]
Any preference between the different buttons, checkboxes, and radios?

**Comment by Dalas121** [comment]
Samples showing how this would look with various backgrounds:
main-menu1
main-menu2
main-menu3
main-menu4
main-menu5
main-menu6

**Comment by Vultraz** [comment]
> New version, using the current wesnoth UI blue and slight opacity.

That looks fantastic 😃 As for the checkboxes and radioboxes, they're a bit too ornate, I think.

**Comment by Dalas121** [comment]
From Emperor/ZombieKnight on discord: _"Nice, much better. Those checkboxes and other options are too golden"_

New version, with reduced ornamentation and less gold:
main-menu

**Comment by white-haired-uncle** [comment]
> Any preference between the different buttons, checkboxes, and radios?

I'm not a fan of the checkboxes, too ornate for my taste.  The six on the bottom, in particular the three on the left, kind of bleed together.  If you want ornate, I'm wondering if round would be preferable to 90/45 degree corners.

I don't like the corners on the rectangular buttons.  I think they need to be accompanied by a gold button border like the End Turn button if you're going to do ornate corners.

The preferences menu should not be more or less opaque than the New Campaign/etc menu.  I know I said try def=menu and all, but that was just to see if it made a difference.  It's not so bad with the map in the bg, but with the others it doesn't look right to me.

The motd is a bit too integrated into the New Campaigns dialog.  That's about the best I can describe.  For example, it's not perfectly clear that the Help button (which perhaps should be over with the version/language buttons?) is not part of the motd.  Maybe just moving motd and its buttons up a little and giving them a bit of a border.

Oh, and the backgrounds are all pretty cool.  They should be a slideshow.

With all that out of the way, outstanding work!  Please don't think that just because I only mentioned what I don't like that I'm not a huge fan of what you have here.

**Comment by babaissarkar** [comment]
I personally do like the previous ones, but disagree with the last one. It's too dull and boring, and can't be consider better that the classic theme.

Upon closer look, I think I agree that the ornamentation on the checkbox/radios were too much. My preference is a simple square for the checkbox and a simple circle within rhombus design for the radio. However, please don't remove the top filigree.

**Comment by babaissarkar** [comment]
> move the help tips to the loading screen

small problem: not enough time for reading them. I do agree that it's a good idea however, another game I play also does that. (But it's a multiplayer battle type game, so naturally there's a lot of time to read that stuff).

**Comment by white-haired-uncle** [comment]
The more I think about it, the more I like the slideshow bg idea.  Probably with fade out/in, and either rotating between calm and intense (dude sitting under tree), or in a narrative sequence.

Also, perhaps a slideshow for tips instead of buttons.  Give each 15 or 20 seconds.  That keeps the tips, but sort of de-emphasizes them, IMO.

**Comment by Vultraz** [comment]
The slideshow is an interesting idea, but I don't think it makes for good design. We're still in need of a proper background for the main menu. Reusing the existing images (few as they are) is a good stopgap measure for now, but keeping them around (and making them a slideshow) would serve to make the game look cheap and underdeveloped. There's no real synergy besides "cool fantasy image" because they're either literally that - a generic fantasy image - or designed very specifically for TROW.

**Comment by hladkyjakub** [comment]
I'd just like to point out those golden checkboxes and other options stuff.
IMHO it's really golden, which doesn't really fit to the dark blue theme.

**Comment by Dalas121** [comment]
> white-haired-uncle: The preferences menu should not be more or less opaque than the New Campaign/etc menu.

Fixed

> babaissarkar: However, please don't remove the top filigree.

Agreed

> white-haired-uncle:I'm not a fan of the checkboxes, too ornate for my taste.
> white-haired-uncle:I don't like the corners on the rectangular buttons. I think they need to be accompanied by a gold button border like the End Turn button if you're going to do ornate corners.

How do you feel about this design?

main-menu

> Vultraz: Idea - move the help tips to the loading screen. I agree they shouldn't be stuffed in the sidebar like this, and honestly for a really clean design we could do without them.

> white-haired-uncle: small problem: not enough time for reading them. I do agree that it's a good idea however, another game I play also does that.

I've removed them from the mockup so we can see how it looks.  When other games have tips on loading screens, I've seen them have the loading screen wait for a keypress to continue (with an option to disable this), so the player can take as long as they want to read tips. Not sure if that makes sense for a game with loading times as short as Wesnoth though.

**Comment by hladkyjakub** [comment]
Neet :D
would be a big problem to hide those triangles at top and bottom of the listbox?

**Comment by white-haired-uncle** [comment]
It looks like you standardized opacity by making the New Camp dialog less opaque.  I probably would have gone the other way around (depending on bg ofc).

**Comment by Dalas121** [comment]
Removed listbox triangles, and reduced dialog opacity. Several backgrounds for reference:

main-menu1
main-menu2
main-menu3
main-menu4

**Comment by babaissarkar** [comment]
1. Checkboxes/Radios: Now with the darkened colors, they are not really much visible. Maybe thicker borders will help?
2. Background: Still too dark. I won't say make it blue as the sky, but make it a bit less dull, please.

**Comment by Vultraz** [comment]
Honestly, I don't mind the background color. I say we stick with it.

**Comment by babaissarkar** [comment]
> Honestly, I don't mind the background color. I say we stick with it.

I mind, however. If it is too dull for me, then I simply won't implement it. Somebody else can, however.

**Comment by ForestDragon-wesnoth** [comment]
> Samples showing how this would look with various backgrounds: main-menu1 main-menu2 main-menu3 main-menu4 main-menu5 main-menu6

out of the shown backgrounds I prefer the map one. makes it look like a gradual UI evolution as it should be (like how UI gradually changed between 1.10-1.14 while mostly keeping the original theme) instead of a drastic change

**Comment by white-haired-uncle** [comment]
Let the user pick the background?

Oh, and where is my logo-faced troll?

**Comment by Vultraz** [comment]
@babaissarkar the version in your edit (the "I still prefer" one) also works.

**Comment by Dalas121** [comment]
New version, with lighter colors, thicker lines, shadows under checkboxes/radios to improve visibility, and main menu background.

main-menu

**Comment by ForestDragon-wesnoth** [comment]
> How do you feel about this design?
> 
> main-menu

So far this is probably by favorite out of the proposed new UI designs (besides the background image, I am still personally in favor of keeping the map)

**Comment by amakriLexa04** [comment]
> From Emperor/ZombieKnight on discord: _"Nice, much better. Those checkboxes and other options are too golden"_
> 
> New version, with reduced ornamentation and less gold: main-menu

It looks good, but please make size of the main menu buttons the same, because they are a bit hard to read. 
Also, the help tips will definitely look extremely small, it's clearly noticeably even on the mockup. Better to leave help tips as they are, or as Vultraz suggested, move them to the loading screen

**Comment by babaissarkar** [comment]
> please make size of the main menu buttons the same, because they are a bit hard to read.

They can be made proportionally bigger, but the current design uses visual hierarchy, so it automatically shows that "Campaign"/"Multiplayer" has more importance. This was one of the points of the original issue #4531.

**Comment by Dalas121** [comment]
On discord, Sire says: 
_"Make an option for transparency for menus? This way players can choose what level of transparency they desire, or if they prefer a simple solid color.

Also, allow players to choose the background (or keep it random).
-- For reference, see Starcraft II.
Otherwise, it looks good enough to me."_


New version, with larger text, tweaked radio buttons, and click/hover buttons.

main-menu

**Comment by white-haired-uncle** [comment]
Is Campaign/Multiplayer more important than Load Game (and Quit)?  I'd put Load/Quit at the top of my list (most used, not literally the top of the menu), with multiplayer somewhere near Achievements (these could be in a submenu, "Stuff I never Use").

**Comment by irydacea** [comment]
While impressive, the visually-connected radio button design kind of forces you to lay them out vertically and without any elements in between, which is a negative point for general use. I also feel it forcefully draws the readers attention into the radio buttons in places where they shouldn't be the single thing being focussed on such as the Preferences dialog.

**Comment by irydacea** [comment]
> The slideshow is an interesting idea, but I don't think it makes for good design. We're still in need of a proper background for the main menu. Reusing the existing images (few as they are) is a good stopgap measure for now, but keeping them around (and making them a slideshow) would serve to make the game look cheap and underdeveloped.

I tend to disagree here. Looking at the mockups I could see the TRoW story illustrations working just fine in a slideshow where they fade between each other and maybe have some kind of focal zooming effect. Imagine if we could even animate the smoke and fire in the illustrations and just turn the whole thing into a high-res video background rather than render it all crudely in code! Of course, this idea would benefit from having high-res illustrations for every single mainline campaign, maybe then every time the main menu is shown the game would display a different sequence from a different campaign.

**Comment by Dalas121** [comment]
> Is Campaign/Multiplayer more important than Load Game (and Quit)? I'd put Load/Quit at the top of my list (most used, not literally the top of the menu), with multiplayer somewhere near Achievements (these could be in a submenu, "Stuff I never Use").
> 
> Unless perhaps in your example you have no saved games, and that's why "Load Game" is smaller? That makes sense.
> 
> Mods and Add-ons sort of seems like it diminishes the value of UMC, particularly for those of us who don't play mainline.

Load game and quit are definitely the most-used buttons on the menu (though I'd guess many use hotkeys instead), but I think having "New Campaign" be big and on top helps give new players a clear starting point.

That said, we probably don't want a new player opening up with multiplayer, so perhaps I should replace that with a "Game Manual" or "Encyclopedia" button leading to the help menu?

> While impressive, the visually-connected radio button design kind of forces you to lay them out vertically and without any elements in between, which is a negative point for general use. I also feel it forcefully draws the readers attention into the radio buttons in places where they shouldn't be the single thing being focussed on such as the Preferences dialog.

New version, with a possible alternative radio button that's less sensitive to being split apart (might be even more attention-catching unfortunately though):
main-menu

**Comment by Dalas121** [comment]
> possible alternative radio button that's less sensitive to being split apart (might be even more attention-catching unfortunately though)

Actually, I think the rhomboids should work fine while split apart. Here's a sample, with the amount of gold reduce to try and reduce their attention-grabby-ness:

**Comment by Vultraz** [comment]
> > The slideshow is an interesting idea, but I don't think it makes for good design. We're still in need of a proper background for the main menu. Reusing the existing images (few as they are) is a good stopgap measure for now, but keeping them around (and making them a slideshow) would serve to make the game look cheap and underdeveloped.
> 
> I tend to disagree here. Looking at the mockups I could see the TRoW story illustrations working just fine in a slideshow where they fade between each other and maybe have some kind of focal zooming effect. Imagine if we could even animate the smoke and fire in the illustrations and just turn the whole thing into a high-res video background rather than render it all crudely in code! Of course, this idea would benefit from having high-res illustrations for every single mainline campaign, maybe then every time the main menu is shown the game would display a different sequence from a different campaign.

Now that would look amazing. Animated backgrounds would go hard.

@Dalas121 couple more suggestions:
* No BfW text, only the logo
* Buttons vertically centered in space
* Shrink the width of the bar slightly
* Just "Multiplayer" instead of "Play Multiplayer"
* Remove Credits
* I also do think having them the same size would be better, but I'm not especially wedded to either way

**Comment by ForestDragon-wesnoth** [comment]
> New version, with a possible alternative radio button that's less sensitive to being split apart (might be even more attention-

Load game looks too small considering how important the button is

also personally I prefer the old shorter "campaign"/"multiplayer" text over "New Campaign" "Play Multiplayer"

**Comment by ForestDragon-wesnoth** [comment]
I also agree with amakri in preferring more similar/same text sizes for the option

**Comment by Dalas121** [comment]
New version, with only the BfW logo, buttons centered vertically, sidebar narrowed a little, credits removed, "New Campaign"/"Play Multiplayer" shortened to "Campaign"/"Multiplayer", and all text made the same side.

Hejenwar and Jotender from the discord proposed putting the sidebar on the right instead of the left, which I've done as well so we can see how it looks:

main-menu

**Comment by Vultraz** [comment]
Looks great!

**Comment by amakriLexa04** [comment]
I still prefer the sidebar on the left, I don't know why, but it just looks better to me.
I don't think that just logo without a name is the best idea. Not only does it throw away the work of a bunch of people who translated the name, but it would also be wrong not to have the name of the game in the main menu. 
Also, the vertical distances between the buttons seem too large.
I wonder how this exact menu would look with a different background, because with map it looks odd and a bit outdated

**Comment by ForestDragon-wesnoth** [comment]
> I don't think that just logo without a name is the best idea. Not only does it throw away the work of a bunch of people who translated the name, but it would also be wrong not to have the name of the game in the main menu.

Agreed, I firmly believe that the name must stay

**Comment by ForestDragon-wesnoth** [comment]
>     * Remove Credits

Why? Shouldn't it be easy to see who contributed to wesnoth's development?

**Comment by ForestDragon-wesnoth** [comment]
> New version, with only the BfW logo, buttons centered vertically, sidebar narrowed a little, credits removed, "New Campaign"/"Play Multiplayer" shortened to "Campaign"/"Multiplayer", and all text made the same side.

text looks much better now (besides the issues mentioned above)

**Comment by Vultraz** [comment]
> > ```
> > * Remove Credits
> > ```
> 
> Why? Shouldn't it be easy to see who contributed to wesnoth's development?

It’s not important enough to have on the main menu. The first thing the player sees should be the most essential options (Achievements should probably be rolled into Campaigns for the same reason).

**Comment by Pentarctagon** [comment]
You can have non-campaign achievements though.

**Comment by Dalas121** [comment]
Restored "Credits" button, reduced space between buttons, re-added words to logo, and used backgrounds instead of map.

I have no strong opinion on right-side or left-side sidebar, so either is fine by me.  LumiousE will probably make the final call regardless.

main-menu1
main-menu2
main-menu3
main-menu4
main-menu5
main-menu6

**Comment by amakriLexa04** [comment]
It looks very good👍, although the logo should probably be a bit bigger

**Comment by white-haired-uncle** [comment]
Maybe off-topic, but I wonder if something could be done to improve the 'A' in "Fichievements" and "Fiddons"

**Comment by Wedge009** [comment]
> ...I wonder if something could be done to improve the 'A'...

That's the font - I don't see it as an 'F' but clearly that's not the case for everyone.

**Comment by CelticMinstrel** [comment]
> It’s not important enough to have on the main menu.

Yes it is. There isn't any other logical place to put it. Don't remove credits from the main menu.

**Comment by Vultraz** [comment]
Is there no area over which I have the authority to make a design decision? Because at this point, it’s starting to feel like my ideas carry absolutely zero weight.

**Comment by babaissarkar** [comment]
> Is there no area over which I have the authority to make a design decision? Because at this point, it’s starting to feel like my ideas carry absolutely zero weight.

@Vultraz will replacing Credits with About work? Or do you want it to stay as the "About" button?
(Considering I already removed Credits from the main menu and moved it inside the About button).

**Comment by Pentarctagon** [comment]
> Yes it is. There isn't any other logical place to put it. Don't remove credits from the main menu.

Of course there are. It doesn't need to be on the main menu.

**Comment by babaissarkar** [comment]
> people are free to state their opinions though.

Yes, I was literally in the same state a couple of comments ago.

**Comment by Wedge009** [comment]
Looks like this has turned into a full-blown discussion instead of just an enablement of the theme redesign...

> I still prefer the sidebar on the left, I don't know why, but it just looks better to me.

> I have no strong opinion on right-side or left-side sidebar, so either is fine by me.

I recognise the current (up to 1.18) design has the menu as a stack of buttons on the right. With this redesign into a full column, I think I would also prefer it on the left. If it's not too difficult, would it be reasonable to make this a user preference? Before anyone remarks that we shouldn't allow user configuration without good reason, my thinking is that such an option might be good for those using RTL-based languages.

**Comment by Wedge009** [comment]
Regarding credits placement - I don't have a super-strong opinion though I do lean towards not including it in the main menu. I feel like it's a convention - if credits are present at all - to put it in an About dialogue such as what Audacity does:
image

On the other hand, Endless Sky chose to show their credits in an auto-scrolling dialogue on the title screen:
image

**Comment by babaissarkar** [comment]
I'll open this as a new PR later with the proposed new theme changes by @Dalas121. Thanks for the feedback!

**Pull request closed without merging**
