### PR TITLE
Wrap SDL_RWops* in std::unique_ptr

### PR DESCRIPTION
**Pull request by AI0867**

### CODE REVIEW

**Comment by gfgtdf** [comment]
I wonder whether we still need our custom RW_ops in the first place? Iirc correctly the reason why we added them was an issue that sdl1 (in particular sdl_mixer) didn't support unicode, whihc might be fixed with sdl

**Comment by CelticMinstrel** [comment]
I thought they were needed so we can get SDL to read from C++ streams?

**Comment by AI0867** [comment]
Well, they only needed to read from our own streams because SDL1 had terrible (absent) Unicode filename handling. SDL2 has improved a lot of things, though I don't know if it improved this bit.

**Comment by gfgtdf** [comment]
So me it looks like, at least or sdl_mixer it's fixes in https://github.com/bminor/SDL_mixer/commit/6be5e86fdf621dbb8ef949561aa4ecb190527bcc#diff-58b8bb5891c4da364bb04a303345f926 , wihc removed the fopen calls and replaces it with proper RWops.

**Comment by Vultraz** [comment]
If we don't need the custom RWops can someone remove them.

**Comment by gfgtdf** [comment]
On the other hand, using a custom rwops  gives os also other oütions, fo example we can make it use our custom error reporting function (ERR_FS, DBG_FS ...) or we coulod make it accept relertie paths like "~addons/my_addon/my_file.png"

**Comment by CelticMinstrel** [comment]
What are the RWops used for again? Reading images, I guess? Personally I think it makes a lot of sense to be using C++ streams consistently here, but... I suppose it may not technically be necessary...

**Comment by AI0867** [comment]
Images, music, sound and fonts. Music requires seeking.

I've also noticed an attempt to use RWops for saving images, but I never implemented the write function. I could do that if we want.

**Comment by CelticMinstrel** [comment]
I personally think it's worth implementing the write function, mainly for completeness.

**Comment by jyrkive** [comment]
@CelticMinstrel IMO, that write function is out of scope for this pull request.

I'm merging the PR. @AI0867 can create a separate PR for the write function.

**Pull request merged**
