### PR TITLE
[harm_unit] fix secondary_attack animation

### PR DESCRIPTION
**Pull request by virtualghetto**
Discussed on the forum.
https://forums.wesnoth.org/viewtopic.php?f=4&t=53620

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Yeah… this seems fine. It's not my preferred fix, but if it works, it works, I guess…

**Comment by virtualghetto** [comment]
Oops, closed this by mistake :/

**Comment by Pentarctagon** [comment]
@CelticMinstrel What would be the preferred fix?

**Comment by CelticMinstrel** [comment]
I would prefer to update it to directly use the `wesnoth.create_animator` API instead of calling it indirectly via another WML tag.

**Comment by Pentarctagon** [comment]
@CelticMinstrel should this be merged or closed?

**Comment by CelticMinstrel** [comment]
I think fixing the bug takes priority over doing it properly? We can rewrite it to use `create_animator` at some later time.

**Pull request merged**
