### PR TITLE
Preprocessor: Add {LEFT_CURLY} and {RIGHT_CURLY} escape sequences

### PR DESCRIPTION
**Pull request by jostephd**
See #4414

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Though I think I'd prefer the names `{LEFT_BRACE}` and `{RIGHT_BRACE}`. Or if it's easy, maybe even support `{[}` and `{]}`.

**Comment by stevecotton** [comment]
+1 for `{LEFT_BRACE}` and `{RIGHT_BRACE}`

I don't like `{[}`, it would be a pain to grep through the source code for.

**Comment by jostephd** [comment]
Adding two lines of code for this seems worthwhile to me.

**Comment by CelticMinstrel** [comment]
I feel like there could still be use-cases for this, though I'm not quite sure what they'd be... and it doesn't hurt to have two ways of doing the same thing.

Incidentally, I also just [added a note](https://wiki.wesnoth.org/index.php?title=SyntaxWML&curid=1528&diff=64695&oldid=61135) on the wiki about the support for `key=_<<>>`.

**Comment by ProditorMagnus** [comment]
These are not documented yet.

**Comment by jostephd** [comment]
Thanks, fixed. I _thought_ I'd forgotten something when I did yesterday's batch of merges...

**Comment by ProditorMagnus** [comment]
Normal macro would evaluate
`message="{LEFT_BRACE}"` -> 
`message="{"` ->
error missing }. 

If c++ implementation stops further processing of that token it should be explained in wiki.

**Pull request merged**
