### PR TITLE
Add a "Teleport Unit (Debug!)" option to debug menu

### LINKED ISSUE #5649: Add a "Teleport Unit (Debug!)" option to debug menu
### Game and System Information
I'm on 1.14.16 downloaded from Steam for Mac.

### Describe the desired feature
Currently when enabling debug mode, it adds options to create units, kill units, and change unit side to the contextual menu (see screenshot below). It would be helpful if there were also an option to teleport an existing unit somewhere else to that menu in debug mode, to make it easier to test certain events that depend upon certain units triggering them. Using `unit moves=100` isn't as practical because there might be enemy units in the way, or impassable terrain. 

### Screenshots
Screen Shot 2021-03-31 at 02 04 51

### PR DESCRIPTION
**Pull request by Pentarctagon**
Code taken from #7961 by TheHitsy

Fixes #5649

### CODE REVIEW

**Review by cooljeanius — APPROVED** [review]
LGTM (pending CI passes)

**Comment by CelticMinstrel** [comment]
I think this commit should be amended to retain the original author information. I think something like the following should work on the command-line:

```bash
git commit --amend -author=$hash_of_one_of_the_original_commits
```

I'm not 100% sure though.

**Comment by Pentarctagon** [comment]
Oh, I didn't even know that was a thing you could do. I'll see if it works.

**Comment by Pentarctagon** [comment]
Mostly seems to work - the one issue is that teleporting a unit with no moves will trigger an OOS in the replay since the unit moved without having any movement points.

**Comment by CelticMinstrel** [comment]
That doesn't seem too terrible. It could probably be addressed and fixed, but it doesn't seem like a blocker to merging this.

**Comment by Pentarctagon** [comment]
Yep, no reason to check movement remaining for a debug teleport.

**Pull request merged**
