### PR TITLE
halo persistent and alternate soluce for Mage of light halo

### PR DESCRIPTION
**Pull request by newfrenchy83**
after ac.unit_halo_ = halo_man.add( 0, 0, u.image_halo()+u.TC_image_mods(), map_location(-1, -1));
paste halo_man. set_location (ac.unit_halo_, x, y - height_adjust); and halo bug resolve without artefact when 2 mage of light adjacent after move.

### CODE REVIEW

**Comment by Vultraz** [comment]
You still haven't explained why you reverted 0bc0681.

**Comment by newfrenchy83** [comment]
travis reject is logic alas, i am beginner in github, i just wanted propose an alternative a 0bc0681 but i modified advancement.cpp before my first request has can or not approved. I am sorry for my error.

**Comment by jyrkive** [comment]
If you want to propose an alternative, then please explain why your alternative is better. Code shouldn't be changed just for the sake of it.

**Comment by GregoryLundberg** [comment]
The purpose of commit messages is to explain the commit. "Update halo.cpp" as a commit message is about as meaningful as `a += 1 // Add 1 to a`

In general, a commit should be one idea. And the commit message should identify that idea. "Handle adjacent halo" or "Prevent halo interference" would be better commit messages. And, if several files need changing, put them all into one commit. The idea of commit messages is to make it easier, in the future, to see what was done to the code, why, and when and by whom.

**Comment by gfgtdf** [comment]
> The purpose of commit messages is to explain the commit. "Update halo.cpp" as a commit message is about as meaningful as a += 1 // Add 1 to a


While this is generally true, the author here obviosuy used github to update single files which creates a lot of non-working single commits which we won't allow in the main repoo anyways. So if we merge we have to use squash-and-merge ignoring the commits message and using the prs description as the commit mesage then.

**Comment by newfrenchy83** [comment]
put files into one commit, i like but i don't know doing now but i correct.

**Comment by newfrenchy83** [comment]
Ignore commitSep 11, 2017 please!, i use uploads files

**Comment by jyrkive** [comment]
@newfrenchy83 I committed the fix in 8a7aa49718aac264d1eacf7f95bc7774a8dd6db8.

You were right, reverting 0bc068113a9cb8a18f797e4aec29d280653b57d3 fixes the crossing halo issue. I looked closer, and found that removing the `unrender()` call from `halo_impl::effect::set_location()` is the only change necessary, so I committed that.

Thanks for the help! 👍 

Is there any other changes in this pull request you want to make to Wesnoth, or can we close it?

**Comment by newfrenchy83** [comment]
[advancement.cpp.txt](https://github.com/wesnoth/wesnoth/files/1293554/advancement.cpp.txt)
Linr 310 get_amla_unit
[game_lua_kernel.cpp.txt](https://github.com/wesnoth/wesnoth/files/1293558/game_lua_kernel.cpp.txt)
Line 2127 function erase_unit
[synced_commands.cpp.txt](https://github.com/wesnoth/wesnoth/files/1293565/synced_commands.cpp.txt)
Line 437 and 470-475

[udisplay.cpp.txt](https://github.com/wesnoth/wesnoth/files/1293575/udisplay.cpp.txt) line 572.
And 
[wml-tags.lua.txt](https://github.com/wesnoth/wesnoth/files/1293582/wml-tags.lua.txt)
Line 845-849
This is the modifications to resolve persitant halo when unit die, amla advance or unstored.
Can you test this? Thanks.

**Comment by jyrkive** [comment]
OK, I can look into your changes later this week.

One thing, though: none of your commits make changes to wml-tags.lua.

**Comment by newfrenchy83** [comment]
i forgot to commit the last file.

**Comment by newfrenchy83** [comment]
game_lua_kernel.cpp.txt line 2100

**Pull request closed without merging**
