### PR TITLE
AToTB: Add Maghre to bigmap

### PR DESCRIPTION
**Pull request by Gothyoba**
Edit: It seems I’ve accidently deleted the metadata. I will mark this as a draft until I solve that (probably tomorrow).

Adds Maghre to the AToTB big map. This is only small village, but in the context of the campaign it is quite important. It is the location Mordak terrorized at the start, the location of scenario 1, and the location of the final battle.

New map:

Maghre

Current Map:

NoMaghre

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Is this the correct way to edit a bigmap? It seems to me that there's probably something missing?

**Comment by Gothyoba** [comment]
> Is this the correct way to edit a bigmap? It seems to me that there's probably something missing?

Other than the metadata, I don’t think there is anything missing. The journey trackers should be identical. It works fine in-game. I’m not sure if copyrights.csv is still being used, but it seem not.

**Comment by Gothyoba** [comment]
Not working so I’ll close it. Very likely it will be working tomorrow, or the day after. For now, this is not in an acceptable state.

**Comment by CelticMinstrel** [comment]
> The only thing I can think of is issue with translations.

This is what I meant when I said it seemed like something is missing. I'm not very familiar with the process on that, however. As you mentioned, maybe it's a separate PR against [wesnoth/resources](https://github.com/wesnoth/resources)? Or maybe the assets are here in the main repository? I'm not sure.

**Comment by Gothyoba** [comment]
Localization files are in wesnoth/resources, so I would have to make a second PR in that repo which would have to be merged at the same time as the one on wesnoth/wesnoth. I don’t know of any assets in this repo related to big maps.

**Comment by Gothyoba** [comment]
I have now made the change on the flat version of the bigmap found in the localization files. However, I still need to figure out how to turn this into the final, rotated image.

Maghre_Flat

**Pull request closed without merging**
