### PR TITLE
Pathfind indexer

### PR DESCRIPTION
**Pull request by AI0867**

### CODE REVIEW

**Comment by Vultraz** [comment]
What exactly does this do?

**Comment by AI0867** [comment]
Refactor some things to make both coverity and @GregoryLundberg happy.

**Comment by GregoryLundberg** [comment]
Hey, you don't need to make me happy. I was just thinking it was some low-hanging fruit which would be easy to fix and turned out to have a couple worms. I'm fine with being told there's more to it than I saw and having my change backed out.

I would suggest, however, that this branch wait to post-1.14 so we don't inadvertently break pathfinding at this late stage.

**Comment by AI0867** [comment]
Well, what this PR does is change the `findroute_indexer` to throw when encountering invalid map locations, rather than return `-1`, which could cause problems.
To do this, the one case where this is expected to happend (the check-adjacent-hexes step), is changed to remove the off-map hexes early, after optionally adding them to the `edges` vector.

In addition, the `findroute_indexer` now returns unsigned.

**Comment by GregoryLundberg** [comment]
Code-read looks good.

Rebased to current master and compiled no errors in several forms.

Quick tests and no obvious breakage.

As far as I'm concerned this should merge. It's better than what was there and if it does not quell Coverity, it's a better starting point.

**Pull request merged**
