### PR TITLE
mp_staging: Build all teams, not only those that have a side assigned to them (#3849)

### PR DESCRIPTION
**Pull request by jostephd**
I just moved the team initialization to another function and made it initialize all teams, not only those that some side was on.

### CODE REVIEW

**Comment by gfgtdf** [comment]
so does it now show empty teamsin the mp connect screen, or itjust an internal refctor without visible changes?

**Comment by jostephd** [comment]
It fixes a null pointer dereference (#3849).

**Comment by gfgtdf** [comment]
Yes, but does only do that or does it also change the UI of the month connect dialog by showing empty teams.

**Comment by jostephd** [comment]
It does show empty teams now.

**Comment by gfgtdf** [comment]
hmm thatsounds ui wise a step bakwards to me (in particular when uncheck the usemapsettings checkbox), Maybe you could hide unused teams (`widget::set_visible(invisible)`)

**Comment by jostephd** [comment]
I'll look into that. If I don't sort it out before string freeze, I'll merge as is and leave the UI step backwards to be fixed in 1.14.7.

**Comment by jostephd** [comment]
Okay, not merging. What _would_ be the right fix?

**Comment by jostephd** [comment]
@Vultraz ping

**Comment by Vultraz** [comment]
I don't actually know what the right fix is. I thought I did, but it wasn't it.

**Comment by jostephd** [comment]
Vultraz said on discord he thought a commit wasn't backported. If we find that commit we can backport it. In the meantime, merged this as is to fix the crash. @gfgtdf I looked into setting invisibility but couldn't get it to work.

**Comment by jostephd** [comment]
Merged.

**Pull request closed without merging**
