### PR TITLE
update_copyrights - improve performance a lot

### PR DESCRIPTION
**Pull request by Pentarctagon**

### CODE REVIEW

**Comment by Wedge009** [comment]
I haven't looked at this in detail, but wondering what the performance change was. Is it that you're comparing hashes now instead of meta-data?

**Comment by ProditorMagnus** [comment]
What is the reason for looking file size?

**Comment by Pentarctagon** [comment]
@Wedge009 yeah, apparently looking up the most recent commit information via `git log` is incredibly slow.

@ProditorMagnus checking file size is even faster than getting the hash.

**Review by cooljeanius — APPROVED** [review]

**Comment by ProditorMagnus** [comment]
>             size = str(os.path.getsize(file))
>             hash = do_hash(file)
You get hash no matter what size says.

**Comment by Pentarctagon** [comment]
True.

**Comment by cooljeanius** [comment]
> > ```
> >         size = str(os.path.getsize(file))
> >         hash = do_hash(file)
> > ```
> 
> You get hash no matter what size says. But size collision feels so rare case that I did not feel need to point that out yesterday to separately check them.
> size=, hash= -> often
> size!=, hash!= -> happens
> size=, hash!= -> very rare, no need to optimize for it
> size!=, hash= -> extremely rare

So, I started using the `./update_copyrights` script from this PR with the "Size" field before this feedback led to that field being removed, so now my `copyrights.csv` file has problems with it leading to cooljeanius/wesnoth#104... how do I fix it?

**Comment by Pentarctagon** [comment]
What are you using it for?

**Comment by ProditorMagnus** [comment]
Replace it with current version.

**Comment by cooljeanius** [comment]
> Replace it with current version.

I did, but that's what caused the failure. It was working fine when I was using the version that included the "Size" field.

**Comment by Pentarctagon** [comment]
You need to recreate it from scratch.

**Pull request merged**
