### PR TITLE
Saurian sprites cleanup

### PR DESCRIPTION
**Pull request by czyzby**
This pull request improves the mainline Saurian sprites.

* Removed stray transparent pixels from the Augur tree sprites. These were usually supposed to be grey parts of the robes, and might have been missed as they blended with the default transparent background in tools such as Gimp.
* Recolored Oracle's robes in SE melee attack frames to match the other animations. They were grey instead of blue.
* Fixed overlapped and broken shadows. This should address most of the graphical artifacts where 2 shadows were placed on top of each other, had incorrect colors, or when a shadow was pasted over the sprite's outline, making it purple.
* Added missing leg bracelets to Flanker SE and Oracle NE running animations.
* Fixed eye colors in Ambusher NE bob, run and throw frames, as well as Soothsayer magic animation. Now they are consistent throughout all frames.
* Replaced pure black `#000000` (and nearly pure black `#020202`) with a lighter `#151515` shade. Since `#000000` usage is discouraged in the Wesnoth guidelines, I updated the palette across all animation frames of all Saurian units. The palette is still pretty dark, and the units look mostly the same in game, but the outlines are now slightly more subtle.
  * As a side note, I've toyed with more drastic changes like `#202020` and it still looks pretty OK. If you propose any further palette changes, please let me know - I've written a script that does so automatically.
* Removed around 50 redundant colors, replacing them with their closest equivalents. See the comments below for the current palette.

All images were optimized using `woptipng` script. Let me know if you'd like me to adjust or revert any of the changes.

### CODE REVIEW

**Comment by czyzby** [comment]
I've missed a couple black shades in the previous commit due to some differences between units - the latest one replaces and unifies all near-black colors darker than `#151515`.

**Comment by doofus-01** [comment]
I need to actually review the images, but this sounds like a good thing.  Pure black is discouraged, as you say.  Palette swapping/shifting is a prime benefit of pixel art, and we blow the chances to use it when we have this sloppiness, so thanks for addressing it.

I'm as guilty as anyone for contributing to the sloppiness, color-picking from the existing sprites instead of using a color swatch - we should probably have set color swatches for the different units/races/factions, but that's a different can of worms.

**Comment by czyzby** [comment]
@doofus-01 Sure, take your time. For what it's worth, I've separated the changes from each bullet point into a separate commit - you can focus on individual changes like the bracelets instead of going through all 500+ files. The last two commits are just literally find-and-replace though. Thanks.

**Comment by czyzby** [comment]
> (...) we should probably have set color swatches for the different units/races/factions, but that's a different can of worms.

@doofus-01 Now that I think about it, it might be a good opportunity to address this. I've compiled a rough list of colors that's currently used for the units. If you'd like to improve it by making it more consistent with the current graphical style, or simply by cutting down the number of redundant colors, I can swap the palette as a part of this pull request. All I'd need is a list of colors that you'd like to see - you can edit the image below and draw the replacements next to the current colors.

Palette

I'll set up a warning for anything that isn't on the list, and either assign the closest color from the new palette automatically or modify the sprite manually if necessary.

**Comment by czyzby** [comment]
I've removed 40+ redundant colors that were very close to each other. Most of them seemed like errors (i.e., no visual difference to the closest alternative), or simply very similar colors that were not reused among different sprites. There are no major visual differences between the sprites after the latest commit, but it does make it easier to recolor automatically, etc.

Outside of team colors, shadows and other effects like weapon swings, the current palette consists of:

* White, black: `#ffffff`, `#151515`
* Gold armor: `#8e5e46`, `#bf6d00`, `#ffd44a`
* Gold armor shadow, dark wood: `#581802`
* Wood (spear): `#8c3e3e`, `#e45a4c`
* Wood (staff): `#4d3f19`, `#a38637`
* Skin: `#0d4218`,  `#4d8d38`, `#98d858`, `#cff521`
* Skin (oracle): `#26882e`, `#22d22f`
* Robe, staff head: `#515249`, `#9b9c92`, `#d0d1c3`
* Robe (oracle): `#17212c`, `#3f4d5c`, `#97a7b8`, `#93c4c5`
  * _Darkest shade shared with armor._
* Armor, spear:  `#17212c`, `#2c4c6c`, `#618d8d`, `#8dc2c2`, `#c2e2e2`
* Eyes (basic): `#823818`, `#c28202`
* Eyes (upgrade): `#ad3721`, `#f88d57`
* Eyes (soothsayer): `#f93c3c`, `#ffafaf` 
* Shield (gold): `#512c00`, `#ac6e17`, `#deaa62`, `#ffe6c3`
* Shield (metal): `#263034`, `#47515d`, `#5f6b6b`, `#9aabb4`

Some thoughts:
* Ambusher's and flanker's shields stand out a bit, and do not reuse any colors. I believe at some point they were recolored without considering the existing palette, as the original Neorice basic sprites seemed to have used different colors. I'd consider recoloring them with robe/metal and gold armor colors respectively for consistency.
* I'd consider changing the spear's wood palette, possibly reusing staff's colors. Not an expert by any means, but the colors do not seem well chosen and seem a bit too flashy/orange. The darkest wood color has to work as a gold armor outline though if we want to avoid manual palette changing.
* Oracle's robe could be recolored with armor/metal palette with minimal visual changes.

**Comment by doofus-01** [comment]
Cutting down the number of colors was the first thing I was going to look into, but you're already on it.  The only thing I have to add, and you've probably considered this, is that the sprites should "pop" out compared to the terrain - the outlines and contrast mostly take care of this, but the colors are part of it.  The only test for this is seeing the sprites "in game", with terrain and time-of-day tinting.  I doubt your cleanups will break anything there, but I should test it before I formally approve.

> Anyway, I'd set up a warning for anything that isn't on the list, and either assign the closest color from the new palette automatically or modify the sprite manually if necessary.

Were you thinking of a utility script, similar to woptipng (or whatever webp compression may be coming)?  I'd be less excited about the engine itself spitting out warnings or changing the colors automatically.  Just including the color swatch as another PNG in the saurians folder would be a good start for now, in any case.

I'll try to have something more concrete to say tomorrow.  Thanks again for your work on this.

**Comment by czyzby** [comment]
@doofus-01

> The only thing I have to add, and you've probably considered this, is that the sprites should "pop" out compared to the terrain - the outlines and contrast mostly take care of this, but the colors are part of it.

Palette is mostly the same, and the difference between the current near-black color and the original `#000000` is marginal. I'm guessing that if there are any issues with terrain blending, they're likely apply to the unchanged sprites as well. I've checked the sprites in game and they seem mostly fine, although they are a bit dark and vivid/flashy compared to drakes. I've considered toning down the colors, particularly the bright greens of the skin, but I'm not terribly good with palettes and I'm a bit afraid of making them too bleak.

> Were you thinking of a utility script, similar to woptipng (or whatever webp compression may be coming)? I'd be less excited about the engine itself spitting out warnings or changing the colors automatically. Just including the color swatch as another PNG in the saurians folder would be a good start for now, in any case.

No, I was referring to my local scripts that I didn't plan on committing. Any automatic check would be problematic, since there are some semi-transparent effects (such as staff swings) that can introduce some colors outside of the palette while still being valid. Just saying that while some of the changes were manual, I'm recoloring the sprites automatically - if you have any palette changes in mind, I can apply them easily to all frames.

> I'll try to have something more concrete to say tomorrow. 

Let me know what you think about my latest comments on the colors of the shields, wood, skin, etc. I didn't want to apply these changes without asking first, since they modify the sprites more significantly than simply removing redundant colors. Thanks.

**Review by doofus-01 — APPROVED** [review]
Ideally, I would test this PR in master, but I'm not set up to do that easily, so I downloaded several of the images and compared them to the existing sprites.  Everything I saw checks out as advertised, this should be good to go.

I'll need to follow up on the precise palette, and how to apply this to other sprites, but this PR is a step forward.

**Comment by czyzby** [comment]
Thanks for the review. What are the next steps for this pull request? I think it can be merged as is, since the introduced changes are rather minor overall from the user point of view. We can handle the palette change in a separate issue. I can propose a new palette in the meanwhile, so it fits drakes a bit better.

**Comment by czyzby** [comment]
Hey @doofus-01, can I ask what are the next steps for this? Like I mentioned before, currently this pull request only includes the changes included in the top post, i.e. removal of the redundant colors, slightly lighter black color, and various fixes of some graphical issues. No major changes to the palette were applied yet, and I think we can do these within a separate issue and pull request.

**Comment by doofus-01** [comment]
> can I ask what are the next steps for this? Like I mentioned before, currently this pull request only includes the changes listed in the top post, i.e. removal of the redundant colors, slightly lighter black color, and various fixes of some graphical issues. No major changes to the palette were applied yet, and I think we can do these within a separate issue and pull request.

I agree, any palette changes can be in a separate PR.  I'm not waiting for something else from you, I'll try to commit this this weekend.

**Pull request merged**
