### PR TITLE
gui2: new logging dialog

### PR DESCRIPTION
**Pull request by ScegfOd**
I kept getting weird errors when trying to rebase the old fork (probably related to me not using the git commandline from the start)
SO I tried doing things right this time around and there's now only one commit it seems...

sorry about any confusion ^^;;

On the bright side, I think I'll be able to use the terminal git from here on out :D
Also: everything is squashed into a single not-badly-named commit :D

### CODE REVIEW

**Comment by gfgtdf** [comment]
In your code it seems like `default value is always level 1: "warn"` this sounds wrong to me the digets in the dialog shoudl default to what is the current value for that logger.

**Comment by ScegfOd** [comment]
oh, I checked and they all start out at level 1.
I didn't find a way to save or load logging settings, so I figured it'd be best to use the same convention.

**Comment by gfgtdf** [comment]
> oh, I checked and they all start out at level 1.

Yes but in your code it looks like if you open the dialog change the settings and then reopen the dialog the your previous setting will be lost.


> I didn't find a way to save or load logging settings, so I figured it'd be best to use the same convention.

well you set the settings with set_log_domain_severity and if there is no `get_log_domain_severity` yet it makes sense to add it to log.cpp/hpp of course you can do that in a seperate commit.

**Comment by ScegfOd** [comment]
Oh I see what you mean, actually adding a get_log_domain_severity would be a good idea!

**Comment by gfgtdf** [comment]
This actually looks liek something is really messsed up with the mergign commits in this branch.

**Comment by CelticMinstrel** [comment]
@gfgtdf - That merge commit at the bottom is to blame for that.

@ScegfOd - You should be able to fix this with the following sequence:

1. Reset your branch: `git reset --hard 4870ae4` - that's the commit hash of the single commit you have in this PR.
2. Make sure you have the latest changes fetched: `git fetch main master` - replace "main" with the name you've given to the upstream repo (which could be anything, but "origin" and "upstream" are common) or the URL of the main wesnoth repo (obtained from the box on the main page, not the browser's URL bar).
3. Rebase your changes onto the new ones: `git rebase FETCH_HEAD` - this may result in some conflicts, which you would need to fix; instructions on how to do so are usually given by git.
4. Force-push to update (and fix) this PR: `git push --force` - might also need to specify your fork and branch so as to push to the correct place.

If conflicts are too troublesome, you can `git rebase --abort` and just force-push the original commit here - we can resolve conflicts when it's finally merged, too.

**Comment by ScegfOd** [comment]
Oh, I did mess up the commits, sorry about that.
@CelticMinstrel - Thanks for the tips on fixing it.
BTW, should I make it into just one commit that has all the edits? I could break it up into several commits (e.g. a commit for the new files and a commit for adding the getter method to the original log.?pp)

**Comment by CelticMinstrel** [comment]
There's not really much point in having a separate commit for new files - new files should be added in the commit that requires them. The most I could maybe suggest is a separate commit for the changelog entries, but it's really not necessary. (It just might make conflict resolution a little easier in some cases.)

**Comment by ScegfOd** [comment]
I finally got around to fixing the commit history, thanks for all the tips ^_^

**Comment by ScegfOd** [comment]
#646 to help anyone digging around in this PR's history, 'cause this ended up as a different PR due largely to my inexperience with git at the time.

**Pull request merged**
