### PR TITLE
lua: Simplify the __index and __newindex wrappers in wesnoth.deprecate_api

### PR DESCRIPTION
**Pull request by jostephd**
I posted this on https://github.com/wesnoth/wesnoth/issues/4584#issuecomment-560029352 but posting again as a PR for ease of tracking. Testing instructions are on that comment too, I haven't done any testing yet.

### CODE REVIEW

**Comment by jostephd** [comment]
Tested.

- #4079: Tested using https://github.com/wesnoth/wesnoth/pull/4376#issue-320362160. The "petrified" icon shows both in master and with this PR (that's correct).

- The first issue described in https://github.com/wesnoth/wesnoth/issues/4584#issuecomment-555788446: Tested using the code in that comment. It prints `bar foo` `nil nil` both in master and with this PR (I'm not sure if that's correct).

- The second issue described in https://github.com/wesnoth/wesnoth/issues/4584#issuecomment-555788446: is not expected to be fixed by this.

@CelticMinstrel Would you be able to take this from here? I hope this PR is correct but I don't know lua well enough to be certain about that. I'm also not sure what to make of that piece of code printing `nil nil` rather than what the comment says it should print.

**Comment by CelticMinstrel** [comment]
Yeah, it should definitely be printing `bar  foo`... so there must be something wrong somewhere.

**Comment by jostephd** [comment]
Would it be correct to assume that nothing here is a regression nor a blocker?

**Comment by CelticMinstrel** [comment]
Figured out the issue. You're returning `elem[val]` instead of `elem[key]`. With that change, I think this is good to merge.

**Pull request merged**
