### PR TITLE
Implementation of a "Surrender Game" feature

### PR DESCRIPTION
**Pull request by kallaballa**
I implemented a "Surrender Game" feature that resides in the main in-game menu. When clicked a confirmation dialog will be opened and when confirmed all units of the current side are killed and "check_victory()" is called to end the game.

### CODE REVIEW

**Comment by gfgtdf** [comment]
Your code just kills all unit on that client, but doesnt send that action to the other clients, so the unit will just appear dead on your client but not on the others, you can probably also test with you start a game with 2 wesnoth clients on  local mp server.


for the record, we had alreeady a very similar pr  https://github.com/wesnoth/wesnoth/pull/535 that made the same mistake and then had to be rejected becasue the author didn't repond.


also i tihnk it'd be better if your code, instead of killing all your units just marks the side as defeated (by setting defeat_condition=always) this in particular as the follwong advantages:
1) linger mode will will work for you enemy and you in the normal way.
2) it's nicer for your teammate if your units still stand there.

**Comment by kallaballa** [comment]
Thx. I'll fix those issues tomorrow

On November 18, 2017 11:10:31 PM GMT+01:00, gfgtdf <notifications@github.com> wrote:
>Your code just kills all unit on that client, but doesnt send that
>action to the other clients, so the unit will just appear dead on your
>client but not on the others, you can probably also test with you start
>a game with 2 wesnoth clients on  local mp server.
>
>
>for the record, we had alreeady a very similar pr 
>https://github.com/wesnoth/wesnoth/pull/535 that made the same mistake
>and then had to be rejected becasue the author didn't repond.
>
>
>also i tihnk it'd be better if your code, instead of killing all your
>units just marks the side as defeated (by setting
>defeat_condition=always) this in particular as the follwong advantages:
>1) linger mode will will work for you enemy and you in the normal way.
>2) it's nicer for your teammate if your units still stand there.
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/wesnoth/wesnoth/pull/2215#issuecomment-345475197

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kallaballa** [comment]
i changed the code accordingly but there is still a problem. If I test the change with a local mp server the defeat_condition doesn't seem to be transmitted between clients. what am i missing?

**Comment by gfgtdf** [comment]
> what am i missing?

Well you obviously don't send that actions to the other clients. To understand how it should work, have a look at how other actions do it, for example recruiting:
1) the (ui) (here menu/mouse_handerl) code calls synced_context::run, https://github.com/wesnoth/wesnoth/blob/master/src/menu_events.cpp#L341
2) synced_context::run stores that recruit action in the replay and calls the accoring hander
3) the recruit hdnler is executed at your local client (called by synced_context::run) https://github.com/wesnoth/wesnoth/blob/master/src/synced_commands.cpp#L67
4) the reply data is sended to the other clients: https://github.com/wesnoth/wesnoth/blob/master/src/playmp_controller.cpp#L187
5) The recruit handler (https://github.com/wesnoth/wesnoth/blob/master/src/synced_commands.cpp#L67) is executed on the other client after they received the action

Note that there are somc corner cases, for example actions that can be undone are not yet sended to other clients and delayed until thy cannot be undone anymore.

**Comment by kallaballa** [comment]
I implemented a synced command as far as i understand them and it works when the current side surrenders. but the command is rejected when the side surrenders while it is not its turn. I'm sorry but i don't understand how to fix that.

btw. replay files record the surrender correctly

**Comment by gfgtdf** [comment]
> but the command is rejected when the side surrenders while it is not its turn

Yes that's how it currently works, you cannot invoke gamestate chaging commands unless it is your turn. The main reason for that is that it might result in these commands beeing executed in a different order on the different cleints (in case that the currentl plaing player issued a move or other actions just at the same time when you made yours) which leads to OOS error later.

**Comment by kallaballa** [comment]
So there is no way to surrender while it's not the side's turn?

**Comment by gfgtdf** [comment]
while it's not completeley impossible it's likeley not suitable for 1.14 since it coudl be rather complicated and thus had good chance to break other things.

**Comment by kallaballa** [comment]
ok. thanks for all the support. I'll add the code to disable the surrender item while it's not the side's turn once i figured out how to :)

**Comment by gfgtdf** [comment]
what you could do though is make it send a message like 'player x gives up' this cal also be implemented as  custom replay tag . As i said above the limitation of only working on your own turn only applies to gamestate changing actions. To do that you wouldn't use synced_context::run, but insted just call resources::recorder->add_... directly follwoed by a turn_info->send_data()

**Comment by kallaballa** [comment]
Is this how you mean? https://gist.github.com/kallaballa/1e54f5a907829d6c7863243728014689
Because the surrender command somehow won't show up in the remote side's replay. only in the replay of the side issuing the surrender.

**Comment by kallaballa** [comment]
nevermind. i think i understand now.

**Comment by kallaballa** [comment]
ok. i tried manipulating the replay from a synced command. but https://github.com/wesnoth/wesnoth/blob/master/src/replay.cpp#L854 prevents that. now i'm a bit confused because i thought only game state data shouldn't be manipulated from passive sides.

**Comment by kallaballa** [comment]
I made it work but I'm not sure at which cost :p 
https://gist.github.com/kallaballa/1429ec8c90d5216b8b093f9bac93de24

Also i'd like to send a server message stating the fact that a side has surrendered but by now i couldn't find out how.

**Comment by gfgtdf** [comment]
No that's not what i meant. In your current code yout synced surrender handler is completel useless because it does nothing on the current players side and isns executed at the other players side(bevause of yoyr code in replay.cpp). What i meant was,  that in case it is not the local players turn, you could just add a unsynced command (like add_speak) _instead of calling 
synced_context::run_

**Comment by kallaballa** [comment]
Of course i believe you when you say that this is not they way it should be and i'll try to reimplement it. But try it - it works.

**Comment by kallaballa** [comment]
I just read thoroughly through your comments and i really think you misunderstood the code... could you maybe check again? because it really works as expected: a surrender command in both replays and the surrendering side quits. i tested with a local mp server. to make reading and testing the code easier i created a commit instead of a diff.

**Comment by gfgtdf** [comment]
I cannot test right now, since im not home currently. I'm still not seeing the advantage of your latest commit. are you saying that with that you testaed that the server no longer rejects off-turn surrender messages?

**Comment by kallaballa** [comment]
Thanks for your patience.. I think i see the light and implemented it as suggested

**Comment by kallaballa** [comment]
The pull request has become convoluted because of many small changes. I close it and reopen a new one with all changes in one commit.

**Comment by GregoryLundberg** [comment]
No need to do that.

Read up on `git rebase` specifically `git rebase --interactive` and fix your commits then `git push -f` your master to update this PR and re-open it.

For future reference, it is best to work in a feature-branch and keep your master clean.

**Comment by kallaballa** [comment]
Thx. that's what i did but i'm not able to reopen that pull request

**Comment by GregoryLundberg** [comment]
OK. I can't either. _sigh_ Well, I'd suggest, then making a feature branch to clean up your master and openning a new PR. Be sure to reference this one in your opening comment so the history is, at least, linked.

**Pull request closed without merging**
