### PR TITLE
Game Display: Show correct defense modifier for unreachable terrain.

### LINKED ISSUE #2353: Wrong terrain defense display for Horseman on Snowy Mountains
1. Start HttT.
2. :change_level to The Dwarven Doors.
3. Click on the Horseman unit.
4. Mouseover the frozen mountains (9,33) (terrain code "Ms").

The hex is highlighted as "30%" terrain defense, even though Horsemen can't enter that hex at all. This is different to the adjacent regular mountains (10,33 "Mt") that are also unreachable but show as "0%". In contrast, the infobox at the top of the sidebar shows a dash for both Ms and Mt.

### PR DESCRIPTION
**Pull request by jostephd**
Fixes #2353. I copied the idiom from the position report (REPORT_GENERATOR(position)), I'm not sure if that's the best fix.

### CODE REVIEW

**Comment by GregoryLundberg** [comment]
Oh, and there is no need to open an Issue if you're going to open a PR. If you'll notice they're sequentially numbered. Think of an Issue as just a Pull Request without the suggested fix attached,

**Comment by jostephd** [comment]
Good point about else. Incorporated.

When I opened the issue, I hadn't yet had a patch in hand :)  (I will keep this in mind for next time)

**Comment by GregoryLundberg** [comment]
I'll merge when the CI runs finish.

I'm kicking myself for not adding the snide remark about using ?: because it's 'cute', not as readable as if..else, and with a modern optimizer not really needed. But I backed it out and you used it. _sigh_ Don't bother changing it now. But next time I'll remember to make my snide remark :P

**Comment by jostephd** [comment]
Please do :). FWIW, I changed the if/else to a ternary because with the former it's less obvious that `def` would be initialized in all codepaths. And thanks for merging :)

**Comment by CelticMinstrel** [comment]
Is it not possible to have a non-zero defense value on an impassible terrain? I thought it was...

**Pull request merged**
