### PR TITLE
add weapon abilities in unit_type analysis for simulation

### PR DESCRIPTION
**Pull request by newfrenchy83**
This changes must be add abilities like UtBs formation to be added in unit_type simulation but not the 'aura' abilities(Httt initiative).

### CODE REVIEW

**Comment by soliton-** [comment]
Is there a reason why this is not relevant anymore?

**Comment by newfrenchy83** [comment]
@soliton- i fear what apply_to=oponent cause a crash with that.

**Comment by soliton-** [comment]
That's very little to go by. Does that mean there is a bug in the ability handling code? Surely this does not only affect the damage calculation that was being modified here. Is there a bug report about this crash?

**Comment by newfrenchy83** [comment]
@soliton-  in fact, i think what this bugs was caused by a bug fixed by https://github.com/wesnoth/wesnoth/commit/3b9325647d9de6122b186b7728405cde5ef87fa9, i retry and all fine, perhaps i will reopen this PR

**Comment by newfrenchy83** [comment]
@soliton- i play some and tested abilities used like special with this change, but none bugs. i will reopen this PR but i frustrated to don't find the cause of this crashes who is genertaed one time only.

**Comment by gfgtdf** [comment]
does this actually work? I'd expect that (since if there is no unit ser in the attack context setter) that get_special_bool returns exactly the same values as bool_ability.

**Comment by newfrenchy83** [comment]
> 
> 
> does this actually work? I'd expect that (since if there is no unit ser in the attack context setter) that get_special_bool returns exactly the same values as bool_ability.

I expect but how know this, i don't see this.

**Comment by gfgtdf** [comment]
> Did you test that this actually changes anything?

**Comment by newfrenchy83** [comment]
I don't see how testing that, alas?

**Comment by soliton-** [comment]
Make up a test case where the ability will produce a significant difference between two attack targets or so. Like without considering the ability there is a 100% hit chance and with it is really 0%. Then you should see a difference in AI behaviour with and without this PR.

**Comment by newfrenchy83** [comment]
all that what i know on this function came to https://github.com/wesnoth/wesnoth/commit/fb4361d666b8b0e169544217e33f4287a747719c. i don't know how see diffrences in game.

**Comment by gfgtdf** [comment]
I think its also conlear what you mean by "must be add abilities" in the commit message

**Pull request closed without merging**
