### PR TITLE
Add string representation to wmlparser3 nodes

### PR DESCRIPTION
**Pull request by ProditorMagnus**
I reverted wml fragment formatting currently, not sure if those may be changed.

### CODE REVIEW

**Comment by ProditorMagnus** [comment]
Looks like https://vgy.me/txQ2Fp.png

**Comment by Vultraz** [comment]
This ready?

**Comment by ProditorMagnus** [comment]
Yes.

**Comment by CelticMinstrel** [comment]
It feels wrong to be implementing `repr` in terms of `str`. The two functions are intended for different purposes. See [here](https://www.geeksforgeeks.org/str-vs-repr-in-python/) for some explanation. In particular, `str` should be _human-readable_ while `repr` would ideally be _machine-readable_.

**Comment by ProditorMagnus** [comment]
True. The reason behind adding repr too is to show it in list - data lines from screenshot.

**Comment by CelticMinstrel** [comment]
Oh, Python debugger? I've somehow never really used that.

I'd say it does make sense to implement `repr` but doesn't make sense to use the same format as `str`. However, I don't have any other ideas about how it could be formatted, so I guess it could be left as is unless someone else comes up with something...

**Comment by ProditorMagnus** [comment]
Ideally eval(repr(x))==x. But going full recursion for TagNodes will just timeout pycharm debugger evaluation.

**Comment by jostephd** [comment]
I think `TagNode(foo)` is a suitable format for `__repr__` but not for `__str__`. Calling str() on a TagNode object should return a multi-line WML string representation of the TagNode, shouldn't it?

I wonder if we should do this:

```
diff --git a/data/tools/wesnoth/wmlparser3.py b/data/tools/wesnoth/wmlparser3.py
index 5b15f8dd8b9..730bc15b2ff 100755
--- a/data/tools/wesnoth/wmlparser3.py
+++ b/data/tools/wesnoth/wmlparser3.py
@@ -99,11 +99,8 @@ class StringNode:
         else:
             return "'%s'" % self.data.decode("utf8", "ignore")
 
-    def __str__(self):
-        return "StringNode({})".format(self.debug())
-
     def __repr__(self):
-        return str(self)
+        return "StringNode({})".format(self.debug())
 
 
 class AttributeNode:
```

for all classes, not just StringNode.

**Comment by ProditorMagnus** [comment]
Using self.debug() on nontrivial node will just result in timeout.

**Comment by CelticMinstrel** [comment]
I don't think it's necessary for `eval(repr(foo))` to return foo, just for the record. Sometimes (like here) it's really impractical, after all.

If it's practical it might make sense to make `repr(foo)` output actual valid WML, but that too might be impractical...

**Pull request merged**
