### PR TITLE
Hide the Suppose Dead hotkey from the preferences

### PR DESCRIPTION
**Pull request by jostephd**

### CODE REVIEW

**Comment by gfgtdf** [comment]
hmm instead of disabling the hotkey we could also enable the actual function, i wonder why it was disabled in the first place.

**Comment by gfgtdf** [comment]
according to the comment before yours the only reason why it is disabled is that we cannot find a good ui for it?

**Comment by jostephd** [comment]
> i wonder why it was disabled in the first place.

It fails an assertion as soon as I try to use it:

https://github.com/wesnoth/wesnoth/blob/2eccbab9708526ab289f201d40b613c5f25a5a06/src/whiteboard/suppose_dead.cpp#L122-L123

**Comment by gfgtdf** [comment]
ok there seems to be so much wrong the suppose_dead code, for starters why do we sometime use resources::gameboard->units() and sometimes the passed unit_map& unit_map if they actuall point to the same object. Also that asserion makes no sense as we just extraced the unit form the map and get_unit gets the unit from the map ....


Okay in any case, this pr looks good to me, we can still try to fix the supposedead code after this is merged.

**Comment by Wedge009** [comment]
When I first started in Wesnoth dev I tinkered a bit with the whiteboard stuff, trying to resolve some issue back in Gna. But it is indeed quite a difficult-to-understand chunk of code and I fear a lot of it is quite broken so I think collectively we've given up on it. Nonetheless it appears a lot of players still use whiteboard functionality even as it currently stands so some devs made the point that we can't just disable it altogether.

Anyway, I concur that this can be merged to at least clean up #1270.

**Comment by jostephd** [comment]
Merged. Will backport too, after 1.14.9. If someone wants to make suppose dead work, go ahead.

**Comment by Wedge009** [comment]
Hmm, looks like this was never back-ported to 1.14 branch, but I suppose that's moot as there are no more releases scheduled for it.

**Pull request merged**
