### PR TITLE
Add "Other aspects: " string in catalogue

### PR DESCRIPTION
**Pull request by newfrenchy83**
Fix partially of https://github.com/wesnoth/wesnoth/issues/7612 issue

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
This is nice and all, but how does it fix anything?

**Comment by newfrenchy83** [comment]
@CelticMinstrel It begin to resolve https://github.com/wesnoth/wesnoth/issues/7612 issue bt not all.

**Comment by CelticMinstrel** [comment]
No, it doesn't address it at all.

**Comment by Pentarctagon** [comment]
The po files should never have strings added to them directly. The source of the missing string needs to changed in some way to get it to show up.

**Comment by newfrenchy83** [comment]
Can I still leave the pot file or just abandon this request?

**Comment by Pentarctagon** [comment]
The pot file should also not be directly modified.

**Pull request closed without merging**
