### PR TITLE
updated copyright in WML tool GUI app

### PR DESCRIPTION
**Pull request by knyghtmare**
From 2016 to 2024

### CODE REVIEW

**Comment by stevecotton** [comment]
Even for the tools domain, this doesn't feel worth breaking the string freeze.

**Comment by Pentarctagon** [comment]
I'm not sure how it works for the python tools, but is possible to concatenate translatable and untranslatable strings? `© Elvish_Hunter, 2014-2016` doesn't seem like it would even need translation in the first place.

**Comment by stevecotton** [comment]
It would be possible to concatenate translatable and non-translatable strings, however in this case the existing string is multi-line:

https://github.com/wesnoth/wesnoth/blob/37a45c32cef0a0b96f4872b7382015fa076335ed/po/wesnoth-tools/ar.po#L490-L507

**Comment by knyghtmare** [comment]
So, can this on in now?

**Comment by Pentarctagon** [comment]
I'd say so.

**Pull request merged**
