### PR TITLE
Use std::numeric_limits instead of C macros

### PR DESCRIPTION
**Pull request by Vultraz**
CI run

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I accidentally commented on the commit instead of the PR. Whoops.

**Comment by Pentarctagon** [comment]
I don't see any comment on the commit here either.

**Comment by CelticMinstrel** [comment]
Link! https://github.com/wesnoth/wesnoth/commit/da44c829877b69a36904d84e424d6148999f6687#r144160673

**Comment by Vultraz** [comment]
I think I’ll forego `auto` in this case.

**Comment by CelticMinstrel** [comment]
I'd say you should use `auto` in any case where it's a type other than `int`, but I don't think I saw any of those.

**Pull request merged**
