### PR TITLE
[UtBS] 1.14 various graphics updates

### PR DESCRIPTION
**Pull request by doofus-01**
This is for various graphics updates.  I will try to stay away from string changes and balance changes, though there may be some minor trespasses.  I think any changes here will be compatible with 1.14.1 and later.

### CODE REVIEW

**Comment by shikadiqueen** [comment]
Just noting: you **can** propose string changes for 1.14.1 if you want, and if you are going to do so, this is the right time since the string changes window for it is going to be shorter than the norm. (Most things aren't going to be merged before 1.14.0 is announced, though.)

**Comment by doofus-01** [comment]
OK.  In that case, I will try to get rid of the obvious prose issues like "horses" within the next couple of days.  Thanks.

**Comment by gfgtdf** [comment]
adding a new terrain_type is an incomability on wml api. ths cannot go into 1.14 as is.

**Comment by shikadiqueen** [comment]
Firstly, because of the Debian/Ubuntu packaging of the mainline campaigns, nobody should be assuming that they are present in the first place.

Secondly, `#ifver` exists.

I don't think the replays issue warrants rejecting improvements to solo campaigns in 1.14, especially given the current situation with master.

**Comment by CelticMinstrel** [comment]
Since it's not multiplayer, and assuming the terrain type is not exposed for multiplayer, I think this is fine to go in 1.14. The terrain type will likely be visible in the editor, but there's a warning about using the extra terrain types anyway, so people should know not to just put them on any random map.

**Comment by shikadiqueen** [comment]
I thought that was limited to debug mode? I hope it is, because people on the MP server shouldn't be playing campaigns that weren't coded for MP and balanced with human players in mind.

**Comment by shikadiqueen** [comment]
Sigh.

It should be possible to rework the new decoration for scenario 1 into a scenario-specific `[terrain_graphics]` rule instead of adding a new terrain.

**Comment by ln-zookeeper** [comment]
I really don't see a reason for a new terrain type here, even without technical issues it seems unnecessarily complicated to do it that way. The image is great, and if/when it can't easily be applied using [item], we can indeed just use a local [terrain_graphics] rule to place it (I can whip up the WML for that if you don't immediately know how); the hex isn't really combat-relevant, so it's fine if it's simply flat grass gameplay-wise.

**Comment by CelticMinstrel** [comment]
The only possible problem I can see with a local `[terrain_graphics]` rule is, does that allow it to be placed and removed as needed?

**Comment by ln-zookeeper** [comment]
By local I mean one that's truly specific to that scenario only; not a rule that's crafted to only match a location in that scenario. So there's no need to place/remove the rule during the scenario.

**Comment by doofus-01** [comment]
I think it's fixed now.  (Gotta say, I'm not liking this multiplayer access to SP campaigns thing.)

**Comment by doofus-01** [comment]
By the way, what are the antelopes going to be called?  Hopefully not "antelopes".  I'll come up with something if no one has any preferences.  Something descriptive and not obviously Dutch.

**Comment by CelticMinstrel** [comment]
Antelopes, gazelles, sand-runners, sand-goats (did I seriously think of this <_< ), hornbeasts, duocorns (was gonna suggest unicorn but they have two horns not one, so)...

**Comment by doofus-01** [comment]
If there are no objections to those two base sprites (shaman and druid), I will do basic animations for them.

**Comment by CelticMinstrel** [comment]
They seem pretty decent to me.

**Comment by Vultraz** [comment]
BTW, if you want the unconscious Kaleh sprite to not be ToD colored, append `~NO_TOD_SHIFT()` to the image path.

**Comment by doofus-01** [comment]
I've used Vultraz's IPF suggestion for the Kaleh item.  I have got done all I'm going to get done for now, if 1.14.1 timeline requires these changes should be committed, feel free.  It touches many different files, so maybe best not to squash.

My thinking for the antelopes name is "dustboks".  It has the disadvantage that it has a European colonial root (-bok), but the advantage is that the name should make sense to anyone with access to Wikipedia, and is probably translatable.  And it is short & simple enough that the Quenoth might believably refer to them by that name.

**Comment by ln-zookeeper** [comment]
These look good to me, except I think Druid has anatomical problems. She seems to have an unusually small head, a hunchback, and really wide shoulders (in relation to her hips, anyway). Might not be terribly relevant for animations, of course.

The antelopes naming really should be done/discussed separately from any other textual changes, it's a rather important decision.

If at all possible, it'd be great if you could set up your text editor to not use tabs, or if you could otherwise take care of whitespace/indentation issues. If it makes your workflow difficult then we can keep running wmlindent afterwards, but if it's just a matter of checking the diff before committing and fixing visible issues (tabs, mismatching indentation, empty lines), I'd suggest that.

**Comment by CelticMinstrel** [comment]
Pretty sure all he needs to do is run wmlindent himself before committing. That's what I did with the dunefolk balancing changes.

**Comment by Vultraz** [comment]
I'm merging this. The Druid can always be further updated if necessary.

**Pull request merged**
