### PR TITLE
Change editor event from start to prestart.

### LINKED ISSUE #7969: scenario editor adds its content in a start event.
As said in the title the editor currently adds its content ([area]s, [unit]s etc) in a start event, this means they cannot be used form prestart events,

I suggest that the editor adds those in a prestart even with a higher `priority=`,  so that other prestart events can access it, a usecase for example would be a prestart event that randomly scatters a few items in an [area] that was defined in the editor.

### PR DESCRIPTION
**Pull request by Pentarctagon**
fixes #7969

### CODE REVIEW

**Comment by gfgtdf** [comment]
I still think it should also have a higher `priority=` so that other prestart events are guarenteed to be able to use the stuff  added by this event.

**Comment by Pentarctagon** [comment]
How high a priority would be a good value?

**Comment by sevu** [comment]
The id with both _ and - is a bit complicated … maybe something shorter?

**Comment by Pentarctagon** [comment]
The point is to make it somewhat complicated/unique, so that someone doesn't by chance give one of their own events the same ID.

**Comment by gfgtdf** [comment]
> How high a priority would be a good value?l

Hmm, not sure, since the prior value only gets meaning compared to others priority values the first one will always be chose a bit arbitrary. I'd probably put 1000.

**Comment by Pentarctagon** [comment]
Alright, updated.

**Pull request merged**
