### PR TITLE
Properly implement DO_NOT_MODIFY_CACHE

### PR DESCRIPTION
**Pull request by soliton-**
This fixes node_to_string().

### CODE REVIEW

**Comment by stevecotton** [comment]
Looks good to me, but please add a description of a user-observable bug that this causes to the commit message. Current it "fixes" something without saying what.

**Comment by soliton-** [comment]
It fixes the behavior of `DO_NOT_MODIFY_CACHE` which `node_to_string` is the only user of.

Kinda hard to describe a user-observable bug based on undefined behavior. I can write something like "This fixes node_to_string() by making sure the node is really not modified".

**Comment by Pentarctagon** [comment]
Does it fix #5390?

**Comment by soliton-** [comment]
Probably, didn't try to reproduce it.

**Pull request merged**
