### PR TITLE
1.17 terrain transitions update

### PR DESCRIPTION
**Pull request by doofus-01**
This is best summarized with these before/after images.  Possibly the rubble is too busy now, maybe it should have bigger rocks, or maybe just lower contrasts.
Screenshot_20220327_before
Screenshot_20220327_after

### CODE REVIEW

**Comment by stevecotton** [comment]
It's beginning to look like a stone path rather than rubble, IMO.

**Comment by doofus-01** [comment]
> It's beginning to look like a stone path rather than rubble, IMO.

That is up to the map designer, I think?  In any case, I've made some of the rocks bigger.

I'll merge this in a few days, if there are no objections or CI failures.

**Comment by Pentarctagon** [comment]
Having something that could be used for an old/ruined stone isn't a bad thing either.

**Comment by stevecotton** [comment]
> > It's beginning to look like a stone path rather than rubble, IMO.
> 
> That is up to the map designer, I think? In any case, I've made some of the rocks bigger.

Looks good, thanks. Sorry for commenting without checking these in the editor first, having tested them it's easy to distinguish a line of these from a line of the flat terrains Cobbles or Cave Path.

**Pull request merged**
