### PR TITLE
remove only_active argument to weapon_specials()

### PR DESCRIPTION
**Pull request by newfrenchy83**
weapon_specials only called in unit_attack.cpp, only_active argument don't usable

### CODE REVIEW

**Comment by stevecotton** [comment]
There's some documentation on that function that should be updated too.

If we merge this now, would you be happy to merge this exact change onto 1.17 too and then rebase the bigger PR on top? Otherwise I'd prefer to only merge things that can be applied to both 1.16 and 1.17.

**Comment by newfrenchy83** [comment]
merge change into 1.16/1.17 and rebase big PR. i will update documentation.

**Comment by newfrenchy83** [comment]
Documentation corrected

**Comment by stevecotton** [comment]
Oops, I forgot to squash those into a single commit.

**Pull request merged**
