### PR TITLE
fix carryover_percentage not valid when victory_when_enemies_defeated=no

### PR DESCRIPTION
**Pull request by newfrenchy83**
this is another version of https://github.com/wesnoth/wesnoth/pull/4126

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Wait, no, I think I do remember why the conditional is there - If I'm not mistaken, that schema commit now makes those two keys _required_ when `victory_when_enemies_defeated=no`, which would certainly cause problems if there are any scenarios that omit them.

We should consider whether they should be required in both cases - if they're optional in one case and required in the other, then keep the conditional but add an `[else]` branch defining them with a default. If they're always optional, just change them to `DEFAULT_KEY` and add a default value.

**Comment by newfrenchy83** [comment]
@CelticMinstrel  those value was correst where it is carryover_percentage=on and carryover_add=no?

**Comment by CelticMinstrel** [comment]
Urgh, bad indentation... if this is merged maybe someone should run wmlindent on the schema dir? Or if we're sticking to tabs for schemas then this commit should be changed to tabs.

**Comment by jyrkive** [comment]
This pull request is obsolete after commit 670488d53ed527be0273b7d715dfff09ec688b0a.

**Pull request closed without merging**
