### PR TITLE
More New Titlescreen Images

### PR DESCRIPTION
**Pull request by Gothyoba**
A followup to #9182 

Since then I have found more really cool images to add to the titlescreen.

cool
cool2
cool3
cool4
cool5
cool6

### CODE REVIEW

**Comment by Wedge009** [comment]
The last one is a bit bland, but I suppose more variety is better. I can't remember why we had these images in 'core' that weren't already used in campaigns. Seems like general images would be well suited for the title screen.

Trivial point: does the configuration still work if the file paths are listed on separate lines? Just to make it easier to read and for future maintenance.

**Comment by CelticMinstrel** [comment]
While we're at it, can we maybe also remove that one that has a completely different art style?

**Comment by Vultraz** [comment]
I say let's remove the last one, and also the one celmin is talking about.

**Comment by Wedge009** [comment]
> ...can we maybe also remove that one that has a completely different art style?

> I say let's remove... the one celmin is talking about.

...which one is that?

**Comment by Gothyoba** [comment]
I presume celticminstrel is talking about the last one with a completely different art style. Otherwise I’m confused. I didn’t notice much of an art syle difference. Though there are other images on the titlescreen that have an art style similar to the last one so I’m not entierly sure about that. The last one is useedin WoF by the way. By the way, all of these are used in campaigns (TRoW or WoF). I’m not too bithered removing the last one, thiugh I do feel it’s prety nice. It’s not the blandest image on the titlscreen, and adds some nice variety.

**Comment by Wedge009** [comment]
> Otherwise I’m confused.

So am I. Vultraz said the last one + 'the one celmin is talking about', so sounds like another one altogether.

**Comment by Vultraz** [comment]
Sorry, I was thinking of one of the existing images (the one with the elven sword not done by LordBob). But for this just remove the last one.

**Comment by Gothyoba** [comment]
The elven sword was my favourite titlscreen image! And it is stylistically simialr to the others. But I suppose it could be removed later. I will be removing the final one later, though I’d like to note there’s other mountain inages in a similar style on the titlescreen already and the image is still made by LordBob (one of various geenric story images, currently used only used briefly in WoF as far as I know).

**Comment by Wedge009** [comment]
For reference, is the 'elven sword' referring to https://raw.githubusercontent.com/wesnoth/wesnoth/refs/heads/master/data/core/images/story/wesmere.webp?

For what it's worth, I don't think it's too different from the other scenes (certainly nowhere near to the degree that the proposed music addition in #9364 would be from the existing core), although the depth-of-field blurring looks odd (the bottom-right corner seems to be still in-focus). If I have a say, I think it's worth leaving in.

**Comment by Gothyoba** [comment]
Inwould at least leave it in core. One of the reasons for adding it was due to the immense lack of generic in-game story art. I saw that a few add-ons used this, and maybe it would be useful for forest settings. I quite like it on the titlescreen, and it isn’t too different form the rest. I personally think it’s good to have some image variety in Wesnoth. That’s also why I would personally keep the last image proposed here. It is similar enought to eh toher images and provides some nice-looking variety. It also breaks the monoply of mostly TRoW images, but I’m not as concerned about the last one I proposed.

**Comment by babaissarkar** [comment]
I also agree with leaving the Elven Sword image in.

**Comment by Vultraz** [comment]
I'm fine keeping the elven sword. The problem with the hills image is it's just not visually interesting. It's quite flat, the colors are muted, and it looks more like it was meant as a base for a piece that never came to fruition.

**Comment by CelticMinstrel** [comment]
> For reference, is the 'elven sword' referring to https://raw.githubusercontent.com/wesnoth/wesnoth/refs/heads/master/data/core/images/story/wesmere.webp?

That's not the one.

**Comment by CelticMinstrel** [comment]
I think the one I was thinking of is landscape-battlefield[-nohumans]?

**Comment by Wedge009** [comment]
Linking just so we're clear on what we're talking about.

https://raw.githubusercontent.com/wesnoth/wesnoth/refs/heads/master/data/core/images/story/landscape-battlefield.webp

https://raw.githubusercontent.com/wesnoth/wesnoth/refs/heads/master/data/core/images/story/landscape-battlefield_nohumans.webp

I'm not sure, but I think these might be included in the current list of title screen images. The one without bodies does look a bit empty, but then the one with bodies might be a bit grim to show on the title screen for a newcomer's first impression.

> The problem with the hills image is it's just not visually interesting. It's quite flat, the colors are muted, and it looks more like it was meant as a base for a piece that never came to fruition.

Not sure what the hills image is referring to. But there are files named hills in the core images, but I don't think they're used as title images at present.

https://raw.githubusercontent.com/wesnoth/wesnoth/refs/heads/master/data/core/images/story/landscape-hills-01.webp

https://raw.githubusercontent.com/wesnoth/wesnoth/refs/heads/master/data/core/images/story/landscape-hills-02.webp

I agree 01 is rather plain and probably not suited as a stand-alone image. While 02 is in a distinctly different style to the other images, I think it's okay as a stand-alone image. Again, I don't think I've seen either of these used as title images at this point.

**Comment by CelticMinstrel** [comment]
> Linking just so we're clear on what we're talking about.
> 
> https://raw.githubusercontent.com/wesnoth/wesnoth/refs/heads/master/data/core/images/story/landscape-battlefield.webp
> 
> https://raw.githubusercontent.com/wesnoth/wesnoth/refs/heads/master/data/core/images/story/landscape-battlefield_nohumans.webp
> 
> I'm not sure, but I think these might be included in the current list of title screen images. The one without bodies does look a bit empty, but then the one with bodies might be a bit grim to show on the title screen for a newcomer's first impression.

I find it jarring every time it comes up, not because it's grim or anything, but because the style is so much more cartoony than most of the others, with sharp, clear line art. In comparison, most of the other are soft like brushwork, with minimal if any line art.

**Comment by Wedge009** [comment]
That's okay. I find the EI-specific music jarring in a similar way.

**Comment by CelticMinstrel** [comment]
…

**Comment by Vultraz** [comment]
I meant the last image proposed for addition in the OP.

**Comment by Gothyoba** [comment]
Ok, I’ll try to find an alternative to the last image then. I think I would like to have some other hills image then, but I agreee this option sin’t visually interesting. Currently there is only one landscape battlefiled image iirc, the one with humans. Perosnally I think that image is a bit jarring, so I would either remove it or add more images in that style.

**Comment by Gothyoba** [comment]
I've tried replacing the drake mountain image with this:



I was thinking adding more images in the style of the battlefield one would make it less weird while keeping the nice variety it adds:

**Comment by Wedge009** [comment]
I think these are good, but others might disagree...

**Comment by CelticMinstrel** [comment]
> I was thinking adding more images in the style of the battlefield one would make it less weird while keeping the nice variety it adds:

What nice variety? It doesn't fit in with the current main menu at all (the side buttons in particular look really bad against that sky), and it's jarringly different from all the other images that can be chosen for the title screen.

**Comment by Gothyoba** [comment]
Does anyone else have an opinion on this? I know Wedge likes them and celticminstrel strongly dislikes them, but I’d like to wait for a bit more feedback before making changes.

**Comment by Wedge009** [comment]
Like might be a strong word. I think they are fair when viewed individually. I can understand the concern when comparing with the existing image set, but if the purple undead image can be included, I don't see why these can't.

**Pull request merged**
