### PR TITLE
WoF S02: Rename the orc team to "Trespassers"

### PR DESCRIPTION
**Pull request by stevecotton**
The drakes' dialogue is unchanged, so Vladnir still calls them "infesters", this just removes the term from the UI.

Ping: @Jonathan-Kelly @CelticMinstrel @demario-w

### CODE REVIEW

**Comment by stevecotton** [comment]
I'd be in favor of changing Vladnir's text too, so the second paragraph of ""The treachery of Gorath Ohm ..." becomes:

> For even now voracious landbound creatures keep a holdfast on our northernmost isle.
> This isle that was before bountiful with game is now laid bare by these trespassers.

**Comment by Hejnewar** [comment]
Can someone remind me when was the string freeze huh? Yes Im angry about that.

**Comment by stevecotton** [comment]
I acknowledge that string freeze should have been 3 months ago, but I feel these are bugfixes that justify breaking the freeze.

**Comment by demario-w** [comment]
> I acknowledge that string freeze should have been 3 months ago, but I feel these are bugfixes that justify breaking the freeze.

1. I am [obviously](https://forums.wesnoth.org/viewtopic.php?t=55582&start=90) a fundamentalist in terms of string freeze and stable content for translators. 
2. I [don't think](https://github.com/wesnoth/wesnoth/pull/8124#discussion_r1457706971) a couple of string changes will change the problematic nature of the story told in this campaign
3. I made public [my concerns](https://github.com/wesnoth/wesnoth/issues/7361) about the content of this campaign a long time earlier

Consequently, I made [a suggestion](https://github.com/wesnoth/wesnoth/pull/8124#discussion_r1459064714) to cut the cost on the future release. Discussions on the remaining work is fine to be open now as the momentum is there, but changes could be easily [postponed](https://github.com/wesnoth/wesnoth/pulls?q=is%3Apr+is%3Aopen+label%3APostponed) after the release 1.18.

> Can someone remind me when was the string freeze huh? Yes Im angry about that.

How does it feel now, with [the boot on the other foot](https://idioms.thefreedictionary.com/boot+is+on+the+other+foot)?

**Comment by stevecotton** [comment]
> Discussions on the remaining work is fine to be open now as the momentum is there, but changes could be easily [postponed](https://github.com/wesnoth/wesnoth/pulls?q=is%3Apr+is%3Aopen+label%3APostponed) after the release 1.18.

Are you meaning "postponed, and only done in 1.19" or "postponed and done in 1.18.1"? I'm assuming you mean 1.19.

I thought the biggest problem with string changes was having them land after the 1.x.0 release, so that a game that was fully translated at launch time becomes not fully translated again in a maintenance release. Is that assumption wrong?

> I [don't think] a couple of string changes will change the problematic nature of the story told in this campaign

We disagree on whether eating sapient races is problematic enough to require changing the story. If you're feeling that the change in this PR is only the same level of importance as that, then I should probably postpone this PR (would wait for @CelticMinstrel 's opinion before closing it though). I opened #8124 because of a sentence that contained "infestation of (race) was destroyed", and I've opened this one because I'm judging "infesters" on its own with my judgement clouded by that other sentence. Do you feel this one isn't necessary for 1.18?

**Comment by demario-w** [comment]
> > Discussions on the remaining work is fine to be open now as the momentum is there, but changes could be easily [postponed](https://github.com/wesnoth/wesnoth/pulls?q=is%3Apr+is%3Aopen+label%3APostponed) after the release 1.18.
> 
> Are you meaning "postponed, and only done in 1.19" or "postponed and done in 1.18.1"? I'm assuming you mean 1.19.

I think "postponed" means delayed until after the branch split (stable/devel). I also think that a recent update of the [rules](https://forums.wesnoth.org/viewtopic.php?p=656757#p656757), exclude any major change in stable cycle. So yeah, you need to follow that and do the changes in 1.19 for 1.20.
 
> I thought the biggest problem with string changes was having them land after the 1.x.0 release, so that a game that was fully translated at launch time becomes not fully translated again in a maintenance release. Is that assumption wrong?

Both are bad. This case is worse but has been sorted by the rule update. The other case (change during string freeze before 1.x.0) is also bad as it moves the target of full translation further away (and creates trouble as the reaction of that new Polish translator here-above shows).

> We disagree on whether eating sapient races is problematic enough to require changing the story.

OK. rofl

**Comment by stevecotton** [comment]
Do you feel this one isn't necessary for 1.18?

**Comment by nemaara** [comment]
Better be absolutely sure this is totally necessary and worth breaking string freeze over if you want to add it in now.

**Comment by CelticMinstrel** [comment]
I think it's necessary to make this change, but I don't have a strong opinion on whether or not it should break string freeze.

**Comment by Jonathan-Kelly** [comment]
I do not have a strong feeling about this either way.

**Comment by Pentarctagon** [comment]
I don't think this needs to break string freeze.

**Comment by stevecotton** [comment]
Thanks all, I misjudged the priority of this one.

**Comment by Hejnewar** [comment]
> Strange how different it feels now, with [the boot on the other foot](https://idioms.thefreedictionary.com/boot+is+on+the+other+foot), isn't it?

Dont assume things. This was for so many reasons. Listing:
- how long was it to actually review this campaign? 
- how many changes in string frezze were already made this time?
- actual anti translator stuff that made me angry way earlier and I actually care about well only my translators but w/e
- im not a nice person

**Comment by CelticMinstrel** [comment]
I don't really think there's a need to close it, we can merge this after 1.18 is released.

Though it could also be reopened at that time.

**Pull request closed without merging**
