### PR TITLE
extent fix halo to advance debug and create_unit and put_unit

### PR DESCRIPTION
**Pull request by newfrenchy83**
i expect what it is not spacing problem

### CODE REVIEW

**Comment by newfrenchy83** [comment]
create_unit_in_same_loc_of_mage_of_light
halo_remain_after_advance_or_debug_unit
halo_remain_after_normal_kill
@jyrkive i post this files for you look what debug_kill and erase_unit aren't only function to fix

**Comment by jyrkive** [comment]
I merged the fixes for the following situations:

- unit is killed with `[put_unit]`
- a developer adjusts unit's properties with `:unit`
- a developer replaces the unit with another by using the "Create Unit" debug option

I merged them as commit c6408dbd9536f2d1a8e80705dae9e04ccbc64005.

Your other "fixes" I rejected:

- when a unit advances, its halo is supposed to stay. I'm not aware of any unit that has a halo before advancing but not after it.
- the halo already disappears like it should when a unit is killed normally.

**Comment by Arcanister** [comment]
[advance_unit] is sometimes used to downgrade it, like in [Secrets of the Ancients](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/Secrets_of_the_Ancients/utils/sota-utils.cfg#L203)

**Comment by newfrenchy83** [comment]
It's true what halo disapear in 80-90% of attack kill but if unit die just after have be changed then halo remain. It's not current but it exist

**Pull request closed without merging**
