### PR TITLE
Fix ai error

### PR DESCRIPTION
**Pull request by gfgtdf**

### CODE REVIEW

**Comment by knyghtmare** [comment]
What AI Error did this exactly fix? I see no linked issue nor do I see any summary of what the fix is

**Comment by gfgtdf** [comment]
?, Its both there in the second commit

**Comment by knyghtmare** [comment]
I meant the PR description where I see "no description provided".

**Comment by gfgtdf** [comment]
Well yes, i assumes that people that are interested would just look in the commit, there werent that many that it really needed a summary.

**Comment by Pentarctagon** [comment]
Is there any way to have it evaluate a formula instead of treating it like it doesn't exist?

**Comment by CelticMinstrel** [comment]
Looks like this is the cause of #8297.

**Comment by gfgtdf** [comment]
It's not the cause, the error was there before, it's just that the fix didn't work correctly.

**Pull request merged**
