### PR TITLE
make macro definitions accessible from Lua

### PR DESCRIPTION
**Pull request by vn971**
The goal is to make some of the macro definitions
easily accessible from Lua code.

Not all definitions were handled --
only some of those that are expected
to be used in real Lua addon code.

--
Tested locally by overriding --data-dir

UPD: I had to use `_final.cfg` to make sure this macro runs when others were already initialized. I could of course place it in a correct file by checking alphabet order of existing files, but I'm not sure which approach is better here.

### CODE REVIEW

**Comment by gfgtdf** [comment]
first:

> `# {MACRO_TO_LUA ABILITY_FEEDING}  # doesn't work because of unbalanced WML tags`

this is wrong

> `{MACRO_TO_LUA ABILITY_LEADERSHIP_LEVEL_5}`

this is deprecated

second:

I think it'd be better to just write a script that gather all abilitites/trait from all unit types, since woudl have some advantages
1) it woudl mean no overhead in case that it's not used whihc shodul be the default case.
2) it would add umc unit abilitites aswell.

and i don't see any advantages, note that even trait aged is there (fog_clearer), in partiticular this will al least give you all abilitites theat appear in help since this is what the help browser does aswell.

third:

there were some plans to somehow mk unit abilitites only references to a global ability list, in case that this still has a >0% chance of heppening we shoudl design this to b somehow forward compatible for that.

**Comment by vn971** [comment]
@gfgtdf what exactly is "wrong" about feeding? If I wesnoth just fails to expand this ability if I uncomment it.

I can remove the leadership thing for sure, yes.

2. indeed. There is a slight technical problem with that though: calling `for k,v in pairs(wesnoth.unit_types) do end`  is very, very slow somewhy. I should probably report this separately, but currently, invoking such a code will have severe time penalties for cfg initialization.

3. well, if at some point we will refer to abilities by their id-s, then we will neither use macros nor those variables for new code anymore. Or do you hint to the fact that we may not need those variables after all, since we might deprecate such an approach altogether? Sounds valid actually, modulo the fact that we're not sure "ability referencing" is actually good. Is there some agreement on that topic?

**Comment by gfgtdf** [comment]
> @gfgtdf what exactly is "wrong" about feeding? wesnoth just fails to expand this line if I uncomment it.

you are probably testing on 1.12 again?

**Comment by vn971** [comment]
Ok, I think it doesn't worth it, for now. Thanks for the comments anyway.

**Comment by CelticMinstrel** [comment]
> there were some plans to somehow mk unit abilitites only references to a global ability list, in case that this still has a >0% chance of heppening we shoudl design this to b somehow forward compatible for that.

That's why I was suggesting this sort of solution, actually, except stored in places like `wesnoth.abilities` rather than `wesnoth.macros`; because once we do the global ability list thing, that's where I'd probably put it.

**Pull request closed without merging**
