### PR TITLE
Another fix for animation truncated after message in stable branch

### PR DESCRIPTION
**Pull request by newfrenchy83**
I post this PR for propose a fix of animate for master branch

### CODE REVIEW

**Comment by Vultraz** [comment]
Ah, this was actually already fixed on master. This fix would only be needed in 1.14. Does it work there?

**Comment by newfrenchy83** [comment]
yes it work on 1.14. but what fix has put in master?

**Comment by newfrenchy83** [comment]
https://github.com/wesnoth/wesnoth/commit/56111818e972332391d520ad900cccfdb4a23ec0 it is not a fix but a workaround in Thot. the prpblem is not fixed in engine or lua code.

**Comment by newfrenchy83** [comment]
the problem is in S1of EI too with Dacyn and Mal ravanal disapearrence

**Comment by newfrenchy83** [comment]
@Vultraz i not find a fix in master orher what the workaround akready mentioned. This fix is needed in 1.14 but in master too. But like master ins not playable yet, i work on 1.14 source code for testing.

**Comment by Vultraz** [comment]
The fix isn't a specific commit, but rather the general refactoring of the rendering engine that has occurred so far on master. Now, I'm not 100% sure the bug was fixed, but I'm pretty sure it was. If you can repro it, then perhaps this fix is also needed in some form on master, but otherwise it's only needed on 1.14.

**Comment by newfrenchy83** [comment]
Master branch is playable now? Else i cannot test if fix is needed in master too.

**Comment by Vultraz** [comment]
It runs, but there's no in-game UI (sidebar, menu bar, etc) or editor. But you should still be able to view [message]s and test the bug since launching a game is possible.

**Comment by newfrenchy83** [comment]
@Vultraz dacyn and mal ravanal animations get played in master. this fix will be needed in 1.14 only. but what fixes in master branch reolved the problem?

**Comment by newfrenchy83** [comment]
https://github.com/wesnoth/wesnoth/milestone/15

**Pull request closed without merging**
