### PR TITLE
Prepend 'SDL2/' to all SDL includes

### PR DESCRIPTION
**Pull request by Vultraz**
This was needed to get the build working with vcpkg's version of SDL, where all the SDL files are
in their own SDL folder. However, our cmake config also has a note saying it was a deliberate choice
to move our SDL files *out* of their SDL2 folder due to certain distros (FreeBSD is mentioned) not
putting the files in said folder in the first place.

Testing here to see what breaks...

### CODE REVIEW

**Comment by Pentarctagon** [comment]
Is there anyone who'd be able to check FreeBSD (or any of the *BSDs, I guess)?

**Comment by Vultraz** [comment]
Not that I know of. Is it a widely-used distro?

**Comment by Pentarctagon** [comment]
I don't know.  The BSDs aren't linux though, so they aren't really distros.

**Comment by Vultraz** [comment]
...They're not? p_p

**Comment by Pentarctagon** [comment]
Nope.  Linux originated from the first release Linus Torvalds created, while the BSDs all descend from the original BSD created by University of California, Berkeley.

**Comment by soliton-** [comment]
There's bound to be an option for whatever compiler you're using there to add an include directory, no need to rewrite all includes. cl.exe for example uses `/I`.

**Comment by jostephd** [comment]
@soliton- On Debian both /usr/include/SDL/SDL.h and /usr/include/SDL2/SDL.h exist, so `#include <SDL.h>` might pick either one of them (whichever is first in the include path) but `#include <SDL2/SDL.h>` would always pick the right one.

**Comment by jostephd** [comment]
> Is there anyone who'd be able to check FreeBSD (or any of the *BSDs, I guess)?

The packagers, I guess? wen@FreeBSD.org for FreeBSD (https://svnweb.freebsd.org/ports/head/games/wesnoth/Makefile?revision=499026&view=markup#l11).

**Comment by soliton-** [comment]
@jostephd why would we assume that the build system is not configured correctly? What else does it do wrong? Doesn't seem useful to try to protect from that by hardcoding an arbitrary path. Unless the path is not arbitrary and it is somewhere mandated where your SDL2 include files need to be.

**Comment by jostephd** [comment]
> @jostephd why would we assume that the build system is not configured correctly? What else does it do wrong? Doesn't seem useful to try to protect from that by hardcoding an arbitrary path. Unless the path is not arbitrary and it is somewhere mandated where your SDL2 include files need to be.

I'm not proposing to hardcode an arbitrary path. I'm simply saying there _is_ a reason to rewrite all includes. If our code says `#include <SDL.h>`, then the directory containing SDL2 headers would be in the include path. If the directory containing SDL1 headers would _also_ be in the include path (for whatever reason), then the #include directive might pick up the wrong file, sdl1's SDL.h instead of sdl2's SDL.h. That won't happen if our code says `#include <SDL2/SDL.h>`.

**Comment by CelticMinstrel** [comment]
> Not that I know of. Is it a widely-used distro?

According to DistroWatch as of this writing, there are five BSD distributions in the top 100, the most popular of which is FreeBSD which sits at 26th most popular. (Though BSD isn't Linux, I think it's still fair to use the term distro for them.)

> Ideally we'll set up a *BSD build in Travis.

…Travis doesn't support that, does it?

> There's bound to be an option for whatever compiler you're using there to add an include directory, no need to rewrite all includes.

I more or less agree, but from my understanding Vultraz had trouble figuring out how to do this in a machine-agnostic manner (and I think also how to do it without hindering vcpkg's automatic include path additions).

**Comment by soliton-** [comment]
@jostephd still reads to me like "the build system is broken, let's try to fix it by mandating an arbitrary path for SDL2 headers". You might as well mandate the header being called SDL2.h but apprently the SDL devs did not see using the same header filename as an issue. Trying to guard against build environments which include random directories with files that may match some include in our code seems futile.

Apart from BSD or any other distro not using the same path for SDL2 headers, anyone installing SDL on their own should also be able to choose the path they want. There should be a good reason to disallow this and potentially broken build environments are not it IMO.

**Comment by jostephd** [comment]
It's not an arbitrary path. It's a path hardcoded by SDL's own build system. If you build SDL with `configure --includedir=/foo`, it installs its headers to `/foo/SDL2/*.h`. That `SDL2/` path component is hardcoded in SDL2's makefile.

I think it's fair to say that there are two different approaches to this. One approach is to for every application that uses either version of sdl to use `#include <SDL.h>` style includes and manually pass some `-I /bar` switches to the compiler. The value of `/bar` needs to be provided manually unless something like pkg-config provides it. Another approach is for applications to use `#include <SDL2/SDL.h>` style includes and trust that sdl2 was installed into the compiler's default include path. This way applications don't need to specify custom include paths to the compiler.

**Comment by GregoryLundberg** [comment]
Personally, I'd suggest that any system with both SDL and SDL2 in the include path has more problems. The best way to fix this, to my mind, is to tell the builder that we need SDL2 and if their system has both, they need to be sure the correct one is chosen.

So I'm for the first of @jostephd's options: set your include path properly, either on the command line or in the environment like you should have done all along.

**Comment by Vultraz** [comment]
Conflicts between SDL1 and 2 aren't why I want to make this change. I want to make this change because it appears the standard location for SDL2 headers is in the `SDL2` folder, and assuming they are not there causes problems with vcpkg.

**Comment by soliton-** [comment]
Indeed if SDL2 mandates the SDL2 path in its makefile it makes sense to expect that. Then I'd wonder if/why some BSD would do it differently but that's most likely their problem to solve then.

**Comment by GregoryLundberg** [comment]
I don't see how our source code effects vcpkg.

I see vcpkg specifically shows SDL2 as an example package. If you start on a fresh system and install it using their process does SDL2 get added to the standard search path? If so, then we should not add it to our #include directives. If, on the other hand, the SDL2 package installs and places the SDL2 directory in a standard search location without adding it to the path, then, yes, we should add SDL2/ to our #includes's.

**Comment by Vultraz** [comment]
Yes, when installing SDL 2 with vcpkg the SDL files get put in their own `SDL2` folder, just like Boost files go in their own `boost` folder.

**Pull request merged**
