### PR TITLE
Replace problematic mushroom base terrain

### PR DESCRIPTION
**Pull request by slavrenyuk**
This PR is an update to this one https://github.com/wesnoth/wesnoth/pull/4185

It replaces problematic base terrains (namely `Ss`, `Ha` and `Mm`) which are incorrectly displayed under the `^Uf` overlay. Instead of those terrains, `Uu` is used now. The issue is described here https://forums.wesnoth.org/viewtopic.php?p=646099#p645168

Screenshot of the problematic base terrains before the fix. `Ss` and `Mm` base is not hidden. `Ha` has incorrect (snowy) transition.
problematic_mushroom_base_terrains

### CODE REVIEW

**Comment by stevecotton** [comment]
I'd prefer if this was fixed by fixing the graphics instead of changing the maps, because it will also affect UMC.

**Comment by nemaara** [comment]
This should probably wait until mixed terrains are implemented (see #4213). As stevecotton says, this will break UMC and can't go in 1.14 if it simply removes terrain codes without equivalent alternatives. Even for 1.15, it would be additional work for UMC authors that might end up being unnecessary if/when mixed terrains are made after.

**Comment by slavrenyuk** [comment]
https://github.com/wesnoth/wesnoth/pull/4185 was reverted, perhaps this PR should be closed.

**Comment by CelticMinstrel** [comment]
Agreed.

**Pull request closed without merging**
