### PR TITLE
Emulate weapon specials in abilities for development

### PR DESCRIPTION
**Pull request by newfrenchy83**

### CODE REVIEW

**Comment by jostephd** [comment]
What pull request is this a new version of? #3287?

**Comment by jostephd** [comment]
@newfrenchy83 I see. I closed the old PR and pushed 392d75c9a14a76174a1a1655a04a228076d22121 to fix the project files. Next time, please do a separate PR for project files, and if a PR becomes obsolete close it yourself and link the old and new PRs. Thanks!

**Comment by newfrenchy83** [comment]
At last.

**Comment by GregoryLundberg** [comment]
Looks like you picked up commits from another PR and need to rebase to clean things up.

**Comment by newfrenchy83** [comment]
I tried but i can t rebase after revert changes

**Pull request closed without merging**
