### PR TITLE
Fixed hard-coded word order in attack_type::describe_modification

### PR DESCRIPTION
**Pull request by gunchleoc**
- Replaced _ with vgettext
- Replaced _n with vngettext
- Set_damage now uses set_damage rather than increase_damage
- Add missing utils::print_modifier to increase_movement

Fixes https://gna.org/bugs/?25468

### CODE REVIEW

**Comment by gunchleoc** [comment]
Does anybody know where these strings are used? I was unable to get them on screen for testing.

**Comment by Vultraz** [comment]
There's some rather excessive indent in your commits. Could you reduce it? As for usage, I'm not sure off the top of my head.

**Comment by gunchleoc** [comment]
Indents should be fixed now.

**Comment by gfgtdf** [comment]
Note that in most of these cases `$number` isnt nesearily a number but can also be percentage, like `10%`, so form lookiing at the code it seems like it would result in '1% strike' and '10% strikes' not sure whther that's a problem though.

**Comment by gunchleoc** [comment]
That is actually important for translators! In the case of "$percent|% accuracy", it's explicitly part of the string, so translators will know. So, are there more percentages here where I can't see that they're percentages? We need to make this clear with the names of the placeholders.

I have a hard time tracking the actual usage of these and eventually failed. It all dead-ends at the Lua interface and I didn't trawl through the WML. So, any pointers will be appreciated :)

**Comment by gfgtdf** [comment]
Well the varabiels like `increase_attacks` or `set_damage` come from attribute values, you can see teh documentation here https://wiki.wesnoth.org/EffectWML it usually says soemthing like 
> can be positive or negative, or a percentage

a percentage value mens that the damage or number of strikes is increased by that percentage (and rounded)

**Comment by gunchleoc** [comment]
Thanks, that helped, although I still can't see them on screen.

I would still like to be able to add comments for the translators (which currently only happens with WML), and I found out where to change the xgettext options, but not where you run xgettext. The [Wiki page](https://wiki.wesnoth.org/GettextForWesnothDevelopers) is hopelessly outdated.

**Comment by CelticMinstrel** [comment]
Excellent! Somehow I didn't think of this issue when I was working in that area of the code. I'm not quite clear, is this ready to merge or not?

**Comment by gunchleoc** [comment]
It can be merged - I can always work on adding translators' comments at a later stage.

**Pull request merged**
