### PR TITLE
(1.17/1.18)remove deprecated backstab option

### PR DESCRIPTION
**Pull request by newfrenchy83**
Backstab attribute option deprecated, we could remove that, isn't it?

### CODE REVIEW

**Comment by soliton-** [comment]
Is there a specific reason to do this?

**Comment by Pentarctagon** [comment]
If we say something is deprecated and then state the version it will be removed in, then we should probably remove it. Otherwise there isn't really a point to providing the version.

**Comment by soliton-** [comment]
> Deprecated preemptively — This deprecation level is the one which should be aimed for the vast majority of the time. Obsolete APIs which can be implemented in terms of a simple minimal-maintenance wrapper should be deprecated, but left in the code indefinitely. At such time as an obsolete API presents itself as an active obstacle toward further development, it can be slated for removal in the next release, or even removed at will immediately, so long as it has already survived a minimum deprecation period of at least one stable release version.

Maybe the idea is that the deprecation level was wrong?

**Comment by newfrenchy83** [comment]
Must i repull DEP_LEVEL::PREEMPTIVE in code?

**Comment by soliton-** [comment]
> Must i repull DEP_LEVEL::PREEMPTIVE in code?

I can't tell what that means.

Can you explain why you're doing this? Are you aware of the [deprecation policy](https://wiki.wesnoth.org/CompatibilityStandards)?

**Comment by CelticMinstrel** [comment]
_Was_ it deprecated in 1.15? Not in 1.13?

**Comment by Pentarctagon** [comment]
Looks like it was deprecated in 1.13.5 over 6 years ago: https://github.com/wesnoth/wesnoth/commit/c761a80bd53a9537e09a7008ad9c17031e7604ca#diff-468254ac2424b59830c0606b5ab37eb3cd1863fa0394b505c7484c4e9945622f

**Comment by mesilliac** [comment]
Apologies for the conflict from the indentation commit i just pushed - that was formatting only, so whatever this PR was doing should probably take precedence.

**Comment by Pentarctagon** [comment]
So for the record, I'm fine with this being removed. If something is deprecated with a version it will be removed on, then that's the version it should be, well, *removed*, not the version where we all again start debating whether it should actually be removed or not. I'll leave this open for a few more days, but otherwise I don't see any reason to let this sit here open forever like it seems a lot of PRs have ended up doing.

**Comment by CelticMinstrel** [comment]
> If something is deprecated with a version it will be removed on, then that's the version it should be, well, _removed_, not the version where we all again start debating whether it should actually be removed or not.

I have a slightly different take. Removing something takes effort. The version given is the minimum version at which something _can_ be removed, but there's no requirement that we _do_ remove everything marked for removal in a given version before releasing the version. So… it's not the version where it absolutely must be removed, but it's also not the version where we start debating over whether to actually remove it. There shouldn't be any debate over removing deprecated stuff in the version it was marked to be removed in; if someone chose to put in the work to do the removal, I don't see any reason not to accept it.

**Comment by soliton-** [comment]
> So for the record, I'm fine with this being removed. If something is deprecated with a version it will be removed on, then that's the version it should be, well, _removed_, not the version where we all again start debating whether it should actually be removed or not.

The deprecation policy clearly says:

> Obsolete APIs which can be implemented in terms of a simple minimal-maintenance wrapper should be deprecated, but left in the code indefinitely. At such time as an obsolete API presents itself as an active obstacle toward further development, it can be slated for removal

There seems to be either a misunderstanding or disagreement with the deprecation policy or the deprecation level that was assigned. Or this actually is an obstacle to further development that hasn't been mentioned yet.

It's certainly not true that this was deprecated with a version it will be removed on. That is not how the `PREEMPTIVE` level works but the `FOR_REMOVAL` level.

> I'll leave this open for a few more days, but otherwise I don't see any reason to let this sit here open forever like it seems a lot of PRs have ended up doing.

Certainly it can just be closed unless some kind of reason is given.

**Comment by CelticMinstrel** [comment]
> Obsolete APIs which can be implemented in terms of a simple minimal-maintenance wrapper

Hmm, well, this description doesn't fit this API…

And I could definitely see an argument that it presents an obstacle to further development, since it's a special case in the ability system that everything needs to continue to account for.

**Comment by Pentarctagon** [comment]
> Certainly it can just be closed unless some kind of reason is given.

I'd say that CelticMinstrel's most recent post is the reason.

---

More generally though, I'm starting to question why the preemptive deprecation level exists at all much less why it's "the one which should be aimed for the vast majority of the time". The other three deprecation levels give specific information to both UMC authors and developers on what to expect:
* Indefinite - this will continue to exist forever.
* For Removal - this will be removed in version 1.XX.
* Removed - this is already gone.

Then there's this other one:
* Preemptive - same as Indefinite, except actually this may be removed on or after `<some arbitrary version>` for `<some arbitrary reason>`.

I feel like this is not particularly useful to anyone - it doesn't tell UMC authors when they need to update their code by and it doesn't tell developers when the API should be removed. It's basically just a shrug and saying "It'll be removed at some point. Maybe."

**Comment by CelticMinstrel** [comment]
> * Indefinite - this will continue to exist forever.

Not quite… more like "this will continue to exist as long as it doesn't require maintenance".

> it doesn't tell UMC authors when they need to update their code by

Uhh, yes it does? They need to update their code by the specified version, other wise it _may_ stop working.

> it doesn't tell developers when the API should be removed

Okay, sure, it doesn't give developers an explicit time when it should be removed, sure. The idea is that it can be removed for almost any reason and without notification after the specified version (although removing it just for the sake of removing things should be discouraged).

**Comment by soliton-** [comment]
It seems `backstab=` could simply be replaced with https://github.com/wesnoth/wesnoth/blob/d8b8c5ea8024bf51959a6520cbb5bb6fd3a1c9f7/data/core/macros/abilities.cfg#L415-L421

If that is easy to do in code then I think that would be worthwhile to actually make it "a simple minimal-maintenance wrapper".

Also seems like the deprecation notice is not great. Especially if it's clear what the exactly equivalent new WML should look like it should just mention it explicitely. No vague "Use [filter_adjacent] instead." when that is 1) not the actual tag to use but a subtag (that isn't even used anymore in the mainline implementation) and 2) it's clear what the replacement should be in its entirety.

While we don't have to bend over backwards to keep everything compatible one of wesnoth greatest assets by now is all the user made content of which not everything is kept up-to-date but occasionally old addons do get ported to new versions and IMO it is worthwhile to make that as easy as possible if we don't have to sacrifice code quality. It's a good idea to simplify internal interfaces as done here but if it's cleanly possible we should keep the exernal functionality.

**Comment by Pentarctagon** [comment]
What would a simple minimal-maintenance wrapper look like here?

**Comment by Pentarctagon** [comment]
Would it be to insert the [filter_opponent] formula there?

**Comment by soliton-** [comment]
Yes, the idea is to put the `[filter_opponent]` WML where the `backstab` attribute is. Haven't checked how easy it is to do in code. If it's not easy then alternatively it could also be done by wmllint.

**Comment by newfrenchy83** [comment]
> @newfrenchy83 Is soliton's suggestion something you'd be able to do?

i don't tkink, ,no, and i don't see interest to modify boolean backstab for put in the wml. For me formula in [filter_opponent] make the work and other possibility can be encoded. backstab attribute is deprecated and easy to replace in wml code. I propose to remove that by consequentbut else, the message is suficient.

**Comment by soliton-** [comment]
If it's easy to replace in WML why can't the engine do it? Why doesn't the deprecation message say explicitly what to replace it with? It seems we're making it harder on addon authors than it needs to be and that means there is a good chance to lose content because of it.

**Comment by newfrenchy83** [comment]
> If it's easy to replace in WML why can't the engine do it? Why doesn't the deprecation message say explicitly what to replace it with? It seems we're making it harder on addon authors than it needs to be and that means there is a good chance to lose content because of it.

Ah, the depreciation message? Sorry, I misunderstood and I beg your pardon for the harshness of my answer, but this PR had slipped my mind and I had imagined that I was being asked to implement the formula in filter_opponent in the 'backstab attribute. I will close this PR and open another one with the new post.

**Comment by newfrenchy83** [comment]
> > If it's easy to replace in WML why can't the engine do it? Why doesn't the deprecation message say explicitly what to replace it with? It seems we're making it harder on addon authors than it needs to be and that means there is a good chance to lose content because of it.
> 
> Ah, the depreciation message? Sorry, I misunderstood and I beg your pardon for the harshness of my answer, but this PR had slipped my mind and I had imagined that I was being asked to implement the formula in filter_opponent in the 'backstab attribute. I will close this PR and open another one with the new post.

message changed in https://github.com/wesnoth/wesnoth/pull/7021 pr

**Comment by stevecotton** [comment]
I merged #7024 (the PR that changes it from `PREEMPTIVE` to `FOR_REMOVAL`) thinking that there was support from @CelticMinstrel for that change, and now I'm rereading this I just imagined that. Should I revert it?

**Comment by newfrenchy83** [comment]
> I merged #7024 (the PR that changes it from `PREEMPTIVE` to `FOR_REMOVAL`) thinking that there was support from @CelticMinstrel for that change, and now I'm rereading this I just imagined that. Should I revert it?

if @CelticMinstrel don't oppose to that, then you can let like this.

**Comment by CelticMinstrel** [comment]
> And I could definitely see an argument that it presents an obstacle to further development, since it's a special case in the ability system that everything needs to continue to account for.

This quote from my earlier post reads like token support to present me. That is to say, I'm not strongly in favour of it but not against it either.

Removing all the backstab logic but keeping the deprecation message along with code that substitutes the formula Soliton noted would also be a reasonable alternative. In that case, you'd probably push the deprecation level in the opposite direction, to INDEFINITE.

**Comment by newfrenchy83** [comment]
> > And I could definitely see an argument that it presents an obstacle to further development, since it's a special case in the ability system that everything needs to continue to account for.
> 
> This quote from my earlier post reads like token support to present me. That is to say, I'm not strongly in favour of it but not against it either.
> 
> Removing all the backstab logic but keeping the deprecation message along with code that substitutes the formula Soliton noted would also be a reasonable alternative. In that case, you'd probably push the deprecation level in the opposite direction, to INDEFINITE.

if i push level to INDEFINITE, i cannot remove the backstab logic to hard code. if remove the code, the level must be push to REMOVED to inform the wml develloper what backstab attribute don't work anymore.

**Comment by CelticMinstrel** [comment]
> if i push level to INDEFINITE, i cannot remove the backstab logic to hard code. if remove the code, the level must be push to REMOVED to inform the wml develloper what backstab attribute don't work anymore.

If you remove the code, then yes, it should be changed to REMOVED. However, if you remove the code but add logic alongside the deprecation message that writes the tag @soliton- mentioned into the WML, that means backstab will continue to work even without all the supporting code, so it can be changed to INDEFINITE.

**Comment by newfrenchy83** [comment]
@CelticMinstrel i cannot write the formula code in massage because a quotation marks problems in formula, this why a added refrence to abilities.cfg and WEAPON_SPECIAL_BACKSTAB for whatdevelloper know what sepcial work with this code and noanymore backstab attribute

**Comment by CelticMinstrel** [comment]
That statement makes no sense whatsoever.

**Comment by newfrenchy83** [comment]
@CelticMinstrel INDEFINITE pushed in https://github.com/wesnoth/wesnoth/pull/7031 PR

**Comment by CelticMinstrel** [comment]
I don't know how you got that (d5535a866a0a376dffe391d651e32923d81bca1a) from what I said. That was nothing like what I said.

**Comment by Pentarctagon** [comment]
@newfrenchy83 celticminstrel's statement was not about adding it to the deprecation message. It was about adding that WML into the weapon special config.

**Comment by newfrenchy83** [comment]
itring but i don't find how.

**Comment by CelticMinstrel** [comment]
It's definitely not a trivial thing. The current message is in a place where the config is const, so you'd need to move it to somewhere completely different, and I don't know where that place would be.

**Comment by stevecotton** [comment]
I've created issue #7032 so that discussion is easier to find later, instead of being hidden from the issues' search list.

**Pull request closed without merging**
