### PR TITLE
AOI: Remove unnecessary trait

### PR DESCRIPTION
**Pull request by sigurdfdragon**
Leaders don't need loyal.

### CODE REVIEW

**Comment by ln-zookeeper** [comment]
Then the trait should be added to her in the next scenario.

**Comment by sigurdfdragon** [comment]
@ln-zookeeper
Not sure what you mean, Linaera is always a leader in this campaign & able to recruit mages.

**Comment by ln-zookeeper** [comment]
Right... I looked at the commit logs, and it seems she was accidentally made into a leader in 70974d49 way back in 2011 and after that everyone has just assumed it's intentional. She wasn't intended to be a leader, but after this much time I'm not sure whether it makes sense to make her a loyal non-leader as originally intended, or to keep the current behavior. The latter would require actually telling the player of it, of course.

**Comment by sigurdfdragon** [comment]
Unless there's any objections, I'll make a pr to add scenario objective notes in S5 & S6 informing the player that Linaera is a leader who can recruit.

**Pull request merged**
