### PR TITLE
HttT: fix grammar in Moremirmu's farewell

### PR DESCRIPTION
**Pull request by jostephd**
Add missing comma.  Also remove the word "here" because it felt redundant.

### CODE REVIEW

**Comment by Vultraz** [comment]
I think it was better with the `here`.

**Comment by GregoryLundberg** [comment]
But it does need a comma .. "here, my brothers"

**Comment by jostephd** [comment]
Thanks. Changed. Should I squash the commits?

**Comment by Vultraz** [comment]
Yes, please.

**Comment by jostephd** [comment]
Done.

**Pull request merged**
