### PR TITLE
fix berserk continue the fight to almost infinite if value negative(1.14)

### PR DESCRIPTION
**Pull request by newfrenchy83**
….14 version)

### CODE REVIEW

**Comment by jyrkive** [comment]
The line isn't too long yet. Please remove the intermediate variable.

**Comment by jostephd** [comment]
This is the 1.14 version of https://github.com/wesnoth/wesnoth/pull/4086

**Comment by sevu** [comment]
I think this would cause OOS with older 1.14 clients and can be 1.15 only.

**Comment by CelticMinstrel** [comment]
> I think this would cause OOS with older 1.14 clients and can be 1.15 only.

While technically true, I think in practice no-one would've actually saved a replay where a berserker fought for MAX_INT rounds. Who would ever wait that long?

If you're really worried about OOS I suppose we could use `max` instead of `clamp` on 1.14 - avoid negative values but allow deliberately-ridiculously-high positive values.

**Pull request closed without merging**
