### PR TITLE
Restore defence modifier display in side-bar

### LINKED ISSUE #3693: Sidebar terrain defense modifier truncated
The terrain defense modifier is truncated. This happens on master but not on 1.14. Probably need to fwdport 47bd5ade3726675c0d6e4e68af82004a01ddb63d (one of the two remaining commits on #3614).

screenshot_2018-11-06_23-54-18

### PR DESCRIPTION
**Pull request by Wedge009**
Tested against master, already resolved for 1.14, resolves #3693.

May be good for @hrubymar10 to double-check this. Submitting as PR because I'm not sure what the figures mean for the theme configuration plus I don't know if the second of the three lines changed (which conflicts with later changes in master) needs further adjustments.

### CODE REVIEW

**Comment by jostephd** [comment]
> Submitting as PR because I'm not sure what the figures mean for the theme configuration

See the explanation of `rect` in https://wiki.wesnoth.org/ThemeWML. If it's unclear, do ask.

> plus I don't know if the second of the three lines changed (which conflicts with later changes in master) needs further adjustments.

The `unit_moves` report generates the number of moves (remaining and overall), the "X/Y" text just under the text `MP` next to the unit's sprite in the sidebar. Try making both the number of moves and terrain defense wide (e.g., more than 10 moves remaining, and at least 20% terrain defense) and see if anything gets truncated.

**Comment by Wedge009** [comment]
Thanks. I was mainly concerned with the conflict with `label-mp`. I saw no difference between the offset of 14 vs 16, so I think this is fine to merge as it is, if you approve.

**Comment by jostephd** [comment]
I haven't tested this, but if you've tested it with the widest possible strings (10/10MP, 100/101XP, and whichever terrain defense value is the widest) and it doesn't truncate, then go ahead and merge it :)

The 100/101XP is needed for lvl3 versions with type advancements, like Arch Mage and Inferno Drake (when ENABLE_ARMAGEDDON_DRAKE is set).

Thanks for picking this up! :-)

**Comment by Wedge009** [comment]
A pity Sigurd's debug tools aren't in 1.15 yet. But it doesn't look like 10/10 will collide with the defence rating. I looked at 1.14 as well.

Thanks for your verification.

**Pull request merged**
