### PR TITLE
Slightly rewrite dialogue (fixes #3386)

### LINKED ISSUE #3386: NR - Epilogue, ambiguous wording
There is a line:
“If a chieftain refused to co-operate with the Alliance, he was forcibly removed from his post and another more favourably **disposed** put in his place.”
When I read this the first time I thought there is a word missing, because disposed doesn't just mean 'inclined', but also 'getting rid of'. So I tought it was supposed to say:
'..another more favourably one than the disposed one put in his place...' or '..another more favourably candidate/orc put in his place...'
I hope that in this case 'disposed' can be changed to 'inclined' or another clear (not ambigous) synonym.

### PR DESCRIPTION
**Pull request by Wedge009**
Some non-native English readers may find use of the word 'disposed' confusing.

(Using PR because I'm not sure of the process surrounding string freezes.)

### CODE REVIEW

**Comment by sevu** [comment]
@Wedge009 I was not sure if you are on IRC or Discord, could you change this in the British translation?
https://r.wesnoth.org/p632080

There is no String Freeze currently or being planned. They have been announced in the Discord topic the last times, and the IRC topic was not updated in time.

**Comment by Wedge009** [comment]
IRC isn't working for me for some reason at the moment (seems to be permanently trying to log-in). Why only change in en_GB? Does @Konrad22 have an opinion?

**Comment by Konrad22** [comment]
My guess is that @sevu was trying to ask you to do something about the bug he indentified (see his link), which (because it's in the translation files) has to be fixed in en_GB.
Basically making an additional commit to your PR here, merging the PR afterwards.

**Comment by Wedge009** [comment]
Ohhh, got it. I didn't realise the request was completely unrelated to this PR.

Will have to get IRC working again somehow...

**Comment by CelticMinstrel** [comment]
Might be worth trying the [webchat](http://webchat.freenode.net/)? Obviously a proper client's better, but if one connects and the other doesn't...

**Comment by Wedge009** [comment]
I just gave that a try a few minutes ago.

I hadn't changed my settings, but I just tested I can connect to both irc.wesnoth.org and irc.freenode.net (I presume wesnoth just redirects to freenode anyway). I get the server message, etc, but upon attempting to join #wesnoth or #wesnoth-dev I don't get any response. Actually, as I write this it might be related to the client. I'll do some more testing (though technically I'm supposed to be working at the moment...).

**Comment by Wedge009** [comment]
@sevu Found out it was freenode. What do you want me to do with en_GB? I can escape the ampersands, but isn't that still an issue in the original en_US cfg text?

**Comment by sevu** [comment]
Merging, as there is no more feedback.
As for the other issue, b1a1839 changed it in mainline.

**Comment by Wedge009** [comment]
Thanks.

**Comment by sevu** [comment]
You're welcome, feel free to merge things as well, you are already longer in the project active.

**Comment by Wedge009** [comment]
Longer maybe, but not as active. ;) I try to look through things when I have time, did #3378 recently.

**Comment by sevu** [comment]
That one I didn't wanted to look into as I started playing Liberty on 1.13 and didn't finish it =)

**Pull request merged**
