### PR TITLE
Port campaignd to asio

### PR DESCRIPTION
**Pull request by loonycyborg**
campaignd, the addon server is the last part of wesnoth that needs porting, merging this pr will drop SDL_net as dependency. This port is aiming to keep full functionality of campaignd.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Do you want me to push the XCode update to this branch? I probably won't get to it for another day or two, though.

**Comment by CelticMinstrel** [comment]
If I recall correctly, XCode already excludes SDL_net (since it doesn't have a target to build the campaign server), so I don't think I need to update anything here.

**Comment by loonycyborg** [comment]
There is a new source file, server_base.cpp. It's used by both campaignd and wesnothd

**Comment by CelticMinstrel** [comment]
Okay, in the case I'll probably get to that once I've got spirit-po to PR stage (which should be soon, I think).

**Comment by shikadilord** [comment]
Just in case wesnoth.org gets hit by a truck: the issues I originally encountered with this seem fixed so it should be good to go after @loonycyborg deals with the merge conflicts. Make sure to keep me informed when the merge happens so I can rebuild the 1.13 and testing instances on wesnoth.org accordingly and keep an eye on them.

**Comment by Vultraz** [comment]
Please also do ensure all the new code uses appropriate stdlib functions (such as std::bind) when applicable instead of their boost counterparts.

**Pull request merged**
