### PR TITLE
fire theme_reset event after theme was changed

### PR DESCRIPTION
**Pull request by gfgtdf**
probably not the prettiest fix, 4004

### CODE REVIEW

**Comment by shikadiqueen** [comment]
What does this do in practice though?

**Comment by gfgtdf** [comment]
as described on https://github.com/wesnoth/wesnoth/issues/4004  previous the replay_controller listenes to a reset_replay event that is destroyed  in that line, so we try to carry to  over to the new theme object.

**Comment by shikadiqueen** [comment]
Doesn't that gloss over the fact that the relevant themes (`Cutscene_Minimal` and `Cutscene`) as well as any other potential candidates for use with `[change_theme]`, do not or might not provide any replay controls, so if for whatever reason you are meant to stay with a different theme than a replay-suitable default you are going to lose the ability to control the replay anyway?

**Comment by gfgtdf** [comment]
hmm i thought the code in replay_cotnroller  would just take the [replay] tag from a global config  and not from the theme itself, so that it'd alway be available. I might have been wrong here.

In that case, can't we just add the the replay theme by using the same for as for the default theme to all of these themes?

**Comment by shikadiqueen** [comment]
That I can't tell you since I'm not well versed in theme WML or the underlying infrastructure. I just wanted to point out again that even if the themes in mainline are patched accordingly by hand, that doesn't mean that it will be done by WML authors when writing their own custom themes as well.

**Comment by Pentarctagon** [comment]
Closing as gfgtdf is no longer around and this fix is incomplete.

**Pull request closed without merging**
