### PR TITLE
Safer campaignd file commits

### PR DESCRIPTION
**Pull request by shikadilord**
See first commit message.

### CODE REVIEW

**Comment by GregoryLundberg** [comment]
A general comment based upon comments on IRC which may not apply here ...

You talked about signal handling and it occurs to me that you might want to consider the following definitions. These are generally how we thought of these 'back in the day' and it's up to you:

SIGINT -- An external change has occurred such as a configuration file. If possible, change to the new configuration for all new work; but allow all ongoing work to complete using the old configuration. Otherwise: perform a shutdown the same as SIGTERM, but the daemon should, however, return to normal service after loading the new configuration.

SIGTERM -- Shutdown requested. Do not accept new work, but finish any already started. At some point the daemon should actually shut down, but it may take a long time.

SIGKILL -- Panic shutdown. It is likely the entire system is going down very soon. Do the bare minimum to prevent corruption and shut down as quickly as possible.

**Comment by shikadilord** [comment]
@GregoryLundberg Your description of SIGINT sounds like the conventional handling of SIGHUP by Unix daemons, actually, not SIGINT. Also, per POSIX, SIGKILL and SIGSTOP to be unable to be caught or ignored, and Linux complies with this requirement. There's nothing a program can do about SIGKILL other than be designed with the possibility in mind (i.e. what this PR does).

**Comment by shikadilord** [comment]
Also, worth noting that SIGHUP *is* already handled with the expected semantics (schedule a config reload for the next processing cycle), and SIGTERM is as well (schedule orderly exit for next cycle) as of commit 019e7a72c741740650ea3930a6dfbfe50bde7c54.

**Comment by GregoryLundberg** [comment]
Well, OK. I guess I'm showing my BSD roots.

**Comment by gfgtdf** [comment]
I think std::remove and std::rename do not support utf8 filenames on windows.

**Comment by GregoryLundberg** [comment]
std::remove ???

I just checked and it appears Windows support for Unicode filenames uses utf-16le so I believe gfgtdf is correct.

**Comment by shikadilord** [comment]
@gfgtdf I don’t see much point into explicitly bringing Boost.Filesystem into the mix here since Windows is already an unsupported platform for this target (the master version won’t even build for Windows since PR #671 was merged) — hence I decided to not bother with Boost.Filesystem here after my disappointing experiences with it. Plus, the big WARNING comment.

**Comment by gfgtdf** [comment]
> Plus, the big WARNING comment.

Specially with his comment, it sounds like the atomic issue is the onyl issue this code has on windows.

> hence I decided to not bother with Boost.Filesystem 
But do already use or filesystem functions, the first part this line `filesystem::file_exists(dest_name_) && std::remove(dest_name_.c_str())` uses `filesystem::file_exists` instead  of whatever std provides but in the second part you decided to use `std::remove` instead of `filesytem::delete_file`.

**Comment by shikadilord** [comment]
@gfgtdf I was lazy and `fs::file_exists()` is more expressive than using `stat()`. And if you take a look at campaign_server.cpp you’ll see that this is not the only use of `std::remove()` a.k.a. C `remove()`.

I’m not sure why you keep insisting on this. Perhaps you are personally interested in being able to run this undocumented pile of crap on Windows? I really don’t see the point.

**Pull request merged**
