### PR TITLE
New Poacher & Trapper (ranged) Sprites/Animations

### PR DESCRIPTION
**Pull request by ghype**
This are [Jetrel's new base sprites](https://www.wesnoth.org/jetrel/Wesnoth/trapper-line.png) I started animating.

**What I have done:**
- animations as seen below
- adjusted the naming system as the current for the poacher/trapper was just so confusing
- adjusted the codes
- replaced the missing animations with base frames. melee animations soon to follow

Remaining animations/codes soon to follow.

**Poacher**
- [x] ranged attack
- [x] ranged defense

Poacher-Ranged-Animtaiton-9

**Trapper**
- [x] trapper ranged attack
- [x] trapper ranged defense

_trapper-bow-attack+defense-3

EDIT:
I decided to public this PR as it is without the melee animations for the Poacher and Trapper as I will make a new PR for that one. I have some animations for that already, but will need some more feedback before I commit them

### CODE REVIEW

**Comment by ghype** [comment]
I decided to public this PR as it is without the melee animations for the Poacher and Trapper as I will make a new PR for that one. I have some animations for that already, but will need some more feedback before I commit them

One can see the progress on the melee animations [here in the forums](https://forums.wesnoth.org/viewtopic.php?p=654824#p654824).

**Comment by Pentarctagon** [comment]
@doofus-01 Would you be able to review this?

**Comment by doofus-01** [comment]
Hi @ghype - thanks for working on this.  I'll look at it this weekend, I don't want to just lob quick-takes.  But current quick-take is that it looks like a good addition.

**Comment by doofus-01** [comment]
Quick note to say I'm finally reviewing this, I should have something constructive to add later today.

**Comment by ghype** [comment]
Honestly I am a bit confused as I am not quiet sure what is it is that you mean. I would very much appreciate if you could elaborate on the following:

> A blocker that is easy to fix: the poacher-attack[1-7].png frames need to be removed.
>so clean up the duplicate files and it's good to squash & merge.
 >

with "blocker" I assume you mean what ever hols this PR to be merged. Here you say that the ranged attack frames of the poacher should be removed. Because there are duplicates? The only duplicate I knew of was the frame 1 and frame 8 which does not longer exist as I eliminated it and adjusted the code to it.

> A nice-to-have change, but not a blocker for now: the trapper-bow.png frame could be more of a transition. 

I made this frame as I referenced frames and their naming of other existing mainline units with have both melee and ranged(bow) attacks. Purpose of this frame is so that the Trapper does not change to the base frame which shows the dagger. It would do that 4 times, that wouldn't be looking good.
I assume I could just rename the trapper-bow.png to trapper-bow-attack1 and adjust enumeration of the following frames. But practically that wouldn't change anything other then the renaming the files. 
So at this I am not sure if it really is that what you mean.

> The dagger looks little weird popping into view after the bow attack, almost like a switchblade.

That is true. I could try add an animation that shows how the trapper actually draws the dagger either from the front of the belt. For that I'd have to make add the dagger to the bow attack frames.Or I could even put the dagger at the backside of the belt but for that I had to redraw a lot more.

> It would be nice to get the updated sprites into the game, so clean up the duplicate files ...

So yeah, I am not sure which duplicates you mean and if you do mean the poacher-attack[1-7].png I would not see where the duplications would be.

Sorry if I not able to see what you mean.

**Comment by doofus-01** [comment]
> Honestly I am a bit confused as I am not quiet sure what is it is that you mean. I would very much appreciate if you could elaborate on the following:

    A blocker that is easy to fix: the poacher-attack[1-7].png frames need to be removed.
    so clean up the duplicate files and it's good to squash & merge.

>with "blocker" I assume you mean what ever hols this PR to be merged. Here you say that the ranged attack frames of the poacher should be removed. Because there are duplicates? The only duplicate I knew of was the frame 1 and frame 8 which does not longer exist as I eliminated it and adjusted the code to it.

poacher-attack6.png and poacher-bow-attack6.png are the same image, one of them has to go.

**Comment by ghype** [comment]
> poacher-attack6.png and poacher-bow-attack6.png are the same image, one of them has to go.

OOOk. This must have slipped through when adjusting to a better naming of the frames to avoid confusion when adding the melee animations. I deleted poacher-attack[1-7].png.

**Pull request merged**
