### PR TITLE
DM S03 Fix WML unit not found for role

### PR DESCRIPTION
**Pull request by GregoryLundberg**
Turn 4: simply skip the message if there is no bowman

Victory: Use the same bowman as turn 4, promote one if not present, recruit one if none present at all.

AOI and Liberty used macros. But only needed once, here, so coded inline.

### CODE REVIEW

**Comment by GregoryLundberg** [comment]
N.B. Commit cc45013d (DM S10 Missing defeat condition) adds two new translatable strings.

**Comment by GregoryLundberg** [comment]
After completing play-testing Delfador's Memoirs, these are my notes on console messages observed:

General messages

    warning ai/config: side 2: aspect with id=[version] lacks default config facet!
Confirmed to be coming from saved turns. Uncompressed and edited to remove the version= from an [ai] tag and the message no longer appears.

    error ai/engine/cpp: side 2 : UNKNOWN aspect[version*composite_aspect]
Appeared following loading a saved turn.

    libpng warning: iCCP: known incorrect sRGB profile
Seems to be randomly occurring. Is there a memory corruption going on? Sometimes this is consistent; sometimes not. I have the vauge impression it may be related to specific map tile images or special objects on the map.



Delfador's Memoirs, scenario 7, "Night in the Swamp"

    error config: Illegal tile in map: (Gs^Imb) 'Gs^Imb'

    error config: Error while loading the map: Illegal tile in map: (Gs^Imb) 'Gs^Imb'
    The map cannot be loaded.
Appeared upon loading the scenario into a fresh instance of the game.



Delfador's Memoirs, scenario 11, "Wasteland"

    error ai/actions: Error #2007 (E_NOT_REACHED_DESTINATION) in full move by side 3 from location 30,1 to location 31,4

    error ai/actions: Error #2007 (E_NOT_REACHED_DESTINATION) in full move by side 3 from location 30,2 to location 31,4
During battle.



Delfador's Memoirs, scenario 13, "The Return of Trouble"

    error ai/actions: Return value of AI ACTION was not checked. This may cause bugs! 
Seems to occur if one loads a game while the AI is moving.



Delfador's Memoirs, scenario 18, "The Portal of Doom"

    error ai/actions: Error #2007 (E_NOT_REACHED_DESTINATION) in full move by side 2 from location 19,23 to location 17,22
Same message occurring 5 times over several turns with same locations. This is side 2 leader, Prepolur, moving from his keep to a mountain two hex away. The hex between is flat dirt. Death Knight, moves 5. Flat cost: 1. Mountains cost: 3. The unit should be able to make this move.



Delfador's Memoirs, scenario 19, "Showdown in the Northern Swamp"

First turn, after KALENZ_REJOINS_DELFADOR with an unstore, Kalenz' movement is already completely used. He is standing on a hex which Delfador might use to recall into, and he cannot move to take a village. This seems wrong but I don't see what the issue is. Perhaps Kalenz was stored after moving and the unstore here did not reset for the new move?



Delfador's Memoirs, scenario 20, "Prince of Wesnoth"

    warning unit: Unknown attribute 'previous_recruits' discarded.
From loading the scenario file: DM-Prince of Wesnoth.gz
See ~/src/carryover.hpp ~/src/carryover.cpp and ~/src/teambuilder.cpp

**Comment by rjaguar3** [comment]
Thanks for fixing the S19 bug.  I looked at the documentation again, and the documentation suggests that the unit whose death caused the `last_breath` event to be fired shouldn't be counted in the `[filter_unit]`, yet I needed to make sure `count` was 2.

The campaign is not unwinnable if the player finishes S10 without any undead units.  In that unlikely instance, the S19 objective is changed to requiring Delfador to strike the final blow against Iliah-Malal.  I think this contradictory timeline is entirely satisfactory and should be changed before 1.14.  My suggestion would be to give the player loyal undead units at the start of S19 (or, less preferably, at the end of S10) if the player finishes S10 without any undead.  (The player does need to be trying in order to finish S10 without any undead, so I think it would make a great easter egg.)  Also, there should be more foreshadowing in S10 about the future need for undead veterans from that scenario in the campaign.

**Comment by GregoryLundberg** [comment]
I agree, the Wiki is unclear on what counts when. The comment in the WML lead me to the 2-99999 fix.

Yes, I didn't see the objective change at first and backed out my changes when I saw it. I guess I forgot to edit my notes accordingly. Sorry.

I originally simply added a lose condition to S10 and added the foe telling why. But, as I said, I backed that out when I spotted the objective change. I'm guessing that was a later addition since the comments in the WML said it would be unwinnable. I suppose I should remove that comment.

I agree, at the start of S10, there should be a premonition that you'll need undead later, or one of the undead can talk about it. And I sort of liked the fail-if-none-available objective. But all that adds translatable strings, and I am trying, real hard, right now, to not have my changes cause any more additional work than absolutely necessary.

Actually, when I play test I first do a quick run in debug killing and moving on. Any units in the recall list, I dismiss. What I'm trying to do is find the low-hanging 'no unit for role' messages, quickly; as well as any crashes or untoward messages on the screen or stderr. Only then do I do a code-read. After I've made all the changes I think I need, I do another run in debug, checking all events and try to get 100% code coverage in the WML. Only when I'm done to I do a final, no-debug, end-to-end at EASY run through the campaign, using my knowledge of the Easter Eggs I want, and taking the short-route whenever possible.

**Comment by GregoryLundberg** [comment]
On checking the comment, it's meant to imply that the objective is  Delfador XOR an undead. And, if the objective is undead (ONLY), there is no way to know that, after losing the last undead on the board, and running to the keep to recall one, the player dismisses all undead without recalling any, the scenario is unwinnable.

That can NOT be corrected by ANY WML changes except:

(a) allowing Delfador to recruit Ghosts and, optionally, Ghouls (depending on S10 actions), or

(b) changing the victory conditions (silently?) so that, even if it says "undead" it allows Delfador to deal the final blow.

Option (a) seems heavy-handed.

Option (b) actually fits with the spoken lines because, no matter what the objective is, Delfador tells Lionel that HE (Deflador) must strike the blow. There is no mention of his undead.

I vote for (b) .. comments?

**Comment by rjaguar3** [comment]
There is no WML event that fires on dismissal of a unit.  Because the player has to go out of their way to dismiss the only units that can help them win the scenario, I'm inclined to treat the issue of dismissal making the scenario unwinnable a won't-fix.  I think the objectives should stay as-is.

(I previously raised the issue of removing the ability to dismiss units and replacing it with the option to [temporarily] hide specific units in the recall list to avoid this issue and some others as well.  See [this previous discussion](https://forums.wesnoth.org/viewtopic.php?f=12&t=43007) in which there was some expressed developer support.  I'd consider making a PR myself, but I'm not that familiar with the save-file structure and how the Wesnoth GUI works.)

**Comment by GregoryLundberg** [comment]
Well, I can see arguments for and against. But, that's neither here now there, to me. My goal, at present, is to make the lightest possible changes to get the scenario running without **execution** error.

This is a design error. so I don't have a problem with leaving it as-is. I can agree that saying "Then, don't dismiss your undead." is (marginally) acceptable to the action making the scenario unwinnable. Remember, to make it unwinnable, you have to dismiss them with no undead on the board when you were told in the objectives you would need undead.  "Take gun, aim at foot, pull trigger" Well, duh!

**Comment by GregoryLundberg** [comment]
With the recent changes to [role] I have a much cleaner branch for Delfador's Memoirs.

I am closing this PR in favor of my new PR #694.

**Pull request closed without merging**
