### PR TITLE
Remove fallback logic from alignment_str() to work the same as alignment()

### PR DESCRIPTION
**Pull request by soliton-**
No caller was adjusted since IMO this is the correct behavior.

### CODE REVIEW

**Comment by newfrenchy83** [comment]
You don't put aligment optinnal directly into constructor? I had crash issue when i tried that.

**Comment by soliton-** [comment]
> You don't put aligment optinnal directly into constructor? I had crash issue when i tried that.

Can you give more details on what the issue is? If you have specific code that crashes then perhaps post it.

**Comment by newfrenchy83** [comment]
> > You don't put aligment optinnal directly into constructor? I had crash issue when i tried that.
> 
> Can you give more details on what the issue is? If you have specific code that crashes then perhaps post it.

I think what it's because i used std::optinal instrad of utils and after i don't want retried. I must test lua and filter but game work without issue for now.

**Comment by soliton-** [comment]
> I must test lua and filter but game work without issue for now.

To be clear you need to implement a fallback to the unit's alignment yourself now if wanted. Accessing alignment of a weapon will only return the actual weapon alignment or the empty string (I guess we could also make that `nil`) if there is none.

Same in a weapon filter, if fallback to unit alignment is wanted that needs to be done explicitly.

**Comment by newfrenchy83** [comment]
Everything works without crashing, and never mind if there is no fallback in filters and formulas

**Comment by newfrenchy83** [comment]
Since you removed the fallback you can move the alignment_str() function into hpp only

**Comment by CelticMinstrel** [comment]
Looks good to me.

> I guess we could also make that `nil`

I do think this would be a slight improvement, but that's a minor detail.

**Comment by newfrenchy83** [comment]
@soliton- i ad tishttps://github.com/soliton-/wesnoth/pull/21 PR in your repositorie.

**Comment by CelticMinstrel** [comment]
We discussed this on IRC/Discord and decided it would be better for filters _not_ to fall back to unit alignment. The reason is that, if it doesn't fall back, you can still construct a filter that handles the fallback; but if it _does_ fall back, you can't easily construct a filter that _doesn't_ fall back.

So, not falling back to unit alignment gives greater versatility.

**Comment by newfrenchy83** [comment]
> @soliton- i ad tis https://github.com/soliton-/wesnoth/pull/21 PR in your repositorie.

removed

**Comment by newfrenchy83** [comment]
@soliton-  i moved alignment_str() in attack_type.hpp and correct documentation in https://github.com/soliton-/wesnoth/pull/22 PR

**Comment by soliton-** [comment]
A different PR was merged without closing this one.

**Pull request closed without merging**
