### PR TITLE
moved {SOUND:POINSON} and {SOUND:SLOW} to deprecated-utils

### PR DESCRIPTION
**Pull request by sevu**

### CODE REVIEW

**Comment by gfgtdf** [comment]
your commit doesn't explain why these were moved there. Also your commit message should contain information about what should be used instead.

**Comment by CelticMinstrel** [comment]
From the comment, it seems like there's nothing to replace them - addon devs should simply remove them. I guess the sounds are played automatically when the relevant status is given?

**Comment by gfgtdf** [comment]
So the sounds will now played twice when this macro is used? then maybe we should replace that macro to expand to just nothing so that older files that use this macro still plays that those sounds correctly (only once).

**Comment by CelticMinstrel** [comment]
While you do kinda have a point... what if someone used these for an attack that doesn't confer the poison or slow status?

**Comment by CelticMinstrel** [comment]
While you do kinda have a point... what if someone used these for an attack that doesn't confer the poison or slow status?

**Comment by ln-zookeeper** [comment]
Yes, the sounds are now played automatically so the macros are no longer needed. I doubt anyone uses them in any unusual manner, since the contents pretty much make it impossible to do so, so it should be perfectly safe to make them empty. For example using {SOUND:POISON} to make an attack animation play the poison sound as a normal hits sound wouldn't work correctly, since then the sound wouldn't be played when hitting an enemy that actually is already poisoned.

**Comment by CelticMinstrel** [comment]
Well, that's true. I'm sure someone could come up with a rare case when that's actually wanted, but... well... rare.

**Comment by sevu** [comment]
I don't think that there would be a case there this would be wanted, ... rather that someone uses the sound:poison macro to play the poison sound as attack sound, and not taking care about the case when the unit is already poisoned.... which would be buggy anyway.

I did change them now to empty definitions. Maybe we can remove the macros with wmllint someday completely.

**Pull request merged**
