### PR TITLE
Updated changelog style

### PR DESCRIPTION
**Pull request by hrubymar10**
I have to do that because maximum size for textfield is 1000x1000 so full changelog doesn't fit there.

This should be also merged to 1.14 branch

### CODE REVIEW

**Comment by hrubymar10** [comment]
Can we merge this?

**Comment by hrubymar10** [comment]
@Vultraz , @jyrkive 

and from 'macOS team' @ancestral , @singalen , ( @GregoryLundberg ) , @mattsc , ( @CelticMinstrel )

**Comment by hrubymar10** [comment]
On request from @CelticMinstrel :

image

And at the end of changelog:
image

**Comment by CelticMinstrel** [comment]
Looks good, but I kinda think the link to the full changelog could instead be a link _below_ the box... this is good enough to merge though IMO.

I'll cherry-pick it to 1.14 first (probably after I deal with #2761), then merge it if it hasn't already been done by someone else before then.

**Comment by ancestral** [comment]
If possible, make it not editable. There shouldn’t be a cursor.

**Comment by hrubymar10** [comment]
It is already disabled by b0068db @ancestral

**Pull request merged**
