### PR TITLE
Various surface handling cleanups

### PR DESCRIPTION
**Pull request by Vultraz**
Bunch of cleanup to our surface utility functions, especially geared towards creating fewer temporary surfaces.

### CODE REVIEW

**Comment by Vultraz** [comment]
Just a note that I'll likely be pushing more to this, but comments along the way are welcome.

**Comment by aginor** [comment]
This is looking like a very nice start :)

**Comment by matthiaskrgr** [comment]
I had a look at 646ee1d using {A,UB}SAN.
While playing I noticed that sometimes units are rendered invisible:
inv_unit_snoth

**Comment by Vultraz** [comment]
I've merged the first 4 commits manually. As discussed with @aginor, the last two weren't the direction in which we want to go.

I also was unable to reproduce the issue reported by @matthiaskrgr, so I'm assuming it was an isolated incident. If more people report it on master, I'll have to look for a fix.

**Pull request closed without merging**
