### PR TITLE
Force console on Windows when --help is specified

### PR DESCRIPTION
**Pull request by techtonik**

### CODE REVIEW

**Comment by shikadilord** [comment]
This is a good change, but is there a particular reason you used ``or`` in the code instead of ``||``? We don't use the alternative plain-language operators in our code base.

**Comment by techtonik** [comment]
In Python pipes are invalid, so I just not used to them.

**Comment by techtonik** [comment]
Why tests failed?

**Comment by shikadilord** [comment]
Only one build failed due to a time-out. It's a quite common occurrence with Travis, so I decided to ignore it.

**Pull request merged**
