### PR TITLE
translation hint for planning mode

### PR DESCRIPTION
**Pull request by sevu**
... since I saw one language translating it literally.
Any remarks to the wording?

### CODE REVIEW

**Comment by Vultraz** [comment]
Looks alright to me.

**Comment by soliton-** [comment]
Is this the only place Whiteboard is mentioned? Perhaps there are more places where a hint is needed.

**Comment by sevu** [comment]
It's the only place.

**Comment by sevu** [comment]
Ideally this string should be marked as fuzzy, but we are in freeze (and for a good reason)

**Comment by soliton-** [comment]
More mentions of whiteboard in translatable strings:
https://github.com/wesnoth/wesnoth/blob/c04a13ec8ff0b60cb7893259518074acafaba32c/src/menu_events.cpp#L1253
https://github.com/wesnoth/wesnoth/blob/c04a13ec8ff0b60cb7893259518074acafaba32c/src/whiteboard/manager.cpp#L1114

**Pull request merged**
