### PR TITLE
1.17 Lower terrain

### PR DESCRIPTION
**Pull request by doofus-01**
This is a generalized version of what was requested in #6919.  You can create some awkward situations, but that's up to the map-maker.  It's at the border instead of the hex center (like "cliffs" would need to be) by design.

Known issues:
1.  It's currently an overlay that makes terrain unwalkable, needs some refinement somehow, probably separate unwalkable and base-movement terrains - the unwalkable version with some sort of indicator like the mountain peaks have.
2.  Needs some variations, this is just the default so far (very little new art at this first commit)

Screenshot_20220730_a

### CODE REVIEW

**Comment by doofus-01** [comment]
This now has the three-way transition with chasm and regular terrain, but still needs the water versions.
Screenshot_20220731_a

**Comment by CelticMinstrel** [comment]
> still needs the water versions.

I guess that refers to how the two giant holes in the middle of the pond don't have water flowing down the sides?

**Comment by doofus-01** [comment]
Yeah.  Water-low/dry-high is probably most important, but all three versions are pending.  And then there is snow.  This can be a can of worms.

**Comment by doofus-01** [comment]
There are still a few things that need fixing, but I don't think they are enough to break this.  I'll merge if CI doesn't find something.
Screenshot_20220807_a

**Comment by doofus-01** [comment]
That failing macos-intel (Debug) looks unrelated to whatever I did, I'll not let that stop the merge.

**Pull request merged**
