### PR TITLE
GUI2 prefs dialog refactor

### PR DESCRIPTION
**Pull request by Vultraz**
WIP effort to reimplement the preferences dialog in GUI2 using @shikadilord 's layout. Right now I'm just focusing on getting all the buttons working; there's probably a lot of code simplification that could be done for the similar functions.

CURRENT STATUS:

- [x] **General Panel**
- [x] **Display Panel**
- [x] **Sound Panel**
- [x] **Multiplayer Pane**
- [x] **Advanced Panel**

### CODE REVIEW

**Comment by Vultraz** [comment]
@shikadilord How did you plan on implementing Advanced Preferences? I'm wondering if it's possible to have panels within the panels. Then we could have a listbox and a panel underneath it with each of the options' widgets. Or we could do away with that and make it a page the style of other pages, since it's now simpler to implement new options. It wouldn't be as easy as before (adding a new node to the .cfg file, but it should still be relatively simple. Thoughts?

**Comment by gfgtdf** [comment]
You quite some options from preferences: titltescreen animation, flip tod image, and local tod lighting. What were the reasons to do so?

**Comment by Vultraz** [comment]
@gfgtdf shadowm thought we didn't need those anymore and I agree. They were useless options to have.

**Comment by gfgtdf** [comment]
Hmm at least for the flip_tod option i know that i was removed already once and then people complained because they needed it https://gna.org/bugs/?9526.

For the ttlescreen option i think its useful to keep it as a code example to know how gui2 anmiations can be done.

I don't know what 'local tod lighting' so i cannot tell about it.

**Comment by Vultraz** [comment]
@gfgtdf the complaints were years ago; I don't think it'll be an issue now.

The titlescreen anim code will still be in history.

And Local ToD Lighting means having [time_area]s with local light. I removed the option so that becomes the standard behavior.

**Comment by shikadilord** [comment]
Local ToD lighting was enabled by default and allowed [time_area]-affected regions to have local lighting shifts according to their ToD schedule. Since the performance concerns that prompted it to be originally disabled by default when it first appeared no longer apply, and hardware has moved forwards quite a way since then, I don't think there is any value in keeping the option around other than allowing people who don't know better to touch it without any real need to do so. And if we find out there are people who actually needed it we can reimplement it or (better) fix whatever needs to be fixed.

I'm not concerned about disabling the flipped ToD images option for the same reason I'm not interested in implementing an option to remove magical creatures from the game.

**Comment by Vultraz** [comment]
Advanced is now fully functional. :D

**Comment by gfgtdf** [comment]
the travis test fail becasue teh preferences menu is no tested in that gui2 boost tests. you have to eigher add a test in src/tests/gui/test_gui2.cpp or add that dialog to the list of untested dialogs (in the same file).

**Comment by Vultraz** [comment]
@shikadilord cleanup/rebasing complete, please review.

**Comment by gfgtdf** [comment]
setup_.. functiosn still have the T template parameter.

**Comment by Vultraz** [comment]
@gfgtdf ^

**Comment by Vultraz** [comment]
@gfgtdf sizeof(speeds) doesn't work

**Comment by Vultraz** [comment]
Fixed

**Comment by gfgtdf** [comment]
the 'disambiguate_widget_value' function is a little strange, because it uses dynamic_cast __and__ template parameters. usually you should eigher use dynamic polymorphism (dynamic_cast) or static polymorphism (templates/overloading) in such a case. I reccomend that you decide for one and use only that in that function.

**Comment by Vultraz** [comment]
@gfgtdf but then what type should the "parent_widget" argument be? That's why I was using templates.

**Comment by gfgtdf** [comment]
This depends of yource on which way you choose:
with the 'runtime polymorphism' you'd change the type to twidget and change the last 'else' case into a if dynamic_cast<tselectable>. The 'compile time polymorphism' would use different overloaded methods, one that takes a ttoggle_button& one that takes a &tcombobox ....

**Comment by Vultraz** [comment]
@gfgtdf implemented and rebased

**Comment by Vultraz** [comment]
Rebased again, hopefully will fix the failing travis runs.

**Comment by Vultraz** [comment]
Split out the widget group stuff. This is done.

**Pull request merged**
