### PR TITLE
Clean up `config_attribute_value::operator==`

### PR DESCRIPTION
**Pull request by Vultraz**
The old implementation was recursive when building with C++20 due to primary operator reordering. More importantly, however, it would fail this test:
```
	c["x"] = "yes";
	BOOST_CHECK_EQUAL(c["x"], true);
```

### CODE REVIEW

**Comment by gfgtdf** [comment]
Hmm i agree that the old code is not very good, even on c++17, its unclear for the reader what the `return val == str;` actually does.


So im thinking about what `attr == v` is supposed to do, following to the comments it should convert `v` to a attribtue value, and the other code just exists to to prevent wrong t_string creation.

with your code it currently looks like
```
cfg c;
c["a"] = "sfvsdgdsfg";
return c["a"] == 0
```
would eval to true, since it converts the string "sfvsdgdsfg" to a number. Its possible that the previous code also did that, from the comments though i think that it's supposed to return false since clearly `attribute_value("sfvsdgdsfg") != attribute_value(0)`.


I furthermore think that:

1) equals should probably take a string_view instead of std::string
2) the implicit t_strign ctor that takes char* or std::string should be removed. (especially since creatng a t_string from that is in more cases thatn not a bug since those strings arent really translatable)

**Comment by Vultraz** [comment]
I was going to remove `equals` actually, since it's only used in this one place. Also, why would `sfvsdgdsfg` be evaluated as a number?

**Comment by gfgtdf** [comment]
Becasue of the `return T(*this) == comp;` line, no? in `c["a"] == 0` it convets c["a"] to a number,and then compares it to 0.

**Comment by Vultraz** [comment]
Hmmm... you're right. The conversion to int calls `to_int` which basically would try to convert the string to an int, fail, and return the default 0...

I guess it depends on how `return val == str;` actually worked in the old code. I assumed it relied on the implicit conversion of `this` to T of `val`, since otherwise what operator was actually getting called? But that could be wrong.

**Comment by gfgtdf** [comment]
wait i just noticed that attribute_value doesnt have a ctor thattakes an int,only an operator == so you are right here

**Comment by Vultraz** [comment]
@gfgtdf I changed the impl to only compare against T if the variant currently holds T.

**Comment by Vultraz** [comment]
Honestly, the more I look at this the more I'm thinking we should delete the heterogenous comparators entirely. If you add the constraint that the variant must currently hold the type you're comparing against, then any comparison with bool falls apart. What would `false` mean? Either that the variant holds another type, or that the bool type held compared false. Either is a valid interpretation.

I'm gonna see what happens if we remove the comparisons.

**Comment by gfgtdf** [comment]
> Honestly, the more I look at this the more I'm thinking we should delete the heterogenous comparators entirely

not sure whetehr i understood you correctly, but the template function exists for a single reason: becasue otherwise `c["a"] == "sfvsdgdsfg"` would convert both parameters to t_strings to compare them. And if even if its works correctly, this is at least slow.

**Comment by Vultraz** [comment]
I'm thinking we leave only one implicit conversion to std::string and make everything else (including comparison) call `to_x` first.

**Comment by Vultraz** [comment]
Decided I'll handle more extensive refactors separately. For now I just explicitly deleted comparison with bool given the ambiguous meaning of `c["x"] == false`.

**Pull request merged**
