### PR TITLE
weapon_special_daze_event with abilities

### PR DESCRIPTION
**Pull request by newfrenchy83**
now what changes in abilities used like specials are merged, i can propose that for simpplify WEAPON_SPECIAL_DAZE_EVENTS code

### CODE REVIEW

**Comment by gfgtdf** [comment]
Looks good to maybe but maybe @ln-zookeeper could review this?

**Comment by ln-zookeeper** [comment]
I can't really properly review this, there's a bunch of new WML features I'm not familiar with. But if it works, it works. Only issue I can immediately spot is some mixed-up indentation.

**Comment by newfrenchy83** [comment]
Someone can be review this PR, please?

**Comment by gfgtdf** [comment]
🤷🏻‍♂️, did you think you test it enough?

**Comment by newfrenchy83** [comment]
@gfgtdf yes i think when i test that, the precision of unit dazed is reduced to 10% and this enemy won 10% cth, except for magical attack and marksman affected is base cth greaet to 60% that it is identical to description of daze

"When hit with this attack, an enemy suffers a 10% penalty both to their defense and chance to hit for one turn. Other specials that affect chance to hit (e.g. magical and marksman) take precedence over this special.

Magical attacks will still have a 70% chance to hit.
Marksman attacks are only affected if the chance to hit is greater than 60%."

i tested non-magical, magical marsksman lowest what 60% and marksman with cth greater what 60% and i think what it is enough for me.

**Comment by CelticMinstrel** [comment]
It feels pretty hacky for it to be explicitly referencing the marksman and magical specials… is there a way to avoid that? I realize that the old code was also referencing them, and it doesn't matter if the special is unique to UtBS, but if we're considering moving it to core, it should probably be more generic if possible.

**Comment by newfrenchy83** [comment]
@CelticMinstrel
 [filter_weapon]
                                [not]
                                    special_id=magical
                                [/not]
                                [not]
                                    special_id_active=marksman
                                [/not]
                            [/filter_weapon]
can be replaced by

[filter_weapon]
                                [not]
                                    special_type_active=chance_to_hit
                                [/not]
                            [/filter_weapon]

but [filter_weapon]
                                special_id_active=marksman
                            [/filter_weapon]

is necessary in abilities where cth can be applied to marksman attack in certain condition, and marksman must be specified.

Because of abilities who call [event], moves quenoth elves in core isn't good idea for me.

**Comment by gfgtdf** [comment]
i have merged this, its an improvement over the old code feel freeto improve rurther if you think you can refactor out the reliance on these concrete wepaon specials.

**Pull request merged**
