### PR TITLE
Fix Issue 5743 surronding unit checksum code caring about weapon spec…

### PR DESCRIPTION
**Pull request by cpranga**
…ial names, which causes OOS when changed locally; fix issue by clearing out respective values by following later code.

### CODE REVIEW

**Comment by cpranga** [comment]
Fixes #5743

**Comment by Pentarctagon** [comment]
As a note for the future, to have the issue linked so that merging the PR closes the issue, you need to put `fixes #NNNN` in the text of the commit message.

**Comment by Wedge009** [comment]
I don't normally play MP so I tend not to consider OoS issues. If I understand the original issue correctly, the reporter wants to ignore these fields in the check-sum because they have the potential to vary even though there's no effect game-play. I suppose that makes sense, but I don't really understand the details around that. Has this been tested? (Is it even possible to test easily?)

@soliton- You looked at the original issue #5743...

**Comment by soliton-** [comment]
Looks fine to me.

Would be good to fix the commit message format though. The first line should be a short summary, followed by an empty line, followed by a more detailed description. Something like:

> Improve unit checksum code
> 
> Clear out unimportant attributes from weapon specials. Fixes #5743.

**Comment by Pentarctagon** [comment]
Any chance of getting this merged and backported before RC1 (in about 20 hours)?

**Comment by cpranga** [comment]
Thanks for your patience; I've been sick recently. I was able to force push the updated commit message, but I was unable to test with the listed example; I'm still learning how to do stuff, and other commitments prevented me from doing too much

**Comment by Pentarctagon** [comment]
Alright, no worries :)

**Review by soliton- — APPROVED** [review]
Looks good to me. I'm going to merge for master without test since it's simple enough but it'd be nice to get this tested into 1.16 before the next release as well.

**Pull request merged**
