### PR TITLE
prevent crash in case of faulty WML in mainline content (#1899)

### PR DESCRIPTION
**Pull request by sevu**
proposed fix for #1899 
Crashes don't happen again.
Still getting the wml error message thrice.
Aside from that, are there code formatting issues?

### CODE REVIEW

**Comment by gfgtdf** [comment]
> Aside from that, are there code formatting issues?

the  `});` shodul have on less indention, it currently looks liek it'd close the `gui2::dialogs::wml_error::display(` but it cataull closes the `events::call_in_main_thread([&]() {`

**Comment by sevu** [comment]
Updated it.

**Comment by gfgtdf** [comment]
looks good to me, i'll merge it if noone objects.

**Comment by CelticMinstrel** [comment]
It'd be nice if you fixed the typo in the commit message, too - "prevent".

**Comment by sevu** [comment]
No idea how I wrote it that way.

**Pull request merged**
