### PR TITLE
Fix Animations immediately following a message get truncated (issue #1617)

### PR DESCRIPTION
**Pull request by newfrenchy83**
When unit with staff of tighteous die in s9 forbidden forest the animatiom is'nt played. The same problem with Dacyn disapear in S1 of EI. Insert wesnoth.delay fix this.

### CODE REVIEW

**Comment by GregoryLundberg** [comment]
Should this also go into Stable 1.14?

**Comment by newfrenchy83** [comment]
Ues the problem is in also 1.14.

**Comment by DisherProject** [comment]
@newfrenchy83 I found a workaround (via WML) for this: switch [these](https://github.com/wesnoth/wesnoth/blob/master/data/campaigns/The_Hammer_of_Thursagan/utils/macros.cfg#L149-L150) lines:
```
duration=700
halo=halo/elven/faerie-fire-halo[1~7].png
```
with this one
```
halo=halo/elven/faerie-fire-halo[1~7].png:[100,200,300,400,500,600,700]
```
I don't really know what the lua code looks like, but maybe in the first case the timing of each frame is not correctly interpolated according to the total `duration`

**Comment by newfrenchy83** [comment]
if i replace extra_anim by attack_anim in uni_type the animation is played. i all tried and interpolate wesnoth.delay un lua code is the only thing who function. i too modify the and mation wirhout changes.

**Comment by newfrenchy83** [comment]
It seem a simular bug was report here https://github.com/wesnoth/wesnoth/issues/1617

**Comment by newfrenchy83** [comment]
@shikadiqueen i see what you re fix this problem in you re Ethea project
I hope what my fix was put in stable and master branch also.

**Comment by newfrenchy83** [comment]
@GregoryLundberg it is appear what message lua function cause the bug in animation, i put wesnoth.delay in end of this function for fix and this function.

**Comment by shikadiqueen** [comment]
This not a fix, this is a workaround (not even clearly marked as such).

**Comment by shikadiqueen** [comment]
Also, quoting @ln-zookeeper from the original issue:

> Regardless, even a delay of 0 after a message causes a redraw between successive messages, causing flicker.

**Comment by newfrenchy83** [comment]
@CelticMinstrel. It's to done for 1.14.6 now

**Comment by newfrenchy83** [comment]
I fix my mistake

**Comment by newfrenchy83** [comment]
i posted this PR https://github.com/wesnoth/wesnoth/pull/3573 for fix this bug un 1.15.

**Pull request closed without merging**
