### PR TITLE
Enable tree_view gui2 widget for lua

### PR DESCRIPTION
**Pull request by gfgtdf**
wesnoth.add_dialog_tree_value to add nodes to a tree_value
wesnoth.set_dialog_callback support for tree_views (triggers when the
selected node was changed)
wesnoth.get_dialog_value support for tree_views returns an array of
integers that describe the path to the currebntly selected node.

### CODE REVIEW

**Comment by Vultraz** [comment]
Can't add_dialog_tree_value be part of set_dialog_value like everything
else?

**Comment by gfgtdf** [comment]
@Vultraz 
You mean implcitly creatign those liek we do for listitems? That is not possible becase unlike for list item we allow multiple types of nodes, when we add the node we have to specify the type.

**Comment by gfgtdf** [comment]
This pr does not add a set_dialog_value for treeviews yet, but set_dialog_value(), should set the currently selected node (that whats get_dialog_value returns) if it was implemented.

**Comment by gfgtdf** [comment]
Ok i was able to make a testing lua dialog that uses tree_view:
image

Unless there are more concerns i'll most likeley merge it soon.

**Pull request merged**
