### PR TITLE
Fixed campaignd Xcode target

### PR DESCRIPTION
**Pull request by hrubymar10**
Theoretically this can be also merged to 1.14 branch. I don't know if it will be useful there.

### CODE REVIEW

**Comment by jyrkive** [comment]
Thank you. 👍

**Comment by CelticMinstrel** [comment]
This is only really useful for developers wishing to test campagnd changes, so the only reason to put it in 1.14 IMO is if you think it would help avoid conflicts in later project updates (but I don't even know if that's relevant; it's likely easier to just manually update both branches, in which case there's no point adding this to 1.14).

Basically, campaignd is not part of the release. It's only built and run on the official server. So it's not necessary for the Mac build of it to work in a release branch.

**Comment by GregoryLundberg** [comment]
This is open source softeware.

Assuming that the users do what you want is folly.

The release BUILD package should contain all three: wesnoth, wesnothd and campaignd.

The addons server is generally useful to anyone wanting to run a private addons server; perhaps for development or perhaps for a private club. Making it harder to do that simply because you don't expect them to do so serves no purpose.

**Comment by hrubymar10** [comment]
Should we package `campaignd` inside `.app` application in your opinion?

**Comment by CelticMinstrel** [comment]
The release package has ~never~ contained campaignd. While I'm not opposed to changing that, I think it doesn't make sense to do so at this stage.

We're not making it harder for people to run a private addons server in my opinion; also most people who would want to would be on Linux anyway (at least the server would be). So I really don't think this is high priority. And the source download, at least, does include campaignd source.

**Comment by GregoryLundberg** [comment]
On Windows, I'd have a checkbox to install campaignd, defaut: unchecked/no. On Archi Linux, I'd probably do a separate package: wesnoth-campaingd-1.14.0. It's really up to the packager for each platform. CM's point about non-Linux installs probably not wanting it is valid.

**Comment by hrubymar10** [comment]
Ok, so we won't embed `campaignd` inside macOS package at least for 1.14.x .

We may start new discussion about it with 1.15.x and/or 1.16.x .

**Comment by jyrkive** [comment]
The primary reason to allow building `campaignd` with Visual Studio and Xcode is that it makes development easier. End users aren't supposed to use it.

**Pull request merged**
