### PR TITLE
Add a way to disable _on leaving_ confirmations if wanted.

### PR DESCRIPTION
**Pull request by galegosimpatico**
The default behavior is to confirm everything as it has been for years.

Add the feature as an advanced preference.

At the editor: only close without confirmation if there are no changes pending save.

### CODE REVIEW

**Comment by sevu** [comment]
A similar thing might be the confirmation when leaving the MP lobby.

**Comment by gfgtdf** [comment]
note that in 1.14.0 you can just press quit (the red cross) twice, you don't need to move your mose over the  confirm button

**Comment by galegosimpatico** [comment]
> A similar thing might be the confirmation when leaving the MP lobby.

Aha,.. I don't use the MP lobby. I'll check it.

> note that in 1.14.0 you can just press quit (the red cross) twice, you don't need to move your mose over the confirm button

Uh, didn't knew. I would have not written this. 😃💧

**Comment by galegosimpatico** [comment]
> note that in 1.14.0 you can just press quit (the red cross) twice, you don't need to move your mose over the confirm button

I would not have written this, but I still think the feature is somewhat desirable,.. as long as nobody in the team opposes so? That _double exit request_ feature is indeed cool, but... I'm afraid it's maybe a bit obscure?

I forgot to comment..: I want to propose this in a 1.15 context. Because I have big instabilities in master I thought better base it on 1.14... then you choose between unmerged dismiss, merge in 1.14, or rebase on master and iterate; of course this as long as nobody in the team opposes so.

**Comment by galegosimpatico** [comment]
> This does NOT need to be a preference. Options, when there is one sensible option, are bad. When quitting the game or the multiplayer lobby, there should be no prompt. Period. When quitting the editor with unsaved changes, there should be a prompt. Always.

Hmm. Can't refuse any of that.

Maybe I should think everything again and turn to more ~~requests~~ proposals, smaller in scope, in the direction you point to, and ideally much more focused.

**Comment by gfgtdf** [comment]
> When quitting the game or the multiplayer lobby, there should be no prompt. 

no, these quit conformations were explicitly added for a reason. In the worse case people have to replay multiple hours of a scenario if they didnt save and accidently hit quit. For the mp lobby, i don't know why they were aded but also here people explicitly decided for adding these, so there is probably a reason aswell.

**Comment by sapientN3T** [comment]
Isn’t that why we have autosaves? As for the lobby, it is pretty telling that you could not even think of a single reason for this malfeature. Removing these two prompts is a no-brainer. Whatever reason led to them was wrong-headed thinking and poor UI design.

**Comment by galegosimpatico** [comment]
It's not exactly poor UI. It's just missing at least one abstraction somewhere. The game uses literally the same flow for every closing gesture. For some of those the confirmation makes sense. But not for every one.

* They wanted confirmation when the window toolkit cross is clicked. Good.
* They wanted confirmation for closing when Alt-F4 is hit. Better.
* The game has now confirmation for closing via menu navigation. Nope! That's a gesture combining several movements. There is no possibility of getting there by mistake. So no confirmation is needed by that particular closing flow - unless the reason for such confirmation are changes pending save, at the editor.

**Comment by gfgtdf** [comment]
> Isn’t that why we have autosaves?

even a single turn can take some time, and in mp is is very annoying if you have a rejoin a game and replay that whole game to the current turn, even if you just did a save.

> As for the lobby, it is pretty telling that you could not even think of a single reason for this malfeature. 

Well yes, thats what i said and i never supported having the quit confirmation there, but still other people added it becasue they thought it was better that way and your opinion is not enough to change it back.

> Removing these two prompts is a no-brainer. Whatever reason led to them was wrong-headed thinking and poor UI design.

No, that just your personal preference, you gave no reason yet why they should be changed.

> The game has now confirmation for closing via menu navigation. Nope! That's a gesture combining several movements. There is no possibility of getting there by mistake. So no confirmation is needed by that particular closing flow

hmm yes we could do that, another thing we could do is to detect whether there were actions after the last save and skip the quit confirmation in that case in sp.

**Comment by sapientN3T** [comment]
"Just my personal preference" or an industry wide trend in finding ways to reduce the number of clicks and confirmation pop-ups? 

"You gave no reason" because the reason is obvious: they are annoying. users get frustrated by unnecessary confirmations.

Here is a source, but I am sure you can find a lot more by searching UI design blogs; http://www.uxdesignedge.com/2010/06/are-you-sure-how-to-write-effective-confirmations/

Watching a replay or falling back to an autosave seem perfectly reasonable to me, in the unlikely event that I exited Wesnoth unintentionally, which has never happened to me in the past decade. However if it's really worth such a hot debate then I would be interested to hear some more opinions of users other than just myself and gfgtdf, perhaps via Polling.

**Comment by CelticMinstrel** [comment]
I think the confirmations should all stay for clicking the X or hitting Cmd+Q / Alt+F4. There shouldn't be a confirmation when clicking Log Out though. 

I think the original iteration of quit confirmations didn't cover the lobby because it wasn't clear whether it should. I think it was @Vultraz who ended up adding that, though I could be mistaken.

**Pull request closed without merging**
