### PR TITLE
Remove gzip/bzip2 (de)compression commandline options

### LINKED ISSUE #8065: (Re)move gzip/bzip2 command line compresion code from wesnoth.cpp
### Describe the desired feature

I was recently analysing Wesnoth initialisation code and stumbled upon command line (de)compression code. IMO, providing a compression tool in the game is out of scope and should be removed or moved to some other file than wesnoth.cpp.

### PR DESCRIPTION
**Pull request by grz0**
The pull request removes the `--gzip`, ` --gunzip`, `--bzip2`, and `--bunzip2` command line options and related documentation.

These options allow compression and decompression of gzip and bzip2 archives from the command line. Given the widespread availability of third-party compression tools, these options most likely have no real use case. Also, it looks like Windows 11, starting from build 23493, can natively handle gzip and bzip2 files (I didn't test how well it works). 

Resolves #8065

### CODE REVIEW

**Comment by cooljeanius** [comment]
@AI0867 originally added the bzip-related options in 31d8c98, while the gzip-related ones have been there since... well, a while before that (haven't quite figured out for sure yet); requesting reviews from related committers

**Comment by grz0** [comment]
@cooljeanius 
`--gzip` and `--gunzip` options were added in commit e3047c9ab46 on Nov 30, 2007, also `--compress` and `--decompress` options existed, added on Feb 20, 2005 in 2cac259d89e.

**Comment by AI0867** [comment]
I don't feel strongly about this either way, but the following phrasing sounds like it may still be of use to someone.
> Also, it looks like Windows 11, starting from build 23493, can natively handle gzip and bzip2 files (I didn't test how well it works).

I also don't really see the point of removing the CLI to libraries we definitely still use.

**Comment by CelticMinstrel** [comment]
I have no issues with this. The options are certainly redundant; I doubt they see much use, all things considered. Most people probably use 7-Zip or WinRar or The Unarchiver to decompress save files, and those on Linux probably already have the command-line tools installed if nothing else… and I bet most Linux DEs can automatically extract them for you.

Even for the few niche cases where someone needs to unpack a save file but doesn't have _any_ native program to do it, simply setting their preferences to store saves uncompressed, opening the file, and resaving it should work in most cases, shouldn't it? I'm not sure if that would work with start-of-scenario saves, and it's probably a little tricky with replays (as you have to let the replay complete before resaving), but it should be doable.

I'm not particularly opposed to keeping this code around, but removing it means less code to maintain, and I don't see any point in keeping it.

**Comment by stevecotton** [comment]
What do people do with savefiles which would be affected by compression? I think it's only editing them, or attaching them to a forum post / bug report.

It seems that both Notepad++ and Visual Studio Code have plugins for editing compressed text files, but don't do that automatically. However, if Windows already does that transparently then maybe the editors don't need them.

Vim automatically decompresses gzip and bzip2 files, and compresses when writing to them. I expect Emacs does too.

**Comment by CelticMinstrel** [comment]
For Mac users, BBEdit also does that automatically – you can just open the gzipped save in BBEdit and edit it like a normal text file. (I haven't tested if that works with bzipped files but I wouldn't be surprised.)

**Pull request merged**
