### PR TITLE
Fixed a bug in which not defeated sides without a leader couldn't capture villages

### PR DESCRIPTION
**Pull request by Elvish-Hunter**
Following a discussion that happened on the Wesnoth Italian Forum, I and Xalzar found out that, after the introduction of the new [side] defeat_condition key, the engine's behaviour when capturing a village has become inconsistent.
Before, a side was considered defeated just when it didn't have a leader. But now, a side with *defeat_condition=no_units_left/never* may not have a leader and be active; in the same manner, a side with *defeat_condition=always* may have five leaders, and still be defeated.
In my opinion, the expected behaviour from the game should be the following:

* **no_leader_left:** the side can capture villages as long as it has a leader; upon losing it, the side loses all its villages
* **no_units_left:** the side can capture villages as long as it has a unit; upon losing all the units, the side loses all its villages
* **never:** the side can always capture villages (in case that it doesn't have any units, villages can still be captured via WML or Lua), and loses them only through events or enemy captures
* **always:** the side cannot capture villages at all, not even programmatically

Instead, what happens now is the following: it doesn't matter if a side is defeated or not, it can only capture villages if it has a leader. It's really simple to test it:

* Install *A Simple Campaign*
* Modify the side 2 to have a human controller and *defeat_condition=no_units*; also comment out the corresponding canrecruit=yes
* Try capturing a village with the only blue unit: it fails.

This pull request should fix the capturing behaviour, at least on the 1.13 series. It compiles correctly and I tested it, but I didn't yet test the case when a defeated side captures an allied village.
I'm not sure if this should be backported on the 1.12 series, if possible, due to the obvious incompatibilities that it introduces.

### CODE REVIEW

**Comment by gfgtdf** [comment]
All travis build have failed.

Also in wesnoth.set_village_owner you should check whether new_side is in range before using it.

**Comment by cbeck88** [comment]
Hmm... it looks like this commit is creating a segfault during the game setup procedure somehow.

Right now the game setup process is fairly convoluted -- teams are built during "stage one" and "stage two" to try to resolve some cyclic dependencies between the different objects. The game events manager object appears to be involved in this case. It's not obvious to me what the problem is, if I had to hazard a guess I would say that the new code is trying to register new game events at a time when the old code never would have, and at this time it isn't possible.

When a unit test segfaults, travis automatically reruns it with gdb to try to get a backtrace, which you can find by digging through the logs, for your convenience here's this one:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000a4ab76 in boost::scoped_ptr<game_events::t_pump>::operator*() const ()
#0  0x0000000000a4ab76 in boost::scoped_ptr<game_events::t_pump>::operator*() const ()
#1  0x0000000000a49be0 in game_events::manager::pump() ()
#2  0x00000000006da323 in team::get_village(map_location const&, int, game_data*) ()
#3  0x00000000008336d1 in actions::get_village(map_location const&, int, int*) ()
#4  0x000000000082cfff in unit_creator::post_create(map_location const&, unit const&, bool) ()
#5  0x000000000082c8f1 in unit_creator::add_unit(config const&, vconfig const*) ()
#6  0x0000000000c80660 in team_builder::place_units() ()
#7  0x0000000000c7da58 in team_builder::build_team_stage_two() ()
#8  0x0000000000c7d7b1 in build_team_stage_two(boost::shared_ptr<team_builder>) ()
#9  0x0000000000a61c30 in game_state::init(int, play_controller&) ()
#10 0x0000000000c54fdb in play_controller::init(CVideo&) ()
#11 0x0000000000c54643 in play_controller::play_controller(config const&, saved_game&, int, config const&, boost::shared_ptr<terrain_type_data> const&, CVideo&, bool) ()
#12 0x000000000061d722 in playsingle_controller::playsingle_controller(config const&, saved_game&, int, config const&, boost::shared_ptr<terrain_type_data> const&, CVideo&, bool) ()
#13 0x0000000000611179 in playsingle_scenario(config const&, boost::shared_ptr<terrain_type_data> const&, display&, saved_game&, std::pair<config::const_child_iterator, config::const_child_iterator> const&, bool, end_level_data&) ()
#14 0x00000000006118b4 in play_game(game_display&, saved_game&, config const&, boost::shared_ptr<terrain_type_data> const&, io_type_t, bool, bool, bool, bool) ()
#15 0x00000000004a475a in game_launcher::unit_test() ()
#16 0x000000000042387e in do_gameloop(std::vector<std::string, std::allocator<std::string> > const&) ()
#17 0x0000000000424fb4 in main ()
```

**Comment by gfgtdf** [comment]
Ok i was able reproduce that segfault also with current master and this test scenario:
```
[scenario]
	id= "01_STARTUNIT_TEST"
	map_data = "Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh
Gs^Vh, Gs^Vh, 2 Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh
Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh
Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh
Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh
Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh
Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, 1 Gs^Vh, Gs^Vh, Gs^Vh
Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh, Gs^Vh
"
	{DEFAULT_SCHEDULE}
	[side]
		side=1
		id= "leader1"
		controller=human
		team_name= "team1"
		type = "Elvish Archer"
		canrecruit="yes"
	[/side]
	[side]
		side=2
		id= "leader2"
		controller=human
		team_name= "team2"
		type = "Elvish Archer"
		canrecruit="yes"
	[/side]
[/scenario]
```

So it is not caused by this patch.

**Comment by cbeck88** [comment]
"So it is not caused by this patch."

Do you understand why the unit tests were passing before this commit and failing after?

**Comment by gfgtdf** [comment]
well yes, my theroy is that the unit tests in question try to place a [unit] inside [side] in a village which fires the "capture" event during build_team_stage_two if the side can capture the village.

The unit tests use defeat_condidtion=no_units_left, and the behaviour of this case was now changed in the pr so that they can now capture the village even if the side has no leader.

**Comment by Elvish-Hunter** [comment]
As gfgtdf asked, now my code checks if new_side is in range.
By the way, is there any progress in fixing the regression that my pr apparently uncovered?

**Comment by gfgtdf** [comment]
not that i'm aware of but it was noticed that this bug currently makes Low aswell as AtS crash on master
```
20150110 17:02:48< shadowm> master segfaults when attempting to load AtS E1.
20150112 15:22:38< aquileia> I don't know whether that's the cause, but wesnoth crashes when I cl to that scenario... which WML never should cause...
```

**Comment by Vultraz** [comment]
The crash seems to happen whenever you try to initialize a unit on a
village during side building. So it's not the patch causing it.

**Comment by gfgtdf** [comment]
@Vultraz yes, that's what i said before.

i made a bug report about this issue in https://gna.org/bugs/index.php?23188 so that we can use this place here to discuss the pr.

about this pr: 
Why do we allow catching a village now íf a side without a leader? I thought the original reason why we don't let leaderless sides capture villages is that without a leader it cannot recruit so uit has no use for that gold.

**Comment by Elvish-Hunter** [comment]
> Why do we allow catching a village now íf a side without a leader? I thought the original reason why we don't let leaderless sides capture villages is that without a leader it cannot recruit so uit has no use for that gold.

It's true that it can't recruit, but by using WML or Lua the gold may be used for other things, like buying unit upgrades or even a new leader with a right-click menu, if the UMC author decides so!
In fact, it's true that a side without a leader and with no_units_left can't capture villages, but as it is currently (without applying my patch) I noticed that it doesn't lose the villages upon losing the leader - I forgot to mention it in my proposal.

**Comment by gfgtdf** [comment]
y i see, the current behaviour is quiet inconsistent. I think we can merge this pr and disable the failing tests.

**Comment by Elvish-Hunter** [comment]
This PR is now merged.

**Pull request closed without merging**
