### PR TITLE
Fix halo flash when unit advance

### PR DESCRIPTION
**Pull request by newfrenchy83**

### CODE REVIEW

**Comment by jyrkive** [comment]
I don't see why this change would help anything. The old halo should disappear when `advance_unit` drops its reference to the old unit, i.e. in line 352, _only three lines below the line you added_.

**Comment by newfrenchy83** [comment]
Because rhe halo flash briefly when unit amla advance before what unit reference was deleted. Tje player can see the halo persitent problem. I added the old clear_haloes to halo don't flash with advance animation. The refrence delete is not perfect.

**Comment by jyrkive** [comment]
After investigating myself, you're right. Frames higher up in the call stack retain a reference to the old unit while the animation is playing.

Merged. Thanks for the pull request. :)

**Comment by gfgtdf** [comment]
@jyrkive next time please don't merge commits with desciptions like that, if you don't want to wait for him to update the commit mesage you can also use 'squash and merge' to do the commit message yourself.

**Pull request merged**
