### PR TITLE
[world conquest] [master/1.17] update to new mushroom terrain from the deprecated mushroom terrain

### PR DESCRIPTION
**Pull request by knyghtmare**
same as #5960, addresses #5135 for the master branch.

### CODE REVIEW

**Comment by stevecotton** [comment]
Needs a check with `git grep` - the mushrooms are still in Lua files' `adjacent_liked` lines, as well as the postgeneration Lua files and the destruction mechanics.

**Comment by Pentarctagon** [comment]
Any help needed with doing the grep here?

**Comment by knyghtmare** [comment]
> Needs a check with `git grep` - the mushrooms are still in Lua files' `adjacent_liked` lines, as well as the postgeneration Lua files and the destruction mechanics.

I ran `git grep -rl "\^Uf" | wc -l` and got `127` returned. Is that it?

**Comment by stevecotton** [comment]
Yeah, that's it. A load more places to change.

**Comment by knyghtmare** [comment]
> Yeah, that's it. A load more places to change.

Changes to be inside the WC campaign directory? Or...the entire repo?

**Comment by Pentarctagon** [comment]
Given this is for WC, then just for WC.  I'd expect there to be some references elsewhere anyway because otherwise there would be no way to mark the terrain as deprecated in the first place.

**Comment by knyghtmare** [comment]
I have run ` git grep -rl "\^Uf" | wc -l` on the add-on version (my repo for WC) and got `0` this time. So, I guess this PR does update all instances of deprecated mushrooms inside the WC directory.

**Comment by stevecotton** [comment]
You might need to push an update to this PR; at least for me this branch still seems to have old mushrooms in it:

```
$ git rev-parse knyghtmare/wc-fungal-mushroom-deprecation-patch-master
167df8d5c4ccb43418071462610f7a5a680c5cec
$ git grep '\^Uf' knyghtmare/wc-fungal-mushroom-deprecation-patch-master:data/campaigns/World_Conquest/
knyghtmare/wc-fungal-mushroom-deprecation-patch-master:data/campaigns/World_Conquest/:lua/map/generator/clayey.lua:                     adjacent_liked="Gg, Gs, Ww, Ww, Ww, Re, Rd, Rb, Gg, Gs, Re, Rd, Rb, Gg, Gs, Hh, Hh^Fp, Hh^Uf, Mm",
knyghtmare/wc-fungal-mushroom-deprecation-patch-master:data/campaigns/World_Conquest/:lua/map/generator/clayey.lua:                     adjacent_liked="Gg, Gs, Ww, Ww, Ww, Re, Rd, Rb, Gg, Gs, Re, Rd, Rb, Gg, Gs, Hh, Hh^Fp, Hh^Uf, Mm",
knyghtmare/wc-fungal-mushroom-deprecation-patch-master:data/campaigns/World_Conquest/:lua/map/generator/clayey.lua:                     adjacent_liked="Gg, Gs, Ww, Ww, Ww, Re, Rd, Rb, Gg, Gs, Re, Rd, Rb, Gg, Gs, Hh, Hh^Fp, Hh^Uf, Mm",
knyghtmare/wc-fungal-mushroom-deprecation-patch-master:data/campaigns/World_Conquest/:lua/map/generator/clayey.lua:                     adjacent_liked="Gg, Gs, Ww, Ww, Ww, Re, Rd, Rb, Gg, Gs, Re, Rd, Rb, Gg, Gs, Hh, Hh^Fp, Hh^Uf, Mm",
knyghtmare/wc-fungal-mushroom-deprecation-patch-master:data/campaigns/World_Conquest/:lua/map/generator/clayey.lua:                     adjacent_liked="Hh,Hh^Fp,Mm,Uu,Uh,Hh^Uf,Xu,Uu^Uf,Mm^Xm,Ww",
knyghtmare/wc-fungal-mushroom-deprecation-patch-master:data/campaigns/World_Conquest/:lua/map/generator/clayey.lua:                     adjacent_liked="Hh,Hh^Fp,Mm,Uu,Uh,Hh^Uf,Xu,Uu^Uf,Mm^Xm,Ww",
knyghtmare/wc-fungal-mushroom-deprecation-patch-master:data/campaigns/World_Conquest/:lua/map/generator/coral.lua:                      adjacent_liked="Gg, Gs, Wwt, Wwrt, Re, Gg, Gs, Re, Gg, Gs, Hh, Hh^Fp, Hh^Uf, Mm",
...
```

**Comment by Pentarctagon** [comment]
It looks like several are in regular multiplayer maps, actually.  I'll make a PR to fix those hopefully later today.

**Comment by Pentarctagon** [comment]
Just removing the `| wc -l` will list the files instead of the count.  You probably want to use `grep -Irn "\^Uf"` though - `-I` ignores binary files like images, and doing `\^` is needed since just `^` means "start of the line".  So `^Uf` doesn't search for the literal text, it searches for "lines that start with `Uf`".

**Comment by Pentarctagon** [comment]
Yeah, I assume `git grep` looks at the entire repository rather than just regular `grep` that looks in the current folder.  Looks good though, thanks!

**Pull request merged**
