### PR TITLE
tSG text change

### PR DESCRIPTION
**Pull request by chisquare130**
Make Deoran the grandson of Haldiel in HttT.
Silently delete the objective after killing Queen Xeila in scenario 6a. 

* Fixed tabstop problem in previous pull request.

### CODE REVIEW

**Comment by Vultraz** [comment]
ab9aff0 should be merged into 8fda270, and b388f4e should be a separate pull request.

**Comment by ln-zookeeper** [comment]
Also, it's slightly shorter and cleaner if you don't re-define the objectives, but instead just make the [objective] conditional with this:

[show_if]
    [have_unit]
        id=Queen Xeila
    [/have_unit]
[/show_if]

**Comment by Elvish-Hunter** [comment]
Another thing that can be done to slightly shorten the code is replacing this block:

#ifdef EASY
        {VARIABLE troll_help_cost 100}
#endif
#ifdef NORMAL
        {VARIABLE troll_help_cost 150}
#endif
#ifdef HARD
        {VARIABLE troll_help_cost 150}
#endif

with this block:

#ifdef EASY
        {VARIABLE troll_help_cost 100}
#else
        {VARIABLE troll_help_cost 150}
#endif

**Comment by chisquare130** [comment]
I'll learn more about git commands and reopen the PR

**Pull request closed without merging**
