### PR TITLE
Remove xbrz

### PR DESCRIPTION
**Pull request by Vultraz**
CI run.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I don't think it's that complicated to make the stub just use the nearest neighbour scaling algorithm (using `scale_surface_sharp`).

**Comment by Vultraz** [comment]
@Pentarctagon no objections?

**Comment by cooljeanius** [comment]
So, IIRC, this is due to some sort of licensing issue? Could you put a recap of that in this PR so that anyone coming across this PR when browsing history can be easily reminded of why it's necessary?

**Comment by Pentarctagon** [comment]
I think this should wait until 1.19.0. We're supposed to be in feature freeze which IMO also just generally means not doing things that require more changes to be made by UMC authors.

**Comment by CelticMinstrel** [comment]
> I think this should wait until 1.19.0. We're supposed to be in feature freeze which IMO also just generally means not doing things that require more changes to be made by UMC authors.

This implies that it might be okay if the stub IPF is updated to actually scale instead of doing nothing?

**Comment by cooljeanius** [comment]
Looks like #8307 would be going in a different direction... ok to close this PR?

**Comment by Pentarctagon** [comment]
Closing, since we're not considering removing xBRZ anymore.

**Pull request closed without merging**
