### PR TITLE
[UtBS] Quenoth elf animations

### PR DESCRIPTION
**Pull request by doofus-01**
This incorporates Jetrel's revisions.  the -fly1.png image is actually closer to what he had, the dress billowing sort of like Superman's cape for heroic dynamism.  I thought it looked odd to have it frozen like that, so I'm trying to get it animated for cases where it makes sense.  The fly/float animation filtering probably needs revision.

Of course, more than just the dress should move, but the dress has to be finished first.

### CODE REVIEW

**Comment by doofus-01** [comment]
I don't know what to do with the splitting off of 1.14 and master.  I don't use git for anything IRL, so I don't feel puzzling this out is worth eating into time I could spend on something that is actually useful.  I'll just keep adding Quenoth defense animations to this PR, unless someone requests otherwise.

**Comment by CelticMinstrel** [comment]
It just means someone will need to manually merge the PR into 1.14. It will also need to be merged into master though, of course.

By the way, are there any plans to animate the (currently-used) Moon Singer and Moon Shyde? I guess it's not important since they're not used, but I kinda like them... >_>

**Comment by ln-zookeeper** [comment]
It just means that after merging the PR, someone has to cherry-pick the commit(s) into the 1.14 branch too, which is simple to do. So you don't really need to worry about it.

**Comment by CelticMinstrel** [comment]
Well, that's a possibility too, but it's probably easier to just merge it twice, into each branch.

**Comment by doofus-01** [comment]
Glad to hear it will work out, thanks.  As for the Moon Singer and Shyde, I have no plans for them.  Just too low priority.

**Comment by doofus-01** [comment]
I think this can be merged, if there are no issues.  The other sprites need more input from Jetrel before going any further,

**Pull request merged**
