### PR TITLE
Add JPG support to VC++2019 build

### PR DESCRIPTION
**Pull request by DisherProject**
Related to #5030 

I have updated the list of the dependencies and the Visual Studio project, so that they also include `sdl2-image[libjpeg-turbo]:x64-windows`. This further library solved the issue.

### CODE REVIEW

**Comment by Pentarctagon** [comment]
It looks like travis failed since it hadn't built and cached the jpeg library, so I've cleared the cache and trigger a manually run.  Once that's done I'll re-run the failed job here, and at that point I'm expecting it'll pass.

**Comment by Pentarctagon** [comment]
@DisherProject You'll need to update the dependencies [here](https://github.com/wesnoth/wesnoth/blob/master/utils/travis/steps/script.sh#L28) as well.

**Comment by DisherProject** [comment]
Thank you, i missed that

**Comment by Pentarctagon** [comment]
As a note for the future: having for example `fixes #5030` in your commit message will automatically close #5030 when the PR is merged.

**Pull request merged**
