### PR TITLE
Game Load: The dialog shall be usable even if the auto-selected savefile is invalid.

### LINKED ISSUE #3647: The file you have tried to load is corrupt: 'Mandatory WML child missing yet untested for. Please report.'
I get this error when I press the _Load_ button in the game. I don't even get a chance to play any of my saved files because I get this error right away when I click the button.

### PR DESCRIPTION
**Pull request by jostephd**
Fixes #3647.

### CODE REVIEW

**Comment by jostephd** [comment]
To test, revert 1497dc5fea578976fb98310e06071789a9ec91f5, delete the `active_mods` line from the newest savegame, and delete `save_index`.

**Comment by gfgtdf** [comment]
#3647 indicates a wrong use of the config class (using .child or .find_child with no check before use) we can put this in as an additional safety but we should also fix the code that calls .child or .find_child.

**Comment by gfgtdf** [comment]
oh seems like we did that already, hmm yeno opinion on this one then.

**Comment by GregoryLundberg** [comment]
Actually, I agree this is hiding the error rather than fixing it. I don't mind that we catch the error and keep going, but I would like to ensure we properly log the caught exception in case something really bad crops up and we blow by it without even noting the event.

**Comment by jostephd** [comment]
Added logging. _Of course_ we should also fix the root cause of #3647, this is just about not making Game Load entirely unusable when one savefile is bad.

> and also: to reroduce you probabyl need to delete teh whole[multiplayer] tag not just the active_mods= line.

No, deleting active_mods is enough. I did test the patch before I posted it.

**Comment by GregoryLundberg** [comment]
This looks good to go. Be sure, when this merges:
- cherry-pick to master
- do NOT close the original issue, that bug still exists

**Comment by jostephd** [comment]
Thanks for the review. I'll do as you say, but note that for all we know #3647 might be a duplicate of #3561 (which affects 1.14.5 only and is already fixed in git).

**Comment by jostephd** [comment]
That assumption is correct. I tested this PR by locally reverting #3561, seeing that I get the error, and then applying this PR and seeing the error disappears.

**Comment by GregoryLundberg** [comment]
So you're good to go and close the related Issues as well.

**Pull request merged**
