### PR TITLE
manual: update hotkey of command mode

### PR DESCRIPTION
**Pull request by fujimo-t**
Default hotkey of command mode is changed from ":" to ";".

### CODE REVIEW

**Comment by sevu** [comment]
Formerly, it was  :  independent from what keyboard layout you use.
Now it is the key where on American layout is ;
E.g. on German layout it's now ö

**Comment by CelticMinstrel** [comment]
Which is really a bad situation in my opinion. I suppose translators could be given the responsibility of substituting the correct keys, but what about languages that have multiple common keyboard layouts? And that still wouldn't work for people who use Dvorak keyboards.

**Comment by fujimo-t** [comment]
@sevu 
Yes, I have known.
I just told that hotkey of command mode is changed by commit 2459e7db10a5f5437e30279ab6952bd9ad9a9123 .

**Comment by Wedge009** [comment]
https://gna.org/bugs/?24681

The immediate issue is the change in command key from ':' to ';'

The larger issue is how to make this universal for different translations and/or keyboard layouts. I thought the command key was based on the character, not the position of the key on the keyboard, though.

**Comment by aginor** [comment]
All of the hotkeys are based of scancodes (making it button position dependant). The old way didn't work with sdl2, but I'll have a think to see if there might be a middle path.

**Pull request closed without merging**
