### PR TITLE
Revert opp_ctx in attack_prefiction( impossible to compile)

### PR DESCRIPTION
**Pull request by newfrenchy83**
The compiler show an error message . i must retry this line. Sorry @CelticMinstrel .

### CODE REVIEW

**Comment by Vultraz** [comment]
Wait a minute. This shouldn't be in master...

**Comment by Vultraz** [comment]
Ok, wait, *what*?? This code isn't in `attack_predictions.cpp`. What the hell is going on here.

**Comment by CelticMinstrel** [comment]
Rejected. I'll fix the compile error in a minute or so.

**Comment by CelticMinstrel** [comment]
Or I won't. Fixed in 46598681b61d1c85b665ca902648b9d587903894.

**Pull request closed without merging**
