### PR TITLE
Made blitting error handling less aggressive

### LINKED ISSUE #2225: leader crown not shown in attack dialogue for leader sprites smaller than 72x72
I do have this message in stderr
```
20171121 13:26:29 error config: Failed to apply a modification to an image:
Image: elementals/water-ice-hardshell.png.
Modifications: ~RC(magenta>red)~BLIT(misc/leader-crown.png)~SCALE_INTO_SHARP(144,144).
Error: ~BLIT(): offset and width '72' larger than destination image's width '70' no blitting performed.
```
This only affects the attack dialogue, works fine on the map. The sprite is 70x70.

Current version: b1c9cb4 (1.13.10+dev)

### PR DESCRIPTION
**Pull request by JGelfand**
Intended to fix #2225. I can't compile wesnoth, so this is untested right now.

### CODE REVIEW

**Comment by GregoryLundberg** [comment]
Compiles fine. I'll leave the testing to @Vultraz because it seems likely he has plans in this area, anyway.

**Comment by CelticMinstrel** [comment]
I think the only thing I'd recommend changing is putting that new comment on a separate line rather than at the end of a code line.

I'd also like to know what the actin effect of this is when there is an out-of-range blit. In particular, does it expand the canvas or clip the blitted image?

**Comment by CelticMinstrel** [comment]
^actual effect

**Comment by JGelfand** [comment]
It looks like it clips the blitted image; see https://github.com/wesnoth/wesnoth/blob/8179c7226b2f9dbf714ccc48303c1b5177b7635e/src/sdl/utils.cpp#L2135 and https://github.com/wesnoth/wesnoth/blob/8179c7226b2f9dbf714ccc48303c1b5177b7635e/src/sdl/utils.cpp#L2166 
I'll fix the comment.

**Comment by Vultraz** [comment]
I'm really not sure this is the proper fix. I shall need to consider.

**Comment by Vultraz** [comment]
FTR, this can't be merged into master anymore since `blit_surface` has been removed. Might still go into 1.14, though, not sure.

**Comment by CelticMinstrel** [comment]
In my opinion we should implement this on master, though I guess not by merging this.

**Comment by JGelfand** [comment]
Changed PR - I no longer use blit_surface.

**Pull request closed without merging**
