### PR TITLE
Attack Enemy: Don't show "poison" in the attacks list if the enemy is unpoisonable

### PR DESCRIPTION
**Pull request by jostephd**
This PR removes the ellipsed word.

screenshot_2018-11-03_19-16-14

Is this right? It tested okay but I am not completely sure.

### CODE REVIEW

**Comment by sevu** [comment]
There is also the feature of making weapon spacials inactive, and inactive weapon specials aren't displayed in that dialogue (at least I think they aren't).
However, only mentioning this for completeness, not saying it would be useful or working. 

Pinging @ln-zookeeper, he maybe can give better feedback.

**Comment by jostephd** [comment]
I assume I should also check for undrainable/unplagueable.

Is that the right place for and method of checking these things?

**Comment by CelticMinstrel** [comment]
I think my suggestion would be to show it, but greyed out to indicate it's not active. But... how does it work for, say, backstab?

**Comment by jostephd** [comment]
Backstab is simply omitted, not grayed out. I agree graying out would be an improvement but I don't think it's a blocker to merging, is it?
screenshot_2018-11-17_04-43-27

**Comment by CelticMinstrel** [comment]
I guess not, since backstab is also hidden.

**Comment by jostephd** [comment]
Greying out wasn't so hard after all:

screenshot_2018-11-18_13-36-35

**Pull request merged**
