### PR TITLE
Jinn and horse graphics

### PR DESCRIPTION
**Pull request by doofus-01**
This is to add #5903 to master.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I think this is against 1.16, not master?

**Comment by doofus-01** [comment]
Yep, I was hoping there was some way to just apply the relevant changes, but it's not looking good.

**Comment by CelticMinstrel** [comment]
You need to create a branch based on 1.16 and then cherry-pick the specific commits.

**Comment by doofus-01** [comment]
This won't be the only thing I need to port to 1.17, and rather than struggling with git each time, I'll just save them for later as a batch.  I'll close this and open an issue (#5963)

**Pull request closed without merging**
