### PR TITLE
Resend the announcements and server info text when rejoining the lobby.

### LINKED ISSUE #5095: Server Information bug.
### Game and System Information
 - 1.15.4
 - Steam
 - Windows 10

### Describe the bug
Bug

### To Reproduce
1. Log in
2. Enter any game
3. Quit to Main Menu
4. Check Information panel

### Expected behavior
Przechwytywanie

### PR DESCRIPTION
**Pull request by Pentarctagon**
Fixes #5095

### CODE REVIEW

**Comment by soliton-** [comment]
I'm not a fan of re-sending the same info to fix this in principle. I'd rather send the info/announcements again when they actually changed.

If we must do a server-side fix first then it should probably rather be done next to the player_record::enter_lobby calls (stuff like `player_connections_.get<game_t>().modify(it, std::bind(&player_record::enter_lobby, _1));`) to make sure we get all cases.

**Comment by gfgtdf** [comment]
> I'm not a fan of re-sending the same info to fix this in principle. I'd rather send the info/announcements again when they actually changed.

I agree here and at least for 1.15 at first sight i see no reason why we shouldn't be able  to fix  this on clientside.

**Comment by Pentarctagon** [comment]
Alright, I'll look at that then.  The main thing I wasn't sure about with a client-side fix was where to store the information rather than in `mp_lobby` in `lobby.*pp` as is done currently.

**Comment by Pentarctagon** [comment]
Updated to make the variables static, so their values are preserved through multiple instances of `mp_lobby`.

**Review by soliton- — APPROVED** [review]

**Pull request merged**
