### PR TITLE
Add new abilities for 1.15

### PR DESCRIPTION
**Pull request by newfrenchy83**
In htt.utbs andthe addon  loti ,  abilities type chance_to_hit or initiative exist with massive code in wml then. Why don,t create true abilities for addon developper work wiil more easy.
And yes it is a massive tan peoblem in attack
Cpp what i will correct in few days but i lokw had comment in the idea also crazy was it.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Eh, I'm not really sure of this... the general idea is good but I'm not sure about the method. (Also, if we're going to have "defense_leadership" we might as well just have "defense" too. The implementation of "defense" already exists in the source but was commented out because it was thought to be inefficient.) For example, I wonder why we actually need a new special for each case when we actually have all these specials already. We already have both "damage" and "leadership" though; but really, what's the actual difference between them?

**Comment by newfrenchy83** [comment]
like explain in changelog, thw idea is to use the affect_adjacent for use the abilitie on allies ennemies without must use object for create an latent_special. in legend of imvinciblr the weapon special have an abilitily leadership equivalent but an wml macros are necessary. for the defense_leadership name, i will what the name of ability remain different of defense tags who ignore the chance_to_hit special. i fear what same name for rsistance ability and movetype could create bugs.

**Comment by newfrenchy83** [comment]
I fix the tabulations now. And i try to justfie my leadership type abilities. If abilitie initiative and formation exist in canon campaign, and what Legend of the Invincible has a lot of unit with leadership abilities(marsman,berserk, drain etc...) thwn other addon devellopper could want make the same. With a more large chpice what damage resistance affect. I already explain that but for example shikadiqueen could create new unit line more complex if eventually she make the sequel of ats.

**Comment by newfrenchy83** [comment]
I complile attack.cpp with opp_ctx= special_context without use emplace and i haveno problems. I will test emplae but i trust what it's not function.

**Comment by gfgtdf** [comment]
> Instead of separate tag for each original ability, like firststrike_leadership, I would find it more useful if the ability supported using arbitrary weapon special inside new tag. Something like [supply_ability](with [filter])

there is alsoa  featurerequests that suggests that https://github.com/wesnoth/wesnoth/issues/1407

**Comment by newfrenchy83** [comment]
i don't think to weapon_special but leadership will be onsolete if damage could be used in abilities. and i don't see how doing this.

**Comment by ProditorMagnus** [comment]
Leadership implemented as [damage] and as [leadership] have different interactions with each other, especially when negative values exist.

**Comment by newfrenchy83** [comment]
i cannot call weapon_special in abilities without crash wesnoth. and add special tags in abilities don't resolve separate abilities tags but move in filter tags. and like apply_to=opponent not in abilities there ate not really weapon_special equivalent.

**Comment by newfrenchy83** [comment]
i tried but the weapon spwcials abilities are alll called same with tags. bad idea. best to have separate abilities tags.

**Comment by newfrenchy83** [comment]
@gfgtdf i will try your idea but i failed. i also see a bugs what i will corrected but i must close this PR before.

**Pull request closed without merging**
