### PR TITLE
Replaced Egg Sacs in EI with Fire/Giant Ant Eggs from core

### PR DESCRIPTION
**Pull request by Gothyoba**
This is a change proposed in #8734 

This is a small change that does not require any further balancing changes to the scenario in my opinion. It replaces the custom Egg Sac unit in EI with the Fire Ant Eggs and Giant Ant Eggs from core. The proposal in the issue above only mentioned Giant Ant Eggs, but given that fire ants exist in the scenario, some eggs near where fire ants first appear have been changed to Fire Ant Eggs. This also add some nice visual variety to this area in my opinion.

### CODE REVIEW

**Review by Dalas121 — COMMENTED** [review]
Assuming you've tested this and there's no bugs (bugs, get it?), using the mainline ant eggs sounds like a good idea to me.

I believe the ant eggs already have "hatch" events built in, so the custom logic in EI can be removed.

**Comment by Gothyoba** [comment]
I will make it a draft. It has been tested and seems to be bug-free, but I feel I to test it further before this can be merged, and I need to update copyrights.csv (which seems to be why checks are failing). Should be ready soon though.

**Comment by Gothyoba** [comment]
I still need the hatching logic to hatch the eggs when the queen is hurt, but this is currently not working yet, and it only hatches some of the eggs. Currently it seems its basic hatching mechanic only hatches them when an enemy unit is adjacent. I will also be doing some more work so that the hatched units are not randomly fire/giant ants when hatched by hurting the Ant Queen, but rather the type depends on the egg. Hopefully this will be working soon!

Also, this should not have the building or scons label. I accidently edited a related file once, leading to the labels being automatically added, but that has been fixed and this PR is unrelated to that.

**Comment by Gothyoba** [comment]
Most things are working now, though it seems when the Ant Queen in injured only one of the eggs hatches instead of all of them, which I have to fix. I also should copy over the hatching animation to the scenario file so they don't simply disappear.

**Comment by Gothyoba** [comment]
This PR keeps adding changes that were made to master as if their changes to the PR. As the THoT changes are already in master it don’t think this should create any issues in merging. It is still annoying forreviewibg though. The campaign THoT label can be removed. I’m currently still having the issue of only one ant egg hatching instead of all of them when the queen get injured. Hopefully I can fix that soon.

**Comment by Gothyoba** [comment]
I’m closing this. I won’t work on it, and its currently a mess.

**Pull request closed without merging**
