### PR TITLE
wmlxgettext: added support for plural forms (used on lua files)

### PR DESCRIPTION
**Pull request by AncientLich**
# wmlxgettext support for plural

Changelog:
* Added **--version** option (wmlxgettext version number is written in 
  *YYYY.MM.DD.py3* format, where "_py3_" underline the language used on 
  wmlxgettext: python 3.x)
* Added **--DMode** option --> I introduced a "stable" debugging code that can
  be executed only using this option. It will write an extra file (_debug.txt_)
  wich will record all the state sequences. It is a really useful option that
  helps me to debug wmlxgettext if something doesn't work as expected.
  Obliouvsly this option is useless for an end-user.
* Added lua plural support

### lua different string type, but no textdomain changes

The first test I did was focused to find and fix possible bugs on basic usage.
I tested wmlxgettext using this [lua source file](https://github.com/AncientLich/wmlxgettext-unoff/blob/master/wmlxgettext/test/reports/2016.10.03/tlua1.lua)

`wmlxgettext --domain=test1 -o tlua1.pot tlua1.lua`

And this is the [resulting pot file](https://github.com/AncientLich/wmlxgettext-unoff/blob/master/wmlxgettext/test/reports/2016.10.03/tlua1.pot)
Wich is exactly the desired result file.

**NOTE**: As you can notice, header file doesn't have the `nplurals` info, and
all plural sentences are associated to `msgstr[0]` and `msgstr[1]`.
Those settings, infact, higly change from language to language. They will be
"fixed" by the gettext tool _msginit_ .

`msginit -i input.pot -o dest_language.pot -l LOCALIZATION_CODE`

### Old vs new release on pot-update

This test was focused to check if the code I needed to add to allow the support
for plural forms on wmlxgettext introduced or not new bugs on the previous
features.
What we wanted to see here is that there are **NO** differences from the pot
files created by pot-update wesnoth target build, comparing the results created
by current implementation of wmlxgettext vs the new one.

For personal setup I cannot use directly the official pot-update, so why I 
developed a tool called _wescheck.py_ wich is available on my wmlxgettext
personal repository.

_wescheck.py_ originally was intendent to run _perl_ wmlxgettext, then _python_
wmlxgettext, comparing the results and error logs.

Test was performed against wesnoth 1.13.4 source directory

I will omit to write here all the tecnical details about the test, wich can be
[readed here](https://github.com/AncientLich/wmlxgettext-unoff/blob/master/wmlxgettext/test/reports/2016.10.03/wescheck.txt) if you are really interested.

What is important is the [resulting diff file](https://github.com/AncientLich/wmlxgettext-unoff/blob/master/wmlxgettext/test/reports/2016.10.03/test2.diff).

As you can check, the result is the desired one (all the differences, except ù
one, are related to file time creation, wich is expected). 

There is only an actual difference: on line 197 of the diff file you can notice
that the NEW wmlxgettext implementation captured another translatable string 
previously ignored

```lua
local wait_description = cfg.wait_description or _("input")
```

The new captured string (_input_) comes from this lua line code
(under data/lua/wml/message.lua:233, as marked by the diff file)

### testing updates on the same sentences

This test want to verify that the plural form is successfully updated on the
same sentence. This is the [lua test file](https://github.com/AncientLich/wmlxgettext-unoff/blob/master/wmlxgettext/test/reports/2016.10.03/tlua3.lua) we used as source. 

We have to test different scenarios:
    
1) Sentence that originally doesn't have a plural form, but later will have it.
Desired result: sentence with plural form, with references of every time
the sentence was met (regardless if plural form was specified or not)
**on pot file:** sentence1 (singular), sentence1 (plural)
2) Sentence that originally HAVE a plural form, but later not.
It is the opposite of case 1, but the expected result is the same.
**on pot file:** sentence2 (singular), sentence2 (plural)
3) Sentence that, for any reason, definde different plural values in different
points. Desired result: we want that the FIRST plural occurrence will be used
and other implementations will be discarded
**on pot file:** sentence3 (singular), sentence3 (plural)
4) Case 1 and 3 combined.
**on pot file:** sentence4 (singular), sentence4 (plural)

`./wmlxgettext --domain=test3 -o tlua3.pot tlua3.lua`

will produce [this pot file](https://github.com/AncientLich/wmlxgettext-unoff/blob/master/wmlxgettext/test/reports/2016.10.03/tlua3.pot), wich is exactly the result we expected.

### testing plural form and multiple textdomain

This test will focus to verify if the pot file will contain ONLY the desired
translations contained into the desired textdomain.

This is the [lua test file](https://github.com/AncientLich/wmlxgettext-unoff/blob/master/wmlxgettext/test/reports/2016.10.03/tlua4.lua) I used, and this is the
[pot file](https://github.com/AncientLich/wmlxgettext-unoff/blob/master/wmlxgettext/test/reports/2016.10.03/tlua4.pot) produced.

### testing mixed WML-lua file

This is the final test with a custom file. 
Here the [WML test file](https://github.com/AncientLich/wmlxgettext-unoff/blob/master/wmlxgettext/test/reports/2016.10.03/test5.cfg) used for the test, and here the
[generated POT file](https://github.com/AncientLich/wmlxgettext-unoff/blob/master/wmlxgettext/test/reports/2016.10.03/test5.pot)

### CODE REVIEW

**Comment by gfgtdf** [comment]
I didnt know our lua trabnslation code does support plurarly, if so could you please give a an example lua cod eon hwo to use plurarls?

**Comment by AncientLich** [comment]
Glad you find it. I couldn't give more details how to use the plural form on an actual wesnoth lua file (I never used lua file in my custom add-on), but I tested only what wmlxgettext is expected to capture (after all wmlxgettext is not a WML/lua parser, but only an utility wich collect translatable strings from wesnoth addons)

**Comment by AncientLich** [comment]
As I announced I retyped comments... now they should be correct. I needed to update other 2 commits becouse on the first one I introduced another bad comment, wich is now retyped in the second commit.

**Comment by loonycyborg** [comment]
From pot-update I got an error:
> error: data/ai/formula/engine.lua:9: first argument of function '_ (...)' must be a string

For some reason that file contains a large snippet of C++ code which happens to contain initializations like varname_(varname) which confuses wmlxgettext.

**Comment by AncientLich** [comment]
Thank for discovering this bug. 
Wescheck.py didn't  encounter this problem becouse I emulated pot-update within wesnoth 1.13.4 and not within the current wesnoth git snapshot (under the current snapshot the bug was reproduced also by wescheck.py).

Now the bug should be fixed. The regexp I used to check _ (  [introducing a translatable string wich possibly will have a plural form] was wrong becouse couldn't distinguish from a standard underscore used inside a variable name and an isolated underscore (wich is actually the function _).
Now the regexp is fixed: I added the requirement of a space character rightly before the underscore.
The problem is that this fix could intoduce another downside problem.
Probably if the line rightly starts with an isolated underscore (without space) that translatable string will be ignored.

Currently I'm thinking how to solve this issue. In the meantime I published the fix wich will work in all other cases, except the corner case I explained in this moment

**Comment by AncientLich** [comment]
Thank for discovering this bug.
Wescheck.py didn't encounter this problem becouse I emulated pot-update within wesnoth 1.13.4 and not within the current wesnoth git snapshot (under the current snapshot the bug was reproduced also by wescheck.py).

Now the bug should be fixed, The reason of the bug was the wrong regexp I used for LuaStr00 wich checks `_(`  [translatable string wich will possibly contain plural form]. In the original regexp I didn't add anything to distinguish from an isolated underscore followed by open parenthesis and an underscore wich is part of variable name wich is immediately followed by an open parenthesis.

You can notice I did two different commits for the same fix.

On commit #4 I added the first fix, wich was simplier (adding the requirement of a space before underscore). The advantage of this solution is that the regexp is simplier, so it can speedy a bit wmlxgettext.
The disadvantage of this solution is: it introduce a new bug on corner case: if the translatable string wich uses a parenthesis is placed IMMEDIATELY at the start of the lua code line (without any kind of space) the translatable string will be ignored.

On commit #5 I added another fix, wich uses a more complex regexp.
The advantage of this solution is that it woks also in the corer case where function _ followed by parenthesis is used at the very beginning of a lua line code.
This second regexp will be able to capture also that translatable string, unlike the regexp used on commit #4.
The disadvantage of this solution is that the regexp is a bit more complex and it can reduce a bit the speed of wmlxgettext.

**Pull request merged**
