### PR TITLE
Reachmap ai turn fix

### PR DESCRIPTION
**Pull request by AI0867**
This should address issue #2197.

### CODE REVIEW

**Comment by gfgtdf** [comment]
hmm compltley missed this one, assignoing to to me for now to that i won't forget it again

**Comment by GregoryLundberg** [comment]
@gfgtdf ping

**Comment by Pentarctagon** [comment]
So should this be left as tagged for 1.14.6, or should it be moved to 1.14.7?  This PR is now just over a year old.

**Comment by gfgtdf** [comment]
From looking at the code this seems to change how cursors behave: not the wait cursor is shown during network human turns. If this means that you can no longer check the units reachmaps during network turns, then i don't think this is a good idea.

Also for idle sides before_human_turn() is called but after_human_turn is not, also after_human_turn might not be calles if the sides controller was changed. So in total i think this looks somwwhat incomplte to me.

In total i'd say that this needs testing and should not go into 1.14.6 unless someone has the time do to the testing.

**Comment by Pentarctagon** [comment]
@gfgtdf Thoughts on whether to keep this open or not?

**Pull request closed without merging**
