### PR TITLE
create a simple overlay tag for resolve overlays bug

### PR DESCRIPTION
**Pull request by newfrenchy83**
To solve the problem in the https://github.com/wesnoth/wesnoth/issues/4058 issue, I had the idea to create a simple overlay that could contain only one image and use it for icon 'hero' and 'loyal' instead of overlays multiple that is no persist now. I also reassign unit_overlay and remove_unit_overlay to this unique overlay and add unit_overlays to multiple overlays.

### CODE REVIEW

**Comment by jostephd** [comment]
@newfrenchy83 Since you keep adding commits, please put a "[WIP]" marker in the PR title while you're still working on it and remove the marker when it's ready for review. Thanks.

**Comment by newfrenchy83** [comment]
i believe what it is good this time

**Comment by gfgtdf** [comment]
The only problem the the current solution is the compatability. And from the amount of changes in the wml of this pr this seems to force umc to rewrite their code even more than before so I don't really see the point.

**Comment by newfrenchy83** [comment]
i know but else it miust what overlays can contains one image only. my solution is not ideal but modify the wml code has the same problems, perhaps more. and if overlays is simple and not multiple, the cumulation of image don't be usable.

**Comment by newfrenchy83** [comment]
i could assign unit_overlay to simple overlay abd using unit_multiple_overlay for the case where overlays is necessary(book icon or other what loyal hero or oter crown), perhaps what it will be less changes in wml code.

**Pull request closed without merging**
