### PR TITLE
Tutorial: provide more detail about the Status Table

### PR DESCRIPTION
**Pull request by joeylmaalouf**
Simple text change addressing issue #2883.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Would be nice if we could variable-substitute the _actual_ key into the text, rather than only showing the default...

**Comment by joeylmaalouf** [comment]
Good point. I don't suppose you have any tips on how I might do that?

Based on `unit_mover::feedback()` in `src/actions/move.cpp`, I expect it to be something like `hotkey::get_names(hotkey::hotkey_command::get_command_by_command(hotkey::HOTKEY_STATUS_TABLE).command)`, but I've got no idea how to call that C++ code from the scenario WML.

**Comment by CelticMinstrel** [comment]
Yeah, I think we'd need to augment the Lua API for that, maybe add hotkeys to the preferences API (and expose that to normal scripts rather than just plugin scripts). So showing the default will have to do for 1.14.

**Comment by sigurdfdragon** [comment]
I don't agree with listing the default hotkey in the text, it makes it more complex than it needs to be. I think something like "You can access it in the <b>Menu</b> menu." would be sufficient.

**Comment by joeylmaalouf** [comment]
Sounds good! Updated.

**Comment by joeylmaalouf** [comment]
Bonus: there was another string in the tutorial that referenced the menu, but in a slightly different way, so I standardized the wording.

**Comment by sigurdfdragon** [comment]
Looks good. I'll merge this in a day or two to 1.14, then see about the forward porting of it.
Since this looks like your first pr for the project, if you'd like to, add yourself to the about.cfg's Miscellaneous Contributors section.

**Comment by sigurdfdragon** [comment]
@joeylmaalouf ^ &
Please also prefix the commits that affect the Tutorial with
T:

**Comment by CelticMinstrel** [comment]
Personally I'd prefer them to be prefixed with Tutorial:

But either works, I guess.

**Comment by sevu** [comment]
>in the <b>Menu</b> menu.

you have that word twice

**Comment by CelticMinstrel** [comment]
That's intentional @sevu. It means "the menu titled Menu"; that's why the first one is capitalized.

I agree it sound awkward though.

**Comment by joeylmaalouf** [comment]
"Tutorial:" it is.

The double-wording does sound a little off, but I wanted it to match the wording of "the **Actions** menu" that's everywhere else.

**Comment by sigurdfdragon** [comment]
@joeylmaalouf Since there doesn't seem to be any more suggested changes to the text, two more things and this can go in. Both of these are so it will be easier to merge & forward port to master as well.
1. Move the credits entry to a separate commit.
2. Remove the changelog entry. This pr may not make it in time before string freeze for 1.14.4 & It'll be easy enough to be added when it's merged. (copied here for reference)

>   * Tutorial:
>    * Added more information to the Status Table prompt about how to access it (issue #2883).

**Comment by sigurdfdragon** [comment]
@joeylmaalouf Almost there.
Had meant to remove the changelog entry by pulling it out of 
'Tutorial: provide more detail about the Status Table'
instead of making a removal commit

**Comment by sigurdfdragon** [comment]
Thanks for the contribution

**Pull request merged**
