### PR TITLE
fix bug in leadership abilities in master

### PR DESCRIPTION
**Pull request by newfrenchy83**
Fix https://github.com/wesnoth/wesnoth/issues/6269 issue

### CODE REVIEW

**Comment by Pentarctagon** [comment]
Please add a unit test for this situation.

**Comment by stevecotton** [comment]
What does this do to the speed of the AI? It seems that get_cumulative_value uses a cached value, but this calculates it with multiple nested loops each time.

I haven't tested, asking because I don't know.

**Comment by newfrenchy83** [comment]
> 
> 
> Please add a unit test for this situation.

test case added

**Comment by newfrenchy83** [comment]
> 
> 
> What does this do to the speed of the AI? It seems that get_cumulative_value uses a cached value, but this calculates it with multiple nested loops each time.
> 
> I haven't tested, asking because I don't know.

i not decide with this PR or added 'add' and sub to schema validation now what it can be used instead of cumulative=yes in leadership

**Comment by Pentarctagon** [comment]
Interestingly, though no idea if it's related or not: https://forums.wesnoth.org/viewtopic.php?t=55094

**Comment by newfrenchy83** [comment]
> 
> 
> What does this do to the speed of the AI? It seems that get_cumulative_value uses a cached value, but this calculates it with multiple nested loops each time.
> 
> I haven't tested, asking because I don't know.

for limit eventual decreased of AI speed, i implement for what abil.highest("value")( and lowest also) called what if [leadership] with cumulative=yes is present in the list, else if default calculation who is used. and 'add' and 'sub' can be used in same time.

**Comment by newfrenchy83** [comment]
@Pentarctagon I'll try to explain what this PR does:
first, all the abilities [leadership] and only those there are checked to verify if any of them has the attribute "cumulative = yes"
if this is the case then the method of calculating 'value' in abilities.cpp is abandoned in favor of the old method used for leadership in version 1.14, and this calculation is only performed once.
However, calculations with 'add', 'sub', 'multiply' or 'divide' remain active in case a leadership uses one of these attributes instead of 'value'.
Compatibility is not broken while fixing an issue that appeared in version 1.15, but too little reported before for me to understand the true usefulness of the cumulative option in [leadership] and I apologize for it.

**Comment by newfrenchy83** [comment]
@Pentarctagon review https://github.com/wesnoth/wesnoth/pull/6281 in same time, please.

**Comment by newfrenchy83** [comment]
someone could review this PR?

**Comment by Pentarctagon** [comment]
Unless there are further comments in response to https://github.com/wesnoth/wesnoth/issues/6269#issuecomment-970588681 I am planning on closing the issue and the related PRs since it seems to actually be working as intended now.

**Comment by newfrenchy83** [comment]
> Unless there are further comments in response to [#6269 (comment)](https://github.com/wesnoth/wesnoth/issues/6269#issuecomment-970588681) I am planning on closing the issue and the related PRs since it seems to actually be working as intended now.

only if you use add or sub insteat of  value with cumulative=yes. else, the using of cumulative=yes remain diffrent in 1.16 what in 1.14.

**Pull request closed without merging**
