### PR TITLE
 resolve negative value for leadership and alternate for heal 

### PR DESCRIPTION
**Pull request by newfrenchy83**
i post an alternate PR to https://github.com/wesnoth/wesnoth/pull/3748 for not broken heals where "value" not used. i let both PR open because i can't choice a solution

### CODE REVIEW

**Comment by gfgtdf** [comment]
calling list.lowest("value").first/list.highest("value").first inside the effect constuctor list is potentialls slow and unnessesary, just kjeep track of both the nimimal set effect and the maximal set effect (replace `individual_effect set_effect;` with `individual_effect set_effect_max, set_effect_min;`) and the do the aprropritate claulation atr the end of the constructor.

**Comment by gfgtdf** [comment]
From looking at the (old) code it also seems like `cumulative` actually has a differnt meaning in single value effects and effects that support the whole sub/add/mul etc mechanism, in the first case it means just sume these values up whiel inth e secodn case it means 'cannot decrease the base value'

**Comment by gfgtdf** [comment]
thinkin about i'm unsure how cummulative with multiple abilitites is supposed to work ín the first place, assume for example you have a unit with a natural 90% change to hit becasue the enemy stands on deep water but you have both the marksman and the magical attack special. What is the expected bheviour in this case?

**Comment by newfrenchy83** [comment]
the maksman is xeapon special or abilities like weapon?

**Comment by newfrenchy83** [comment]
if a using a weapon like chance_to_hit to 60% with cumulative=no then i must exclude special=magical in filter_weapon else result 60% same if weapon is magical but if cumulative=yes then the highest value (70%)is used because weapon special calculate cth before cth ability. with add, sub etc.. cumulative don't usable but, if two abilities with one add=10 and other add=20 two case possible, if ability id is the same then add=20, else if id diffrent then add=(10+20).

**Comment by newfrenchy83** [comment]
@gfgtdf i tried with your approach (individual_effect set_effect_max, set_effect_min) but i find the same problem what i had in my first PR with effect constructor involved, i must use list.(highest/lowest) but i put this in the end of constructor for don't too slow this. the solutions who don't involve effect break heals don't using "value" and don't extent to "drains" ability.

**Comment by gfgtdf** [comment]
Which problem were there exactly?

**Comment by newfrenchy83** [comment]
i mentionned in https://github.com/wesnoth/wesnoth/pull/3739 when i speak of value who change if student is left or right of two or more owners of abilities. it is why i using highest lowest value for what final value was the same. and use list.higest is more easy what put the extremum code in cnstructor

**Comment by gfgtdf** [comment]
It certailny to avoid that problem and also to aboid that extra highest/lowest call let myput a sample code here

**Comment by newfrenchy83** [comment]
thanks @gfgtdf for your code, now it don't problem anymore! i just fix declaration problems and set_effect

**Comment by newfrenchy83** [comment]
i added test case for heals with negative value.

**Comment by newfrenchy83** [comment]
@gfgtdf i pull an old_calc option for fix a bug in illuminates abilities

**Comment by gfgtdf** [comment]
what exactly was the bug in illuminates ability?

**Comment by gfgtdf** [comment]
I think that we should NOT calculate differnt abilitity values diffently, since that will only be confusing to umc authors.

>a Mage of Light and a unit with darkens aura are adjacent, in neutral tod, the Mgae a -25% damage, then what he must be neutral in this tod.

It is still unclear what you mean here.

**Comment by newfrenchy83** [comment]
colsed and replace by https://github.com/wesnoth/wesnoth/pull/3765

**Comment by newfrenchy83** [comment]
if Mage of light and a unit with illuminates value=-25 min_value=-25 then in new rules of calculation, the Mage have 25% of malus then what before the bonus was 0 in neutral ToD, this because illuminates have his proper rule of calculation for compensate the old rule, but if calculation is aready done in effect constructor, then the result will be different.

**Comment by gfgtdf** [comment]
i cherry picked b74a326 to master

**Pull request closed without merging**
