### PR TITLE
utbs add mode=append to fix set_specials erase specials already there

### PR DESCRIPTION
**Pull request by newfrenchy83**

### CODE REVIEW

**Comment by gfgtdf** [comment]
This looks good to me, j actually really think append should be the default mode in the c++ source, but I'm not sure whtger this might break things, so let's not do that in this pr

**Comment by newfrenchy83** [comment]
> 
> 
> This looks good to me, j actually really think append should be the default mode in the c++ source, but I'm not sure whtger this might break things, so let's not do that in this pr

Perhhap will i pull a PR for resolve this in C++ but i would what this pR was commited, and https://github.com/wesnoth/wesnoth/pull/4719 also who fix another bug

**Comment by newfrenchy83** [comment]
@gfgtdf i forget to specify what this PR is not only for master but also for 1.14 branch.

**Comment by gfgtdf** [comment]
Wait I thought I already merged this?

**Pull request merged**
