### PR TITLE
[Lua] Clean up inconsistencies in mapgen filter API, and improve documentation

### PR DESCRIPTION
**Pull request by CelticMinstrel**
I split this from #7359 so that @gfgtdf can easily review and merge it. It looks like several places are just doing entirely the wrong thing. I haven't verified that I caught _every_ place with this issue, but it's likely that I did, as I think they all would've raised the same warning in my Lua linter.

### CODE REVIEW

**Comment by gfgtdf** [comment]
Why is this incrrect usage of map filters, i'm pretty sure map:find does support passing a table as the second argument

**Comment by gfgtdf** [comment]
Here map:find creates the filter object form the table 
https://github.com/wesnoth/wesnoth/blob/e644613caeeec3546d2cfaaea2c9ebbcdd79c23a/src/scripting/lua_terrainfilter.cpp#L713

**Comment by CelticMinstrel** [comment]
> Why is this incrrect usage of map filters, i'm pretty sure map:find does support passing a table as the second argument

Well… it's not how it's _documented_ to work. Good to know it works anyway, but… it does make you wonder why `wesnoth.map.filter` even exists if you actually never need to call it…

**Comment by gfgtdf** [comment]
> but… it does make you wonder why wesnoth.map.filter even exists if you actually never need to call it…


I think it has a constructor which takes an additional "known_locations" parameter, that isn't supported when you just pass a table to map:find, also its in theory possible to reuse a filter, and save some cputime for building it again.

**Comment by CelticMinstrel** [comment]
> I think it has a constructor which takes an additional "known_locations" parameter, that isn't supported when you just pass a table to map:find, also its in theory possible to reuse a filter, and save some cputime for building it again.

Looks like _this_ isn't documented either… wonderful! Seems like that extra parameter is _only_ used by the `f.find_in` filter type. Seems kind of crazy to have an extra argument solely for that one filter type. Can you explain very clearly what it does? Something I could add to the documentation comment in emmylua/map.lua. I can kind of guess from inspecting the code, but I don't fully understand what's going on there.

If we can get the documentation to a point that the linter accepts the code changed in the middle commit, and you prefer that commit to be removed, then I'll do so. Are the other two commits fine? Particularly the first one, as I wasn't entirely sure what was intended there.

Oh, and while we're on the topic of undocumented things:

* `f.formula` is undocumented, though the meaning seems obvious enough, so I'll just go ahead and add it
* `f.cached` is undocumented, and I have no idea what it's supposed to do?
* There's an `onborder_filter` that's defined but not exposed nor used anywhere, why?

(Technically those two `f.*` cases are undefined, so it would required you to write `{'formula', ... }` to use them. I'll fix that, as long as we can properly describe what they even do.)

**Comment by CelticMinstrel** [comment]
This kinda turned into smoothing out inconsistencies in the API and correcting the documentation, so I'll rename it; but if you want to, you can feel free to cherry-pick the first and third commit.

**Comment by gfgtdf** [comment]
> Particularly the first one, as I wasn't entirely sure what was intended there.

The first one looks fine, i compared it it to the original wc2 wml code, and the now code is how it is supposed to work.

> Looks like this isn't documented either…

I think quite a few of these aren't documented because i wasn't that happy with their current shape and wanted to change them later at some point, but didn't find the energy to do that.


> Seems like that extra parameter is only used by the f.find_in filter type. Seems kind of crazy to have an extra argument solely for that one filter type. Can you explain very clearly what it does?

iirc currently its only usecase is that it can be refered to in find_in("") fin_in contains a name of a location set that is defined in the second parameter of the filter constructor, 

> f.cached is undocumented

It caches its result, in particular when we have a lot of adjacent filers lets say we want all location matching `f.adjacent(filter_1)` the "naive" approach (check whether each location matches the condition) might execute filter1 quite often in the worst case 6 times for each tile, with nested adjacent filters is can easily get worse. 

I am not sure when exactly the cache is cleared though, so these filter objects might not be reusable..

**Comment by CelticMinstrel** [comment]
> The first one looks fine, i compared it it to the original wc2 wml code, and the now code is how it is supposed to work.

Okay, I'll push that to master. Does the 3rd commit also look fine?

> iirc currently its only usecase is that it can be refered to in find_in("") fin_in contains a name of a location set that is defined in the second parameter of the filter constructor,

So, if I understand that correctly, the following two filters are equivalent?

```lua
local f = wesnoth.map.filter_tags
wesnoth.map.filter( f.find_in{ {1,1}, {2,2}, {3,3} } )
wesnoth.map.filter( f.find_in "my_locs", { my_locs = { {1,1}, {2,2}, {3,3} } )
```

If that's accurate, then I'll need to update the documentation again…

> It caches its result, in particular when we have a lot of adjacent filers lets say we want all location matching `f.adjacent(filter_1)` the "naive" approach (check whether each location matches the condition) might execute filter1 quite often in the worst case 6 times for each tile, with nested adjacent filters is can easily get worse.
> 
> I am not sure when exactly the cache is cleared though, so these filter objects might not be reusable..

Hmm… it sounds like it's best to leave this one undocumented for the time being, as it's not clear if it's even useful… or do you have a good example of its use?

**Comment by Pentarctagon** [comment]
Is this something you're looking to get into 1.18?

**Comment by CelticMinstrel** [comment]
At least the first and third commit should be, assuming @gfgtdf approves the third one. If not, then at least the first commit.

For the rest, it would be nice but not essential.

**Comment by CelticMinstrel** [comment]
I think this is probably about ready for merging. Any thoughts, @gfgtdf ?

**Comment by CelticMinstrel** [comment]
@gfgtdf Any comments on this? It'd be nice to get it merged within the next week.

**Comment by gfgtdf** [comment]
Looks good to me i think

**Review by gfgtdf — APPROVED** [review]

**Pull request merged**
