### PR TITLE
Walking Corpse variation portraits

### PR DESCRIPTION
**Pull request by doofus-01**
This PR is to give portraits for Walking Corpse variations.  At this time, the "swimmer" and "wolf" variation are not done.  (The "gryphon" variation is cheaply done, but I think that is all that variation deserves.)

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Looks nice!

**Comment by doofus-01** [comment]
All the existing variations have a portrait now.  If these are deemed better than nothing, they can be committed now.  Some could probably be improved, but I wouldn't hold my breath for masterful critique or professional approval on the forums.

**Comment by ln-zookeeper** [comment]
Some could certainly be improved further (mostly I'm thinking of the wolf), but I don't mind if they go in since, as said, they're better than nothing.

I was able to achieve a bit better compression with zopflipng, so I can put these in by hand too if that's okay.

**Comment by doofus-01** [comment]
I have no objections, if you are asking me.

**Comment by ln-zookeeper** [comment]
All right, it's done in 18f866eb. Will changelog it as part of my usual changelog updates before next release.

**Pull request closed without merging**
