### PR TITLE
Quotation marks in mountains WML so wmlparser.py outputs proper results

### PR DESCRIPTION
**Pull request by BlueWinds**
Previously, running `wmlparser2.py -k` (or wmparser3.py) resulted in rules containing text like this:
```
    {
     "name": "mountains/dry_range35.png",
     "base": "306,144"
    }
```
dry_range35.png doesn't exist. Adding quotes around the image suffix results in this:
```
    {
     "name": "mountains/dry_range3_5.png",
     "base": "306,144"
    }
```
dry_range3_5.png does exist. Things work properly in-game either way - this issue is only visible in wmlparser[2|3].py.

Suggested fix courtesy of @ln-zookeeper on the forums (https://forums.wesnoth.org/viewtopic.php?f=21&t=44945&sid=da79aff862f7f997abb8be22734cfe31)

------

My first attempt at a commit / pull request for wesnoth. Please let me know if there's anything I should change or do differently. :)

### CODE REVIEW

**Comment by ln-zookeeper** [comment]
Otherwise good, but the credits addition should rather go into the "Miscellaneous Contributors" section.

**Comment by BlueWinds** [comment]
Amended the commit to put attribution in the right place.

**Comment by gfgtdf** [comment]
I wonder why we cannot just fix wmlparser[2|3].py? I'd guess that we just have a to change the check for whether it is a trasnlatable string from string.begins_with("_") to string.begins_with("_ *\"") somehere . Not sure on the exactly condition when the _ indicated a translatable string in the the c++ code, but it doesn't sound too hard to do.

**Comment by BlueWinds** [comment]
@gfgtdf - I was less sure that it wouldn't have side effects I wasn't aware of, and also hadn't found it in the code. Pushed a new commit adjusting wmlparser.py instead of mountain.cfg file.

**Comment by gfgtdf** [comment]
The new code seems like `var = _"string"` is no longer accepted while `var = _ string` is still errorously treated as a translatable string by the python code. I didn't understand the c++ code that does this parsing so i am not 100% sure, but i think the actuall check shodul be: first a `_` then a arbitary number (including 0) of spaces an then a `"`, at lest that was the rult of some quick testing that i did.

**Comment by CelticMinstrel** [comment]
Yeah, this fix is clearly wrong. There is not always a space after the underscore in a translatable string. There is, however, always a quote after the underscore (possibly separated by one or more spaces). So, you need to check for the presence of a double quote. (Single quotes are not allowed, only double quotes.)

**Comment by BlueWinds** [comment]
That's why I wanted to go with the simple fix, and just add quotes to mountains.cfg. ^^;; I'm not super into in learning about translateabel strings and wesnoth's internals - my interest is just in wmlparser.

**Comment by gfgtdf** [comment]
> That's why I wanted to go with the simple fix, and just add quotes to mountains.cfg. ^^;; I'm not super into in learning about translateabel strings and wesnoth's internals - my interest is just in wmlparser.


Hm yes but if we are already at it it'd be nice if we could make it work for umc content too, not only for content that has been 'fixed' to be compatible with wmlparser.py

I still think that using a regex check is the simplest sultion. I don't really know python but most modern languages to support regex in their core libary and i'd be suproised if python didn't.

**Comment by CelticMinstrel** [comment]
Something like `re.match(r'_\s*"')` should do it. (And of course import re. Might need find rather than match, I can't remember.)

**Pull request closed without merging**
