### PR TITLE
Tutorial part 2 typo fixes & text changes

### PR DESCRIPTION
**Pull request by sigurdfdragon**
Some typo fixes & minor text cleanup in Tutorial Part 2. Let me know what's usable & I'll delete/squash commits as appropriate.

### CODE REVIEW

**Comment by Vultraz** [comment]
Everything looks good. Merging.

**Comment by CelticMinstrel** [comment]
I kind of question the first two changes in the diff - it feels like they weaken the point.

**Comment by sigurdfdragon** [comment]
@CelticMinstrel
My thoughts on the first one were saying that 'might be cheaper' was odd, as it's always cheaper to recruit an Elvish Fighter, always the same cost to recruit/recall a Mage, always more expensive to recruit a Horseman. It seemed like 'better' handled the intent better.

For the second one, hmmm... I saw the enemy counterattacking as occurring on the enemy's turn, which is why I put 'overall' in. If the counterattack is understood as the enemy's response when you are attacking, then the original version makes more sense. So, with this one, I'm now inclined to agree you. Though perhaps a different way of wording the whole sentence might be better.

**Comment by CelticMinstrel** [comment]
Sorry, the second one in question was "first" -> "as well".

About the cost, that's true. I think the intent was to reference some sort of idea of "relative cost" whereby, even though the absolute price is always 20, it's "cheaper" when the unit being recalled is more valuable. But maybe you have a point - that could confused people.

**Comment by sigurdfdragon** [comment]
With "first" -> "as well", I think my thought was along the lines of making it more in harmony with the previous message in the scenario about recalling veterans. And I think I was going for a weakening, as recalling them first isn't always the best idea. (ie, level 2's being recalled on turn 2 to give time for turn 1 village grabbing to better cover upkeep.)

**Pull request merged**
