### PR TITLE
lol

### PR DESCRIPTION
**Pull request by ToBeFree**

### CODE REVIEW

**Comment by ToBeFree** [comment]
If anyone wonders why I'm laughing: I think adding a year there is completely unneeded anyway. The latest commit has been "new year update" and shows 2015, so nobody cares anyway. Why not "since 2003" or something like that? Someone once mentioned legal issues, but I can't believe that one really needs to have a frequently updated "copyright end date" to claim their rights. Snake oil, that's it.

**Comment by jyrkive** [comment]
Thanks, merged.

**Comment by GregoryLundberg** [comment]
No. That's not how copyrights work.

Absent any other information, the copyright for the file is presumed to begin in 2003 and, therefore, expire 75 years following the death of David White (still pending). Assuming the file was actually published in 2003, statutory protections expire after 25 years, at the end of 2028.

The reason for date ranges is to warn that portions of the file might have copyrights as late as 2013 or 2017 or whatever. The enforce those rights, however, the actual author of that portion would need to be able to prove authorship and a publication date (the commit logs will help a lot with that).

Note that file file you're concerned with is the copyright boilerplate. That file probably has no copyright protections because it is not a significant work.

Authors are expected to copy that boilerplate into their files and update it as appropriate. That would include changing the date(s) and name(s).

**Comment by ToBeFree** [comment]
Ah, I think I understand now. I thought it's a weird unneeded addition, but that's an interesting aspect.

**Pull request merged**
