### PR TITLE
Update Xcode build settings

### PR DESCRIPTION
**Pull request by cooljeanius**
PR #9510, take 2:
In attempting to address https://github.com/wesnoth/wesnoth/issues/9478 I opened the Xcode project, and while I didn't see the build setting in question for that issue, it did prompt me to make some other changes to the build settings... just opening this PR to see what sort of effect the changes have on CI...

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
This probably shouldn't be merged without approval from every regular contributor who uses a Mac (and in particular the Mac packager, which is @hrubymar10 if I recall correctly). I don't think any of the changes in here do anything important though. It looks like mostly just enabling some new warnings. The one change that seems like it'd have potential to break people's builds though is `ENABLE_HARDENED_RUNTIME`. I'd have to actually try it to know, but I seem to remember having issues with that setting in the past.

Note that I use Xcode 12 and cannot update since Catalina cannot run Xcode 13. But I doubt any of the changes in this PR (other than maybe `ENABLE_HARDENED_RUNTIME`) would break the build on Xcode 12.

**Comment by Pentarctagon** [comment]
Note that the hardened runtime is already enabled for the signed release: https://github.com/wesnoth/wesnoth/blob/master/projectfiles/Xcode/The%20Battle%20for%20Wesnoth.xcodeproj/project.pbxproj#L6816 which is required for notarized apps.

**Comment by CelticMinstrel** [comment]
That's fine. That's not the build anyone uses for iteration and debugging.

**Comment by Vultraz** [comment]
It looks like hardened runtime needs to be enabled if you want your build notarized, but I don't see anything immediately obvious about it that would break dev builds.

**Comment by Vultraz** [comment]
RE the original issue though, this option doesn't show up in XCode 13? https://stackoverflow.com/a/72800877

**Comment by CelticMinstrel** [comment]
> I don't see anything immediately obvious about it that would break dev builds.

I don't remember if it was definitely due to the hardened runtime, but I've run into issues where the build just won't start. That's why I said it should be tested first before merging this.

**Comment by CelticMinstrel** [comment]
The new change seems like it's much _more_ likely to break something than all the previous changes, given that it changes a string to an array.

**Comment by cooljeanius** [comment]
> The new change seems like it's much _more_ likely to break something than all the previous changes, given that it changes a string to an array.

Well, let's see how the CI handles it...

**Comment by CelticMinstrel** [comment]
The CI isn't what you need to be worried about.

**Comment by cooljeanius** [comment]
hm that's strange, it looks like the build actually takes longer after turning on parallelization than it did before... (43 minutes before vs. 54 and 57 minutes afterwards...) ...also why did only the Release build run this latest time? How do we get the Debug build to run again?

**Comment by Vultraz** [comment]
It's been release-only for a while (for both Mac and windows). The CI runs just take so long and we want some of that time for extra Linux builds.

**Comment by CelticMinstrel** [comment]
You can make the debug build run by editing the CI yml. I'm not exactly sure what the edit would look like though.

**Comment by cooljeanius** [comment]
> You can make the debug build run by editing the CI yml. I'm not exactly sure what the edit would look like though.

OK, let's see how [1424857](https://github.com/wesnoth/wesnoth/pull/9511/commits/1424857dda47eac9e905daad808d304004f8863e) fares...

**Comment by CelticMinstrel** [comment]
Still, the CI passing is not enough to merge this. The CI is using Xcode 15, but it needs to build even on Xcode 12 and possibly on 11 (unsure about that one, and I have no way to test it myself).

**Comment by cooljeanius** [comment]
I'm also kind of curious as to why the macOS builds actually take *longer* now with parallelism than they did before...

**Comment by cooljeanius** [comment]
I'm playing with increasing the number of `scons` build jobs in my fork in cooljeanius/wesnoth#138, but something seems to have broken there...

**Comment by CelticMinstrel** [comment]
I don't really know, but… I would think the CI is running on a server with relatively low CPU power. Parallelism helps when you have a lot of CPU cores to share the load between, but it won't make as much of a difference if all you have is 2 or 4 shared virtual CPUs on a virtual host… I guess?

If setting this flag actually makes the situation worse in CI, we could always just close this. Then I don't need to worry about checking if it works in Xcode 12.

**Comment by cooljeanius** [comment]
> I don't really know, but… I would think the CI is running on a server with relatively low CPU power. Parallelism helps when you have a lot of CPU cores to share the load between, but it won't make as much of a difference if all you have is 2 or 4 shared virtual CPUs on a virtual host… I guess?
> 
> If setting this flag actually makes the situation worse in CI, we could always just close this. Then I don't need to worry about checking if it works in Xcode 12.

OK.

**Pull request closed without merging**
