### PR TITLE
Improve default settings for the timer

### PR DESCRIPTION
**Pull request by Hejnewar**
Change default settings for the timer to 240/240/360/0.

Will forward port latter.

### CODE REVIEW

**Review by knyghtmare — APPROVED** [review]

**Comment by soliton-** [comment]
Is there any rationale for this?

**Comment by Hejnewar** [comment]
Action bonus - is often thought as inconsisnent and generally not very well understood not only by new players but aslo by players with mid tier experience, so removing it from initial setting should improve overall experience of a new player.
Turn bonus - 60 seconds is way too low and initial 270 is also not much for the whole game. 240/240 does better job at keeping the game in good pace while not being too opressive in my opinion, 360 reserve is aslo ok if you can save some time for more intensive turns.

**Comment by soliton-** [comment]
Please put the rationale into the commit message when merging.

**Comment by Hejnewar** [comment]
No problem.

**Comment by gfgtdf** [comment]
If action bonus is too complicated we could consider having something else, for example a "bonus per unit" meaning you get x second per turn for each unit that you have.

**Comment by Hejnewar** [comment]
Thats honestly pretty good idea. Having something simpler would be nice. With this proposal tho I dont like the fact that it would often reward the player who is ahead already, but other than that it could be worked out I guess / it could work for non PvP scenarios.

**Pull request merged**
