### PR TITLE
Delete old ability's description:Unpoison

### PR DESCRIPTION
**Pull request by fujimo-t**
There is "Unpoison" in the manual, but I don't know the ability such name.
It has almost same description as "Cure".
I think it is an old ability, so it should be deleted.

### CODE REVIEW

**Comment by Vultraz** [comment]
"Unpoison" is actually a valid ability - it cures poison, but doesn't heal. "Cures" cures poison, *and* heals.

**Comment by gfgtdf** [comment]
> "Unpoison" is actually a valid ability - it cures poison, but doesn't heal. "Cures" cures poison, and heals.

units like white mage, elvish druid all have both abilitites 'heals+8' and 'cures' where heals+8 does the healing and cures does just cure poision. there is a ABILITY_UNPOISON macro but afaik this manual is not a a macro documenation for wml developers but a documantation for players.

**Comment by CelticMinstrel** [comment]
What Vultraz said is correct, from a designer's point of view, but from the player's point of view, the original poster is correct.

**Comment by Wedge009** [comment]
It sounds like even in the code 'unpoison' is a synonymous with cure. Unpoison isn't a word in English anyway. I vote for removing the description.

**Comment by pydsigner** [comment]
> "Unpoison" is actually a valid ability - it cures poison, but doesn't heal. "Cures" cures poison, and heals.

You're thinking of the... heal 8 plus? macro, which adds both the cure ability and the heal 8 ability. It's not one heal+cure ability.

**Comment by pydsigner** [comment]
Hmm ok looks like I'm wrong on this — {ABILITY_CURES} is the combining macro for {ABILITY_UNPOISON} (cures) and {ABILITY_EXTRA_HEAL} (heals +8). So there's a bit of a mismatch that would be nice to resolve, but difficult. That does not affect this change manual, however, which I think is fine.

**Pull request merged**
