### PR TITLE
Add a hack to workaround setting the fontconfig cachedir only for windows.

### LINKED ISSUE #7089: Wesnoth creates D:\a\msys64\var\cache\fontconfig with two files inside
### Game and System Information

The Battle for Wesnoth version 1.17.9 x86_64
Running on Microsoft Windows 7 Service Pack 1 (6.1.7601) x86_64
Distribution channel: Steam

### Description of the bug

While the game is active it won't let me delete the files, but even if I delete the entire path, when I start the game it is created again.

### Steps to reproduce the behavior

1. Start the game
2. Go to the main folder of the drive (X:) when the game is installed
3. X:\a\msys64\var\cache\fontconfig appears with two cache files inside

### Expected behavior

Store cache files on
Cache dir:       C:\Users\USER\Documents\My Games\Wesnoth1.17\cache

### Additional context

Possibly only happens on Windows 7

### PR DESCRIPTION
**Pull request by Pentarctagon**
Fixes #7089

### CODE REVIEW

**Comment by Pentarctagon** [comment]
Barring any comments or ideas for a better approach, I'll be merging this in a couple of days.

**Comment by loonycyborg** [comment]
I asked about it on msys2 gitter. Seems it's indeed packaging issue with fontconfig. This hack should be fine until they fix it.

**Comment by Pentarctagon** [comment]
Is there any sort of issue that could be linked to here? Or it's just in the chat history somewhere?

**Comment by loonycyborg** [comment]
https://matrix.to/#/!KcLVgQvsWqZARtzJOs:gitter.im/$5hFQAt4bI1ODI7BI8fH-zNG2twdBCxG_-Kg0PJliq_o?via=gitter.im&via=matrix.org&via=mozilla.org

**Pull request merged**
