### PR TITLE
Backport of #6685

### PR DESCRIPTION
**Pull request by Pentarctagon**
Should hopefully address #7543

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Issue numbers in the title don't create an auto-link, so: #6685

**Review by loonycyborg — APPROVED** [review]

**Comment by Wedge009** [comment]
@Pentarctagon The Windows installer from the artefacts seemed to include a build that loads the Lato font correctly. But you also need to back-port #6923 because now #6908 is showing.

**Comment by gfgtdf** [comment]
This looks like a risky commit to me,  did you test that it did nott break https://github.com/wesnoth/wesnoth/issues/7462 in 1.16

**Comment by gfgtdf** [comment]
Accidentally clicked the wrong button

**Comment by Pentarctagon** [comment]
> This looks like a risky commit to me, did you test that it did nott break https://github.com/wesnoth/wesnoth/issues/7462 in 1.16

It would of course result in that bug occurring in 1.16 as well.

> Furthermore iirc the " utf8" part is not supported by windows 7, so if it is needed for the fix, the fix might not work under windows 7

I think this was tested and worked fine? The minimum windows version for 1.17 is still listed as Windows 7 and I'm pretty sure I would've updated that if it changed because of #6685.

**Comment by Pentarctagon** [comment]
@Wedge009 could you check whether or not having non-ascii characters in the path where you installed Wesnoth to causes any issues?

**Comment by Wedge009** [comment]
I don't normally have any non-ASCII characters nor special characters (besides space) in my Windows directories. I'm travelling again, should be back home in around 9 days from time of this post.

**Comment by gfgtdf** [comment]
> It would of course result in that bug occurring in 1.16 as well.

Knowingly breaking addons code in stable, even if it's just visual issues that some might consider minor, is obviously something that we shouldtry try to avoid.

Are there reasons against simply shipping 1.16.9 with the previous pango versions?

**Comment by gfgtdf** [comment]
Since there is probably still some time until 1.16.10 gets tagged, my approach would be to wait and hope that either #7462 or #7543 is fixed upstream (especially since it seems that pango releases are kinda frequent), and postpone the decision of merging this for now.

**Comment by Pentarctagon** [comment]
Sure, there's no rush. My guess though would be that since #7462 happened when switching to us using fontconfig on Windows rather than from upgrading to a particular version of pango, it's less likely to be quickly fixed.

**Comment by Pentarctagon** [comment]
Seems like https://github.com/wesnoth/wesnoth/pull/7547 can't be backported since the version of fontconfig provided by the Scout steam runtime is too old.

**Comment by Wedge009** [comment]
@Pentarctagon I took the installer from the most recent 'action' that I could find (https://github.com/wesnoth/wesnoth/actions/runs/4812991123) and used `é` in my installation path (this is on Windows 7). In this case I get a crash on launch, though the logs appear to show something closer to #7217 than #7543.

`Dev message: /wesnoth/src/gui/widgets/window.cpp:945 in function 'layout' found the following problem: Failed to size window; wanted size 980,426877 available size 1920,1200 screen size 1920,1200.`

Nonetheless, removing the `é` from the path name such that only ASCII characters and 'normal' symbols (space character, `+` sign from `1.16.9+dev`, etc, remain) and the game starts normally again.

For what it's worth, at least the Lato font is loading normally. Though #7089 is introduced to 1.16 (previously I only observed it in 1.17).

**Comment by Pentarctagon** [comment]
Alright, so this can't be merged then.

**Pull request closed without merging**
