### PR TITLE
Add override specifier to derived virtual methods

### PR DESCRIPTION
**Pull request by PoignardAzur**

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I'm just kinda surprised that this is such a small change. I thought there'd be more overridden virtual methods.

**Comment by PoignardAzur** [comment]
I think most of them already had the override keyword.

**Comment by jyrkive** [comment]
Or it might be that @PoignardAzur only caught a small subset of them. IIRC, he can't build the game. (Issues with Boost.Bind, same as with @ancestral )

**Comment by PoignardAzur** [comment]
To be precise, I can't build the game with clang++. g++ is okay for some reason.

As far as I can tell (with g++ -Wsuggest-override), all overridden virtual methods have been marked.

**Comment by jyrkive** [comment]
I found an overridden virtual method that isn't marked: [`gui::textbox::handle_event()`](https://github.com/wesnoth/wesnoth/blob/087a2822d16b8eb129a271e4a6e66edd51a5be6f/src/widgets/textbox.hpp#L103). Whatever g++ does with -Wsuggest-override, I'm afraid it likely missed opportunities to use the `override` specifier all over the place. :(

**Comment by aginor** [comment]
All of the sdl_handler methods most likely lack the keyword, I think the hotkey handling code does too.

**Pull request merged**
