### PR TITLE
draw: dashed lines w/ arbitrary pattern

### PR DESCRIPTION
**Pull request by white-haired-uncle**
Adds drawing dotted/dashed lines based on a supplied bitset, as mentioned in #9238.

Silly example.  You really have to scroll in to see the lines based on two points.
Untitled

### CODE REVIEW

**Comment by Vultraz** [comment]
Do you have a specific usecase in mind for these? I'm hesitant to add them otherwise, since I don't really see where we might use them.

**Comment by white-haired-uncle** [comment]
Debug borders is the one I'm interested in.  I definitely like this way better than what I did with fixed patterns.  Other than that, I got nothing.  But once the suggestion was made, I just had to try it.

@CelticMinstrel said:
> I kinda feel like this dashed/dotted stuff would be nice to support as a border style in canvas shapes.

**Comment by CelticMinstrel** [comment]
I like this! I'm not sure what use-cases there are, but I bet someone can come up with one…

**Comment by white-haired-uncle** [comment]
At first I was thinking it might be useful to add as a new shape for [drawing].  Don't know what users would draw with it, but it's a nice enough addition.  But I think that really boils down to "as a border style in canvas shapes" - a bitset could be added to all(?) existing shapes, and a line is just another shape that only has one side?

At some point, I'm going to have to learn more about [drawing], canvases, and definitions.  Pretty sure they're closely related in at least one way, but I'm not there yet.

**Comment by Vultraz** [comment]
I think I'm going to close this. It looks like SDL3 is encouraging people to adopt floating point coordinates for drawing, and I don't think this would fit in very well with that. Besides, the proposed use case (widget borders) doesn't benefit from an arbitrary pattern (unless this is intended to replace the dashed lines implementation from your other PR?)

**Comment by white-haired-uncle** [comment]
That's fine.  It was intended to replace the dashed/dotted lines in the debug borders (not just widget borders, once you start putting borders on columns and rows and such things get a little cluttered and the border patterns become more useful).

**Comment by Vultraz** [comment]
Could you say more? Were you imagining having alternating colors for overlapping lines?

**Comment by white-haired-uncle** [comment]
Yes, different patterns with different colors can help when borders overlap, such as in complex scenarios where you're looking at columns, rows and widgets, or even multiples of each.  I assume patterns would also help for those who can't see color.

I don't see why using FP for the coordinates would make any difference to the math, but if it's going to break anyway perhaps it's best just to think about it later?

**Pull request closed without merging**
