### PR TITLE
Upgrade special=* uses in master

### PR DESCRIPTION
**Pull request by newfrenchy83**
now what special is deprecated it must replace in master for resolve https://github.com/wesnoth/wesnoth/issues/3915

### CODE REVIEW

**Comment by jostephd** [comment]
Thanks for the PR! I haven't played these campaigns so could someone else review/merge please?

**Comment by newfrenchy83** [comment]
@sevu can you review this PR please?

**Comment by nemaara** [comment]
Merged.

**Comment by nemaara** [comment]
Sorry, I didn't realize this before when playtesting, but the special_id key doesn't actually work. It doesn't do anything at all in [filter_attack], so actually the specials get applied on all attacks. I had to revert the PR because of this, but I can add it back if/when special_id gets fixed.

**Pull request merged**
