### PR TITLE
New syntax for campaign difficulty.

### PR DESCRIPTION
**Pull request by Vultraz**
This replaces the current difficulties/difficulty_descriptions syntax with a new one using a [difficulty] tag with the following syntax

```
[difficulty]
    define=
    image=
    label=
    description=
    default=
[/difficulty]
```

The old syntax is still completely supported and is translated to the new syntax at runtime.

Note that the old format doesn't have a deprecation warning right now, since I'm not sure where best to display it.

### CODE REVIEW

**Comment by gfgtdf** [comment]
since difficulty_list_ and difficulty_opts_ are only used in the constructor they shouldn't be class ember variables.

**Comment by aginor** [comment]
There's compilation failures in Travis...

**Comment by gfgtdf** [comment]
difficulty_list_ and difficulty_opts_ still have teh underscore at the end of thir names which should only be used for class memeber variables.

**Comment by Vultraz** [comment]
Fixed @gfgtdf

**Comment by gfgtdf** [comment]
I see currently no reasons against merging

**Pull request merged**
