### PR TITLE
[TRoW][Units] Give Prince Haldric his resilient and healthy traits

### PR DESCRIPTION
**Pull request by knyghtmare**
Part of #7129

### CODE REVIEW

**Review by nemaara — APPROVED** [review]
Or hear me out, don't nerf his HP!! (Or nerf it a little less ha, up to you).

**Comment by knyghtmare** [comment]
> Or hear me out, don't nerf his HP!! (Or nerf it a little less ha, up to you).

Currently, the HP nerf is such that he is still

|Condition |  0 | 1 | 2 | 3 |
| -------- | ------| - | - | - |
| no traits | 24 | 36 | 48 | 64 |
| HP nerf | 19 | 29 | 39 | 53 | 
| with traits | 24 | 36 | 48 | 64 |

**Comment by stevecotton** [comment]
Although he's a unique unit, when I right-click on him and select "Unit Description", the stats in the encyclopedia no longer match the stats of the unit.

For a normal unit, we'd accept that because the trait system's mechanics are a necessary part of making the combat mechanics more interesting. Doing it for unique units is unnecessary, and I think this idea shouldn't be implemented.

**Comment by knyghtmare** [comment]
> Although he's a unique unit, when I right-click on him and select "Unit Description", the stats in the encyclopedia no longer match the stats of the unit.

Is this not the default case for every recruited unit with traits?

**Comment by stevecotton** [comment]
I already answered that in my second paragraph - we have to do it for recruited units, because it's a necessary cost of adding that diversity for non-unique units. That doesn't mean it's good to do it when we don't have to.

**Review by nemaara — CHANGES_REQUESTED** [review]
Okay stevecotton raised a good point. Haldric isn't a regular unit, he might not have AMLAs but since nobody else uses his unit we can treat him as a hero unit. Leaving this open because if you wanted to give him a dummy trait that adds some flavor you can do that.

**Pull request closed without merging**
