### PR TITLE
Build with C++20

### PR DESCRIPTION
**Pull request by Vultraz**
Given the CI failures, it looks like we won’t be able to use this for a while. Specifically, we need a newer version of clang (at least 16) due to https://github.com/llvm/llvm-project/issues/44178, which seems to be (if I’m not mistaken) the underlying issue causing the failures related to `views::reverse`. That requires a new docker image built off Ubuntu 24.04.

As for the Windows failures, I don’t know what to make of them. I don’t get the warnings about a recursive `config_attribute_value::operator==` implementation in VS 17.10, but I also do realize that my “updated” implementation in this PR is most likely actually wrong.

The macOS builds are equally baffling. While it seems possible that we might not need to bump the minimum deployment target, we definitely require a much newer version of XCode. Though even running on the `macos-latest` runner, we get weird errors about `wfl::variant` being an incomplete type.

The flatpak failure, I can’t figure out. We need to update to boost 1.74 (https://github.com/boostorg/bimap/commit/6fba6e5de3a5d9b0675a875fdac8aad9238d6dd8 is needed), but on doing `make` randomly decides to stop detecting asio, and with 1.85, to stop detecting system. No idea what’s going on.

Likewise, the GCC failure is somehow related to boost, but doesn’t seem affected by a boost version bump, and I can’t find any info on that particular failure.

TL’DR: The best we can do for now with regards to C++20 is conditional compilation. VS offers (and has offered) the best support thereof for a few years now (we could honestly use C++23 features if we were just targeting VS). I might look to enabling certain features on a per-compiler basis, but that’s a different project.

UPDATE 7/31: I've gotten everything building. We don't actually need to bump the MacOS target, but we do require a newer XCode version to actually build. That constitutes a requirement bump for devs (not for players), so for now C++20 features should be enabled by conditional compilation using the [standard feature test macros](https://en.cppreference.com/w/cpp/utility/feature_test). All existing C++20 code has already been updated to use those guards.

### CODE REVIEW

**Comment by Pentarctagon** [comment]
Do our minimum targeted versions support enough of C++20 for this to make sense?

**Comment by Vultraz** [comment]
That's what I'm trying to ascertain. Definitely not macOS, at least, but theoretical the other targets should be fine. If I can figure out why they're failing so much ._.

**Comment by CelticMinstrel** [comment]
I won't be able to contribute for probably quite awhile if this is merged. Just saying.

**Comment by CelticMinstrel** [comment]
> I won't be able to contribute for probably quite awhile if this is merged. Just saying.

I'm going to take this back, as I was able to pull this branch and build it. I already mentioned in IRC, but I'll repeat here so it doesn't get lost.

* If 1816ce4bd611d463b06956b5539e6a00ce9bd552 is reverted, it builds without issue in Xcode 12 on MacOS 10.15, though there are a couple of warnings that `[=, this]` is a C++20 extension.
* Even if 1816ce4bd611d463b06956b5539e6a00ce9bd552 is _not_ reverted, it still builds in Xcode 12 on MacOS 10.15 _if_ the language setting in the project file is changed to `c++2a`.

**Comment by Vultraz** [comment]
I have no idea why the CodeQL build is failing. It doesn't give any errors, and instead throws an error that the runner ran out of space. I tried adding a step to clear some space but it still didn't work.

**Comment by Vultraz** [comment]
Going to close this since it served its purpose. All the build issues with C++20 have been fixed, the lambda issue was addresses separately, and we have a dedicated CI build now. Any other build changes that need to be done can be done separately when the time comes.

**Pull request closed without merging**
