### PR TITLE
[1.16] Add support to replay 1.14 saves to BFW1.16

### PR DESCRIPTION
**Pull request by demario-w**
(version tagged as BFW1.16.load_1.14_replay_backward_support_UNITLESS-noSPDE.v4)

This supports loading the 1.14 saves from the "Show saves from different a version" without OOS.
See details in https://forums.wesnoth.org/viewtopic.php?p=669885#p669885

The patch is creating:
- the data/add-ons directory in mainline data
- a default-unitless-1.14 era
- no new unit type
- the events of the era are appended to the 1.14 saves to brings compatibility with 1.16 engine

The replays doesn't work on ladder and dunefolk saves.

### CODE REVIEW

**Comment by Pentarctagon** [comment]
It looks like the CI jobs are having some issues, so those would need to be fixed.  Also I'm very much opposed to shipping a `data/add-ons` directory - that's just asking for people to get confused where their own add-ons are supposed to go.

**Comment by cooljeanius** [comment]
> It looks like the CI jobs are having some issues, so those would need to be fixed. Also I'm very much opposed to shipping a `data/add-ons` directory - that's just asking for people to get confused where their own add-ons are supposed to go.

On Macs at least that would get hidden in the app bundle, thus reducing the likelihood of people getting confused by it

**Comment by Pentarctagon** [comment]
Windows and Linux do now however, and they (mostly Windows of course) would account for well over 90% of users.

**Comment by demario-w** [comment]
Need the help of someone knowledgeable on the macos/clang compilation chain to fix error in macos-arm-release CI job:

`Undefined symbols for architecture x86_64:
  "savegame::replay_start_config(config&)", referenced from:
      savegame::loadgame::append_era_event() in savegame.o
  "savegame::append_suffix_to_era_id(config&)", referenced from:
      savegame::loadgame::append_era_event() in savegame.o
  "savegame::convert_earlier_version_saves(config&)", referenced from:
      savegame::convert_old_saves(config&) in savegame.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **`

Need to pull the code from repository https://github.com/demario-w/wesnoth/tree/1.16 add the src/savegame_conversion.cpp and src/savegame_conversion.hpp compilation and object linking (to some project file, I believe!?) and push back the resulting configuration files to the repository.

**Comment by demario-w** [comment]
For the record, summary of the WML validation errors:

Invalid key 'set_cost=' in tag [modify_unit_type]
Invalid value '90 pierce=90 impact=30 fire=200 cold=120 arcane=150' in key 'blade=' in tag [resistance]
Invalid value 'Ancient Wose (1.14)' in key 'description=' in tag [effect]
Invalid value 'Armageddon Drake (1.14)' in key 'description=' in tag [effect]
Invalid value 'Banebow (1.14)' in key 'description=' in tag [effect]
Invalid value 'Bone Shooter (1.14)' in key 'description=' in tag [effect]
Invalid value 'Drake Burner (1.14)' in key 'description=' in tag [effect]
Invalid value 'Drake Flameheart (1.14)' in key 'description=' in tag [effect]
Invalid value 'Drake Flare (1.14)' in key 'description=' in tag [effect]
Invalid value 'Dwarvish Dragonguard (1.14)' in key 'description=' in tag [effect]
Invalid value 'Dwarvish Lord (1.14)' in key 'description=' in tag [effect]
Invalid value 'Dwarvish Pathfinder (1.14)' in key 'description=' in tag [effect]
Invalid value 'Dwarvish Sentinel (1.14)' in key 'description=' in tag [effect]
Invalid value 'Dwarvish Sentinel (1.14)' in key 'set_description=' in tag [effect]
Invalid value 'Dwarvish Stalwart (1.14)' in key 'description=' in tag [effect]
Invalid value 'Dwarvish Stalwart (1.14)' in key 'set_description=' in tag [effect]
Invalid value 'Dwarvish Steelclad (1.14)' in key 'description=' in tag [effect]
Invalid value 'Dwarvish Thunderguard (1.14)' in key 'description=' in tag [effect]
Invalid value 'Elder Wose (1.14)' in key 'description=' in tag [effect]
Invalid value 'Elvish Lady (1.14)' in key 'description=' in tag [effect]
Invalid value 'Elvish Shaman (1.14)' in key 'description=' in tag [effect]
Invalid value 'Elvish Shaman (1.14)' in key 'set_description=' in tag [effect]
Invalid value 'Fire Drake (1.14)' in key 'description=' in tag [effect]
Invalid value 'Giant Scorpion (1.14)' in key 'description=' in tag [effect]
Invalid value 'Giant Scorpling (1.14)' in key 'description=' in tag [effect]
Invalid value 'Heavy Infantryman (1.14)' in key 'description=' in tag [effect]
Invalid value 'Inferno Drake (1.14)' in key 'description=' in tag [effect]
Invalid value 'Iron Mauler (1.14)' in key 'description=' in tag [effect]
Invalid value 'Mermaid Diviner (1.14)' in key 'description=' in tag [effect]
Invalid value 'Mermaid Enchantress (1.14)' in key 'description=' in tag [effect]
Invalid value 'Mermaid Priestess (1.14)' in key 'description=' in tag [effect]
Invalid value 'Mermaid Siren (1.14)' in key 'description=' in tag [effect]
Invalid value 'Merman Hunter (1.14)' in key 'description=' in tag [effect]
Invalid value 'Merman Javelineer (1.14)' in key 'description=' in tag [effect]
Invalid value 'Merman Spearman (1.14)' in key 'description=' in tag [effect]
Invalid value 'Poacher (1.14)' in key 'description=' in tag [effect]
Invalid value 'Shock Trooper (1.14)' in key 'description=' in tag [effect]
Invalid value 'Troll Rocklobber (1.14)' in key 'description=' in tag [effect]
Invalid value 'Wose (1.14)' in key 'description=' in tag [effect]

**Comment by Pentarctagon** [comment]
For macOS, that's a limitation since it doesn't read the list of source files from the source_lists directory like Windows (cmake) and Linux (cmake, scons) do.

> Invalid key 'set_cost=' in tag [modify_unit_type]

This should be a valid attribute, so it looks like that needs to be added to the schema.

>  Invalid value '90 pierce=90 impact=30 fire=200 cold=120 arcane=150' in key 'blade=' in tag [resistance]

I'm not sure what to make of this one, but this looks like a valid issue related to newlines somehow. This one would need to be fixed.

>  Invalid value '<unit> (1.14)' in key 'description=' in tag [effect]

The logs say `expected value of type t_string` so a guess would be that the attribute needs to have the `_` translation mark after the equals sign and before the text.

**Comment by Pentarctagon** [comment]
Also, what is the plan for this functionality in terms of the eventual 1.18 release?

**Comment by demario-w** [comment]
> > Invalid key 'set_cost=' in tag [modify_unit_type]
> 
> This should be a valid attribute, so it looks like that needs to be added to the schema.
> 

Should that be fixed in this branch? Or is it dealt with directly in master branch?

**Comment by demario-w** [comment]
> Also, what is the plan for this functionality in terms of the eventual 1.18 release?

What do you mean? Replaying 1.14 in version 1.17 (just need to merge the code in master) or replaying 1.16 in version 1.17 (there is no break in compatibility now)?

**Comment by Pentarctagon** [comment]
> Should that be fixed in this branch? Or is it dealt with directly in master branch?

I would say it should be fixed here, since the WML schema validation can be a bit tricky sometimes and this way it can be tested that it's working.

> What do you mean? Replaying 1.14 in version 1.17 (just need to merge the code in master) or replaying 1.16 in version 1.17 (there is no break in compatibility now)?

Mainly I'm concerned about the ongoing maintenance burden. At a minimum it would be good to document, either in doxygen or on the wiki, what sort of changes need to be made to keep this up to date between major versions (1.16, 1.18, 1.20, etc), how to test for compatibility, and so on. Essentially: what do future developers need to know to consider if you're not around in a few years?

**Comment by demario-w** [comment]
> > Should that be fixed in this branch? Or is it dealt with directly in master branch?
> 
> I would say it should be fixed here, since the WML schema validation can be a bit tricky sometimes and this way it can be tested that it's working.

OK, if it is on me, I will handle how I think it is best.

**Comment by demario-w** [comment]
> Mainly I'm concerned about the ongoing maintenance burden. At a minimum it would be good to document, either in doxygen or on the wiki, what sort of changes need to be made to keep this up to date between major versions (1.16, 1.18, 1.20, etc), how to test for compatibility, and so on. Essentially: what do future developers need to know to consider if you're not around in a few years?

I understand your concerns. At this point, this is a mere request to pull the code into 1.16 branch. When 1.18 is out, the code will not be in, the feature will disappear and there is no maintenance work to do.

The likeliness to have such a old-replay-support code to be pushed to 1.18 is linked to the amount of compatibility breaking changes that are made in default era during the 1.17 cycle (based on how branches are managed now). Given the lack of knowledge on the plans, I can't make any estimation.

Generally speaking this code is **by essence** obsolete at each new version and that is why I don't propose to push it to master.

**Comment by Pentarctagon** [comment]
So this wouldn't be part of anything that would (eventually) allow 1.14 saves to be playable on 1.18?

**Comment by demario-w** [comment]
> So this wouldn't be part of anything that would (eventually) allow 1.14 saves to be playable on 1.18?

What I mean is this:
- this code makes 1.14 saves compatible the changes done in BFW1.16
- if BFW1.18 is compatible with 1.16 then this code can be used as is in 1.18 to replay 1.14 saves
- if BFW1.18 breaks compatibility with 1.16 then this code won't be able to load 1.14 saves in 1.18
- in this case **if some additional work is done** to be able to load 1.16 saves in BFW1.18 **following the way it is done in this code** for past-default-era support, **then this code can be recovered** to extend the compatibility to 1.14 saves with no trouble.
- there are some ways to break compatibility that can't be recovered afterwards without hacks that can't be used in mainline.
 
The concerns for compatibility has to be raised when changes are made to the engine, rng, replay data structure... that break compatibility.

**Comment by Pentarctagon** [comment]
Right, so I want it to be documented what specific things you tested for when you were implementing this, what issues you ran into, etc. Wesnoth simply doesn't have perfect documentation of when those things change, and developers might not even be aware that something they're doing will cause that as a side effect.

---

You'll need to add the schema changes for `[modify_unit_type]` here as well, so the CI doesn't fail on them. It also looks like wmlindent needs to be run given:
```
WML validation failed! (./utils/CI/schema_validation.sh)
Executing Whitespace and WML indentation check
make: Entering directory '/home/wesnoth-CI/data/tools'
wmlindent: ../../data/add-ons/Support_Past_Default_Era_Unitless/era-spde-unitless-1.14.cfg changed
wmlindent: ../../data/add-ons/Support_Past_Default_Era_Unitless/macros/changed_move_points-1.14.cfg changed
wmlindent: ../../data/add-ons/Support_Past_Default_Era_Unitless/macros/macros-unitless-1.14.cfg changed
wmlindent: ../../data/add-ons/Support_Past_Default_Era_Unitless/macros/rounding_trait-1.14.cfg changed
wmlindent: ../../data/add-ons/Support_Past_Default_Era_Unitless/macros/changed_hitpoints-1.14.cfg changed
wmlindent: ../../data/add-ons/Support_Past_Default_Era_Unitless/macros/changed_unit_cost-1.14.cfg changed
wmlindent: ../../data/add-ons/Support_Past_Default_Era_Unitless/macros/changed_damages-1.14.cfg changed
wmlindent: ../../data/add-ons/Support_Past_Default_Era_Unitless/macros/changed_resistances-1.14.cfg changed
wmlindent: ../../data/add-ons/Support_Past_Default_Era_Unitless/macros/unit_changes-1.14.cfg changed
```

Additionally, my previous statement about a `data/add-ons` directory still applies. To fit into the existing mainline structure, the [era] should go into `data/multiplayer/eras.cfg` and the events into a modification that is set to be required by that era.

**Pull request closed without merging**
