### PR TITLE
fix other_attack conditional generate bug in abilities used like specials

### PR DESCRIPTION
**Pull request by newfrenchy83**
resolve https://github.com/wesnoth/wesnoth/issues/4718. if other_attack condition for adding of abilitie applied to opponent then abilitie function what for attack to same range what owned by owner of abilitie and weapon like abilities must be applied to all attack matched

### CODE REVIEW

**Comment by newfrenchy83** [comment]
@gfgtdf could you review this corestion of bug lease?

**Comment by newfrenchy83** [comment]
@Vultraz could you review this PR please?

**Comment by Vultraz** [comment]
Did you test this? This bit of code isn't really my area.

**Comment by newfrenchy83** [comment]
yes, i did, when i test fix, the enemy unit of formation units have both melee and ranged attack affected, like it must be, then what with other_attack, it was like if cth fomation was implemented in [specials] instead of [abilities]

**Comment by gfgtdf** [comment]
Right now this looks good, but I'm on my phone and cannot review very well

**Comment by newfrenchy83** [comment]
@gfgtdf have you review this PR what thos bug was fixed before pre 1.16 string ?

**Comment by gfgtdf** [comment]
im not aware of any plans for a 1.16 string frreze. And i f even if there it would be this pr could be merged regardless

**Pull request merged**
