### PR TITLE
HttT S12 Snow falls at a constant pace

### PR DESCRIPTION
**Pull request by OrekOrek**
Currently, snowfall is not at a constant pace as intended.
707 hexes of 10 terrain types (Gs,Gd,Co,Ko,Gll^Fp,Gll^Fmw,Gll^Fdw,Gd^Vo,Gd^Vc,Hhd^Vo) are converted to snowy terrains. Therefore, on challenging difficulty with 28 turn limit (=27 snowfall turns), it should be (26 hexes converted*22 turns) + (27 hexes converted*5 turns)=707 hexes. However, according to my experiments, 21~30 hexes are randomly converted. Removing Re and Rb from filtered locations should solve this problem.

Line 227 (original):
Re, Rb are dirt, and these hexes are not converted to snowy terrain. However, by having them within [filter_location], the snowfall pace fluctuates. Also, Hhd^Vc doesn't exist on this map.

Line 258~269 (original):
Coa and Hhd are not filtered.

Line306~311 (original)
Hhd^Vc doesn't exist on this map.

These changes make snow fall at a constant pace. Also, unnecessary codes are deleted.

### CODE REVIEW

**Comment by OrekOrek** [comment]
I don't have a particular opinion about what terrain should be covered by snow.
Currently, dirt roads are not covered, so I kept it the same way because balance change or suggesting a new feature is not the goal.
The main intention of this PR is making snowfall constant because the comment in the code states so but the actual program fails to achieve it.

If people agree to implement more comprehensive changes to the snowfall mechanism, I don't mind that this PR is overridden.

**Comment by soliton-** [comment]
This looks like a perfectly fine bugfix+cleanup. I don't see why behavior changes need to be considered here.

IMO this should just be committed. If someone wants behavior changes that can be done in a separate PR.

**Comment by stevecotton** [comment]
Okay, that makes sense.

**Comment by soliton-** [comment]
Actually one thing that could be considered is to also remove this fallback:

https://github.com/wesnoth/wesnoth/blob/395f93d06101d986627e185dedb29032f1b82b84/data/campaigns/Heir_To_The_Throne/scenarios/12_Northern_Winter.cfg#L312-L315

To me it seems that is either useless since without it nothing would happen just the same or worse it hides an error that would have told us earlier that some terrains are filtered for but not actually handled. (Would be cool if someone can check. From reading the code it seems to me that it should produce an error when trying to replace the terrain with an empty terrain code.)

**Comment by OrekOrek** [comment]
The fallback seems to prevent a filtered terrain with an empty terrain code from using another terrain’s code.
For example, When Rb (dirt) is within [filter_location] but without [case], it can be converted to Aa^Voa because of
```
                        [case]
                            value=Gd^Vo

                            {VARIABLE terrain Aa^Voa}
                        [/case]
```
though this [case] is supposed to work only for Gd^Vo. (see picture)
This happens without an error message.

Snowfall-Test

Therefore, it is okay to remove the fallback for now because all filtered terrains have the codes for terrain replacements when this PR is committed. However, just in case future map/code changes are not perfect, and a terrain is accidentally added to the filtered locations etc., the fallback can stay.
I would like more experienced people here to decide how to handle it.

**Comment by soliton-** [comment]
Ah ok, since the terrain variable is only cleared in the end. Could you check again with moving `{CLEAR_VARIABLE terrain}` to the end of `[command]`?

**Comment by OrekOrek** [comment]
Moving `{CLEAR_VARIABLE terrain}` inside `[command]` and removing the fallback as described below seem to cause no problem in 1.17.24.
```
                        [case]
                            value=Hhd^Vo

                            {VARIABLE terrain Ha^Voa }
                        [/case]
                    [/switch]

                    [terrain]
                        x,y=$loc.x,$loc.y
                        terrain=$terrain
                    [/terrain]

                    {CLEAR_VARIABLE terrain}
                [/command]
            [/random_placement]
        [/event]
    [/event]
```
I have tested this version also with unwanted Rb (dirt) etc. in ` [filter_location] `, but the only problem is the inconstant snowfall pace, which has existed even with the fallback anyways.
Therefore, I believe that this version works fine even after the potential map/code changes in the future. 

I am so new to GitHub, and I couldn't figure out how to update the code (or send a cfg file?) here.
May I ask how? Then, I will update to the version that actually worked. Thank you.

**Comment by soliton-** [comment]
> I have tested this version also with unwanted Rb (dirt) etc. in `[filter_location]`, but the only problem is the inconstant snowfall pace, which has existed even with the fallback anyways.

Ok, thanks. I guess it doesn’t matter much what we do with the fallback then.

> I am so new to GitHub, and I couldn't figure out how to update the code (or send a cfg file?) here. May I ask how? Then, I will update to the version that actually worked. Thank you.

This pull request comes from the master branch of your fork so you can update it by adding another commit to that branch.

**Comment by OrekOrek** [comment]
Ok. This should be it. Thank you for your support and guidance.

**Pull request merged**
