### PR TITLE
[UtBS] - New Quenoth sprites

### PR DESCRIPTION
**Pull request by doofus-01**
Initial commit for quenoth fighter-line sprites.  Level 1 & 2 only, so far.  They might be a bit too small at the moment.

### CODE REVIEW

**Comment by Vultraz** [comment]
Hmmm... I think perhaps you should keep the LVL1, since Jetrel drew that one. The lvl 2 and 3 weren't redone, however.

**Comment by doofus-01** [comment]
Hrm, it doesn't mesh with the portraits really (though they still are WIP).  Maybe it is set in stone, maybe not, let's see what Jetrel says.

**Comment by Rayyann4206** [comment]
I can' understand what is all this.

**Comment by doofus-01** [comment]
What an odd comment, is Ray*&#*42@6 a spambot?

Anyhow, I've included the antelope riders now, this will be a sprite/portrait alignment PR, not just the fighters.  I won't put animations in here, the scope is just to get base sprites agreed upon.  The previously commited antelope rider sprites have a bit too much bling; they are not very true to the spirit of the story, and don't align well with LordBob's plans.  I'll include a link when he publicly posts his work.

**Comment by rkettering** [comment]
Looks good to me as well.

**Comment by doofus-01** [comment]
Thanks.  I'll work on some basic animations in another PR.  I'll try to tweak the flanker/ranger to look less goblin-like.

**Pull request merged**
