### PR TITLE
network_download_file: replace spaces with tabs

### PR DESCRIPTION
**Pull request by babaissarkar**

### CODE REVIEW

**Comment by gfgtdf** [comment]
most of our c++ codebase uses tabs, is there a reason why this file uses spaces?

**Comment by CelticMinstrel** [comment]
I don't quite understand what you're asking. The good change was made, wasn't it?

**Comment by CelticMinstrel** [comment]
> I don't quite understand what you're asking. The good suggested change was made, wasn't it?

**Comment by stevecotton** [comment]
Ah, missed that the change was already made.

**Pull request merged**
