### PR TITLE
Display: use point math for viewport position

### PR DESCRIPTION
**Pull request by Vultraz**

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
What the heck is "point math"? I don't see anything here that I would describe as such, in any case…

**Comment by Wedge009** [comment]
Without context, I thought it might have been referring to floating-point arithmetic. But it looks like replacing pairs of integers with the `point` class. Which I think is a sensible thing to do.

**Comment by Vultraz** [comment]
Yes, I meant using the math operations defined for the point class.

**Comment by CelticMinstrel** [comment]
What "math operations defined for the point class"? From what I can tell you've used no such thing here. All the math is on either x or y of a given point, not on the point itself.

**Comment by Vultraz** [comment]
Adding/subtracting two points, for example.

**Pull request merged**
