### PR TITLE
Spelling Corrections

### PR DESCRIPTION
**Pull request by Wedge009**

### CODE REVIEW

**Comment by Vultraz** [comment]
A period isn't incorrect for the rhetorical question, and I think it sounds better than a question mark. Other than that, good to go.

**Comment by CelticMinstrel** [comment]
Punctuation for rhetorical questions... I dunno. I think either way works just fine. An ellipsis could also be appropriate.

**Comment by Wedge009** [comment]
The thing is that everywhere else the 'who knows' expression is used in UtBS, the sentence ends with a question mark. So while I was also thinking that this could go either way, for the sake of consistency the question mark makes more sense to me.

I had a look around and the consensus seems to be... that there's no real consensus. Some sources say to use question marks, others say that the informality of the construct can allow for either question mark or a full stop. What do you think? If you're really against it, I'll revert the question mark but at the moment I'm leaning towards consistency across the campaign.

**Comment by CelticMinstrel** [comment]
To some extent I think it depends on the tone you want to convey. Sometimes, a rhetorical question has normal question intonation (rising towards the end), and in that case, it's probably best to include the question mark. Sometimes, a rhetorical question has normal sentence intonation (falling towards the end), in which case it makes a lot of sense to just use a normal period. And sometimes, a rhetorical question might have a trailing-off intonation, in which case an ellipsis would be most appropriate.

If you're not going for the trailing-off intonation though, I think there's sufficient leeway to just pick the one you like best.

**Comment by Wedge009** [comment]
Some Australians have a bad habit of inflecting the ends of all their sentences as though they were asking questions. XD

That aside, and not knowing the intention of the author, I've decided to leave the rhetorical question as-is (ending in a full stop) to accommodate the feedback given. I presume there are no further objections, so please (to anyone with push access) go ahead and merge this at your convenience.

**Comment by CelticMinstrel** [comment]
Is that really a bad habit or is it more of a dialectical trait?

**Comment by Wedge009** [comment]
I would say it's a bad habit, but for some it's probably reached the point of 'critical mass' that it could be called a dialectical trait. But I do emphasise that it's some - not all - Australians who exhibit this. I notice it's more common in younger (say, school-aged - that's primary/secondary school, not university-aged) folks, perhaps those of a less-educated background. Which is definitely not a slight against those who happen to be less-educated - it's simply an observation I make with regards to this specific style of intonation.

But we're digressing and the PR has been merged (thanks for that). I think I had better stop here. (:

**Pull request merged**
