### PR TITLE
Many new features in the formula engine

### PR DESCRIPTION
**Pull request by CelticMinstrel**
This adds several new features to the [Wesnoth Formula Language](https://wiki.wesnoth.org/Wesnoth_Formula_Language) and engine. See the link for a fairly detailed coverage of the state of the language prior to this PR.

This is not entirely finished, but I'd like to hear feedback on the general content of the PR. There are a couple of things that I'm uncertain of - for example, is the hypot() function really worthwhile? (Especially since it's limited to two arguments.) Does string interpolation really need to support entire subformulas? (The main use-case I can think of for this is conditional interpolation.) On the other hand, I'd also be open to ideas of other things to add.

- The formula engine had an undocumented syntax which allowed arbitrary formulas to be interpolated into strings - `'some string with {interpolated_formula}'`. Since the `{}` causes problems with the WML preprocessor, I've changed this to use `[]` instead. In addition, the same syntax is now used for three escape sequences - `[']` expands to a single quote, `[]` expands to an open bracket, and `[.]` expands to a close bracket. (See the commit for some alternative escape syntaxes if you think this sounds weird - I may change it.)
- Four new operators have been added. The `..` operator performs string or list concatenation (there was already an undocumented function for string concatenation, but I didn't know about it when I added the operator, and I think the operator is more convenient anyway). The `~` operator creates a range - a list of consecutive numbers. The `xor` operator does exactly what it says, but can also be thought of as a boolean `!=`. Similarly, the `xnor` operator can be thought of as a boolean `=`.
- In order to emphasize that the Wesnoth Formula Language and FormulaAI are two different things, I've changed the `fai` and `faiend` keywords to `wfl` and `wflend`. (The old keywords are still silently supported.)
- Lists can now be indexed by a list. This functions as a "select" mechanism, returning a list containing only those elements of the list whose index is listed in the indexing list. In other words, `[1,2,3,4,5][ [1,3] ]` returns `[2,4]`. I'm not sure how useful this is in the general case, but in conjunction with the range operator it allows for list slicing - eg `[1,2,3,4,5,6][2~4]` returns `[3,4]`.
- New math functions: tan(), asin(), acos(), atan(), sqrt(), cbrt(), root(), log(), exp(), hypot(), pi() - all return null in the event of a NaN error
- New string functions: reverse(), find_string(), replace()
- New list functions: tail(), union(), intersection(), set_diff(), symmetric_diff(), zip() - the four set operations also work on maps
- New higher-order functions: take_while()
- Changes to existing functions: head() takes optional size argument; reduce() takes an optional initial accumulator; substring() function allows negative size to count backwards from offset
- The dice operator now uses the synced RNG whenever possible. I haven't tested that this truly eliminates out-of-sync errors, though.
- Decimals can now implicitly convert to integers, though in practice this will probably rarely happen since most things that accept both have special cases for each.
- abs() and the modulus operator now work on decimal values
- Logical `and` and `or` operators now short-circuit
- Function definitions can now be used outside of FormulaAI code.

Some functions that I considered but rejected are:
- replicate - can now be implemented as `def replicate(val, times) reduce(map(1~times, val), a .. b)`
- replace_string taking a string to replace rather than a range - can now be impleneted as `def replace_string(str, key, repl) if(contains_string(str, key), replace(str, find_string(str, key), repl), str)`
- scalar multiplication and division (multiplying a list by a number) - can be implemented as `def scalar_mult(V, n) map(V, self * n)` and `def scalar_div(V, n) map(V, self / n)`
- vector magnitude - can be defined as `def norm(L) sqrt(sum(map(L, self ^ 2)))`
- vector dot product - can be defined as `def dot_prod(u, v) sum(map(zip(u, v), reduce(self, 1, a * b)))`
- vector cross product - of extremely limited use in a game in 2D space, and could probably be defined if really needed
- cartesian product - limited use, inefficient
- power set - limited use, inefficient
- reverse acting on lists - may still add this, not sure
- contains (test if an element is in a list) - can be implemented as `def contains(L, key) if(find(L, self = key) = null(), 0, 1)`
- foreach - identical to map, except ignoring the return value

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Changed escape syntax for square brackets to `[(]` and `[)]` based on feedback from @gfgtdf .

**Comment by CelticMinstrel** [comment]
Draft changelog entry: 8d80697821c9ce002c54de8c80e69875f2824423

**Comment by CelticMinstrel** [comment]
New draft of changelog entry: 139978a8d62f06c28dbebd03dc4340c49fe86a70

**Comment by Vultraz** [comment]
I was just speaking to @rkettering (Jetrel), and apparently, Wesnoth's formula language has its roots in the same place Frogatto/Anura's formula engine did. However, as @shikadilord puts it:

> Frogatto's formula language evolved in a completely different direction than Wesnoth's. The former became a solid framework of its own, the latter was doomed to be an accessory for GUI2 and FAI.

Still, it might be of some use to look at their language for some inspiration for improvements on our own. We might even consider it as a replacement for WML in some places, but that's a bit presumptuous for now, or at least move it out of its restrictive arithmetic niche.

**Comment by CelticMinstrel** [comment]
Honestly, considering all it can do, it's hard to think of it as fitting into a "restrictive arithmetic niche" right now. It sees little use outside of unit filters and simple arithmatic in `$(...)`, sure, but it's capable of quite a bit more even before this PR.

**Comment by gfgtdf** [comment]
As iceiceice said the irc, i think we should rather try to remove formula from wesnoth, and this pr seems to work into the opposite direction, even though it doesnt really prevent us from removing formula.

Formula is currently only used in a very few cases:

1) The $(..) syntax in variable substitution, this can easily be replaced doing a lua evalulation, in most cases where it does simple stuff like $($var1 + $var2) this will work just as before and more complicated cases can also be ported to lua without too much work.

2) formula= in filters, replacing this with lua isn't as easy as the one above, but its still possible if we make lua_function= a little more powerful (adding [args] ) which is a good idea anyway.

3) The gui2 internals. Mostlikeley the harest part. The advantage here is that formula in gui is almost exclusiveley used by widgets definition which are never in umc content, so we don't have to worry about compability here at all. I think that this can also be changed to use lua instead.

**Comment by CelticMinstrel** [comment]
You forgot FormulaAI, which is still used in at least one place in mainline and probably used in UMC too.

1) I recall you arguing that the problem with formula in $(...) was at least partly because it gave poorer error messages, but I haven't found the error messages to be all that bad, and many formula errors in $(...) stem from WML variables that don't exist. Changing $(...) to use Lua won't make those errors any better, since the nonexistent variables have already been replaced by empty space by the time the parser sees the formula.

2) I think formula= in filters can often be simpler and cleaner than Lua code, partly because it's implicitly "in the scope of the unit". I've also been working on improving lua_function= (as you know), but formula= is already there, already works, and can do nearly anything that lua_function= can do.

3) I think changing GUI2 internals to use Lua could be a lot harder than it sounds. For starters, there may not be a Lua kernel available when a dialog is shown. In any case, the use of formula works perfectly fine, so why break it by ripping out formula and replacing it with Lua? Porting from WFL's functional paradigm to Lua's procedural paradigm is probably not _hard_ exactly, but I also don't think it's as simple as you might think.

4) The formula language is a completely different paradigm from Lua. I think it's nice that authors can, to some extent, choose between a functional and procedural approach to things. (Unlike some people, I don't think it's bad to have multiple ways of doing things.)

The formula language already exists in Wesnoth. It's not broken - it works perfectly fine in the majority of cases. Removing it would, in my opinion, be more work than it's worth, and I don't think its presence detracts from the engine in any way. In fact, I kind of like the language, and it has been interesting discovering all its little quirks, too. It does have a few bugs, which this PR attempts to fix. This PR also adds a few more features. I believe it's not inferior to Lua - only different.

I have a number of additional features to push to this branch as well, for example allowing Lua to call formula code (this could be useful for people implementing custom WML tags intended to be used by others, or possibly even in mainline WML tags). You can see some of these in my lua_formula_bridge_wip branch.

**Comment by Vultraz** [comment]
I don't know about removing the formula engine. For one, it would simplify
syntax by reducing the numbers of languages we support. However, as celmin
mentioned, it could be complicated and more trouble than its worth.

Right now, though, I don't think there's any significant benefit of the
formula language over our Lua or WML. Anura transition its use of it into a
full-fledged scripting and data set language, but I don't think that's the
way we're going, are we?

**Comment by CelticMinstrel** [comment]
**vultraz wrote:**
> Anura transition its use of it into a full-fledged scripting and data set language, but I don't think that's the way we're going, are we?

At the moment, WFL works well for general expression evaluation on top of the WML engine, using the $(...) formula substitution syntax. Barring a few weird attribute names (based on the C++ rather than the WML), I believe it also works pretty well for unit filters. I think it would be great to add it to side and location filters as well, though I'm uncertain if it would be as useful there as it is in unit filters.

I think it would not be overly difficult to allow WFL for general-purpose scripting, if we wanted to (just add a "formula=" key to events that supercedes ActionWML, or alternatively a WML tag that executes a formula; both would work similarly to FormulaAI in that the formula would return an action to be executed), but you're right, we don't really seem to be headed that way at the moment, and mattsc at least is leaning in the opposite direction with the talk of removing FormulaAI.

We're definitely not moving towards using WFL for data definition. I don't think it's possible to completely replace WML in that realm, anyway, though I think it would be great if GUI2-style formulas (where you need to start with a parenthesis for it to be parsed as a formula rather than a literal value) were accepted in more places (I don't have any specific ideas at this time though). I already used them for movetype patching, and I'm sure there are other places where they might be useful (perhaps the animation engine? though that might get in the way of the progressive syntax).

**Comment by gfgtdf** [comment]
>  recall you arguing that the problem with formula in $(...) was at least partly because it gave poorer error messages

hmm yes that's what iceiceice said. I personally don't remember the last time i got formula error message so i cannot tell. But even thought the ``$($a + $b)`` syntax will still work when $(..) uses lua you can then also use ``$(V.a + V.b)`` if you did a ``V = set_wml_varmetatable {}`` in preload (like its suggested on the wiki) which will sureley give better error messages.

> For starters, there may not be a Lua kernel available when a dialog is shown.

Well, we always have the application lua kernel, alterntiveley a 'one kernel per dialog' approach is also ok if creating a lua kernel is a fast operation.

> 4) ...

Hmm but note that when you are using those things its doesn't only mean that you have to know all those things it also means that everyone who wants to understand you codes for example to use them in their addon have to understand your code.

Also this is a maintance issue on he c++ side, and i'm quite sure that most people that add new features will not bother adding a formula interface for them.

About formula beeing inferiror, i'm quite sure that there a are a quite some features that can be used form lua but not from formula, for example if $(..) used lua you could easily do things like:

``{VARIALBE unit.hitpoints = $(math.max($unit.hitpoints - wesnoth.game_config.poison_amount, 1))}``
``{VARIALBE map_data "$(wesnoth.read_file('maps/my_map'))"}``

> ...

Well, the main advantage is not that lua is in all aspects better than formula, its more like its not having to learn another language for those (corner) cases. This doesn't only mean the general language syntax but also tht you have to relearn the names and interfaces of all thoes functions like heelper.disance_between, wesnoth.find_path, wesnoth.read_file etc for each language then.

>  I think formula= in filters can often be simpler and cleaner than Lua code, partly because it's implicitly "in the scope of the unit"

Well its true that formula can so some things with less code than the equivalent lua but i don't think its worth the work from learnign another language (see above).
For example look at the formula
``size(filter(attacks, range = 'ranged' and size(filter(special, self = 'first strike')) > 0 )) > 0``,
it checks whether the unit has at least one ranged attack with a firsttrike special. The is a typical example where formula is good at and can be used as-is in [filter] formula=. The corresponding lua code like this
``#helper.filter(u.attacks, function(a) return a.type == 'ranged' and helper.get_child(a.specials, 'firststrike') ~= nil end) > 0``
assuming that 'helper' was set and that we add helper.filter . The main (only) difference here is that in the forula code you can just put an expression in filter while in the lua code you have to wrap the expression in a 'function(u) return...  ...end'.


> Anura transition its use of it into a full-fledged scripting and data set language, but I don't think that's the way we're going, are we?

Hmm i don't think this is possible without modifying a huge part of the wesnoth code (everthing that uses config class) and breaking most addons.

**Comment by CelticMinstrel** [comment]
> But even thought the ``$($a + $b)`` syntax will still work when $(..) uses lua you can then also use ``$(V.a + V.b)`` if you did a ``V = set_wml_varmetatable {}`` in preload (like its suggested on the wiki) which will sureley give better error messages.

This can be done in the formula engine too, with a bit of work. Not by an end-user, but by changes to the C++ code... though admittedly I have not yet evaluated the difficulty of this.

>About formula beeing inferiror, i'm quite sure that there a are a quite some features that can be used form lua but not from formula, for example if $(..) used lua you could easily do things like:
>
>``{VARIALBE unit.hitpoints = $(math.max($unit.hitpoints - wesnoth.game_config.poison_amount, 1))}``
>``{VARIALBE map_data "$(wesnoth.read_file('maps/my_map'))"}``

The formula language already has a `max()` function, and it wouldn't be hard to allow it to access the game_config or read files. The only reason formula can't do these things is that it has been neglected; adding the capabilities to it is not especially difficult in most cases. Mind you, there _are_ things Lua can do that formula can't - WFL cannot change gamestate in any way, but Lua can. (As I understand it, even FormulaAI doesn't change the gamestate directly; instead, it returns instructions on how to change the gamestate.) This, however, is not really a problem in my opinion.

If you don't have argument against the specific contents of this PR (rather than arguments for removing formula altogether), I'd like to merge this soon. I think the fact that removing formula would alienate some content creators (eg shadowm), combined with the challenge of doing so without breaking anything, is sufficient reason to dismiss the idea of removing it.

**Comment by gfgtdf** [comment]
> The formula language already has a max() function, and it wouldn't be hard to allow it to access the game_config or read files

Yes, that example was obviosuly for the game config values not for the max function. Even if you add those 2 specific functions to formula i'm quite sure that there'll be other ones (not counting gamestate changing functions).

> If you don't have argument against the specific contents of this PR

No i don't, i just thought this woudl be a good place to discuss the forula removal.

**Comment by CelticMinstrel** [comment]
> Yes, that example was obviosuly for the game config values not for the max function. Even if you add those 2 specific functions to formula i'm quite sure that there'll be other ones (not counting gamestate changing functions).

Well, regarding game_config, I'd prefer to add it as variables rather than a function; then everything in game_config would be accessible. Other things that could be made accessible include WML variables and the turn count.

I guess my main point is that yes, formula currently has some drawbacks; however, addressing these drawbacks directly is easier than outright removing it.

**Pull request merged**
