### PR TITLE
wmlxgettext: added support for _ << translatable string >> on WML

### PR DESCRIPTION
**Pull request by AncientLich**
This commit contains also some changes in comments made by aquileia.

### CODE REVIEW

**Comment by loonycyborg** [comment]
This makes pot-update fail: https://gist.github.com/loonycyborg/fc23bd4d7fd3440828f4e3c800f4229c

**Comment by AncientLich** [comment]
Wow... I would never think this could ever actually happen... luckly I added this error message for code safety... now I will try to investigate the problem. In this moment I can only explain what has tecnically happened.

Scenario: this error is generated by pywmlx/state/wml_states.py, class WmlStr02, function run.
The regexp defined in in the __init__ of the WmlStr02 class is the regexp wich will capture all translatable string with the syntax _ << translatable string>>. 
The regex treat two different cases with an or:
_ << text >>     or   _ << text (if any) without the final  >> marker (first line of multiline translatable string).

So, in the regexp you could have group1 or group2 for capturing text.
The error you noticed is generated when the regexp defined in __init__() matches (function run() reached) but neither group(1) nor group(2) were found, wich should never happen according to the regexp (and actually during my tests never happened).

I will try to figure why the problem happens and to figure where the bug could be hidden. Thank for reporting the problem

**Comment by CelticMinstrel** [comment]
My first thought from your description would be an empty string `_ <<>>`, but I doubt that would be present anywhere in Wesnoth's files, and it wouldn't be a problem anyway if the groups use `*` rather than `+`. Without knowing what the regex is I can't say more.

Regarding how to update the PR, if you add more commits to the master branch and `git push`, the PR will automatically be updated. If you need to delete commits from the PR (for example to replace the existing commit with a fixed version of it), you'll need to `git push --force`.

**Comment by AncientLich** [comment]
Now the error should be fixed. Let me know if you discover any other bug.

**Pull request merged**
