### PR TITLE
Add underlying type of the terrain to Lua, re #4227

### PR DESCRIPTION
**Pull request by ProditorMagnus**

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Need to update the emmylua files too

**Comment by ProditorMagnus** [comment]
I doubt emmylua helps it compile.

**Comment by ProditorMagnus** [comment]
I found typedef std::vector<terrain_code> ter_list;

**Comment by CelticMinstrel** [comment]
> I doubt emmylua helps it compile.

It does not, but it still needs to be done. :)

**Comment by ProditorMagnus** [comment]
```
 	struct terrain_code {
		terrain_code(const std::string& b, const std::string& o);
		explicit terrain_code(const std::string& b, ter_layer o = NO_LAYER);
		terrain_code(ter_layer b, ter_layer o) : base(b), overlay(o) {}
		terrain_code() : base(0), overlay(NO_LAYER) {}

		ter_layer base;
		ter_layer overlay;
	};
```
This looks like string of base and overlay, which does not tell about terrain group.

**Comment by ProditorMagnus** [comment]
Aim is to have access to swamp_water,flat kind of identifiers.

**Comment by stevecotton** [comment]
What you're looking for is the `terrain_type_data::basic_movetypes()` function from https://github.com/stevecotton/wesnoth/pull/new/terrain_refactor - but that isn't ready for a PR yet, and there's a lot of `todo` comments in it.

I don't expect to have time to do that refactor soon, but you're welcome to cherry-pick stuff from it.

**Comment by ProditorMagnus** [comment]
I will add next reminder for january then.

**Comment by ProditorMagnus** [comment]
@stevecotton I got my reminder. Any update for this topic?

**Pull request closed without merging**
