### PR TITLE
WML: Add additional members to [store_side] results

### PR DESCRIPTION
**Pull request by sigurdfdragon**
Most were only possible to add since 1.13.5

Not sure if 'lost' should be here.

I still need to add a changelog entry

### CODE REVIEW

**Comment by gfgtdf** [comment]
Hmm i don't remember why the is 'lost' thing was added in the first place, what it actually does is removing a side form carryover when it was defeated. but note that:

1) Ai sides usually have already persistent=no in their [side] definition

2) When a human side looses this usuualy means that the campaoign ends and that there will be no carryover going on anyway.

So it might be some (possibly multiplayer related) corner case where this is important.

**Comment by sigurdfdragon** [comment]
ok, given that, is there any reason not to just store the whole side.__cfg as below, with maybe an addition to knockout the [ai] tag? (such a case would match what is displayed for the side in the Gamestate Inspector)




``
local container = t.__cfg

utils.vwriter.write(writer, container)
``

**Comment by CelticMinstrel** [comment]
Well, there could be things that exist in `t` but not in `t.__cfg`. I recall adding a few such things which are calculated on the fly. (I don't remember if that was in master or a branch, though.)

(By the way, it's three backticks to delimit code blocks, not two. You can also add a language on the same line as the opening backticks, in this case lua.)

**Comment by CelticMinstrel** [comment]
So, just to be sure, I assume all those individual keys that were specifically accessed before also exist in `t.__cfg`?

**Comment by sigurdfdragon** [comment]
Double-checked and added back two keys that aren't handled correctly by .__cfg

**Comment by CelticMinstrel** [comment]
By the way, IIRC the wml_tag_porting branch added some new side proxy members, some of which may need special handling added here.

**Pull request merged**
