### PR TITLE
Dunefolk race description

### PR DESCRIPTION
**Pull request by Pentarctagon**
This removes the deprecated Khalifate compatibility code, and adds the race description from the forum.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Wow, that's hard to read on the phone.

One correction: "fall prey _to_ trolls", rather than of trolls.

I'd also say "the world" rather that Irdya, since as far as I know there isn't any precedent for using that name I descriptive text.

**Comment by Vultraz** [comment]
Well, here's a chance to set precedent! :P I think we should keep mentions of Irdya.

**Comment by Pentarctagon** [comment]
I've changed it to "to trolls".  Unless there's any need for for the generic-ness of "world" though, I think "Irdya" is fine.

**Comment by CelticMinstrel** [comment]
I disagree on "the world" being too generic. I also don't see any reason to set a precedent, but if the consensus is to start using the name "Irdya" in the in-game documentation, I think I'd prefer to go all-out and use it all over the place. Which in my opinion would be a separate pull request.

**Comment by Pentarctagon** [comment]
I'll leave it up to @Vultraz to decide then.

**Comment by Vultraz** [comment]
Where else would it be used?

**Comment by Pentarctagon** [comment]
Updated based on the further feedback.

**Pull request merged**
