### PR TITLE
SP campaigns: rename beginner difficulty level

### PR DESCRIPTION
**Pull request by nemaara**
As the title says. We have enough campaign difficulties and as @Dalas121 rightly pointed out, I doubt players are going to want to stoop to a difficulty level they deem as "beginner". Having Easy/Normal take the place of the older lower difficulty levels will probably make people feel better about themselves.

### CODE REVIEW

**Comment by stevecotton** [comment]
It would be more accurate to say "rename" rather than "remove".

What do the difficulty names mean now? I thought that, for example, "Challenging" was intended to be require around the same skill level for all campaigns that had a level called "Challenging", but this contradicts that.

**Comment by soliton-** [comment]
Quite confusing to say remove when you mean rename.

**Comment by stevecotton** [comment]
> as @Dalas121 rightly pointed out

Is there a link to that discussion? I can't find it in Discord or the forums, and this feels like a change that people will look at in a few years time and want to know more about the reasoning.

**Comment by nemaara** [comment]
> It would be more accurate to say "rename" rather than "remove".
> 
> What do the difficulty names mean now? I thought that, for example, "Challenging" was intended to be require around the same skill level for all campaigns that had a level called "Challenging", but this contradicts that.

It's been pointed out to me many times that this isn't entirely true even as it stands right now. The goal would be to make it like that though.


> > as @Dalas121 rightly pointed out
> 
> Is there a link to that discussion? I can't find it in Discord or the forums, and this feels like a change that people will look at in a few years time and want to know more about the reasoning.

Not much of a discussion. I talked with him briefly on it in a DM on Discord and the point is that he and I both think people aren't going to want to stoop to playing a difficulty level entitled "beginner" simply out of ego. Plus, only two campaigns use the "beginner" difficulty anyway, so I think it's better to simplify how many difficulty levels we have.

**Comment by CelticMinstrel** [comment]
I agree that the title should say "rename" rather than "remove".

**Comment by Jonathan-Kelly** [comment]
Did you do any play testing of current WoF before renaming its difficulty settings?

Its "Easy" setting really is easy, with players usually getting a two fold gold advantage over their AI opponent(s). On its "Normal" players are generally on an equal footing against the AI in terms of gold. These first two settings are already carefully mimicking the "Easy" and "Normal" of most other current mainline campaigns, especially if you consider players cannot 'soft' lose future scenarios by mismanaging carryover or recalls and there are no real turn limits to worry about.

On its "Hard" setting the AI opponent(s) generally have a two fold gold advantage over players and on "Nightmare" it is four fold. So as with EI the difficulty ramp up is not small or linear.

>> "Challenging" was intended to be require around the same skill level for all campaigns that had a level called "Challenging", but this contradicts that.

> It's been pointed out to me many times that this isn't entirely true even as it stands right now.

> I think it's better to simplify how many difficulty levels we have.

Then let's rename both "Challenging" and "Difficult" to simply "Hard". Currently there is a very small difference between them in terms of balance and those two names are terribly synonymous. "Hard" is short, clear and it matches the actual setting names in WML (`EASY`, `NORMAL`, `HARD`, `NIGHTMARE`).

So far, EI and WoF have not received any complaints about their difficulty settings being too far apart. So I think the future is to have more meaningful differences between settings than the status quo of the mostly identical "Challenging" and "Difficult".

**Comment by Dalas121** [comment]
> So far, EI and WoF have not received any complaints about their difficulty settings being too far apart. So I think the future is to have more meaningful differences between settings than the status quo of the mostly identical "Challenging" and "Difficult".

I support this.  I'd be a fan of standardizing Easy, Normal, Hard, and Nightmare (as well as any 2- or 3-difficulty variation thereof), while also trying to keep the difficulty for each setting roughly similar across all campaigns.

**Comment by nemaara** [comment]
> Did you do any play testing of current WoF before renaming its difficulty settings?
> 
> Its "Easy" setting really is easy, with players usually getting a two fold gold advantage over their AI opponent(s). On its "Normal" players are generally on an equal footing against the AI in terms of gold. These first two settings are already carefully mimicking the "Easy" and "Normal" of most other current mainline campaigns, especially if you consider players cannot 'soft' lose future scenarios by mismanaging carryover or recalls and there are no real turn limits to worry about.
> 
> On its "Hard" setting the AI opponent(s) generally have a two fold gold advantage over players and on "Nightmare" it is four fold. So as with EI the difficulty ramp up is not small or linear.
> 
> >> "Challenging" was intended to be require around the same skill level for all campaigns that had a level called "Challenging", but this contradicts that.
> 
> > It's been pointed out to me many times that this isn't entirely true even as it stands right now.
> 
> > I think it's better to simplify how many difficulty levels we have.
> 
> Then let's rename both "Challenging" and "Difficult" to simply "Hard". Currently there is a very small difference between them in terms of balance and those two names are terribly synonymous. "Hard" is short, clear and it matches the actual setting names in WML (`EASY`, `NORMAL`, `HARD`, `NIGHTMARE`).
> 
> So far, EI and WoF have not received any complaints about their difficulty settings being too far apart. So I think the future is to have more meaningful differences between settings than the status quo of the mostly identical "Challenging" and "Difficult".

I considered this as well, just wasn't sure if it was too much of a change for this PR. But as you also are suggesting it, I'm down to merge challenging and difficult into "hard". Anyone else have opinions?

**Comment by Wedge009** [comment]
I was under the impression difficulty names was supposed to be standardised, or at least trying to head in that direction. I don't know if this is taking the same or contrary direction to that.

Neutral on the renaming.

**Comment by nemaara** [comment]
I'm realizing I might need to change the scope of this PR. I do want the more standardized difficulties, but will need to look at the other campaigns in a little more depth and tweak either their descriptions or difficulty levels to work. Let me put this as a draft instead for now.

**Pull request closed without merging**
