### PR TITLE
Revert "Fix travis osx build."

### PR DESCRIPTION
**Pull request by GregoryLundberg**
This reverts commit 489eed776091b65ab3ebe0ade2e1d0405658a375.

### CODE REVIEW

**Comment by mattsc** [comment]
The macos build launches again with this, both when clicking on the icon and from the command-line without have to specify the data-dir (which is as it was before).

**Comment by singalen** [comment]
A more conservative fix for warnings was the right thing: https://github.com/singalen/wesnoth/commit/7b8a8b61b3078840182cf97ffad96af851f3c646

On Mac OS 10.12 there is a bunch of other warnings. How soon do we need to deal with compilation on 10.12?

**Comment by mattsc** [comment]
> On Mac OS 10.12 there is a bunch of other warnings. How soon do we need to deal with compilation on 10.12?

Hmm, what warnings are those?  I am compiling using Xcode 9.2 on 10.12 and I don't get any warnings (other than the usual "update to recommended Xcode settings").  We do need to add the new surrender_game files to the Xcode project file, of course, but I assume that is not what you are talking about?

**Comment by GregoryLundberg** [comment]
Travis build is failing with a lot of deprecated this-and-that and a few unused variables and parameters.

**Comment by singalen** [comment]
So we have to deal with Mac OS 10.12 warnings.
I think I can do that too.

**Comment by GregoryLundberg** [comment]
Rebased, fixed merge conflict with PR 2279.

**Comment by GregoryLundberg** [comment]
Code-complete. No errors or warnings on Travis macOS build. Waiting for all CI to Green-light before merge.

**Pull request merged**
