### PR TITLE
WIP: Create log files on linux

### LINKED ISSUE #4805: create logfiles also on linux/mac
On windows wesnoth creates logfiles that contain the output of stderr, on linux that does afaik not happen. I don't know whether its my lack of linux knowledge but when i recently started wesnoth normally (here this means: form the desktop launcher with no console attached) and got an error then i had no idea how to get the output that was written to stderr, a situation that can no happen on windows due to the logfiles.

Even if linux somehow does supports recovering the stderr output of a non-termianl programm that did already run, i really don't expect users from who i might want bug reports to be able to figure out how to do it if i am unable to do it myself.

So what i propose it: generate logfiles on linux just as we do on windows.

### PR DESCRIPTION
**Pull request by lukasmalkmus**
This is a WIP PR. I want to - step by step - fix #4805. The codebase is rather large and I need to get familiar with it. Also need to refresh my CPP knowledge (again).

The idea is to take the work from [src/log_windows.cpp](src/log_windows.cpp) and [src/log_windows.hpp](src/log_windows.hpp) and adapt for Linux in the respective files.

The first commit just makes sure stuff compiles and I didn't break anything major :)

### CODE REVIEW

**Comment by gfgtdf** [comment]
Soo ... no progess in one month and so far he only copied  one file, should  we close this?

**Comment by Pentarctagon** [comment]
Depends on if @lukasmalkmus is still intending to work on it or not.  There are certainly much longer lived PRs still open though.

**Comment by lukasmalkmus** [comment]
I think I was a bit overoptimistic :( Tbh, I haven't made any progress apart from getting a bit familiar with the codebase. I someone feels the need to close this: Feel free to do so. If I have some more time on my hands in the future I'll pick it up from the ground again.

**Comment by Pentarctagon** [comment]
Closing then - if you get back to this in the future, feel free to either reopen this PR or open a new one.

**Pull request closed without merging**
