### PR TITLE
Change Human Ranger and Huntsman

### PR DESCRIPTION
**Pull request by Dalas121**
These Ranger changes are an attempt to raise his power closer to the Master Bowman or Elvish Avenger, while also cementing his role as a wilderness rover - powerful in the wild but vulnerable in castle/village.

These Huntsman changes are an attempt to help him better-fill the role of a frail mage-equivalent for the bandits (who otherwise lack Marksman/Magical), while adding some hunting flavor and a useful niche with "swamp lurk".

### CODE REVIEW

**Comment by Mirion147** [comment]
I would consider "unaccustomed" instead of "unused" for the ranger description. 

I think the huntsman changes are great, though I think the ranger is still a bit lackluster, but I think this puts it much closer to the mark and I'm willing see how the defenses play out.

👍

**Comment by Roge-Tebnelok** [comment]
A few questions:
Why 8x5 ranged on Hunter, and not 10x4? The presence of Windbolt kinda already breaks the uniqueness of Sharpshooter as the only archer with 5 hits per attack, but they are rarer than Hunters, who can be straight up recruited in Liberty, and the essence of mage-like unit is marksman/magical with great ranged damage, not multihit attacks which are primarily elvish thing. 10x4 is a bit weaker at night, but it's more humanlike and raises Hunter in comparison to Master Bowman as a better archer, who would be better then his loyalists counterpart if he had his strength and bow, as he doesn't need time to shoot hard with a great accuracy.
Why not improve Ranger's ranged instead of melee? His sword is already more powerful than bow because of possiblity to get strong trait, while he comes from the line of archers with better shooting skills. Also, sword isn't a weapon for wilderness, so him being trained with it more than bow doesn't make sense thematically. And while I understand the reasoning behind him having worse defense in castles, why not debuff it for all outlaws, who often live in the same conditions? Camp is also a castle and it's something a Ranger should be familiar enough to defend on effectively, same with villages, which can be small, temporary, isolated in the wilds and outlaw occupied. Swamp lurk suits hunter better than ranger, but it makes sense for the latter as well, why not also/instead add ambush?

**Comment by MrTitainin** [comment]
I think while Huntsman changes are agreeable, he's still not fully fitting mage role despite +4dmg buff, and therefore is still slightly underpowered - I'd say partially reverting hp nerf might help him with that, but that's not a musthave.

Meanwhile reducing Ranger's castle/village defense completely ruins this unit for me. I've always used it as a general-purpose all-rounder, with special focus on medium-terrain (not flat, but not mountains or castle either - forest, hills etc) defense - especially village nerf makes him hard to use in the area he excelled so far.
I'm very much against this change. Also while I've seen him less on castle, he still made use of it and that's fine. Especially since lore-wise he's not some sort of feral animal, born in forest - they're still humans, just ones that prefer to be away from people when possible - but not straight up running away from them (they can be still hired, as description notes). I'd say in my headcannon they're plenty capable when making creative use of terrain, including all sort of huts (they even probably live in one) and ruins, and if so, there's no problem for normal construction as well, especially ones specifically made for purpose of defense.

Also I generally agree with Roge here.

**Comment by ForestDragon-wesnoth** [comment]
In terms of huntsman, the current proposal of swampstalk + reduced hp seems overkill in my opinion, and would very heavily impact campaigns where swamp terrain is common and huntsmen are available to the player or enemies (enemies catching a player completely off-guard when the scenario was designed around them still being visible, or players cheesing leaderkills by sneaking through large sections of swamp). I think keeping the hp/abilities as is but just increasing the damage to either 8x5 or 10x4 would be good enough to make huntsman viable.

I agree with MrTitainin that the castle/village nerf for Ranger is entirely unnecessary, as he points out they are not as feral as animals so seems too extreme to treat them as such. I think it's best to keep the old castle/village defenses but reduce the hp buff a bit (so maybe instead of 67 it can be 62-64 or so)

Other terrain changes for ranger seem reasonable - movecost changes from 3 to 2 are much less likely to break mainline/UMC content than changes from 2 to 1, and the defense buffs generally make sense

As for ranger damage, I agree with rodolphecombe that 7x4 melee + 8x4 ranged would be a more fitting buff than 8x4 melee + 7x4, especially considering that huntsman would have +4 total damage now anyway so they are still distinct enough. On top of that, it's possible to get the old "equal melee and ranged" effect if you get the strong trait on ranger, while the other way around is impossible due to humans not having dextrous trait.

**Comment by MrTitainin** [comment]
> Regarding Castle/Village defense: I'm open to reverting this and finding a different way to separate the Ranger from the other archers. Right now his unique points are a weak ranged attack and better hill movement/defense.

I find his differences sufficient. Among similar units, he's close to Avenger and Wayfarer - they all have slightly different terrain defenses, Wayfarer gets pierce res, Avenger gets ambush. But Ranger is good at both hills and forests, and has low movement cost there, as well as unique 60% on swamp - those are actually pretty strong points alltogether, making him an all-rounder on common terrain. If any change is really needed, I think it'd have to be something unconventional like slow, accuracy/parry (or even acc/parry-like conditional weapon special), but not something that ruins his all-rounder usage.

**Comment by Dalas121** [comment]
> I've always used it as a general-purpose all-rounder (in NR especially), with special focus on medium-terrain (not flat, but not mountains or castle either - forest, hills etc) defense - especially village nerf makes him hard to use in the area he excelled so far.

> not something that ruins his all-rounder usage.

Could you elaborate on this a little? I'd generally considered the Fugitive to be the bandits' all-rounder - more MP, identical ranged damage, better durability in most terrains/situations, and the added bonus of invisibility.

While the Ranger does have more melee damage, given the general weakness of blade and common availability of the Fugitive/Highwayman I've never considered him particularly useful. In my mind, the 1.18 Ranger's best strengths is his swamp defense (shared by the Huntsman) and high mobility in forest/mountain - but to me he was already a worse option for defending village/castle (and forest/hills).

**Comment by Mirion147** [comment]
Not all units are going to progress the same way. While Poacher is an archer unit, as he levels to trapper, he becomes much more of a mixed fighter while the outlaw line takes on a more archer/scout role. This gives him options as a unit, stick with the mixed fighter role, or dive back into being primarily an archer. I think that having ranger gain melee damage was a unique approach that fit the path that the unit is on. I agree the defense changes were abnormal, but I'm honestly not sure if it would be straight up bad without testing it in game. I enjoy the unique identity that these changes placed on the Poacher line as a whole. These units have always been lacking imo. I think that switching huntsman to 10-4 is fine, but it pulls from that mix of elven marksman and master bowman and puts him too close to master bowman. I would prefer the 8-5 myself.

**Comment by MrTitainin** [comment]
> Could you elaborate on this a little? I'd generally considered the Fugitive to be the bandits' lvl3 all-rounder - more MP, identical ranged damage, better durability in most terrains/situations, and the added bonus of invisibility.

Fugitive has only one damage type, and I rarely see him in combat against units susceptible to it. In addition, he is susceptible to all three physical damage types, and damage he deals is mediocre - especially in melee. That one mp more is useful when map is flat, but when it is not it becomes twice as slow as Ranger.

So sure, Fugitive might look like an all-rounder, but he's actually quite reliant on his terrain defences - get a bit unlucky and he's dead, while he does not have movement costs that go with that reliance. He's better on flat and slightly better in castles/villages - but in campaigns I played he just fails in reliability.

Ranger has consistent 6mp across typical terrains, 60% defense on typical defensive terrains, including those that he has 1mp on, no damage type susceptibilities, better melee, and two different damage types, of which pierce quite often has advantage in enemy res (e.g. horse units, drakes). On no terrain does he move slower than 3 tiles per turn, but very often more.

Meanwhile while attacking, he has two good ranges with lots of hits, which means he can attack pretty much anything - and that especially comes in handy against enemy archers and mages. Outlaw pretty much only attacks melee units, because his own melee is not enough to kill and less reliable.

Overall, while it's debatable which one is strictly better, but if you want to buff Ranger, the best ways I see are: hp increase, damage increase, fearless musthave trait. In particular, giving him 68 base hp would allow resillient (good indicator for Ranger over Huntsman) to survive Knight's charge at daytime, and strong resilient (99% Ranger indicator) to survive strong Knight's daytime charge at full hp - and that's a good benchmark of what is good.

> But if you feel he's already quite strong with just his 1.18 stats (though I disagree), then maybe changes aren't necessary in the first place?

Leaving him at previous stats is ok - you get a cheap all-rounder, and one buff for that direction would be atypical upkeep decrease. But he is indeed a bit on the cheap-weak side, and buffing similarly weak Huntsman would require him to get a buff as well - here hp/damage are primary ways to get him stronger, while fearless trait, acc/parry etc would be more interesting, but less fitting.

Overall, he's not strong, but he's ok - it's Huntsman that's weak, because 1.18 Huntsman does not fulfill his attacker role well, but Ranger does fit his role reasonably well as mixed fighter whose primary goal is to retaliate and survive.

**Comment by Dalas121** [comment]
I do still disagree with some of your points. For example, by the math even a strong+resilient Ranger is less durable than a traitless Fugitive, even against blade damage and even in forest/hills/castle/village! Not to mention the Fugitive's massively better durability vs fire/cold/arcane attacks, on flat, etc.

And given how common undead are in both campaigns and UMC, I feel that impact is on-average more useful than blade/pierce. I've often used the Fugitive's melee to great effect vs the Skeleton Archer line! Even in Liberty (which includes a lot of enemy cavalry), there's at least as much impact-vulnerable HI.

I don't suppose there's any way to adjust the Rangers other stats in a way that you'd be alright with a lower castle/village defense? I'd really liked the flavor of that, and felt it made for a clear difference from the other factions' mixed-fighter archer units. If not, I'm ok with just HP/damage tweaks like you suggested.

**Comment by ForestDragon-wesnoth** [comment]
> Ok, Ranger damage changed to 7-4/8-4, Huntsman damage changed to 10-4.

Seems reasonable

> The "files changed" tab looks a little misleading, but I haven't changed any of the Ranger's movecosts - just reordered them to be alphabetical.

Ok makes sense

> . Regarding Castle/Village defense: I'm open to reverting this and finding a different way to separate the Ranger from the other archers. Right now his unique points are a weak ranged attack and better hill movement/defense.

> . That said, I'm open to reverting Swamp Lurk - but if we do revert both Huntsman's Swamp Lurk and Ranger's village/castle defense, I feel we'll need some other changes to the Huntsman/Ranger to help differentiate them from each-other and the elves / Master Bowman. The Huntsman/Ranger is the only branched advancement in the entire bandit lineup, so I'd like it to be a very meaningful one.

Now that I think about it, ranger has 30% reef defense but 40% shallow water defense and 60%. since reef is meant to be better for humans than land, maybe reef can be 40-50% defense instead? further solidifying ranger's niche as a difficult-terrain (especially considering most human units struggle to fight in water) expert. and maybe also buffing frozen from 20% to 30% since he moves faster on frozen than Trapper but currently has same defenses.

**Comment by rodolphecombe** [comment]
To me, Huntsman seems more bow oriented while the Ranger seems more mixed damage+mobility+defense oriented.
If you want to buff the Huntsman, increase his bow damage (as was done or maybe even 11x4). 
If you want to buff the Ranger (is it needed?), increase its mobility+defense not his damage. As was said, coastal reef to 40 or maybe even 50% def, 50% for cave, 30 or even 40% for frozen or reduce its move cost to 1 for cave, fungus or swamp.

**Comment by ForestDragon-wesnoth** [comment]
> want to buff the Huntsman, increase his bow damage (as was done or maybe even 11x4).

11x4 marksman would make him an objectively better Master Bowman (who has 11x4 without marksman), 10x4 is good enough

> If you want to buff the Ranger (is it needed?), increase its mobility+defense not his damage. As was said, coastal reef to 40 or maybe even 50% def, 50% for cave, 30 or even 40% for frozen or reduce its move cost to 1 for cave, fungus or swamp.

Reducing movecosts to 1 can affect some campaigns too much, and Ranger already has good movecosts, defense buffs would be less likely to break anything

**Comment by kameramen0106** [comment]
I would like to leave my opinion at this stage.

First, regarding the Huntsman, I think that HP is slightly too reduced, 54-55 would be better. However, the biggest issue is the swamp ambush ability, which I think is somewhat excessive change from tactical point of view. I will not know exactly without testing, but it could affect the balance of many campaigns in an impact that cannot be called an improvement. For those reasons I am against the addition of the ability. Increased damage would be okay.

Secondly, regarding the Ranger, I can understand the changes to the defense in the castle. But why should the defense in villages be reduced?

I feel that it does not make any noticeable sense from the lore aspect. They may indeed be wild and rough around the edges, but that does not directly translate to their defense in the village. Because in my opinion, the village is not necessarily the place of civilization. As for the other changes, I am basically neutral. But HP is now too large of an increase. So, about 64-65 seems appropriate.

**Comment by Dalas121** [comment]
> Ranger is significantly better against all horses and better against Swordsman+, Mages, Fencers, and Archers.

When fighting in Forest/Hills/Village/Castle and compared to the Ranger, the Fugitive can survive +16% damage vs Swordsmen/Fencers/Cavalry, +13% vs Mages, +26% vs Archers/lances, and +26% vs HI. On Flat, the Fugitive's advantage is even bigger.

Fugitive does 22% less melee damage than Ranger. Their ranged attacks are equal in power. If both attacks are used (for example, ranged retaliation against a Mage then counterattack in melee), Fugitive does 11% less damage.


> ranger has 30% reef defense but 40% shallow water defense and 60%. since reef is meant to be better for humans than land, maybe reef can be 40-50% defense instead? further solidifying ranger's niche as a difficult-terrain (especially considering most human units struggle to fight in water) expert.

Good idea, thanks. Done.


> and maybe also buffing frozen from 20% to 30% since he moves faster on frozen than Trapper but currently has same defenses.

Already included in the PR.


> Secondly, regarding the Ranger, I can understand the changes to the defense in the castle. But why should the defense in villages be reduced?
>
> I feel that it does not make any noticeable sense from the lore aspect. They may indeed be wild and rough around the edges, but that does not directly translate to their defense in the village. Because in my opinion, the village is not necessarily the place of civilization. As for the other changes, I am basically neutral. But HP is now too large of an increase. So, about 64-65 seems appropriate.

Ok, I've reverted Village defense to 60% and lowered HP to 64.


> If you want to buff the Huntsman, increase his bow damage (as was done or maybe even 11x4).

> However, the biggest issue is the swamp ambush ability, which I think is somewhat excessive change from tactical point of view. I will not know exactly without testing, but it could affect the balance of many campaigns in an impact that cannot be called an improvement. 

With regards to the Huntsman, I think the current stats are OK. As FD pointed out, more ranged damage would make him strictly more deadly than the Master Bowman, which seems wrong.

And while Swamp Lurk is a concern, I checked mainline and asked around in both the main discord and WMG discord to see if any major campaign/UMC would be seriously hurt. Nobody knew of any campaigns that might be hurt by this change - the Huntsman is a fairly uncommon unit, and swampy maps are less common that flat/forest/hill/water.

**Comment by rodolphecombe** [comment]
I am still not found of adding swamp lurk to the huntsman. To me it does not really fit thematically. 
And I do not really see a problem with 11x4. It is as much as the master Bowman, but the latter is more skilled in melee

**Comment by Dalas121** [comment]
The Huntsman already gets abnormally good 60% defense in swamps, so to me that felt like his "preferred terrain". Stealth is also a crucial skill for hunters, as compared with a soldier whose enemy is already alert and expecting a fight. Thus, I feel that stealth in swamps fits well with the Huntsman's preexisting identity - and doesn't step on the toes of the Elvish Ranger/Avenger.

Balance team has voted in favor of this PR 4-0-0, so I'll be committing it once the checks complete.

**Comment by rodolphecombe** [comment]
No problem. 
It's just that I thought it would have fitted ranger more than huntsman (he also has 60% on swamp). 
However, it is only my personal opinion, and I do not see any reason for it to block anything.

**Pull request merged**
