### PR TITLE
Prompt moderators to observe game with observers disabled.

### LINKED ISSUE #4101: confirm to observe game using moderator rights
Please add confirmation before force-observing games using Moderator rights.

This can happen accidentally because observing happens by simply clicking the Observe button for a Moderator, with currently no prompt whatsoever. It is relatively easy to miss the "no observers allowed" icon in the game list: it's on the right, far away from map icon and description.
Moderator observation is only meant to fight spam / abuse (see GH-2851). Players also get distracted because they see "*** joined the game" chat notification. A confirmation could help preventing that.

### Current behavior:
you can join a private game with just a double click

### Expected behavior:
show a confirmation dialog asking if you really want to use moderator rights to observe a game

### PR DESCRIPTION
**Pull request by Pentarctagon**
Fixes #4101

@vgaming 
prompt

### CODE REVIEW

**Comment by vgaming** [comment]
@Pentarctagon Yaaaay, thanks! The code looks pretty solid, likely CI would be enough (but I can also test if needed)

**Comment by vgaming** [comment]
I've added a "Backport" label to backport it, happy to do that myself as well if needed

**Comment by vgaming** [comment]
UPD: maybe the wording could be improved slightly. "This game doesn't allow observers. Observe using moderator rights anyway (abuse reports only)? I'm happy to change that before merging (and backporting)

**Comment by vgaming** [comment]
UPD: actually I wonder about the rule used in the code. Do password-protected games in wesnoth also allow moderators to join? In this case, shouldn't the code be changed?

I'll test that in wesnoth-1.16 now...

**Comment by vgaming** [comment]
UPD: joining password-protected games works by "secret" (non-user-visible) magic of knowing that you need to put an empty password as a password if you're a mod. I guess that's potentially a separate feature request.

**Comment by Pentarctagon** [comment]
I'd prefer just:
> This game doesn't allow observers. Observe using moderator rights anyway?

**Review by vgaming — APPROVED** [review]

**Comment by vgaming** [comment]
@Pentarctagon sure, that works as well

**Pull request merged**
