### PR TITLE
Miscellaneous units changes (mostly)

### PR DESCRIPTION
**Pull request by Hejnewar**
Misc
Elder Falcon - cost changed from 18 to 20.
Soldier ant – cost changed from 16 to 12, hp changed from 35 to 36
Yeti - cost changed from 80 to 151
Piglet – xp changed from 26 to 20
Woodland Boar – cost changed from 15 to 16, hp changed from 35 to 34
Fire guardian – xp changed from 29 to 24, hp changed from 23 to 25
Fire Wraith – gold cost changed from 22 to 17
Bay Horse and Dark Horse – xp changed from 44 to 24
Giant Scorpion - cost changed from 16 to 17.
Fire Ant - xp changed from 50 to 22.
Firebomb Ant - hp changed from 38 to 45, cost changed from 14 to 19.
Giant Ant – xp changed from 26 to 16
Mermaid Initiate – cost changed from 19 to 16, xp changed from 50 to 42
Mermaind Priestess – cost changed from 38 to 31, xp changed from 132 to 61 
Mermaid Diviner – cost changed from 57 to 49
Mermaid Enchanterss – cost changed from 33 to 32, xp changed from 90 to 46
Mermaid Siren – cost changed from 52 to 42
Merman Brawler - cost changed from 19 to 17.
Naga Guardian – xp changed from 35 to 36
Naga Warden – xp changed from 70 to 54
Troll Hero – cost changed from 30 to 42, xp changed from 52 to 90
Great Troll – cost changed from 48 to 78
Troll Shaman – cost changed from 32 to 35
Dwarvish Scout – xp changed from 30 to 33
Dwarvish Pathfinder – cost changed from 30 to 24, xp changed from 60 to 65
Dwarvish Explorer –cost changed from 45 to 51
Dwarvish Runesmith – cost changed from 30 to 27, xp changed from 86 to 71
Dwarvish Runemaster – cost changed from 50 to 55
Dwarvish Arcanister – cost changed form 80 to 98
Dwarvish Miner – cost changed from 19 to 5
Orcish Leader – cost changed from 20 to 21, xp changed from 60 to 54
Orcish Ruler – cost changed from 35 to 45, xp changed from 120 to 102
Orcish Sovereign – cost changed from 50 to 80
Skeleton Rider – xp changed from 44 to 33
Death Squire – xp changed from 144 to 91
Death Knight –cost changed from 45 to 80
Royal Warrior - cost changed from 40 to 47
Elvish Lord – cost changed from 36 to 42, xp changed from 120 to 97
Elvish Highlord	- cost changed from 56 to 77
Nibbler – cost changed from 10 to 15, xp changed from 32 to 26
Caribe – cost changed from 16 to 25, xp changed from 40 to 43
Hunter Caribe – cost changed from 25 to 40
Dragonfly Naiad – cost changed from 8 to 11, xp changed from 23 to 16
Dragonfly – cost changed from 13 to 16, xp changed from 23 to 25
Grand Dragonfly – hp changed from 34 to 39, cost changed from 22 to 30
Ruffian - cost changed from 6 to 7.
Thug - xp changed from 42 to 32.
Bandit - cost changed from 23 to 22, xp changed from 70 to 61.
Peasant and Woodsman - xp changed from 23 to 19.
Elder Mage - cost changed from 65 to 90.
Loyalists
Young Ogre – cost changed from 15 to 13, xp changed from 32 to 34, mountain defense changed from 60% to 50%, arcane resistance changed from 20% to 10%
Ogre – cost changed from 30 to 27, mountain defense changed from 60% to 50%, arcane resistance changed from 20% to 10%
Rebels
Elvish Enchanterss – xp changed from 180 to 198
Elvish Sylph – cost changed from 148 to 161

This is not the end i still didnt do / forgot about some units.

### CODE REVIEW

**Comment by Jonathan-Kelly** [comment]
Could we put the submerge ability on the Kraken? It is sad we do not have even a single sea monster with `hides`. Thematically, the squid-like Kraken is the best fit for a creature that can disappear into the deep sea. As is the appearance of its sprite:
k_v_s
_Just look at that stealthy beast!_

**Comment by Pentarctagon** [comment]
Was a follow up ever made for #7125, or would this essentially be that follow up?

**Comment by Hejnewar** [comment]
Probably this is just separate request? 

I might, idk.

Also no idea why this is failing. Probably unrelated to this PR.

**Comment by Pentarctagon** [comment]
Yeah, it's not related to this PR.

**Pull request merged**
