### PR TITLE
Efficiency improvements to Lua AIs

### PR DESCRIPTION
**Pull request by mattsc**
There is probably more that can be done along these lines and I am planning to do a general clean-up of the Micro AIs later.  In the meantime, this is specifically for the Goto Micro AI (although it affects some other Lua AIs as well) in response to [this forum thread](https://forums.wesnoth.org/viewtopic.php?f=21&t=48125).  For one of the test cases from that thread, it improves the evaluation time from close to a second (on my computer) to a milli second.

I don't have time for the more comprehensive clean-up right now, but it would be good to get this into 1.14.3.

### CODE REVIEW

**Comment by mattsc** [comment]
> You can use status = "petrified" instead of a formula here. Might be a little faster, not sure if it's actually worth it though. (Of course that would also change the tag name from and to not.)

Oh, right ...  It's probably not worth it as far as performance is concerned (in fact, I was wondering whether it was worth changing this function at all), but might as well do it "right", because somebody will eventually take the code and copy it.

> Also is there a reason not to use wml.tag["and"] here and elsewhere?

The only reason I didn't is that that's new syntax and I didn't think about it.  The only reason to use wml.tag is because it simplifies syntax though, right?  As in, there's no (noticeable) difference in performance?

In any case, I'll change both those things.

**Comment by CelticMinstrel** [comment]
> The only reason I didn't is that that's new syntax and I didn't think about it. The only reason to use wml.tag is because it simplifies syntax though, right? As in, there's no (noticeable) difference in performance?

Well, the question was more about using the WML tag metatable at all rather than specifically using `wml.tag` - if you already had the WML tag metatable assigned to `T`, as was commonly done, then `T["and"]` would work equally well (and always has).

Yes, it's only to simplify syntax, reducing the levels of nested braces. I don't think there'd be a noticeable performance difference.

**Comment by gfgtdf** [comment]
t.tag or wml.tag.tag is expected to be rather slower than faster copared to writing the brackets manually since it involves and extra table lookup and an extra function call, but its not important here becaue its negletable compared to he other stuff these functions do.

**Comment by mattsc** [comment]
I changed the syntax for the petrified status check, but as I said on irc, I find the bracket syntax "tidier":
```wesnoth.get_units { { "not", { status = "petrified" } }, { "and", filter } }```
vs.
```wesnoth.get_units { wml.tag["not"] { status = "petrified" }, wml.tag["and"](filter) }```

Since it is also faster (even if negligibly), I'll stick with the former.

**Pull request merged**
