### PR TITLE
Timestamping server messages [1.16 backport]

### PR DESCRIPTION
**Pull request by Discontinuum**
Backport #6979

### CODE REVIEW

**Comment by Wedge009** [comment]
Seems reasonable to me. Just wondering why you didn't cherry-pick the original commit, though - looks like you've added an extra line compared with what was added to master.

**Comment by Discontinuum** [comment]
Yeah, I didn't notice the extra line, my bad. I can fix it if that matters. 

> why you didn't cherry-pick the original commit
I tried to rebase the original commit onto 1.16 branch but it failed, maybe because I fetch branches from the Wesnoth repo with 1 commit depth, I'm too lazy to download the full 3GB repo history

**Comment by Wedge009** [comment]
I don't think it matters too much, but it's a divergence from master that is probably best avoided. I normally cherry-pick in GUI, but I think it should be a rather quick operation, shouldn't need to download branches for it. If there are no objections to this PR, I could just cherry-pick it for you.

**Comment by Wedge009** [comment]
Ah, I just noticed soliton's affirmation regarding back-porting, plus Pentarctagon assented in #wesnoth-dev too. Have back-ported in b5ce5010881d87e44701f69e86cbc6f3531d456e.

**Pull request closed without merging**
