### PR TITLE
THoT: Tweak four scenarios

### PR DESCRIPTION
**Pull request by jostephd**

### CODE REVIEW

**Comment by jostephd** [comment]
Angarthing's remark that something is glowing inside the hut is spoken just as day breaks. I am puzzled as to why they didn't spot any glow or light from the hut during the night (turns 5-6). Surely Ratheln would have had a fire lit overnight to keep warm?

**Comment by sevu** [comment]
I just played last night through the first scenarios, and was confused by the hint as well. I had no idea which village was meant.

Technically, there has been a change not too long ago (last half year) by Doofus that the some villages do really have a light glowing at evening and 1st watch. It is dependent of the [time]s' id – which are not important anywhere else – one could make that village have a glowing light all the time by having there an time area, which is the same as the default schedule, but has the id of evening or 1st watch for all [time]s. And could use [remove_time_area] when the mage has been encountered. ...

But well,... maybe a better hint? Actually, the hint is not needed, as there is no way to not trigger the event... if you didn't trigger it at turn 8 it rather means you are in danger to not finish the level in time.

@doofus-01 The lights are enabled for `*^Vc`, can they be enabled for `*^Vca` too?

**Comment by doofus-01** [comment]
> The lights are enabled for *^Vc, can they be enabled for *^Vca too?

Sure.  I'll look into it this weekend.

**Comment by jostephd** [comment]
@sevu Thanks for merging. I don't know whether the hint should be removed. On easy difficulty the turn limit is 24 so maybe the hint is useful there. Instead of making the village glow even in morning/afternoon could we change the line, change "Something is glowing in that hut" to "There's a scent of scorched gryphon meat in the air, emanating from that hut yonder"? I realize that can't be done until after string freeze.

**Comment by sevu** [comment]
Sounds good.

**Comment by jostephd** [comment]
Done. I didn't know about string freeze, how does it work?

**Comment by sevu** [comment]
Starting with the string freez translators can translate the new changes since the last release. (At that time the pot-update is run)
Before that, they can only improve the translation at the state of 1.14.3, and it may or may not be send as in-between update do steam (happened just once so far).
String freeze starts usually one week before the release tagging, until the tagging new translations can be submitted. It ends with the announcement of the release in the forums, which is often a few days later, so one can make a new tag if a problems occurs without restarting the release process from scratch.

Release dates (meaning tagging dates) and string freezes are announced in the topic in Discord.

**Comment by jostephd** [comment]
Thanks for explaining. I've been collecting a new batch of typos so I won't hurry to submit it.

**Comment by sevu** [comment]
Oh, you removed the cherry-picked commits. Neat.

**Pull request merged**
