### PR TITLE
core: Fix grammar and punctuation

### PR DESCRIPTION
**Pull request by jostephd**
Split from #2390 at @GregoryLundberg's request.

### CODE REVIEW

**Comment by Vultraz** [comment]
I agree with all these changes except the one to the Lich description. It seems a bit more awkward now.

**Comment by CelticMinstrel** [comment]
Small changes like this should also be included in the po-fixes script.

**Comment by jostephd** [comment]
@Vultraz Yes, the sentence is rather long. I've refactored it.

@CelticMinstrel I'll update utils/pofix.py.

**Comment by Vultraz** [comment]
Hmmm... I think you changed the meaning too much. First off, "testament" would be more appropriate than "testimony" here. Second, the new sentence essentially says it's admirable that the dark sorcerers have kept the details of necromancy secret. The original sentence was saying it was impressive that one would even need to ask whether a Lich lives indefinitely or not.

Honestly, probably best just to stick with the original wording.

**Comment by jostephd** [comment]
You're right. I've reverted the refactoring and made another change to avoid "But" at the start of a sentence.

**Comment by jostephd** [comment]
pofix updated.

**Comment by Vultraz** [comment]
Seems good now. Thanks!

**Pull request merged**
