### PR TITLE
Simplify game_config::path determination

### PR DESCRIPTION
**Pull request by soliton-**

### CODE REVIEW

**Comment by stevecotton** [comment]
Is the behavior meant to be exactly the same?

I haven't reviewed the code yet, I'm asking to know what to look for.

**Comment by soliton-** [comment]
Not in all cases. The weird font manager destruction and recreation is not done anymore and there where several confusing ways the path was set. Like auto detection running even when --data-dir was given and in the end the path may or may not be normalized. (I think parts of this might have been introduced only recently when code got moved around.)

With this there is one single place where the path is determined and set in normalized form and if the path does not exist exit is called.

**Comment by CelticMinstrel** [comment]
Sounds like this might fix the bug I've been seeing where `--data-dir` seems to be ignored when launched from Xcode.

**Comment by CelticMinstrel** [comment]
> Sounds like this might fix the bug I've been seeing where `--data-dir` seems to be ignored when launched from Xcode.

Just noting that I tried it out and it does indeed fix the issue.

**Pull request merged**
