### PR TITLE
Set UtBS date to 600 AF to prevent lore conflicts with IfTU

### PR DESCRIPTION
**Pull request by Gothyoba**
Sorry about this second PR! This is a follow-up on #9404 Apparently my previsouly proposed date of 1000 AF contradicts certain UMC such as IfTU so I’m going for 600 AF, which is still more reasonable than the previous 300.

### CODE REVIEW

**Comment by knyghtmare** [comment]
Requested review from the IftU author herself, since it was the add-on referenced here.

**Comment by irydacea** [comment]
This is a bit of a strange request since obviously my add-ons are not canon. Regardless, I'll give you some input.

Let me start by saying that the only thing that's fixed regarding time in my campaigns' own canon (this means both Invasion from the Unknown and After the Storm) is that IftU begins approximately 358 years after UtBS. This obviously has no real relevance for mainline since there's never going to be any content set after UtBS.

Regarding the amount of time that's passed since the Fall, however, I've always been pretty flexible about it and never made any hard assumptions, instead letting characters provide vague speculation without providing any kind of factual records in-universe that could reveal the truth. I attempted to provide some justification for this in the timeline outline:

> Pollution and debris from the fallen sun and volcanic activity cause cyclic periods of absolute darkness over the whole world, making it impossible to keep accurate track of time using astronomical means for over two centuries.

Personally I've always gone with an estimate of 1,500-3,000 years taking into account elves' lifespan, the possibility of said lifespan shortening over time*, the amount of historical records that have been lost on all sides over time, and the many changes to the overall world of Irdya compared both to before the Fall and *during* and *shortly after* the Fall per the merfolk's records.

\* (classic UtBS never specified how long desert elves lived compared to forest elves, then again at the time it was originally written the lifespan of forest elves wasn't defined)

Regardless of anything else, including the technical need for a "start date" for classification purposes, it would be good to make sure that UtBS' start date is never actually shown in the user interface since it'll always be speculation at best.

**Comment by Gothyoba** [comment]
Looks like it should be close then.

**Comment by CelticMinstrel** [comment]
I think I will also note that it shouldn't be assumed that 1 AF is the day after the "fall". The AF epoch measures from an arbitrary point after the fall where things became organized enough to start keeping records again. So, 1 AF could already be a couple hundred years after the actual event.

**Pull request closed without merging**
