### PR TITLE
Rename [unit_type_fix] to [modify_unit_type] for clarity.

### PR DESCRIPTION
**Pull request by Pentarctagon**

### CODE REVIEW

**Comment by soliton-** [comment]
I like `modify_unit_type` a little better. I think `modify` is used more often in similar tags?

**Comment by GregoryLundberg** [comment]
I don't see any documentation on [unit_type_fix] but if it does for unit_type what [modify_unit] does for unit, then [modify_unit_type] would be a more logical choice.

**Comment by jostephd** [comment]
@GregoryLundberg It's documented in https://wiki.wesnoth.org/ModificationWML

**Comment by Pentarctagon** [comment]
Updated to modify.

**Pull request merged**
