### PR TITLE
Make the multiplayer faction accessible via Lua and simplified Hornshark

### PR DESCRIPTION
**Pull request by spixi**
Now the same thing like in #643, but instead of checking against the translatable string, we check against the id.

### CODE REVIEW

**Comment by gfgtdf** [comment]
this has some wrong indention, in particular, our c++ code shoudl be indended via tabs and not spaces.

**Comment by spixi** [comment]
Hello gfgtdf,

ignore the second commit. I was logged in as root, to invoke "make install". I guess this edit was from CMake. The third commit is the correct one. Should I fix the intention?

**Comment by spixi** [comment]
I just fixed the indention.

**Comment by CelticMinstrel** [comment]
The faction field should probably be added to the formula team proxy too, in _src/formula/callable_objects.hpp_. (You could add faction_name there too, but so far I've mostly avoided including translatable strings in the formula proxies.)

**Comment by spixi** [comment]
@CelticMinstrel: Where is the Callable Objects Proxy used? Is there a test case for this?

**Comment by spixi** [comment]
I don't know how to use pick and squash. I hope, it is correct now.

**Comment by spixi** [comment]
I think, I broke everything ...

**Comment by CelticMinstrel** [comment]
Unfortunately there are no test cases that I know of for the formula team proxy. It's used in Wesnoth Formula Language, eg the formula= key in a filter.

It seems that you badly messed up the attempt to squash - that last commit is all merge conflicts and should probably be discarded (eg with `git reset HEAD^`). If you can fix it, great, but it shouldn't be too hard for me to fix it when merging.

**Comment by spixi** [comment]
Sorry, I don't know how to reset the repository. I hope, you can fix it.

**Comment by spixi** [comment]
See #658

**Pull request closed without merging**
