### PR TITLE
Fix build on MacOS Catalina

### PR DESCRIPTION
**Pull request by CelticMinstrel**
I had a choice of replacing `value()` with `*` or bringing back `utils::optional`. Personally, I think having `value()` is probably better, as it throws an exception instead of silently reading garbage.

### CODE REVIEW

**Comment by Pentarctagon** [comment]
What was the build issue?

**Comment by CelticMinstrel** [comment]
`value()` does not exist

**Comment by CelticMinstrel** [comment]
What…? How did this get merged? I don't remember clicking the merge button.

I was going to merge it anyway, so whatever, but…

**Comment by gfgtdf** [comment]
Is this needed for you specificially to build wesnoth? Otherweise its imo not really worth it to support such an old version.

That said, i also think being able to write std:: instead of boost:: is not really a noticable advantage either, unless there is something concrete that the std:: version does better.

**Comment by CelticMinstrel** [comment]
> That said, i also think being able to write std:: instead of boost:: is not really a noticable advantage either, unless there is something concrete that the std:: version does better.

I've said pretty much this several times. Completely agree.

> Is this needed for you specificially to build wesnoth? Otherweise its imo not really worth it to support such an old version.

It was done in response to build failures on my local machine. It is presumably not the only way to fix the build failures. I also could have replaced `value()` with `*` or bumped the deployment target to 10.14; either change would probably be sufficient for me to build locally.

I chose this option because:

* Throwing an exception seems better than silently reading garbage
* Bumping the minimum version just so we can write `std::` instead of `utils::` strikes me as crazy

**Comment by gfgtdf** [comment]
wait so whether these are avilable depends on the deployment target ? That sounds really dumb since all of these features are header only and shouldn't require any library on the end users computer to be installed.

**Comment by CelticMinstrel** [comment]
I didn't make the header, so who knows. Maybe there's something in the optional header that _isn't_ header-only. Or maybe the Apple person just wasn't thinking clearly.

**Pull request merged**
