### PR TITLE
WIP add documentation for bool_ability and combat_ability(for 1.15/16 version)

### PR DESCRIPTION
**Pull request by newfrenchy83**

### CODE REVIEW

**Comment by newfrenchy83** [comment]
Don't forget me, please!

**Comment by jostephd** [comment]
@newfrenchy83 Thanks for the bump. The functions in question were added in 7f7217cf157393fc5fe3526a81181d95aa7fcbe9. @GregoryLundberg any chance you can have a look at this PR?

**Comment by CelticMinstrel** [comment]
This is pretty terrible as documentation. It does look like it describes what each of the functions do, but it's kinda rambling and not very easy to understand.

As a starting point, the documentation should be made to use Doxygen markers to individually explain the purpose of each parameter and the return value.

**Comment by jostephd** [comment]
@newfrenchy83 Could you give this another shot, please? Each comment should answer the following questions:

- What does each parameter mean?
- What does (each component of) the return value mean?

**Pull request closed without merging**
