### PR TITLE
terrain.cfg: Fix grammar in Rockbound Cave

### PR DESCRIPTION
**Pull request by jostephd**
Remove "who", add full stop.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
This looks good, but if you'd like to also add a few "the" in there it would be nice (particularly "the main settlers" but there was at least one other place where I thought an article would make it sound better).

**Comment by Ja-MiT** [comment]
Another place: "reduces **the** efficiency of most units".

**Comment by jostephd** [comment]
@CelticMinstrel @Ja-MiT Thanks for the review; added both.  What about "formed by the action of water and wind", is that correct?  Should the "the" be removed, or another added?

**Comment by Ja-MiT** [comment]
I think that part is fine as it is. While it would be correct to say "the water and wind", you'd lose some poetic feel to the description.

The part that still strikes me as odd is "the full advantage", where I would drop "the". However, that might be just personal style.

**Comment by jostephd** [comment]
Right, thanks.  What about changing "advantage" to "capability"?

**Comment by CelticMinstrel** [comment]
That phrasing is rather awkward in general. I think it might be better to write something more like "Dwarves ... can easily navigate the terrain."

**Comment by jostephd** [comment]
How about just deleting that sentence entirely?  It repeats the preceding one.

Or, alternatively, see the commit I just added (5be5170), which makes a few more tweaks.

**Comment by jostephd** [comment]
The travis error seems to be a false positive.  Is there anything else I need to do to move this forward?

**Comment by CelticMinstrel** [comment]
Nothing whatsoever.

**Comment by jostephd** [comment]
Cheers!

**Pull request merged**
