### PR TITLE
WIP: SotA Fixes

### PR DESCRIPTION
**Pull request by sigurdfdragon**
This pr is for various minor fixes to the Secrets of the Ancients campaign.

### CODE REVIEW

**Comment by sigurdfdragon** [comment]
There's two possible fixes here for the hard edge void, I prefer the impassable shroud version.

**Comment by Wedge009** [comment]
I'm still about half-way of a proper play-through. It's quite a lengthy campaign (which is good!).

Thanks for the ellipsis spacing, I concur with that. I don't see anything game-play-changing with the map changes. If no-one else has issue with this, I'm favour of merging.

**Comment by Vultraz** [comment]
@sigurdfdragon just committed 4cbd411 which makes Difficulty entries the same size by default, so c16e77a isn't strictly needed anymore, but it might be good to reduce the size anyway.

**Comment by sigurdfdragon** [comment]
@Vultraz gonna leave in c16e77a, as the SotA difficulty menu looks better with it.

**Comment by sigurdfdragon** [comment]
Went with the impassable shroud fix for the void hard edges on S1

**Comment by beetlenaut** [comment]
There are a couple small things I want to change. Should I use this fork?

**Comment by sigurdfdragon** [comment]
Sure, go ahead

**Comment by beetlenaut** [comment]
The bug that allows WCs to be recruited from anywhere seems to be caused by the values of x1 and y1 being changed by the player right-clicking while the [command] of a menu item is executing. This is probably unintended behavior. We can fix it easily enough by copying the values into new variables, but isn't this an engine bug?

**Comment by beetlenaut** [comment]
There are three translations on the add-ons server. Even though they are not completely current, they should be added, but I'm not sure how to do that correctly.

**Comment by Wedge009** [comment]
I think it's a matter of copying the files to the po directory... is this something that still has to go through @ivanovic first? He normally maintains the translations.

**Comment by beetlenaut** [comment]
You can't *just* copy the .po files into their directories because then Wesnoth doesn't compile. If ivanovic usually does it, I'll let him.

**Comment by beetlenaut** [comment]
I'm done with the fixes and changes I wanted to make.

**Comment by sigurdfdragon** [comment]
That's all I have for now. I don't know how to add the translations.
Unless there's anything else, I'll run a rebase to do minor commit title cleanup on Thursday.

**Comment by beetlenaut** [comment]
I found something else I wanted to fix. I committed it and something else got committed at the same time that isn't something I did. Did I just merge it? I didn't mean to and have no idea how it could have happened.

**Comment by Vultraz** [comment]
@beetlenaut which commit is the problem one?

**Comment by Wedge009** [comment]
@Vultraz I think he's referring to 6f5de6b, the most recent one.

**Comment by Vultraz** [comment]
@beetlenaut ok, 6f5de6b is just a merge commit. You must have made 5dd0e03 before pulling 84aa6b3 and 552e089, so git automatically made that merge commit. You can get rid of these by forcibly rebasing onto to master.

**Comment by beetlenaut** [comment]
Okay, thanks. I thought maybe I had broken something.

**Comment by sigurdfdragon** [comment]
Rebase completed

**Comment by sigurdfdragon** [comment]
@beetlenaut 
I took a look at the SotA translations on the add-on server.
They are the compiled .mo files
What needs to be placed in master/po/wesnoth-sota are the uncomplied .po files
it may just be as simple as doing that. Do you have the .po versions?

**Comment by beetlenaut** [comment]
It was the .po files I tried adding, and that's what didn't work. Anyway, I've sent the .po files to @ivanovic, and hopefully he can handle it soon.

**Comment by Wedge009** [comment]
So 19 turns for everyone. I suppose one turn more/fewer hardly makes a difference in the starting scenario.

**Comment by beetlenaut** [comment]
I don't agree with this change. At the hard difficulty, you really might need that last turn. If it bothers you that it takes place at dawn, you can add another turn of night to the beginning of the schedule instead.

**Comment by Wedge009** [comment]
Hmm, in that case, maybe the dialogue needs correcting then.

I'm about two-thirds or three-quarters through my own play-through. Getting to the tough part now, if I recall correctly.

**Comment by sigurdfdragon** [comment]
I could add another morning hour on the end of the schedule instead.
With no change, On hard, it loops back around, so that the time over dialog is given during nighttime

**Comment by beetlenaut** [comment]
Oh, I see what was wrong now. It actually shows turn 21 when time runs out. I guess I never tested that. Sure, adding a morning works just as well.

**Comment by sigurdfdragon** [comment]
Hmmm... How about this: Adding a {FIRST_WATCH_HOUR2} to the beginning and setting turns to 20/20/20?
With that, dawn would be the last turn for the player, and the time_over would be delivered during the morning hour for all difficulty levels

**Comment by beetlenaut** [comment]
Okay, let's do that.

**Comment by sigurdfdragon** [comment]
Updated ToD/turn change. Went with 20/20/20, adding two First_watch_hour2 at the beginning, and removing morning at the end, so that time_over ToD behavior & dialog match what happens in S2 as well.

**Comment by Vultraz** [comment]
If all the turn values are the same you can just do `turns=20`

**Comment by sigurdfdragon** [comment]
Did the macro, as that's the style of S2 as well where it's 18/18/18

**Comment by Vultraz** [comment]
Well, that could be changed to. Just saying.

**Comment by CelticMinstrel** [comment]
I'd agree that there's no point using the macro when all values are the same, though it doesn't hurt or anything.

**Comment by sigurdfdragon** [comment]
Added commit to clarify that Ardonna needs to be moved to the tunnel in S6

**Comment by Wedge009** [comment]
Ah, good one. I remember being confused about how to finish that scenario the first time I played it.

**Comment by beetlenaut** [comment]
I never noticed that the ellipse was visible there, but it is, so that's an improvement. Wouldn't it be better if it went in the dummy.cfg file though?

**Comment by sigurdfdragon** [comment]
Yeah, it would. Fixed.

**Comment by sigurdfdragon** [comment]
Any thoughts on if making the S2 guards attempt to recapture the guardhouse would affect the difficulty too much?

**Comment by Wedge009** [comment]
It makes sense in terms of behaviour, but I find the graveyard to be pretty cramped as it currently stands. Would it make that much difference in the AI? Maybe try it for hardest difficulty only?

**Comment by UnwiseOwl** [comment]
I'd say it's worth making that change. Being able to lose the ability to recruit is a nice touch and having the AI try to force it probably doesn't make it too much harder. Actually, if anything it might make it easier, as it'll presumably reduce their desire to kill your leader.

**Comment by sigurdfdragon** [comment]
@beetlenaut 
I noticed that Ras-Tabahn's traits are stong,loyal. As loyal isn't necessary for leaders, is this a placeholder? Could/should he receive another trait instead?

**Comment by beetlenaut** [comment]
Hmm. I thought he was strong and intelligent. That was what I meant to use anyway.

**Comment by sigurdfdragon** [comment]
I've finished my debug playthrough, so that's it from me for.

@Vultraz , @CelticMinstrel Is it desired to squash this down to a few commits like was done with https://github.com/wesnoth/wesnoth/pull/896 ?

I'm looking to get this wrapped up by the end of Friday, so this can be in 1.13.7

**Comment by Vultraz** [comment]
If beetlenaut signs off on this, I'll merge it. Commits seem fine as-is, since they're all for specific issues and not a bunch of WIP WIP WIP ones.

**Comment by beetlenaut** [comment]
@Vultraz  It's fine with me. Go ahead.

**Comment by Vultraz** [comment]
Thanks for working on this you guys :)

**Comment by sigurdfdragon** [comment]
You're welcome. :)

**Comment by sigurdfdragon** [comment]
I've decided not to pursue the S2 guardhouse change at this time, as I think might make things easier. It can always be done later.

**Pull request merged**
