### PR TITLE
fix leader image not always tc_colored

### PR DESCRIPTION
**Pull request by newfrenchy83**
Sometimes in last saves of scenario the leader image is magenta.

### CODE REVIEW

**Comment by Vultraz** [comment]
How did you reproduce this? I have a similar case under different circumstances, but I'd like to know where you see this happening.

**Comment by newfrenchy83** [comment]
when i play utbs with mew unit sprites, in the last save kaleh magenta is not tc_colored

**Comment by Vultraz** [comment]
What do you mean "last save"?

**Comment by newfrenchy83** [comment]
The last savegame played in the scenario or "sauvegarde automatique" in french

**Comment by Vultraz** [comment]
Could you upload a savegame where this happens? I don't think the fix here is the correct one.

**Comment by newfrenchy83** [comment]
I think what i will propose another change for clarifie the origin of problem

**Comment by newfrenchy83** [comment]
leader_image = filesystem::get_independent_image_path(leader_image);  is used when the leader image is not find but the tc_coloring has be forget in game_load. Only the image leader named in save_index are tc_colored in load game window.

**Comment by Vultraz** [comment]
Ah, I see... Yes, this might be the fix..

**Comment by Vultraz** [comment]
I pushed your change with some comments added. Thanks for tracking this down :)

**Pull request closed without merging**
