### PR TITLE
Send scenario/era/modification source add-ons and addon versions to wesnothd.

### PR DESCRIPTION
**Pull request by Pentarctagon**
This adds the additional attributes under the multiplayer information sent to wesnothd:
* mp_scenario_addon_id
* mp_scenario_addon_version (host's version)
* mp_era_addon_id
* mp_era_addon_version (host's version)
* active_mod_addon_ids
* active_mod_versions (host's versions)

---

This doesn't contain the part to actually insert the data, since I don't want to create a conflict with #4884.

### CODE REVIEW

**Comment by gfgtdf** [comment]
What the intention here? just to store it into the database ?

**Comment by Pentarctagon** [comment]
Yes.

**Comment by gfgtdf** [comment]
I think it'd be nice if the mp server would  automaticially check whether all addons used are up to date, for that it'd need to ask the addon server probably. Maybe it'd be easiest if the mp server just fetched a list of all addon versions from the addon server every hour.

**Comment by Pentarctagon** [comment]
That would additionally require:
* The client to tell wesnothd all add-ons the user has installed and their version on login, rather than just the ones that will be used in the current game.  That wouldn't entirely supersede this change, which also links the add-on+version to the particular scenario/era/modifications being used.
* Some way to check what the current version of the user's add-ons are.  IMO this would be best implemented by giving campaignd database support and on upload inserting/updating a row in a new database table that would have the add-on ID and version, which wesnothd could then simply query.

So while I do think it's something worth doing, it's also not something I'd work on implementing at least until after #4884 is hopefully able to be merged in early July.

**Pull request merged**
