### PR TITLE
merge moveto event into turn_refresh, closes #8954

### LINKED ISSUE #8954: In MP games with Plan Mod enabled Undo doesn't work for the first action of a turn even if no fog/shroud update
### Game and System Information

- **Version:** 1.18

### Description of the bug

If "Plan Unit Advance" is enabled, the first action of every side's new turn can't be undone, even if it doesn't update fog/shroud

### Steps to reproduce the behavior

1. Host a game on any simple MP map (Isar's Cross, for example) with enabled "Plan Advance Mod" and with Fog of War and Shroud disabled (in the map choosing window click the "Game Settings" tab, disable "Use Map Settings" and disable "Fog of War" and "Shroud"
2. Move your leader by one hex. You can't undo this action
3. Move your leader one hex more. Now undo works
4. Repeat steps 1-2 without "Plan Advance Mod", now the first move is undoable

### Expected behavior

Plan Advance Mod doesn't affect undoing

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ProditorMagnus**

### CODE REVIEW

**Comment by stevecotton** [comment]
Please mention Pick Advance in the first line of each commit's message, otherwise the Git history log will be confusing.

**Comment by ProditorMagnus** [comment]
It doesnt offer renaming.

**Comment by stevecotton** [comment]
Yeah, Github doesn't offer a way to rename without squashing the commits, and IMO these should stay separate. Renaming would need a `git rebase` and force-push.

**Comment by ProditorMagnus** [comment]
until I created second branch, git log only showed one commit, and git rebase -i HEAD~2 did not work

**Comment by Pentarctagon** [comment]
@stevecotton any other concerns with this?

**Comment by stevecotton** [comment]
Sorry for the slow response - I was "commits look good, but my brain isn't ready to read Lua code" about it. The change looks good; I approve merging it as it was in d249883.

@ProditorMagnus, was the PR closure intentional, or an accidental deletion from reusing the branch name.

**Comment by ProditorMagnus** [comment]
Thought it was merged so removed branch.

**Pull request merged**
