### PR TITLE
Re-add cropping of transparent padding on status icons.

### LINKED ISSUE #8303: Status icons are rendered deformed (poisoned, slowed, petrified)
### Game and System Information

- **Version:** 1.17.24
- **Downloaded from:**AUR
- **Build info:** 80da6fd
- **OS:** Manjaro Linux under X11
- Also appears on Windows 10

### Description of the bug

bug
As the upscaled image shows, status icons are shown squashed in-game. That goes both for mainline ones _and_ for UMC created art.

I've added the proper visual of the icon under the rendered one with added border for clarity.

### Steps to reproduce the behavior

1. Start any scenario
2. Apply any status to any unit
3. The icon(s) is/are deformed

### Expected behavior

3. The icons is shown in its proper aspect ratio

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Pentarctagon**
Fixes #8303

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Looks mostly good, but this won't apply to custom icons like stun. Didn't we discuss that the IPF should be appended later on in the pipeline so that custom icons also benefit from it? It's not the end of the world if it doesn't (since being squashed is a relatively minor bug and anyone who gets it can fix it by manually adding the IPF), but if we're _not_ going to do that, we need to at least update any custom icons that are used in mainline. There are fortunately only two places in mainline that use custom icons, so it shouldn't be hard if that's the route you want to take.

**Comment by Pentarctagon** [comment]
Would that just be `add_status()` in reports.cpp, or do custom statuses get set somewhere else?

**Comment by CelticMinstrel** [comment]
They're done in Lua.

**Comment by Pentarctagon** [comment]
Alright, so that'd be related to `lua_report_generator` in game_lua_kernel?

**Comment by CelticMinstrel** [comment]
That sounds right… what exactly are you looking to do…?

**Comment by Pentarctagon** [comment]
To have this applied to custom icons I'd need to append the new IPF somewhere in `lua_report_generator`, right?

**Comment by CelticMinstrel** [comment]
> The IPF seems more like CROP_TRANSPARENT.

Both names are okay. I personally prefer `CROP_TO_FIT` but I also wouldn't mind `CROP_TRANSPARENT`. Either way, precisely what it does will be documented on the wiki.

> To have this applied to custom icons I'd need to append the new IPF somewhere in `lua_report_generator`, right?

That's a way to do it, but it doesn't seem to fit with the approach you've taken for the other status icons in C++ – you just appended the IPF to the image path for each icon, rather than generically applying it in some central case.

I think editing the Lua files would hew closest to what you did for the other icons.

By the way, originally this affected _all_ images in the theme UI, so if you're _not_ doing this in a generic way that implicitly applies to every report image (as was the case before the rendering changes), we should probably double-check that other images don't have transparency. For example, the images along the top bar, or the images under the minimap, or the editor toolbar icons.

**Comment by soliton-** [comment]
https://github.com/wesnoth/wesnoth/blob/e506c2a1ffecb18cc545ed1759ad647c9ae29e46/src/display.cpp#L3064-L3069
Can't you append the IPF to `t` here?

**Comment by Pentarctagon** [comment]
Looks like that does work, actually.

**Comment by soliton-** [comment]
I do agree that it'd be good to get away from this functionality in the long run. Better to remove the superfluous transparency in mainline from the images and expect UMC authors to add the IPF themselves if they need it.

For the latter it'd be good to log a message when the IPF actually does some work in this specific use case. And for that I guess we'd either need to give the IPF an argument it can check or make an "alias" like `CROP_TRANSPARENCY_WORKAROUND_FOR_REPORTS` that is not getting documented and which logs a message if it does crop something.

**Comment by Pentarctagon** [comment]
Transparent pixel padding seems like a really weird thing to deprecate.

**Comment by CelticMinstrel** [comment]
> Transparent pixel padding seems like a really weird thing to deprecate.

The deprecated thing would be "we crop transparency for you automatically".

**Comment by Pentarctagon** [comment]
I don't think that makes a whole lot of sense, unless there's some urgency to removing CROP_TRANSPARENT?

**Comment by CelticMinstrel** [comment]
No, why would we remove `CROP_TRANSPARENT` that was literally just added?

What we'd remove someday is the line that automatically adds it to all report images.

I think that's maybe something that's better to discuss in 1.19 though – it's not at all obvious how we'd work that kind of deprecation.

**Comment by Pentarctagon** [comment]
I mean, it's worked this way for well over a decade without the IPF. It now uses an IPF to implement the same functionality, but we're not planning on removing the IPF any time soon, so... why is there any need to stop automatically adding the IPF? We're not going to gain anything by not automatically adding the IPF.

**Comment by CelticMinstrel** [comment]
There isn't an urgent _need_ to, but there might at some point be a reason to _want_ an image that has transparent padding in the sidebar. Deprecating it would mean we can do that if we want.

**Comment by Pentarctagon** [comment]
Well, anyway, any issue if I merge this as-is if we're coming back to whether to deprecate it in 1.19?

**Comment by CelticMinstrel** [comment]
That's fine.

**Comment by soliton-** [comment]
> I think that's maybe something that's better to discuss in 1.19 though – it's not at all obvious how we'd work that kind of deprecation.

Anything wrong with what I suggested? The IPF code can output deprecation notes when it knows it's specifically used for this.

> why is there any need to stop automatically adding the IPF? We're not going to gain anything by not automatically adding the IPF.

1) It's just an odd thing to do automatically. Why not let the user decide. I have no idea why the mainline images do have the transparency at all. Are they used elsewhere where those pixels are needed?
1) As far as I understand this kind of thing is not great for performance and will fill the image cache unnecessarily. No idea how significant that impact really is. If one day IPFs are implemented as shaders perhaps it doesn't matter at all but that is presumably a very long time away.

> Well, anyway, any issue if I merge this as-is if we're coming back to whether to deprecate it in 1.19?

Nope, I just wanted to mention how I think the deprecation can be done.

**Comment by Pentarctagon** [comment]
> It's just an odd thing to do automatically. Why not let the user decide. I have no idea why the mainline images do have the transparency at all. Are they used elsewhere where those pixels are needed?

> As far as I understand this kind of thing is not great for performance and will fill the image cache unnecessarily. No idea how significant that impact really is. If one day IPFs are implemented as shaders perhaps it doesn't matter at all but that is presumably a very long time away.

This is something that could probably be searched on the add-ons server - check for `wesnoth.theme_items.unit_status` and `wesnoth.interface.game_display.unit_status`, and then check if those images have transparent pixel padding. If nobody actually has that padding in their images, then it can be removed.

Otherwise, sure it's odd, but we also gain nothing at all by removing it other than making anyone who has custom status icons with transparency need to edit them. The images are also so small that I can't imagine it makes a difference to either performance or the extra entries in the image cache.

**Comment by CelticMinstrel** [comment]
I think it means all images used in the theme are basically stored in the cache twice, even if they don't have any transparent padding.

**Comment by mesilliac** [comment]
> Otherwise, sure it's odd, but we also gain nothing relevant by removing it other than making anyone who has custom status icons with transparency need to edit them.

The reason this behaviour is detrimental is that there are plenty of valid reasons for wanting to have transparency in an image for padding. Lets say for example somebody wants to have a status icon which is similar to a centered dot, or a horizontal line, like an arrow or spear. But (i assume this is how it works from the squishing behaviour) status images are constrained to fill the height of a line. So the current behaviour removes the transparency above and below and then stretches their horizontal spear to a big smushed box.

You will never see if somebody wanted to do this because they will have just given up and changed their icon to fit the existing constraints.

**Pull request merged**
