### PR TITLE
WoF: Change Leopard race to cats

### PR DESCRIPTION
**Pull request by Gothyoba**
Given the new cats race, I think it makes more sense for them to be cats, and to not use the wolf undead variation. So I changed the race from monster to cats.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
The other option is to _replace_ it with one of the two new cats.

**Comment by gfgtdf** [comment]
whats the reason for not using the wolf undead variation ?

**Comment by Gothyoba** [comment]
Because here is acar one now which fits a lot better with a leopard.

**Comment by gfgtdf** [comment]
oh okay makes sense

**Comment by Jonathan-Kelly** [comment]
Well, this may be a bit redundant, since the Leopard is fully replaced with the new core Forest Lion in the next update for this campaign (which I am currently working on and testing).

**Comment by Gothyoba** [comment]
I'm closing this then.

**Pull request closed without merging**
