### PR TITLE
revert b98cbe31cc861cc10a326ba14c7ac0a5e7b637d8

### PR DESCRIPTION
**Pull request by GregoryLundberg**
While apparently an excellent idea, the change caused a race condition to appear when using LTO.

### CODE REVIEW

**Comment by Vultraz** [comment]
No point leaving this open, then.

**Comment by GregoryLundberg** [comment]
The C++ standard only guarantees that static initialization of an object will occur prior to the first use of that object.

This revert moved the static object to a file which has something which must be executing prior to starting the splash screen thread.

Your alternative is to create a new file, and add a call to something in that new file, probably from the top of main() before anything can fire off a thread.

**Comment by jyrkive** [comment]
Not so fast. Because the static initialization is in a function, it occurs when the function is first **called**. See https://isocpp.org/wiki/faq/ctors#static-init-order-on-first-use

The only difference in your revert is that the evaluation order of function parameters is unspecified, i.e. after the revert the compiler is no longer allowed to evaluate other parameters before the dummy display context. That appears to accelerate the creation of the display context very slightly so that the code just barely wins the race.

The problem absolutely should be fixed by *removing* the race condition, rather than slightly changing timing so that we just happen to win the race in your particular conditions.

**Comment by GregoryLundberg** [comment]
Not arguing this is the best fix. Just arguing that closing the issue is not a good idea.

I'm open to suggestions about fixing it. Maybe it is the pointer-vs-reference change. I don't know. But I spend all day yesterday bisecting to find the source of the error.

The most expedient fix is to revert the change. This is a PR, if another change works better and everyone agrees to it, that's fine.

But, remember, we would not be having this discussion if it had never been made. And we're up against ANOTHER missed commitment. To my mind, if we want to make our commitments, reverting the change which exposed the problem, and revisiting the issue after the release has tagged, is a fine solution.

As it is, though, we missed the commitment, AGAIN. So, I suppose we have plenty of time until the next deadline, or the one after that, or the one after that ...

I will spend today (which SHOULD have been after tagging) working the problem.

**Comment by jyrkive** [comment]
Only changing the timing just isn't even a fix. In your case it happens to hide the issue with LTO builds, but at the same time it can also *trigger* the issue for someone else with, say, different hardware.

**Comment by GregoryLundberg** [comment]
Actually, I'm more concerned about different compilers, or future changes to current compilers.

Tell you what, since it's an LTO-only issue, how about we declare it a compiler bug. That way we can delay shipping 1.13.11 until the gcc and clang teams get around to fixing it.

**Comment by GregoryLundberg** [comment]
Finally got a debug build to crash.

This is nothing more than initialization sequencing.

I started by eliminating unneeded work. So no function, just a static const object. And BOOM! there's the crash .. we're trying to write a log message before the log domain object has been initialized.

So, either we have to statically initialize the log objects BEFORE we statically initialize the dummy display, or we need to avoid logging by checking for nullptr to avoid the segfault.

Alternatively, we could delay initialization of a static (but non-const) object pointer until we actually need the dummy display context. That WOULD cause a race condition so we'll need to make sure the initialization is atomic (std::swap might do).

Alternatively, we could forget the shared common dummy display context and create a new one every time we need one.

I'm going to start by trying the second alternative and wrap the initialization is a lock so it's "atomic" as far as our code is concerned. I think there's a Boost for that; is so, that should handle platform differences.  :crossed_fingers:

**Comment by Vultraz** [comment]
I seem to recall we had this problem with static init order of log objects before at some point... hmm...

**Comment by Vultraz** [comment]
Closing again since progress has been made and we've been discussing alternate solutions, such as disabling the tests for the two dialogs that use the dummy display context.

**Comment by CelticMinstrel** [comment]
For the record I think it's better not to disable the tests except maybe as a temporary measure.

**Pull request closed without merging**
