### PR TITLE
LoW bigmap localization fix and folder regroup

### PR DESCRIPTION
**Pull request by amakriLexa04**
I noticed that map localization in LoW doesn't work. As it turned out, this is because main map image is in .png format, but all overlays are in .webp format. 

So I fixed this and also:
— Created separate folder for maps and renamed files to match the format of other campaigns.
— Updated bigmap.cfg to point to the new location of bigmap.
— Updated copyrights.csv.

### CODE REVIEW

**Comment by Wedge009** [comment]
Never noticed the localisation because I don't use any of the languages provided for this campaign. I'm not really sure how it works, but looking at the changes as they stand, it makes sense to me.

**Comment by amakriLexa04** [comment]
I don't really understand how it works either, but the fact is that the main image and overlay should be in the same format. I had a similar problem with AOI, where bigmap was in .png, and my overlay was in .webp. And I wondered for a long time why it was not displayed in the game

**Comment by Vultraz** [comment]
I'm working on the area of the code that handles the translation overlays, and it seems that though it will check both `png` and `webp` endings for the base, it will only look for an overlay with an extension matching the base.

**Comment by amakriLexa04** [comment]
> I'm working on the area of the code that handles the translation overlays, and it seems that though it will check both png and webp endings for the base, it will only look for an overlay with an extension matching the base.

Wouldn't it be better to make it search only by file name, ignoring its type?

Hmmm, github shows me in this PR that 'This branch has conflicts that must be resolved'. But I don't understand what's wrong here, I don't think there are really any problems with copyrights.csv

**Comment by Vultraz** [comment]
It just means it can’t automatically merge your changes with some other recent changes made to that file. Could you rebase and force push to your branch manually? That will fix it and I can merge this.

**Comment by amakriLexa04** [comment]
Well, I don't know how to do it yet, but I will try

**Comment by amakriLexa04** [comment]
Hmmm, it looks like I did something wrong

**Comment by amakriLexa04** [comment]
I'm so sorry for all this mess....

**Comment by Wedge009** [comment]
Since you're a Windows user, I'll point out that I find GUI tools such as [TortoiseGit](https://tortoisegit.org/) quite handy. Popular editors these days often include GUI git functionality within them too.

Re-base your branch on to the current origin/master and you can also go through the previous commits and edit or squash them along the way.

If all else fails, you can keep your current branch, create a new one against master, and copy your work on to that.

**Comment by amakriLexa04** [comment]
Thank you for this helpful information, I will download this program then. I'm still new to PRs, branches and git in general, so unfortunately _this_ happens.

Well, anyway, github has no complaints about the copyrights.csv now, so everything should be fine

**Comment by Wedge009** [comment]
It was a learning process for me too.

@Vultraz Looks like this can be merged if squashed.

**Comment by Pentarctagon** [comment]
The "Squash and merge" option is also still available here on github.

**Comment by Wedge009** [comment]
> The "Squash and merge" option is also still available here on github.

Sorry, that's what I was referring to. Done now, anyway.

**Pull request merged**
