### PR TITLE
Ability to shrink composite widgets below the default size

### PR DESCRIPTION
**Pull request by jyrkive**
Composite widgets, i.e. widgets which inherit container_base, such as the unit preview pane, can have an explicit minimum size set in their definition. The widget will request either that size or however much space the child widgets want, whichever is higher.

If an explicit minimum size is set, the composite widget can't shrink below that size even if there isn't enough space. That limitation has annoyed at least @Vultraz : he wants to specify a minimum size for the unit preview pane but still allow it to shrink below that size before scrollbars show up.

This commit implements ability for composite widgets to shrink below the explicit minimum size, if set. I tested it locally: I set the minimum width of unit preview pane to 1000 pixels by editing [this line](https://github.com/wesnoth/wesnoth/blob/f5e0d38f02e2eb21529b4e5babfccb80b1e7680c/data/gui/widget/unit_preview_pane.cfg#L386). After that, the pane took all available space up to 1000 pixels, but if that much space wasn't available, it shrunk instead of causing a scrollbar to appear.

### CODE REVIEW

**Comment by Vultraz** [comment]
Does this have any affect on default_width/default_height? TBH, the behavior describes almost sounds like that one would except of those keys, not min_*.

**Comment by jyrkive** [comment]
`container_base` ignores the `default_width` and `default_height` keys. This pull request (at least in its current state) doesn't have any effect on them.

**Comment by AI0867** [comment]
Semantically speaking, it sounds like you're making the 'minimum' not be the minimum because the 'default' does nothing.

**Comment by jyrkive** [comment]
@AI0867 @Vultraz Would you prefer if I changed `container_base` to query the default size instead, then? I didn't initially do that because the risk of regressions is higher that way (as there may well be composite widgets which currently have a minimum size specified but not a default size: such widgets would suddenly become smaller).

**Comment by Vultraz** [comment]
I think it's worth a shot to see how it works, since this behavior definitely does make more sense with the default_* keys.

**Comment by jyrkive** [comment]
Done.

I quickly played around with a local build and didn't see any obvious problems from the change.

**Comment by jyrkive** [comment]
This pull request didn't receive any additional feedback. Merged.

**Pull request merged**
