### PR TITLE
Make mushrooms hide base terrain

### PR DESCRIPTION
**Pull request by doofus-01**
Visual change to mushroom forest overlay that hides the base terrain
This is to address this:
https://forums.wesnoth.org/viewtopic.php?f=6&t=49996

Probably better to make two terrains in 1.15, this PR is pretty much a compromise working in constraints of no API changes.

### CODE REVIEW

**Comment by stevecotton** [comment]
The transitions for `Hh^Uf` seem to still be using hill transitions (reproducible on Caves of the Basilisk).

**Comment by doofus-01** [comment]
Thanks, I think it's fixed now.  The hex next to that one shows how the grass, and some other terrains, sometimes still lay their transition over the mushroom base image.  This is not finished...

**Comment by CelticMinstrel** [comment]
Still opposed to this idea; the terrain itself is fine for a new 1.15 terrain (with an overlay and non-overlay version), but here I just don't like that it's an overlay that's not really an overlay.

Is the new base terrain here a separate graphic from the original mushroom overlay? For 1.15 that base terrain could be the new addition, leaving the existing mushrooms as they are, so that existing cases of `*^Uf` in MP scenarios get replaced by `Uf^Uf` to produce the effect you've shown here, but then the same base terrain can also be combined with other overlays.

Also, I hear that 1.15.0 will be released soon, so will the mushroom stuff be put into 1.15 before then? Or will it have to wait for 1.15.1?

**Comment by jostephd** [comment]
> Still opposed to this idea; the terrain itself is fine for a new 1.15 terrain (with an overlay and non-overlay version), but here I just don't like that it's an overlay that's not really an overlay.

That ship has sailed. In 1.14, `^Uf` **is** an overlay that isn't an overlay. Let's think how to move forward from here. Changing the graphics is an option, deprecating the `^Uf` overlay is an option, adding new terrain codes an overlays is an option, but saying we shouldn't have spilled that milk is not productive.

**Comment by jostephd** [comment]
Remember this PR is for 1.14 only.

**Comment by CelticMinstrel** [comment]
> That ship has sailed. In 1.14, `^Uf` is an overlay that isn't an overlay.

Uh, what? It's clearly an overlay prior to this PR - you can see the base terrain through the mushrooms, after all.

**Comment by doofus-01** [comment]
No.  That's the problem, it's a graphical overlay, but a data base terrain.  That's deceptive, and is a bug.
Screenshot_mush-info

**Comment by soliton-** [comment]
Also this PR changes no terrain properties it just changes the graphics. It just makes it clearer to the player that this terrain works only like Mushroom Grove.

Overlay terrains can decide their properties via the alias keys. If they do not contain the special value `_bas` it doesn't matter what the base terrain is.

**Comment by doofus-01** [comment]
I'm going to merge this now because it's better not left to the very last minute.  If anyone has a problem with the images, I'm open to suggestions.

**Comment by CelticMinstrel** [comment]
Alright, guess I'll build a custom terrain for my campaign then...

**Comment by jostephd** [comment]
Created #4213 for creating the new terrain code and #4214 for forward-porting this (which I assume will be needed for backward compatibility).

**Comment by jostephd** [comment]
Reverted in fb4fd54427569d4afa5ffb349eef492955e9fe1f.

**Comment by CelticMinstrel** [comment]
Well that sure was a journey.

**Comment by doofus-01** [comment]
Indeed.  One less thing to worry about though, for me at least.

**Comment by CelticMinstrel** [comment]
However, this PR is still mentioned in the changelog. It needs to be removed from there.

**Pull request merged**
