### PR TITLE
Typo fixes

### PR DESCRIPTION
**Pull request by jostephd**

### CODE REVIEW

**Comment by Wedge009** [comment]
Some of the grammatical oddities may have been intentional from the author, but I don't object to these changes. I appreciate the capitalisation of proper nouns. The only thing I couldn't check was the MP scenario Caves of the Basilisk: going to the unit description shows the generic text - I didn't see the text from this cfg file. Not sure if something is broken or if I'm checking in the wrong place.

Overall I'm happy for this to be merged, notwithstanding any potential objections from others. I note this is for master anyway.

**Comment by jostephd** [comment]
Thanks for reviewing.

In Caves of the Basilisk, the texts changed show as tooltips when you select the petrified unit and mouseover its name in the sidebar.

I hoped to backport this to 1.14 before string freeze for 1.14.7 starts, assuming reviews finish before then.

**Comment by Wedge009** [comment]
#3906 reminded me of https://wiki.wesnoth.org/SpellingMistakes - I note you've covered two of the three remaining items (as at time of writing), I don't have a strong opinion on HttT S20b either way, but do you think it's worth including that one too?

Thanks for pointing out where the Caves of the Basilisk texts are shown. I agree with the new line spacing added there.

**Comment by jostephd** [comment]
> #3906 reminded me of https://wiki.wesnoth.org/SpellingMistakes - I note you've covered two of the three remaining items (as at time of writing), I don't have a strong opinion on HttT S20b either way, but do you think it's worth including that one too?

The wiki says:

> S20b: "Stand fast, we will send reinforcements." - change "," to ";" and "will" to "shall" 

The PR already changes the comma to an exclamation mark. I'm not sure about will/shall; which one would be more consistent with Kalenz's style?

**Comment by Wedge009** [comment]
Which PR? This one? I'm sorry I can't see it. :/

As for shall vs will, I've been taught to use shall for first person and I understand that's the traditional rule, but in contemporary Americanised English most people seem to use will (especially in colloquial contexts). Given Wesnoth seems to aim for an older style of speaking/writing, I'd go with shall.

**Comment by Wedge009** [comment]
I can see the exclamation mark now. Thanks.

**Comment by jostephd** [comment]
The exclamation mark had already been added in master before this PR.

As to will/shall, there's more to it than just a question of person, but for now, I've gone ahead and made the change.

**Pull request merged**
