### PR TITLE
Made flatpak ci job upload bundle too

### PR DESCRIPTION
**Pull request by loonycyborg**
This adds new CI artifact containing file wesnoth.flatpak. It can be installed and run like this:
`flatpak --user install wesnoth.flatpak`
`flatpak run --branch=ci org.wesnoth.Wesnoth`
After done with with testing it can be removed to save disk space:
`flatpak uninstall org.wesnoth.Wesnoth` and choose install from branch `ci` if there are other installs.

### CODE REVIEW

**Review by soliton- — APPROVED** [review]
Looks good to me and works. Just a little weird that the version says "Modified" instead of "Clean".

**Comment by soliton-** [comment]
jq outputs to a new file.

**Comment by loonycyborg** [comment]
Probably that's something about the way checkout is made then.

**Comment by soliton-** [comment]
Yeah, it looks like the check does `git status --untracked-files=normal --porcelain` and Clean means no output. So it might be the new json file.

**Comment by soliton-** [comment]
So we could put the file elsewhere or pick one that is in .gitignore. Is the filename important?

**Pull request merged**
