### PR TITLE
Fix some minor bugs in WC campaign

### PR DESCRIPTION
**Pull request by wuxiangjinxing**

### CODE REVIEW

**Comment by Pentarctagon** [comment]
I'm curious how that second commit fixes only one map getting generated?

**Comment by CelticMinstrel** [comment]
What's the `[+]` and `[-]` about?

**Comment by wuxiangjinxing** [comment]
I don’t know the reason exactly.  But without this fix, after beating map 1 the game automatically exits to the main menu.  Anyway, it is not reasonable to call the 3P scenario module after 4P is executed. 从 Windows 版邮件发送 发件人: Pentarctagon发送时间: Sunday, February 20, 2022 9:40 PM收件人: wesnoth/wesnoth抄送: wuxiangjinxing; Author主题: Re: [wesnoth/wesnoth] Fix some minor bugs in WC campaign (PR #6538) I'm curious how that second commit fixes only one map getting generated?—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by wuxiangjinxing** [comment]
That’s just personal habit.  [+] means I introduced some new contents / functions / modifications and [-] means I fixed some bugs. 从 Windows 版邮件发送 发件人: Celtic Minstrel发送时间: Sunday, February 20, 2022 10:38 PM收件人: wesnoth/wesnoth抄送: wuxiangjinxing; Author主题: Re: [wesnoth/wesnoth] Fix some minor bugs in WC campaign (PR #6538) What's the [+] and [-] about?—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Pentarctagon** [comment]
So I guess @sevu - is the 4 player implementation for WC functional?

**Comment by knyghtmare** [comment]
Comments regarding 1st commit:
Has it been tested to see if it is working properly? 

Comments regarding 2nd commit:
The 3p scenario was included with the 4p WC due to "fallback to 3p mode if one of the leader dies." as far as I can recall. Also, if you have DEBUG mode enabled, finishing any WC scenario lands you to the main menu, so the 3p scenario isn't doing anything wrong being there.

also, 4p WC had some problems as I stated in its PR back in December.

**Comment by wuxiangjinxing** [comment]
*Has it been tested to see if it is working properly?*
I tested it by myself and it works fine.  The use of function
create_random_function() is to fill hero list, so it shall also be called
if the faction has [world_conquest_data] but has no hero list being defined.

*if you have DEBUG mode enabled, finishing any WC scenario lands you to the
main menu*
Based on my testing, even with debug mode enabled and finishing every
scenario by :n command, the campaign progresses to the next scenario
normally (after making my commit).  However, without this commit, when
hitting 'end scenario' button after defeating the enemy leader the game
just returns to the main menu.

Tahsin Jahin Khalid ***@***.***> 于2022年2月21日周一 08:32写道：

**Comment by Pentarctagon** [comment]
@knyghtmare should this PR be merged or closed?

**Comment by knyghtmare** [comment]
> @knyghtmare should this PR be merged or closed?

Need to test this PR once more because I am rather curious as well on the second commit's outcome.

**Comment by CelticMinstrel** [comment]
> What's the `[+]` and `[-]` about?

I would also like an answer to this question. Why are these symbols at the beginning of your commit messages?

**Comment by knyghtmare** [comment]
> @knyghtmare should this PR be merged or closed?

image

Seems my hunch was correct. The second commit does break the _4p-World Conquest_.

**Pull request closed without merging**
