### PR TITLE
UI: Prefix tooltips with what kind of information they show

### PR DESCRIPTION
**Pull request by jostephd**
Having these prefixes is consistent with all other tooltips in the sidebar.

Also add a tooltip to vision because the label is truncated and there is no other way for the player to get the vision value.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Looking at this makes me want to add jamming to the vision tooltip, too (if it's non-zero).

**Comment by jostephd** [comment]
I tried to add that:

```
diff --git a/src/reports.cpp b/src/reports.cpp
index 2a48fc5e7c4..d8a12dfe72b 100644
--- a/src/reports.cpp
+++ b/src/reports.cpp
@@ -571,6 +571,11 @@ static config unit_vision(const unit* u)
 		str << _("vision: ") << u->vision();
 		tooltip << _("Vision: ") << u->vision();
 	}
+	if (u->jamming() != 0) {
+		if (str.tellp() == 0)
+			str << _("jamming: ") << u->jamming();
+		tooltip << _("Jamming: ") << u->jamming();
+	}
 	return text_report(str.str(), tooltip.str());
 }
 REPORT_GENERATOR(unit_vision, rc)
```

But in `wesnoth -t` it had no effect. The scenario has two units with `[unit] jamming=5` set, an Outrider and an Orcish Archer, but in `:inspect` both of them show with jamming=0, and `:unit jamming=5` doesn't change that.

**Comment by jostephd** [comment]
I'll add the newline and remove the trailing spaces.

@CelticMinstrel As I said, `:inspect` shows `jamming=0`. The wiki doesn't document a `jamming` key in [unit] or [unit_type], only in [effect]. I think the test scenario may be a syntax that isn't supported. I will investigate.

**Comment by CelticMinstrel** [comment]
I looked into it and it seems that it has only ever been supported in `[unit_type]`, not in `[unit]`.

https://github.com/wesnoth/wesnoth/commit/fbbfadfc6b8cc6ba1323a5fd7b7908f0c98e1d25#diff-5c3015c1ec6963a9da9a75fff346f390R788

I think this is an oversight that should be fixed; however, I guess that would need to be on master only.

**Comment by jostephd** [comment]
Thanks. I can add that to my todo list after the newline and whitespace.

Before I forget, using `:kill` on a jamming unit (Mages) doesn't redraw the vision of the jammed unit (Konrad). Here is a test:

```
diff --git a/data/campaigns/Heir_To_The_Throne/scenarios/01_The_Elves_Besieged.cfg b/data/campaigns/Heir_To_The_Throne/scenarios/01_The_Elves_Besieged.cfg
index 805f25cc679..293de472be0 100644
--- a/data/campaigns/Heir_To_The_Throne/scenarios/01_The_Elves_Besieged.cfg
+++ b/data/campaigns/Heir_To_The_Throne/scenarios/01_The_Elves_Besieged.cfg
@@ -49,6 +49,9 @@
                 carryover_percentage=40
             [/gold_carryover]
         [/objectives]
+        {UNIT 2 Mage 21 21 (vision=1)}
+        {UNIT 2 Mage 22 21 (vision=1)}
+        {UNIT 2 Mage 23 21 (vision=1)}
     [/event]
 
     {HTTT_INTRO}
@@ -68,6 +71,7 @@
     [side]
         type=Fighter
         id=Konrad
+        fog,shroud=yes,yes
         name= _"Konrad"
         unrenamable=yes
         profile=portraits/konrad-elvish.png
diff --git a/data/core/units/humans/Mage.cfg b/data/core/units/humans/Mage.cfg
index e9ea2aff94d..9ce4f57edfc 100644
--- a/data/core/units/humans/Mage.cfg
+++ b/data/core/units/humans/Mage.cfg
@@ -13,6 +13,7 @@
     experience=54
     level=1
     alignment=lawful
+    jamming=1
     advances_to=White Mage,Red Mage
     cost=20
     usage=mixed fighter
```

**Comment by CelticMinstrel** [comment]
Just for the record, fixing jamming is obviously out of scope for this PR. Maybe that was obvious but I like to make sure the obvious is explicitly stated anyway, just in case it actually _wasn't_ obvious to someone.

**Comment by jostephd** [comment]
I've pushed the newline and whitespace fixes. I fixed only the newly-added strings since I didn't want to break translations.

@CelticMinstrel It was clear to me, but thanks for making it explicit. I've submitted #3330 for the `[unit] jamming=5` support. Shall I also file a bug about `:kill` not redrawing?

**Comment by jostephd** [comment]
There are merge conflicts, 1.14.6 string freeze starts soon, and this isn't terribly urgent. Postponed to 1.14.7.

**Comment by jostephd** [comment]
Merged in 97ca22e94bf2c4d5b35ff005ffb5c16f5862a5cc ce75665ae56fc4dc89ed446754d782f4f5e6f6bd.

**Pull request closed without merging**
