### PR TITLE
Redesign force cth macro

### PR DESCRIPTION
**Pull request by newfrenchy83**
Is second version of https://github.com/wesnoth/wesnoth/pull/3704

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I approve of this change.

**Comment by gfgtdf** [comment]
unlike the old implementation this does not remove the the other [change_to_hit] specials that the unit currently has, so one would need to test (with multiple values) whether it still works if the unit has for example a marksman attack special. Even if not, this could probably be easily be solved by just making the object also remove other change_to_hit specials though.

**Comment by GregoryLundberg** [comment]
Provided those others are discoverable. Can we filter based upon whether the object modifies the chance-to-hit? (Sounds like a general problem not specific to chance-to-hit, BTW.)

**Comment by gfgtdf** [comment]
> Provided those others are discoverable. Can we filter based upon whether the object modifies the chance-to-hit? (Sounds like a general problem not specific to chance-to-hit, BTW.)

Not sure what you mean here, why would you want to filter other objects? chance_to_hit is a weponspecial/ability and unrelated to whether it was added via object or part of the unit definition.

**Comment by newfrenchy83** [comment]
Cth ability compute after cth special and like cumulative=no value of ability remplace special value.

**Comment by newfrenchy83** [comment]
I hope fixed all indentation.

**Comment by newfrenchy83** [comment]
i pull test case in scenarion test and this time it musn't had bugs

**Comment by CelticMinstrel** [comment]
...whoops. forgot to fix the author information to newfrenchy due to using `git merge --squash`. Oh well!

**Pull request closed without merging**
