### PR TITLE
EI S12: prevent ogres from saying the final goodbye

### LINKED ISSUE #8746: EI: In S12 Evacuation, Prefer Non-Ogre Veteran Speaker For Units Left Behind
### Describe the desired feature

If Evacuation is completed by destroying the bridge and units are left behind, the game places a batch of doomed recalls and selects an L2+ unit to speak a line of dialogue.

Ogres have a distinct speaking style and the line is much more eloquent and formal than the Ogre-specfic dialogue lines.

It doesn't make sense to make alternate lines for all dialogue an Ogre could speak but:
1) This is part of a story beat
2) It is likely that a non-Ogre veteran will be available to speak instead

Alternately, Ogres could be forbidden from saying this line outright.
Screenshot 2024-04-02 00 54 54

Other Notes:
Is this line intended for units that have been left behind?
The line "From here, we must ride swift..." seems a little off because the speaker will soon be dead. It should probably be "you" instead of "we" or the "From here, we must" should be deleted (-> "Ride swift...")

### PR DESCRIPTION
**Pull request by Dalas121**
Fixes #8746

### CODE REVIEW

**Comment by soliton-** [comment]
The po hint below should be updated as well.

**Comment by Dalas121** [comment]
Fixed

**Comment by Wedge009** [comment]
Back-port to 1.18?

**Comment by Dalas121** [comment]
Missed your message; thanks for fixing this

**Comment by Wedge009** [comment]
Only did it just then... XD

**Comment by Dalas121** [comment]
Yeah I saw the message in the discord development channel 😂

**Comment by CelticMinstrel** [comment]
Wait, do you have no female units in EI? Because that tag is missing a `female_message`.

**Comment by Dalas121** [comment]
Ah.

That could be a bit of a problem; I didn't realize I needed `female_message` in cases where the speaker's gender could be either male or female.

At the moment, it looks like there's exactly 4 instances of `female_message` in the entire EI campaign, all of which must have been added by Yumi. I guess I'll need to go through the campaign and add `female_message` in everywhere?

**Comment by CelticMinstrel** [comment]
I don't know for sure that it's needed in absolutely every place where the gender is unknown, but it's my opinion that it's generally safest to provide it. I know for certain that first-person pronouns are one thing that can be gender-dependent in some languages, so at minimum any sentence that contains "me" or "I" definitely needs a `female_message`, and probably "we" and "us" as well, though I'm less sure of those ones. Another example I know of is that the word for "brother" or "sister" can depend on the gender of the speaker.

**Pull request merged**
