### PR TITLE
Fix typo: "with heavy loses" -> "with heavy losses"

### PR DESCRIPTION
**Pull request by severin**
This is a simple translation fix

### CODE REVIEW

**Comment by Wedge009** [comment]
Thanks for this. However there's no need to update the `po` files as they are generated from the `cfg` text so only that change is necessary.

If no-one else sees fit to handle it I can take care of it - including the back-port - once the 1.16.2 string freeze is over (I'm keeping track of a number of similar master commits that will need to be back-ported too).

**Comment by severin** [comment]
Hi @Wedge009, thanks for your comment! I changed the PR to only include the *cfg*... Let me know if it is ok like that or if you prefer some other way of reporting/fixing spelling issues (the only thing I found in the wiki now is to open a Github Issue with typos, but I think a PR is easier).

---

Also, if you don't mind answering the following questions:

- I find it strange that generated artifacts (in this case the *po* files) are checked into source control. What is the reason for that?
- And if there are generated files in the repo, why shouldn't they be kept up-to-date when their "input" changes?

Sorry if these questions are stupid, feel free to point me to any documentation that might exist on this topic 🙂 

Have a nice day!

**Comment by CelticMinstrel** [comment]
@Wedge009 was incorrect – the _po_ files are **not** generated files. There are _pot_ files checked in too, which are generated; I'm not sure what argument there is for not ensuring they're always up-to-date, other than the fact that it requires special tools that contributors aren't expected to have installed.

**Comment by Wedge009** [comment]
Thank you for the correction. My point was that in making corrections we only need to update the source `cfg` files. `po` files are updated by the translators and committed by @ivanovic separately. To date, I'm still hazy on why the process is done this way, but it's what I've been following.

**Comment by severin** [comment]
Thanks for the explanations!

**Comment by ivanovic** [comment]
> Thank you for the correction. My point was that in making corrections we only need to update the source `cfg` files. `po` files are updated by the translators and committed by @ivanovic separately. To date, I'm still hazy on why the process is done this way, but it's what I've been following.

So what you should do is the following:
1) fix the typo in the cfg file
2) add the string change (with a little bit of content to make it unique) to utils/pofix.py
3) apply utils/pofix.py to po/wesnoth*/*.po* (yes, to all po files as well as the pot files

This way the translators should not get any fuzzy strings yet the translation should automatically work. If the translators send me files based on the old version, it will automatically be fixed since I run pofix on every translation files before merging against the lastest pot files.

**Pull request merged**
