### PR TITLE
Trigger unit_hits, unit_misses events, re #7782

### PR DESCRIPTION
**Pull request by ProditorMagnus**
If there are no strong objections about design I will add some tests too.

### CODE REVIEW

**Comment by ProditorMagnus** [comment]
Actually these lines shouldnt doesnt solve the problem about reversed units.

**Comment by ProditorMagnus** [comment]
Dont think I know enough codebase to solve it without adding additional parameter to fire_event()

**Comment by ProditorMagnus** [comment]
Java style solution

**Comment by ProditorMagnus** [comment]
Current test does not validate that unit_hits is later than attacker_hits, but I do not consider it important requirement either

**Review by stevecotton — APPROVED** [review]

**Comment by stevecotton** [comment]
A changelog entry would be good too, but not essential.

**Comment by ProditorMagnus** [comment]
https://wiki.wesnoth.org/index.php?title=EventWML&diff=prev&oldid=73178

**Comment by ProditorMagnus** [comment]
If you want changelog line, you can use
Added new events "unit hits/misses" to simplify creating events that use attacker+defender hits/misses

**Comment by stevecotton** [comment]
On the Wiki page, I assume they should be in the "multiplayer safety" list too?

**Comment by ProditorMagnus** [comment]
Probably pre attack too.

**Pull request merged**
