### PR TITLE
add tooltip to [unit_vision]

### LINKED ISSUE #7636: Improve vision and jamming tooltip
### Describe the desired feature

If a unit vision is different from movement points or have jamming points, apparently this appears in the UI (vis...) Hovering the mouse over shows nothing.

imagen

Replacing "Vision:" with a empty space on my language translation, shows a number.

imagen

So it looks like it uses the status UI to put
`Vision: X`
Or
`Jamming: X`

https://github.com/wesnoth/wesnoth/blob/454d816c86e1669cfcacb56a744aae9f2f37321e/src/reports.cpp#L643

But there is no space for it.
It must be some old code from a different UI than the current one.
I suggest doing something like (JP VP =Jamming or Vision points)
```
VP/JP
X/X
```
It should be a very simple change to the code, and it improves an unusable part of the current UI.

### PR DESCRIPTION
**Pull request by ProditorMagnus**
closes #7636
re #6021
re #5575

### CODE REVIEW

**Comment by ProditorMagnus** [comment]
for 1.18 too

**Comment by CelticMinstrel** [comment]
I'm confused. How does this add a tooltip?

**Comment by ProditorMagnus** [comment]
no idea, but it does

**Review by Vultraz — APPROVED** [review]
I have no idea why this would work, but if it works, I have no objections.

**Pull request merged**
