### PR TITLE
Move Cry from Elensefar to Core

### PR DESCRIPTION
**Pull request by Gothyoba**
This music would be useful in core. I don't have to change any WML as I'm not actually changing any playlists. It's still specific to EI. The difference here is UMC creators can more easily use them without copying unnecessary files.

Edit: Failed copyright checks. Is music still using copyrights.csv?

Eidt 2: Looks like it is. I thought it was replaced with a metadata system.

### CODE REVIEW

**Comment by Dalas121** [comment]
`cry_from_elensefar.ogg` would be nice to have in core. A strong song, originally written for Wesnoth, and fits the theme well.

`journeys_end_faststart.ogg` is the default `journeys_end.ogg`, but with some seconds of silence at the beginning removed. I don't think there's any benefit to moving it.

I'd prefer to keep `heavens-remix.ogg` as an EI-exclusive. The style is a little unconventional for core, and I think it's good for certain campaigns to have unique tracks, helping to set them aside - this one is particularly recognizable.

**Comment by Gothyoba** [comment]
I will make the necessary changes when I have more time (tomorrow probably), but I just want to say I disagree with your choice not to add heavens-remix to core. None of these songs are being added outside of EI. Adding them to the folder doesn’t add them to the default/full music playlist. My reasoning here is to allow UMC to use them without compyig, and UMC (e.g. kameramen’s TDH revision) are already using heavens-remix. So imo adding them sould be helpful to prevent unnecessarily copying files.

btw would you also like cry for elensefar to be added to the default/full music playlists to be heard outside of EI?

**Comment by Gothyoba** [comment]
I decided to keep it an EI exclusive. This should probably be ready to merge once the CI Checks pass.

**Comment by CelticMinstrel** [comment]
> `journeys_end_faststart.ogg` is the default `journeys_end.ogg`, but with some seconds of silence at the beginning removed. I don't think there's any benefit to having it in core.

This can just be deleted if #1717 is implemented.

**Comment by Wedge009** [comment]
> `cry_from_elensefar.ogg` would be nice to have in core. A strong song, originally written for Wesnoth, and fits the theme well.
> 
> I'd prefer to keep `heavens-remix.ogg` as an EI-exclusive. The style is a little unconventional for core, and I think it's good for campaigns to have unique tracks, helping them feel different from others - this track is particularly recognizable.

It's interesting that you took this opinion because I thought I had the opposite opinion at first. But listening to them again, I think it's the first 20 seconds of Cry from Elensefar that I find so jarring, compared to the existing Wesnoth music - the rest of the track does seem closer to the Wesnoth music style than I initially thought. The opening drums for Heavens sounded more fitting for Wesnoth to me, but then it does go in quite a different direction from 26 seconds onwards with the strings.

I think it's because they're _both_ so different to what I'm used to hearing from Wesnoth that I found them a bit distracting when playing EI in 1.18. But on the other hand, I suppose the music needs to be diversified at some point so the player can be accustomed to hearing different styles and composers.

**Comment by Wedge009** [comment]
I was just expressing my opinion/concern that the EI music pieces don't fit in the current schedule of core music, however, I don't object to this being merged if others wish it.

**Review by knyghtmare — APPROVED** [review]

**Comment by Pentarctagon** [comment]
Merging then.

**Pull request merged**
