### PR TITLE
fix leadership animation played when weapon don't matche [filter_weapon]

### PR DESCRIPTION
**Pull request by newfrenchy83**
if a unit under leadership use a weapon don't matched with [leadership] [filter_(second_)weapon], then leader_anim of leader is played, or the attack not helped in that case, it musn't be like that.

### CODE REVIEW

**Comment by newfrenchy83** [comment]
@gfgtdf could you review this PR, please?

**Comment by gfgtdf** [comment]
so in which way does the function `int under_leadership` behave differnt now?

**Comment by newfrenchy83** [comment]
int under leadership continues to filter the attacks corresponding to the filter filter_ (second_) weapon, because implemented as at the origin, the difference concerns the filtering for leading_anim, henceforth, if the attack does not correspond to the filter, the animation will not be  not played any more than the attack will be improved.

**Comment by newfrenchy83** [comment]
@gfgtdf don't forget this PR, please!

**Comment by gfgtdf** [comment]
> int under leadership continues to filter the attacks corresponding to the filter filter_ (second_) weapon, because implemented as at the origin, the difference concerns the filtering for leading_anim, henceforth, if the attack does not correspond to the filter, the animation will not be not played any more than the attack will be improved.


Sry but i still don't really understand maybe  you can give an explicit  example where under_leadreship now returns a different value than before?

**Comment by newfrenchy83** [comment]
@gfgtdf currently, when filter_weapon is used in in leadership, only the attacks corresponding to the filter are taken into account, however when an attack not corresponding is used, the leader animation is still played.

To solve this problem, ability_affect_weapon is called directly from the get_abilities_weapons function similar to get_abilities. By replacing getabilities by get_abilities_weapons in int underleadership, I also simplify the writing of the code of this function, without altering the calculation of the value, and in udisplay unit_attack the filtering obtained allows to call leading_anim only when the filtered attack is used.

Here is an example to illustrate my explanation,

We have two mages, one of level 1 and his master who has the capacity to improve the efficiency of the magic attack of his student in combat, in this case, he raises his stick to (leading_anim) help, but when the student fights without magic, the master does not react logically, except that in the current coding, he would raise his stick so even his student (or even another type of fighter) does not use magic, while 'with this PR, he will only do so when he actually helps his student with magic with the same efficiency.

**Comment by gfgtdf** [comment]
> By replacing getabilities by get_abilities_weapons in int underleadership, I also simplify the writing of the code of this function, without altering the calculation of the value

So underleadership still return exactly the same value as before? but this means you could simplify `get_abilities_weapons` by simply doing what `under_leadership` did before instead of copying the whole get_ability function. Doesn't it?

**Comment by newfrenchy83** [comment]
i will try that.

**Comment by newfrenchy83** [comment]
@gfgtdf 

> 
> 

> So underleadership still return exactly the same value as before? but this means you could simplify `get_abilities_weapons` by simply doing what `under_leadership` did before instead of copying the whole get_ability function. Doesn't it?

it is done

**Pull request merged**
