### PR TITLE
 revert simplify cpp code in abilitie.cpp fix UtBS - Segfault in The Morning After bug,engine high priority

### PR DESCRIPTION
**Pull request by newfrenchy83**
it is a try to fix https://github.com/wesnoth/wesnoth/issues/4862

### CODE REVIEW

**Comment by gfgtdf** [comment]
Hmm i feel like there must a be a shorter solution, that doesn't increase  the size of this file by 200.

**Comment by newfrenchy83** [comment]
@gfgtdf could you merge this PR and fix the bugs what i introduce with simplification of cpp code in abilities.cpp?

**Comment by newfrenchy83** [comment]
> 
> 
> Hmm i feel like there must a be a shorter solution, that doesn't increase the size of this file by 200.

@gfgtdf i had placed the old code for fix the bugs instead, and i wait the merging for pull repair of https://github.com/wesnoth/wesnoth/pull/4856, i has forgetes what the instruction or exit if !other_attack_ was necassary in weapon special, but for me, this condition is a problem for abilities like weapon(abilitie 'formation' in Utbs).

**Comment by gfgtdf** [comment]
Im an wondering: what is te expected outcome in that case anyways? I mean if the defender has for example a [chance_to_hit] apply_to= opponent ability, should it also activate when the definer doesn't use a weapon in the combat?

**Comment by newfrenchy83** [comment]
Yes, that's why I put the old code in this PR, with the use of special_active it only attacks of the same scope as that used by the training user would have been affected.

**Comment by newfrenchy83** [comment]
@gfgtdf Of course, it only works between a fight between the possessor of the 'training' ability and his opponent, if the fight takes place between two units without this ability even if a third unit is adjacent, the cth will not be changed.

**Comment by gfgtdf** [comment]
> @gfgtdf Of course, it only works between a fight between the possessor of the 'training' ability and his opponent, if the fight takes place between two units without this ability even if a third unit is adjacent, the cth will not be changed.

This wasn't my question, my question was if the defender has the [chance_to_hit] in [abilities] with apply_to= opponent, but the defender doesnt use a wepon to counterattack, will the [chance_to_hit] still apply to the defenders weapon?

**Comment by gfgtdf** [comment]
I madea an alternative fix which does less changes https://github.com/gfgtdf/wesnoth/commit/d3ad23f5f8198661271ea2dbc8c716387a694ac1 i still have to test it, but if its works ill probably use mine here.

**Comment by newfrenchy83** [comment]
The reply is yes, same if defender with formation ability doesn't have weapon, tthe ecpected outcome is what all weapon cth of opponent was affected. In simplify thz code, i must placed an if( ! orher_attack) loop for fix crash bug but introduce an limitatipn of formation ability to melee attack, this is for that what i put the old code.

**Pull request closed without merging**
