### PR TITLE
Re-sets the standing animation before and after the temporary_unit_mover moves the unit

### LINKED ISSUE #6960: Unit's image is missing when attacking
### Game and System Information

The Battle for Wesnoth version 1.17.6+dev (https://github.com/wesnoth/wesnoth/commit/565b318c9f0166d09f2dbff8f7982a52cd382dbb-Modified) x86_64
Running on Fedora Linux 36 (Workstation Edition) x86_64
Distribution channel: Default

SDL video drivers: wayland [x11] KMSDRM dummy
Window size: 1920x1021
Game canvas size: 1920x1021
Final render target size: 1920x1021
Screen refresh rate: 60
Boost: 1.76
Lua: 5.4.4
OpenSSL/libcrypto: 3.0.0e-dev (runtime 3.0.0e-dev)
Cairo: 1.17.6 (runtime 1.17.6)
Pango: 1.50.8 (runtime 1.50.8)
SDL: 2.0.22 (runtime 2.0.22)
SDL_image: 2.0.5 (runtime 2.0.5)
SDL_mixer: 2.0.4 (runtime 2.0.4)

### Description of the bug

Unit's image is missing at the destination hex, sometimes the unit's image is irregularly blinking at hex when the unit was previously standing:
image
image

### Steps to reproduce the behavior

1. Select unit then move&attack another unit 

### Expected behavior

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Pentarctagon**
Fixes #6960

### CODE REVIEW

**Comment by gfgtdf** [comment]
I'm not sure that the whiteboard always, sets the units ghosted, so unless you tested this thoroughly it maybe be better of the whiteboard path doesn't call any function.

**Comment by Pentarctagon** [comment]
Yep, updated.

**Comment by CelticMinstrel** [comment]
It looks like you accidentally squashed it into an unrelated commit.

**Comment by Pentarctagon** [comment]
Whoops, fixed.

**Comment by Konrad22** [comment]
Hey, I just want to to confirm that it's intentional that this fix changes the way the game behaved before the bug was introduced.
1.16 (your own screenshot from #6960)
296534272-4d9e866d-63e3-432e-ac16-fb6682132c46
(interestingly going out of focus on 1.16.11 causes the following)
weirdo

1.17.26
new

In 1.16 the unit isn't visible where it would attack, but in 1.17.26 it basically teleports over there.

The fix is consistent with 1.16 that the sprite, ellipse, and orb stay together.
It actually looks like 1.17 made the change to move the unit over there and forgot to bring the sprite as well...? (But I don't know enough about that.)

**Comment by Pentarctagon** [comment]
What happened was that the unit was actually always moved, but prior to the rendering overhaul the dialog opening froze all other animations so quickly that it seemed like it didn't actually move. With the rendering overhaul dialogs don't freeze everything else, so you now see the movement.

**Pull request merged**
