### PR TITLE
EI - show custom traits in help menu

### PR DESCRIPTION
**Pull request by Dalas121**
EI has a few custom traits, but since they aren't assigned to a race they don't show up in the help menu.

This PR creates a dummy race and dummy unit to fix the issue. Ugly but it works.

### CODE REVIEW

**Comment by soliton-** [comment]
The existing workaround for loyal and aged is to add it to the Fog Clearer. This should probably do the same.
https://github.com/wesnoth/wesnoth/blob/c1b331c62fd1c4d14d83da5bb88592bb7ce518ce/data/core/units/fake/Fog_Clearer.cfg#L16-L20

**Comment by Dalas121** [comment]
Is there any way to add traits to Fog Clearer? The traits in question are only defined within the EI campaign, and I don't know of any way to add traits to an existing unit type.

**Comment by CelticMinstrel** [comment]
No, obviously these can't be added to the Fog Clearer. However, adding them to a dummy unit rather than a dummy race is certainly possible. I don't know which one is better; with the core ones, we chose the Fog Clearer solely because it already existed.

**Comment by Dalas121** [comment]
> Given the comment in the code Soliton cited, if there's any custom units of the monster race (or another race with num_traits=0) in EI, that might work as a place to stash these (with a similar comment)

Is this desirable? It seems it's more straightforward to create a dummy race explicitly for the help text - using an existing custom unit runs the risk of creating more issues if we ever need to change/remove that unit.

**Comment by CelticMinstrel** [comment]
I don't know if it's desirable to use an _existing_ unit. It certainly is simpler to make a dummy unit of the monster race rather than a dummy unit of a dummy race, though.

**Comment by Dalas121** [comment]
Ah, I see. That makes perfect sense, I've made the change.

**Comment by Wedge009** [comment]
Back-ported in 04d29f4e3b895b6396bde659ae52f8312aa7678c.

**Comment by stevecotton** [comment]
@Wedge009 this has string changes, so it can't be backported unmodified.

I attempted to just remove the `help_text` parts, and ran into what seems to be an engine bug. According to UnitsWML, `help_text` should default to `description`, but even after removing the markup from `description` the lack of `help_text` meant that the help page wasn't shown when clicking on "survivor" in the sidebar.

**Comment by Wedge009** [comment]
Please advise @Dalas121, I only back-ported this one per their request.

**Comment by Wedge009** [comment]
Back-port reverted in 49d586a537fca69b3932c36de28b2969e35ec7c1.

**Comment by stevecotton** [comment]
FYI, just opened #8683 "document why the Fog Clearer's traits show in help".

The survivor trait only shows up when opening help with a unit that has that trait on the map, or when Wesnoth is in `:debug` mode.

**Pull request merged**
