### PR TITLE
fixed two grammatic mistakes in the sentences

### PR DESCRIPTION
**Pull request by wofwofwof**

### CODE REVIEW

**Comment by Pentarctagon** [comment]
Translation updates are meant to go through the respective translation maintainer (currently @Byteron for German, or maybe @sevu as a fallback), or the person responsible for the overall translations updates (@ivanovic), but not through the regular PR process.

**Comment by wofwofwof** [comment]
Sorry, this is my first time I try to get something into wesnoth. A bit more help would be great.
Neigther Byteron nor sevu seems to have a current fork of wesnoth. How shall I give them the pull request.
If you are not interested or don't care, its fine for me, too. I've just motivated my daugther to correct something she had found. If the project doesn't need this I wont wast time here.

cheers

**Comment by soliton-** [comment]
Translations are not done with pull requests on github. For the german translation you can contact them on discord or IRC. https://wiki.wesnoth.org/GermanTranslation

**Comment by wofwofwof** [comment]
Ok, thank you very much.

**Pull request closed without merging**
