### PR TITLE
Move [color_range] id=darkblue to core

### LINKED ISSUE #4670: DiD's color_range is unknown to the load save dialog
### Game and System Information
 - What version of the game are you running?
1.15.2
 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
Steam.
 - What OS are you running?
Windows 10

### Describe the bug
Malin has the wrong teamcolor (magenta?) in the loading save dialog.
(The screenshots and the saves are just examples. This bug seems to be in effect for every DiD save, but not for other saves.)
This issue disappears once you've loaded one of the DiD saves until you close Wesnoth.

### To Reproduce
1. Have a 1.15 save from DiD.
2. Start Wesnoth 1.15.
3. Open the loading saves dialog.
4. Select a 1.15 save from DiD.

### Expected behavior
Malin has the intended teamcolor (dark blue).

### Screenshots
grafik
grafik

### Savefiles
[DiD-A Small Favour — Part 3.gz](https://github.com/wesnoth/wesnoth/files/4006398/DiD-A.Small.Favour.Part.3.gz)

### PR DESCRIPTION
**Pull request by hexagonrecursion**
Fixes #4670

### CODE REVIEW

**Comment by Vultraz** [comment]
I think if this is being moved to core, the string should be in the `wesnoth` textdomain and not `wesnoth-did`.

**Comment by hexagonrecursion** [comment]
Done

**Comment by soliton-** [comment]
Did the translations get moved over? `utils/po2po` can be used to do that.

**Comment by soliton-** [comment]
`utils/po2po wesnoth-did wesnoth`

Perhaps have to do a pot-update before.

Though it seems like the string is new and if I had to guess not actually translated so far.

**Pull request merged**
