### PR TITLE
Made more use of std::isalnum, std::isalpha, and std::isdigit (std::l…

### PR DESCRIPTION
**Pull request by Vultraz**
…ocale versions)

I'm wondering if maybe I should make these util functions to avoid having to specify the classic locale constantly.

### CODE REVIEW

**Comment by GregoryLundberg** [comment]
Um .. isn't std::isalnum(c) the classic (ie., "C") locale version of std::isalnum(c, locale)?
I really don't know and dont have the time atm to do the research

**Comment by CelticMinstrel** [comment]
I'm guessing `std::isalnum(c)` uses the current global locale, while `std::isalnum(c, locale)` uses the specified locale.

(By the way, when was the latter added to the standard? I've never heard of it before. Will it work in MSVC 2013? ...I guess Appveyor does test 2013, so it should be fine right?)

**Comment by Vultraz** [comment]
Isn't marked as C++11 on CPPreference so we should be fine. Besides, we already use `std::isalnum` as of a few days ago and there've been no problems.

**Comment by CelticMinstrel** [comment]
I was referring specifically to the version with two arguments; the version with one argument is actually part of the C library and has been around for roughly centuries.

**Comment by Vultraz** [comment]
I was also referring to the two-argument version.

**Comment by jyrkive** [comment]
Hand-rolled digit detection is so short and easy to understand that I prefer it over `std::isdigit()`.

@CelticMinstrel is right, the `<cctype>` versions of the functions use the global locale that can be changed. Therefore the `<locale>` version must be used if non-ASCII characters should be rejected.

**Comment by Vultraz** [comment]
Well, since the `std::bad_cast` exception is back, I have no idea what to do. I'm not using `static_cast`....

**Pull request closed without merging**
