### PR TITLE
EI: reduce Barrow/Pyre Wight vulnerability to arcane

### PR DESCRIPTION
**Pull request by Dalas121**
EI's Barrow/Pyre Wights still have 50% arcane vulnerability. This PR lowers it to 20%

### CODE REVIEW

**Comment by Wedge009** [comment]
Back-port to 1.18 as well?

**Comment by stevecotton** [comment]
This probably changes the balance, but has no corresponding changes to correct the balance. Should it have?

Should the Barrow Wight's ABILITY_SHROUD, described in the [now-fixed bug](https://github.com/wesnoth/wesnoth/issues/8631) be correspondingly nerfed, or even removed as no longer necessary?

**Comment by Dalas121** [comment]
> This probably changes the balance, but has no corresponding changes to correct the balance. Should it have?

No, not a big enough change. The Barrow Wight and Pyre Wight are leader units that only ever appear once each, so changing their stats doesn't have major balance implications.

Especially because, as you mention, ABILITY_SHROUD sets arcane resistance to 50% regardless of the existing vulnerability, so the change really only meaningfully affects the Pyre Wight.

> Back-port to 1.18 as well?

Would be great, yes please.

**Comment by Wedge009** [comment]
Still needs back-porting.

**Comment by Dalas121** [comment]
Ok, I *think* I've back-ported this correctly. Can you verify I didn't break anything?

**Comment by Wedge009** [comment]
The commits (80e84f1eeb391858a3ce55ac8d29a098fdb17946 and b501342d3e03b5559931da5a99cbac6a66fa3c2d) are the same and the branches look right. As for 'didn't break anything' the CI is still running.

**Pull request merged**
