### PR TITLE
[world conquest] [artifact/abilities] Make banner stack with leadership ability.

### PR DESCRIPTION
**Pull request by knyghtmare**
fixes banner not stacking with leadership

Addresses point 8 of #6411

### CODE REVIEW

**Comment by newfrenchy83** [comment]
you must ever pull cumulative=no for what case of negative value don't relaced by zero.

**Comment by newfrenchy83** [comment]
I try to resolve issue with https://github.com/wesnoth/wesnoth/pull/6468.

**Comment by knyghtmare** [comment]
> I try to resolve issue with #6468.

I will have a go at testing it then. Need to rebuild my client first.

**Comment by stevecotton** [comment]
Is this waiting for review, or waiting for testing?

My current feeling is that I'd be happy to merge this to master now, even though #6468 is also going to be merged to master.
I'd also happily merge a backport of this to 1.16.

After review (and maybe changes) I intend to merge #6468 to master, but not to backport that (because it's an API change).

**Comment by knyghtmare** [comment]
> Is this waiting for review, or waiting for testing?

It has been tested and works too.

**Pull request merged**
