### PR TITLE
Minor color_t cleanup

### PR DESCRIPTION
**Pull request by Vultraz**
Just to double check, since we don't use hex value with alpha, `uint32_t` should be big enough to support any hex string-to-num conversion, right?

### CODE REVIEW

**Comment by gfgtdf** [comment]
why does macos complain about value() ? using operator * is ub if the option doesnt hold a value, while value() throws an exception, which is better since the cdode doesn't seem to check whether it has a value.

**Comment by Pentarctagon** [comment]
It's a limitation of the macOS version we're targeting.

**Comment by Vultraz** [comment]
Because we refuse to update the macos target >__<

**Comment by Pentarctagon** [comment]
What version of macOS would we need to target to get that functionality anyway?

**Comment by gfgtdf** [comment]
> It's a limitation of the macOS version we're targeting.

Is there a reason why we are targeting such an ancient OS that isn't supported by apple itself anymore and received its last security update in 2019? (for comparision: that even longer ago than windows 7s last security update, which we iirc dropped for a similar reason)

which this particular issue only requires macos 10.13, I strongly suggest setting the minimum version to maybe macos 11 (which also doesn't't receive security updates anymore) or even later.

**Comment by Pentarctagon** [comment]
@CelticMinstrel said he wouldn't be able to continue contributing if we set it past 10.15.

**Comment by Vultraz** [comment]
Then let's do at least 10.15. Then we can drop the fallbacks for macOS for `any` and `variant` and won't have to worry about the issues with `optional`. I'd advocate at least 12.x, tbh, but if we need to stick with 10 let's at least make it 10.15.

**Comment by CelticMinstrel** [comment]
> Just to double check, since we don't use hex value with alpha, `uint32_t` should be big enough to support any hex string-to-num conversion, right?

…what on earth are you saying? `uint32_t` is _exactly_ the size required for RGBA colour with 8-bit channels… so unless you're expanding to 16-bit channels like QuickDraw used on ancient Macs, `uint32_t` is exactly sufficient _including_ alpha.

**Comment by Vultraz** [comment]
You don't need to be an ass about it. Yes, I should have remembered that `uint32_t` was exactly the right size, but I was thrown by the old code converting to `unsinged long`, which is 64 bits on non-Windows platforms. I wanted to double check, so I wouldn't get yelled at for breaking code.

**Comment by CelticMinstrel** [comment]
As far as I'm aware, unsigned long is normally 32 bits as well… though the standard doesn't actually define the sizes of _any_ of the integer types, so there's no guarantee of its size. Perhaps it has become 64 bits lately to make way for the new 128-bit integers as unsigned long long…?

**Pull request merged**
