### PR TITLE
Menu: re-order and re-rank campaigns (including new ranks) (fixes #1222)

### LINKED ISSUE #1222: Rename "Novice, Intermediate, Expert" on the campaign screen (GNA #16276)
**[Original submission](https://gna.org/bugs/index.php?16276)** by elvish_sovereign on 2010-07-17

Currently the only difficulty ratings on the campaign screen (not the campaign difficulty level, but like HttT is 25 scenarios, Novice level) are Novice, Intermediate, and Expert. Campaigns like AToTB and HttT or Liberty and LoW are markedly different in difficulty, yet they are marked the same as Novice and Intermediate, respectively.

I suggest It should be a little more fine-graded: Rookie, Novice, Intermediate, Hard, Expert. The names are WIP but this is the general idea I'd like to see: slightly more relevant description to the campaign difficulty. This way we won't noobs jumping straight into HttT and complaining about SoE or something. IMHO A more gradual progression would be AToTB, TSG, AOI, then HttT.

*******

This is just my idea of what it should sort of be, also taking note of the recent campaign changes (notably LoW).

Rookie: AToTB, TSG, AOI

Novice: HttT, Liberty, EI

Intermediate: DiD, THoT, DM

Hard: LoW, SoF, SoTBE

Expert: SoTBE, UtBS, NR

This part is only my opinion, so you can scratch this part if you'd like

*******

(Reproduced on Mac OS 10.6)
Release: 1.8.3
Priority: 5 - Normal
Severity: 1 - Wish

### PR DESCRIPTION
**Pull request by joeylmaalouf**
Fixes #1222.

Note that the wiki's description of "rank" on the CampaignWML page will need to be updated, though I don't have a wiki account or the knowledge of how that's supposed to go (I suppose it'd be the addition of one of those "if version XYZ or later:" blocks?).

For ease of comparison, here's a before and after summary of each campaign's rank and category, along with the wiki text:

BEFORE
```
Novice:
    5 A Tale of Two Brothers
   10 An Orcish Incursion
   15 The South Guard
   20 Heir to the Throne
Intermediate:
  110 Liberty
  125 Legend of Wesmere
  130 Eastern Invasion
  140 The Hammer of Thursagan
  150 Descent into Darkness
  160 Delfador's Memoirs
  170 Dead Water
  180 Secrets of the Ancients
Expert:
  215 The Sceptre of Fire
  220 Son of the Black-Eye
  230 The Rise of Wesnoth
  240 Northern Rebirth
  250 Under the Burning Suns
```

CampaignWML:
  rank: a number that determines the order of campaigns in the campaign selection menu. Lower rank campaigns appear earlier, with unranked campaigns at the end. Currently the mainline campaigns use multiples of 10 from 0 to 399, with 0-99 for Novice campaigns, 100-199 for Intermediate campaigns, and 200-399 for Expert campaigns; if you specify this, it should not be less than 400. (Note: This replaces an older convention that topped out at 50.)

AFTER
```
Rookie:
    5 A Tale of Two Brothers
   10 The South Guard
   15 An Orcish Incursion
Novice:
   50 Heir to the Throne
   55 Liberty
   60 Eastern Invasion
Intermediate:
  100 Descent into Darkness
  105 The Hammer of Thursagan
  110 Dead Water
  115 Delfador's Memoirs
Hard:
  150 Legend of Wesmere
  155 The Sceptre of Fire
  160 Secrets of the Ancients
Expert:
  200 Son of the Black-Eye
  205 The Rise of Wesnoth
  210 Under the Burning Suns
  215 Northern Rebirth
```

CampaignWML:
  rank: a number that determines the order of campaigns in the campaign selection menu. Lower rank campaigns appear earlier, with unranked campaigns at the end. Currently the mainline campaigns use multiples of 5 from 0 to 249, with 0-49 for Rookie campaigns, 50-99 for Novice campaigns, 100-149 for Intermediate campaigns, 150-199 for Hard campaigns, and 200-249 for Expert campaigns; if you specify this, it should not be less than 300.

### CODE REVIEW

**Comment by Pentarctagon** [comment]
You can get a wiki account following the instructions [here](https://forums.wesnoth.org/viewtopic.php?f=17&t=43815).

**Comment by sigurdfdragon** [comment]
I've played all the mainline campaigns

I don't think TRoW is that difficult or having unusual mechanics that it should be in Expert. I'd put it in Hard (possibly even Intermediate??)

**Comment by Wedge009** [comment]
The Rise of Wesnoth is one of the older campaigns, isn't it? I imagine relative difficulties (and opinions) can shift over time.

**Comment by sigurdfdragon** [comment]
SotA's positioning in hard is an improvement over the current way of things.
Having thought about it, TRoW in hard seems best.

As for the ordering inside each new rank:, Rookie, Novice, & Intermediate seem fine.
For hard, I think an order of TRoW, SoF, LoW, SotA would be better.
For expert, SotBE, UtBS, NR seems fine.

**Comment by joeylmaalouf** [comment]
Sounds good. Now:

```
Rookie:
    5 A Tale of Two Brothers
   10 The South Guard
   15 An Orcish Incursion
Novice:
   50 Heir to the Throne
   55 Liberty
   60 Eastern Invasion
Intermediate:
  100 Descent into Darkness
  105 The Hammer of Thursagan
  110 Dead Water
  115 Delfador's Memoirs
Hard:
  150 The Rise of Wesnoth
  155 The Sceptre of Fire
  160 Legend of Wesmere
  165 Secrets of the Ancients
Expert:
  200 Son of the Black-Eye
  205 Under the Burning Suns
  210 Northern Rebirth
```

**Comment by Pentarctagon** [comment]
@joeylmaalouf Check your forum PMs about getting wiki access.

**Comment by joeylmaalouf** [comment]
Awesome, thanks. I've updated the CampaignWML page accordingly.

**Comment by Pentarctagon** [comment]
The only other question I would have then, would be whether this should go into 1.14 or master.  There really shouldn't be anything that's "1.14.x or later" unless it can't be avoided.

**Comment by Pentarctagon** [comment]
Alright, I'll merge/cherrypick this soon unless someone objects.

**Comment by sevu** [comment]
Uhm, "Rookie" etc are new strings, I think this must be reverted till 1.14.6.

**Comment by jostephd** [comment]
Not to hijack, but should the default difficulty of Liberty be raised to Normal from Easy? Every other campaign (except SotBE/NR) uses the middle of three available difficulties as the default.

**Pull request merged**
