### PR TITLE
Actually run the SDL2 test to check the version

### PR DESCRIPTION
**Pull request by soliton-**

### CODE REVIEW

**Comment by loonycyborg** [comment]
I would recommend using conditional compilation and `#error` instead. It would work with cross-compile too. However runtime way would let us emit a better error message in case of old version..

**Review by loonycyborg — APPROVED** [review]

**Comment by soliton-** [comment]
> I would recommend using conditional compilation and `#error` instead. It would work with cross-compile too.

Makes sense. I'll look into that sometime.

**Comment by soliton-** [comment]
Looks like it used to be a compile time test already before 0aa8dc3c6c7a2a729390a9a3b4a32c6a4a45f493 made it into a runtime test and broke the scons check.

**Comment by soliton-** [comment]
I haven't checked anything on the cmake side though the CI appears to work.

**Review by Pentarctagon — APPROVED** [review]

**Pull request merged**
