### PR TITLE
Exclude nonvillages from outer_villages array

### LINKED ISSUE #7202: UtBS S01: has 1841 `outer_villages`
### Game and System Information

- **Version:** 1.17.10+dev
- **Downloaded from:** Built from Git
- **Build info:** GCC and b5ff5c3ddc706f1281bbbe2f235b16c4b00f92db
- **OS:** Linux

### Description of the bug

Low priority, because it's only visible when looking at WML variables. However, as it's a mainline campaign it should be reference code that can be copied by UMC authors.

The code that uses `[store_locations]` to create the `outer_villages` array ends up with an array that has 1841 entries. That doesn't affect gameplay, because the array is only accessed in `capture` events, so the non-village entries are ignored.

### Steps to reproduce the behavior

1. Start Under the Burning Suns
2. :debug
3. :inspect
4. Start to scroll down to the "units" section, and notice that the scrolling is slow and there are over 1800 entries in the `outer villages_array`.

### Expected behavior

About 6 entries

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ProditorMagnus**
Fixes #7202 

@nemaara could confirm that Gd^Vdt, Rd^Vdt, Re^Vda are intended to be included.

V terrains in that map:
Dd^Vda
Dd^Vdr
Dd^Vdt
Ds^Vda
Ds^Vdr
Ds^Vdt
Gd^Vdt
Rd^Vdt
Re^Vda

### CODE REVIEW

**Comment by soliton-** [comment]
Wouldn't it be more robust to filter for gives_income?

**Comment by ProditorMagnus** [comment]
Comment explicitly mentioned desert villages.

**Comment by soliton-** [comment]
If the intention is truly to consider just desert villages then perhaps the variable should have a better name.

Looks like we're just waiting for the filter to become outdated again then though.

**Comment by ProditorMagnus** [comment]
I have never opened the campaign, not even for this change. I have no idea what the map looks like or how it is played, I just analyzed map file and identified the overlay to add to filter so that functional behaviour would not change.

**Comment by ProditorMagnus** [comment]
If it was not about desert villages then filter would have been \*^V*.

**Comment by stevecotton** [comment]
> I have never opened the campaign, not even for this change. I have no idea what the map looks like or how it is played, I just analyzed map file and identified the overlay to add to filter so that functional behaviour would not change.

While I think this is the right change, the reason that I logged a bug for it instead of doing a quick fix was that I didn't want to spend time playtesting the fix. I feel that PR reviewers should assume that the author playtested it, unless the PR mentions otherwise.

**Comment by knyghtmare** [comment]
> I have never opened the campaign, not even for this change. I have no idea what the map looks like or how it is played, I just analyzed map file and identified the overlay to add to filter so that functional behaviour would not change.

I think this PR needs Playtesting before merging. Because applying a patch without "knowing you are aiming to fix" is an invitation to more follow-up bugs

**Comment by ProditorMagnus** [comment]
Correct. That is also why asked for approval from nemaara.

**Comment by soliton-** [comment]
> If it was not about desert villages then filter would have been *^V*.

If it was about desert villages the variable name would have desert in it... I don't think this is a particularly useful line of thought. Clearly there is no difference anyway since there are no other villages.

My point is simply that gives_income is a more robust filter by not leaning on convention for terrain strings and instead using the property that actually makes a terrain a village.

**Comment by ProditorMagnus** [comment]
True. I was just not aware of the key or even most changes after 1.14.

Would be good to solve the need of relying on terrain code for other terrain concepts too, not just village.

> When adding terrains make sure the following files are also checked:
> data/multiplayer/factions/* contains favorite positions for the different factions, this is only used for the random map generator at the moment so it is not very important.
> data/core/macros/abilities.cfg contains the definition of submerge and ambush so depending on the change these need to be updated.

**Review by nemaara — APPROVED** [review]
Good to go.

**Review by cooljeanius — APPROVED** [review]

**Comment by cooljeanius** [comment]
> Good to go.

OK, so... can some merge please?

**Comment by CelticMinstrel** [comment]
Looks like I showed up late, but… is there a reason not to use `[show_villages]`? Is it planned to be deprecated, maybe? It's basically the same as `[store_locations]` but with an implicit `gives_income=yes` in the filter.

**Pull request merged**
