### PR TITLE
AToTB: Tweak hint to not assume the AI will make mistakes

### PR DESCRIPTION
**Pull request by jostephd**
As discussed at https://github.com/wesnoth/wesnoth/pull/2105#pullrequestreview-72671256.

### CODE REVIEW

**Comment by sigurdfdragon** [comment]
@jostephd 
Baiting the AI in SP campaigns is such a useful tactic, I'm not sure why we shouldn't tell the player about it. Also, your comments in #2105 appear to suggest you have MP in mind, which plays differently than SP.

**Comment by jostephd** [comment]
@sigurdfdragon I think the tips in SP should recommend strategies that would work even in MP, so new players don't develop bad habits.  I don't mind mentioning AI baiting as well but I think it should be recommended only as a secondary alternative, not as a primary.  Perhaps I'm in the minority on this :-)  Cheers!

**Comment by GregoryLundberg** [comment]
Not alone in the minority

**Comment by sigurdfdragon** [comment]
I'm not that attached to either version of the hint. So if the tweak is felt to be better, go with it.

**Comment by CelticMinstrel** [comment]
I like the tweaked version.

**Comment by sigurdfdragon** [comment]
@jostephd Ok, I'll go with changes. Please update commit title to follow convention (AToTB S03:), since it only affects one scenario, and I'll merge it.

**Comment by jostephd** [comment]
Done!

**Pull request merged**
