### PR TITLE
Loyal units always get the ring overlay, fix #4058

### LINKED ISSUE #4058: Level up removes loyal overlay from unit
(Version 1.15.0 on Windows 10)

To reproduce, you can load this game save...

[2p — Caves of the Basilisk-Auto-Save1.gz](https://github.com/wesnoth/wesnoth/files/3128733/2p.Caves.of.the.Basilisk-Auto-Save1.gz)

... and then attack the Blood Bat with your Elvish Fighter. You'll see the loyal overlay is removed after the advancement.

### PR DESCRIPTION
**Pull request by spixi**

### CODE REVIEW

**Comment by gfgtdf** [comment]
There are some cases even in mainline where authors don't want the ring overlay, in particular when they have already another overlay (the hero overlay usually)

Also, I am already working on this https://github.com/wesnoth/wesnoth/pull/4088 (don't have that much time do it'll take a while)

**Comment by GregoryLundberg** [comment]
We should reject deprecating {IS_LOYAL}.

I won't close this myself, but suggest someone working the problem (@gfgtdf?) should.

**Comment by newfrenchy83** [comment]
i know what the method in https://github.com/wesnoth/wesnoth/pull/4081 is not ideal but it is the less heavy for the wml reworking and permit to use another overlay what ring overlay

**Comment by gfgtdf** [comment]
this was basicially implements as part of myother pr

**Pull request closed without merging**
