### PR TITLE
proposed new resistances for Giant Scorpion, fix to SotBE 7

### PR DESCRIPTION
**Pull request by IskarJarak**
The addition of a variation for the Giant Scorpion and respective resistance change in #4015 left the unit with the uninspired values of standard humans.

I propose to change the resistances back to something more interesting that builds on their carapace (hard to hurt with normal blades, but you can crush or cook them). Note, that especially the impact resistances go in the _opposite_ direction of the Scuttle variation. Didn't want to overdo it, but I'd also be open to add +10% pierce resistance.

Also added a fix to SotBE scenario 7 to use the variation because scenario dialogue clearly talks about the old resistance values.

Edit: updated the commit with resistances as discussed below and according modifications to the unit description.
I pulled the changes to the Scuttler, because simply reducing the extremes of good ol' Mudcrawler resistances doesn't make it much better and doesn't help for scenarios currently balanced around it - might as well keep it as is, we have the standard Scorpion for a more realistic (and mundane) representation.

Edit: also fixed a continuity error between SotBE scenarios 5 and 9 (scenario 5 says: `Leaving most of his people at Barag Gór, Kapou’e, accompanied by the shamans and his warriors, set off to Tirigaz`) which I caught multiple times over the years but now have the means to remedy...

### CODE REVIEW

**Comment by Hejnewar** [comment]
I don't get why people think that scorpions are easy to burn. In fact they are harder to burn than humans. The only difference is that scorpions are smaller than humans, but in Wesnoth they are not. 

Pierce and blade resistance are ok. 
Impact also I think is (tho I recently discovered that scorpions have two skeletons so in theory they could be more impact resistant than we think). 

Also scorpions are fluorescent so they should be very easy to hit at night. (Just something to think about. :P )

@ElderofZ You were interested in them not too long ago. Want to share your thoughts?

**Comment by IskarJarak** [comment]
So we take out the fire vulnerability. I don't think I'd make them positively resistant to it, simply because the unit would get _very_ tanky. Also drop the +10% pierce resistance idea for that reason. That better for you?

**Comment by ElderoZ** [comment]
"I would rather have it retain some qualities of its past design, however small, even if the original idea was kinda ridiculous. So I would say maybe -20% fire res, rest is up to debate, maybe symbolic 10% impact or somewhat less symbolic 30%, idk, maybe something like +20% fire would also feel right, 0% just feels kinda wrong"

Thats my quote.

My initial idea was sth like -20% or 20% fire 30% impact, pierce and blade 0%, or just pierce 10% because some people said scorpions are probably harder to pierce than slash.

Imo anything that is within the realm of possibility and retains some characteristics of the old design looks good, ie relatively high impact res and fire vulnerability, though I would also accept fire resistance, so like -20% or 20%.

I like that Hejne discovered that scorpions might be harder to squash than it seems at the first glance, it supports the idea of impact res XD

I would like to hear opinions of third parties, but if people have ideas all over the place, then we will just decide on something.

Exact resistance values also can be changed, we could also add cold vulnerability, some arcane res or none at all, make both blade and pierce 0%, idk, people seem to have many ideas, there was even somebody who apparently wanted it to have 20% arcane and rest 0%!

**Comment by IskarJarak** [comment]
My reason for diverging from the original stats is that we now have the Scuttle variation, which has exactly the old values. I thought it'd be kinda boring if it was just the same, but less extreme in values.

**Comment by Hejnewar** [comment]
Well having outside and inside skeleton is very interesting. I would say that scorpion would still be less impact resistant than pierce and blade resistant. (Also you could in theory make 2 skeletons using one scorpion as necromancer. :P )

What about having scorpionling be vulnerable (or neutral) vs pierce, blade, fire etc. but scorpion being resistant to these? That could make sense because their armour need time to harden.

**Comment by IskarJarak** [comment]
Alright, so as to not go in circles with everyone throwing numbers around, I'll just offer a new proposal.

This keeps Hejnewar's words about two skeletons in mind - but with a quick google search on the matter I didn't find anything and, lacking biology skills, I'm not keen on putting anything in this direction in the unit description (by myself, if someone wants to propose changes beside the blade/impact line I wrote, go for it...)

How about:
- Scorpling 10/0/-10/0/0/20
- Scorpion: 30/10/-10/10/0/20
- Scuttle: 10/10/30/-50/-10/-20

(Keeping the over-the-top identity for the Scuttle but not quite as absurd by simply scaling the numbers down to align better with undeads, which are "normal" units with an extreme resistance portfolio.)

**Comment by Hejnewar** [comment]
I can show my sources. No a problem. (It looks really cool!) 

Looks ok, I would only change blade with pierce, and lower it a bit:

Scorpling 0/10/-10/0/0/20
Scorpion: 10/20/-10/10/0/20

What do you think?

**Comment by IskarJarak** [comment]
Sounds fine to me, I'm not fixed on specific values - just wanted to remedy both the current lack of inspiration and the 1:1 copy of the mud crawler that was in for over a decade :D

I'll update the commit later and also adjust the description a little.

**Comment by nemaara** [comment]
So since your new resists are an overall buff for the scorpion, the HP needs to come down by a little bit. Not a lot, but like 2-3.

**Comment by IskarJarak** [comment]
I'm not opposed to that, but was the unit balanced after the stat-reset? I think you just reset all resistances to 0, so the balance is still that of the mudcrawler-resistance scorpion? Compared to _those_ weaknesses, a moderately tanky portfolio is probably quite an upgrade in most cases (although, e.g., Knalgans should actually be stronger against the new scorpion!). For a tanky unit with poison, I'd actually be inclined to go down a little more though, 40 hp is a lot. @ElderoZ what do you think? You are way more experienced with balance than me.

**Comment by nemaara** [comment]
Hejne can comment to be absolutely certain but in general, I think the order I'd rank importance of resistance is something like blade > pierce > fire > impact > arcane > cold. Since the scorpion's blade resistance is up by 20% compared to its original value and fire by 40%, it's more or less an overall buff compared to before.

**Comment by Hejnewar** [comment]
It's for lvl1 blade > pierce > impact >fire > cold > arcane and on higher levels blade > pierce > impact >fire >arcane > cold.

Scorpionling - changes not needed. Difference is small enough to overlook. Current cost is 10g should be 14g (0 lvl). 
Gigant Scorpion - changes needed. -3 hp - a bit stronger than currently is -4hp a bit weaker than currently is. Current cost is 22g should be 23g.

Scuttle - no need to change hp.

**Comment by ElderoZ** [comment]
I commented on this in PM. In short I said that we shouldn't change scuttle variation at all and leave it with old scorpion stats. I am ok with wide range of new scorpion stats and it isn't that important if scuttle variation exists. Also I wil add here that I would rather prefer the lvl 0 and lvl 1 scorpion to have the same resistances, the idea of different resistances looks a bit crazy to me.

**Comment by IskarJarak** [comment]
Ok, just to be absolutely clear we are talking about the same things (it seems I forgot to write down my changes visibly for you guys):

Current resistances (B/P/I/F/C/A) in the commit are

- Scorpling 0/10/-10/10/0/20 and
- Scorpion 10/20/-10/10/0/20.

This was motivated by Hejne's comments of a) functionality of the shell (+ double skeleton) and b) the idea of the shell hardening with age, becoming stronger (that's why pierce and blade go up by 10). The 20% arcane are to stay in line with other "mundane" monsters, most of which have 20% arcane res. I don't see a problem with giving it cold weakness. If I understand it correctly, we _could_ diverge on pretty much everything between scuttle and scorpion, but I would prefer to keep them identical in most metrics so long as it's meant to stay a variation and not be exported to a new unit.

@Hejnewar is your "current" aimed at the no-resistances scorpion or at the scuttle? How much should the scuttle cost? I'd rather regulate scorpion HP enough so it stays on the same cost as scuttle, though I'm willing to bow to greater wisdom on this point as well :D .

How would your gold values be affected by -10 to cold? How much HP would we have to take off to keep Scorpion on the same price as Scuttle?

**Comment by Hejnewar** [comment]
@IskarJarak  Scuttle should cost 22 its close between 22 and 23 but 22 is tiny bit closer. 
For Scorpion to cost 22 you would need to lower its hp by 5.

-10% cold is not affecting prices much (almost not at all). Cold is very uncommon damage type overall (it makes up for only 4% of damage in default era on lvl 1 and even less later). I would say more but that would be offtopic so I will stop here.

**Comment by IskarJarak** [comment]
Alright, thank Hejne!

I'll update the PR with the following changes:

- scorpling resistances changed to 0/10/-10/10/-10/20; price increased to 14 gold.
- scorpion resistances changed to 10/20/-10/10/0/20; HP decreased to 35.

**Comment by sevu** [comment]
I think 14 gold is too much for the Scorpling. Spearman and Bowman have the same price.
Scorpling has 24 hp, the other > 30. For the spearman it's 50% more.
His big bonus is to have poison, but he also has a low attack compared to these units.
If you assume, that poison will cause 16 damage, then the attack is worth 21 damage – as much as Spearman does.
His movement is a bit better with 6 MP though. And the fact that he's L0 is an advantage, also needing only half XP to advance.
13 gold?
12 gold?
11 gold?
Goblins — the after them the strongest L0's — are at 9 gold.

**Comment by Hejnewar** [comment]
I can see them as 13g units, a bit too strong but ok.
In general 0 lvl units have to pay few gold for starting as 0 lvl, the stronger the unit the more it needs to pay. When you pay 1g for 0 level unit 22% of that 1g is going towards it being 0 lvl and only 78% is going towards it's body. That is important because for goblin only 2g is going towards it being 0 lvl. But the stronger the unit the more it will have to pay. So how much would you pay for body of this scorpionling?

Also bats are 13g 0 lvl units so goblins aren't strongest after them and if we take all of 0 lvl units from mainline goblins wouldn't even be 3rd. :P

**Comment by sevu** [comment]
How did you come to value the Lv0 as exactly **22%**?
But in that case, I'm fine with a higher price.
And forgot about the bats!

**Comment by Hejnewar** [comment]
I'm glad you ask. Its simple really, I just checked how much of a benefit its to recruit 0 lvl units instead of lvl 1 units with average price (16g) on map with average amount of villages (8 per side) during game that lasts 16 turns. Exact numbers for me were 356g (lvl 0) and 279g (lvl 1) with assumption that game is not very dynamic and units are recruited but don't die (very good environment for 0 lvl units).
Please note that 22% is really only good for units below or slightly above 16g, for example 0 lvl unit  with body that would cost 50g would need to cost 61g and that doesn't make much sense thus this 22% in reality as cost of unit gets higher is going to decrease until it hits 0. 

Cost of 0 lvl unit can be adjusted by wide margin depending on what you want to do with them, they will (almost) never be useless after all so they can only be too strong, for default purposes 22% is good often it's just few g so 0 lvl units doesn't feel too bad even for medium sized armies or in right matchups (goblins vs drakes) but are not good enough to use during games that are dynamic.   

Ehh, sorry for offtopic, I really like to talk about balance too much.

**Comment by IskarJarak** [comment]
apologies for the constant updates - embarassingly, I forgot to keep the scuttles HP at the old value.

@sevu are your concerns met sufficiently or would you still prefer the 13 gold version?

**Comment by sevu** [comment]
@IskarJarak Yes they are.

Personally, I wouldn't vary the resistances between the Lv0 and Lv1, which makes it easier for players to memorize the resistances. But the way it is is perfectly fine as well.

On another note, are scorpions weak to impact and resistant to pierce? I ended up on some page which tells how to kill them, and it's harming their exoskeleton by piercing it or using some sharp soil (=blade), while they can survive impact. Granted, regarding their size, anything works.

If they'd be giant scorpions, impact would probably work better, as it concentrates the impact onto one point, instead over the whole body.

In general, scorpions are very resistant beings: physical resistances, the generic 20% arcane, fire as they live in heathy regions, being cold-blooded could either be seen as weakness or resistance … they can have anything, which is equal to nothing. Except that a giant scorpion seems more scary than a giant human.

Anyways, I would merge the PR as is.

**Comment by Hejnewar** [comment]
I need to agree with sevu. Scorpion can really be good Vs everything you think about. I guess that's the reason why they look almost the same for millions of years now. 

About price as I said 14 and 13 are close but I noticed that 13 might be better because less people will pay attention to this cost and less people will ask questions about it. ;)

**Comment by sevu** [comment]
Merged – last change being the 13 gold cost .

**Pull request merged**
