### PR TITLE
Add battery percentage into game view (next to current time)

### PR DESCRIPTION
**Pull request by hrubymar10**
I am working on new feature. I want add current battery percentage next to current time in game view:
2018-08-08 at 16 07

## TODO
- [x] Create `battery_info` class
- [x] Add function to check if is battery present
- [x] Add function to get battery percentage
- [x] Port to macOS
- [x] Port to iOS
- [x] Port to Linux
- [x] Port to Windows
- [x] Create/Find nice battery icon (e1aefce)
- [x] Ask someone to create Windows port (probably jyrkive)
- [x] Ask someone to create Linux port (probably jyrkive)
- [x] Move battery icon on right from current time (b1c12acb8ee9b82c088114dfe00cf1a7ceff9c33)
- [x] Ask someone to fix CMake build on macOS (add `-framework IOKit` linker option) (827063d)
- [x] Find way to hide GUI element (if battery not present) - (16a44b25f1bf3f00efdc8e55cf8c107ede8fdca3)

## Example usage (patch):
```
diff --git a/src/wesnoth.cpp b/src/wesnoth.cpp
index fc78252d34..2a7c53ab32 100644
--- a/src/wesnoth.cpp
+++ b/src/wesnoth.cpp
@@ -17,6 +17,7 @@
 #include "commandline_options.hpp" // for commandline_options, etc
 #include "config.hpp"              // for config, config::error, etc
 #include "cursor.hpp"              // for set, CURSOR_TYPE::NORMAL, etc
+#include "desktop/battery_info.hpp"
 #include "editor/editor_main.hpp"
 #include "filesystem.hpp" // for filesystem::file_exists, filesystem::io_exception, etc
 #include "floating_label.hpp"
@@ -1112,6 +1113,10 @@ int main(int argc, char** argv)
 		std::cerr << "Battle for Wesnoth v" << game_config::revision << '\n';
 		const time_t t = time(nullptr);
 		std::cerr << "Started on " << ctime(&t) << "\n";
+        
+        if (desktop::battery_info::does_device_have_battery()) {
+            std::cerr << "Battery level is " << desktop::battery_info::get_battery_percentage() << "%\n";
+        }
 
 		const std::string& exe_dir = filesystem::get_exe_dir();
 		if(!exe_dir.empty()) {
```

### CODE REVIEW

**Comment by jyrkive** [comment]
I think your current implementation duplicates the interface needlessly. You declare functions `does_device_have_battery()` and `get_battery_percentage()` in both the `desktop::battery_info` class and in the `apple_battery_info` namespace, and the `desktop::battery_info` implementation does nothing other than forwards the function call to the actual implementation.

I think it would be better to simply remove `desktop/battery_info.cpp` and implement the `desktop::battery_info` class in the platform-specific file (`desktop/apple_battery_info.mm`, `desktop/windows_battery_info.cpp`, `desktop/dummy_battery_info.cpp` etc.)

**Comment by hrubymar10** [comment]
Linux and Windows could use same file but macOS is specific case because it require implementation in Objective C++ so it needs separate file. I wanted to use same model as in notifications:

`src/desktop/notifications.cpp` - for linux and windows
`src/desktop/apple_notifications.mm` - for apple systems (macOS and iOS)

in case of battery_info:
`src/desktop/battery_info.cpp` - for linux and windows
`src/desktop/apple_battery_info.mm` - for apple systems (macOS and iOS)

So should I really remove original `src/desktop/battery_info.cpp`?

**Comment by jyrkive** [comment]
Ah, I see. If your idea is to have the Windows and GNU/Linux implementations straight in `desktop/battery_info.cpp`, then it's fine for me.

**Comment by hrubymar10** [comment]
Exactly :)

**Comment by hrubymar10** [comment]
## Battery icon survey
Which icon do you like the most:

### 1. 
screenshot 2018-08-08 at 21 43 05

### 2. 
screenshot 2018-08-08 at 21 44 27

### 3.
I'll create better icon myself

**Comment by jyrkive** [comment]
I prefer icon 2.

**Comment by jyrkive** [comment]
Why did you move the battery info to the rightmost position? I said that I'd prefer to have the time there instead.

**Comment by hrubymar10** [comment]
Ops. I misinterpreted your message, Sorry.

But I'll keep it this way until I'll find way to hide battery info when battery is not available.

**Comment by Pentarctagon** [comment]
Regarding the cmake build, based on how the Cocoa framework is [added in](https://github.com/wesnoth/wesnoth/blob/master/cmake/FindSDL2.cmake#L180), I believe you could could add IOKit in [here](https://github.com/wesnoth/wesnoth/blob/master/src/CMakeLists.txt#L111), just as:
```
if(APPLE)
	set(game-external-libs ${game-external-libs} "-framework IOKit")
endif(APPLE)
```

**Comment by hrubymar10** [comment]
It worked. Thank you @Pentarctagon

**Comment by hrubymar10** [comment]
Linux port could probably use some code from here: https://www.cemetech.net/forum/viewtopic.php?p=84036&sid=b7003b8768e90f2ef4506cf82c292729#84036

Also it would be nice to support more than one battery. We can sum all batteries so if there will be 2 fully charged batteries, then Wesnoth will show 200%.

**Pull request merged**
