### PR TITLE
HttT S6: Cancel attacks, support alt cave entrance

### PR DESCRIPTION
**Pull request by jostephd**
If the player ordered a unit to move and attack, allow the attack to be canceled, as done in #3227 for DiD. And change the undead reinforcements triggering.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I don't understand the first commit... part of it looks like it really belongs with the second commit, while the other part is just confusing.

**Comment by jostephd** [comment]
@CelticMinstrel There are a couple of different things going on:

1. [first commit] When you order move-and-attack and the moves ends in a village, and that spawns the Thieves, cancel the ordered attack to let the player choose another attack if he wishes. As in #3227.

2. [first commit] Same, for when you order a move-and-attack and the move ends on the cave entrance trigger hex. For example, if you move to 17,6 to attack a unit that's on 17,5.

3. [second commit] Change the trigger from moveto to enter_hex. That matters when using a fast unit to move directly into the cave without first stopping on one of the four trigger hexes. If the fast unit is followed by a slow unit that stops on the trigger hex, the fast unit could get trapped.

4. [third commit] Add cave entrance trigger hexes on the side entrance.

Clearer? Should I split this to two PR's or something?

**Comment by CelticMinstrel** [comment]
Yes, that makes it clearer, thanks. I don't think it needs to be split.

**Comment by GregoryLundberg** [comment]
Your "unlikely" behavior is exactly how I play it. The question is: do we really want to expand the tripwire to the left, or leave it? Perhaps it should be the entire cave interior?

**Comment by jostephd** [comment]
I assumed the side entrance should be a tripwire for balance reasons, to ensure the undead reinforcements are always spawned.

I don't understand what you mean by making the entire cave interior a tripwire, do you mean making it so the hills/flat hexes adjacent to the cave hexes will no longer be tripwires? If 13,3 (cave) is a tripwire but 12,3 (flat) is not, once the player moves a unit to 13,3 a Revenant will spawn adjacent to the unit preventing it from either completing its move or retreating, and given the low terrain defense on that hex the player's unit will probably die even if it's a level 3 unit at full health (except Highwaymen). I don't think that would be fun.

The PR makes it so 12,3 is a tripwire, once the player steps on it it will be in range of both a Revenant and the Dark Sorcerer, but on 12,3 the player will have better terrain defense than on 13,3. Also it's more likely that the player will have MP remaining to retreat, not having expended MP on entering a cave hex.

**Comment by jostephd** [comment]
> If, somehow (which is not now possible, but could be), a unit could avoid the present tripwire hex, landing on any cave interior hex should trigger the undead breaking out of the corners as well,

Yes, with this PR it is impossible to avoid the tripwire, so it's moot whether hexes inside the cave are tripwire or not.

In 1.14 without this PR it is possible to avoid the tripwire by having enough MP (Outlaw, Sylph, Rogue, of course the latter would be bad play).

> What I am saying is that I remember working on it to clean it up a bit but I don't remember checking that every possible hex inside the carver was a tripwire. It probably should be the same hex which have permanent night as their day cycle.

As I said in my previous post, I don't think it would be good for 13,3 (cave, permanently night) to be a tripwire if 12,3 (flat, normal day/night cycle) isn't, because that would effectively kill a player unit with no forewarning and no recourse.

Maybe we could make only the cave hexes a tripwire, but add a forewarning about the Revenant? The Thieves could speak of rumors of undead reinforcements, or of the undead being much stronger than they have shown so far, or something? Then the 13,3 trap wouldn't be frustrating.

**Comment by GregoryLundberg** [comment]
Lessee ... IIRC it was my fifth or twentieth attempt when I finally got up there and was, like, cool, what can go wrong, now? Kill the Boss and I'm finally done with this scene. Lad-de-dah let's waltz in and get to it. WTF? WHERE DID *THEY* COME FROM?

So it was my sixth (or thirtieth) attempt before I finally decided to flank them and win through.

Personally, I like the flanking not tripping the trap. But if you want it there, it should be everywhere. And don't depend upon a given move limit. If you can debug and set moves remaining to 99 and skip over the tripwire, someone can eventually make a unit which will, as well.

**Comment by jostephd** [comment]
@GregoryLundberg Did you miss that this PR changes the tripwire from moveto to enter_hex? "Make the entire cave a tripwire" does not make sense when enter_hex is used. It is also not possible to skip over the tripwire when it uses enter_hex.

**Comment by sevu** [comment]
Can this go into 1.14.5 as is?

**Comment by jostephd** [comment]
At least 1) and 2) (adding `cancel_action`) should go to 1.14.5. Possibly the whole patch.

**Comment by GregoryLundberg** [comment]
As much as I hate losing my favorite end-run I'd say merge it as-is.

**Comment by sevu** [comment]
By all means, have your favourite end run. I asked because I wondered if we have here a situation of one person expecting more changes and another assuming it's done, and because of the planned release.

**Comment by GregoryLundberg** [comment]
Nah. I'm fine with it as it is.

**Pull request merged**
