### PR TITLE
NR S05a_01: changed SE path to remove 1-hex bottlenecks

### PR DESCRIPTION
**Pull request by UnwiseOwl**
Fix for #3043

This allows player 3 to send more enemies against the human player sooner. If this is an issue, may be necessary to  consider changing the scenario wml to delay this player spawning by a turn.

Note: This is my first pull request and as usual I don't know what I'm doing so if I'm doing it wrong please let me know

### CODE REVIEW

**Comment by UnwiseOwl** [comment]
Did this fail because I accidentally merged to master instead of 1.14?

**Comment by stevecotton** [comment]
The AppVeyor test is testing C++ compilation, so a map fix definitely can't cause it; it looks likely that 2a585118d8b6c4b37d0ff9446a72ca20419ff7f7 is the problem.

With this PR, confusingly Github is saying that "UnwiseOwl wants to merge 1 commit into wesnoth:master from unknown repository". Have you deleted the branch in your fork (which I guess is why it says "unknown")?

The convention in Wesnoth's history for scenario fixes seems to be to start the commit's topic with something like "NR S05a_01:", although that's obviously easier when maps don't have extra bits after the number.

**Comment by CelticMinstrel** [comment]
Since it's just one commit, we can add that prefix when we merge it.

**Comment by UnwiseOwl** [comment]
> Have you deleted the branch in your fork (which I guess is why it says "unknown")?

Yes, after posting this I proceeded to break my fork and wasn't sure how to restore it to master so I just deleted and reforked it.

**Comment by CelticMinstrel** [comment]
Normally deleting a branch closes the PR; I guess deleting the whole fork doesn't do that?

**Comment by stevecotton** [comment]
Known issue with Github (isaacs/github#168), apparently the right thing to do is close this PR and open a new one.

**Pull request merged**
