### PR TITLE
Lua integer indices

### PR DESCRIPTION
**Pull request by GregoryLundberg**
@gfgtdf requested assistance with a crash in MP scenario 2p_Dark_Forecast

The cause turned out to be a change from Lua 5.2 to 5.3 which converts numbers to always have a fractional part. This means integer values will have ".0" at the end. The unexpected input caused the engine to crash.

1. Changed all mainline which builds similar indices to conform to Lua 5.3

2. The MP startup is not complete, worked around this with a temporary fix

3. There were two issues with the Wesnoth API in the scenario

4. Updated the Lua configuration to enable compatibility with 5.2 for this error

2p_Dark_Forecast can now be played to victory/defeat although there is an error which appears complaining about an audio track being duplicated. (This may be due to my rapid play-through and is not a real error.)

The Lua compatibility should prevent errors in UMC, but will mask any remaining errors in mainline.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Commit 21b1414 is kind of shocking. o.o

Anyway, this looks good to go in. Maybe we should mention the int/float thing in the RELEASE_NOTES, as we probably won't want to have the compatibility flag set forever and there is probably a lot of UMC that builds variable names with string concatenation.

**Comment by GregoryLundberg** [comment]
Why is it shocking?  I imagine someone changed the API so we should expect breakage.

**Comment by Vultraz** [comment]
As far as I know, the syntax you fixed has never been valid.

**Comment by GregoryLundberg** [comment]
It came from here: https://github.com/wesnoth/wesnoth/commit/8ee34c39b2cfd30cf0ba49dadaa8643d438a1fa9

**Comment by Vultraz** [comment]
Typos, then.

**Comment by CelticMinstrel** [comment]
> 

Why is it shocking? I imagine someone changed the API so we should expect breakage.


It's shocking that someone committed that code in the first place.

**Pull request merged**
