### PR TITLE
Add new units as discussed on the forums.

### PR DESCRIPTION
**Pull request by Pentarctagon**
See https://forums.wesnoth.org/viewtopic.php?f=32&t=47721&start=450#p625660

All images but the young roc/roc would remain under the GPL, since Kwandulin based them on images by Sleepwalker and I wasn't able to contact him about using the CC BY-SA for them.  The young roc base and attack sprites are under the CC BY-SA, and are by Vyncyn(forum username).

---

I wasn't sure what to do with the L2 Roc, since it still needs a sprite, so it uses the L1's sprite.

todo: Vyncyn has not yet replied about what name he'd prefer in the credits.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Why is the roc and its images filed under Dunefolk rather than Monsters? Also I think maybe the gryphon names might be more appropriate than the ogre names? Or they could get their own name generator.

But anyway this is nice to see!

**Comment by Pentarctagon** [comment]
The rocs I put under Dunefolk, since it was mentioned a few times about maybe replacing the falcons with the rocs, or merging the unit lines, or something along those lines.  I have no particular preference either way, though.

The rocs also have the Ogre name generator, since that's what the falcons use.

**Comment by CelticMinstrel** [comment]
Ah, I see. Kinda weird for Falcons too, but I guess that's out of scope for this PR. 

I do think rocs should not be in the Dunefolk folder though since they're not technically Dunefolk, merely associated with them; this is done in other cases too, like the bats.

**Comment by Pentarctagon** [comment]
Alright, should be good now then.  Vyncyn has not yet replied to my PM about what he wants to be called in the credits though, so I don't know whether it would be preferred to merge now and update later if needed, or wait for a reply.

**Comment by CelticMinstrel** [comment]
Credits not being updated isn't a blocker for merging in my opinion.

**Pull request merged**
