### PR TITLE
Updated to Lua 5.4.6

### PR DESCRIPTION
**Pull request by Vultraz**
CI run.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I can't seem to find a changelog for this release… is there one?

**Comment by Vultraz** [comment]
From the commit for the "emergency" 5.4.6 release:

```
"Emergency" new version 5.4.6
'lua_resetthread' is back to its original signature, to avoid
incompatibilities in the ABI between releases of the same version.
New function 'lua_closethread' added with the "correct" signature.
```

For 5.4.5, we have https://github.com/lua/lua/compare/v5.4.4...v5.4.5

**Comment by CelticMinstrel** [comment]
Okay, so it sounds like basically "nothing", and shouldn't cause any problems.

**Comment by Vultraz** [comment]
Just noting this updates from 5.4.4.

**Pull request merged**
