### PR TITLE
 preserve traslatable strings in simple_wml.

### PR DESCRIPTION
**Pull request by gfgtdf**
This still has problmes especially related to chaching of simple_wml. But it fixes the most commen cases of "translatability lost in networked mp"

### CODE REVIEW

**Comment by Wedge009** [comment]
I finally got around to looking at this again. I took the branch you put into my repository and rebased to to master. I then reproduced bug #22918 the only way I knew previously - play the Legend of Wesmere MP campaign and advance to the second scenario.

Unfortunately I haven't yet seen any discernible difference between master and the simple_wml_string branch. Upon reaching the second scenario, observers' story text revert to the original English (the original bug reported). Units' descriptions and everything else seems to remain on the chosen translation (French, in my case) for both master and branch.

Am I looking at/for the wrong thing? What difference might/should I observe with this PR?

**Comment by gfgtdf** [comment]
I just tested and i observed that too. Since it also more than a year since this commit were made my first guess woudl be that something else has changed during that time.

**Comment by Wedge009** [comment]
Okay, thanks. I'll leave this for the time being, then.

**Comment by CelticMinstrel** [comment]
I have to ask, why on earth were you taking `sizeof(string-constant)`? The result of this expression will be the size, in bytes, of a native pointer on your platform. I highly doubt that's what was intended.

**Comment by AI0867** [comment]
Actually, when applied to a string literal or character array defined in the same scope, they sizeof does return the number of bytes required to represent the string (including NUL).

It's just that passing a char array around causes it to decay to a char pointer.

http://stackoverflow.com/q/1392200/145413

**Comment by CelticMinstrel** [comment]
Huh, okay. I didn't know that.

**Comment by gfgtdf** [comment]
Hmm i now wonder whether this is the right way to fix this problem, another was that came into my mind, not to parse incomgind wml docuemnts into simple_wml object but in c++ packet pobjects instead (like one subclass for every packagetype) wml content that doenst need to be parsed by the server would then be  just skipped, read into a big string/buffer and resended, so that for example when receving a new scenario the [store_next_scenario] could look like 
```
[store_next_scenario]
 max_turns=1
 current_turn=1
 [side]
  controller=human
  player=gfgtdf
 [/side]
 [side]
  controller=ai
  player=gfgtdf
 [/side]
 ... other data the server needs to know.
[/store_next_scenario]
[scenario]
 .. th orignal [scenario] content
[/scenario]
```

which would the correspond to a store_next_scenario class
```
struct store_next_scenario_packet : public incoming_packet
{
typedef std::pair<std::string, CONTROLLER> tside;
std::vector<tside> sides_;
int current_turn_;
int max_turn_;
buffer scenario_data_;
};
```
So that the parsing code for the store_next_scenario packet woudl then parse its wml until the [/store_next_scenario] and put the rest into store_next_scenario_packet ::scenario_data_ without paring it just resending it to the other players.

**Comment by Vultraz** [comment]
Should this be closed?

**Comment by gfgtdf** [comment]
hmm maybe, i am currently in favor of the second approach i mentioned in my last post. But it would require a quitge large reefactor of how teh server processes wml, so it's not possibel for 1.14

**Comment by gfgtdf** [comment]
ok i somhow ran into #1420 again so i decided to fix this pr, turned out there were just some stupid mistakes like inverted conditions in .https://github.com/wesnoth/wesnoth/pull/342/commits/b87b9e16cc16c3a53068abf8cd7aed8e74438974#diff-72f22c18964f3ffe6b65b320ba5a7c01R229 

i think i can make this working soon, as said in the code comments it dosnt cover all of the cases, but its sure an improvement.

**Pull request merged**
