### PR TITLE
THoT: Create heroes if they don't exist

### PR DESCRIPTION
**Pull request by amakriLexa04**
Resolves [1.15 THoT Movrur should be created if he doesn't exist #5520 ](https://github.com/wesnoth/wesnoth/issues/5520) as well as adds few small fixes.

### CODE REVIEW

**Comment by amakriLexa04** [comment]
Well, now I don't understand what it doesn't like...

**Comment by Wedge009** [comment]
I've seen this kind of check failure before but I'm not sure what's going on either.

**Comment by gfgtdf** [comment]
did you try running wmlindent?

**Comment by amakriLexa04** [comment]
I didn't even know there was such a thing. Looks like a very useful tool

**Review by knyghtmare — APPROVED** [review]
Looks okay. Would be a merger commit though.

Reason: `update characters.cfg` twice

**Comment by soliton-** [comment]
This should certainly be squashed. "Update characters.cfg" is not a useful commit message whether it's there once or multiple times.

**Pull request merged**
