### PR TITLE
SCons and CMake all tools

### PR DESCRIPTION
**Pull request by GregoryLundberg**
Refactor sdl/utils.cpp into two files. This allows building all tools without pulling in the entire engine.

Note that the size of some targets could be further reduced by additional refactoring in other areas.

SCons and CMake can now build all of the following targets:

* campaignd
* create_images
* cutter
* exploder
* schema_generator
* schema_validator
* test
* wesmage
* wesnoth
* wesnothd

----

This PR duplicates a commit from PR 863 to add missing targets to .gitignore.

### CODE REVIEW

**Comment by aginor** [comment]
I don't really like this PR, there's some functions that are put into a new file, whereas the related functions are kept in the old file. That means that the SDL-utility code is suddenly split between two separate file, but there's no clear definition of responsibility between them.

**Comment by GregoryLundberg** [comment]
My preferred solution would be one function to one file. I decided to be more conservative and only make two files.

If there are functions you would prefer moved to the new file, list them and I'll move them.

At present, the new file is the minimum set needed for all tools to build without turning all tools into full copies of the 'wesnoth' target.

**Comment by aginor** [comment]
Ok, please ensure that all colour/colour space manipulation functions are in one file (this includes neutral surface stuff).
Please ensure that surface manipulation functions are all in the same file. By surface manipulation, i mean anything that changes actual pixel values. Examples of this would be stretching, mirroring, blitting, resizing, removing/altering a colour channel or alpha.

**Comment by GregoryLundberg** [comment]
I'll look at that but I think the problem is some of the pixel manipulation refers to the scripting engine, which pulls in all of WML, Lua and the entire GUI.

**Comment by aginor** [comment]
Thank you

**Comment by CelticMinstrel** [comment]
I guess that's my fault for adding the ~ALPHA() formula thing, huh...

**Comment by GregoryLundberg** [comment]
Not really. It's a community fault for being more concerned about keeping the number of files small instead of the executable program.

I'm sitting, staring at my screen, wondering why I'm moving code around to make what I can build as a 31K-byte program go from 2.1M-bytes to 2.2M-bytes and telling my self it's progress because, hey, at least it's not the 20M-bytes it was when I started.

**Comment by GregoryLundberg** [comment]
I'm not going to make any changes. The idea was to get the tools working so they could be evaluated. Most likely, from what I'm hearing, the more proper course of action would be to delete all sources and build tools for: create_images cutter exploder schema_generator schema_validator and wesmage.

**Comment by aginor** [comment]
@CelticMinstrel: The formula things would best be put somewhere else too, they don't actually have anything to do with the surface or drawing routines, except using them.

**Comment by aginor** [comment]
@GregoryLundberg I'm going to close this PR in that case, since I do not think that the changes you have proposed here makes sense from a concerns (as in separation of concerns) point of view. An alternative approach to reach your goal would be to get rid of the other code that has crept into the sdl utilities instead.

**Comment by jyrkive** [comment]
Related to commit 5e2af01fbadbed8a0182a5fe9bd3b23ef95317c3 where I split font/constants.cpp to stop it from depending on sdl/utils.cpp. @GregoryLundberg took the opposite approach of splitting sdl/utils.cpp instead.

**Comment by GregoryLundberg** [comment]
The problem with the approach is it's half-assed, not that it doesn't show proper separation of concern.

The source layout of Wesnoth forces inefficiency and waste.

The correct solution is to separate every function into its own source file.  This would allow the linker to properly select only those parts required. And it would prevent future errors causing a change unrelated to the program causing massive bloat as occurred here.

I took the approach of only separating what absolutely needed to be separated in the hope it would garner less complaints than actually fixing the underlying issue and separating the source file into dozens of files.

The discussions on this matter lead me to believe that a better PR would be to eliminate the following tools entirely: create_images cutter exploder schema_generator schema_validator wesmage; leaving only the following targets: campaignd wesnoth wesnothd; and moving all dead code from the remaining file and moving it elsewhere to allow the entire tools directory to be eliminated.

Further discussions lead me to conclude that any future work on increasing efficiency and reducing waste in the software are meaningless and would be unwelcome.

**Comment by GregoryLundberg** [comment]
Therein lies the problem: nobody cares.

You see those tools and think it's a waste because they're not used at all.

You see the daemons and think it's a waste because they're not used to any extent (that we know of) outside the Wesnoth-controlled servers.

What you don't see is this waste indicates two things:

 * a misunderstanding of how the tools (in this case, the linker) work and

 * a larger problem which almost certainly effects the only program left: wesnoth

Would it take wesnoth from a 20M program to a 2M program? Certainly not. But it would not surprise me if properly organizing the source code to both make it more efficient to compile, link and deploy, and make it easier for programmers to work on, paid off significantly.

**Comment by CelticMinstrel** [comment]
Just because no-one uses the tools doesn't mean they should be deleted; if fixed, maybe they'd be useful enough that someone _would_ use them.

I personally have no problem with merging this, though it seems Aginor disagrees? (Though the PR has not been closed, so I dunno.)

**Comment by shikadilord** [comment]
I don’t believe arbitrarily (from the programmer’s POV, not the compiler’s) splitting code without clear guidelines to follow *for future code* is a maintainable approach.

And yes, for better or for worse Wesnoth has been built with fast (as in writing, not compiling) coding in mind instead of maximum efficiency and optimization. For a project that relies on volunteers from all over the world, most of them without a permanent or lasting stay, I’d see this as a good thing rather than something to summarily dismiss as “half-assed”.

Full disclosure: We’ve had at least two unfortunate situations in the past where people have come and changed and eventually broken everything with the intention of optimizing code, only to disappear as soon as things get FUBAR and thus leave the rest of the team faced with a choice between blindly reverting full commits or cherry-picking individual bits to revert in order to make Wesnoth usable again. On the first occasion it was the older AI engine that isn’t around anymore, and on the second it was micro-optimizations of the WML `config` type and users of `std::string` and `t_string` throughout the code base. Arguably I could count a third incident where someone tried wiring a custom memory allocator into the codebase, although that was a more controlled experiment guarded behind a conditional build option. I’d be tempted to add to this list the OpenMP support code, which is completely unmaintained and probably has only continued to work without breaking builds by sheer luck, but is likely to not be as good as it could be otherwise if someone on the team actually understood how to use OpenMP correctly and deploy more code using it whenever possible (the official Windows builds enable it).

Personally, taking all this into account I wouldn’t feel comfortable with the idea of making profound changes to how we manage our code unless you are also willing to take the time to properly educate people on the mistakes that they should avoid from now on, or act as a general maintainer and oversee all code changes forever (which is definitely a no go given the hit-by-a-bus principle I’ve mentioned on IRC several times). I apologize if I seem biased and tainted by past disasters, but having been part of the team for 9 years I’d like to believe I understand a bit better how social dynamics intermingle with the code production process around here and why people might seem reluctant to certain kind of extensive changes with long-lasting impact.

**Pull request closed without merging**
