### PR TITLE
AI: add [filter_own] to all candidate actions

### PR DESCRIPTION
**Pull request by mattsc**
This allows restricting the CA to only a subset of the units. It is a first step toward solving Issue #2349, which calls for adding `[filter_own]` tags to all candidate actions. In my experience, it is one of the most serious shortcomings of the default AI. See #2349 for more information and additional comments.

So far, this is only implemented for the move-to-targets CA, as I want to see if there are comments before I add it to the other CAs as well.

`[filter_own]` is chosen as the tag name, because that's what is used for the only CA (combat) for which this exists already.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Looks pretty simple! But that's not a bad thing or anything.

If I'm not mistaken, doesn't this actually add it to every candidate action? (But other CAs just ignore it.)

**Comment by mattsc** [comment]
> Looks pretty simple! But that's not a bad thing or anything.

Agreed on both parts of that.  I was quite pleased to find that it was this simple.

> If I'm not mistaken, doesn't this actually add it to every candidate action? (But other CAs just ignore it.)

Yes, you're right.  I was not clear in my description.  I am trying to do this in a way that will work with all CAs, but I am only applying it to the MtT CA so far.  I just wanted to get this out to see if there were comments before going through the steps for all the CAs.  The main hassle is actually testing this, specifically setting up test cases that make it clear that this is working.

**Comment by mattsc** [comment]
I have hit the limit of my C++ knowledge yet again ...

In 31ec24e9f0, the first commit of this PR, I define a function `is_allowed_unit()` as part of the 'candidate_action' class.  I have successfully used and tested this for all but one C++ engine CA (locally; except for the MtT CA included in the commit above, the changes are not committed yet).

The one remaining CA is 'combat' and I need to include `is_allowed_unit()` in [this conditional](https://github.com/wesnoth/wesnoth/blob/master/src/ai/default/aspect_attacks.cpp#L85).  At which point the compiler complains that it does not know the function, of course.  I know why it is complaining, what I don't seem to be able to figure out is how to get this information (context?) there without compromising something else.  I've tried a bunch of things but my lack of knowledge of C++ is hitting hard here and I just don't seem to be able to get it even close to right.  Any help would be much appreciated.

Besides that, I have this all done for the C++ CAs and just need to add it for the one Lua CA.

**Comment by mattsc** [comment]
I don't have the problem from my previous message solved yet, but wanted to commit the changes for the Lua CAs so that people can comment on them.  The method works, I've tested it, but I'm not sure if that's the best way to go about it.

FTR, I am planning to clean up and squash the commits later (and fix typos in commit messages etc.)

**Comment by CelticMinstrel** [comment]
I'm thinking perhaps that function should just take the filter as a parameter.

**Comment by mattsc** [comment]
I did some investigation into @CelticMinstrel's last suggestion.  It's certainly possible to do it that way, but because of the way how the code handles aspects, it's quite messy.  In the end, I did this differently and slightly inefficiently, but as this is only a fall-back option for consistency with other CAs anyway, I think that's acceptable.  See the comment in a3f0ac2d.

The only thing left now is using the filter in the high_xp_attack Lua CA, but that's trivial.

I'd still appreciate if somebody could look over 87bbee97d.  I'm not sure if that is all "clean" C++ code.

**Comment by CelticMinstrel** [comment]
I can't really see any notable issues with it.

**Comment by mattsc** [comment]
Thanks.

I will squash the commits, wait for the checks to go through, and then merge this; probably later today.  I'll also update the changelog and the wiki.

**Comment by mattsc** [comment]
Hmm, actually ...  I'm going to add this to the Experimental AI and the `CUSTOMIZABLE_EXPERIMENTAL_AI` macro as well before merging.  While I originally made this feature request for custom AI creation reasons, there are definitely use cases for using this in scenarios/modifcations via WML only, without every touching the AI code.  So I might as well anticipate somebody making this feature request.

Adding this to the ExpAI CAs is simple anyway with the changes already made.  It will take much more time testing that I did it correctly than changing the code.

**Comment by mattsc** [comment]
Alright, this should be all.  I will merge this once the checks have passed.

For the record, I did not add this as an option to the `CUSTOMIZABLE_EXPERIMENTAL_AI` macro. The use of this feature is mostly in applying it to individual CAs, so providing a macro that applies it to all CAs does not really make sense.

**Pull request merged**
