### PR TITLE
Bump macOS target, drop boost::variant and boost::any compat

### PR DESCRIPTION
**Pull request by Vultraz**
Bumps macOS target to ~~10.15 as discussed in #9031~~ 10.13.

### CODE REVIEW

**Comment by gfgtdf** [comment]
Does is correspond to xcode 11 or xcode 12 ?

**Comment by CelticMinstrel** [comment]
I don't see anything wrong with this change, but I'm against merging it. This is something that should be deferred until we bump the version requirement for a different, more practical reason. We shouldn't bump the minimum required version solely so that we can "clean up" compatibility code.

**Comment by Pentarctagon** [comment]
Fixing potential UB when dereferencing an optional would good to be able to do, though this PR doesn't do that part.

**Comment by Vultraz** [comment]
Once this was merged I can revert 688b6b3cd1b51f4c264955da583b6795c47a478e. Having the cleanup here was both to ensure that similar code passed CI (since, as far as I can tell, the reason for `optional::value` and `variant` et-al having issues had to do with their throwing behavior) and to get it out of the way.

**Comment by Pentarctagon** [comment]
There are also other places that have the UB issue. Do you plan to fix those as well?

**Comment by Pentarctagon** [comment]
https://github.com/wesnoth/wesnoth/blob/7b54d42d4b8d94b8fb3afe377c617f2eb01a6653/.github/workflows/ci-main.yml#L254 can also be removed - that was added since the newer, default xcode version on the CI image only supported 10.13+.

**Comment by Vultraz** [comment]
> There are also other places that have the UB issue. Do you plan to fix those as well?

Do you have specific ones in mind? I’ll look for others, but if you remember a specific case that would be useful.

**Comment by Pentarctagon** [comment]
Not specific, but it'd mean looking through the results of:
```
grep -Iirn 'std::optional'
image_modifications.cpp:1058:std::optional<std::pair<point, uint8_t>> parse_scale_args(std::string_view args)
enum_base.hpp:57:	static constexpr std::optional<enum_type> get_enum(const std::string_view value)
enum_base.hpp:73:	static constexpr std::optional<enum_type> get_enum(unsigned long value)
ai/lua/lua_object.hpp:292:		std::optional<ai_target::type> type = ai_target::type::xplicit;
game_board.hpp:155:	std::optional<std::string> replace_map(const gamemap & r);
gui/auxiliary/typed_formula.hpp:130:	std::optional<std::string> formula_;
gui/dialogs/attack_predictions.cpp:130:	std::optional<decltype(ctx)> opp_ctx;
gui/dialogs/drop_down_menu.hpp:57:		std::optional<bool> checkbox;
gui/dialogs/drop_down_menu.hpp:63:		std::optional<std::string> image;
gui/dialogs/drop_down_menu.hpp:69:		std::optional<t_string> details;
gui/dialogs/editor/generate_map.hpp:46:	std::optional<uint32_t> get_seed();
gui/dialogs/editor/generate_map.cpp:117:std::optional<uint32_t> editor_generate_map::get_seed()
gui/dialogs/loading_screen.hpp:140:	std::optional<decltype(std::chrono::steady_clock::now())> animation_start_;
gui/widgets/tree_view.hpp:170:	std::optional<decltype(node_definitions_)::const_iterator> get_node_definition(const std::string& id) const
gui/widgets/tree_view.hpp:174:		return def != node_definitions_.end() ? std::optional{def} : std::nullopt;
gui/widgets/listbox.cpp:346:	std::optional<unsigned> vertical_scrollbar_position, horizontal_scrollbar_position;
utils/from_chars.hpp:22:std::optional<T> from_chars(std::string_view str, int base = 10)
utils/from_chars.hpp:27:	return ec == std::errc{} ? std::optional{result} : std::nullopt;
utils/optional_reference.hpp:25: * Since std::optional (as of C++17 at least) does not support reference types (see [1]),
utils/optional_reference.hpp:26: * the only way to use those is std::optional<std::reference_wrapper<T>>. However, this makes
utils/optional_reference.hpp:100:	std::optional<std::reference_wrapper<T>> opt_;
utils/config_filters.cpp:77:bool utils::config_filters::int_matches_if_present(const config& filter, const config& cfg, const std::string& attribute, std::optional<int> def)
utils/config_filters.cpp:95:	const config& filter, const config& cfg, const std::string& attribute, const std::string& opposite, std::optional<int> def)
utils/config_filters.cpp:118:bool utils::config_filters::double_matches_if_present(const config& filter, const config& cfg, const std::string& attribute, std::optional<double> def)
utils/config_filters.hpp:43:bool double_matches_if_present(const config& filter, const config& cfg, const std::string& attribute, std::optional<double> def = std::nullopt);
utils/config_filters.hpp:44:bool int_matches_if_present(const config& filter, const config& cfg, const std::string& attribute, std::optional<int> def = std::nullopt);
utils/config_filters.hpp:65:	const config& filter, const config& cfg, const std::string& attribute, const std::string& opposite, std::optional<int> def = std::nullopt);
sound.cpp:199:std::optional<unsigned int> get_current_track_index()
game_events/handlers.cpp:259:					std::optional<decltype(ctx)> opp_ctx;
game_events/menu_item.hpp:165:	std::optional<hotkey::wml_hotkey_record> hotkey_record_;
game_events/action_wml.cpp:617:	std::optional<std::string> errmsg = resources::gameboard->replace_map(map);
font/font_description.hpp:57:	std::optional<std::string> bold_name; //If we are using another font for styled characters in this font, rather than SDL TTF method
font/font_description.hpp:58:	std::optional<std::string> italic_name;
synced_context.hpp:195:		std::optional<int> lua_;
lexical_cast.hpp:138:	To operator()(From value, std::optional<To> fallback) const
lexical_cast.hpp:169:	std::string operator()(From value, std::optional<std::string>) const
lexical_cast.hpp:194:	long long operator()(From value, std::optional<long long> fallback) const
lexical_cast.hpp:219:	long long operator()(const std::string& value, std::optional<long long> fallback) const
lexical_cast.hpp:258:	To operator()(From value, std::optional<To> fallback) const
lexical_cast.hpp:282:	To operator()(const std::string& value, std::optional<To> fallback) const
lexical_cast.hpp:324:	To operator()(From value, std::optional<To> fallback) const
lexical_cast.hpp:348:	To operator()(const std::string& value, std::optional<To> fallback) const
lexical_cast.hpp:401:	unsigned long long operator()(From value, std::optional<unsigned long long> fallback) const
lexical_cast.hpp:427:	unsigned long long operator()(const std::string& value, std::optional<unsigned long long> fallback) const
lexical_cast.hpp:466:	To operator()(From value, std::optional<To> fallback) const
lexical_cast.hpp:490:	To operator()(const std::string& value, std::optional<To> fallback) const
lexical_cast.hpp:529:	bool operator()(const std::string& value, std::optional<bool>) const
lexical_cast.hpp:551:	bool operator()(From value, std::optional<bool>) const
game_initialization/multiplayer.cpp:70:	mp_manager(const std::optional<std::string> host);
game_initialization/multiplayer.cpp:160:mp_manager::mp_manager(const std::optional<std::string> host)
generators/lua_map_generator.hpp:38:	virtual std::string create_map(std::optional<uint32_t> randomseed) override;
generators/lua_map_generator.hpp:39:	virtual config create_scenario(std::optional<uint32_t> randomseed) override;
generators/map_generator.cpp:30:config map_generator::create_scenario(std::optional<uint32_t> randomseed)
generators/map_generator.cpp:36:std::string map_generator::create_map(std::optional<uint32_t> randomseed)
generators/map_generator.hpp:67:	virtual std::string create_map(std::optional<uint32_t> randomseed = {}) = 0;
generators/map_generator.hpp:69:	virtual config create_scenario(std::optional<uint32_t> randomseed = {});
generators/default_map_generator.cpp:76:std::string default_map_generator::create_map(std::optional<uint32_t> randomseed)
generators/default_map_generator.cpp:81:std::string default_map_generator::generate_map(std::map<map_location,std::string>* labels, std::optional<uint32_t> randomseed)
generators/default_map_generator.cpp:169:config default_map_generator::create_scenario(std::optional<uint32_t> randomseed)
generators/cave_map_generator.hpp:35:	std::string create_map(std::optional<uint32_t> randomseed = {});
generators/cave_map_generator.hpp:36:	config create_scenario(std::optional<uint32_t> randomseed = {});
generators/cave_map_generator.hpp:41:		cave_map_generator_job(const cave_map_generator& params, std::optional<uint32_t> randomseed = {});
generators/default_map_generator.hpp:53:	std::string create_map(std::optional<uint32_t> randomseed) override;
generators/default_map_generator.hpp:54:	config create_scenario(std::optional<uint32_t> randomseed) override;
generators/default_map_generator.hpp:57:	std::string generate_map(std::map<map_location,std::string>* labels, std::optional<uint32_t> randomseed);
generators/lua_map_generator.cpp:68:std::string lua_map_generator::create_map(std::optional<uint32_t> seed)
generators/lua_map_generator.cpp:84:config lua_map_generator::create_scenario(std::optional<uint32_t> seed)
generators/cave_map_generator.cpp:76:std::string cave_map_generator::create_map(std::optional<uint32_t> randomseed)
generators/cave_map_generator.cpp:82:config cave_map_generator::create_scenario(std::optional<uint32_t> randomseed)
generators/cave_map_generator.cpp:88:cave_map_generator::cave_map_generator_job::cave_map_generator_job(const cave_map_generator& pparams, std::optional<uint32_t> randomseed)
about.hpp:63:std::optional<credits_data::const_iterator> get_campaign_credits(const std::string& campaign);
display.cpp:2643:	std::optional<unit_drawer> drawer{};
log.hpp:162:std::optional<bool> log_dir_writable();
about.cpp:99:std::optional<credits_data::const_iterator> get_campaign_credits(const std::string& campaign)
about.cpp:103:	return res != parsed_credits_data.end() ? std::optional{res} : std::nullopt;
game_launcher.hpp:152:	std::optional<savegame::load_game_metadata> load_data_;
filesystem.cpp:677:static std::optional<std::string> get_games_path()
filesystem.cpp:681:	std::optional<std::string> path = std::nullopt;
filesystem.cpp:722:		std::optional<std::string> games_path = get_games_path();
filesystem.cpp:740:		std::optional<std::string> games_path = get_games_path();
serialization/schema_validator.hpp:184:	std::optional<std::map<std::string, wml_key>> find_mandatory_keys(const wml_tag* tag, const config& cfg) const;
serialization/schema_validator.hpp:185:	std::optional<std::map<std::string, wml_key>> find_mandatory_keys(
serialization/schema_validator.cpp:503:std::optional<std::map<std::string, wml_key>> schema_validator::find_mandatory_keys(
serialization/schema_validator.cpp:510:std::optional<std::map<std::string, wml_key>> schema_validator::find_mandatory_keys(
serialization/preprocessor.hpp:64:			std::optional<DEP_LEVEL> dep_lvl, const version_info& dep_ver)
serialization/preprocessor.hpp:91:	std::optional<DEP_LEVEL> deprecation_level;
serialization/string_utils.cpp:839:std::pair<std::string, std::optional<std::string>> parse_range_internal_separator(const std::string& str)
serialization/preprocessor.cpp:1193:			std::optional<DEP_LEVEL> deprecation_level;
serialization/schema/type.cpp:55:	std::optional<config::const_child_itors> composite_range;
replay_controller.hpp:86:	std::optional<REPLAY_VISION> vision_;
log.cpp:63:static std::optional<bool> is_log_dir_writable_ = std::nullopt;
log.cpp:275:std::optional<bool> log_dir_writable()
map/map.hpp:116:		std::optional<t_translation::terrain_code> terrain_;
scripting/mapgen_lua_kernel.hpp:35:	std::string create_map(const char * prog, const config & generator, std::optional<uint32_t> seed); // throws game::lua_error
scripting/mapgen_lua_kernel.hpp:36:	config create_scenario(const char * prog, const config & generator, std::optional<uint32_t> seed); // throws game::lua_error
scripting/mapgen_lua_kernel.hpp:44:	std::optional<uint32_t> random_seed_;
scripting/mapgen_lua_kernel.hpp:45:	std::optional<std::mt19937> default_rng_;
scripting/mapgen_lua_kernel.cpp:187:	std::optional<lua_pathfind_cost_calculator> calc;
scripting/mapgen_lua_kernel.cpp:325:std::string mapgen_lua_kernel::create_map(const char * prog, const config & generator, std::optional<uint32_t> seed) // throws game::lua_error
scripting/mapgen_lua_kernel.cpp:341:config mapgen_lua_kernel::create_scenario(const char * prog, const config & generator, std::optional<uint32_t> seed) // throws game::lua_error
scripting/lua_gui2.cpp:209:	std::optional<button_style> style;
scripting/push_check.hpp:344:		std::optional<typename T::type> val = T::get_enum(str);
widgets/menu.hpp:137:	virtual void set_items(const std::vector<indented_menu_item>& items, std::optional<std::size_t> selected);
widgets/menu.hpp:204:	mutable std::optional<int> widest_row_width_;
widgets/menu.cpp:121:void menu::set_items(const std::vector<indented_menu_item>& items, std::optional<std::size_t> selected)
editor/map/map_context.hpp:304:	std::optional<int> get_xp_mod() const { return xp_mod_; }
editor/map/map_context.hpp:500:	std::optional<config> previous_cfg_;
editor/map/map_context.hpp:503:	std::optional<int> xp_mod_;
editor/map/map_context.hpp:504:	std::optional<bool> victory_defeated_;
units/frame.hpp:54:	std::optional<color_t> text_color;
units/frame.hpp:55:	std::optional<color_t> blend_with;
units/frame.hpp:118:	std::optional<color_t> text_color_;
units/frame.hpp:119:	std::optional<color_t> blend_with_;
units/frame.hpp:180:	std::optional<color_t> text_color_;
units/frame.hpp:181:	std::optional<color_t> blend_with_;
units/udisplay.cpp:625:	std::optional<decltype(ctx)> opp_ctx;
units/abilities.cpp:2000:	std::optional<int> max_value = std::nullopt;
units/abilities.cpp:2001:	std::optional<int> min_value = std::nullopt;
units/unit.hpp:2049:	std::optional<std::string> usage_;
units/unit.hpp:2050:	std::optional<std::string> halo_;
units/unit.hpp:2051:	std::optional<std::string> ellipse_;
help/help_topic_generators.cpp:77:	std::optional<ter_iter> last_change_pos;
help/help_menu.cpp:168:	std::optional<std::size_t> selected;
help/help_impl.cpp:1670:void push_tab_pair(std::vector<help::item> &v, const std::string &s, const std::optional<std::string> &image, unsigned padding)
help/help_impl.hpp:423:void push_tab_pair(std::vector<help::item> &v, const std::string &s, const std::optional<std::string> &image = {}, unsigned padding = 0);
game_state.hpp:64:	std::optional<end_level_data> end_level_data_;
mp_game_settings.hpp:76:		std::optional<version_info> version;
mp_game_settings.hpp:77:		std::optional<version_info> min_version;
server/wesnothd/server.hpp:77:	void send_to_lobby(simple_wml::document& data, std::optional<player_iterator> exclude = {});
server/wesnothd/server.hpp:84:	void send_server_message_to_lobby(const std::string& message, std::optional<player_iterator> exclude = {});
server/wesnothd/server.hpp:85:	void send_server_message_to_all(const std::string& message, std::optional<player_iterator> exclude = {});
server/wesnothd/server.hpp:214:	void update_game_in_lobby(const game& g, std::optional<player_iterator> exclude = {});
server/wesnothd/game.cpp:772:std::optional<player_iterator> game::kick_member(const simple_wml::node& kick, player_iterator kicker)
server/wesnothd/game.cpp:804:std::optional<player_iterator> game::ban_user(const simple_wml::node& ban, player_iterator banner)
server/wesnothd/game.cpp:1547:void game::send_user_list(std::optional<player_iterator> exclude)
server/wesnothd/game.cpp:1635:void game::send_to_players(simple_wml::document& data, const Container& players, std::optional<player_iterator> exclude)
server/wesnothd/game.cpp:1644:void game::send_data(simple_wml::document& data, std::optional<player_iterator> exclude)
server/wesnothd/game.cpp:1651:		std::optional<player_iterator> exclude)
server/wesnothd/game.cpp:1693:void game::send_observerjoins(std::optional<player_iterator> player)
server/wesnothd/game.cpp:1932:std::optional<player_iterator> game::find_user(const simple_wml::string_span& name)
server/wesnothd/game.cpp:1942:void game::send_and_record_server_message(const char* message, std::optional<player_iterator> exclude)
server/wesnothd/game.cpp:1953:void game::send_server_message_to_all(const char* message, std::optional<player_iterator> exclude)
server/wesnothd/game.cpp:1960:void game::send_server_message(const char* message, std::optional<player_iterator> player, simple_wml::document* docptr) const
server/wesnothd/server.cpp:1990:void server::send_to_lobby(simple_wml::document& data, std::optional<player_iterator> exclude)
server/wesnothd/server.cpp:2000:void server::send_server_message_to_lobby(const std::string& message, std::optional<player_iterator> exclude)
server/wesnothd/server.cpp:2010:void server::send_server_message_to_all(const std::string& message, std::optional<player_iterator> exclude)
server/wesnothd/server.cpp:2971:void server::update_game_in_lobby(const wesnothd::game& g, std::optional<player_iterator> exclude)
server/wesnothd/game.hpp:31:typedef std::vector<std::optional<player_iterator>> side_vector;
server/wesnothd/game.hpp:246:	std::optional<player_iterator> kick_member(const simple_wml::node& kick, player_iterator kicker);
server/wesnothd/game.hpp:257:	std::optional<player_iterator> ban_user(const simple_wml::node& ban, player_iterator banner);
server/wesnothd/game.hpp:376:	void send_server_message_to_all(const char* message, std::optional<player_iterator> exclude = {});
server/wesnothd/game.hpp:380:	void send_server_message_to_all(const std::string& message, std::optional<player_iterator> exclude = {})
server/wesnothd/game.hpp:393:			const char* message, std::optional<player_iterator> player = {}, simple_wml::document* doc = nullptr) const;
server/wesnothd/game.hpp:398:			const std::string& message, std::optional<player_iterator> player = {}, simple_wml::document* doc = nullptr) const
server/wesnothd/game.hpp:410:	void send_and_record_server_message(const char* message, std::optional<player_iterator> exclude = {});
server/wesnothd/game.hpp:414:	void send_and_record_server_message(const std::string& message, std::optional<player_iterator> exclude = {})
server/wesnothd/game.hpp:428:	void send_to_players(simple_wml::document& data, const Container& players, std::optional<player_iterator> exclude = {});
server/wesnothd/game.hpp:436:	void send_data(simple_wml::document& data, std::optional<player_iterator> exclude = {});
server/wesnothd/game.hpp:610:	std::optional<player_iterator> current_player() const
server/wesnothd/game.hpp:710:			std::optional<player_iterator> exclude = {});
server/wesnothd/game.hpp:718:	void send_observerjoins(std::optional<player_iterator> player = {});
server/wesnothd/game.hpp:732:	std::optional<player_iterator> find_user(const simple_wml::string_span& name);
server/wesnothd/game.hpp:763:	void send_user_list(std::optional<player_iterator> exclude = {});
server/campaignd/server.cpp:233:std::optional<std::vector<std::string>> multi_find_illegal_names(const Vals&... args)
server/campaignd/server.cpp:238:	return !names.empty() ? std::optional(names) : std::nullopt;
server/campaignd/server.cpp:247:std::optional<std::vector<std::string>> multi_find_case_conflicts(const Vals&... args)
server/campaignd/server.cpp:252:	return !names.empty() ? std::optional(names) : std::nullopt;
server/campaignd/options.hpp:56:	std::optional<std::string> config_file;
server/campaignd/options.hpp:58:	std::optional<std::string> server_dir;
server/campaignd/options.hpp:60:	std::optional<unsigned short> port;
sound.hpp:123:std::optional<unsigned int> get_current_track_index();
picture.hpp:121:	std::optional<T> copy_from_cache(cache_type<T>& cache) const;
commandline_options.hpp:57:	std::optional<std::string> campaign;
commandline_options.hpp:59:	std::optional<int> campaign_difficulty;
commandline_options.hpp:61:	std::optional<std::string> campaign_scenario;
commandline_options.hpp:67:	std::optional<std::string> core_id;
commandline_options.hpp:71:	std::optional<std::string> data_dir;
commandline_options.hpp:86:	std::optional<std::string> debug_dot_domain;
commandline_options.hpp:88:	std::optional<std::string> debug_dot_level;
commandline_options.hpp:91:	std::optional<std::string> editor;
commandline_options.hpp:99:	std::optional<std::string> language;
commandline_options.hpp:104:	std::optional<std::vector<std::pair<lg::severity, std::string>>> log;
commandline_options.hpp:106:	std::optional<int> log_strict_level;
commandline_options.hpp:108:	std::optional<std::string> load;
commandline_options.hpp:110:	std::optional<std::string> logdomains;
commandline_options.hpp:116:	std::optional<std::vector<std::pair<unsigned int, std::string>>> multiplayer_ai_config;
commandline_options.hpp:118:	std::optional<std::vector<std::pair<unsigned int, std::string>>> multiplayer_algorithm;
commandline_options.hpp:120:	std::optional<std::vector<std::pair<unsigned int, std::string>>> multiplayer_controller;
commandline_options.hpp:122:	std::optional<std::string> multiplayer_era;
commandline_options.hpp:128:	std::optional<std::string> multiplayer_label;
commandline_options.hpp:130:	std::optional<std::vector<std::tuple<unsigned int, std::string, std::string>>> multiplayer_parm;
commandline_options.hpp:132:	std::optional<unsigned int> multiplayer_repeat;
commandline_options.hpp:134:	std::optional<std::string> multiplayer_scenario;
commandline_options.hpp:136:	std::optional<std::vector<std::pair<unsigned int, std::string>>> multiplayer_side;
commandline_options.hpp:138:	std::optional<std::string> multiplayer_turns;
commandline_options.hpp:140:	std::optional<int> max_fps;
commandline_options.hpp:160:	std::optional<std::vector<std::string>> preprocess_defines;
commandline_options.hpp:162:	std::optional<std::string> preprocess_input_macros;
commandline_options.hpp:164:	std::optional<std::string> preprocess_output_macros;
commandline_options.hpp:166:	std::optional<std::string> preprocess_path;
commandline_options.hpp:168:	std::optional<std::string> preprocess_target;
commandline_options.hpp:170:	std::optional<std::pair<int,int>> resolution;
commandline_options.hpp:172:	std::optional<unsigned int> rng_seed;
commandline_options.hpp:174:	std::optional<std::string> server;
commandline_options.hpp:176:	std::optional<std::string> username;
commandline_options.hpp:178:	std::optional<std::string> password;
commandline_options.hpp:180:	std::optional<std::string> render_image;
commandline_options.hpp:182:	std::optional<std::string> render_image_dst;
commandline_options.hpp:186:	std::optional<std::string> screenshot_map_file;
commandline_options.hpp:188:	std::optional<std::string> screenshot_output_file;
commandline_options.hpp:190:	std::optional<std::string> script_file;
commandline_options.hpp:192:	std::optional<std::string> plugin_file;
commandline_options.hpp:198:	std::optional<std::string> test;
commandline_options.hpp:210:	std::optional<std::string> usercache_dir;
commandline_options.hpp:214:	std::optional<std::string> userconfig_dir;
commandline_options.hpp:218:	std::optional<std::string> userdata_dir;
commandline_options.hpp:224:	std::optional<std::string> validate_addon;
commandline_options.hpp:226:	std::optional<std::string> validate_schema;
commandline_options.hpp:228:	std::optional<std::string> validate_wml;
commandline_options.hpp:230:	std::optional<std::string> validate_with;
commandline_options.hpp:232:	std::optional<std::string> output_file;
commandline_options.hpp:247:	std::optional<unsigned int> translation_percent;
actions/undo_action.hpp:26:		std::optional<int> lua_idx;
actions/attack.cpp:134:	std::optional<decltype(ctx)> opp_ctx;
actions/attack.cpp:284:	std::optional<decltype(ctx)> opp_ctx;
actions/attack.cpp:862:	std::optional<attack_type::specials_context_t> a_ctx, d_ctx;
picture.cpp:134:std::optional<T> locator::copy_from_cache(cache_type<T>& cache) const
picture.cpp:137:	return elem.loaded ? std::optional{elem.item} : std::nullopt;
game_board.cpp:292:std::optional<std::string> game_board::replace_map(const gamemap& newmap)
game_board.cpp:294:	std::optional<std::string> ret;
```
Not sure if Windows has something equivalent these days. It's not hard to find examples from that list though - ie there are a bunch in lexical_cast.hpp (all the `fallback` usage) and `commandline_options.hpp`.

**Comment by Vultraz** [comment]
That's not all of them, but it's a good chunk for now.

**Comment by gfgtdf** [comment]
I'd prefer is lexical_cast.c/hpp wasnt updated becasue 1) its not needed becasue all of those are befing an if making sure they're valid, 2) it would probably merging conflics with #8790

**Comment by gfgtdf** [comment]
wait, why does it target 10.13 now ?

**Comment by Vultraz** [comment]
10.13 is technically the minimum needed to support `variant`, `any`, and `optional::value`. I had forgotten that each 10.x was a major release not a point release, so in the interests of not arguing about what version o bump to I reverted to the minimum needed.

**Comment by Vultraz** [comment]
Dropped the last commit, I'll handle that separately.

**Comment by gfgtdf** [comment]
> What version do you need for https://github.com/wesnoth/wesnoth/pull/8790?

I actually don't know,  Acording to https://en.cppreference.com/w/cpp/compiler_support/17 "apple clang" still doesn't support it at all even thought clang 14 got what i need? The Entry is "Elementary string conversions" and the fourth row is apple clang, (the second is clang for comparision) . Maybe that page it outdated thought, not sure

**Comment by Vultraz** [comment]
Looking at https://developer.apple.com/xcode/cpp/#c++17, it looks like 10.15 is the minimum for integer conversions.

**Pull request merged**
