### PR TITLE
Filter weapon in [filter student/opponent/etc] ,rework [filter_(secon…  …d_)weapon and fix sidebar show(pre 1.16 string)

### PR DESCRIPTION
**Pull request by newfrenchy83**
this th 4th PR for resolve https://github.com/wesnoth/wesnoth/issues/4389, but also resolve https://github.com/wesnoth/wesnoth/pull/3642 for abilities used like specials.

i see what sidebar weapon don't follows mouseover when i use weapon abilities for "damage" or "attacks"

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I'm not clear on how this relates to #4481, is it a replacement, a supplement, or what?

**Comment by newfrenchy83** [comment]
It is a replecement but i wait what Pr pass cheks before to close.

**Comment by newfrenchy83** [comment]
@CelticMinstrel it seem what paying testing passed.

**Comment by newfrenchy83** [comment]
@CelticMinstrel I have 2 idea to submit:

1. use weapon->combat_ability for "leadership" instead to under_leadership.

2. add a optional min_value and max_value(active if !=0 only) for by example, using damage instead of regular resistance in particuliar condition  (filter_weapon and/or filter_opponent) and deprecate using of [filter_(second_)weapon]

i like haveyou're opinion before to commit change in this PR, please.

**Comment by CelticMinstrel** [comment]
Is `combat_ability` also used by weapon special abilities?

**Comment by newfrenchy83** [comment]
@CelticMinstrel No, leadership can not be used as a special weapon, I have indeed corrected shema validation accordingly, I wanted to use combat_ability for [leadership] to allow the use of all available filters for damage, which keeps the default d accumulation of values (if one unit is adjacent to a load capacity teacher and another teacher backstab, one will have a melee attack whose damage will be quadrupled instead of doubled) what leadership can avoid when we want to avoid this case and allow damage when this scenario is desired.

**Comment by newfrenchy83** [comment]
@jostephd , @CelticMinstrel , today december 2th, it remain not many time before pre1.16 string commit, could you review this PR please?

**Comment by jostephd** [comment]
@newfrenchy83 I'm sorry, but I am on a wesbreak. I don't expect to be reviewing or writing anything any time soon, unless it's a regression that I authored or merged. If this PR must get merged by string freeze, please ask for it to be labeled and milestoned appropriately.

**Comment by newfrenchy83** [comment]
@CelticMinstrel , @jostephd or someone, could you add this PR to pre 1.16string milestne and labeled this ?

**Comment by newfrenchy83** [comment]
all chek passed, finally

**Pull request closed without merging**
