### PR TITLE
add icon to windows installer and uninstaller

### PR DESCRIPTION
**Pull request by babaissarkar**
Add icons to the windows installer and uninstaller executable, which are currently using the default icon of NSIS.
This gives more authenticity and branding to the installer/uninstaller, and makes it look a bit more official.
PNG previews : (actual images are ico files)
icon-installer icon-uninstaller

### CODE REVIEW

**Review by loonycyborg — APPROVED** [review]

**Comment by Wedge009** [comment]
Good idea, I didn't even think about the +/- variations.

Not directly related, but there's a long-standing request in #1180 to differentiate 'development' releases with a different icon. Is that something you'd be interested in?

**Comment by babaissarkar** [comment]
> Not directly related, but there's a long-standing request in #1180 to differentiate 'development' releases with a different icon. Is that something you'd be interested in?

My idea would be to :
1. We decide on an icon
2. Somebody maintains different sets of icons in master and stable branches.

Step 2 could possibly be automated, for example, by a CI action that runs only on release that triggers another script. The second script swaps the icons. Not very sure about the details.

**Comment by babaissarkar** [comment]
Seems to be working as intended.
Capture4
Capture5
Capture6
Capture7
Capture9
Capture10

@Pentarctagon is it fine to merge this?

**Comment by Pentarctagon** [comment]
Sounds fine to me.

**Comment by CelticMinstrel** [comment]
> Seems to be working as intended.
> Capture4

Not exactly great that the + is covered by the shield, but…

**Comment by Wedge009** [comment]
This will only change 1.19 - is it too much of a change to back-port to 1.18?

**Comment by Pentarctagon** [comment]
I can't think of any reason this couldn't be backported.

**Pull request merged**
