### PR TITLE
SunOS 5.11/OpenIndiana build fixes

### PR DESCRIPTION
**Pull request by larb0b**
With these changes, Wesnoth builds and runs on SunOS 5.11, tested on OpenIndiana 2021.10.

### CODE REVIEW

**Comment by loonycyborg** [comment]
Buildsystem changes look fine to me.

**Comment by Wedge009** [comment]
@Pentarctagon Any objections to merging? As you said, the only one (we're aware of so far) who is affected by #6377 and benefits from this PR is the requester.

**Comment by Pentarctagon** [comment]
It looks like nothing happened to break in any of the other builds, so I'm good with it.

**Comment by Pentarctagon** [comment]
@larb0b For future reference as well, if you add `Fixes #6377` to the commit message, the issue #6377 will be automatically closed when the commit is merged.

**Comment by larb0b** [comment]
Ah right, forgot to do that. 

By the way, tested building Wesnoth with these patches on Solaris 11.4 and it works:

image

**Comment by CelticMinstrel** [comment]
I'm not sure it's even worth using conditional compilation in the first commit, as the change should still compile on any platform.

**Comment by Wedge009** [comment]
I think I understand what you mean. My guess is larb0b is being conservative in not wanting to potentially break the non-SunOS builds. There's no harm in merging this as-is and potentially including the socket library for other *NIX builds later is there?

**Comment by Pentarctagon** [comment]
A code comment would be just as effective in that case.

**Comment by Pentarctagon** [comment]
The CI jobs also check the configurations we ourselves use, so if it broke one of those we'd know before the PR is merged.

**Comment by Wedge009** [comment]
Would you prefer such a comment before merging then?

**Comment by larb0b** [comment]
> I think I understand what you mean. My guess is larb0b is being conservative in not wanting to potentially break the non-SunOS builds. There's no harm in merging this as-is and potentially including the socket library for other *NIX builds later is there?

Celtic was referring to the first commit, regarding utsname, not the socket stuff. `-lsocket` is only needed on SysV-style stuff like Solaris where it's a separate library, on most modern system's it's just part of libc. 



> I'm not sure it's even worth using conditional compilation in the first commit, as the change should still compile on any platform.
> 
> I guess it _does_ have the advantage of making it clear _why_ it's being declared in the C way but beyond that…

Yeah, it doesn't really matter.

**Comment by CelticMinstrel** [comment]
> I think I understand what you mean. My guess is larb0b is being conservative in not wanting to potentially break the non-SunOS builds. There's no harm in merging this as-is and potentially including the socket library for other *NIX builds later is there?

Yeah, as larb0b said, I was referring to the `struct utsname u;` line; sorry if that was unclear.

**Comment by Pentarctagon** [comment]
@larb0b So specifically, can you change the first commit to be just `struct utsname u;`?

**Comment by CelticMinstrel** [comment]
Possibly with a comment noting that the struct keyword is required to compile on SunOS?

**Comment by larb0b** [comment]
Done.

**Comment by Pentarctagon** [comment]
Alright, I'll let this run on the CI just to be sure, then merge after it finishes.

**Pull request merged**
