### PR TITLE
Three carpet terrains 

### PR DESCRIPTION
**Pull request by doofus-01**
This initial commit is for terrain-graphics WML, image alignment, and demo only; images are unshaded place-holders.  This is in reference to issue #2088 . I tried to make the carpet a pseudo-overlay, so that true overlays (*^Blah) can still be used, as shown in this screenshot.
carpets_000
I'll not try to make elaborately patterned Persian rugs, the purple will just have noisy texture.  I do plan to put more effort into shading the border, especially the right-angles, where some tassels would make sense.

### CODE REVIEW

**Comment by doofus-01** [comment]
An update, though I'm not committing yet.  I'd tried to introduce a vertical flip asymmetry for the corners so there was some perspective, but I don't think it's going to work; it makes the straight vertical strips look weird and doesn't really help the diagonal patches much.  Instead, I'll just have to make special corner cases, like the west-pointing corner of the larger diagonal patch, and the little fall-back corners will be straightened back to right angles.
screenshot_001

**Comment by doofus-01** [comment]
There are still some unfinished images, and at least one broken rule, but this is getting close.  Once the last of the images are shaded (next commit), I am fine with this being merged, but let me know if there are errors.  I plan to clone a lot of this to a "rougher" (brown, ragged edges instead of straight, guilded trim)
screenshot_002

**Comment by ln-zookeeper** [comment]
I'm a bit late to the party, but was there a specific reason why you wanted there to be need for an underlay, instead of letting the transitions go outside the carpet hexes (and thus making an underlay unnecessary)?

I mean, obviously your method has the benefit of allowing the carpets to be better used in narrow spaces, but it's also a pretty big limitation if a) you can only choose from a few pre-designated underlays or b) it's made into an overlay terrain and then you can't put braziers or whatever on it. Was there some other reason too?

**Comment by doofus-01** [comment]
I thought it looked more appropriate to have it be on top of a more solid terrain, rather than be, say, a repaint of the wooden floor.  Chasm and water transitions would need to be something roughly similar to what there currently is, so the underlayer limitation would still show up.  

The need for straight edges was also something of  a limitation, those usually spill over neighbouring hexes, I thought it would be better to pull the carpet back a bit so it didn't do that (though as can be seen in the previous screenshot, where the water is, I didn't always go far enough).

The original request was for an overlay, and in many ways that makes sense.  But that is also a big limitation, as you say, so I thought this was the best compromise.  More variations might be less of an issue if there were some way to make sub-menus in the editor?

**Comment by doofus-01** [comment]
added a WIP for a shaggy cave rug.  Not sure if the color shouldn't be shifted, also not sure if the Urb flagstones are the best underlayer, but this is it so far:
screenshot_004

**Comment by doofus-01** [comment]
Added the regular/red carpets, there's a screenshot on the forums:
https://forums.wesnoth.org/viewtopic.php?f=9&p=619387#p619379

This is "complete", but needs some clean-up.

**Comment by doofus-01** [comment]
I changed the cave rug underlayer to cave path, I think it looks slightly better.  I also changed the terrain codes to what I hope makes sense:
Icr -> **I**nterior, **c**arpet, **r**oyal
Icn -> **I**nterior, **c**arpet, **n**ormal
Urc -> **Ur** with a **c**arpet

I'll stop changing it now, and wait to see if anyone has anything to say.  I'll merge it eventually, if there are no objections.

**Comment by CelticMinstrel** [comment]
> More variations might be less of an issue if there were some way to make sub-menus in the editor?

What do you mean by this?

**Comment by doofus-01** [comment]
> What do you mean by this?

I mean if there was some way to have a lot of variations in the editor, without cluttering the palette.  Kind of like terrain groups.  It's not a fully thought out idea, and although I can envision a few ways to do it, I'm not sure it's a good use of resources.  Let's talk when this variations issue covers lots more terrains, once Wesnoth is on Steam and there are floods of volunteers, donations, and unicorns.

---------------------------------------------- 

The Ur (cave path) underlayer practically makes the cave carpet its own terrain anyway, as seen in the attached image.  A possible compromise in the overlay/fixed-underlayer conundrum could be to make the underlayers for all the carpets "recessive" like Ur is.  I haven't tested it though, just an idea for later.
screenshot_006

As per the discussion on the forum, I'll squash and merge this.

**Pull request merged**
