### PR TITLE
[DiD] S10 time over defeat scene

### PR DESCRIPTION
**Pull request by nemaara**
Added a defeat scene for DiD S10 where there was not previously one.

### CODE REVIEW

**Comment by GregoryLundberg** [comment]
Can't Dela Keshar and a few Paladins capture Malin so we don't have to bring in such heavy hitters?

**Comment by nemaara** [comment]
I honestly fail to see how Dela Keshar and a few Paladins is an easier/more plausible solution, given that you're fighting them throughout the scenario and are presumably beating them.

**Comment by GregoryLundberg** [comment]
So have reinforcements arrive or choose another character from an earlier scenario

**Comment by Konrad22** [comment]
How about the leader of Tath? (You'd have to check though if it's now impossible to kill him while invading Tath.)

**Comment by nemaara** [comment]
It's possible and reasonably likely that you kill him while invading Tath. I don't think reinforcements are good because Malin can just flee into the mountains, as he says at the end of the scenario (victory), and I don't see a compelling reason why he would risk his life over that book at this point in time.

**Comment by GregoryLundberg** [comment]
Contriving someone who is super-powerful and just swoops in to end it doesn't feel right. You might as well have one of the Gods appear in a flash of light and reduce Malin to a pile of ashes. What we need is something more logical, more in keeping with the story as it has been developing.

Drogan, for instance, if he's still alive (it's been a while so I don't recall) could finally capture Malin.

Or change the conversation at the start, where Darken Volt takes off to leave open the possibility that he'll return and have Darken do so, when time runs out, and overwhelm Malin with undead. Perhaps because he's proven so unept that this long-running battle is drawing too much attention to Malin and that is endangering Darken's activities as well.

**Comment by Konrad22** [comment]
Drogans death is the reason that Malins sister is attacking him in the scenario.

Also, it is quite likely that you have already killed Darken Volk by the time your turns run out.
I do believe that you have either never played this scenario or that too much has passed since you did.

**Comment by nemaara** [comment]
I've decided to just change it to paladin reinforcements as Gregory suggested. There's a lot of similar kind of reasoning in mainline, so I guess one more scenario like that won't hurt.

**Comment by GregoryLundberg** [comment]
Yes, it's been ages since I played. I was just quick-scanning the source looking for names. I really appreciate that someone is working on the TODO but think it's too much to just slam the player with some super-powerful.

**Comment by GregoryLundberg** [comment]
Thanks. 

You  will want to make the same changes against the master branch.

**Comment by jostephd** [comment]
Please fix the typo, Paldain->Paladin.

@GregoryLundberg Any reason for not cherry-picking this to master? It's playable now. I really don't want to see more technical debt being created while we're still working to pay off [the debt we've already accumulated](https://github.com/wesnoth/wesnoth/issues/3614).

**Comment by GregoryLundberg** [comment]
All fixed.

Cherry-picked and squashed on master

**Pull request merged**
