### PR TITLE
DiD S01-S04 fixes

### PR DESCRIPTION
**Pull request by GregoryLundberg**
Long ago I started a code-read and walk-through of DiD, but had to drop it due to RL.

@sigurdfdragon has been working on DiD S12 in #2188, which reminded me of these changes. Turns out, even though it has been a year, there were no merge conflicts; so I rebased and pushed, and am putting up this PR to clear the completed work off my queue.

### CODE REVIEW

**Comment by sigurdfdragon** [comment]
The first 4 seem straightforward enough. Haven't checked how the snow looks yet. A colon could be right after scenario numbers in commit titles.

**Comment by sigurdfdragon** [comment]
Took a look at the snow.

From the story, they spend the winter in the cave and emerge in spring, so storywise, it seems like it might be better to go with a fixed amount of random snow, rather than base it on how fast the previous scenario was completed. (with less snow the faster it was completed)

**Comment by GregoryLundberg** [comment]
Set snow coverage to constant 5%, still random. If constant placement is desired, I can pull the code and someone can add an overlay for the map.

**Comment by sigurdfdragon** [comment]
Did some playtesting. I think 15% can be used for more coverage, without causing any major changes to things too much. Beyond that, more involved playtesting would be needed to be sure.

**Comment by GregoryLundberg** [comment]
15% it is, then.

**Comment by ln-zookeeper** [comment]
I don't really see why DiD S04 in particular should be a unique scenario in that it features static but random snow coverage, but some random variation like that doesn't hurt either. If someone applies the same mechanic to other snowy scenarios, then at that point it would make sense to port the code to a core macro or something similar.

Anyway, I don't see any problems.

**Comment by GregoryLundberg** [comment]
The problem is, as a core macro, it needs a _**very**_ complete translation table to know which snow goes with which non-show terrain. I imagine it's possible but it's fragile.

**Pull request merged**
