### PR TITLE
Delfador’s Memoirs Round 3 Fixes

### PR DESCRIPTION
**Pull request by sigurdfdragon**
I still have rebalancing for S09, 10, 18, and maybe 19 to add.
Otherwise this is mostly done, & I'll merge at that point if there are no issues.

### CODE REVIEW

**Comment by sigurdfdragon** [comment]
I've updated the commits after "DM S20: Improve Delfador's arrival"
That should conclude my fixes for S09
The adjustments for 10 are included in S09 (just lessening the carryover from S09)
So next I'll be adding S18 changes

**Comment by sigurdfdragon** [comment]
Reordered & merged some commits and changed timestamp to make the sequence easier to read.

May make some slight changes S09 & S18 pending playthroughs for S10 & S19

**Comment by Vultraz** [comment]
Is this ready?

**Comment by GregoryLundberg** [comment]
I read it through and it looks good to me. But I'd suggest @sigurdfdragon rename the PR when he's ready and @ln-zookeeper push the button when he's taken a gander, too.

**Comment by sigurdfdragon** [comment]
@ln-zookeeper @Vultraz It's ready for final review, just need to add changelog

Significant things in this PR:
S01 - Dialog change
S13 & S 23 - Lessening 4th wall breaks & spoiler removal
Delfador portrait and character progression fix & cleanup
S07 Rebalancing
S09 Rebalancing
S18 Rebalancing
IlIliah-Malal is now an Ancient Lich in S18 & 19
Many dialog, objectives, and bug fixes/improvements

**Pull request merged**
