### PR TITLE
TRoW S19 Fix for the flying chocobones issue

### PR DESCRIPTION
**Pull request by Descacharrado**
Fixed a bug reported on discord by @Konrad22 which made the chocobones spawn over a chasm as can be seen:
Flycobones
Using passable=yes, and with the previous code implementation, no undead should spawn over a chasm.
No flybones

### CODE REVIEW

**Comment by knyghtmare** [comment]
Wouldn't something like this be better?
```ini
#define PASSABLE_HEX
[+unit]
    passable=yes
[/unit]
#enddef
```

and 

```swift
{LOYAL_UNIT 5 (Chocobone) $|spawn_x $|spawn_y}{PASSABLE_HEX}
```

**Review by knyghtmare — COMMENTED** [review]
If it's only for this scenario, it's missing an `#undef LOYAL_UNIT_PASS`

**Comment by Descacharrado** [comment]
Done and tested. I had never used [+tag] so that is good intel.

**Review by knyghtmare — APPROVED** [review]

**Comment by knyghtmare** [comment]
> Done and tested. I had never used [+tag] so that is good intel.

Programming essentials: you never stop learning and pick up something new everyday.

**Review by nemaara — APPROVED** [review]

**Pull request merged**
