### PR TITLE
[Complete in first approximation] iOS and general touchscreen support, pass 3 

### PR DESCRIPTION
**Pull request by singalen**
Applied review notes from PR #1742, #1748.

It is STILL not in a shape I'd like to see it, but it's playable on a touchscreen.

Known major problems:

* in gui2, first touch is registered as a hover, only second one works.
* context menu is hard to invoke (by long-press, on finger-up). I intend to replace it with both long-press timer and a touble-tap.
* on-screen keyboard pops up too often.
* crash in «Server executable» preference.
* Whiteboard is not tested

### CODE REVIEW

**Comment by singalen** [comment]
Aw crab. Again `SDL_platform.h` cannot be included in some files. Will have to hardcode the `#if` or put it somewhere like `src/utils/`

**Comment by singalen** [comment]
Hooray, Travis build passed!

**Comment by CelticMinstrel** [comment]
For the record, a nice place for things that might be needed anywhere is global.hpp. Although it's not included by every file, so you might need to add an include for it sometimes (though I've entertained the possibility of making it a prefix header).

**Comment by singalen** [comment]
Thanks. I wouldn't like to do that. These general utilities turn to a scrap piles  dry fast. Maybe we can add an util/os.h, or add boost::predef::is to boost-patched, or just leave it as is.

**Comment by singalen** [comment]
Sorry, so is this in an OK state to be merged?

**Comment by CelticMinstrel** [comment]
As long as it doesn't introduce bugs on Mac, Windows, etc, I see no reason why it can't be merged.

**Comment by GregoryLundberg** [comment]
Was this a 1.14 milestone?

**Comment by singalen** [comment]
@GregoryLundberg I dunno. It lets play on PC touchscreens. Other than that, its purpose is to put a foot in the door from mainline sources to iOS.

**Comment by GregoryLundberg** [comment]
I'll test it a bit on a Dell touchscreen running Windows 10. My point is we're pushing toward 1.14 release and this seems like a pretty large change when we should be in feature-freeze.

**Comment by singalen** [comment]
Thanks!
I personally don't mind if it's delayed till 1.15, just don't know who makes the decision.

/// Context menu is invoked by long-press, on finger-up. This might be confusing. That's the thing I want to improve next.

**Comment by GregoryLundberg** [comment]
Sounds like how it works elsewhere in W10. As I said, I'll test it .. I just need to sneak into the wife's sewing room when she's asleep and test it on her new toy.

**Comment by CelticMinstrel** [comment]
If I understand correctly, we're not actually in feature freeze until after the next release, but at the same time, this _is_ a big feature and as such is something to be wary of.

**Comment by singalen** [comment]
Can we define "be wary"? "Test on three platforms", "Postpone till 1.15" or "Carefully read through the code"? (I'm proud that the result is achieved in a relatively small amount of code).

**Comment by CelticMinstrel** [comment]
Mostly it means "don't be too trigger-happy with the merge button". Carefully reading through the code and/or testing on several platforms are good practical applications of that though.

**Comment by CelticMinstrel** [comment]
...wait, why did you close this?

**Comment by singalen** [comment]
Ops, sorry. Needed to redo the branch.
I'll rebase onto master soon and open yet another one. This one has grown conflicts on it anyway.

**Comment by CelticMinstrel** [comment]
Oh, I see, it must've auto-closed because you deleted the branch.

**Pull request closed without merging**
