### PR TITLE
Fix #2852: Reset statistics when rewinding a replay to the beginning.

### LINKED ISSUE #2852: Kills/losses in replays are counted again after starting the replay from the beginning.
Wesnoth 1.13.13

1. Run any replay
2. Wait for it to finish
3. Click start replay from the beginning and wait for it to finish again, the kills/losses in the statistics will be counted again and added to the real kills/losses after the first run of the replay, possible to be repeated indefinitely.

### PR DESCRIPTION
**Pull request by jostephd**

### CODE REVIEW

**Comment by gfgtdf** [comment]
Iirc [statistics] is not a subtag of what is contained in ex.level ( [replay_start]/[snapshot])

**Comment by jostephd** [comment]
I checked my savegames and you're right: [statistics] is not a subtag of [replay_start]/[snapshot] but a sibling. What would you recommend instead? Also, how do I test that codepath? I don't know how to create a (replay) savegame that starts with non-zero values in the statistics dialog. Thanks for reviewing!

**Comment by gfgtdf** [comment]
> What would you recommend instead?

Hmm not sure, statistics::clear_current_scenario sounds like it could do the job, but It s possible that it does not work in all corner cases.


> I don't know how to create a (replay) savegame that starts with non-zero values in the statistics dialog. Thanks for reviewing!

You play a (sp) campaign and open the replay of the second scenario, and then make sure that the info from the first scenario is still there after rest.

**Comment by jostephd** [comment]
Thanks. It seems in master there's an independent bug, if I beat the first two scenarios of AOI and then load the S2 replay there are _two_ entries for it in the drop down menu. That happens in unmodified master, _without_ this PR.

**Comment by jostephd** [comment]
Okay, I see what happens. I just force-pushed https://github.com/wesnoth/wesnoth/commit/2a7188ea10401247bda25d4efefe27e11fa639d0, its commit message explains why there are two entries with the same name. It fixes #2852 in my testing, and I think the fix will continue to work even after the "two entries for the last scenario" thing is fixed.

`reset_gamestate_exception` is thrown from two places:

https://github.com/wesnoth/wesnoth/blob/a65fb92d82571eddb463e9c9302750b6bf1d822f/src/playsingle_controller.cpp#L666-L675
https://github.com/wesnoth/wesnoth/blob/a65fb92d82571eddb463e9c9302750b6bf1d822f/src/hotkey/hotkey_handler_sp.cpp#L303-L322

I tested only the first of these two codepaths so I added an `if(!ex.start_replay)` in order not to affect the latter.

**Comment by gfgtdf** [comment]
Hmm yes the latter path is also borken though, but your fix will not work since that path does npt reset to the start of the scenario but to a mid scenario position.

**Comment by jostephd** [comment]
I suppose the latter codepath should pass `savegame.child_or_empty("statistics")` to the exception's constructor and then the catch block should pass that config object to `statistics::read_stats`? While continuing to call `reset_current_scenario` when thrown from the "reset replay" codepath.

**Comment by gfgtdf** [comment]
related issue https://github.com/wesnoth/wesnoth/issues/1079 , probalby also fixed already?

**Comment by jostephd** [comment]
Indeed. Closed that one.

**Comment by gfgtdf** [comment]
looks good to me

**Comment by jostephd** [comment]
Thanks for the review!

**Pull request merged**
