### PR TITLE
Locale and language dialog: retrieve country code using boost::locale

### PR DESCRIPTION
**Pull request by babaissarkar**
1. Remove embedded country code from `English (US)` and `English (GB)`. Countries will be programmatically retrieved using `boost::locale`.
2. Update Bengali locale info (add transliteration and `sort_name`)
3. Slightly reorganize the language selection dialog so that country codes are shown for each language. The country code is calculated from the locale's `locale` key.

Screenshot from 2024-07-14 22-27-29

### CODE REVIEW

**Comment by stevecotton** [comment]
The region names visible in the screenshot include Taiwan. I don't know the details of how the politics affect us, but the names supplied by the translators are Traditional Chinese and Simplified Chinese - I think this needs to be reviewed by someone knowledgeable about the politics.

Also visible in the screenshot are France, Germany and Spain, although several other countries are happily sharing a single German translation, and I believe that the French and Spanish translations are also widely used.

**Comment by Wedge009** [comment]
I'm not sure it's a case of politics, this change seems to be displaying the _primary_ country associated with the given locale, at least according to boost. I'm not an expert, but to my knowledge mainland China and Taiwan are the primary regions associated with Simplified Chinese and Traditional Chinese, respectively. Likewise, France is the primary region for (unqualified) French, contrasted with Canadian French.

**Comment by Pentarctagon** [comment]
https://wiki.wesnoth.org/WesnothTranslations says Taiwan as well.

**Comment by babaissarkar** [comment]
@stevecotton I'm simply using the data already existing in the language cfg files, and given that it was specified by translators, I don't see how that could be problematic.
(Given a locale, `zh_TW`, boost::locale gives its primary country as `TW`, as already pointed out by Wedge. I'm getting the primary locale from the `locale` key of the corresponding language)

As for the alternates, its possible to show them in the language dialog, but it would take a lot of space and maybe clutter that dialog.

**Comment by stevecotton** [comment]
I feel that most of the country codes are just adding clutter, but I don't see a problem with the current system of English (US) and English (GB) putting their differentiation into their names.

**Comment by babaissarkar** [comment]
> I don't see a problem with the current system of English (US) and English (GB) putting their differentiation into their names.

That makes the system inconsistent, because there's no way to know in advance which names have a country name embedded inside it. On the other hand, if it just contains the language name, there is a way to find out the country code. As for clutter, that's why I'm just showing two letter country codes and not the entire country name. (there's no way presently to get entire country names apart from libicu).
The changes here allow the API to be consistent, even for use cases other than the language dialog.

**Comment by babaissarkar** [comment]
Another one with embedded country info:

Screenshot from 2024-07-15 16-27-53

**Comment by stevecotton** [comment]
What's the problem with the system being inconsistent? What is the motivation for this change?

The old system is inconsistent because translators, with knowledge of the culture, have decided that the language needs a more specific name, and have then supplied the most appropriate identifier for describing it. Why is inconsistency bad in this case?

**Comment by babaissarkar** [comment]
> The old system is inconsistent because translators, with knowledge of the culture, have decided that the language needs a more specific name, and have then supplied the most appropriate identifier for describing it.

I think embedding country names inside the language name is partially motivated because translators weren't aware that country information could be extracted programmatically from the locale.
Anyway, I'm closing this. I'll find a different solution for the particular problem I'm facing.

**Pull request closed without merging**
