### PR TITLE
Changed and added hotkeys

### PR DESCRIPTION
**Pull request by ancestral**
This prevents unneeded collisions.

No keys are changing with this PR.

### CODE REVIEW

**Comment by ancestral** [comment]
No keys are changing here. I’m just reorganizing the keys in the file so modifiers come first before non-modifiers. This will be helpful for when I commit another PR with changing the keys.

**Comment by CelticMinstrel** [comment]
I don't quite get the purpose of this PR?

**Comment by ancestral** [comment]
I’m going to push another PR after this one with more changes.

**Comment by ancestral** [comment]
The reason for putting the modifier keys earlier was to fix what appeared to be a bug with commands that were looking for keys without modifiers and keys with. However, I have been unsuccessful with reproducing this test after I experienced the issue.

https://r.wesnoth.org/t41525 has virtually all the changes listed. Only about 6 keystrokes are getting changed; many more are getting added, with the emphasis on single key shortcuts that make reasonable sense to ease playing the game (`r` for recruit, `e` for recall, `j` for objectives, `g` for toggle grid, `.` for toggle ellipses, etc.)

**Comment by CelticMinstrel** [comment]
1. I see you've added space for "continue", but space is already assigned to something, how does that work?
2. I'm also kinda used to Ctrl+Y for redo, think that's worth including?

**Comment by jostephd** [comment]
This PR needs to be rebased from old master to new master.

**Comment by jostephd** [comment]
Removing this from the milestone until it's rebased to new master (I did check, the patch doesn't apply to master). I also notice that the patch has many more `+` lines than `-` lines, which seems odd since the discussions says the patch just moves stuff around but doesn't add, delete, or change any hotkeys.

And for the record, I'm not sure I'd be in favor of changing default hotkeys, any changes there should be opt-in (possibly as addons).

**Comment by CelticMinstrel** [comment]
It's probably because of the "reorganize" commit?

I believe this already exists as an add-on, but personally I'd be more in favour of merging this but then offering "classic hotkeys" as an add-on. I don't think we should avoid changing them just because it would confuse people who are already used to the current hotkeys. Anyway, these are just defaults, so they're opt-in by definition - anyone can change them to whatever they want.

I could probably work out porting this patch over to master; even if it doesn't apply cleanly I doubt it would be difficult to manually apply the changes.

**Comment by ancestral** [comment]
I can re-do it.

**Comment by jostephd** [comment]
> I don't think we should avoid changing them just because it would confuse people who are already used to the current 

Well, here we disagree. I'm not saying we shouldn't ever change hotkeys, but we should do so very rarely if at all. People are used to meanings and don't like having those change upon them.

> Anyway, these are just defaults, so they're opt-in by definition - anyone can change them to whatever they want.

No, that's not what "opt-in" means. Defaults are, by definition, something people can opt _out_ of. Opt-in would be if the new hotkeys were not the default and had to be explicitly installed or enabled.

People can change defaults, but few people will go and replace the entire set of hotkeys, and even then they'd need to do it on every single computer they use wesnoth on, so it does matter what the defaults are.

Dave wrote once that he'd like to have a norm that any PR could become the default (with an opt-out) for one development patch. I'd support doing that here.

**Comment by CelticMinstrel** [comment]
> Dave wrote once that he'd like to have a norm that any PR could become the default (with an opt-out) for one development patch. I'd support doing that here.

I'm not sure if I understand what you mean here... are you suggesting adding a "new/old" toggle for the hotkeys for 1.16 and then removing it in 1.17, keeping only the new hotkeys?

**Comment by ancestral** [comment]
* Continue is now `C` instead of `T`
* Go to Leader is now `K` instead of `L`
* Kill Unit is now `DEL` instead of `X`
* Undo is now `Z` or `CTRL + Z` instead of `U`
* Redo is now `SHIFT + Z` or `CTRL + SHIFT + Z` instead of `R`
* Planning mode is now `ALT + P` instead of `P`
* Delete Action (Planning Mode) is now `BACKSPACE` instead of `H`
* Suppose Dead (Planning Mode) is now `X` instead of `I`

(I had to revert Y for undo as it’s being used by execute [all] actions in planning mode, unless we decide to change that too.)

**Comment by jostephd** [comment]
> I'm not sure if I understand what you mean here... are you suggesting adding a "new/old" toggle for the hotkeys for 1.16 and then removing it in 1.17, keeping only the new hotkeys?

"One development patch" means one 1.15.x release. For example, make it on _by default_ for 1.15.3 with a preference to disable it, and then in 1.15.4 it's off by default again.

@ancestral I don't want to drown other voices... let's see what others have to say.

**Comment by soliton-** [comment]
> The idea here is bringing Wesnoth into simpler, more “modern” controls. Much like StarCraft, League of Legends, and other competitive games have simple, single-letter keys for popular commands, why shouldn’t Wesnoth also? This lets players learn the keystrokes more easily, as commands do not require holding different modifier keys.
> 
> For example, to recruit a unit on a hex, press `R`.
> 
> There are a few changes of keys:
> 
> * Continue is now `C` instead of `T`
> * Go to Leader (“King”) is now `K` instead of `L`
> * Kill Unit is now `DEL` instead of `X`
> * Undo is now `Z` or `CTRL + Z` instead of `U`
> * Redo is now `SHIFT + Z` or `CTRL + SHIFT + Z` instead of `R`
> * Planning mode is now `ALT + P` instead of `P`
> * Delete Action (Planning Mode) is now `BACKSPACE` instead of `H`
> * Suppose Dead (Planning Mode) is now `X` instead of `I`

The stated rationale and the changes don't seem to fit particularly well. (Not that I understand the rationale well since wesnoth already uses simple, single-letter keys.)

Simple, single-letter keys are changed to other simple, single-letter keys. Some are even changed away from simple, single-letter keys.

Changes like for Undo and Redo seem rather motivated by more-or-less generic conventions that those actions are mapped to CTRL+Z and CTRL+SHIFT+Z (I've never seen Z and SHIFT+Z though) which could well be a good idea.

**Comment by jostephd** [comment]
Wesnoth relies on the mouse so it would be nice if hotkeys could be entered single-handed with the left hand only. `DEL` and `Alt+P` can't. (They're nowhere near the home row.)

**Comment by ancestral** [comment]
> The stated rationale and the changes don't seem to fit particularly well. (Not that I understand the rationale well since wesnoth already uses simple, single-letter keys.)

Surprisingly, this isn’t the case.

You seem focused on the re-mapping of 8 keys, but you’re missing out on the [changes/additions](https://github.com/ancestral/wesnoth/pull/1/commits/d364c14522f4e5a52cb7a745860ffe5010978182). It seems maybe you haven’t seen these.

* Best Enemy Moves can be used with `B`
* Change Side can be used with `U`
* Chat Log can be used with `L`, no longer requiring `ALT + C` (which still works)
* Cycle can be used with `RETURN`, which is similar to other games like Civilization — but if you still like `N`, that still works
* Describe Terrain can be used with `I` (think “info”)
* Hold position is `H` — like so many other games — but if you prefer `SHIFT + SPACE` that still works
* Objectives is `J` — again, like many other games, and doesn't require holding down `CTRL` — but that still works if you miss your control key
* Recall is `E` (but `ALT + R` still works)
* Recruit is `R` (but `CTRL + R` still works too)
* Show Enemy Moves is `V` (but if you prefer `CTRL + V`, the paste keystroke, I didn’t change that)
* Speak is `TAB` (like in many other games)
* Statistics is `T`, Status Table is `S` (but if you prefer `ALT + S` for Status Table, be my guess)
* Toggle Ellipses is `.` — which hopefully makes semantic sense

etc.

**Comment by Pentarctagon** [comment]
@ancestral Are you going to continue to work on this?

**Comment by ancestral** [comment]
I submitted a file, but at the time there was something @Vultraz didn’t like about it.

**Comment by Vultraz** [comment]
It's been too long. I really can't remember 😬

**Comment by ancestral** [comment]
Alright, I’ll rebase tomorrow and resubmit.

**Comment by CelticMinstrel** [comment]
@ancestral If/when you get to the follow-up PR, might I suggest also changing New Map from Ctrl+M to Ctrl+N? That'll fix #2986 as well.

**Comment by CelticMinstrel** [comment]
Or maybe this became the follow-up? I only re-read the first post before saying that but it looks like there's a lot more discussion and stuff in here.

**Comment by Wedge009** [comment]
What's the status here? I'm not sure I necessarily agree with all the changes but this is a pretty simple PR that should have a decision one way or another.

**Comment by CelticMinstrel** [comment]
If we accept this I think there are a few minor changes that would be needed (for example, see my previous comment). However, by and large I think it's good.

**Comment by Wedge009** [comment]
#1316 also seems to list some key combinations already taken by macOS.

**Comment by Wedge009** [comment]
#1918 also discusses hot-key revisions... but possibly in different contexts and beyond what is available in the current hot-key system.

**Comment by Pentarctagon** [comment]
I'm fine with this being merged. Are there any objections?

**Comment by CelticMinstrel** [comment]
I don't think I have any specific objections. I'd like to change/augment the New Map hotkey as previously mentioned, but there's no reason for that to block merging.

**Comment by Wedge009** [comment]
Was there trouble changing the base branch?

Along with the change to continue-on-enemy-sighted, I'm also not sure about the change of leader from `l` to `k` (the PR wants to make `l` for chat log).

...I forget - are hot-keys hard-coded into the tutorial? I recall leader might be a short-cut that's mentioned there.

**Comment by Pentarctagon** [comment]
Yeah, I figured I might as well see if it happened to work, and it does not.

**Comment by CelticMinstrel** [comment]
> are hot-keys hard-coded into the tutorial?

If so, we should create some system to dynamically insert the actual hotkey you've assigned.

**Comment by ancestral** [comment]
Some clarification: I never got around to revisiting this, and I’ll be honest, I haven’t touched the game in a while. I apologize for that.

The goal was originally to use keys without modifiers for the most common commands (R to Recruit, E to Recall, for example), so if someone has a list they like, even if it deviates from what I propose, that’s awesome. The easier the game is to play, the better the game will be!

**Comment by Wedge009** [comment]
> If so, we should create some system to dynamically insert the actual hotkey you've assigned.

I had a quick look - maybe this isn't the case (that hot-keys are in the tutorial).

**Comment by Pentarctagon** [comment]
Alright, barring anything else coming up then, I'll take this and push it to the current master branch in a couple days.

**Pull request merged**
