### PR TITLE
Changed Shebang line of python scripts and terrain2wiki

### PR DESCRIPTION
**Pull request by sevu**
It's mostly about making the scripts run if python defaults to python3.
Has been tested for each script.

I hope this doesn't lower the motivation to port things to python 3.

### CODE REVIEW

**Comment by sevu** [comment]
Is the fix in the file utils/nacl/buildpack.py fine in terms of copyright?

**Comment by sevu** [comment]
Adjusted the commits since PR #868 got merged.

**Comment by Elvish-Hunter** [comment]
It looks good, except for the `rmtrans.py` file. This one is a script for The GIMP, which AFAIK doesn't support Python 3, but just Python 2.

**Comment by sevu** [comment]
I just realized that I had mistaken that tool for reintex, and never saw it in the list.
Changed it to python2, but stumbled about sth. else. When using it on a sprite it worked, but then I tried it on a screenshot, or the image attached,  I get a RuntimeError which points to line 11.
However, it works on sprites. No Idea about that...
some_image

**Comment by CelticMinstrel** [comment]
It's possible that that's not a significant problem, since it seems like something you would never _want_ to run on a screenshot. I guess it might be good to fix just to avoid the error in case you accidentally use it that way, though.

**Comment by sevu** [comment]
I think the same about it.
But I have no idea what is actually wrong with line 11, and I'm not used to python programming.
Can't fix that.
However, that issue is independent from this PR.

**Pull request merged**
