### PR TITLE
WIP: Use the Python run_wml_tests on Windows too

### PR DESCRIPTION
**Pull request by stevecotton**
Not tested locally, just creating a PR to run the AppVeyor tests and see if this works.

### CODE REVIEW

**Comment by stevecotton** [comment]
This doesn't look good, both of those AppVeyor builds should have failed.

The release build should fail due to this PR, `'.\run_wml_tests' is not recognized as an internal or external command`. For some reason that doesn't cause a failure.

The debug build is more confusing - it's finishing with the following log. It's probably a case of the binaries being called wesnoth-debug.exe, but why is it counted as a success?
```
Collecting artifacts...
No artifacts found matching 'wesnoth.exe' path
No artifacts found matching 'wesnothd.exe' path
Build success
```

**Comment by Pentarctagon** [comment]
Perhaps it's counted as a success because the actual compiling was successful?  Travis I know relies on whatever the return code of the last command was, but maybe AppVeyor checks more specific results?

**Comment by stevecotton** [comment]
Need to sanity-check that a failing test causes the build to fail.

**Comment by stevecotton** [comment]
Sanity check didn't work, it needs to fail on AppVeyor.

**Comment by stevecotton** [comment]
If the AppVeyor build now fails, which is expected, then I'll rebase removing the sanity check.

**Comment by stevecotton** [comment]
I'm not going to continue with this, it needs someone running Windows locally to debug it.

**Pull request closed without merging**
