### PR TITLE
Added translators comments to src/units/attack_type.cpp and pick them up the CMake way too

### PR DESCRIPTION
**Pull request by gunchleoc**

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
So the only question is whether we want `TRANSLATORS` to be the magic string that indicates a translation note. It seems okay to me, though.

**Comment by gunchleoc** [comment]
It already is the magic string in the scons compile path.

**Comment by CelticMinstrel** [comment]
Ah, okay. Fair enough.

**Comment by gunchleoc** [comment]
Yes, I have tested them. And no, we can't move them up, because [xgettext can't handle that](https://www.gnu.org/software/gettext/manual/html_node/xgettext-Invocation.html).

I have added some [documentation](https://wiki.wesnoth.org/GettextForWesnothDevelopers#Marking_up_strings_in_C.2B.2B) to the wiki.

**Comment by CelticMinstrel** [comment]
Huh, okay. It'd be great if the wiki could also mention whether you can have multiple comments for each string, eg:

```
// TRANSLATORS: Stuff
// TRANSLATORS: More stuff
_("The String")
```

**Comment by gunchleoc** [comment]
I don't know, but multiline comments definitely work, so I have added that to the wiki.

**Pull request merged**
