### PR TITLE
Text Updates (1.14)

### PR DESCRIPTION
**Pull request by Wedge009**
Implementing text changes suggested in #2882 and #2950.

### CODE REVIEW

**Comment by Wedge009** [comment]
I'm aware of the condition that it's only for attack - was thinking to keep it simple for a tutorial. Then again, it might not be that much more complex to rephrase it as:

When attacking, I always have at least a 60% chance of hitting with my longbow thanks to my _Marksman_ ability...

How does that sound to you?

**Comment by CelticMinstrel** [comment]
Sounds good to me.

**Comment by Wedge009** [comment]
I updated this and #3001 with the above suggestion. Everything else is the same as before.

**Comment by CelticMinstrel** [comment]
These seem to have conflicts for forward-porting, so could you handle that as well?

**Comment by sevu** [comment]
That's #3001

**Comment by CelticMinstrel** [comment]
Ah, how did I miss that!

**Pull request merged**
