### PR TITLE
Sync new rendering

### PR DESCRIPTION
**Pull request by Vultraz**
Opening this for a CI run.

### CODE REVIEW

**Comment by mesilliac** [comment]
With #6855 this is fully merged, excepting the commit enabling render batching.

**Comment by Wedge009** [comment]
Sorry for not following all the discussion - is there something still stopping us from using SDL's batched renders?

**Comment by mesilliac** [comment]
There was some discussion on IRC. It had previously caused various difficult to debug issues, tracked from https://github.com/wesnoth/wesnoth/issues/4245 and linked issues.

I don't want to have to debug a reoccurance of any of that. It is unlikely to bring any meaningful performance benefits in current usage anyway.

**Comment by Wedge009** [comment]
I was the one who removed the default batched renders, so I was curious to know if your work changed anything in that issue. If not, may as well leave it switched off then.

**Comment by mesilliac** [comment]
It may have. I don't know. I definitely don't want to have to find out in the middle of all the other changes.

**Pull request closed without merging**
