### PR TITLE
fix Did advancement

### PR DESCRIPTION
**Pull request by newfrenchy83**
another fix off https://github.com/wesnoth/wesnoth/issues/6351

### CODE REVIEW

**Review by knyghtmare — APPROVED** [review]

**Comment by Wedge009** [comment]
Just so I understand why this is a 'fix' or improvement, what's the difference between `modify_unit_type` and `advances_to`? Is it because the lich removal is applied to all Dark Sorcerers and not just Darken Volk?

**Comment by newfrenchy83** [comment]
> Just so I understand why this is a 'fix' or improvement, what's the difference between `modify_unit_type` and `advances_to`? Is it because the lich removal is applied to all Dark Sorcerers and not just Darken Volk?

While Darken Volk is the only Dark Sorcerer present in Did, the use of advances_to specifically on this character is unstable and requires @nemaara to undo the removal of the loyal trait when the wizard returns his jacket as this resets the settings and advances_to was rebuilt from unit_type, therefore modifying unit_type is more appropriate, and this method is already used in TroW to prevent Aethyr from advancing to Grand Marshal, and include the modification in the help file for unit_type

**Review by knyghtmare — APPROVED** [review]

**Comment by Wedge009** [comment]
If this solution avoids the need for Darken Volk to keep his loyal trait, can you revert the removal of the removal (not a typo) of the loyal trait together with this PR, then? a304bc105dddde7069fd1412f56d51b20759b750 for master, eb6eb7d9627a219ea404297835a7f3c4345caa8a for 1.16.

**Review by nemaara — APPROVED** [review]
Any fix is fine with me, just needs a coder to approve/merge it

**Comment by Wedge009** [comment]
I think @knyghtmare has approved, and we can keep Volk as no longer being loyal now. From what I understand this and #6358 makes sense to me.

**Review by knyghtmare — APPROVED** [review]

**Comment by Discontinuum** [comment]
Sad Darken is no loyal now when switches sides, I thought it's a cool thing to do, why remove this loyal trait? I don't understand

**Comment by knyghtmare** [comment]
> Sad Darken is no loyal now when switches sides, I thought it's a cool thing to do, why remove this loyal trait? I don't understand

When he switches sides, he has also gets canrecruit=yes which means leader/no upkeep. Which is like the loyal trait and more. So, having the loyal trait for a selfish character such as Volk makes little sense when he switches sides. Does that clarify your confusion?

**Comment by Wedge009** [comment]
I also thought the loyal trait only really makes sense when he and Malin are working together. Now that they have separated, it doesn't make sense to keep it. And in fact, in the original state he didn't have the loyal trait - it was only restored to him to avoid the possibility of him advancing to Lich, which was then resolved properly in this PR (or so I understand).

**Comment by Discontinuum** [comment]
It's not about upkeep really, it's about cool description. He is still loyal to himself when he switches

**Comment by Wedge009** [comment]
That makes no sense, story selfishness has nothing to do with game-play loyalty trait.

**Comment by Discontinuum** [comment]
Still the trait has this description, so it's used for the story purposes too.

**Comment by Wedge009** [comment]
By your logic, every enemy leader should have loyal trait. Just leave it - the loyalty trait was only restored, briefly, as a work-around. It isn't coming back.

**Comment by Discontinuum** [comment]
> By your logic, every enemy leader should have loyal trait. 
No. The only reason I want it for Darken is that it's specifically used as a story element, like this
изображение

No other enemy leader has this highlighted. 

And when I proposed it, I proposed it not as a work-around but as a permanent story thing as well.

**Comment by Wedge009** [comment]
Okay, that's different. I had no idea that was even present until you pointed it out, but it is indeed there:
https://github.com/wesnoth/wesnoth/blob/82b54920d6ad7faab79281091dffebb5ee57279e/data/campaigns/Descent_Into_Darkness/utils/characters.cfg#L43-L45

I'd consider it more of an in-joke or an 'easter egg' of sorts. Unfortunately it is tied to the loyal trait mechanic and I think that does override this little reference when he turns against the player. It's only a 'loss' if you're actually astute enough to find this little quirk.

**Pull request merged**
