### PR TITLE
Add a filter_second_weapon to leadership and tesistancrs abilities

### PR DESCRIPTION
**Pull request by newfrenchy83**
The ennemy wrapon can be also filtered.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
You're now passing the weapon twice to `damage_from`. I'd rather pass it only once.

If you need to transform the `attack_type&` back to an `attack_ptr`, call `weapon.shared_from_this()`.

**Comment by CelticMinstrel** [comment]
Also, I'd prefer merging `ability_affects_weapon` with `ability_affect_second_weapon` (by adding a string parameter).

**Comment by newfrenchy83** [comment]
Understand for merging the function

**Comment by newfrenchy83** [comment]
Merging function done but a problem of connection damage_frm will be fixed later.

**Comment by newfrenchy83** [comment]
It's done.

**Comment by newfrenchy83** [comment]
It's not done i must do an error.

**Comment by newfrenchy83** [comment]
It's attack.shared_from_this is this weapon or opp_weapon what i must calling with?

**Comment by CelticMinstrel** [comment]
...I'm not really sure, it looks like it could use a bit more work, but I might just decide to fix it up when I merge it, which will likely be Friday or Saturday.

**Comment by newfrenchy83** [comment]
good luck. a bit tired.

**Comment by newfrenchy83** [comment]
today sunday, you had forget this PR or you have too to working and you ended this after Pâques? thank you else fot your help.

**Comment by CelticMinstrel** [comment]
Well, I could still get to it today, I guess. I'm not sure if I will, but I'll try.

**Comment by CelticMinstrel** [comment]
Just for the record, I have it merged, but since I want to test it properly first, it's possible I may not get the merge pushed to github today.

**Comment by newfrenchy83** [comment]
tje PR is open and not merged. if the test is succefull tjen merge the commits please.

**Comment by CelticMinstrel** [comment]
Yes, I will, just be patient.

**Pull request closed without merging**
