### PR TITLE
Ingame tab completion works with friendlist (bug #9742)

### PR DESCRIPTION
**Pull request by niegenug**

### CODE REVIEW

**Comment by shikadilord** [comment]
I had written a comment on the code but it seems to have disappeared for some reason, while the code is still the same.

**Comment by shikadilord** [comment]
Reposting below for reference:

Constness: code should always use ``const`` where appropriate (which also includes using ``const_iterator`` when your intent is not to write to iterators). That is, ``friends`` here should be a const value or even a reference, and ``iter`` should be a ``const_iterator`` (read-only) rather than a ``iterator`` (read/write).

Variables: loop variables that only get used within the loop should be declared inside the loop or in the loop statement. In this case, ``iter`` is not needed outside the ``for`` loop, and it should be declared and defined in the loop start statement instead.

Formatting: we generally don't use extra spacing for control block statements (`keyword(statement)` instead of `keyword( statement )`), and we do use spacing around operators (`foo = bar; baz != bat` instead of `foo=bar; baz!=bat`).

**Comment by gfgtdf** [comment]
Why not using the BOOST_FOREACH macro here? (or even better the FOREACH macro?)

**Comment by niegenug** [comment]
ok i had some git misunderstandings but now the fix is uploaded correctly.

shikadilord: did i miss something?

gfgtdf: i noticed BOOST_FOREACH gets creepy when working with maps. I had to create a new type to avoid the macro limitation (it requires 2 inputs while there was apparently 3 - 3 commas in declaration- ) since map got 2 types to manage. See for example this link: "http://stackoverflow.com/questions/2104208/is-it-possible-to-use-boostforeach-with-stdmap".
IMO workarounds for "bugs" in dependancies makes the code less understandable, while plain std is widely known.

**Comment by niegenug** [comment]
uh i just wrote answer and got lost? (test comment to check)

**Comment by gfgtdf** [comment]
Hmm both these codes worked fine for me (with the necessary includes):
```
BOOST_FOREACH(const std::string& name, preferences::get_acquaintances_nice("friend") | boost::adaptors::map_keys) {
	dictionary.insert(name);
}
```
```
FOREACH(const AUTO& pair, preferences::get_acquaintances_nice("friend")) {
	dictionary.insert(pair.first);
}
```

**Comment by shikadilord** [comment]
@gfgtdf I really don't think it's a problem.

@niegenug No, it's all correct, except for a few trivial bits which I corrected myself and pushed upstream to save you an additional amend/push sequence. You can see the final diff in commit b549ac258c18d103361613aeb118053dc8053ed8. I only replaced whitespace indentation with tabs (important) and changed the ``const`` keyword spacing and position to match our most common usage.

Also, I tested before pushing and noticed that chat messages come out duplicated in networked games for some reason, but it's certainly a completely unrelated issue that must've been introduced recently.

Thanks for your work on these improvements!

**Pull request closed without merging**
