### PR TITLE
SotA: Fix altar lighting

### PR DESCRIPTION
**Pull request by sigurdfdragon**
Proper wml item lighting behavior restored in 478c75bdb5bc914fcd71469a2ae6967cadc99e11, so a change is needed

This PR is an attempt to use [item] image adjusted properly, so Ras-Tabahn will pass in front of the alter.

The adjustment to counteract underground lighting seems slightly off.

[item] halo could be used( & was used previously), but that would have Ras pass behind the alter.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
While this might be "good enough", I need to point out that colour-shift is, generally speaking, not a reversible operation. It would be better to offer a flag or something that disables the TOD colour shifting.

I think @ln-zookeeper was actually talking about something like that not long ago? A pseudo-IPF something like `~NO_TOD_SHIFT()`, if I recall correctly.

**Comment by ln-zookeeper** [comment]
Just to make sure: is the problem the colour difference between items/altar-sacrifice-halo.png and units/rastabahn-on-altar.png (because items are now ToD-shifted whereas units are not)?

Note that there'd still be an inconsistency between the altar in this scenario and the next one.

And yes, I was going to add an IPF for preventing the ToD-shifting of item and terrain images, so that would work nicely in this case. In fact it's almost done, just needs a bit of testing and cleanup, and unless it turns out I've missed something I can probably get that in within a day or two.

**Comment by sigurdfdragon** [comment]
@CelticMinstrel I had thought it was reversible & I'd figure out what math would be needed to get it more exact.
@ln-zookeeper Yes, that's the problem and a nice solution.

**Comment by CelticMinstrel** [comment]
> I had thought it was reversible & I'd figure out what math would be needed to get it more exact.

It might be _theoretically_ reversible (I'm not sure what the formula is, but multiplication seems to be a common blend mode), but in practice I don't think it necessarily works out that way for two reasons - first, there's potential loss of precision if you multiply by _x_ and then divide by _x_ (though that may not apply when using integer components?), and secondly there is a range limit for the colour channel values (0..255 in this case). If it was allowed to overflow, then it might be reversible, but normally it's clipped instead.

**Comment by sigurdfdragon** [comment]
Updated to use the new ~NO_TOD_SHIFT() IPF
Also removed altar images that are no longer needed.

@CelticMinstrel I'll keep that in mind, thanks.

@beetlenaut Thoughts?

**Comment by beetlenaut** [comment]
I'd had to de-shift the image manually before, but that left it a little off when the TOD color shifts changed during this development cycle. (I never bothered to redo it because it wasn't really noticeable in the game.) The new IPF is obviously a nicer solution, and other UMC authors will probably find it useful too.

**Comment by Vultraz** [comment]
Any reason the mainline `items/altar-evil.png` can't be used here?

**Comment by beetlenaut** [comment]
Yes. The SotA altar is about twice the size of the original altar-evil.png. It has to be that big for a unit to fit on top of it.

**Comment by Vultraz** [comment]
You can use an IPF to scale it up.

**Comment by Vultraz** [comment]
Ah, perhaps you can't... yeah, maybe this is fine. If you have no objections I'll merge, then.

**Comment by beetlenaut** [comment]
I copied the textures from the original, but it is actually redrawn, not just scaled up. That wouldn't have looked as nice. I haven't actually downloaded this branch to take a look, but this is the way I would have done it if the IPF had existed at the time, so I don't have any objections.

**Comment by Vultraz** [comment]
Ahhh, gotcha. Will merge then in a little bit.

**Pull request merged**
