### PR TITLE
Add an environment variable to disable logging to file

### LINKED ISSUE #8527: Add --no-log-to-file option to preferences
### Describe the desired feature

At some point relatively recently, wesnoth has started logging to a file instead of console or standard error.  At least for Linux CLI.

That's probably an improvement for some people, but I find it very unhelpful and wish there was some option to make the `--no-log-to-file` option persistent, without layering on some alias or launch script.  There is already a "logging" section in advanced preferences, it could go there.

### PR DESCRIPTION
**Pull request by Pentarctagon**
Fixes #8527

### CODE REVIEW

**Comment by soliton-** [comment]
This looks like it gives higher precedence to the env variable than to command line arguments. Usually it's the other way around. The env variable should only have an effect if no log to file options are given.

**Review by doofus-01 — APPROVED** [review]
I can't say if there is some coding convention issue or not, but functionally, it works great.  It would be nice if there was a way to advertise the variable, but maybe just updating the wiki is enough.

**Comment by Pentarctagon** [comment]
Adding it to the man page would make sense, but I'm not sure where this info would be added on the wiki?

**Review by stevecotton — APPROVED** [review]

**Comment by doofus-01** [comment]
> I'm not sure where this info would be added on the wiki?

Maybe somewhere under here?
https://wiki.wesnoth.org/DevelopersHome

**Comment by Pentarctagon** [comment]
I don't really see any category there where it would fit under is the issue.

**Comment by doofus-01** [comment]
Would `INSTALL,md`, linked by the wiki in various places (including "DevelopersHome" and "Play") by "Compiling Wesnoth" be a good place?  That's where I would have found it.  Many UMC authors might miss it, so if not there, then a link from "ReferenceWML", under the "Other" or "See also" sections, could make sense?

**Comment by Pentarctagon** [comment]
Could perhaps add a Runtime Options section there I suppose? Otherwise it doesn't really fit there either, since everything else is about compiling Wesnoth, not options when running it.

**Comment by doofus-01** [comment]
Fair enough, then we agree it's one of the "ReferenceWML" sections?

**Comment by Pentarctagon** [comment]
Is starting Wesnoth from the command line and watching for output there something that most UMC authors would do?

**Comment by doofus-01** [comment]
I can't speak for most UMC authors, especially if there is now a functioning scenario editor, but I'd assume anyone messing with the WML/Lua would want the instant feedback, in a place that can scroll and be copy-pasted (as opposed to in-game error/chat messages).

Since this isn't forcing a new default, it's just an online reference, there probably are enough such authors to make it a good thing.

**Comment by Pentarctagon** [comment]
My impression generally is that most UMC authors essentially don't even look for this output at all unless there's already something wrong - most wouldn't even know what an environment variable or the command line is. On Windows, which is where the large majority of Wesnoth's playerbase is, logging to file has been the default for a while (since 1.14). So I guess I'm confused why this is so important a thing that it needs to be documented like this.

**Comment by CelticMinstrel** [comment]
I don't think this fits on ReferenceWML. You could _link_ to a page mentioning it from there, maybe, but directly mentioning it there is off topic.

**Comment by doofus-01** [comment]
> So I guess I'm confused why this is so important a thing that it needs to be documented like this.

And I'm confused about the resistance to making the info available, but I've added a page to the wiki and linked it from ReferenceWML, at the end of "See Also".

**Comment by doofus-01** [comment]
Why doesn't it fit?

**Comment by soliton-** [comment]
I think a page specifically for env variables is a bit narrow. A page explaining command line use, specifically for UMC authors perhaps, could be useful and would make sense to link from ReferenceWML. It could also include how to use the schema validation for a given addon, how to start your campaign directly from the command line and stuff like that.

**Comment by doofus-01** [comment]
I did link a page for env variables from ReferenceWML, and I agree it is too narrow, but until a better CLI article is written, I think it's better to have it than not.

**Pull request merged**
