### PR TITLE
SoF - Replace S1 map

### PR DESCRIPTION
**Pull request by doofus-01**
Map is now smaller, does not have a long slog of moving caravans and nothing else.  Otherwise, I think it's the same scenario, the story isn't really changed. ...except for the next scenario, which can currently start with the two leaders shouting at each other while facing away, like spatting lovers.

I have a replay attached.  I think it's better than the current version, but still needs some adjustments.
[SoF-A Bargain is Struck replay.gz](https://github.com/wesnoth/wesnoth/files/4271276/SoF-A.Bargain.is.Struck.replay.gz)

### CODE REVIEW

**Comment by nemaara** [comment]
Overall, I like the new map design. Still have a couple comments though:

1. I think we should make the main keep a bit lower in the map so that the main force actually presents a relevant threat from the south (not necessarily on the caravans, but at least on blue).
2. Along similar lines, it'd be nice to move Haldric's keep a little bit more south (extending the map a couple hexes) so there's a little bit more ground for the caravans to cover.
3. It's probably better to have a village near the player's starting location so that you at least have some form of healing.
4. Upon implementing the above, it seems to become necessary to reduce the elves' starting gold and also increase Haldric's income.

I've made some edits here to demonstrate what I mean. It's a tad on the hard side, might need some work on the numbers. 

[SoF_S1.zip](https://github.com/wesnoth/wesnoth/files/4271503/SoF_S1.zip)

**Comment by doofus-01** [comment]
Thanks, I'll check this out next weekend.

**Comment by doofus-01** [comment]
@nemaara - I tried out your revisions.  My impression is that they seem to reduce the pressure on the player and increase the amount of AI vs AI.  Possibly I am just misremembering, but I have to log off soon, so for now I'll upload my replay here.
[SoF-A Bargain is Struck replay-alt.gz](https://github.com/wesnoth/wesnoth/files/4335681/SoF-A.Bargain.is.Struck.replay-alt.gz)

**Comment by nemaara** [comment]
Okay, I made the map a bit longer now (didn't draw the extra hexes very prettily, but they're there). You don't have to play it again, I'll attach my replay if you want to look at it. Basically I didn't like the elves coming over the river right from the getgo in the original version so much, I thought that felt a bit weird.


[SoF-A Bargain is Struck replay.gz](https://github.com/wesnoth/wesnoth/files/4335922/SoF-A.Bargain.is.Struck.replay.gz)

[SoF_S1.zip](https://github.com/wesnoth/wesnoth/files/4335919/SoF_S1.zip)

**Comment by doofus-01** [comment]
OK, I updated the map from @nemaara 's revision, I think it should be good now.  Even if it isn't perfect, I do believe it is a significant improvement.

**Pull request merged**
