### PR TITLE
Fix for issue #3444

### PR DESCRIPTION
**Pull request by hrubymar10**
Fix for issue #3444 

Please verify that it will work this way

### CODE REVIEW

**Comment by Wedge009** [comment]
I believe this is correct - the prefix is supposed to denote particular meaning for otherwise homonymous words.

**Comment by CelticMinstrel** [comment]
Yeah, this is fine. It does make me wonder if there are any other colour names we should add this prefix too, but I guess most of them are unambiguously colours.

**Comment by CelticMinstrel** [comment]
To be honest, for this commit I think looking at the diff should be enough to get a general idea.

But you're right, a more descriptive message would've been preferable. I should've thought of that. Oh well.

**Comment by gfgtdf** [comment]
> To be honest, for this commit I think looking at the diff should be enough to get a general idea.

yes ofcourse but it'd be nice to be abo to understand what a commit does withotu looking at its diff or looking upo in the issuetracker. For example when you look for things that should be mentioned in RN one possible strategy is to look at the commits https://github.com/wesnoth/wesnoth/commits/1.14 since the last release and try find the 'important' commits that shoudl be mentioned which is hard to do unless if the commits description is not really self explaining.

**Pull request merged**
