### PR TITLE
#2971 Scrolling with arrow keys can get stuck

### PR DESCRIPTION
**Pull request by singalen**
Phew, seems to fix it for me.

### CODE REVIEW

**Comment by gfgtdf** [comment]
no, in fact most std containers require member types to be assignable, i am not sure about std::set but i would not be suprised if nonassignable keytypes in std::set were not standard-conformant

**Comment by CelticMinstrel** [comment]
Ah, I may have misread his actual changes slightly.

That's not a const value type. It's `std::pair<const hotkey_command*, bool>`, which is assignable, because the const applies to the type pointed to, not the pointer itself.

That aside, I'm dubious of using `std::pair` as the value type of a `std::set`. Why do you need to add both "true" and "false" for a given command? That seems weird? I don't see why an `std::pair<const hotkey_command*>` is insufficient.

**Comment by gfgtdf** [comment]
> That's not a const value type. It's std::pair<const hotkey_command*, bool>, which is ,,


my comment was about the first const in `typedef const std::pair<const hotkey_command*, bool> command_key;` which i assume you talked about becasue that the const that was 'lost' in vultraz code

**Comment by CelticMinstrel** [comment]
Ahhh, you're right, I missed that bit. I think `std::set` would need to be able to support unassignable value types since it uses the same underlying implementation as `std::map`, whose value type is _always_ unassignable; however I'm not sure if that extends to fully const types. I wouldn't generally recommend using a const value type in a standard container, but for containers that store their elements in nodes (`std::list`, `std::map`, `std::set`; not sure about the unordered associative containers but I suspect they don't), I suppose it might still work.

**Comment by singalen** [comment]
@CelticMinstrel , 

> That aside, I'm dubious of using std::pair as the value type of a std::set. Why do you need to add both "true" and "false" for a given command? That seems weird? I don't see why an std::pair<const hotkey_command*> is insufficient.

This was the whole source of this bug. It's a "key unpressed" flag, otherwise one in press-unpress event pairs will get erased. It's commented in the original change. 

Does the question about constness/assignability still stand, given hat this type is assignable? 

On the other hand, I'm not completely happy with std::pair, as it doesn't describe the responsibilities of its fields, which led to part of this confusion.

**Comment by CelticMinstrel** [comment]
I'm thinking the `const` in front of `std::pair` should probably be remove, yeah. Also, I'd either use Vultraz's method or change the `typedef` statement to a `using` alias.

**Comment by gfgtdf** [comment]
most important: the travis check reports build erros, you have to fix them all before we can merge this.

**Comment by singalen** [comment]
@Vultraz Will this do?

**Comment by Vultraz** [comment]
I mean, it's fine, but there's no reason to construct the pair with `command_key ` since you're using `auto`. That's why I suggested `std::make_pair`. I recommend either
`auto command_with_keypress = std::make_pair(cmd.command, cmd.release);`
Or
`command_key command_with_keypress(cmd.command, cmd.release);`

**Comment by jyrkive** [comment]
Thank you. Merged. 👍

**Pull request merged**
