### PR TITLE
WIP, completely untested: Remove the evil path of Northern Rebirth

### PR DESCRIPTION
**Pull request by stevecotton**
@Pentarctagon , @gfgtdf This isn't ready for merging (because it's untested), but it (slightly) simplifies your #5137 and #5131 .

Its inclusion in mainline is causing extra work in tasks roadmapped for 1.15.x.
It has some of the deprecated ^Uf mushrooms, and some use of the {MODIFY_UNIT}
macro.

If it comes back then it will likely start as UMC.

### CODE REVIEW

**Review by nemaara — APPROVED** [review]
As long as the campaign doesn't crash by removing these scenarios it seems fine to me.

**Comment by stevecotton** [comment]
Thanks for the feedback, will do some testing and (hopefully) merge afterwards.

**Comment by cooljeanius** [comment]
> 
> If it comes back then it will likely start as UMC.

There's already Northern Rebirth Remake on the add-ons server that has the evil branch

**Comment by stevecotton** [comment]
Thanks @cooljeanius , I've added that to the draft release notes. https://wiki.wesnoth.org/Release_Notes_1.15.5

**Pull request merged**
