### PR TITLE
plague tests

### PR DESCRIPTION
**Pull request by Pentarctagon**

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Are both leaders an Elvish Archer in COMMON_KEEP_A_B_UNIT_TEST? Normally in unit tests the second leader is an Orcish Grunt, or so I thought…

More importantly… why are you testing plague as an ability? Shouldn't it be tested as a weapon special first and foremost?

**Comment by CelticMinstrel** [comment]
> Every ability test I've added should give identical results when applied as a weapon special to all weapons.

This is probably true. I just think it makes more sense to test fewer things at once – doing your weapon special tests as abilities means you're testing the weapon special and the "leadership-style special granting" mechanism at the same time.

**Comment by Pentarctagon** [comment]
The original motivation behind adding these tests was to have a baseline of tests for all abilities. Since weapon specials can also be used as abilities, they also need to be included.

**Comment by CelticMinstrel** [comment]
I agree they need to be included. It just seems odd to test them as abilities when there isn't yet a test of them as specials.

But it doesn't actually matter in the end.

**Pull request merged**
