### PR TITLE
WC: update todo.txt file

### PR DESCRIPTION
**Pull request by knyghtmare**
Removes completed TODOs and ones deemed irrelevant.

### CODE REVIEW

**Comment by soliton-** [comment]
IMO it's not useful to keep the file. The todo is better described here:
https://github.com/wesnoth/wesnoth/blob/fe09128ee582b502546255bcc1fd0a87d6378d56/data/campaigns/World_Conquest/lua/game_mechanics/dropping.lua#L2-L4

**Comment by gfgtdf** [comment]
Was is the state of the removed todos? was it partly implemented or was it decided that it wasn't worth it.?

**Comment by knyghtmare** [comment]
> Was is the state of the removed todos? was it partly implemented or was it decided that it wasn't worth it.?

Let's see

> * translatable strings are still a mess, some are defined at top of the file while other are defined in the middle.

> * the artifacts file should be change in the same way as the training file wrt translatable strings.

According to [this link](https://github.com/wesnoth/wesnoth/issues?q=is%3Aissue+wc+translation+is%3Aclosed), all WC translation issues seem closed/fixed.

> * We should consider moving the pickup event implementation to core (and rename it)

This is undecided.

> * Maybe change the recruit costs for certain types of units. e.g. Fencers are too expensive, Dwarvish fighters are too cheap etc.

Hejnewar mentioned it's not worth doing or not necessary. 

> * Maybe readd the ruined Fence terrain but in better quality.

I don't think this is necessary.

**Comment by gfgtdf** [comment]
hmm okay makes sense i guess.

**Comment by soliton-** [comment]
If any of these todos should get more attention someone should create issues for them. A todo note in some code or a text file is easily overlooked.

**Comment by knyghtmare** [comment]
> If any of these todos should get more attention someone should create issues for them. A todo note in some code or a text file is easily overlooked.

I will merge this PR and then make a new FR for the remaining TODO...since it's more of a discussion and then implementation from addon.

**Comment by soliton-** [comment]
When squash merging please edit the commit message to something sensible.

**Pull request merged**
