### PR TITLE
Lua read file

### PR DESCRIPTION
**Pull request by gfgtdf**
this adds a function wesnoth.read_file() to read a files contents intoa  string.

This also contains some unrelaed changes to 2p dark forecast mp map.

### CODE REVIEW

**Comment by Vultraz** [comment]
Should be fine as long as it can only be used with the same restrictions as the preprocessor include, for security reasons.

**Comment by aginor** [comment]
I'm slightly nervous about this PR, it feels like it might have security implications. I'm not familiar with the restrections on the preprocessor includes, but I wonder if they would be sufficient.

**Comment by gfgtdf** [comment]
Removed the 5mb file limit and fixed the todo.

**Comment by CelticMinstrel** [comment]
So, what happens if you try to read something like "~add-ons/../../preferences"? Hopefully it rejects this?

Also, I'm pretty sure Boost.Path (bfs::path is how it's called in Wesnoth) can already do all this work for you - any reason you're not using this? (Might be slightly complicated for "./", but I think there's something like `relative_to` available.)

@aginor - Ignoring commit 0f11995 and assuming read_file uses the same path resolution system as dofile, I don't think there's any security risks in adding read_file. I'm unsure of commit 0f11995, as ".." is a walking security risk, but if it's handled properly (which I can't tell from just glancing at the code) it might be okay.

(Is it `get_wml_location()` that verifies the path is within an allowed directory?)

**Comment by gfgtdf** [comment]
> Also, I'm pretty sure Boost.Path (bfs::path is how it's called in Wesnoth) can already do all this work for you - any reason you're not using this? (Might be slightly complicated for "./", but I think there's something like relative_to available.)

I looked for a boost filessytem function to resolve /../ and /./ but all these seem to require abolute paths.

**Comment by CelticMinstrel** [comment]
But you're converting it to an absolute path anyway.

**Comment by gfgtdf** [comment]
> But you're converting it to an absolute path anyway.

Well, yes get_wml_location() does that, but i want that to hapen _after_ i resolve the /../ so that the /../ cannot change the the part of the path that is appended there.

**Comment by CelticMinstrel** [comment]
Oh, so it's not yet an absolute path when you pass it to get_wml_location()?

I guess that means that get_wml_location() also doesn't check to make sure that the path is in an allowed directory?

**Comment by gfgtdf** [comment]
merged manually

**Pull request closed without merging**
