### PR TITLE
MP Faction Select dialog: Show leader unit details.

### LINKED ISSUE #1491: show unit details in mp leader selection dialog (GNA #23669)
**[Original submission](https://gna.org/bugs/index.php?23669)** by anonymous on 2015-06-28

It would be nice if the leader selection dialog in mp had a button to show the unit details like the recruit dialog has.

(Reproduced on all)
Release: 1.12
Priority: 5 - Normal
Severity: 3 - Normal

### PR DESCRIPTION
**Pull request by jostephd**
If the leader hasn't been discovered, the "Unknown Unit" topic will be shown.

Fixes #1491.

This is for 1.14. I tried to rebase it to master but the help system in master doesn't work for me at all right now even without the patch.

### CODE REVIEW

**Comment by gfgtdf** [comment]
> If the leader hasn't been discovered, the "Unknown Unit" topic will be shown.

I thinking it doesn't be better if the unit info was always shown

**Comment by jostephd** [comment]
Okay, done

**Comment by gfgtdf** [comment]
> Okay, done

his was actually not what i meant, i thought you can show a units help page without addong it to the known units list? Iirc at least the lua/wml api show_help allowed that by adding some prefix to the help page id, so the c++ api should allow such a thing aswell.

**Comment by jostephd** [comment]
I don't see anything in description_type() and intf_open_help() about showing a unit's help page without discovering it. I also don't understand why what that would achieve, currently "being shown on the help" is the only thing that encountered_units controls (except for gui2::tip_of_the_day::shuffle), so if we show a unit's help why shouldn't we add it to the list permanently.

**Comment by gfgtdf** [comment]
hmm maybe i just remember it wrongly then ? i somehow rememerb that i did something like that in my addon at some point but probably i just let debug mode fool me.

**Comment by jyrkive** [comment]
Thank you for the pull request, and sorry it took us this long to merge.

**Comment by jostephd** [comment]
You're welcome.

**Pull request merged**
