### PR TITLE
Realign translated logo images.

### PR DESCRIPTION
**Pull request by Wedge009**
Ever since the logo was split into separate image (swords and shield) and text, as well as the dimensions being modified, translated logos have been misaligned. While it's true the translated logo images should be remade so that it the image and text are similarly separated, we can still align the existing logos with the current logo background image.

In many cases, the translated logos were not even showing on the loading screen because its dimensions broke a check in blit_modification::operator() (translated logo height > background logo height). After this change, all translated logos should display again (and are even nicely aligned on top of the current logo background image).

### CODE REVIEW

**Comment by Vultraz** [comment]
This is not really necessary, since there are new translated logo images pending. However, keep this open should we not get hold of those for some reason.

**Comment by Wedge009** [comment]
Are we getting it for all of them? I was getting annoyed seeing a blank logo on the loading screen, and also wanted to find out why the logo was showing on the title screen but not the loading screen.

**Comment by Wedge009** [comment]
How soon are we expecting the new translated logo text? If it's a long time in coming, can we put these in now? As it currently stands, the master build gives a broken experience when using these languages (other languages just use the standard English logo)

**Comment by Vultraz** [comment]
Hopefully not too long. I'll send a PM to the guy and see if he can send a batch of what he already has (which is almost everything).

**Comment by Vultraz** [comment]
Closing this since all the old logo images were deleted in b7cb89209217d44ec427ef08736466ee2207fceb.

**Pull request closed without merging**
