### PR TITLE
Schema: attempt to fix specials used as abilities

### PR DESCRIPTION
**Pull request by newfrenchy83**

### CODE REVIEW

**Comment by newfrenchy83** [comment]
@jostephd @nemaara , in wait what https://github.com/wesnoth/wesnoth/pull/4481 was tested and merged, can you review this please?

**Comment by nemaara** [comment]
I don't have the ability to review c++ or schema things. You're better off asking celmin or waiting for josteph's response.

**Comment by CelticMinstrel** [comment]
I think this should be fine to merge.

**Comment by jostephd** [comment]
I don't have time to review things currently (except regressions I'm responsible for).

**Comment by Vultraz** [comment]
Merging since celmin said this should be fine.

**Pull request merged**
