### PR TITLE
SDL2 related guifixes

### PR DESCRIPTION
**Pull request by aginor**
This tries to mop-up all remaining major GUI related flaws from the SDL2 merge.

These changes adds primitive layering to the drawing. It is done using event contexts in GUI1, and event dispatchers in GUI2.
Upon certain events, it triggers a full redraw of every context, in order, starting bottom up.

It fixes the following bugs, and most likely a number of unreported ones too.

https://gna.org/bugs/?24294
https://gna.org/bugs/?24212
https://gna.org/bugs/?19666
https://gna.org/bugs/?24260
https://gna.org/bugs/?24261

### CODE REVIEW

**Comment by aginor** [comment]
Does anyone object to this being merged?

**Comment by CelticMinstrel** [comment]
I'm still reviewing it, slowly.

**Comment by CelticMinstrel** [comment]
I don't see any issues. I'll see if I can find time to test it today.

**Comment by aginor** [comment]
@Vultraz and @CelticMinstrel has booth looked at this and think it's ok to merge.

**Pull request merged**
