### PR TITLE
Fix Lua update documentation, $UID in Docker scripts, and execute permissions on installed scripts

### PR DESCRIPTION
**Pull request by pehjota**
Add Dockerfile update to Lua update documentation
Another minor documentation improvement I should have thought to include in #8234 or #8394 (I knew I was forgetting something else...).

Replace Bash `$UID` with portable `$(id -u)` in Docker scripts
@Pentarctagon noticed in commit 9a34cbb3291 that `$UID` isn't set when `/bin/sh` isn't GNU Bash.  `id -u` is [specified by POSIX](https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/utilities/id.html).
Also move `-xe` to a `set` command (in case someone runs scripts with `sh path/to/script` instead of `path/to/script`) and add `set -u` to complain more loudly about such unset variables.

Make TeamColorizer and update_pathfinding executable    
These scripts get installed but were missing execute mode bits.

### CODE REVIEW

**Comment by Pentarctagon** [comment]
@loonycyborg this is fine for `itchio_upload` I assume?

**Comment by pehjota** [comment]
`itchio_upload` has to be run with at least one command-line argument (`$PLUGINSDIR` is in single quotes, so it's not expanded by the shell).  Without this change, forgetting the argument results in 7z giving a cryptic error message that effectively means "No such file or directory":

    [...]
    
    Scanning the drive for archives:
             
    ERROR: No more files
    wesnoth--win64.exe
    
    
    
    System ERROR:
    Unknown error -2147024872

With this change, the shell prints a more helpful error message: `utils/itchio_upload: 11: 1: parameter not set`.

It might be even more user-friendly in such scripts to check for arguments and print a usage error, e.g.:

    if [ ${#} -ne 1 ]; then
    	printf 'Usage: %s version\n' "${0}" 1>&2
    	exit 1
    fi

But I didn't go that far here.

**Comment by pehjota** [comment]
I added a commit to fix some spelling errors (not in translatable strings).

FYI, I'm hoping these fixes can go in 1.17.26.

**Comment by loonycyborg** [comment]
> @loonycyborg this is fine for `itchio_upload` I assume?

yes it won't break anything for me.

**Pull request merged**
