### PR TITLE
Added death of Galtrid to defeat conditions for Human Alliance.

### PR DESCRIPTION
**Pull request by tranceitionalMynd**
Equivalent to pr #526 in the master branch.

Addresses https://gna.org/bugs/?23919.

### CODE REVIEW

**Comment by tranceitionalMynd** [comment]
Commit 0d13b2b addresses https://gna.org/bugs/?23882

**Comment by Vultraz** [comment]
Could you please rebase this before I merge? It's preferable to remove merge commits before we accepts PRs.

**Comment by Wedge009** [comment]
Need help with rebasing?

**Comment by CelticMinstrel** [comment]
I don't really mind merging things manually, rebasing them myself. If you'd like me to do that, just let me know.

**Comment by tranceitionalMynd** [comment]
Yes please and sorry about that!

**Comment by CelticMinstrel** [comment]
Ah, that question was more addressed to the other developers. Sorry for the confusion.

**Comment by Wedge009** [comment]
The master version has already been merged some time ago. If you want to do it manually, I don't think anyone would object. I would do it myself but then I would need to produce another PR anyway.

**Pull request merged**
