### PR TITLE
Increase minimum macOS version to 10.15.

### PR DESCRIPTION
**Pull request by Pentarctagon**
I'm tired of the repeated arguments around increasing the minimum macOS version vs new language features. So barring any kind of clear definition that can be used to determine it, this is the lowest version with a strong, clear reason to not upgrade past. After all, I can't think of a language feature that would be worth losing celticminstrel as a contributor.

### CODE REVIEW

**Comment by Pentarctagon** [comment]
The problem is there doesn't seem to be any strong reason *not* to raise the requirement either. It's been pointed out before how only a very tiny fraction of players use 10.12-10.14 today (and therefore even fewer by the time 1.20 is released). If that's the only reason to not set a new minimum version for macOS, then that effectively just means we can never increase the minimum version because that statement will never not be true.

**Comment by Wedge009** [comment]
I'm not aware of the 'arguments' for one way or another, and I suppose macOS environment might be different to Windows, Linux, and others, but does this change affect just the developers or both developers and users of the compiled binaries? I think generally, no matter how old - even if it's officially 'unsupported' - it's preferable to set the minimum version to what's actually required by the program. eg Even if it's no longer supported, if a program only needs features that are available in Windows XP, then that should be the minimum version.

As I recall, we bumped the minimum version to Windows 10 for Wesnoth because of issues relating to Unicode path handling. I have no idea if that aspect is relevant to the discussion here.

**Comment by Pentarctagon** [comment]
To post it here as well: https://wiki.wesnoth.org/Cpp_features_blocked_by_version

I've added sections to list out things that do and don't justify increasing versions - if macOS is going to continue to be the OS where increasing the minimum version that keeps causing arguments, then either those sections need to be filled out so we have some actual concrete guidelines or I intend to merge this PR to make it a moot issue. At this point I think these arguments are causing more of a problem than increasing the minimum macOS version to 10.15 and losing zero contributors and near zero players.

**Comment by Wedge009** [comment]
I was asking from a curiosity angle rather than intending to block this change. I don't mind either way - especially as I don't use Apple.

**Comment by soliton-** [comment]
> The problem is there doesn't seem to be any strong reason _not_ to raise the requirement either. It's been pointed out before how only a very tiny fraction of players use 10.12-10.14 today (and therefore even fewer by the time 1.20 is released). If that's the only reason to not set a new minimum version for macOS, then that effectively just means we can never increase the minimum version because that statement will never not be true.

Why is it useful to disregard whatever tiny fraction just because? Not disregarding them is exactly why the default should be to _not_ raise the requirements.

Statistics on how many users use a version are useful when comparing to arguments on why it is useful to raise the required version. We should gain a lot if it'd impact a lot of people while less gain is acceptable if the change impacts less people. But there needs to be a reason either way besides "new is shiny and good" or something.

**Comment by Pentarctagon** [comment]
> We should gain a lot if it'd impact a lot of people while less gain is acceptable if the change impacts less people. But there needs to be a reason either way besides "new is shiny and good" or something.

And we need to define what that actually means. The current way this is being handled isn't working.

**Comment by soliton-** [comment]
The recent reversions were certainly not handled well but I don't really see how this PR helps. This is not a problem with a final decision once and for all and that's it.

Hashing out what we view as acceptable (via that wiki page for example) is needed either way and will be an ongoing process.

**Comment by Pentarctagon** [comment]
We'll see what happens with the wiki page. If nobody decides to start filling out the lists of things that do/don't justify a minimum version increase, then it can't be that much of a problem.

**Comment by gfgtdf** [comment]
I do think that having _complete_ support for c++17 is by itself an advantage even if the actual feautres are minor. Without it you have in theory to check for every feature whether its actually supported by all compilers that we use, with complete c++17 support you can just look at the cppreference.com and check that itsays c++17. I don't know whether this pr would give that though.


Also about possible new contributors, i think we are much more likeley to scare them away by requireing them to write code for older compilers than by requireing them to have a somewhat recent compiler installed. In my experience in particular new contributirs are kinda used to be able to use the new stuff just like they probably do in their personal projects.

**Comment by Pentarctagon** [comment]
I also think that a bunch of smaller features can collectively justify a minimum version increase, if there minimal to no impact to developers or players.

**Comment by Vultraz** [comment]
Supporting 10.15 as a minimum, it looks like the newest version of XCode that can be run is 12.4 (assuming you have an Intel mac), according to https://developer.apple.com/support/xcode. 12.5 bumps the requirement to macOS 11, for some reason. Looking at [this helpful list I found](https://gist.github.com/yamaya/2924292#file-xcode-clang-vers-L370), the version of apple-clang that shipped with XCode 12.4 was `12.0.0`, which I'm going to assume loosely corresponds to clang 12. Clang 12 was released in April 2021, which means that *under the proposed change here*, we'd tie ourselves to a three year old compiler.

I can't find info on the last XCode version to support 10.13, let alone 10.12. Apple's table goes back to Xcode 10.2, which supports MacOS 10.14 and up. Given that 10.12 received its last official feature release in 2017 and its last security patch in 2019, I think at the very least its reasonable to go for 10.15--which itself has been EOL for almost 2 years (Sept. 2022, according to https://endoflife.date/macos)!

**Comment by CelticMinstrel** [comment]
> which I'm going to assume loosely corresponds to clang 12.

This is a horribly bad assumption. I'm 99.9% sure that the 12 here refers to the version of Xcode that it ships with – in other words, Apple Clang 12 ships with Xcode 12, Apple Clang 13 ships with Xcode 13, etc. I don't believe it has any bearing on the version of vanilla clang that it's based on.

This is total speculation, but I'd guesstimate that Apple Clang 12 may be based on somewhere around clang 8 or 9.

**Comment by Pentarctagon** [comment]
https://en.wikipedia.org/wiki/Xcode#Version_comparison_table and https://en.wikipedia.org/wiki/Xcode#Toolchain_versions seem like they'd be useful to reference.

**Comment by soliton-** [comment]
> Also about possible new contributors, i think we are much more likeley to scare them away by requireing them to write code for older compilers than by requireing them to have a somewhat recent compiler installed. In my experience in particular new contributirs are kinda used to be able to use the new stuff just like they probably do in their personal projects.

While I'm sure there is truth to that what project can they contribute to with that approach? Unlikely to be any bigger mature project. If you must use the latest language features starting a new project or contributing to a new one seems mandatory (or you need to write compatibility code in addition). Even then as time goes on it's likely to change as in any other established project.

On the other hand there are those outliers that have the technical knowhow to run on old versions for whatever reason and if they're interested in wesnoth there is also a good chance they'll contribute.

**Comment by Pentarctagon** [comment]
There's a difference between using the latest features and being able to use all of C++17 though.

**Comment by soliton-** [comment]
Definitely and based on "requireing them to write code for older compilers" we're scaring them away with that.

To be clear allowing us to use all of C++17 instead of some unclear subset is certainly a strong reason in my book. Would be good to know what Xcode version gives us that.

**Comment by Pentarctagon** [comment]
I'm honestly not sure how to figure that out. https://en.cppreference.com/w/cpp/compiler_support#cpp20 lists features by only xcode version, https://developer.apple.com/xcode/cpp/ is mostly empty, and as we saw with optionals Apple's documentation can just be wrong.

**Comment by CelticMinstrel** [comment]
> Would be good to know what Xcode version gives us that.

What Xcode version _and_ what deployment target. Xcode 12 targeting 10.13 clearly doesn't. I don't know if Xcode 12 targeting 10.15 does.

**Comment by Pentarctagon** [comment]
Closing for now since the info on the wiki page doesn't make a particularly convincing case - most of the features listed don't even have minimum requirements specified.

**Pull request closed without merging**
