### PR TITLE
Moves the lists of sources into their own files

### PR DESCRIPTION
**Pull request by Pentarctagon**
Moves the lists of source files out of src/SConscript and src/lua/SConscript and into their own individual files under scons/sources/

This also directly adds files which were being unconditionally added to source lists, such as game_config.cpp, filesystem_common.cpp, filesystem_boost.cpp, and gettext_boost.cpp being added to libwesnoth_core_sources via the .extend() method.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I'm just wondering if there's a benefit to this...

**Comment by gfgtdf** [comment]
I think this makes it rather harder to update the scons with new files sine you now have to seach for the correct file to add them while previously it was always in src/sconscript. It migth have the advantqage that these files can more easily be used by the cmake and other scrips aswell, do you intend to do that?

**Comment by Pentarctagon** [comment]
My original thought was that it makes the sconscripts easier to read, since now the data (lists of source files, a few of which are really really long) are separate from the logic of what the sconscripts are actually doing.  If the thought is that this would end up actually result in more effort, then that isn't what I intended, and obviously this shouldn't be merged.

That said, I could certainly additionally modify cmake to use the same source file lists (not sure about other tools), but it would be much more involved than simply changing cmake to instead read from a file.  For example, cmake's version of `libwesnoth.a` (which is named `libwesnoth-game.a`) does not include the file "generic_event.cpp" - it is instead included with the main wesnoth sources (`wesnoth_sources` for scons, `wesnoth-main` for cmake).  The lua sources are also built differently, in that there is a separate sconscript in src/lua/ in addition to the sconscript in src/, whereas cmake handles everything in a single cmakelists.txt in src/.

There are also differing libraries defined between scons and cmake as well.  For example, cmake has a list of source files for a library called `wesnoth-gui_widget` which does not exist for scons - in scons, it looks like (from a quick glance) those files are simply included in the list of files in `wesnoth_sources`.

So I guess it comes down to how much benefit is seen in synchronizing scons and cmake to make them build the same things from the same lists of source files.

-

Also, if these lists of source files are to be used by more than scons, they should probably be moved out of the scons/ directory.

**Comment by GregoryLundberg** [comment]
Don't worry about what is in which library. The libraries are basically noise. Some say they can't compile and link without them but for most all they do is increase the time needed to compile and link.

If you're interested in re-aligning the libraries, I have the source files organized by which target requires each. It's a couple weeks old but should not take more than a few minutes to get up-to-date.

An acceptable alternative would be to put everything in one library (after fixing the library-update phase to only update what needs updating).

The other toolsets (XCode, Visual Studio, CodeBlocks) generally either don't use the SCons/CMake stuff at all or use it entirely. So don't worry about them.

**Comment by CelticMinstrel** [comment]
If I were designing the build progress from scratch, I'd probably only have two libraries: the core Lua sources, which are never rebuilt anyway, and the few sources that are common to both wesnoth and wesnothd. That said, a library for the common files isn't actually necessary; you can just as easily simply include the files into both targets and scons/cmake should still only build each one once. I'd still keep Lua separate, however.

**Comment by Pentarctagon** [comment]
First things first, I think - should I start altering the cmake build script to use the lists of source files I pulled out of the sconstructs/is that something which would be merged?  Removing/altering libraries that are being unnecessarily built should be done once that's done and scons and cmake are using the same source file lists, whether that's added as part of this PR or a new PR just for adjusting the libraries.

@GregoryLundberg I assume you mean #871/#874?

@CelticMinstrel I think the two libraries make sense.  The fewer places things get duplicated, the better.

**Comment by GregoryLundberg** [comment]
Yes, PR 874 is an example of where libraries can hide a mistake. The tools failed to build because one module was changed to use externals not included in the existing libraries or the list of modules on the command-line. Had everything been in a library, the tools would have built, but been amazingly larger than necessary due to all the dead code being pulled in.

**Pull request closed without merging**
