### PR TITLE
Add code to compare the local wesnoth version with the latest available wesnoth version

### PR DESCRIPTION
**Pull request by gfgtdf**
The intention is to use it for an automatic updater.
currently this unfornately only compares the first 2 parts of the
wesnoth version but this shouldn't be hard to fix.

### CODE REVIEW

**Comment by Vultraz** [comment]
I wonder if you could put these functions in version.*pp instead of a separate file?

**Comment by gfgtdf** [comment]
no, why should I?

**Comment by gfgtdf** [comment]
I tried to add support for https so that it could doanload the link and teh chacksums via https to enure they don't get changed. But it seems like boost/asio/ssl.hpp required openSSL to be installed which seems to be a rather big dependeny which also doesn't offer a msvc projectfile to build it :/ .

I wonder whether it would be easier to implement some handmade check instead.

**Comment by aginor** [comment]
No, I don't think we should roll our own TLS implementation. OpenSSL is a reasonable dependency, in Linux and OSX. Does boost/asio use the windows TLS implementation when on windows?

**Comment by gfgtdf** [comment]
> OpenSSL is a reasonable dependency, in Linux and OSX
The automatic updater here that this here is about, is most likeley windows only, so this doesnt really matter unless we have someone who want to work on a autmatic updater for osx.

> Does boost/asio use the windows TLS implementation when on windows?
No it doesn't

> No, I don't think we should roll our own TLS implementation
Hmm i don't think we need a whoe TLS implementation to do that.

**Comment by CelticMinstrel** [comment]
Obviously I'm really late to this topic, but I don't think OpenSSL (a C library) is an unreasonable dependency on Windows; as far as I know, prebuilt Windows libraries should work fine (pretty sure I've even used one for something myself).

If it's that much of a problem though you could always make it optional with conditional compilation or something.

**Comment by gfgtdf** [comment]
> as far as I know, prebuilt Windows libraries should work fine 

iirc the openssl team explicitly discourages from using prebuild libraries this on their homepage.

**Comment by CelticMinstrel** [comment]
That's... weird? Why would it make any difference whether someone uses a prebuilt binary?

**Comment by aginor** [comment]
Presumably it's a security precaution, there's no way of telling if the binary has been backdoored/weakened in order to provide breakable crypto.

https://www.openssl.org/community/binaries.html

**Comment by GregoryLundberg** [comment]
The choice of whether to use http vs https has to do with securing the transport. It does little to ensure the version offered is verifiable.

The common solution is to use public-key cryptography to sign the data. This works whether the transport is plain-text or encrypted.

Under no circumstances should we roll our own cryptographic package or implement our own TLS. There is nothing inherently wrong with using pre-built binaries .. provided you trust the builder. My recommendation, here, would be to examine how the Apache project handles the issue.

If we do add TLS it should be for all communications, not just update checks.

As for update checks: the cryptographic package we'll need for TLS should provide the PKI support we'll need for signing and verifying the update-check data.

**Comment by vgaming** [comment]
If we only want to notify about an upstream release, there's no point (that I could see) in doing any encryption at all.
I mean, we only notify. If there's a release, we'll share an https link for downloading anyway.

Without any encryption (http), an attacker could only make wesnoth client unaware of a new release or report the existence of a new version whereas there is none. I wouldn't really bother about any of the possible "attacks".

**Comment by CelticMinstrel** [comment]
Reporting a nonexistent release _could_ be bad if a link to the release is included, but if it's literally just a notification "There's a new version, go download it at the website" and the message is static and baked into the client (so that a malicious actor can't inject a bad link), then I think it's probably fine.

**Comment by CelticMinstrel** [comment]
Also, looking at the older clients, @gfgtdf's worry about OpenSSL is moot now that it's become a dependency.

**Comment by CelticMinstrel** [comment]
...comments, not clients. Can't edit my posts on mobile.

**Comment by gfgtdf** [comment]
this code was meant as a preperation for an automatic updater, and if it for eample sends a links from where to download then such attacks woudl sure be a problem.

**Comment by vgaming** [comment]
@gfgtdf I'm surprised wesnoth would want such complexity. But OK.

**Comment by Vultraz** [comment]
Since it's very unlikely we'll implement out own auto-updater, should we close this? Or do we eventually want to implement the update-is-available popup for non-Steam releases?

**Comment by GregoryLundberg** [comment]
No.  Keep it open.

While I agree we probably can't provide an auto-updater, it sounds like an excellent idea to have the game contact the Mothership periodically and inform the player when a new version has been released. Yes, this means they might come to find no package for their platform. That could be mitigated by delaying changing the document until the major packages are built.

There are some security considerations but if we follow the model used by Firefox or Chrome, we should be fine.

In addition, like Chrome, there probably should be a player option to choose Stable or Canary (1.12.6 vs 1.13.11).

**Comment by vgaming** [comment]
I'd like to note that we're inside a PR currently. WIP and master-conflicting to be specific.
Considering this, I'd propose to raise a new _issue_ with clearly defined goals, reference this PR in it and still close the unmergeable PR for now. When we'll be ready, we can make a PR that fixes the issue.

**Comment by vgaming** [comment]
> for non-Steam releases

@Vultraz for non-Steam _Windows_ releases only? I believe 99% of Linux users use a package manager and would like packages built by their distribution, with compatible library versions etc. MacOS has a package manager too IIRC?

**Comment by CelticMinstrel** [comment]
If by "MacOS package manager" you mean Homebrew, MacPorts, or Fink, those are 3rd-party and I wouldn't expect most users to have them.

Macs do have the App Store (which Wesnoth should really be on!) but that's not relevant for a Steam release. 

---

Anyway, I agree with @vgaming on moving discussion to a new issue.

**Pull request closed without merging**
