### PR TITLE
Fire Wraith and Jinn

### PR DESCRIPTION
**Pull request by doofus-01**
Just an initial base frame and config file, but still good to get something concrete up.  Lordbob already made the portrait for it,

### CODE REVIEW

**Comment by doofus-01** [comment]
The Jinn sprite still needs a bit of revision, but it's mostly there, supposed to match Lordbob's portrait.  I changed the attacks and stats a bit, that needs some review soon.

**Comment by CelticMinstrel** [comment]
In my opinion, both fire and wind blast seem to suit a jinn better than lightning…

**Comment by Hejnewar** [comment]
I would like to see some melee attack for Jinni even if weak. When it comes to other attacks I dont actually know because there is no lore for him right now (that I know of). When it comes to balance I will review statistics of all new units in separated PR (unless you really want then I can do review for this PR).

**Comment by doofus-01** [comment]
> In my opinion, both fire and wind blast seem to suit a jinn better than lightning…

The lightning was from the portrait, and makes sense for a desert just as much as fire.

>  would like to see some melee attack for Jinni even if weak. When it comes to other attacks I dont actually know because there is no lore for him right now (that I know of). When it comes to balance I will review statistics of all new units in separated PR (unless you really want then I can do review for this PR).

I thought this wasn't supposed to have a melee attack for some reason, but I got nothing against that changing.  I guess something like the ghost touch? (thematically, not necessarily the same numbers)  Balance changes in another PR is fine, as long as the changes aren't so radical that this needs new graphics.

**Comment by CelticMinstrel** [comment]
> The lightning was from the portrait, and makes sense for a desert just as much as fire.

I don't think that's the right reasoning to decide whether it makes sense… you should be thinking of whether it makes sense for a jinn, not for a desert.

* Fire makes sense for a jinn, because they're said to be made of "smokeless fire" in folklore.
* Wind makes sense for a jinn, because in Dungeons and Dragons they live on the Elemental Plane of Air. (There might be some deeper folkloric reason behind that too, but I'm not aware of it if it exists.)
* Lighting… _might_ make sense for a jinn, but the fact that they live in the desert isn't a very good reason.

Perhaps we should also be considering what the nature of the jinn is… if they are elementals, then what is their element? Fire, or wind? Maybe both? Or maybe they're not elementals. Are they fickle and capricious beings, similar to fairies? Are they a race exceptionally close to nature, like trolls or wose? What are they?

I think it's better to decide the attacks based on the lore rather than deciding the lore based on the attacks.

I think it's a bit of a stretch to give lightning to a fire elemental. It's not completely nonsensical, but it's definitely stretching the definition of fire. It's a bit less of a stretch to give lightning to a wind elemental, as lightning is generated by the atmosphere. Perhaps it makes the most sense if they are dual elemental of fire _and_ wind? But if that's the case, shouldn't they also have flame powers? I suppose you could argue that they do have them and they're just not encoded in the stats, but… I kinda think there should still be _something_ clearly fiery if they're a fire elemental. Maybe it doesn't have to be an attack. Maybe a flame aura or something?

**Comment by Hejnewar** [comment]
Ok, I made up my mind lookin at the portrait and sprite and honestly the portrait is so good that im willing to create lore around it (sprite is great too).

> - Fire makes sense for a jinn, because they're said to be made of "smokeless fire" in folklore.
> - Wind makes sense for a jinn, because in Dungeons and Dragons they live on the Elemental Plane of Air. (There might be some deeper folkloric reason behind that too, but I'm not aware of it if it exists.)
> - Lighting… might make sense for a jinn, but the fact that they live in the desert isn't a very good reason.

1. We already have smokeless flame in game or at least something that is flame and doesn't have smoke, this portrait is much more interesting than the folklore vision anyway.
2. "because in Dungeons and Dragons" - uhmmm.... we are in Wesnoth. Sorry, it really sound like: "Look they did that so we should do the same." and I really don't like throwing opportunities to create something original just like that. 
3. Yeah, I agree. 

> Perhaps we should also be considering what the nature of the jinn is… if they are elementals, then what is their element? Fire, or wind? Maybe both?

Looking at portrait I can see sand, metal, cloth and energy. I can also discard cloth. If we say wind that is not explaining metal at all and metal seems to be main or "still in tact" part of this unit, fire is also out of the equation because it is nowhere to be seen. So what force would explain all three? In my opinion it would be gravity / magnetism / electromagnetism (and that would also explain lightning quite well).   

> Are they fickle and capricious beings, similar to fairies? Are they a race exceptionally close to nature, like trolls or wose? What are they?

Is it nature at all? It looks very artificial to me. It's hands are very much mechanical. Was it perhaps created by someone? (Why else would it be wearing clothes even if very torn ones and so many golden trinkets, it's very... fashionable.) Maybe it was stone golem with golden core made to fulfill wishes and it eroded over time into what it is today? Im honestly very much for leaving this not explained and letting people figure out what it is in UMC or something. 

> I thought this wasn't supposed to have a melee attack for some reason, but I got nothing against that changing. I guess something like the ghost touch?

Ghost touch seems fine it could even be lightning because I think it could fit it really well in my opinion.

**Comment by CelticMinstrel** [comment]
>"because in Dungeons and Dragons" - uhmmm.... we are in Wesnoth. Sorry, it really sound like: "Look they did that so we should do the same." and I really don't like throwing opportunities to create something original just like that.

Well, I don't disagree, but then that also suggests that making it an air elemental is too close to D&D, right?

> Ok, I made up my mind lookin at the portrait and sprite and honestly the portrait is so good that im willing to create lore around it (sprite is great too).

I really don't think this is a good idea, regardless of how nice the portrait is (and I do agree it's a nice portrait).

> If we say wind that is not explaining […] fire is also out of the equation because it is nowhere to be seen.

My impression of the portrait is that it's essentially a cloud of smoke wearing a robe, with artificial arms. If you take that interpretation, both wind and fire fit quite well - fire works because fire produces smoke, and wind because wind could be used to manipulate objects.

It seems that LordBob said we was thinking of it as a cloud of sand rather than smoke, but I suppose there are similarities in appearance. If you take it as a cloak sand cloud, it rules out fire, but wind still fits.

> So what force would explain all three? In my opinion it would be gravity / magnetism / electromagnetism (and that would also explain lightning quite well).

While you're right that electromagnetism can explain lightning, I don't see anything in the portrait to suggest magnetism or electricity.

> Is it nature at all? It looks very artificial to me. It's hands are very much mechanical.

You're right that the hands look artificial, though I don't think I'd go so far as to call them mechanical. They look more skeletal than mechanical.

**Comment by Hejnewar** [comment]
> Well, I don't disagree, but then that also suggests that making it an air elemental is too close to D&D, right?

I guess but it also depends on execution. 

> While you're right that electromagnetism can explain lightning, I don't see anything in the portrait to suggest magnetism or electricity.

I was trying to find a thing that would unite everything we see on the portrait and that is what I came us with. It's hands have something blue around them and well it's open to interpretation but it could be for example preparing to cast lightning. 

> You're right that the hands look artificial, though I don't think I'd go so far as to call them mechanical. They look more skeletal than mechanical.

I see why you are saying that and you are right with that but I could say that there could be mechanical parts inside to help with moving them and well they are most likely operated with magic, question is to what degree. I guess its also very open to interpretation. 

I just realised that the only thing we are discussing here is attack icon and attack name. Not even attack type because for both parties fire would be good attack type. Kinda funny. 

Then while we are on the topic what do you think about it's resistances? I don't see any change to them so I assume that they are 60/60/60/0/70/0 and I don't think that they fit current Jinn well, they would pretty much indicate that it's less physical than ghost and cold resistance is like for real undead.

**Comment by CelticMinstrel** [comment]
> I was trying to find a thing that would unite everything we see on the portrait and that is what I came us with. It's hands have something blue around them and well it's open to interpretation but it could be for example preparing to cast lightning.

Trying to unite absolutely everything into a single unified ability doesn't seem like a good approach though.

> I just realised that the only thing we are discussing here is attack icon and attack name. Not even attack type because for both parties fire would be good attack type. Kinda funny.

Yeah, if the question is whether it's fire or lightning, this discussion won't have any effects on actual game mechanics.

> Then while we are on the topic what do you think about it's resistances? I don't see any change to them so I assume that they are 60/60/60/0/70/0 and I don't think that they fit current Jinn well, they would pretty much indicate that it's less physical than ghost and cold resistance is like for real undead.

Oh, you have a good point… its movement type is "spirit" but there's no overrides to defense or resistance. I think it makes sense for it to have spirit-like physical resistances, although they could be less than the spirit since the jinn is probably more of a physical being than a ghost. It should probably have arcane vulnerability (since it's a magical creature) and cold vulnerability, with a resistance to fire.

As for defense and movement… I guess 50% across the board as a flying unit is mostly fine, though I think it might be good to reduce their defense on water and snow and increase it on desert, and also reduce their movement speed over water and snow. They should have at _least_ one of defense and movement reduced in cold environments, in my opinion.

By the way, what did you think of the flame aura idea I threw out earlier?

**Comment by doofus-01** [comment]
The current "sand-storm" standing animation is a cheaply done and should be updated, but I believe that can be done even after 1.16.0 is released.  I gave them a melee attack, I'm not wedded to the cold touch concept but I did think giving them a broad selection of damage types could make them more significant.  (And claws attack icon is just a placeholder.)

> Lighting… might make sense for a jinn, but the fact that they live in the desert isn't a very good reason.

Nah, it's a fine reason, as good as any.  It doesn't contradict traditional depictions of jinn. as far as I can tell.

>Ok, I made up my mind lookin at the portrait and sprite and honestly the portrait is so good that im willing to create lore around it 

I see nothing wrong with that, since the slate is relatively clean at this point.  If we are having lore discussions, I think @nemaara  is still the lead on that and should have some input here.

> Then while we are on the topic what do you think about it's resistances? I don't see any change to them so I assume that they are 60/60/60/0/70/0 and I don't think that they fit current Jinn well, they would pretty much indicate that it's less physical than ghost and cold resistance is like for real undead.

I don't have any love for the current resistances.  If they are a "storms and shadows" type beng, maybe high physical resistances make sense, then make them weak to arcane/cold/fire.

**Comment by CelticMinstrel** [comment]
> I gave them a melee attack, I'm not wedded to the cold touch concept but I did think giving them a broad selection of damage types could make them more significant. 

I'm not a fan of this; a cold attack seems to be entirely counter to the concept of a jinn.

If you're basing a melee attack on the portrait, something physical seems like it makes the most sense. Impact might work if you envision a sand-based attack, or blade for the claws. Even a punch could make sense. A fire attack would also fit. Arcane… I'm not sure.

I don't know whether they _need_ a melee attack, but lacking one is pretty unusual (I think the mudcrawler's the only mainline example, and even that gains a melee on level-up), so it can't hurt to have one.

> I don't have any love for the current resistances. If they are a "storms and shadows" type beng, maybe high physical resistances make sense, then make them weak to arcane/cold/fire.

I don't know about storms and **shadows**… especially not if they have a lightning attack, which is kinda the opposite of shadows.

**Comment by Hejnewar** [comment]
> Trying to unite absolutely everything into a single unified ability doesn't seem like a good approach though.

It can have multiple abilities, it was just my approach and I quite like it to be honest. 

> About resistances

I actually see them as metal parts that are completely within our world and sand and I would assume that hitting sand does nothing. Then I would propose maybe something like 20/30/0/x/x/x and like 60-70% dodge. Very elusive but not very resistant clearly distinct from ghost. Just an idea.

I agree with reducing movement speed there but I don't know about defence I guess it makes sense because I see them as sand and water would reduce their defence.

> By the way, what did you think of the flame aura idea I threw out earlier?

It can work, it can make sense, it can be balanced, it even can have multiple "flavours". It would be highly unusual when it comes to wesnoth mechnics but that doesn't mean that it's a bad thing. (I assume that it's aura that deals fire damage all aroud Jinn in similar way to healing.)

**Comment by CelticMinstrel** [comment]
> It can work, it can make sense, it can be balanced, it even can have multiple "flavours". It would be highly unusual when it comes to wesnoth mechanics but that doesn't mean that it's a bad thing. (I assume that it's aura that deals fire damage all around Jinn in similar way to healing.)

Yeah, that's what I meant by a flame aura. It could be always on, or it could be active only under certain circumstances.

> I actually see them as metal parts that are completely within our world and sand and I would assume that hitting sand does nothing. Then I would propose maybe something like 20/30/0/x/x/x and like 60-70% dodge. Very elusive but not very resistant clearly distinct from ghost. Just an idea.

Sorry, I should've mentioned this earlier, but I don't have the order of the damage types memorized, so I'm not sure which is which in your little summary there, but… if you're saying it should have some resistance to blade and pierce but no resistance or vulnerability to impact, that sounds reasonable.

**Comment by Hejnewar** [comment]
It's blade/pierce/impact/fire/cold/arcane.

> It could be always on, or it could be active only under certain circumstances.

Always active seems to be the most natural way but I'm actually interested in how do you picture these circumstances?

**Comment by CelticMinstrel** [comment]
The two examples I thought up are that it activates only during the day, or that it activates when the jinn is badly injured (maybe 50% or 25% health).

**Comment by Hejnewar** [comment]
Second one would fit something artificial and also would be not great because in general you don't really want to have unit with 50% hp exposed to as many enemies as possible (as defense mechanism one time discharge would be better). Above x% would fit for example fire that is being extinguished, maybe it would fit Fire Wraith or something similar. 

First one makes me think "solar powered".

**Comment by CelticMinstrel** [comment]
My reasoning for the second applies well to a fire elemental type of creature where the fire is contained by a solid skin. Whether or not that actually describes a jinn is another question; perhaps it doesn't. If they're made mainly of smoke and sand, probably not.

**Comment by doofus-01** [comment]
Well, I can't say I agree with or even followed all of that, and I'm not saying you two are wrong, but I'm going to bypass it for now because time is running out.  If you can fit changes in before feature freeze, that's fine with me.

In the meantime, I made the jinn melee attack more boring and got some animations for the fire wraith, so it isn't a statue.  There's a lot of room for improvement on the frames for both units, but I think it's good enough for 1.16. release candidates.  I'll merge once CI passes.

**Pull request merged**
