### PR TITLE
support scenario files in map_file

### LINKED ISSUE #4803: support scenario files in [scenario]map_file
currently the scenarios generated by the scenario editor mare ment to be inclused ina  scenario via {./map/ediro_scenario.cfg}, i think it migth make sense to support them via [scenario]map_file, so if a .cfg file is given in  map_file, the code the currently reads map_file would just call scenario.appens(read_cfg(scenaro["map_file"])).

There are some things im unsure about yrt though:
1) shoudl we use map_file or a new key for things created by the scenario editor?
2) Assuming we used the same key, should we try to detect whther its a scenario or not by the extension or by content?

### PR DESCRIPTION
**Pull request by gfgtdf**
Now a scenario generated by teh scenario editor can be loaded
just like a simple map file
fixes #4803

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Can you explain how the merge works for this case? Will it be different from macro-including the scenario file?

I kinda question the addition of `inherit_attributes` to the config API. Do you think there are other use-cases for it?

**Comment by gfgtdf** [comment]
> Can you explain how the merge works for this case?

Yes, is basically like  the inclusion,except that it tries to merge [side] tags, so that you can still overwrite the contents of each [side] in the handwritten .cfg file, but still create units in the scenario editor.
  
> Do you think there are other use-cases for it?

Well, one usecase is enough. Its clearly a function that does a  basic config operation so it belongs in config.hpp and fits well along the existing append/inherit etc functions.

**Comment by CelticMinstrel** [comment]
> Its clearly a function that does a basic config operation

Well, this is precisely what I was questioning… 

Also, isn't it identical to the existing `merge_attributes`?

**Comment by gfgtdf** [comment]
We coudl improve the merging for exampy by also marking it merge the  [unit]s in each [side], correctly, but im not convonced that this actually better than makring people use something liek [modify_unit]+prestart events.

**Comment by gfgtdf** [comment]
> Also, isn't it identical to the existing merge_attributes?

no, inherit_attributes choose the already existent attributes over the new ones, but the existing functions config::append_attributes and config::merge_attributes do basicially the same thing.

**Comment by CelticMinstrel** [comment]
I think merging the units in each side would be more confusing than just appending them.

Also, did you miss my question just above?

**Comment by CelticMinstrel** [comment]
> no, inherit_attributes choose the already existent attributes over the new ones

Sure, but doesn't that just mean that `x.inherit_attributes(y)` is equivalent to `y.merge_attributes(x)`? Or maybe `append_attributes`.

**Comment by gfgtdf** [comment]
> Sure, but doesn't that just mean that x.inherit_attributes(y) is equivalent to y.merge_attributes(x)? Or maybe append_attributes.

No, these function all change the `this` object, not the passes config object

**Comment by CelticMinstrel** [comment]
> No, these function all change the `this` object, not the passes config object

I don't quite get how this makes them not equivalent? Whichever object ends up changed, the operation is the same, right? In fact, isn't `inherit_from` literally copy-merge-swap?

**Comment by gfgtdf** [comment]
> I don't quite get how this makes them not equivalent?

No, on both cases you end up with a config that has x values with y as fallback, but in one method you'll also end up with another config with x values and with the other method you'll end up with another config with y values. 


> In fact, isn't inherit_from literally copy-merge-swap?

So? Obviously merge is not the same as copy-merge-swap

**Comment by CelticMinstrel** [comment]
> No, on both cases you end up with a config that has x values with y as fallback, but in one method you'll also end up with another config with x values and with the other method you'll end up with another config with y values.

This means they _are_ equivalent if you first make a copy of the LHS config. So if nothing else, the `inherit_attributes` function should probably be implemented in terms of one of the other functions to reduce code duplication and reflect this equivalency.

**Comment by gfgtdf** [comment]
> So if nothing else, the inherit_attributes function should probably be implemented in terms of one of the other functions to reduce code duplication and reflect this equivalency.

I disagree, and I doubt your suggested implemtation would be noticable smaller or easier to read, but if you want you can do it.

**Pull request merged**
