### PR TITLE
fix build with musl libc

### PR DESCRIPTION
**Pull request by iFoundSilentHouse**
Wesnoth was unable to build with musl.
Error message: ```error: could not convert 'nullptr' from 'std::nullptr_t' to 'int'``` 
It was for strings 43, 44, 65.
I found the same error but with other program: https://github.com/dotnet/runtime/issues/67763
And after changing 'NULL' to '0' build was successful.

### CODE REVIEW

**Review by stevecotton — COMMENTED** [review]
There's a bug in the existing code - these `std::optional` arguments should default to `std::nullopt`. AFAICS, they're defaulting to values of zero instead. Going to have to read through #7923 and #7924 to work out exactly what they should do, how to expand the tests, and whether those arguments can change to just passing non-optional arguments instead.

Thanks for drawing attention to it, but as you can see from the length of discussion in #7924, it's not the easiest first issue to start with.

Having said that, the code in this PR may be a good change. I suspect the perfect fix will be to change the `NULL` to `0` but also remove the std::optional wrappers.

**Comment by iFoundSilentHouse** [comment]
> Having said that, the code in this PR may be a good change. I suspect the perfect fix will be to change the `NULL` to `0` but also remove the std::optional wrappers.
Well I can try removing them and build it again, then change it in PR. Should I?

**Comment by stevecotton** [comment]
Yes please. Sorry for the unclear previous message, still working out what to do.

**Comment by iFoundSilentHouse** [comment]
With this patch:
```shell
diff --git a/src/utils/config_filters.hpp b/src/utils/config_filters.hpp
index 878042a089e..a01a97f4db3 100644
--- a/src/utils/config_filters.hpp
+++ b/src/utils/config_filters.hpp
@@ -40,8 +40,8 @@ bool bool_matches_if_present(const config& filter, const config& cfg, const std:
  *
  * Always returns true if the filter puts no restriction on the value of @a cfg[@a attribute].
  */
-bool double_matches_if_present(const config& filter, const config& cfg, const std::string& attribute, std::optional<double> def = NULL);
-bool int_matches_if_present(const config& filter, const config& cfg, const std::string& attribute, std::optional<int> def = NULL);
+bool double_matches_if_present(const config& filter, const config& cfg, const std::string& attribute, double def = 0);
+bool int_matches_if_present(const config& filter, const config& cfg, const std::string& attribute, int def = 0);

 /**
  * Restricts filters to only looking for values that are zero or more.
@@ -62,7 +62,7 @@ bool unsigned_matches_if_present(const config& filter, const config& cfg, const
  * The function is named "negative" in case we later want to add a "reciprocal" for the "multiply"/"divide" pair.
  */
 bool int_matches_if_present_or_negative(
-       const config& filter, const config& cfg, const std::string& attribute, const std::string& opposite, std::optional<int> def = NULL);
+       const config& filter, const config& cfg, const std::string& attribute, const std::string& opposite, int def = 0);

 bool string_matches_if_present(
        const config& filter, const config& cfg, const std::string& attribute, const std::string& def);
```
Build fails

**Comment by iFoundSilentHouse** [comment]
ahh sorry. my fault

**Comment by iFoundSilentHouse** [comment]
> Yes please. Sorry for the unclear previous message, still working out what to do.

This patch builds fine and, as far as I can understand, it doesn't destroy logic behind ...matches_if_present... functions
```
diff --git a/src/utils/config_filters.cpp b/src/utils/config_filters.cpp
index f833acd7701..dba7a42c2ff 100644
--- a/src/utils/config_filters.cpp
+++ b/src/utils/config_filters.cpp
@@ -53,7 +53,7 @@ bool utils::config_filters::unsigned_matches_if_present(const config& filter, co
        return in_ranges<int>(cfg[attribute].to_int(0), utils::parse_ranges_unsigned(filter[attribute].str()));
 }

-bool utils::config_filters::int_matches_if_present(const config& filter, const config& cfg, const std::string& attribute, std::optional<int> def)
+bool utils::config_filters::int_matches_if_present(const config& filter, const config& cfg, const std::string& attribute, int def)
 {
        if(!filter.has_attribute(attribute)) {
                return true;
@@ -62,12 +62,11 @@ bool utils::config_filters::int_matches_if_present(const config& filter, const c
                return false;
        }

-       int value_def = def ? (*def) : 0;
-       return in_ranges<int>(cfg[attribute].to_int(value_def), utils::parse_ranges_int(filter[attribute].str()));
+       return in_ranges<int>(cfg[attribute].to_int(def), utils::parse_ranges_int(filter[attribute].str()));
 }

 bool utils::config_filters::int_matches_if_present_or_negative(
-       const config& filter, const config& cfg, const std::string& attribute, const std::string& opposite, std::optional<int> def)
+       const config& filter, const config& cfg, const std::string& attribute, const std::string& opposite, int def)
 {
        if(int_matches_if_present(filter, cfg, attribute, def)) {
                return true;
@@ -79,14 +78,13 @@ bool utils::config_filters::int_matches_if_present_or_negative(
                if(!cfg.has_attribute(opposite) && !def) {
                        return false;
                }
-               int value_def = def ? (*def) : 0;
-               return in_ranges<int>(-cfg[opposite].to_int(value_def), utils::parse_ranges_int(filter[attribute].str()));
+               return in_ranges<int>(-cfg[opposite].to_int(def), utils::parse_ranges_int(filter[attribute].str()));
        }

        return false;
 }

-bool utils::config_filters::double_matches_if_present(const config& filter, const config& cfg, const std::string& attribute, std::optional<double> def)
+bool utils::config_filters::double_matches_if_present(const config& filter, const config& cfg, const std::string& attribute, double def)
 {
        if(!filter.has_attribute(attribute)) {
                return true;
@@ -95,7 +93,7 @@ bool utils::config_filters::double_matches_if_present(const config& filter, cons
                return false;
        }

-       double value_def = def ? (*def) : 1;
+       double value_def = (def==0) ? 1 : (def);
        return in_ranges<double>(cfg[attribute].to_double(value_def), utils::parse_ranges_real(filter[attribute].str()));
 }

diff --git a/src/utils/config_filters.hpp b/src/utils/config_filters.hpp
index 878042a089e..a01a97f4db3 100644
--- a/src/utils/config_filters.hpp
+++ b/src/utils/config_filters.hpp
@@ -40,8 +40,8 @@ bool bool_matches_if_present(const config& filter, const config& cfg, const std:
  *
  * Always returns true if the filter puts no restriction on the value of @a cfg[@a attribute].
  */
-bool double_matches_if_present(const config& filter, const config& cfg, const std::string& attribute, std::optional<double> def = NULL);
-bool int_matches_if_present(const config& filter, const config& cfg, const std::string& attribute, std::optional<int> def = NULL);
+bool double_matches_if_present(const config& filter, const config& cfg, const std::string& attribute, double def = 0);
+bool int_matches_if_present(const config& filter, const config& cfg, const std::string& attribute, int def = 0);

 /**
  * Restricts filters to only looking for values that are zero or more.
@@ -62,7 +62,7 @@ bool unsigned_matches_if_present(const config& filter, const config& cfg, const
  * The function is named "negative" in case we later want to add a "reciprocal" for the "multiply"/"divide" pair.
  */
 bool int_matches_if_present_or_negative(
-       const config& filter, const config& cfg, const std::string& attribute, const std::string& opposite, std::optional<int> def = NULL);
+       const config& filter, const config& cfg, const std::string& attribute, const std::string& opposite, int def = 0);

 bool string_matches_if_present(
        const config& filter, const config& cfg, const std::string& attribute, const std::string& def);
```
Sorry if I'm wrong. And let me know if I am, plz.

**Comment by iFoundSilentHouse** [comment]
New edit is in last force commit. Now I'm sure about it.

**Comment by Pentarctagon** [comment]
Was this meant to be closed?

**Comment by iFoundSilentHouse** [comment]
NO SORRY

**Comment by iFoundSilentHouse** [comment]
Accidentally pushed empty commit

**Comment by iFoundSilentHouse** [comment]
Now build works and bug should no longer exist

**Comment by newfrenchy83** [comment]
> @newfrenchy83 would you review this PR please?

Not that I'm happy to revert to the optionality of the default, but if it actually triggers a compilation problem then I'll accept it.

**Comment by newfrenchy83** [comment]
@iFoundSilentHouse did you try compiling with std::nullopt instead of NULL, rather than forgoing std::optional?

**Comment by iFoundSilentHouse** [comment]
> @iFoundSilentHouse did you try compiling with std::nullopt instead of NULL, rather than forgoing std::optional?

No. I didn't.

**Comment by stevecotton** [comment]
@newfrenchy83 if NULL was always zero instead of being equivalent to nullopt, then I'm wondering if the optional things need to be optional at all.

**Comment by newfrenchy83** [comment]
> @newfrenchy83 if NULL was always zero instead of being equivalent to nullopt, then I'm wondering if the optional things need to be optional at all.

I had confused NULL with std::nullopt, hence the confusion, for me it is not a question of using NULLL as an equivalent of 0

**Comment by iFoundSilentHouse** [comment]
Closing this PR in favor of more accurate https://github.com/wesnoth/wesnoth/pull/8649

**Pull request closed without merging**
