### PR TITLE
ported wescamp and libgithub to python3

### PR DESCRIPTION
**Pull request by sevu**
However, there's still a problem left which didn't occur with python2:
calling wescamp -l would crash at [line 49.][link]
I's just a debug message and could be left out, but does someone have an idea why?

[link]:https://github.com/sevu/wesnoth/blob/a92eb2465c402c1f00f8bcc8ddf34eea5c19481b/data/tools/wesnoth/wescamp.py#L49

> Exception ignored in: <bound method tempdir.__del__ of <__main__.tempdir object at 0x7f72de2fcac8>>
> Traceback (most recent call last):
>   File "data/tools/wesnoth/wescamp.py", line 49, in __del__
> AttributeError: 'NoneType' object has no attribute 'debug'
>

### CODE REVIEW

**Comment by AI0867** [comment]
That's probably the object being destroyed *after* the logging object has already been destroyed.

You can either do the same thing as with shutil (see line 45), or wrap the crashing line in `if logging:`.

**Comment by sevu** [comment]
I wrapped it now in the _if logging_ but I guess it will just always be false. Also ran 2to3 with all fixers now.
I don't understand the part with shutil, it would probably be the better fix.

**Comment by AI0867** [comment]
The issue here is that as the program is ending, things are destroyed in an unspecified order. The only guarantee is that if there are no circular references, that if object A keeps a reference to object B, object B will be destroyed after object A. For obvious reasons, globals do not count as references.

The case with shutil is exactly like logging: The global does not count as a reference, so shutil may be destroyed before the destructor of tempdir is run, resulting in tempdir's destructor trying to dereference a global that has already been destroyed.

The solution is to bind the object referred to by the global to a property of the object that needs it (see line 45) and then use that reference in the destructor.

The fix I would suggest is the following:
Change line 45 to `self.shutil = shutil`
Add an extra line `self.logging = logging`

Change line 48 to `self.shutil.rmtree(self.path)
Change the logging-related lines after that to `self.logging.debug(…`

**Comment by sevu** [comment]
Thanks for you explanation, now I understand how this works :)

**Comment by Vultraz** [comment]
Is this done?

**Comment by sevu** [comment]
It is

**Pull request merged**
