### PR TITLE
Remove non-standard spacing (SoF's wyrms)

### PR DESCRIPTION
**Pull request by stevecotton**

### CODE REVIEW

**Review by knyghtmare — APPROVED** [review]
A lot of the mainline campaigns seem to be still undergoing wmllint changes. Otherwise these would have been fixed already.

**Comment by stevecotton** [comment]
When we cherry-pick these, we need (at least part of) 6e6d57d3656c03ff2ab96e179b1910b1ac545ca7 too.

> A lot of the mainline campaigns seem to be still undergoing wmllint changes. Otherwise these would have been fixed already.

Thanks for the heads-up. This change was easy to do, so I can postpone this until that's done.

**Comment by Wedge009** [comment]
Not sure how I missed back-porting 6e6d57d but that's done now. Thanks for spotting it.

Do we know when the wmllint changes will be done? Otherwise this could potentially be postponed indefinitely, it's such a small change after all.

**Review by Wedge009 — APPROVED** [review]

**Comment by stevecotton** [comment]
I've duplicated @max-torch's work here, he's already done this and more (removing the unnecessary word "basically") in #6177.

**Pull request closed without merging**
