### PR TITLE
Fixes #7992

### LINKED ISSUE #7992: [filter_ability] issues
https://github.com/wesnoth/wesnoth/blob/6b9a7627b90f90c0fc4f2065d19b179df4682280/src/utils/config_filters.cpp#L49-L51

Checks like this seem to be intended to test if an ability supports the attribute or not. This cannot be checked in these `*_matches_if_present` helper functions though since they have no idea what ability type they're checking.

For `value` there are some `tag_name` tests but `multiply` for example is checked regardless of what the `tag_name` is. Really the tests for `value` look wrong anyway since they also look at `cfg` as if it tells you what an ability supports.

So the logic in https://github.com/wesnoth/wesnoth/blob/6b9a7627b90f90c0fc4f2065d19b179df4682280/src/units/unit.cpp#L1424
must make sure to only call the `*_matches_if_present` helper functions on attributes the given `tag_name` actually supports. When checking an unsupported attribute the filter must fail to match.

Also all code that checks the given `cfg` for what an ability type supports must be removed since it is simply wrong.

### PR DESCRIPTION
**Pull request by Pentarctagon**
abilities.cpp changes taken from #9361 by newfrenchy

---

Removing the `cfg` checks from `config_filters.cpp` currently breaks the WML unit tests, so that still needs to be fixed. Supercedes #9361.

### CODE REVIEW

**Comment by newfrenchy83** [comment]
Why do you insist on removing the verification of the presence of the attribute? In the case of numeric attributes this allows to continue the verification when there is no default value defined, otherwise it returns a false value even if the attribute is present.

For the rest I agree but the verification of the presence of the attribute in the ability is just as important as that of its value.

**Comment by Pentarctagon** [comment]
It's what Soliton requested in the issue.

**Comment by newfrenchy83** [comment]
> It's what Soliton requested in the issue.

If it is prevent function to work properly, then i don't make only because @soliton- want this.

**Comment by Pentarctagon** [comment]
Well yeah, but I assume an explanation is needed for why it can't be removed.

**Comment by newfrenchy83** [comment]
> Well yeah, but I assume an explanation is needed for why it can't be removed.

add https://github.com/wesnoth/wesnoth/pull/9361/commits/51f90ad3b288027294385e1816d40a1a90fedfdc in my PR for explanation.

**Pull request closed without merging**
