### PR TITLE
Test PR

### PR DESCRIPTION
**Pull request by macabeus**
This PR is just for testing the `map-diff` action

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Okay, it looks like it functions, which is good, but… I can't see where the change is marked in that image…?

**Comment by macabeus** [comment]
@CelticMinstrel Nop, there is still an issue on the GitHub Action 😢 
It's comparing the map from the **base** with the **base**.
Probably by doing it can fix it:
```diff
- git show ${{ github.event.pull_request.base.sha }}:"$map_path" > "$map_filename"
+ git show ${{ github.event.pull_request.head.sha }}:"$map_path" > "$map_filename" 
```

I'll try to add a message if there is no visible change on the image, to avoid confusion like this one.

**Comment by macabeus** [comment]
@CelticMinstrel I just opened this PR fixing it: https://github.com/wesnoth/wesnoth/pull/6714

**Comment by CelticMinstrel** [comment]
I tried rerunning it here but I guess it doesn't merge master in when running the job, so I guess you'll have to rebase to verify that it works?

**Comment by Pentarctagon** [comment]
Can this be closed, or is there a reason for it to remain open?

**Pull request closed without merging**
