### PR TITLE
deleted unnecessary check

### PR DESCRIPTION
**Pull request by Welrub**
The problem in #7654 was that the preprocessor ignored files with an extension other than .cfg. Now it will preprocess all files

### CODE REVIEW

**Comment by soliton-** [comment]
The goal is not to change the preprocessor. We want to just change the preprocess command line option.

**Comment by soliton-** [comment]
https://github.com/wesnoth/wesnoth/blob/4a9acd6e06d82fe070d0ffd23311c0ea40785ca1/src/serialization/preprocessor.cpp#L1774
Presumably this check needs to be disabled but only when called by the preprocess option logic so probably needs a new argument for that.

**Comment by gfgtdf** [comment]
From how i read the code this should only be reached when iterting over a directory (`preprocessor_file::files_` is never filled unless `is_directory_` is true), so i don't understand yet how this can have an effect on handling a single file with the preprocess option.

**Comment by stevecotton** [comment]
Closing, replaced by #8080.

**Pull request closed without merging**
