### PR TITLE
[WIP] generalized sconce images - mostly ironing out mechaics at this point

### PR DESCRIPTION
**Pull request by doofus-01**
sconce_shot_009
I'm not terribly proud of the individual images, but I'm wondering if there are objections to the overall mechanics.  If moving the formulaic animations into the engine (rather than exporting the images as was done for the original torch-lit stone walls) isn't too expensive, that's probably better for future modifications and is more in the 'open source' spirit. 
EDIT: Attaching a screenshot

### CODE REVIEW

**Comment by Vultraz** [comment]
Looks pretty good to me!

**Comment by doofus-01** [comment]
Thanks, @Vultraz .  Let's see if @ln-zookeeper has any objections.  If all is well, I can probably get this cleaned up next week.

**Comment by doofus-01** [comment]
Added some torches, basically just sticks in the ground, for when the overlay isn't on a wall terrain. 
screenshot_torches2

**Comment by Vultraz** [comment]
Nice, nice :D Is this done now?

**Comment by doofus-01** [comment]
Almost, I am working on a few fix-ups right now.  Should this have illuminates halo and time-of-day shift, or should it just be a visual decoration?

**Comment by Vultraz** [comment]
That'd be nice, but I don't know if it's possible and it might be too much work.

**Comment by doofus-01** [comment]
The light-beam overlay `^Ii` can shift the time-of-day, I think.  Or at least it used to.

**Comment by Vultraz** [comment]
Oh, I misunderstood what you meant. Hmmm... probably should just stick to visual decoration.

**Comment by doofus-01** [comment]
I think this is done, or at least usable.

**Comment by CelticMinstrel** [comment]
If it's intended to be placed on the wall terrain, a time-of-day shift would have no effect anyway. (It would only have an effect if it's placed on a passable terrain.)

**Comment by Vultraz** [comment]
Manually squashed and pushed in 2a7947544856 with some indent fixes to the terrain graphics file.

**Pull request closed without merging**
