### PR TITLE
Remove heal+4 from Oracle and Prophet

### PR DESCRIPTION
**Pull request by rodolphecombe**
This PR is the result of discussions inside the WMG. 

Disclaimer: although this PR affect balance, this is not a balance PR, rather a coherence PR. While we also feel that the balance of the whole augur line needs to be adjusted, this would be the subject of a second PR. 

As you probably know, the saurian Augur is the only healer keeping heal+4 on his DPS branch. Although this could be seen as a feature of the line, we consider it is rather an incoherence with respect to the other healer lines. 

The main proposition of this PR is therefore to remove heal+4 from the Oracle and Prophet. 

Following this main proposition, we are making the following additional propositions: 
1.	Add a special to the ranged attack of the Oracle and Prophet to help distinguish them more from the Soothsayer line. 
2.	Give a new special called curse to the “curse” attack of the Oracle and Prophet (“slow” would make them too similar to elvish line, “daze” would not synergize well with being use on an attack with magical, “stun” would not synergize well with the skirmisher line, “drain” and “poison” would not really make sense here). 
3.	Curse special reduce: 
a.	Physical and elemental resistances (not arcane until the position on arcane rework is clarified) 
b.	By 20% 
c.	Until turn end (same duration as “slow”) 
4.	Rename the attack of Augur, Soothsayer and Seer to “Frost Blast” 

All these propositions are of course open to discussing and most of them can be treated independently. The values of 3) are what we found worked best but other combinations are equally good (for example, reducing duration to “turn” has little to no influence in 1vs1).

### CODE REVIEW

**Comment by ForestDragon-wesnoth** [comment]
"on behalf of the WMG" seems a bit misleading in my opinion - the fact that it is an idea discussed in one of the chats on the server does not meant it officially represents the server.

**Comment by rodolphecombe** [comment]
> "on behalf of the WMG" seems a bit misleading in my opinion - the fact that it is an idea discussed in one of the chats on the server does not mean it officially represents the server.

It officially represents the people that contributed to the discussion on the server. This very text was even approved (or at least not disapproved) in the discussion.  
But I understand if you think this is misleading. Can you please propose a better formulation?

**Comment by ForestDragon-wesnoth** [comment]
I think something like "This PR is made after some discussion in WMG." could work

**Comment by rodolphecombe** [comment]
> I think something like "This PR is made after some discussion in WMG." could be better formulation

Edited. Is it fine like that ?

**Comment by Dalas121** [comment]
Wow! I knew there was some talk about the Oracle and Prophet, but I had no idea things had progressed this far. I can see that an impressive amount of work has gone into this PR.

This PR touches on a lot of different questions, so I want to give my opinion on each separately:

1) I oppose removing heal+4 from the Oracle and Prophet. Removing heal+4 has a bigger effect on existing content than does adding Curse or Daze. Also, in my opinion heal+4 is a much better-designed ability than heal+8. I don't see heal+4 as an inconsistency.

2) I support adding a new status effect to core. Wesnoth often gains new specials and abilities, and adding a new debuff provides interesting ways to design units. I think the Oracle/Prophet is a great place to do this.

3) I'd prefer adding Daze instead of Curse - IMO Daze's lack of synergy with Magical is a good thing that encourages mixed armies, and maininling Daze would help better-support UtBS, TDG, and other campaigns that use it. We also don't have great UI for single-unit resistance changes, but we do for defense and CTH.

Since this is more or less a "balance change", I believe that it would require a balance team vote to merge? I've given my opinion, but if the other team members think differently they can always out-vote me.

**Comment by Hejnewar** [comment]
@Dalas121 One thing Daze not only affects dodge but also affects accuracy of affected enemy unit. Which iirc is markers as accuracy penalty currently.

Other than that this is definitely stronger than healing, it is at least twice as good. Probably more since it is on magical attack (way higher cth), that also will increase damage dealt by Oracle if one hit hits for each subsequent hit which is a major thing. Daze or slow is on a weak attack usually. 

And that is for a unit that I personally consider to be the best in the game (saurian augur). 

Making it weaker to 10% will quickly turn into pointing out all the units that can't use this bonus (and will still be stronger than healing). 

Daze is also more than two times stronger than healing even without all the interactions in this case. 

I'm not opposed to this really, this is just my balance review.

**Comment by Roge-Tebnelok** [comment]
I agree with Dalas except on daze, and want to provide some clarification on the idea of curse. 
Before the discussion went towards removing heals, it was about restoring the balance between Oracle and Soothsayer, since in 1.18 the latter became better than the former in everything except ranged damage, and the difference is not significant enough to justify choosing the first advancement over the second in the most situations. We came up with an increase in the ranged damage of the Oracle/Prophet and similarization of the melee with the Soothsayer/Seer, as well as small changes in health, price and set aside for the future PR along with the unresolved issue of movement.
After some time, Rodolphcombe asked what could replace the Oracle's heals, among the options were an additional increase in damage, existing weapon specials, including daze, but the most popular was other that became a resistance reducing status effect, which we agreed on and proceeded to how it should work. Hypothetically, this should be enough to leave Oracle's ranged damage unchanged, as it is now.
Daze was rejected not only due to lack of synergy with magical, but also because drakes and saurians, with their high hits and terrain defense, which a 10% increase changes little, have fewer problems with accuracy and evasion than other factions. They rarely cooperate, most often each race is on its own, which does not allow frequent synergy between them in single-player campaigns, in multiplayer more often, but not sure how much, and the fight is often waged on different fronts, which also does not facilitate one side's use of the effects provided by another. Being a luck-based ability also doesn't help it. Finally, it does not fit well with the name of the attack and the description of the unit line flavorwise. Though, because of this an idea of renaming the attack to not be the same as weapon special to came into consideration, I personally don't like it, another way around is more preferable, in fact, I'm searching for another name for the special, so far I have "hex" and "wastage".
Anyway, I think it's too early to discuss this until arcane resistance issue is resolved.

**Comment by kameramen0106** [comment]
I cannot support removing heal+4 from them. I think this change will have non-negligible impact gameplay-wise. Additionally, in my opinion, I do not see any inconsistency with the other healer lines in the current Oracle/Prophet. Rather, I think heal+4 throughout levels is an excellent feature of this line.

In other regards, I basically agree with the comment by Roge.

I am also aware that this discussion on WMG took place in one chat and with fairly small numbers of people. I do not think this PR represents the collective opinion of many people on the server.

**Comment by Mirion147** [comment]
The opportunity to discuss opinions was open to all, as no one expressed dissent, there was no reason to assume anyone disagreed. The conversation has been going on for some time. So to say a majority of people don't agree with this PR seems overly negative. As of yet, I think maybe 1 person said they were against the changes.

More on topic. I argued heavily in favor of keeping heal +4 on the oracle line. I think it adds flavor to the saurians and helps them maintain health pools with drakes who are pin cushions. They take a lot of damage while fighting and heal on both lines of the augur really helps them maintain their lines.

That being said, there's definitely something missing from the oracle line, especially if we aren't discussing the buffs that were the initial point of conversation. I think that having "Curse" be a new status effect brings a lot to the game, and to the drake faction. Reducing resists is very strong for units with multiple strikes, a much greater chance of utilizing the ability. 

Curse fits thematically where just a cold damage attack doesn't at all. Additionally, it brings a new strategy to the game. My personal thought was to have the duration of curse be only for the turn it was applied. This wouldn't allow allies to take advantage  of the ability, but it means that it can be more impactful for the turn it is applied. 

Daze is too strong imo, oracle would need to be heavily nerfed in order to be able to apply that much dissonance into the field. Slows is also too strong, it has to be something different, and with the name "Curse" being our starting block, it makes sense that we're putting a Curse on the physical body. Which is also why I suggested this not impact arcane resistance.

I think that with this being added to the oracle line, it is fair to remove heal, even though I do think it's good and adds to the faction, i think that Curse is worth switching it out. I think that it brings a lot more lore into play, it gives saurians their own unique flavor (not cooking, don't freak out Refumee lol), while also giving drakes a bit of help so that they don't lose as much hp, compensating for the reduction in healing capabilities. I think the best way to achieve the trade off is to have the ability stay as turn duration, with a higher influence%.

**Comment by Discontinuum** [comment]
First of all, the disclaimer remark "although this PR affect balance, this is not a balance PR, rather a coherence PR" looks weird as this PR exactly does a big balance change.

I'm against changing the Oracle. Removing heals +4 doesn't make sense for me: the unit isn't broken and I don't find any benefit in this kind of consistency.

Regarding the curse, the thing is that Drake is the faction of huge damage. Their units do a lot of damage and their level-ups are especially deadly. Adding resistance-lowering to them, in combination with their already high damage, buffs drakes incredibly and makes a pretty op combo.

Overall, I don't really think Soothsayer/Oracle choice was broken, both units were picked and used. And this is a pretty big change of a good thing without any clear benefits.

**Comment by rodolphecombe** [comment]
For me the PR was more about removing heal+4 but if we don't and still add the special, either the special or the units indeed need to be nerfed. 

As was said, Drake faction is the faction of huge damages so I am not sure decreasing the buff to 15% or even 10% would be a problem. 
The status can also be applied in attack_end rather than attacker/defender_hits although I think it would definitely feels weird in-game to me.

I can easily modify the PR in any of the directions mentioned in the comments.

**Comment by MechanicalDragon963** [comment]
The motivation for this PR seems to me to be insufficiently justified. Oracle is not just a normal unit - it's an important unit for the MP environment, as it is both an available leader and a key advancement in some matchups (e.g. against Loyalists) according to some mp experts. 

I believe that risking a huge layer of SP content and MP balance for the sake of some abstract “consistency” is not rational, therefore, I am not in favor of the proposed changes.

**Comment by Mirion147** [comment]
> The motivation for this PR seems to me to be insufficiently justified. Oracle is not just a normal unit - it's an important unit for the MP environment, as it is both an available leader and a key advancement in some matchups (e.g. against Loyalists) according to some mp experts. 
> 
> I believe that risking a huge layer of SP content and MP balance for the sake of some abstract “consistency” is not rational, therefore, I am not in favor of the proposed changes. 

What do you consider the justification for PR? This PR impacts far less than many of the other PR's that are currently circulating. Note that you are against the changes and be done with it. You have no ground to stand on with the claims you've made. 

The purpose of this PR is simply about removing heal +4 from the oracle line. This unit line has already been changed from its 1.18 status by adding a level 3 option, this is the best time to adjust anything and give identity to the augur lines. For the purpose of this PR in regards to the oracle line, there were options on how to maintain the strength of the line, increase lore accuracy, and, as one of the options, head in the direction of adding new abilities to mainline as has been desired by many.

**Comment by rodolphecombe** [comment]
Can you please tell explain something to me, because as I never play multiplayer it seems that there is something I missed with this PR?
Is heal+4 that defining of the Oracle? I thought it was supposed to be a DPS unit. Is it actually used for support?
I thought you would go for Sooth of you need a healer and Oracle if you want ranged magical DPS. 
Otherwise, I have trouble seeing how removing heal+4 would have that huge an impact that everyone commenting of against it. 
It's just that I never saw anyone complaining that the sorceress was losing heal+4 and I though the shaman was quite similar to the augur. 
Please note I have nothing against those comments, I really am just trying to understand the matter as it was the main point of the PR

**Comment by Discontinuum** [comment]
The thing is that Oracle works well in his current form. It's a DPS unit, with handy heals +4 that heals a bit and stops poison. He doesn't work like Elvish Sorceress and it doesn't have to.

> Because if heal+4 is not removed, adding a special would make the unit OP, and, if it is not added, adding a special to core without having a unit using it makes little sense to me and the PR should therefore be closed

And that's exactly the problem with this PR, it adds a new weapon special just for the sake of adding a new weapon special, and it adds it to a unit that is already well defined and employed. As a result it creates more problems and doesn't really achieve anything tangible. So yeah, I believe this PR indeed should be closed

**Comment by Tezereth** [comment]
It's pretty hard to support a PR that just doesn't get oracle at all
This change, for a starter, completely change the role of oracle from a damage dealer with a bit of support, to a pure debuffer. And there's a few problems with that already I will get to later. Essentially, you're turning the unit into something entirely different, erasing it's role and replacing it.

Second, the debuff in question isn't relevant to drakes as a faction. As said before by [Discontinuum](https://github.com/Discontinuum), the drakes are a faction of large damage, so weakening the oracle both make it fits less the theme despite being the damaging branch of the augur, but it also allows drakes, especially high levels, to deal too much damage. If the ability was reduced to only 10%, then it would become too low and barely relevant, so it wouldn't be worth having either.

Removing +4 heal basically removes one of the main unique points of the oracle, while adding curse will certainly lead to reducing it's cold damage, which is the main job of the oracle.

**Comment by ForestDragon-wesnoth** [comment]
As others pointed, I also think that drakes were a faction that never had problems inflicting damage - they have expensive but above-average DPS units, often having 48 total damage on lvl3 attacks (8x6 inferno, 16x3 blademaster and warden), and they have access to leadership to buff their lvl1-2s with Flare/Flameheart. Slapping an extra damage-boosting ability on top of all that seems pointless.

**Comment by rodolphecombe** [comment]
Thank you for the explanation.
I therefore close the PR.

**Pull request closed without merging**
