### PR TITLE
Add a new attribute that checks calls special_bool for weapon specials abilities were filtered like weapon specials

### PR DESCRIPTION
**Pull request by newfrenchy83**
This PR resolves https://github.com/wesnoth/wesnoth/issues/4840 by adding two new attributes to [filter_weapon] for special weapons implemented in [abilities] is also filtered.

### CODE REVIEW

**Comment by gfgtdf** [comment]
honestly i'd rather wait until we are sure how we want the api to look like the end, probabnly also for some usecases

**Comment by newfrenchy83** [comment]
@gfgtdf Whatever the option used to solve this problem, it goes through the get_special_ability_bool function, however I would like to point out that only special_ (tags_id) _active should be emulated with a new attribute or using the existing attributes, emulate special_id _type no active generate new problems so I leave you there reflect.

**Comment by gfgtdf** [comment]
As I said before if like to wait untill we have a good usecase for this before actually merging this, which can be a very long time it even never so I really suggest that you spend your time on other things for now.

**Comment by newfrenchy83** [comment]
@gfgtdf you find in this file a possible usecase
[abilities_weapons.cfg.txt](https://github.com/wesnoth/wesnoth/files/4706195/abilities_weapons.cfg.txt)
in this case, it is more useful to use new_attribute what extent special_(id type)_active to abilities used like special for what leading anim don't called if weapon specials to same id what abilites filtered.

**Comment by newfrenchy83** [comment]
@gfgtdf i find bugs who make new attribute unusable, or affect abilites, i will close this PR, at least.

**Comment by newfrenchy83** [comment]
@gfgtdf i repair leading_anim don't filter ability_special_id/type_active in udisplay.

**Pull request closed without merging**
