### PR TITLE
Overlay deprecated terrains in the editor with a magenta "D"

### LINKED ISSUE #4354: Make deprecated terrains visible in the editor
Some of the deprecated terrains look similar to their replacements, for example the stone walls with sconces (`Xol` vs `Xos^Efs`) or the mushrooms (`^Uf` vs `^Tf`). This is a feature request to make the deprecated terrains easily visible in the editor.

There's already support for editor-only overlays in terrain-graphics.cfg, and there are very few terrains that are hidden in the editor (`hidden=yes` in terrain.cfg) so handcoding overlays for each one seems a reasonable task.

Related ticket: #4340 to detect these terrains with wmllint.

### PR DESCRIPTION
**Pull request by stevecotton**
Fixes #4354. Some of the deprecated terrains look similar to their replacements, for example the stone walls with sconces (Xol vs Xos^Efs) or the mushrooms (^Uf vs ^Tf). This is a feature to make the deprecated terrains easily visible in the editor.

The image is a fully opaque letter, but leaving many completely transparent pixels to see the underlying hex. When replacing the old mushroom overlay, it's helpful to be able to easily recognise the base terrain.

optipng has been run.

Sample image, showing mushrooms and two `Xol`, one of them with an impassible overlay on top:
wesnoth_d_for_deprecated

### CODE REVIEW

**Comment by jostephd** [comment]
I wonder... :thinking: Should there be a checkbox or menu item or something to temporarily disable these? I can see how they might get in the way of opening an old map to make a few tweaks.

**Comment by stevecotton** [comment]
> I wonder... thinking Should there be a checkbox or menu item or something to temporarily disable these? I can see how they might get in the way of opening an old map to make a few tweaks.

That might need a different implementation, probably in display.cpp as with the `show_coordinates`, `show_num_of_bitmaps` and `show_terrain_codes` implementations. I agree that it's probably worth doing, and would have the nice side effect of being able to add a `show_deprecated_terrains` to use  in-game as well as in the editor.

**Comment by Pentarctagon** [comment]
Is the deprecated terrain indicator drawn above or below other toggleable information (coordinates, terrain codes, etc)?

**Comment by stevecotton** [comment]
The current non-toggleable implementation puts them underneath all of the toggleable information.

**Comment by Pentarctagon** [comment]
I'm good with it then, as long as any preference to turn this off doesn't do so permanently.  The point of deprecating something is to have people know they shouldn't be using it, and if they can just turn off the warning and forget about it, that defeats the purpose.

**Comment by stevecotton** [comment]
So ... should I merge as-is, or should I add the toggling feature?

I'm slightly in favour of merging as-is.

**Comment by jostephd** [comment]
Sure, go ahead and merge. Even without the toggle, the value outweighs the potential inconvenience. And we can always add a (non-permanent, as Pent said) toggle later if we want to.

**Comment by sevu** [comment]
In any case, it's a great idea to use that functionality for highlighting it.

**Pull request merged**
