### PR TITLE
Removed Registered Users Only game config option (resolves #4980)

### LINKED ISSUE #4980: "Registered Users Only" checkbox is checked with no option to clear it on lan servers with no user registration mechanism
### Game and System Information
 - What version of the game are you running? 
1.14.13

 - Where did you download it from? (Steam, Mac App Store, our website, built from source, etc.)
website for mac, flatpack for linux

 - If you're using a custom build, what compiler did you use, and what commit did you build at?
not custom

 - What OS are you running?
linux and mac

### Describe the bug
When hosting a lan server on linux box, the linux and mac clients are not able to uncheck the "Registered Users Only" option. Even though the server does not support registered users

### To Reproduce
1. From a mac or linux client, log into the official servers and create a game with the option "Registered Users Only" checked.
2. leave the game
3. log out
4. Start a locally hosted lan server
5. log into the local lan server from mac or linux client
6. Creating a game will have the  "Registered Users Only" checkbox checked on by default, with no way to uncheck it.

### Expected behavior
If the client is connecting to a local lan server that does not support registered users, the "Registered Users Only" checkbox should not be checked by default, even if the last game created by the client had the option turned on.

### PR DESCRIPTION
**Pull request by Vultraz**
Closes #4980. As @Pentarctagon suggested. Opening a PR to confirm removing that bit from wesnothd is ok.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
I don't think this feature should be removed. Hiding it if the server requires it by default is a good idea, sure, but I don't like removing it altogether.

**Comment by Pentarctagon** [comment]
@CelticMinstrel Why should the feature be kept, then?

**Comment by Pentarctagon** [comment]
(Also, Soliton is the wesnothd maintainer)

**Comment by soliton-** [comment]
I don't think the option is particularly useful anymore. We're unlikely to go back to a mixed registration setup on wesnoth.org and other servers are unlikely to have a mixed registration setup to begin with.

**Review by soliton- — APPROVED** [review]

**Comment by CelticMinstrel** [comment]
> Why should the feature be kept, then?

Because the official server is not the only server. Removing an option because the official server doesn't need it is silly. While it's true that _most_ unofficial servers would probably be small affairs not requiring registration, who are we to constrain that possibility? The forum registration handler is part of the Wesnoth source code after all; anyone could use it if they wanted to.

**Comment by Pentarctagon** [comment]
If the only reason to keep a feature is that there's a near, but not quite, 0% chance it's still useful, then I don't consider that to be a strong argument for keeping something that's actively causing a problem for users we do actually know about.

**Pull request merged**
