### PR TITLE
EI - urbanjungle clean-ups

### LINKED ISSUE #8497: Terrain causes image recolour code errors in console in certain EI scenarios
Certain EI scenarios make use of the campaign-specific Urban terrain for their maps. When the player hovers the mouse on tiles using that terrain, the game prints out errors in the console pertaining to the team colour/image recolouring system.

```
20240305 00:39:26 error display: caught config::error while processing color-range RC: Invalid colour in range: urbanjungleA
20240305 00:39:26 error display: bailing out from RC
20240305 00:39:26 error display: caught config::error while processing color-range RC: Invalid colour in range: urbanjungleC
20240305 00:39:26 error display: bailing out from RC
```

There doesn't seem to be any meaningful impact of this in gameplay. In fact I'm not entirely sure why the recolour engine is invoked here — perhaps it has something to do with the sidebar icon in the map coordinate area?

### PR DESCRIPTION
**Pull request by doofus-01**
Cleans up the help browser and fixes #8497 (and makes the icon no longer pink).

I'm not sure I like this terrain idea, villages that aren't villages but use the village graphics.  As long as it stays in EI though, I guess it can be OK.

### CODE REVIEW

**Review by Dalas121 — APPROVED** [review]
Thanks for addressing this. I don't understand the terrain system well enough to critique the exact changes, so I'll trust that everything works properly.

> I'm not sure I like this terrain idea, villages that aren't villages but use the village graphics. As long as it stays in EI though, I guess it can be OK.

I had been planning on using similar terrain in TDG (for a cutscene) and HttT (for a couple scenarios).  Is the concern that these might be too easy to confuse with proper villages?

**Comment by stevecotton** [comment]
Remember to squash before merging (I've just made that mistake on a different PR).

This looks ready to merge, is it waiting for anything?

**Comment by soliton-** [comment]
> I had been planning on using similar terrain in TDG (for a cutscene) and HttT (for a couple scenarios). Is the concern that these might be too easy to confuse with proper villages?

To me it's weird to have this terrain work like mountains movement wise. If movement worked as in villages that'd make more sense. Still certainly a terrain that looks like a village and behaves like one but not really is a bit confusing. Though the description does mention no income and healing at least.

As I said in the issue to me it seems like this is supposed to be a new archetype terrain (which it technically is now).

**Comment by Dalas121** [comment]
mission17-cropped

I created the "urban jungle" terrain to achieve 2 goals: 1) to fill a large urban area without providing huge income/healing, and 2) to make the map's movement/defense less homogenous.  In a real city, for example, it's much slower to move soldiers through buildings than down an open road.

In EI at least, I think they're clearly differentiated from true villages because of their different size and different colors.  Open to suggestions on both the art and mechanics front.

**Comment by soliton-** [comment]
But why movement like in mountains? Why are units fast in mountains fast in a city?

**Comment by knyghtmare** [comment]
> But why movement like in mountains? Why are units fast in mountains fast in a city?

At this point, I would suggest that there be a new terrain type called cityscape and then have `terrain_defaults` in the campaign for it.
Because I expect city hexes to not allow fluid movement for units with mountain mp cost set as 1 (drakes/dwarves/flyers)

**Comment by Dalas121** [comment]
> But why movement like in mountains? Why are units fast in mountains fast in a city?

Mountain was the closest equivalent I could find.  Not ideal, but in EI the player's units are mostly loyalist, so mountains provided a good barrier.

Flying units and dwarves move fast in everything, so I didn't feel it was an issue for them to move fast through urban terrain as well.

> At this point, I would suggest that there be a new terrain type called cityscape and then have terrain_defaults in the campaign for it.

I don't know the technical side of adding a new default terrain, but it sounds like using it would be convenient for UMC authors.

**Comment by soliton-** [comment]
The new archetype terrain is called urbanjungle added in this PR. So far it's just loaded with EI and the only terrains aliasing to it (urbanjungleA, ...) override movement and defense properties.

**Comment by doofus-01** [comment]
> I had been planning on using similar terrain in TDG (for a cutscene) and HttT (for a couple scenarios). Is the concern that these might be too easy to confuse with proper villages?

Yeah, that's basically it.  I did try this out in EI, and while there are tells if you are paying close attention, it's really easy to get faked out by a decoy village.  I get what the purpose is, but recycling village images seems bad.  

Different-yet-similar images would be a _little_ better, but not much.  Using smaller buildings might work, sort of like the castle towers, but that would really put a neon sign on our terrain scale inconsistencies.  There's probably some way to do this, but it's not immediately obvious to me.  If this were a wall-type terrain graphic (not necessarily impassible terrain type), it might be more clear? 

If it stays as campaign-only, there's more freedom in how to distinguish the terrain from a village (flag-pole overlays or something).  But folks don't like leaving things campaign-only, especially if in more than one campaign.

**Pull request merged**
