### PR TITLE
Fix Ambush Ability Does not Work in Bluff/Glutch Forest Terrain

### PR DESCRIPTION
**Pull request by newfrenchy83**
Resolve https://github.com/wesnoth/wesnoth/issues/8512 issue

### CODE REVIEW

**Comment by Pentarctagon** [comment]
It would be good to have a code comment explaining what the Q terrains are.

**Comment by newfrenchy83** [comment]
> It would be good to have a code comment explaining what the Q terrains are.

comment added

**Comment by CelticMinstrel** [comment]
Although this is technically "fine", I don't like it. If possible, the bug should be fixed by adjusting the definition of the bluff/gulch terrain, not by adjusting the definition of the ambush ability.

**Comment by Pentarctagon** [comment]
Well, for 1.18 it's going in like this, and no reason to not keep master in sync with it. No idea how you'd check for a specific terrain without the terrain codes though.

**Comment by soliton-** [comment]
The natural way to test for forest terrain would be to check for terrain aliased (aliasof; perhaps also mvt/def_alias) to forest (Ft). Since that is why the terrain behaves like forest. Not because it got a string assigned that matches some pattern. That is a convention put on top.

**Pull request merged**
