### PR TITLE
Don't interrupt the event after a WML error

### PR DESCRIPTION
**Pull request by CelticMinstrel**
People have been complaining recently about how events are interrupted if a Lua error occurs, leaving the game in an unexpected state. This patch works around that by calling WML tags in a protected context, allowing the game to continue executing the event even if a single tag fails. While it would still be possible to end up in an unexpected state (for example if a tag was misspelled or a variable is missing in insert_tag), this should at least greatly reduce the chances.

Of course, this also risks the game trying to execute things that depended on earlier things that were skipped due to an error, but... that's probably less undesirable than wholesale dropping the event.

~~I'm not sure whether this should go into 1.14 (but I've opened the PR against 1.14 because that's where I worked it out). If it's decided to put it only in master, this will have to be merged (or rather, cherry-picked) manually.~~

### CODE REVIEW

**Comment by jyrkive** [comment]
I definitely don't want to see a change this drastic in the 1.14 branch.

**Comment by CelticMinstrel** [comment]
Of the seven branches I just force-pushed, this is probably the only one that is definitely in a mergeable state, so if this change is desirable, feel free to merge anytime.

**Comment by gfgtdf** [comment]
even when the the error no longer interrupts the event, you should still print a clearly user visible message that an error occuraed and that this game will likeley have problems later have bugs later on.

**Comment by stevecotton** [comment]
Added to the tasks that will need to be in in time for the string-freeze.
I feel errors that stop events are going to be easier to debug, so I'm not in favour of this change.

**Comment by Pentarctagon** [comment]
@gfgtdf @CelticMinstrel thoughts on merging this?

**Comment by CelticMinstrel** [comment]
I have no plans to work on this. Even if I get back to Wesnoth coding in the next month or two, I'll be focusing on other things. I think the idea of this PR is a good one but I'm not entirely sure if this is the best approach.

**Comment by Pentarctagon** [comment]
Alright, I'm going to close this for now then.  If you do decide to work on this again though, feel free to reopen it.

**Pull request closed without merging**
