### PR TITLE
 Make Dune Burner line naphtha icons consistent and remove outdated comment

### LINKED ISSUE #2974: outdated comment in scorcher file?
https://github.com/wesnoth/wesnoth/blob/ae5ab22b1a1652aa22cc53077cc32967c45a8d64/data/core/units/dunefolk/Scorcher.cfg#L3

### PR DESCRIPTION
**Pull request by joeylmaalouf**
Fixes #2974 as well as a TODO that I noticed in the same file.

### CODE REVIEW

**Comment by CelticMinstrel** [comment]
Isn't torch the same icon used for the goblin pillager for example? I think the purpose of the TODO here was to note "we need a _new_ icon"; and given that they're basically using a flamethrower, a fire icon is probably more appropriate than a fireball. (Maybe the drake breath icon would work, provided it's pure flame without the drake's mouth?)

**Comment by joeylmaalouf** [comment]
Oh, sure. I just assumed torch was right because that's what the Burner had (whereas the Scorcher and Firetrooper had fireball), and the Burner had no TODO comment while the other two did.
The drake breath icon does have the drake mouth in it, but the fire blast icon would probably work.

**Comment by Pentarctagon** [comment]
The fireblast icon looks fine to me.  @CelticMinstrel Thoughts?

**Comment by CelticMinstrel** [comment]
Yeah, fire blast looks appropriate for this.

**Pull request merged**
